default:
	: 
install:
	mkdir -p ../../../Filesets.sl/CMDS-MIN/etc/newconfig
	! cp d.login ../../../Filesets.sl/CMDS-MIN/etc/newconfig/d.login
	! chmog 444 bin bin ../../../Filesets.sl/CMDS-MIN/etc/newconfig/d.login
	! chmog 555 bin bin ../../../Filesets.sl/CMDS-MIN/etc/newconfig
	! chmog 555 bin bin ../../../Filesets.sl/CMDS-MIN/etc
	! chmog 555 bin bin ../../../Filesets.sl/CMDS-MIN/
	! chmog 555 bin bin ../../../Filesets.sl/
