$set 1
1 %4h %2d %H:%M 19%y
2 ar: Fehlerhafte Auswahl `%c'\n
3 ar: Ein Wert aus [%s] muŞ angegeben werden\n
4 ar: AusschlieŞlich Werte aus [%s] sind zugelassen\n
5 ar: Úffnen von %s nicht mÎglich\n
6 ar: %s kann nicht erstellt werden\n
7 ar: Dritte temporÌre Datei kann nicht erstellt werden\n
8 ar: abi nicht zugelassen bei Angabe von q\n
9 ar: %s kann nicht geÎffnet werden\n
10 ar: TemporÌre Datei kann nicht erstellt werden\n
11 ar: %s nicht im Archivformat\n
12 ar: %s Positionierung nicht mÎglich\n
13 ar: Erstelle %s\n
14 ar: Es ist nicht mÎglich, %s zu erstellen\n
15 ar: %s hat kein Archivformat\n
16 Syntax: ar [%s][%s] [Posname] Archivdateien ...\n
17 ar: %s existiert nicht\n
18 ar: %s nicht gefunden\n
19 ar: %s kann nicht geÎffnet werden\n
20 ar: Erstelle %s\n
21 ar: %s kann nicht erstellt werden\n
22 Optionale acl-EintrÌge fÏr %s nicht archiviert\n
23 ar: Fehler bei der Erzeugung des internen Dateikopfes von %s\n
24 ar: Fehlerhafte Archivierung (%ld)\n
25 ar: %s fehlerhafter Header-Aufbau fÏr %s\n
26 ar: Zweite TemporÌrdatei kann nicht erstellt werden\n
27 ar: Zugriffsproblem bei %s\n
28 ar: Schreibfehler
