$set 1
1 Da Sie nicht im Verzeichnis /bin/sh arbeiten, kÎnnen Sie at nicht verwenden
2 Warnung: Befehle werden unter Verwendung von /bin/sh ausgefÏhrt\n
3 Verzeichnis kann nicht nach at geÌndert werden
4 Kann die EigentÏmer-Kennung des Jobs nicht in Ihre Kennung Ìndern
5 Job kann nicht erstellt werden
6 Sie sind kein berechtigter Benutzer (kein Eintrag in /etc/passwd)
7 Korrekte Syntax:\n\tat -ln\nwobei n eine ganze Zahl ist
8 at-Verzeichnis kann nicht gelesen werden
9 Sie sind nicht berechtigt, at zu verwenden. 
10 Es wurde nichts angegeben
11 Diese Zeit ist bereits Ïberschritten 
12 %s existiert nicht\n
13 Sie sind nicht der EigentÏmer von %s\n
14 UngÏltiger Jobname %s\n
15 %s existiert nicht\n
16 Sie sind nicht der EigentÏmer von %s\n
17 '%s' konnte nicht erÎffnet werden, errno=%d\n
18 zu spÌt
19 At: Dieser Job kann nicht zur richtigen Zeit ausgefÏhrt werden\n
20 Warteschlange voll
21 Kein Prototyp
22 cron kann nicht ausgefÏhrt werden - Informieren Sie den Systemverwalter\n
23 Fehler beim Úffnen der Meldungswarteschlange\n
24 Fehler beim Senden von Meldungen\n
25 Kann c-Warteschlange nicht benutzen
26 Syntax:\nat [-m][-f Datei][-qQueue] Zeit [Datum][[next| +Schritt] Zeitbezeichnung] Job\nat -r Job ...\nat -l [Job ...]\n
28 \'%s\' kann nicht erÎffnet werden\n
29 Pipe zum Versenden kann nicht erÎffnet werden\n
30 At: Job %s zum Zeitpunkt %.44s\n
32 Benutzer = %s\t%s\t%s\n
$set 2
1 Es ist nicht mÎglich, %d Byte zu belegen\n
$set 3
1 Mittag
2 Mitternacht
3 Jetzt
4 Heute
5 Morgen
6 Minute
7 Minuten
8 Stunde
9 Stunden
10 Tag
11 Tage
12 Woche
13 Wochen
14 Monat
15 Monate
16 Jahr
17 Jahre
18 nÌchste(n/s/r)
21 falsche Datumsangabe
22 falsche Zeitangabe
23 Stundenangabe ist falsch
24 falsches Datum
25 falsche Uhrzeit
26 falsche NLS-Umgebung
27 Datumsangabe ist nicht eindeutig
28 falsche Katalogdatei
