$set 1
1 Ausschlieﬁlich -F oder -f zugelassen\n
2 Ausschlieﬁlich -F oder -f zugelassen\n
3 Ausschlieﬁlich -P oder -p zugelassen\n
4 Ausschlieﬁlich -P oder -p zugelassen\n
5 mark_ev(%d) nicht erfolgreich\n
6 '%c': Ereignisparamenter fehlt\n
7 Unbekanntes Ereignis: %s\n
8 mark_ev(%d) nicht erfolgreich\n
9 mark_sc(%d) nicht erfolgreich\n
10 '%c': syscall-Parameter fehlt\n
11 Unbekannter Systemaufruf: %s\n
12 mark_sc(%d) nicht erfolgreich\n
13 '%c': unbekannte Auswahl\n
21 Sie sind nicht der superuser.\n
22 audswitch(AUD_SUSPEND) nicht erfolgreich: %s\n
23 mark_ev(%d) nicht erfolgreich\n
24 Unbekannter Parameter: %s\n
25 show_edit() nicht erfolgreich\n
26 set_edit() nicht erfolgreich\n
31 mark_sc(%d) nicht erfolgreich\n
41 audwrite(%s) nicht erfolgreich: %s\n
42 getevent() nicht erfolgreich: %s\n
43 set_event(%s) nicht erfolgreich\n
44 set_syscall(%d) nicht erfolgreich\n
45 audwrite(%s) nicht erfolgreich: %s\n
46 setevent() nicht erfolgreich: %s\n
51 audwrite(%s) nicht erfolgreich: %s\n
52 getevent() nicht erfolgreich: %s\n
53 show_event(%s) nicht erfolgreich\n
61 Syntax: %s
