$set 1
1 audisp: Sie haben nicht die erforderlichen Berechtigungen.\n
2 audisp: Prœfdatei %s kann nicht gelesen werden.\n
3 audisp: Optionen -p und -f kŒnnen nicht gleichzeitig verwendet werden.\n
4 audisp [ -u Benutzername ] [ -e Ereignisbezeichnung ] [ -c Systemaufruf ]\n
5	 [ -p ] [ -f ] [ -l ttyid ] [ -t MMTTSSMM[JJ] ]\n
6	 [ -s MMTTSSMM[JJ] ] Prœfdateiname ...\n
7 audisp: Falsche Startzeit bei -t-Auswahl.\n
8 audisp: Falsche Stopzeit bei -s-Auswahl.\n
9 audisp: Startzeit ist grŒﬁer als Stopzeit.\n
10 audisp: SÃmtliche angegebenen Benutzernamen sind falsch.\n
11 audisp: SÃmtliche angegebenen tty-Namen sind falsch.\n
12 audisp: SÃmtliche angegebenen Ereignisnamen sind falsch.\n
13 audisp: Verzeichnis kann nicht nach /dev geÃndert werden.\n
14 audisp: Verzeichnis /dev kann nicht erŒffnet werden.\n
15 \naudisp: Falscher Prœfsatz.\n
16 \naudisp: Falscher Hauptteil des Prœfsatzes.\n
17 \naudisp: malloc nicht erfolgreich.\n
18 \naudisp: Fehlerhafte aud_flag Struktur.\n
19 Anmerkung: # Dateien erfolgreich geŒffnet = %d.\n
20 audisp: Kann nicht auf Informationen zur pid-Identifikation zugreifen.\n
21 audisp: Versuch der Selbstœberprœfung fehlgeschlagen.\n
22 Zeit		     PID E  EVENT   PPID    AID	  RUID	 RGID	EUID   EGID TTY\n\n
23 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n
24	
25  
26 Benutzer und Unterstœtzung:\n
27 Alle Benutzer ausgewÃhlt.\n
28 AusgewÃhlt wurden folgende Ereignisse:\n
29 Alle Ereignisse ausgewÃhlt.\n
30 ttys und ttydevs:\n
31 Alle ttys ausgewÃhlt.\n
32 Es werden ausschlieﬁlich erfolgreiche Ereignisse ausgewÃhlt.\n
33 Es werden ausschlieﬁlich fehlgeschlagene Ereignisse ausgewÃhlt.\n
34 Es werden erfolgreiche und fehlgeschlagene Ereignisse ausgewÃhlt.\n
35 Startzeit :\n
36 Endezeit :\n
37 F
38 S
39 Selbst-Prœftext:
40 Rœckgabewert 1 = %d;
41 Rœckgabewert 2 = %d
42 PARAM #%1d (int) = %ld\n
43 PARAM #%1d (unsigned long) = %lu\n
44 PARAM #%1d (long) = %ld\n
45 PARAM #%1d (char string) =
46 PARAM #%1d (int) = %lu\n
47 PARAM #%1d (int array) =
49 %d (Adreﬁ-Familie); %s\n
50 PARAM #%1d (Dateipfad) = %lu (cnode);
51			  0x%08.8x (dev);
52			  %lu (inode);
53	    (Pfad) =
54 PARAM #%1d (Dateibeschreibung) = %lu (idev);\n
55				  %lu (inum)\n
56 PARAM #%1d (Zeitstruktur) = %lu (Sekunden); %lu (Mikrosek)\n
57 PARAM #%1d (Zeitzone) = %d (min westlich); %d (dst Zeit)\n
58 PARAM #%1d (Zeichenadresse) = %lu\n
59 PARAM #%1d (cast lang ptr) = %lu\n
60 PARAM #%1d (acl's) =
61 Kein acl vorhanden\n
62 uid=%lu,
63 gid=%lu,
64 mode=%#o
65 PARAM #%1d (Dateibeschreibungen) =\n
66 fd#%1d:   %lu (idev); %lu (inum)\n
67 Kopfteil des Datenstroms {\n
68    pid = %d\n
69    ppid = %d\n
70    aid = %ld\n
71    uid = %d\n
72    gid = %d\n
73    euid = %d\n
74    egid = %d\n
75    tty = %ld\n
76 Hauptteil des Datenstroms =\n
77 /dev
78 /dev
79 syscon
80 systty
81 /dev
82 /dev
83 syscon
84 systty
85 ?????
86 %02d%02d%02d %02d:%02d:%02d
87 audisp: Zu viele Prœfdateien. (Einige kŒnnen CDF-Elemente sein.)\n
88 [
89 Ereignis=%s;
90 Benutzer=%s;
91 Reale Gruppe=%s;
92 Effektive Gruppe=%s;
93 Ursprung=%s;
94  ]
95 /dev/pty
96 /dev/pty
97 /dev/pty
98 /dev/pty
