$set 1
1 Syntax: audomon [-p fss] [-t sp_freq] [-w Warnung] [-v] [-o Ausgabe]\n
2 audomon: fss ist eine Ganzzahl > 0 und < 100\n
3 audomon: sp_freq (Minuten) ist eine positive Gleitkommazahl\n
4 audomon: Warnung ist eine positive Ganzzahl <= 100\n
5 Dateisystem der PrÏfdatei hat noch %d%% freien Platz !\n
6 Ein Versuch, zur Sicherungsdatei umzuschalten, schlug fehl.\n
7 Es muŞ hier eine Sicherungsdatei angegeben werden !\n
8 Aktuelle GrÎŞe der PrÏfdatei ist %ld Kilobytes!!!\n
9 Ein Versuch, zur Sicherungsdatei umzuschalten, schlug fehl.\n
10 PrÏfsystem nÌhert sich dem FreeSpaceSwitch-Punkt.\n
11 Freier Platz im Dateisystem = %d%%.\n
12 PrÏfsystem nÌhert sich dem AuditFileSwitch-Punkt.\n
13 Aktuelle PrÏfdateigrÎŞe = %ld Kilobytes.\n
14 Schaden im PrÏfsystem: PrÏfkontrolldatei konnte nicht\n
15 erfolgreich fÏr den Lesemodus geÎffnet werden - %s !\n
16 Schaden im PrÏfsystem: Aktuelle PrÏfdatei %s konnte nicht\n
17 in der Steuerdatei %s gefunden werden.\n
18 Kann nicht auf die aktuelle/nÌchste PrÏfdatei zugreifen -\n
20 audomon: Sie haben keine Zugriffsberechtigung auf das PrÏfsystem.\n
24 audomon: Status der aktuellen PrÏfdatei kann nicht ermittelt werden.\n
26 audomon: Es ist nicht mÎglich, auf die Ausgabedatei zu schreiben.\n
27 audomon: Status des aktuellen PrÏfdateisystems kann nicht ermittelt werden.\n
