$set 1
1 -a und -D kÎnnen nicht gleichzeitig angegeben werden.\n
2 -A und -D kÎnnen nicht gleichzeitig angegeben werden.\n
3 -A und -d kÎnnen nicht gleichzeitig angegeben werden.\n
4 Syntax: audusr [[-a Benutzer]...] [[- d Benutzer]...] [-AD]\n
5 Kennwortdatei ist gesperrt, Aktualisierung nicht mÎglich.\n
6 Temp. Kennwortdatei konnte nicht erstellt werden, keine Aktualisierung.\n
7 Kennwortdatei /etc/passwd konnte nicht geÎffnet werden.\n
8 TemporÌre Kennwortdatei /etc/ptmp konnte nicht geÎffnet werden.\n
9 TemporÌre Kennwortdatei /etc/ptmp konnte nicht beschrieben werden.\n
10 Status der Kennwortdatei konnte nicht ermittelt werden.\n
11 Einer oder mehrere Eingabenutzer existieren nicht, keine Aktualisierung.\n
12 Anzahl der Eingabebenutzer ist grÎŞer als das erlaubte Maximum.\n
13 PrÏfsystem unverÌndert, keine Benutzer aktualisiert.\n
14 ÛberprÏfung dieses Prozesses nicht unterbrechbar - ProzeŞ beendet.\n
15 Sie haben keine Zugriffsberechtigung fÏr das PrÏfsystem.\n
16 Syntax: audsys [-nf] [-c datei -s kbytes] [-x datei -z kbytes]\n
17 falsche Eingabe
18 Warnung: /.secure/etc/audnames exitsiert nicht\n
19 /.secure/etc/audnames kann nicht geÎffnet und gesperrt werden;\nÏberprÏfen Sie, ob das PrÏfsystem korrekt installiert wurde\nund das Verzeichnis /.secure/etc existiert, bevor Sie diesen Befehl\nverwenden.\n
20 Warnung: Fehlerhaft formatierte /.secure/etc/audnames kann nicht\ngelesen werden.\n
21 /.secure/etc/audnames erstellt/repariert.\n
22 PrÏfdatei %s kann nicht erstellt werden.\n
23 PrÏfdatei %s, ist nicht leer.\n
24 PrÏfdatei %s, ist keine regulÌre Datei (oder CDF)\n
25 Interner Fehler\n
26 -n und -f kÎnnen nicht gleichzeitig angegeben werden.\n
27 -n muŞ angegeben sein, um das PrÏfsystem einzuschalten.\n
28 PrÏfsystem bereits eingeschaltet, eingegebene Parameter ignoriert.\n
29 -c und -s mÏssen gemeinsam angegeben werden.\n
30 PrÏfsystem unverÌndert\n
31 aktuelle
32 nÌchste
33 %s PrÏfdatei %s\nÏberschreitet ihr AFS. Andere Auswahl treffen.\n
34 %s PrÏfdatei %s\nPlatz nicht ausreichend im Dateisystem der PrÏfdatei,\nandere PrÏfdatei angeben oder kleineres AFS wÌhlen\n
35 %s PrÏfdatei %s\nDateisystem Ïberschreitet minfree,\nPrÏfdatei in einem anderen Dateisystem angeben.\n
36 Unbekannte aktuelle PrÏfdatei verwendet:
37 Unbekannte nÌchste  PrÏfdatei verwendet:
38 -c muŞ angegeben werden, um eine aktuelle Datei auszuwÌhlen.\n
39 -x muŞ angegeben werden, um eine nÌchste Datei auszuwÌhlen.\n
40 Es wurde eine unbekannte FolgeprÏfdatei verwendet:
41 -x und -z mÏssen gemeinsam angegeben werden.\n
42 Verzeichnis der PrÏfdatei %s existiert nicht.\n
43 Warnung: PrÏfdatei %s existiert nicht.\n
44 PrÏfdateien:\n
45 Aktuelle Datei:
46 NÌchste  Datei:
47 ** unbekannt **
48 NÌchste  Datei: keine\n
49 NÌchste  Datei:        ** Keine Daten verfÏgbar **\n
50 Aktuelle Datei:        ** Keine Daten verfÏgbar **\n
51 Statistik:      Kb afs  Kb benutzt  %% frei  Kb fs  Kb benutzt  %% frei\n
52 Aktuelle und nÌchste PrÏfdatei verweisen auf gleiche Zieladresse.\n
53 PrÏfsystem gestartet.\n
54 PrÏfsystem gestoppt.\n
55 Erstellte PrÏfdatei:
56 Weitere Eingabeparameter werden ignoriert.\n
57 Keine verfÏgbare nÌchste PrÏfdatei.\n
58 PrÏfsystem ist im Augenblick ausgeschaltet.\n
59 PrÏfsystem ist im Augenblick eingeschaltet.\n
60 NÌchste Datei wurde auf <null> zurÏckgesetzt,\nes ist keine nÌchste PrÏfdatei verfÏgbar.\n
101 Alle Benutzer
102 werden ÏberprÏft\n
103 werden nicht ÏberprÏft werden\n
104 audsys: Es ist nicht mÎglich, die PrÏfung zu unterbrechen -\nFortsetzung nicht mÎglich.
105 audsys: Aktuelle PrÏfdatei ist geÌndert zu
106 audsys: NÌchste PrÏfdatei ist geÌndert zu
107 audsys: Eingegebene PrÏfdatei ist keine leere, regulÌre Datei.\n
108 audsys: PrÏfdatei kann nicht erstellt werden.
109 audsys: PrÏfsystem wird angehalten.\n
110 audsys: PrÏfsystem gestarted\n
111 audsys: Unbekannte aktuelle PrÏfdatei bereits im Zugriff 
112 audsys: Unbekannte nÌchste  PrÏfdatei bereits im Zugriff 
113 audsys: NÌchste Datei auf NULL zurÏckgesetzt.\n
114 audsys: Aktuelle und nÌchste Datei verweisen auf dieselbe Datei.\n
115 audsys: /.secure/etc/audnames konnte nicht geÎffnet und gesperrt werden.\n
116 audsys: unbekannter interner Fehler\n
117 audsys: interner Fehler: Anhalten fehlgeschlagen\n
118 audsys: interner Fehler: Aktualisierung von /.secure/etc/audnames\nfehlgeschlagen\n
119 audsys: interner Fehler: Konnte Kern nicht aktualisieren.\n
120 audsys: /.secure/etc/audnames konnte nicht gefunden werden.\n
121 audsys: /.secure/etc/audnames fehlerhaft ermittelt.\n
122 audsys: /.secure/etc/audnames korrigiert.\n
123 audsys: /.secure/etc/audnames konnte nicht korrigiert werden.\n
124 audsys: PrÏfsystem unverÌndert.\n
125 audsys: Aktuelle Datei ist 
126 audsys: NÌchste  Datei ist 
127 audsys: Erwartete PrÏfdatei nicht gefunden (gelÎscht?).
