$set 1
1 Aufgegeben...
2 unzulÌssige Umleitung
3 unzulÌssiger Befehl
4 Zeichenkette zu lang
5 newline in regulÌrem Ausdruck
6 newline in Schriftzeichenklasse
7 newline in Zeichenkette
8 awk: %s bei Zeile %d\n
9 unzulÌssiger regulÌrer Ausdruck
10 %s ist kein Array
11 Syntax: awk [-f quelle | 'cmds'] [dateien]
12 Fehlerhafte Formatangabe in printf(%s)
13 Erstelle Riesensatz `%.20s...'
14 Es ist nicht mÎglich, Datei %s zu Îffnen.
15 Es ist nicht mÎglich, Datei %s zu Îffnen.
16 $0 kann nicht gesetzt werden.
17 Division durch Null
18 Format des Feldes %.20s... zu lang
19 FragwÏrdige Variable %o: %s %s %g %o
20 unzulÌssiger arithmetischer Operator %d
21 unzulÌssiger Zuweisungsoperator %d
22 unzulÌssiger Funktionstyp %d
23 unzulÌssiger Sprungtyp %d
24 unzulÌssiger Zugriff auf Array %s
25 unzulÌssige Anweisung %o
26 Es fehlen Argumente in printf(%s)
27 Kein Speicherplatz mehr, %d Byte benÎtigt
28 Nicht genÏgend Platz zur AusfÏhrung von makesymtab
29 Nicht genÏgend Platz zur AusfÏhrung von nodealloc
30 Nicht genÏgend Platz zur AusfÏhrung von tostring auf %s
31 Keine temporÌren Strukturen in gettemp mehr
32 Druck fehlgeschlagen
33 Satz `%.20s...' hat zu viele Felder
34 Satz `%.20s...' zu lang
35 RegulÌrer Ausdruck zu lang\n
36 Zeichenkette %.20s ... zu lang zum Drucken
37 Ûberlauf der Symboltabelle auf %s
38 Zu viele Ausgabedateien %d
39 Versuch, auf das Feld %d zuzugreifen
40 Unerwartetes break, continue oder next
41 Unbekannter boolescher Operator %d
42 Unbekannter Vergleichsoperator %d
43 Unbekannter Typ %d in cfoll
44 Unbekannter Typ %d in first\n
45 Unbekannter Typ %d in freetr
46 Unbekannter Typ %d in penter\n
47 Nicht zurÏckgeladen
48 Nicht gesichert
49 Leere RÏckladedatei
50  Satznummer %g\n
30001 Syntaxfehler - kein backup mÎglich
30002 yacc-StapelÏberlauf
30003 Syntaxfehler
30004 Kein Platz an yacc-Stapel zuweisbar
