$set 1
1  in Quellenzeile %d
2  Kontext ist\n\t
3  in Funktion %s
4  Eingabesatznummer %g
5  Quellenzeilennummer %d\n
6 Parameter %s auŞerhalb des erlaubten Bereichs.
7 %s ist eine Funktion und kein Array.
8 %s ist ein Array und keine Funktion.
9 %s ist kein Array.
10 %s generiert zu viele offen Dateien.
11 %s Ergebnis auŞerhalb des erlaubten Bereichs.
12 , Datei %s
13 Syntax: %s [-f Quelle | 'cmds'] [Dateien]
14 \t%d zusÌtzliche %c\n
15 \t%d fehlende %c\n
16 \t%c zu viel\n
17 \t%c fehlt\n
18 `%s' ist ein Array-Name und ein Funktionsname.
19 Der Parameter #%d der Funktion %s wurde nicht angegeben.
20 Fehlerhafte Formatangabe in printf(%s).
21 Aufgegeben...
22 Riesigen Datensatz erstellt: `%.20s...'
23 Aufruf einer unbekannten Funktion %s
24 %s auf %s nicht mÎglich; es ist eine Funktion.
25 %s  auf %s nicht mÎglich; es ist ein Array.
26 Es ist nicht mÎglich, %s zu Îffnen.
27 Es ist nicht mÎglich, Datei %s zu Îffnen.
28 Es ist nicht mÎglich, die Funktion %s als Parameter zu verwenden.
29 Es werden zu viele Felder erstellt
30 Division durch Null in %=
31 Division durch Null in /=
32 Division durch Null in mod
33 Division durch Null
34 Leerer regulÌrer Ausdruck.
35 Leere RÏckladedatei\n
36 ) zu viel
37 ] zu viel
38 } zu viel
39 Gleitkomma-Ausnahme
40 Formatelement %.20s... zu lang
41 Kein ausreichender Platz fuer Stapelrahmen in %s
42 FragwÏrdige Variable %o: n=%s s="%s" f=%g t=%o
43 gsub()-Ergebnis %.20s zu groŞ
44 unzulÌssiger arithmetischer Operator %d
45 unzulÌssiger Zuweisungsoperator %d
46 unzulÌssiges Feld $(%s)
47 unzulÌssiger Funktionstyp %d
48 unzulÌssiger Sprungtyp %d
49 unzulÌssige verschachtelte Funktion
50 unzulÌssiger Elementarausdruck in regulÌrem Ausdruck %s in %s
51 unzulÌssige Umleitung
52 unzulÌssiger Bezug auf Array %s
53 unzulÌssige Anweisung
54 unzulÌssiger split()-Typ
55 index() erlaubt keine regulÌren AusdrÏcke
56 Eingabesatz `%.20s...' zu lang
57 newline in Schriftzeichenklasse %s...
58 newline in regulÌrem Ausdruck %.10s...
59 newline in Zeichenkette %.10s...
60 next ist innerhalb einer Funktion unzulÌssig
61 Kein Platz fÏr temporÌre Struktur
62 Nicht abgeschlossene Zeichenklasse %s
63 Es fehlen Argumente in printf(%s)
64 Es fehlen Argumente in printf(%s)
65 Nicht zurÏckgeladen\n
66 Nicht gesichert\n
67 Null-Dateiname in print oder getline
68 Nicht genÏgend Platz zur AusfÏhrung von makesymtab
69 Nicht genÏgend Platz zur AusfÏhrung von nodealloc
70 Nicht genÏgend Platz zur AusfÏhrung von rehash
71 Nicht genÏgend Platz zur AusfÏhrung von tostring auf %s
72 Satz `%.20s...' hat zu viele Felder
73 RegulÌrer Ausdruck zu groŞ: %s
74 Kein RÏcksprung in Funktion
75 Zeichenkette %.10s... zu lang
76 Zeichenkette zu lang
77 Zeichenkette/regulÌrer Ausdruck %.10s... zu lang
78 sub()-Ergebnis %.20s zu groŞ
79 Ûberlauf der Symboltabelle auf %s
80 Syntaxfehler in regulÌrem Ausdruck %s auf %s
81 Versuch, auf das Feld %d zuzugreifen
82 Unerwartetetes break oder next
83 Unerwartetes break, continue oder next
84 Unbekannter boolescher Operator %d
85 Unbekannter Vergleichsoperator %d
86 Unbekannter Typ %d in cfoll
87 Unbekannter Typ %d in first\n
88 Unbekannter Typ %d in freetr
89 Unbekannter Typ %d in penter\n
90 Sie kÎnnen die Funktion %s nicht mehrmals definieren
91  Eingabesatznummer %g
92 , Datei %s
93  Quellenzeilennummer %d\n
94  Kontext ist\n\t
95  an Quellenzeile %d
96  in Funktion %s
97 \t%c fehlt\n
98 \t%d fehlende %c\n
99 \t%c zu viel\n
100 \t%d %c zu viel\n
101 Falsches Vergleichselement angesprochen\n
102 \\ am Ende in Muster\n
103 \\n gefunden vor Ende des Musters\n
104 Verschachtelungsebene zu tief\n
105 Zahl in \\Ziffer unzulÌssig oder fehlerhaft\n
106 [ ] Ungleichgewicht\n
107 \\( \\) oder ( ) Ungleichgewicht\n
108 \\{ \\} Ungleichgewicht\n
109 fehlerhafter Endpunkt in Bereichsanweisung\n
110 Kein Speicher fÏr Ïbersetztes Muster\n
111 Zahl zu groŞ in \\{ \\} Konstrukt\n
112 Fehlerhafte Zahl in \\{ \\} Konstrukt\n
113 Mehr als zwei Zahlen in \\{ \\} Konstrukt\n
114 Erste Zahl ist grÎŞer als die zweite in \\{ \\} Konstrukt\n
115 Fehlerhaften Typ fÏr Zeichenklasse angegeben\n
116 Keine gespeicherte Suchzeichenkette\n
117 Verdoppelungsoperator in unzulÌssiger Position\n
118 Kein Ausdruck innerhalb ( ) oder auf einer Seite eines |\n
119 Sie kÎnnen nur Array[-Element] lÎschen\n
120 Kein Programm angegeben\n
121 Kein Platz fÏr Stapelbereiche beim Aufruf von %s aufrufende Stapelbereiche\n
122 Funktion %s wurde mit %d Argumenten aufgerufen, verwendet nur %d\n
123 Funktion %s hat %d Argumente, Grenzwert %d\n
124 tempcell-Liste ist defekt\n
125 printf-Zeichenkette %.40s... zu lang\n
126 Kein Platz beim Verketten von %.15s und %.15s\n
127 atan2 erwartet zwei Argumente; 1.0 zurÏckgeliefert\n
128 Warnung: Funktion hat zu viele Argumente\n
129 E/A-Fehler aufgetreten auf %s\n
130 E/A-Fehler aufgetreten beim SchlieŞen von %s\n
131 Zu viele Programmdateien: %s ignoriert.\n
