$set 1
2 chmod: Kein Zugriff auf %s\n
3 chmod: Øndern nicht mÎglich
4 chmod: Falscher Modus\n
5 chmod: Option -A auf die entfernte Datei %s nicht zugelassen\n
6 chmod: Kann %s nicht durchqueren\n
7 chmod: %s kein Verzeichnis\n
101 Syntax: chmod [-A] [-R] [ugoa]+-=[rwxXstHugo][,...] Datei ...\n
102 Syntax: chmod [-R] [ugoa]+-=[rwxXstHugo][,...] Datei ...\n
103 Syntax: chmod [-A] [-R] [ugoa]+-=[rwxXstugo][,...] Datei ...\n
104 Syntax: chmod [-R] [ugoa]+-=[rwxXstugo][,...] Datei ...\n
