$set 1
1 cnodes: malloc-Fehler\n
2 cnodes: malloc-Fehler\n
3 Syntax: %s -aAnlmxC1sr [Namen]\n
4 cnodes: Es nicht mÎglich, /etc/clusterconf zu lesen\n
5 cnodes: cnode_id %d: System existiert nicht\n
6 cnodes: %s: System ist kein Cluster\n
7 cnodes: %s: System existiert nicht\n
8 cnodes: malloc fehlgeschlagen\n
9 <nicht gefunden>
10 CNODE       ID SWAP SITE\n========== === ==========
11  ID CNODE      SWAP SITE\n=== ========== ==========
