$set 1
1 Syntax: cp [-f|-i] [-p] Quelldatei Zieldatei\n	cp [-f|-i] [-p] Quelldatei ... Zielverzeichnis\n	cp [-f|-i] [-p] -R|-r Quellverzeichnis ... Zielverzeichnis\n
2 cp: Link auf %s konnte nicht rœckgÃngig gemacht werden:
3 cp: Kein Zugriff auf %s:
4 cp: <%s> Verzeichnis. Option "-R" erforderlich.\n
5 cp: %s/%s: Name zu lang\n
6 cp: %s und %s stimmen œberein\n
7 cp: %s: Kein Verzeichnis\n
9 cp: %s kann nicht erstellt werden:
10 cp: ⁄ffnen nicht mŒglich
11 cp: %s kann nicht erstellt werden:
12 cp: Fehlerhaftes Kopieren nach %s:
13 cp: %s kann nicht geschlossen werden:
14 cp: Berechtigungs-Bits auf %s kŒnnen nicht gesetzt werden:
15 cp: %s/%s: Name zu lang.\n
16 cp: mkrnod nicht durchfœhrbar
17 cp: symlink nicht durchfœhrbar 
18 cp: readlink nicht durchfœhrbar
19 cp: utime fehlgeschlagen %s: 
20 cp: chown fehlgeschlagen %s: 
21 Warnung: Socket %s œbersprungen\n
22 cp: Warnung: cpacl nach %s nicht mŒglich\n
23 cp: Warnung: cpacl nach %s nicht mŒglich\n
24 link fehlgeschlagen
25 %s œberschreiben?
26 cp: %s: Kein Verzeichnis\n
27 cp: Kein ACL-Zugriff auf %s: 
28 cp: Keine Zuordnung %d Eingabe ACL fœr %s: 
29 cp: Kein ACL-Lesezugriff auf %s: 
