$set 1
2 Schreiben in <%s> nicht mÎglich\n
3 Umbenennen nicht mÎglich (/dev/tty fehlt)\n
4 Optionen mÏssen o|i|p beinhalten\n
5 `R'-Option ist bedeutungslos zusammen mit der '-%c'-Option\n
7 `B'-Option ist bedeutungslos zusammen mit der '-p'-Option\n
10 %s kann nicht gelesen werden\n
11 %s kann nicht gelesen werden\n
12 Warnung: Inhalt von %s in Archivdatei ist beschÌdigt\n
13 In %s kann nicht geschrieben werden\n
14 chmod <%s> nicht ausfÏhrbar (errno:%d)\n
15 Zum Kopieren von <%s> `-d'-Option verwenden\n
16 Kein Link zwischen <%s> & <%s> mÎglich (errno:%d)\n
17 Kein Link zwischen <%s> & <%s> mÎglich (errno:%d)\n
18 Verzeichnis fÏr <%s> kann nicht erstellt werden (errno:%d)\n
19 Kein Link zwischen <%s> & <%s> mÎglich (errno:%d)\n
20 chmod <%s> nicht ausfÏhrbar (errno:%d)\n
21 %s kann nicht gelesen werden\n
22 In %s kann nicht geschrieben werden\n
23 chmod <%s> nicht ausfÏhrbar (errno:%d)\n
24 cpio: ZurÏckspeichern von mindestens %d Datei nicht mÎglich.\n
25 cpio: ZurÏckspeichern von mindestens %d Dateien nicht mÎglich.\n
26 %ld BlÎcke\n
27 Syntax: cpio -o[aAcBvxCh] <Namensliste >Ausgabe\n
28	   cpio -i[BcdmPrtuvfsSbx6RU] [Muster ...] <Auswahlliste\n
29	   cpio -p[adlmruvxU] Verzeichnis <Namensliste\n\n
30 cpio: Neueinstellung, nachdem %d Byte Ïbersprungen wurde.\n
31 cpio: Neueinstellung, nachdem %d Byte Ïbersprungen wurden.\n
32 cpio: korrekte Verarbeitungsreihenfolge verloren; Neueinstellung.\n
33 cpio: Neueinstellung, nachdem %d Byte Ïbersprungen wurden.\n
34 cpio: korrekte Verarbeitungsreihenfolge verloren; Neueinstellung.\n
35 Korrekte Verarbeitungsreihenfolge verloren -- Hilfe holen.\n
36 Sie sollten ggf. die "R"-Option verwenden.\n
37 Vielleicht sollte die "-c"-Option nicht verwendet werden\n
38 Vielleicht sollte die "-c"-Option verwendet werden\n
39 Korrekte Verarbeitungsreihenfolge verloren -- nutzen Sie die RT-Hilfe\n
40 Vielleicht sollte die "-c"-Option verwendet werden\n
41 <%s> umbenennen\n
42 Ûbersprungen\n
43 Verzeichnis fÏr <%s> kann nicht erstellt werden (errno:%d)\n
44 Verzeichnis <%s> kann nicht erstellt werden (errno:%d)\n
45 chmod <%s> nicht ausfÏhrbar (errno:%d)\n
46 chown <%s> nicht ausfÏhrbar (errno:%d)\n
47 Link des aktuellen <%s> kann nicht rÏckgÌngig gemacht werden (errno:%d)\n
48 Aktuelles <%s> ist neuer\n
49 Versuch, die Datei an sich selbst zu Ïbergeben!\n
50 mknod <%s> nicht ausfÏhrbar (errno:%d)\n
51 Verzeichnis fÏr <%s> kann nicht erstellt werden (errno:%d)\n
52 mknod <%s> nicht ausfÏhrbar (errno:%d)\n
53 chmod <%s> nicht ausfÏhrbar (errno:%d)\n
54 chown <%s> nicht ausfÏhrbar (errno:%d)\n
55 <%s> kann nicht geÎffnet werden (errno:%d)\n
56 Verzeichnis fÏr <%s> kann nicht erstellt werden (errno:%d)\n
57 <%s> kann nicht erstellt werden (errno:%d)\n
58 ZusammenhÌngende Datei <%s> geeigneter GrÎŞe kann nicht erstellt werden\n
59     <%s> wird als regulÌre Datei erstellt\n
60 <%s> nicht gelÎscht\n
61 Link fÏr <%s> kann nicht erstellt werden (errno:%d)\n
62 Link <%s> kann nicht erstellt werden (errno:%d)\n
64 chown <%s> nicht ausfÏhrbar (errno:%d)\n
65 Verzeichnis fÏr <%s> kann nicht erstellt werden (errno:%d)\n
66 <%s> kann nicht erstellt werden (errno:%d)\n
67 Kein Link auf diese Datei mÎglich: %s\n
68 %s und %s sind die gleiche Datei!\n
69 Link zwischen %s und %s\n
70 Verzeichnis fÏr <%s> kann nicht erstellt werden (errno:%d)\n
71 Kein Link zwischen <%s> & <%s> mÎglich (errno:%d)\n
73 Kein Speicher fÏr Links vorhanden\n
76 chown <%s> nicht ausfÏhrbar (errno:%d)\n
77 /dev/tty kann nicht zur Anforderung weiterer DatentrÌger geÎffnet werden\n
79 Ende des DatentrÌgers\n
81 errno: %d,
82 Ausgabe kann nicht geschrieben werden\n
83 Eingabe kann nicht gelesen werden\n
84 Zum Weitermachen geben Sie das GerÌt/die Datei ein, wenn Sie so weit sind\n
85 Leeren Namen fÏr die nÌchste GerÌtedatei angegeben\n
86 Das funktioniert nicht\n
87 Benutzer hat Datei %s zum Weitermachen geÎffnet.\n
88 Fehlende 'd'-Option\n
89 chdir nicht ausfÏhrbar (keine `d'-Option)\n
90 chdir nicht ausfÏhrbar - keine Schreibberechtigung\n
91 chdir nicht ausfÏhrbar\n
92 cpio: Zugriff auf augenblickliches Arbeitverzeichnis nicht mÎglich:
93 cpio: Zu viele Muster in Befehlszeile (max=%d)\n
94 `C'-Option ist bedeutungslos zusammen mit der '-%c'-Option\n
95 TemporÌre Datei fÏr Dateinamensliste kann nicht erstellt werden\n
96 %s\n
97 <%s> kann nicht geÎffnet werden\n
98 %s\n
99 Unerwarteter Schreibzustand: CHECKPT\n
100 Unbekannter Schreibzustand (%d).\n
101 Status von <%s> kann nicht ermittelt werden.\n
102 Unerwarteter Schreibzustand: CHECKPT\n
103 Unbekannter Schreibzustand (%d).\n
104 Unbekannter Bestandteil (%d).\n
105 /dev/tty kann nicht geÎffnet werden\n
106 %3h %2d %H:%M:%S 19%y
107 Die Datei "TRAILER!!!" wurde nicht gesichert\n
108 Optionale acl-EintrÌge fÏr <%s> wurden nicht gesichert\n
109 Veraltete NetzwerkgerÌtedatei <%s> wurde nicht gesichert\n
110 Montieren Sie ein neues Band, um Band #%d neu zu beschreiben.\n
111 (Bandstation mit aktiviertem Sofort-Berichtsmodus verwenden (Band #%d).)\n
112 Socket <%s> wurde nicht gesichert\n
113 Veraltete NetzwerkgerÌtedatei <%s> Ïbersprungen\n
