$set 1
1 Token zu lang
2 %s: Nicht abgeschlossener Makro-Aufruf
3 Unerwartetes EOF-Zeichen im Kommentar
4 Probleme beim Beschreiben der Ausgabedatei; ggf. kein ausreichender temporÃrer Platz.
5 Fehlende #endif-Anweisung(en)
6 (NLS) ungœltiges zweites Byte in 16-Bit-Zeichen
7 (NLS) ungœltiges zweites Byte in 16-Bit-Zeichen
8 %s: Zu viele zurœckgestellte Zeichen im Eingabestrom
9 Kein Platz
10 Token zu lang
11 Falsche Include-Syntax
12 Fehlerhafte Schachtelung von Include-Anweisungens
13 Kein Platz
14 Include-Datei %s kann nicht gefunden werden
15 Definitionsœberlauf
16 Ungœltiger Makroname
17 %s: fehlendes )
18 Falscher Formalwert: %s
19 Zu viele Formalwerte: %s
20 %s ist umdefiniert
21 'endif' ohne zugehŒriges 'if'
22 'else' ohne zugehŒriges 'if'
23 Bedingung nicht ausgefœhrt, WAHR angenommen
24 falsche Nummer fœr #line
25 Falsche Datei fœr #line
26 Falsche Datei fœr #line
27 Nichtdefinierte Vorprozessoranweisung
28  (in Vorprozessor-if)
29 Zu viele Definitionsangaben
30 %s: Makro-Rekursion
31 %s: Aktualwerte zu lang
33 %s: Argumente stimmen nicht œberein
36 %s kann nicht geŒffnet werden\n
37 Zu viele -D-Optionen, %s ignoriert
38 Zu viele -U-Optionen, %s ignoriert
39 €berdimensionierte -I-Datei (%s) ignoriert
40 Fehlende TabellengrŒﬁe nach Option -H, Option -H ignoriert
41 Fehlerhafte DefinitionstabellengrŒﬁe angegeben
42 Unbekannte Markierung %s
43 Keine Quelldatei %s
44 %s kann nicht erstellt werden
45 Fremder Name %s
46 Befehlszeile
47 Probleme mit der Ausgabedatei; evtl. nicht genœgend temporÃrer Platz vorhanden
48 Definitionstabelle kann nicht zugeordnet werden
49 Symboltabelle kann nicht zugeordnet werden
50 Objektdatei kann nicht zugeordnet werden
51 Zugriffsberechtigung fœr %s verweigert
52 Pfadname zu lang fœr Datei %s
53 Systemdateitabelle ist voll. %s kann nicht geŒffnet werden
54 Ungœltiger Pfadname fœr %s
55 %s kann nicht geŒffnet werden
56 €berschœssige -y-Datei (%s) ignoriert
57 €berschœssige -p-Datei (%s) ignoriert
30003 Syntaxfehler
$set 2
1 Ungœltiges Zeichen %c in Vorprozessor-if
2 "defined" modifiziert Nicht-Kennung "%s" in Vorprozessor-if
3 Ungœltige Nummer %s
54 Division durch Null
30001 Syntaxfehler - Sicherungslauf nicht durchfœhrbar
30002 yacc: Stapelœberlauf
30003 Syntaxfehler
30004 Platz fœr yacc-Stapel kann nicht zugeordnet werden
