$set 1
1 Kann nicht in crontab-Verzeichnis wechseln
2 crontab-Verzeichnis kann nicht gelesen werden
3 Ihr at-Job kann nicht gelesen werden
4 Da Sie nicht in der Shell /bin/sh arbeiten, kÎnnen Sie cron nicht verwenden.
5 Zugriff auf Ihre crontab-Datei nicht mÎglich. Wiederholen Sie Ihre Eingabe.
6 Kann nicht in Ihr Heimatverzeichnis wechseln.\nIhre Befehle werden nicht ausgefÏhrt.
7 AusfÏhrung der Shell fÏr einen Ihrer Befehle nicht mÎglich
8 Unerwartetes Zeilenende
9 Zugriff auf Ihre crontab-Datei nicht mÎglich. Wiederholen Sie Ihre Eingabe.
10 Standardeingabedatei kann fÏr einen Ihrer crontab-Befehle nicht erstellt werden.\nDieser Befehl wurde nicht ausgefÏhrt.
11 Zahl zu groŞ oder zu klein fÏr das Feld
12 \n\n***************************************************\nCron: Die vorherige Meldung ist die Standardausgabe\n      und die Standardfehlerausgabe eines Ihrer cron-Befehle.\n\n
13 \n\n***************************************************\nCron: Die vorherige Meldung ist die Standardausgabe\n      und die Standardfehlerausgabe eines Ihrer crontab-Befehle:\n\n
14 \n\n***************************************************\nCron: Die vorherige Meldung ist die Standardausgabe\n      und die Standardfehlerausgabe eines Ihrer at-Befehle.\n\n
15 Einer Ihrer Befehle generiert eine Ausgabe oder Fehlerausgabe, aber cron war nicht in der Lage, Ihnen diese Ausgabe zuzusenden.\nVergessen Sie nicht, die Standardausgabe und die Standardfehlerausgabe fÏr jeden Ihrer Befehle umzuleiten.
16 Unerwartetes Symbol aufgetreten
17 *** cron gestartet ***   pid = %d
18 Status der QUEDEFS-Datei kann nicht ermittelt werden
19 Zugriff auf FIFO-Warteschlange nicht mÎglich
20 FIFO-Warteschlange kann nicht erstellt werden
21 cron ist bereits aktiv
22 %s kann nicht geÎffnet werden\n
23 Kann nicht in das at-Verzeichnis wechseln
24 at-Verzeichnis kann nicht gelesen werden
25 Ihre crontab-Datei beinhaltet einen Fehler\n
26 Dieser Eintrag wurde ignoriert\n
27 %c Warteschlangenlimit wurde erreicht
28 MAXRUN (%d) Prozesse wurde erreicht
29 ATLIMIT (%d) wurde fÏr uid %d erreicht
30 CRONLIMIT (%d) wurde fÏr uid %d erreicht
31 Erstellung eines neuen Prozesses nicht mÎglich
32 Unerwartete ProzeŞkennung lieferte %d (ignoriert)
33 Status der FIFO-Warteschlange kann nicht ermittelt werden
34 Meldung empfangen - falsches Format
35 cron abgebrochen: 
36 ******* CRON ABGEBROCHEN ********
37 Erneutes Einreihen des cron-Jobs
38 Erneutes Einreihen des at-Jobs
39 quedefs-Datei kann nicht geÎffnet werden
40 Standardwarteschlangendefinitionen verwendet
69 Ihr Job enthÌlt keine gÏltige PrÏfidentifikation.\nSystemverwalter verstÌndigen.\n
$set 2
1 %d Byte kÎnnen nicht belegt werden\n
