$set 1
1 Ihre crontab-Datei kann nicht im crontab-Verzeichnis erstellt werden
2 Ihre crontab-Datei kann nicht geÎffnet werden
3 Da Sie nicht in der Shell /bin/sh arbeiten, kÎnnen Sie den cron-Befehl nicht verwenden.
4 Warnung: Ihre Befehle werden ausgefÏhrt unter Verwendung von /bin/sh\n
5 Die korrekte Syntax ist: \n\tcrontab [Datei]\n\tcrontab [-r]\n\tcrontab [-l]
6 Sie sind kein berechtigter Benutzer (kein Eintrag in /etc/passwd).
7 Sie sind nicht berechtigt, den cron-Befehl zu verwenden.  Sorry.
8 Unerwartetes Zeilenende
9 Unerwartetes Zeichen in der Zeile 
10 Nummer auŞerhalb des erlaubten Bereichs
11 %scrontab: Fehler in vorheriger Zeile; %s\n
12 cron lÌuft eventuell nicht - verstÌndigen Sie Ihren Systemverwalter\n
13 crontab: Fehler beim Úffnen der Meldungswarteschlange\n
14 crontab: Fehler beim Senden von Meldungen\n
$set 2
1 Belegung von %d Bytes nicht mÎglich\n
