$set 1
1 Angabe fehlerhaft korrigiert: %s\n
2 Initialbelegung fehlgeschlagen, err=%d\n
3 Temp-Belegung fehlgeschlagen:%d WORD:%derr=%d\n
$set 2
1 getwd: Úffnen nicht mÎglich ..\n
2 getwd: Lesefehler in ..\n
3 getwd: Lesefehler in ..\n
4 getwd: Ønderung kann nicht rÏckgÌngig gemacht werden\n
5 getwd: Aktueller Verzeichnisname zu lang\n
$set 3
1 Automatische Abmeldung\n
2 Warnung: Kein Zugriff auf tty; deshalb keine Jobsteuerung in dieser Shell ...\n
3 logout\n
4 Unterbrochen
5 Sie haben neue Post.\n
6 Sie haben Post.\n
7 Neue Post in %s.\n
8 Post in %s.\n
9 %s: Keine regulÌre Datei
10 Zu wenige Argumente
11 Zu viele Argumente
$set 4
1 Syntax: Verzeichnisse [ -l ]
2 Kein Heimatverzeichnis
3 Kein Wechsel ins Heimverzeichnis mÎglich
4 Kein anderes Verzeichnis vorhanden.
5 Verzeichnisstapel nicht so tief gestaffelt.
6 Falsches Verzeichnis
7 Verzeichnisstapel leer
8 Verzeichnis %s existiert nicht, vom Stapel gelÎscht
$set 5
1 Nicht eindeutig
2 Einzelnes %c
3 Wort zu lang
4 $< Zeile zu lang
5 Keine Datei fÏr $0
6 Variable Syntax
7 Subscript auŞerhalb des erlaubten Bereichs
8 Falsch : mod in $
9 AbschluŞzeichen << nicht gefunden
10 ZeilenÏberlauf
11 ZeilenÏberlauf
$set 6
1 Keine Ûbereinstimmung
2 Befehl nicht gefunden
3 %d Treffer, %d Fehler, %2d%%\n
4 %s: AusfÏhrbare Datei nicht mit der Hardware kompatibel
$set 7
1 Division durch 0
2 Modulo 0
3 Syntax des Ausdrucks
4 Fehlendes }
5 Fehlender Dateiname
6 Syntax des Ausdrucks
$set 8
1 Zu wenige Argumente
2 Zu viele Argumente
3 Vom Bildschirm aus nicht mÎglich
4 Vom Bildschirm aus nicht mÎglich
5 Es ist zu gefÌhrlich, dafÏr ein alias zu verwenden
6 Kennwort:
7 Name und Kennwort zu lang
8 UngÏltige Fern-Anmeldung.  errnet = %d\n
9 Netzwerkfehler
10 Remote-Einheit antwortet nicht.  errnet = %d\n
11 Netzwerkfehler
12 errnet = %d\n
13 Netzwerkfehler
14 UngÏltige NetzwerkgerÌtedatei  errno = %d\n
15 Dies ist nicht die Anmelde-Shell
16 Leere 'if'-Konstruktion
17 'then'-Konstruktion nicht korrekt
18 Syntaxfehler
19 Nicht in while/foreach
20 Syntax des Ausdrucks
21 Fehlerhafte Variable
22 Worte nicht in () eingeschlossen
23 Keine Ûbereinstimmung
24 Syntax des Ausdrucks
25 Nicht in while/foreach
26 Nicht in while/foreach
27 then/endif nicht gefunden
28 endif nicht gefunden
29 endsw nicht gefunden
30 end nicht gefunden
31 label nicht gefunden
32 Keine Ûbereinstimmung
33 Keine zutreffende Maskierung
34 Unterbrechung einer Anmelde-Shell nicht mÎglich
35 Keine Ûbereinstimmung
36 Netzwerk nicht unterstÏtzt\n
$set 9
2 Fehlendes ]
3 Fehlendes }
4 Fehlendes ]
5 Fehlendes ]
7 Argumente zu lang
8 Pfadname zu lang
9 Keine Ûbereinstimmung
10 Nicht eindeutig
11 Einzelnes `
12 Wort zu lang
13 Zu viele Worte von ``
14 UngÏltiges Muster
$set 10
1 Keine Ûbereinstimmung 
2 Wort zu lang
3 Variable Syntax
4 ErweiterungspufferÏberlauf
5 Falsche !-form
6 Kein vorausgehendes 'sub'
7 Falsche Substitution
8 Kein vorausgehendes 'lhs'
9 'rhs' zu lang
10 Falsche !-Modifizierung: 
11 Modifizierung fehlgeschlagen
12 SubstitutionspufferÏberlauf
13 Falsche !-Argumentauswahl
14 Kein vorausgegangener Suchvorgang
15 : Ereignis nicht gefunden
16 tty pgrp von %d nach %d zurÏckgesetzt\n
17 \nZum Abmelden "logout" verwenden\n
18 \nZum Abmelden aus csh "exit" verwenden\n
19 tty pgrp auf %d zurÏckgesetzt\n
$set 11
1 Kein ausreichender Speicher
2 Variable nicht definiert
3 Nicht genÏgend Platz fÏr to_short
4 Platz fÏr to_char Ïberschritten\n
$set 12
1 Alias-Schleife
2 Zu viele )
3 zu viele )
4 Zu viele (
5 Falsch plazierte (
6 Fehlender Name fÏr Umleitung
7 Ausgabeumleitung nicht eindeutig
8 << innerhalb () nicht mÎglich
9 Eingabeumleitung nicht eindeutig
10 Falsch angeordnete ()
11 UngÏltiger NULL-Befehl
$set 13
1 Hangup
2 Unterbrechung
3 Ende
4 UngÏltiger Befehl
5 Trace/BPT trap
6 IOT trap
7 EMT trap
8 Gleitkommaausnahme
9 Beendet (KILLED)
10 Bus-Fehler
11 Segmentierungsfehler
12 Fascher Systemprozeduraufruf
13 Unterbrochene Pipe
14 Alarmuhr
15 Beendet
16 Signal 16
17 Signal 17
18 SohnprozeŞ verlassen
19 Neustart nach Stromausfall
20 Virtual Timer Alarm
21 Profiling Timer Alarm
22 Async E/A-Signal
23 Fenster-Signal
24 Gestoppt
25 Gestoppt
26 Fortgesetzt
27 Gestoppt (tty-Eingabe)
28 Gestoppt (tty-Ausgabe)
29 Signal 29
30 Signal 30
31 Signal 31
32 Signal 32
41 FEHLER: Warten auf Hintergrundjob!\n
42 FEHLER: ProzeŞ zweimal abgebrochen
43 Verarbeitung lÌuft
44 Ende %-16d
45 Verarbeitung beendet
46 FEHLER: status=%-9o
47  (core dumped)
48  (wd: 
49 (wd jetzt: 
50 Syntax: jobs [ -l ]
51 Falsche Signalnummer
52 Unbekanntes Signal; kill -l zeigt Signale an
53 %s: bereits gestoppt\n
54 Argumente sollten Kennungen von Jobs oder Prozessen sein
55 \nGestoppte Jobs vorhanden
56 Kein aktueller Job
57 Kein vorheriger Job
58 Kein solcher Job
60 Kein Job stimmt mit dem Muster Ïberein
61 Kein solcher Job
$set 14
4 Kann keine Pipe aufbauen
5 %s: Datei existiert
$set 15
1 Syntaxfehler
2 Fehlende )
3 Subscriptfehler
4 Subscript auŞerhalb des erlaubten Bereichs
5 Syntaxfehler
6 Syntax des Ausdrucks
7 Falsch formatierte Zahl
8 Keine Ûbereinstimmung
9 Keine weiteren Worte
10 Warnung: Pfad zu lang, abgeschnitten\n
11 Das Heimverzeichnis muŞ ein absoluter Pfad sein
$set 16
1 \nZu viele Namen in passwd-Datei!!\n
2 \nZu viele Dateien!!\n
3 Nicht genÏgend Speicher\n
$set 17
1 .\n
