$set 1
10 Interner Anrufer-Typ %s\n
11 mlock %s fehlgeschlagen\n
12 mlock %s durchgefÏhrt\n
13 Timeout bei generellem Úffnen\n
16 Generisches Úffnen (%d) fehlgeschlagen, errno = %d\n
19 %s nicht in der Datei der WÌhleinrichtung gefunden\n
22 gdial(%s) aufgerufen\n
23 dkcall(%s)\n
27 tcpdial Host %s,
28 AnschluÞ %d\n
29 Keine Socket-Schnittstelle: %s\n
31 Keine Socket-Schnittstelle, errno %d\n
34 Timeout in tcpopen\n
37 Familie: %d\n
38 AnschluÞ: %d\n
39 Adresse: %08x\n
40 Verbindng fehlgeschlagen: %s\n
42 Verbindung fehlgeschlagen, errno %d\n
45 unetdial Host %s,
46 AnschluÞ %d\n
47 tcpopen fehlgeschlagen: errno %d\n
48 ÚFFNEN FEHLGESCHLAGEN %s\n
50 COM1-RÏckgabewert = %d\n
52 Timeout bei sytek open\n
53 ÚFFNEN 2 FEHLGESCHLAGEN %s\n
54 mlock %s fehlgeschlagen\n
55 AnschluÞ %s verwenden,
56 acu - %s,
57 Telefonnummer  %s\n
58 Modem - %s versucht,
59 acu - %s,
60 Anruf von %s:
61 DURCHGEFÛHRT\n
62 FEHLGESCHLAGEN\n
63 %s kann nicht geÎffnet werden\n
64 %s ist geÎffnet\n
65 Timeout beim Úffnen des Modems\n
66 Wahl fehlgeschlagen. Sohnprozesse abgebrochen.\n
68 ACU-Schreibfehler %d\n
69 Anwahl durch Program %s\n
72 dcf ist %d\n
73 Fork-Status %o\n
74 DN-Schreibvorgang %s\n
75 Timeout
76 %s kann nicht geÎffnet werden\n
77 %s ist offen\n
78 %s kann nicht geÎffnet werden\n
79 dcf ist %d\n
80 ACU-Schreibfehler %d\n
81 ACU-Schreibvorgang ok%s\n
82 Úffnen der Verbindung %s\n
83 fehlgeschlagen
419 conn(%s)\n
420 getto ret %d\n
421 Anrufer schlieÞen (%d)\n
422 delock(%s)\n
423 Anruf fehlgeschlagen: %s\n
424 Es wird GerÌtetyp %s erwartet\n
425 Angeforderter GerÌtetyp existiert nicht\n
427 Falscher Zeitpunkt zum Anruf von: %s\n
428 ProtoStr = %s\n
430 ( erwartet
431 erhalten\n
432 Verbindung verloren, errno - %d\n
435 bereits ausreichend\n
436 erhalten\n
437 Zeit abgelaufen\n
438 BREAK\n
439 EOT\n
440 sendthem (
441 VERZÚGERUNG\n
442 <KEIN CARRIAGE RETURN>
443 <KEIN CARRIAGE RETURN - MITTE IGNORIERT>\n
444 PAUSE\n
445 ECHO CHECK AN\n
446 ECHO CHECK AUS\n
447 BREAK\n
448 ^M
449 )\n
524 fixline(%d,
525 %d)\n
527 fixline - direkt\n
529 setline - %c\n
530 sytfixline - Geschwindigkeit= %d\n
534 fixline(%d,
535 %d)\n
641 ulockf fehlgeschlagen in onelock()\n
642 ulockf Datei %s\n
643 Dateisperre--Lesen nicht mÎglich (errno %d) --entfernen!\n
644 Dateisperre--falsches Format--entfernen!\n
645 Dateisperre--ProzeÞ weiter aktiv--nicht entfernt\n
646 pid (%d) beenden (kill),
647 RÏckgabewert: %d
648 --bereit, um Dateisperre (%s) zu entfernen\n
649 ulockf in unlink() fehlgeschlagen\n
650 ulockf Datei %s\n
651 Dateisperre--lesen nicht mÎglich (errno %d) --entfernen!\n
652 --bereit, um Dateisperre (%s) zu entfernen\n
653 ulockf in unlink() fehlgeschlagen\n
657 Verbindung(%s,
658 %s)\n
1120 [-h] [-v] [-w n] [-x n] [-s Geschwindigkeit] Telnummer ...
1121 ct: %s kann nicht geÎffnet werden\n
1122 \tSyntax: %s %s\n
1123 (-w %s) Wartezeit muÞ > 0 sein\n
1124 \tSyntax: %s %s\n
1125 \tSyntax: %s %s\n
1126 Keine Telefonnummern angegeben!\n
1127 ct: Telefonnummer zu lang -- %s\n
1128 ct: Falsche Telefonnummer -- %s\n
1129 Der WÌhleinrichtung wurde %s baud zugeteilt\n
1130 Keine %s WÌhleinrichtungen auf diesem System\n
1131 %s aktiv
1132 WÌhleinrichtung ist
1133 WÌhleinrichtungen sind
1134  (%d Minute(n))\n
1135 Die (%d) %s WÌhleinrichtung%s aktiv\n
1136  ist
1137 en sind
1138 %d Minute%s warten\n
1139 n
1140 MÎchten Sie auf die WÌhleinrichtung warten? (y fÏr yes):
1141 Zeit (in Minuten)?
1142 Warten auf WÌhleinrichtung\n
1143 *** TIMEOUT ***\n
1144 Ende der Kommunikation bestÌtigen? (y fÏr Ende):
1145 Verbunden\n
1146 DrÏcken Sie die RÏcklauftaste
1147 Es liegt ein uugetty vor; beendet\n
1148 getty -h -t60 %s starten
1149 ct: Erstellen eines neuen Prozesses fÏr getty nicht mÎglich\n
1150 ct: getty kann nicht ausgefÏhrt werden\n
1151 \nNeue Verbindung?
1152 Verbindung(%d) trennen\n
1153 Verbindung getrennt\n
1154 cleanup(%d)\n
1155 chmod/chown %s\n
1156 chown/chmod auf %s nicht mÎglich
1157 nach %d\n
1158 ut_line %s,
1159 ut_user %s,
1160 ut_id %.4s,
1161 ut_pid %d\n
1162 ProzeÞ weiter aktiv\n
