$set 1
1 Syntax: %s [-s baud] [-l Verbindung] [-h] [-n] [-t] [-d Ebene] [-m] [-o|-e] Telnummer | 'dir' | remote\n
2 Unterbrechung
3 WÌhleinrichtung hÌngt
4 keine Antwort
5 UngÏltige Baud-Rate
6 acu-Problem
7 Verbindungsproblem
8 L-GerÌtedatei kann nicht geÎffnet werden
9 GerÌtedatei kann nicht geÎffnet werden
10 Angesprochenes GerÌt nicht verfÏgbar\r\n
11 Angesprochener GerÌt-/Systemname unbekannt\r\n
12 Kein GerÌt mit %d Baud verfÏgbar\r\n
13 kein GerÌt mit %d Baud bekannt\r\n
14 Verbindung fehlgeschlagen: %s\r\n
15 ErÎffnung nicht mÎglich: %s\r\n
16 Verbindung getrennt\r\n
17 Shell kann nicht ausgefÏhrt werden\r\n
18 Umleitung nicht mÎglich: %s\r\n
19 Verwende `~~' ,um Verbindung mit `~' aufzubauen\r\n
20 Zeichen vermiŞt\r\n
21 nach %ld Byte\r\n
22 %d Zeilen/%ld Zeichen\r\n
23 DateiÏbertragung unterbrochen\r\n
24 ProzeŞerzeugung nicht mÎglich -- versuchen Sie es spÌter\r\n
25 \r\nSonderzeichen `%#o' kann nicht Ïbertragen werden\r\n
26 \nZeile zu lang\r\n
27 r\nE/A-Fehler\r\n
28 Verwende `~$'-Befehl\r\n
29 Terminalstatus kann nicht ermittelt werden\r\n
30 Sie kÎnnen cu nicht von 3B-Konsole starten\r\n
31 Angeforderte Geschwindigkeit nicht korrekt\r\n
32 Angeforderter Systemname unbekannt\r\n
33 cu nicht mit Testeinrichtungsmarkierung Ïbersetzt\r\n
34 Bitte geben Sie die Nummer ein: 
35 Automatische Anwahl - bitte warten\r\n
36 Der Status des GerÌts kann nicht ermittelt werden
37 Anwendung von chown auf %s nicht mÎglich\n
38 Anwendung von chmod auf %s nicht mÎglich\n
39 uid %d kann nicht gesetzt werden\n
40 Verbunden\007\r\n
41 AusfÏhrung von '%s' fehlgeschlagen\r\n
42 Ûbertragung gestartet\n\r
43 Unterbrechung wÌhrend der Ûbertragung\n\r
44 tintr erhalten\n\r
46 Aufruf von tilde(%s)\r\n
47 Aufruf von shell(%s)\r\n
48 Aufruf von dopercen("%s")\r\n
50 Syntax: ~%%take von [nach]\r\n
55 Syntax: ~%%put von [nach]\r\n
58 Datei %s kann nicht geÎffnet werden\r\n
59 Eingabeumlenkung gestartet.\r\n
60 Eingabeumlenkung beendet.\r\n
61 Eingabeaufforderung = \\%03o \\%03o\r\n
62 Timeout = %d s.\r\n
63 Zeilen-Suffix = \\%03o \\%03o\r\n
64 Ausgabeumlenkung beendet.\r\n
65 Keine Ausgabeumlenkung aktiv.\r\n
66 Ausgabeumlenkung beendet.\r\n
67 Datei %s kann nicht geÎffnet werden.\r\n
68 Ausgabeumlenkung wird gestartet.\r\n
69 Wechsel nach %s nicht mÎglich\r\n
70 Wechsel nach %s nicht mÎglich\r\n
71 ~%%%s unbekannt fÏr cu\r\n
72 Schreibvorgang fehlgeschlagen\r\n
73 Empfang gestartet\r\n
74 \r\nTrÌger verloren\r\n
75 Anruf von mode(%d)\r\n
76 uid kann nicht gesetzt werden\r\n
77 gid kann nicht gesetzt werden\r\n
79 Lesefehler, nicht EINTR\n\r
80 Lesevorgang von fd=%d liefert %d zurÏck
81 Lesefehler, nicht EINTR\n\r
82 \ncu: Ausgabe blockiert\r\n
83 \ncu: Ausgabe blockiert\r\n
84 Aufruf von rcvdead(%d)\r\n
85 Aufruf von quit(%d)\r\n
86 Aufruf von bye(%d)\r\n
87 \r\nVerbindung getrennt\007\r\n
88 Aufruf von hangup(%d)\r\n
89 chown/chmod auf %s nicht mÎglich\n
90 \rGerÌtestatus fÏr fd=%d\r\n
91 Lokal
92 Datei Systems kann nicht geÎffnet werden\n
93 Datei L.sys kann nicht geÎffnet werden\n
