$set 1
1 dd: Falsches Argument %s\n
2 dd: %s kann nicht geÎffnet werden\n
3 dd: Datei kann nicht auf sich selbst kopiert werden\n
4 dd: %s kann nicht erstellt werden\n
5 dd: ZÌhlwerte dÏrfen nicht 0 sein\n
6 dd: Zu wenig Hauptspeicher\n
7 dd: Lesefehler
8 E/A-Fehler \n
9 %u+%u eingelesene DatensÌtze\n
10 %u+%u ausgegebene DatensÌtze\n
11 %u abgeschnittene DatensÌtze\n
12 \nFEHLER !! %s BereichsgrÎŞe Ïber 4GB !! \n
13 ioctl-Aufruf zur Ermittlung der PlattengrÎŞe fehlgeschlagen !!\n
14 ioctl-Aufruf zur Ermittlung der BlockgrÎŞe fehlgeschlagen !!\n
