$set 1
1 diff: Eingabedatei 
2 diff: -h unterstÏtzt nicht -e, -f, -n, -c, oder -I\n
3 diff: kein Speicherplatz mehr\n
4 diff: Dateien zu groŞ, versuchen Sie -h\n
5 Nur in %.*s: %s\n
6 Gemeinsame identische Dateien in %.*s und %.*s\n
7 BinÌrdateien unterscheiden sich in %.*s und %.*s\n
8 Gemeinsame Unterverzeichnisse von %.*s und %.*s\n
9 diff: Verzeichnis
10 Gemeinsame Unterverzeichnisse: %s und %s\n
11 Dateien %s und %s sind identisch\n
12 BinÌrdateien %s und %s sind unterschiedlich\n
13 diff: exec
14 diff: ProzeŞverzweigung fÏr pr:
15 Keine Unterschiede\n
16 diff: temporÌre Eingabedatei
18 diff: - kann nicht zusammen mit einem anderen Verzeichnis als Argument angegeben werden\n
19 Warnung : Kein Zeilenvorschub am Ende der Datei %s\n
21 diff: Warnung: -s oder -l nicht zusammen mit -e angeben\n
22 diff: ProzeŞverzweigung fÏr diff:
23 diff: Angabe nicht mÎglich: - -\n
24 Datei %s ist %s, Datei %s ist %s\n
25 Zeichenorientierte GerÌtedatei
26 Blockorientierte GerÌtedatei
27 FIFO-Datei
28 regulÌr
29 Verzeichnis
30 unbekannt
