$set 1
1 Syntax : dumpmsg Katalogdatei\n
2 Katalogdatei Œffnen : %s\n
3 Katalogdatei schlieﬁen : %s\n
4 Keine Meldungen in Katalogdatei\n
5 dumpmsg: %s: Keine Katalogdatei\n
6 %ld Meldungen in Katalogdatei\n
7 dumpmsg: %s: Falsche Katalogdatei\n
8 setnum : %d\n
9 msgnum : %d\n
10 length : %d\n
11 addr   : %d\n\n
12 dumpmsg: %s: Falsche Katalogdatei\n
13 setnum  : %d\n
14 msgnum  : %d\n
15 length  : %d\n
16 addr    : %d\n
17 message : %s\n\n
