$set 1
1 Schreiben oder Úffnen des Kanals fehlgeschlagen
2 Warnung: Erwarte `w'
3 Markierung kein Kleinbuchstabe
4 Eingabedatei kann nicht geÎffnet werden
5 PWB spec Problem
6 Es gibt nichts rÏckgÌngig zu machen
7 EingeschrÌnkte shell-Umgebung.
8 Ausgabedatei kann nicht erstellt werden
9 Kein Platz mehr im Dateisystem!
10 Datei kann nicht geÎffnet werden
11 Bindung nicht mÎglich
12 Bereichsende zu groŞ
13 Unbekannter Befehl
14 Suchzeichenkette nicht gefunden
15 -
16 Zeile auŞerhalb des Bereichs
17 Falsche Nummer
18 Falscher Bereich
19 UngÏltiger AdreŞwert
20 UnvollstÌndiger globaler Ausdruck
21 UngÏltiges Suffix
22 UngÏltiger oder fehlender Dateiname
23 Kein Leerzeichen nach dem Befehl
24 Erstellung eines neuen Prozesses fehlgeschlagen - erneuter Versuch
25 Maximal 64 Zeichen in Dateinamen
26 `\\ziffer' auŞerhalb des erlaubten Bereichs
27 Unterbrechung
28 Zeile zu lang
29 UngÏltiges Zeichen in der Eingabedatei
30 Fehler beim Schreiben
31 Nichtausreichender Speicher zum AnhÌngen
32 TemporÌre Datei zu groŞ
33 E/A-Fehler beim Bearbeiten der temporÌren Datei
34 Es sind nicht mehrere globale Angaben erlaubt
35 Globale Angabe zu lang
36 Keine Ûbereinstimmung
37 UngÏltiges oder fehlendes Trennzeichen
38 -
39 Ersatzzeichenkette zu lang
40 UngÏltige "Move"-Zielangabe
41 -
42 Keine bekannte Suchzeichenkette
43 '\\( \\)' Ungleichgewicht
44 Zu viele `\\(' s
45 Mehr als zwei Zahlen angegeben
46 '\\}' erwartet
47 Erste Zahl ist grÎŞer als die zweite
48 UnvollstÌndige Substitution
49 Neue Zeile nicht erwartet
50 '[ ]' Ungleichgewicht
51 Ûberlauf eines regulÌren Ausdrucks
52 Fehler in einem regulÌren Ausdruck
53 Es wird ein Befehl erwartet
54 a, i, oder c nicht in G erlaubt
55 Zeilenende erwartet
56 Keine bekannte Ersatzzeichenkette
57 Kein bekannter Befehl
58 UngÏltige Umleitung
59 MÎgliche konkurrierende Aktualisierung
60 Dieser Befehl verwirrt yed
61 Der x-Befehl wurde zu X (GroŞschreibung)
62 Warnung: 'w' kann Eingabedatei zerstÎren (aufgrund zuvor beim Einlesen aufgetretener ungÏltiger Zeichen)
63 Achtung: 'q' kann gepufferte Daten verlieren; 'w' kann Eingabedatei zerstÎren
65 -x Option ist nicht verfÏgbar
66 Dateiname zu lang
67 Diese Option ist nicht verfÏgbar
68  Null-Werte wurden ersetzt durch '\\0' 
69 \007Lesevorgang kann unvollstÌndig sein - Achtung!\007
70 Zeile zu lang: zno = 
71 Zeile zu lang: zno = 
72 zu lang
73 Tab-ZÌhler\n
75 Operation auf Socket-Schnittstelle nicht unterstÏtzt
