$set 1
1 %s: Sprache %s unbekannt. Standardsprache wird verwendet.\n
2 %s: Berechtigung verweigert\n
3 Abbruch, fifo-Datei %s kann nicht geŒffnet werden\n
4 Neustart, Konfigurationsdatei wird gelesen
5 Abbruch, fifo-Datei %s kann nicht geŒffnet werden\n
6 Abbruch, kein Lesezugriff auf fifo-Datei %s\n
7 Abbruch, Konfigurationsdatei %s offen fœr Lesefehler\n
8 Abbruch, Aktionsdatei %s offen fœr Schreibfehler\n
9 Abbruch, keine Ereigniszeile angegeben in %s fœr Zeile %d "%s"\n
10 Abbruch, keine Konfiguration angegeben %s\n
11 Abbruch, Ereignis %s doppelt angegeben in Datei %s\n
12 Abbruch, Konfigurationsdatei %s Syntaxfehler in Zeile "%s"\n
13 Temperatur liegt wieder im normalen Betriebsbereich des GerÃts.
14 ***** OVERTEMP_CRIT WARNING *****
15 Temperatur liegt œber Grenzwert fœr Normalbetrieb. €bertemperatur muﬁ behoben werden.
16 ***** OVERTEMP_EMERG WARNING *****
17 Temperatur liegt œber OVERTEMP_CRIT-Grenzwert. Muﬁ sofort behoben werden.
18 Interner Fehler: ungœltiger Wert %d an %s œbergeben.
19 Beendigung durch Signal %d\n
20 Syntax: %s [-f Konfigurationsdatei]\n
