$set 1
2 Pufferlesefehler
3 Name kann nicht gefunden werden\t
4 Eine Kopie eines Ihrer Editorpuffer wurde gesichert, als das System anhielt.\n
5 Eine Kopie eines Ihrer Editorpuffer wurde gesichert, als das Editorprogramm abgebrochen wurde.\n
6 Mit diesem Puffer war kein Name verbunden, so daﬁ er mit "LOST" bezeichnet wurde.\n
7 Eine Kopie eines Ihrer Editorpuffer Ihrer Datei "%s"\nwurde gesichert, als das System anhielt.\n
8 Eine Kopie eines Ihrer Editorpuffer Ihrer Datei "%s"\nwurde gesichert, als das Editorprogramm abgebrochen wurde.\n
9 Dieser Puffer kann erhalten werden, bei Verwendung des "recover"-Befehls des Editors\n
10 Eine einfache Vorgehensweise ist die Verwendung des Befehls "ex -r %s".\n
11 Dies funktioniert sowohl fœr "edit" als auch "vi".\n
