$set 1
1  Falsche Anzahl von Argumenten fœr exrecover
2 %a %h %d %T
3  [Datiert: %1$s, Neueste(s) von %2$d gesichert]
4  [Datiert: %s]
5  Kern nicht ausreichend fœr die Zeilen
6 Keine Dateien gesichert\n
7 %a %h %d
8 %H:%M
9 Am %1$s um %2$s wurden %3$d Zeilen der Datei "%4$s" gesichert\n
10  Datei nicht gefunden
11 Verlorene Zeilen
12 Verlorene Zeilen
13  TemporÃre Datei zu groﬁ
14 Systemfehler %d
