$set 1
1 Syntax: find Pfadliste [PrÌdikatliste]\n
2 find: 'pwd' kann nicht erhalten werden\n
3 find: ÛberprÏfungsfehler\n
4 find: Fehlende Verbindung\n
5 find: Ein Operand folgt einem Operanden\n
6 find: find -user %s nicht mÎglich\n
7 find: find -group %s nicht mÎglich\n
8 find: Erstellen von %s nicht mÎglich\n
9 find: Zugriff auf %s nicht mÎglich\n
10 find: Falsche Option %s\n
11 find: UnvollstÌndige Anweisung\n
14 find: Status von %s kann nicht ermittelt werden\n
15 find: %s %s nicht mÎglich\n
16 /dev/tty kann nicht zur Aufforderung nach weiteren Speichermedien geÎffnet werden\n
17 find: Schreiben nicht mÎglich %s: %s\n
19 Wenn Sie fortfahren wollen, geben Sie, wenn Sie bereit sind, GerÌt/Datei-Name ein\n
20 Der Benutzer gab einen NULL-Namen fÏr die nÌchste GerÌtedatei an\n
21 find: Úffnen nicht mÎglich %s: %s\n
22 Benutzer Îffnete Datei %s um fortzufahren\n
23 find: Falsche Angabe: -type %s\n
24 find: Falscher "-inum"-Wert %s\n
25 find: %s erfordert ein Argument\n
26 find: %s nicht durch ';' abgeschlossen\n
27 find: %s muŞ einen Befehl zur AusfÏhrung angeben\n
28 find: ungÏltiger Modus %s\n
40 mehr als 16 EintrÌge im Eintrag:
41 Eintrag beginnt nicht mit  "(" in Kurzform:
42 Eintrag endet nicht mit ")" in Kurzform:
43 Benutzername wurde im Eintrag nicht durch einen Punkt beendet:
44 Gruppenname wurde im Eintrag nicht korrekt beendet:
45 Kein Benutzername im Eintrag:
46 Kein Gruppenname im Eintrag:
47 UngÏltiger Benutzername im Eintrag:
48 UngÏltiger Gruppenname im Eintrag:
49 UngÏltiger Modus im Eintrag:
51 Unbekannter Fehler von strtoaclpatt():
55 find: 
56 find: UngÏltiger Dateisystemtyp %s\n
57 open
58 search
59 find: find -devcid %s nicht mÎglich\n
60 find: Wechseln des Verzeichnisses (chdir) zurÏck zu %s ist nicht mÎglich\n
61 find: Anwendung von -ncpio und -cpio auf dieselbe Datei ist nicht mÎglich\n
62 find: cpio E/A fehlgeschlagen --
63 find: %s erzeugt einen Kreis\n
64 Kein Fehler\n
65 Kein freier Speicherplatz\n
66 Unbekannter Dateityp\n
67 Fehler bei interner Pufferung\n
68 DateigrÎŞe hat sich geÌndert\n
69 Unbekannter Fehler (CPIO_%d)\n
