$set 1
1 (1001): Dateiende paŞt nicht zum Dateikopf fÏr
2 (1002): Datei %s
3 (1003): Sicherungskennung stimmt nicht mit erwartetem Wert Ïberein
4 (1004): Sicherungszeit stimmt nicht mit erwartetem Wert Ïberein
6 (1006): UngÏltiger Wert fÏr remote; gÏltige Werte fÏr Bit-Feld sind
7 (1007): Null oder Eins
8 (1008): Unbekannter Typ in Kopf- oder SchluŞinformation
9 (1009): Fortsetzung wird versucht
10 (1010): Unbekannte Kennung in Kopf- oder SchluŞinformation
11 (1011): Fortsetzung wird versucht
12 (1012): Unerlaubter Zugriff auf die Datei %s
13 (1013): Wechseln des Verzeichnisses (chdir) in %s nicht mÎglich.
14 (1014): UngÏltiger Wert fÏr remote; gÏltige Werte fÏr Bit-Feld sind
15 (1015): Wechseln des Verzeichnisses (chdir) in %s nicht mÎglich.
16 (1016): Null oder Eins
17 (1017): Wechseln des Verzeichnisses (chdir) in %s nicht mÎglich.
18 (1018): Status der Datei %s kann nicht ermittelt werden.
20 (1020): Block-PrÏfsummenfehler
21 (1021): Block-PrÏfsummenfehler
22 (1022): Status der Datei %s kann nicht ermittelt werden.
23 (1023): Datei %s existiert, ist aber kein Verzeichnis.
24 (1024): Verzeichnis %s kann nicht erstellt werden.
25 (1025): Bindungen der Datei %s kÎnnen nicht rÏckgÌngig gemacht werden.
26 (1026): mknod fÏr Datei %s nicht mÎglich.
27 (1027): mknod fÏr Datei %s nicht ausfÏhrbar
28 (1028): Veraltete Netzwerk-GerÌtedatei Ïbersprungen
29 (1029): Vorhandene Datei %s kann nicht in CDF gewandelt werden\n
30 (1030): Fehler (%s) beim Umbenennen des Verzeichnisses in %s\n
32 (1032): %s - Úffnen nicht mÎglich.
33 (1033): Datei %s kann nicht erstellt werden.
35 (1035): TemporÌrer Dateiname kann nicht erstellt werden.
36 (1036):  Datei wird Ïbergangen
37 (1037): Verbindung zwischen %s und %s nicht mÎglich: %s
38 (1038): Das System unterstÏtzt keine symbolischen Verbindungen.
39 (1039): Gesicherte Version von %s ist neuer.
40 (1040): Verbindung %s zuerst wiederherstellen.
41 (1041): Erstellung der Verbindung zwischen %s und %s nicht mÎglich.
42 (1042): Status der Link-Datei %s kann nicht ermittelt werden.
43 (1043): Fehler bei der Wiederherstellung der Kopfinformationen.
44 (1044): Fehler bei der Dateiwiederherstellung.
45 (1045): Fehler bei der Wiederherstellung der SchluŞinformationen.
46 (1046): Schreibfehler auf Residual-Datei.
47 (1047): E/A-Fehler beim Beschreiben der Datei %s
48 (1048): E/A-Fehler beim Beschreiben der Datei %s
50 (1050): Positionierung auf Neustartdatei nicht mÎglich.
51 (1051): Falscher DatentrÌger eingelegt.
52 (1052): Verbindungen von %s kÎnnen nicht rÏckgÌngig gemacht werden.
53 (1053): chmod Datei %s nicht mÎglich.
54 (1054): Zu viele Komponenten im Dateinamen %s
56 (1056): UngÏltige EintrÌge fÏr die Datei %s; ACLs nicht wiederhergestellt.
57 (1057): Laufwerksfehler beim Positionieren einer Schnellsuchmarkierung
58 (1058): Kein Schreibzugriff auf %s
59 (1059): Datei %s gefunden, aber aktiv/nicht wiederherstellbar
60 (1060): %s nicht auf DatentrÌger;\n\tFortsetzung mit %s und folgenden Dateien
61 (1061): Versuch, Wiederherstellung mit neuer Sicherungskennung fortzusetzen
62 (1062): Versuch, Wiederherstellung mit neuer Sicherungszeit fortzusetzen
63 (1063): ACL kann nicht erstellt werden: unbekannte Benutzerkennung fÏr Benutzer %s
64 (1064): ACL kann nicht erstellt werden: unbekannte Gruppenkennung fÏr Gruppe %s
65 (1065): Lesefehler bei Dateikopf
$set 2
102 (2102): Maximale Anzahl (%d) Wiederanpassungen Ïberschritten.
103 (2103): IOERROR bei einer Plattendatei. Verlasse frecover.
104 (2104): Lesevorgang der LÌnge Null aus Plattendatei. Verlasse frecover.
105 (2105): Erwartete Dateimarkierung nicht gefunden
107 (2107): E/A-FEHLER auf einem PlattengerÌt - frecover wird beendet
108 (2108): LÌnge Null vom PlattengerÌt gelesen - frecover wird beendet
109 (2109): Dateimarkierung wurde gelesen
110 (2110): Kontrollsatz wurde gelesen
111 (2111): DDS-Markierung wurde gelesen
112 (2112): Unerwartete DDS-Markierung wurde gelesen. Status:
113 (2113): SicherungsdatentrÌger kÎnnen nicht wiederangepaŞt werden
114 (2114): Fehler beim Lesen von EingabegerÌt (%s)
$set 3
203 (3203): Verbleibende Datei %s kann nicht geÎffnet werden
204 (3204): Verarbeitung ohne verbleibende Datei
205 (3205): Angegebene Optionen schlieŞen sich gegenseitig aus
206 (3206): Option '%c' erfordert ein Argument
207 (3207): ZusÌtzliches Argument: %s angegeben.
208 (3208): Mindestens eine der Angaben V, I, x, r, oder R muŞ angegeben werden
209 (3209): Sowohl X und F angegeben; F wird verwendet.
210 (3210): UngÏltige Option (-i/-e) wurde mit Option -r angegeben.
211 (3211): N-Option angegeben.	 %s wird ignoriert
237 (3238): Angegebene Optionen schlieŞen sich gegenseitig aus
241 (3241): Konfigurationsdatei %s kann nicht geÎffnet werden.
242 (3242): UngÏltiger Konfigurationsdateikennsatz (%s) ignoriert.
243 (3243): Fehler in der Konfigurationsdatei in Zeile %d.
244 (3244): Falsche Zeile:\n%s
245 (3245): Option '%c' nicht erkannt
246 (3246): Weitere nicht anwendbare Optionen bei Indexerfassung angegeben
247 (3247): Weitere nicht anwendbare Optionen bei DatentrÌgerkopf-Erfassung angegeben
248 (3248): i oder e fehlen in "graph"-Datei %s
249 (3249): "graph"-Datei %s kann nicht geÎffnet werden.
250 (3250): Kopfdaten-Datei %s des DatentrÌgers kann nicht geÎffnet werden.
251 (3251): Anzahl der Ausgabedateien darf nicht grÎŞer als MAXOUTFILES sein.\n
252 (3252): Fehler beim Erweitern des Ausgabedateimusters\n
253 frecover -r [-hosvymFNOX] [-c <Konfig.datei>] [-f <GerÌt>] [-S <Datei>]\n
254 frecover -R <Pfad> [-f <GerÌt>]\n
255 frecover -x [-hosvymFNOX] [-c <Konfig.datei>] [-e <Pfad>] [-f <GerÌt>]\n\
            [-g <Graph-Datei>] [-i <Pfad>] [-S <Datei>]\n
256 frecover [-I | -V] <Pfad> [-vy] [-f <GerÌt>] [-c <Konfig.datei]\n
257  -{r,x} - VollstÌndige bzw. teilweise Wiederherstellung\n
258  -{I,V} - Index bzw. Kopfsatz des DatentrÌgers nach <Pfad> schreiben\n
259  -{F,X} - Wiederherst. ohne Hierarchie bzw. relativ zum Arbeitsverzeichnis\n
260  -{i,e} - Pfadangabe, was einbezogen bzw. ausgeklammert werden soll\n
261  -{g,c} - Angabe einer Graph-Datei bzw. einer Konfigurationsdatei\n
262  -{N,h} - Nur verifizieren bzw. nur Verzeichnis wiederherstellen\n
263  -R     - Fortsetzen einer unterbrochenen Session\n
264  -f     - Angabe eines EingabegerÌts\n
265  -o     - Ûberschreiben existierender Dateien\n
266  -v     - Anzeigemodus\n
267  -y     - Positive Antwort auf alle Fragen\n
268  -S     - Angabe einer Datei fÏr Ïbersprungene BlÎcke\n
269  -s     - Wiederherstellungsmodus fÏr wenige Dateien\n
270  -O     - EigentÏmer wird der die Wiederherstellung startende Benutzer\n
271  -m     - Drucken der Markierungsinformation (PrÏfsummen, Dateimarkierungen)\n
$set 4
301 (4301): %s nicht von Sicherungsmedium zurÏckgeholt.
302 (4302): frecover unterbrochen, fortsetzen
303 (4303): MÎchten Sie den Status fÏr einen Neustart sichern?
304 (4304): automatisches '%s'\n
305 (4305): Nicht genÏgend Speicherplatz fÏr die Zuweisung.
306 (4306): Neustartdatei kann nicht erstellt werden, erneuter Versuch.
307 (4307): Neustartdatei kann nicht beschrieben werden.
308 (4308): Neustartdatei kann nicht erÎffnet werden.
309 (4309): Neustartdatei kann nicht gelesen werden.
310 frecover(4310): Absoluter Pfadnamen fÏr eine Datei zur Sicherung des Status :
311 (4311): OBSCURE node kann nicht gelesen werden.
312 (4312): OBSCURE node kann nicht gesichert werden.
$set 5
401 (5401): DatentrÌger %d fertiggestellt.
402 (5402): GerÌt %s kann nicht geschlossen werden.
403 (5403): GerÌt unter %s kann nicht geÎffnet werden oder wird nicht erkannt\n
404 frecover(5404): RÏcklauftaste, wenn nÌchster DatentrÌger in %s: bereit\n
405 (5405): %s kann nicht geÎffnet werden.
406 (5406): MÎchten Sie weitermachen?
407 (5407): Abbruch
408 (5408): Kein "fbackup"-DatentrÌger; DatentrÌgername nicht lesbar.
409 (5409): DatentrÌgerkopf nicht lesbar.
410 frecover(5410): RÏcklauftaste, wenn voriger DatentrÌger in %s: bereit\n
411 (5411): MÎchten Sie es mit einem anderen DatentrÌger versuchen?
412 (5412): MÎchten Sie diesen DatentrÌger retten?
413 (5413): Versuch, Sicherungskopie nach fehlerhaftem DatentrÌgerkopf zu lesen
414 (5414): Abbruch
418 (5418): Kein "fbackup"-DatentrÌger; DatentrÌgerkopf nicht lesbar.
419 (5419): PrÏfsumme des DatentrÌgerkopfes ist fehlerhaft.
420 (5420): Kein "fbackup"-DatentrÌger; "magic"-Wert ist fehlerhaft.
421 (5421): DatentrÌgerkennung entspricht nicht aktueller Session.
422 (5422): Fehlerhafte Sicherungskopie beim Neustart ausgewÌhlt.
423 (5423): Falscher DatentrÌger eingelegt.
424 (5424): DatentrÌger %d erwartet, %d erhalten
425 (5425): Indexdatei kann nicht geÎffnet werden.
426 (5426): Lesefehler beim Versuch, den Index zu lesen. Wird Ïbersprungen.
427 (5427): Zugeordnetes Terminal kann nicht erÎffnet werden.
429 (5429): Beim Sichern dieses DatentrÌgers war die Umgebungsvariable LC_COLLATE\noder LANG auf %s gesetzt. ZurÏckladen erfordert gleiche Einstellungen. \nRÏcksetzung auf %s.
430 (5430): /tmp/sampipe kann nicht geÎffnet werden.
431 (5431): Beim Sichern dieses DatentrÌgers waren die Umgebungsvariablen LANG und\nLC_COLLATE nicht gesetzt. Setzen Sie die Variablen LANG und LC_COLLATE zurÏck,\nund versuchen Sie es noch einmal.
432 (5432): Fehler beim ZurÏckspulen des DatentrÌgers
433 (5433): MÎchten Sie mit diesem DatentrÌger weiterarbeiten?
434 (5434): Versuch der Synchronisation nach dem DatentrÌgerkopf.
435 (5435): malloc-Fehler beim Versuch, den Index zu lesen
436 (5436): malloc-Fehler: zu wenig virtueller Hauptspeicher fÏr fastsearch.\nFortsetzung ohne fastsearch.
437 (5437): GerÌtedatei %s nicht gefunden\n
