$set 1
1 Syntax: gencat [ -l ] Katalogdatei Dateien ...\n
2 gencat: %s: Keine Katalogdatei\n
3 gencat: %s: Falsche Katalogdatei\n
4 gencat: %s: Falsche Katalogdatei\n
5 "%s", Zeile %ld: Falsche Gruppennummer\n
6 "%s", Zeile %ld: Falsche Gruppennummernfolge\n
7 "%s", Zeile %ld: Falsche LÎschgruppennummer\n
9 "%s", Zeile %ld: Keine Meldungsnummer\n
10 "%s", Zeile %ld: Meldung zu lang\n
12 "%s", Zeile %ld: Falsche Meldungsnummer\n
13 "%s", Zeile %ld: Falsche Meldungsnummernfolge\n
14 "%s", Zeile %ld: Falsches Trennsymbol\n
15 "%s", Zeile %ld: Falsche Meldung\n
16 "%s", Zeile %ld: Falsche LÎschmeldungsnummer\n
18 "%s", Zeile %ld: Fehlendes Zeichen zur Meldungsabgrenzung\n
