$set 1
1 grep  [-E|-F] [-cbilnqsvx] [-e Ausdruck [-e Ausdruck] ... | -f Datei]\n [Ausdruck] [Datei ...]\n egrep [-cbilnqsvx] [-e Ausdruck [-e Ausdruck] ... | -f Datei]\n [Ausdruck] [Datei ...]\n fgrep [-cbilnqsvx] [-e Ausdruck [-e Ausdruck] ... | -f Datei]\n [Ausdruck] [Datei ...]
2 %s: %s kann nicht geŒffnet werden\n
3 Syntax:\n %s\n
4 %s: %s kann nicht geŒffnet werden\n
5 %s: RE-Fehler %d: 
101 Unbekannter regexp-Fehlercode!!
102 Ungœltiges Vergleichselement angesprochen.
103 Nachfolgende \\ im Muster.
104 \\n im Muster gefunden.
105 Zu viele \\( \\) Paare oder ( ) zu tief verschachtelt.
106 Zahl in \\Ziffer ungœltig oder auﬁerhalb des erlaubten Bereichs.
107 [ ] Ungleichgewicht.
108 \\( \\) oder ( ) Ungleichgewicht.
109 \\{ \\} Ungleichgewicht.
110 Ungœltiges Vergleichsende in [ - ]-Ausdruck.
111 €berlauf eines regulÃren Ausdrucks.
112 Zahl zu groﬁ in \\{ \\}-Konstrukt.
113 Ungœltige Zahl in \\{ \\}-Konstrukt.
114 Mehr als 2 Zahlen in \\{ \\}-Konstrukt.
115 Erste Zahl ist grŒﬁer als zweite in \\{ \\}.
116 Ungœltige Zeichenklasse angegeben.
117 Keine bekannte Suchzeichenkette.
118 Verdoppelungsoperator an falscher Position.
119 Leerer Ausdruck angegeben.
