$set 1
1 Syntax: %s -f Voncode -t Nachcode [Dateien ...]\n
2 GrŒﬁe der Konvertierungstabelle kann nicht ermittelt werden\n
3 Kein Platz fœr die Konvertierungstabelle\n
4 Konvertierung kann nicht initialisiert werden\n
5 Falsches Eingabezeichen\n
6 Konvertierung kann nicht abgeschlossen werden\n
7 %s nach %s Konvertierung bildet die folgenden Zeichen ab:\n
8 ROMAN8: \\x%x %-25sISO8859/1: \\x%x %-25s\n
9 ISO8859/1: \\x%x %-25sROMAN8: \\x%x %-25s\n
10 NA (nicht verwenden)
11 Kein "break space"
12 Accent Grave
13 Linkes einfaches Anfœhrungszeichen
14 Accent Circumflex
15 Caret
16 Tilde accent
17 Tilde
18 Italienisches Lirasymbol
19 Pfundzeichen
20 Overline
21 Macron
22 HollÃndische Gulden
23 Kleingeschriebenes f
24 Groﬁgeschriebenes S (caron)
25 Groﬁgeschriebenes S
26 Kleingeschriebenes s (caron)
27 Kleingeschriebenes s
28 Groﬁgeschriebenes Y umlaut
29 Groﬁgeschriebenes Y
30 Horizontaler Balken
31 Bindestrich
32 Kasten
33 Sternchen
34 NA (nicht verwenden)
35 Kein "break space"
40 Kein "break space"
41 NA (nicht verwenden)
42 gebrochener Balken
43 Senkrechte Linie
44 Copyright Zeichen
45 Kleingeschriebenes c
46 Kein Vorzeichen
47 Tilde
48 Soft hyphen
49 Bindestrich
50 Eingetragenes Warenzeichen
51 Groﬁgeschriebenes R
52 Macron
53 Top bar
54 €berschrift zwei
55 Ziffer zwei
56 €berschrift drei
57 Ziffer drei
58 Cedille
59 Komma
60 €berschrift eins
61 Ziffer eins
62 Multiplikationszeichen
63 Kleingeschriebenes x
64 Divisionszeichen
65 Solidus
