$set 1
1 /usr/keysh/C/softkeys
2 /usr/keysh/C/keyshrc
3 /usr/keysh/C/help
4 /usr/keysh/builtins
5 /.softkeys
6 /.keyshrc
7 
8 
9 
10 %s: [10] Terminfo-Initialisierung fehlgeschlagen; prÏfe $TERM.\n
11 %s: [11] FÏhre /bin/ksh... aus\n
12 %s: [12] Fahre ohne Terminfo fort...\n
13 [13] Funktionstaste %q kann in Datei %q nicht ermittelt werden.\n
14 [14] Funktionstaste %q kann nicht ermittelt werden.\n
15 [15] %q Ïberschrieben; vorausgegangene Ønderungen kÎnnen verloren gehen.\n
16 [16] %q kann nicht geschrieben werden; Ønderungen kÎnnen nicht gesichert werden.\n
17 [17] %q kann nicht entfernt werden; keine Ønderung.\n
18 [18] Syntaxfehler in Konfigurationsdatei -- ignoriert.\n
19 [19] Funktionstastendatei %q kann nicht geÎffnet werden.\n
20 [20] Unbekannter Benutzer %q.\n
21 [21] Fehler in Funktionstastendatei %q, Zeile %d, Zeichen %d.\n
22 [22] (Neuer Funktionstastenknoten erwartet; %q gefunden.)\n
23 [23] (Funktionstastenattribute erwartet; %q gefunden.)\n
24 [24] (";" erwartet; %q gefunden.)\n
25 [25] ("}" erwartet; Zeilenende gefunden.)\n
26 [26] (Code ungleich Null erwartet; %q gefunden.)\n
27 [27] Zu viele Fehler; restliche Funktionstasten werden Ïbersprungen.\n
28 [28] %s PrÏffehler bei Funktionstaste %q nahe Zeichen %d.\n
29 [29] Funktionstastendatei geÌndert; Hilfe kann nicht gelesen werden.\n
30 [30] Konfiguration kann nicht von %q oder %q gelesen werden.\n
31 
32 
33 
34 
35 
36 
37 
38 
39 
40 --Hilfe--
41 HILFE
42 --Mehr--
43 MEHR
44  von 
45 Sie haben neue Nachrichten erhalten
46 Sie haben Nachrichten erhalten
47 Keine Nachrichten
48 
49 
50 WÌhlen Sie eine Funktionstaste oder drÏcken Sie die RÏcklauftaste, um Hilfe in diesem Kontext zu erhalten.
51 Sorry.  Es steht keine Hilfe fÏr diese Taste zur VerfÏgung
52 Sorry.  Es stehen keine Hinweise fÏr diese Taste zur VerfÏgung.
53 Sorry.  Keine Hilfe verfÏgbar.
54 Funktionstaste ist deaktiviert.
55 help
56 WÌhlen Sie das Thema, fÏr die Sie Hilfe benÎtigen...
57 (Themen)
58 ENDE
59 
60 Keysh_config
61 kc
62 Dann, geben Sie ein Leerzeichen ein.
63 tsm-
64 UnvollstÌndig...
65 
66 WÌhlen Sie eine Option; dann 
67 WÌhlen Sie eine Option oder 
68 an dieser Stelle nicht erlaubt.
69 
