$set 1
1 Syntax: ln [-f] [-i] [-s] f1 f2\n	  ln [-f] [-i] [-s] f1 ... fn d1\n
2 Syntax: ln [-f] [-i] f1 f2\n	     ln [-f] [-i] f1 ... fn d1\n
3 ln: Kein Zugriff auf %s\n
4 ln: <%s> Verzeichnis\n
5 ln: %s/%s: Name zu lang\n
6 ln: %s und %s sind identisch\n
7 ln: %s: %o%c Modus (%s/%s) 
8 ln: Bindung von %s kann nicht rœckgÃngig gemacht werden\n
9 ln: Anderes Dateisystem\n
10 ln: Keine Berechtigung fœr %s\n
11 ln: Zu viele Bindungen nach %s\n
12 ln: %s bereits vorhanden\n
