$set 1
1 LC_COLLATE kann nicht gesetzt werden\n
2 LC_CTYPE kann nicht gesetzt werden\n
3 Standardeingabe kann nicht wieder ge蝔fnet werden\n
4 Syntax:\tlocaledef [-c] [-f <Umsetzdatei>] [-i <Eingabedatei>] <L.bereichsname>\n
5 oder\tlocaledef -d [-o <Format>] <Lokalisierungsbereichsname>\n
6 oder\tlocaledef -n <Eingabedatei>\n
7 Fehlersuchdatei kann nicht ge蝔fnet werden\n
9 Eingabedatei %s kann nicht ge蝔fnet werden\n
10 Keine 'langname'-Angabe\n
11 Keine 'langid'-Angabe\n
12 Angaben in 'langname' und 'langid' nicht vereinbar\n
13 Angaben in 'isfirst' und 'byte_chars' nicht vereinbar\n
14 WARNUNG: Angegebene Reihenfolge wird ignoriert\n
15 LC_ALL-Kategorie 蟗erschreitet zul蘳sige Maximalgr无e\n
16 LC_MESSAGES-Kategorie 蟗erschreitet zul蘳sige Maximalgr无e\n
17 LC_COLLATE-Kategorie 蟗erschreitet zul蘳sige Maximalgr无e\n
18 LC_CTYPE-Kategorie 蟗erschreitet zul蘳sige Maximalgr无e\n
19 LC_MONETARY-Kategorie 蟗erschreitet zul蘳sige Maximalgr无e\n
20 LC_NUMERIC-Kategorie 蟗erschreitet zul蘳sige Maximalgr无e\n
21 LC_TIME-Kategorie 蟗erschreitet zul蘳sige Maximalgr无e\n
22 Datei 'locale.inf' kann nicht erstellt werden\n
23 localedef-Fehler: ung蟣tiges Schl蟬selwort in Zeile %d\n
25 localedef-Fehler: ung蟣tiges Zeichen in Zeile %d\n
26 localedef-Fehler: ung蟣tige Aussage in Zeile %d\n
27 localedef-Fehler: ung蟣tiger Ausdruck in Zeile %d\n
28 localedef-Fehler: ung蟣tiger Bereich in Zeile %d\n
29 localedef-Fehler: ung蟣tige langname-L蘮ge in Zeile %d\n
30 localedef-Fehler: ung蟣tige langid-Nummer in Zeile %d\n
31 localedef-Fehler: ung蟣tige L蘮ge des Sprachennamens in langname in %d\n
32 localedef-Fehler: ung蟣tige Gebietsnamenl蘮ge in langname %d\n
33 localedef-Fehler: ung蟣tige codeset-Namensl蘮ge in langname in Zeile %d\n
34 localedef-Fehler: ung蟣tige Versionsangabenl蘮ge in Zeile %d\n
36 localedef-Fehler: ung蟣tiger Zeichencode in Zeile %d\n
37 localedef-Fehler: ung蟣tiger isfirst-Zeichencode in Zeile %d\n
38 localedef-Fehler: ung蟣tiger issecond-Zeichencode in Zeile %d\n
39 localedef-Fehler: ung蟣tige code_scheme-Namensl蘮ge %d\n
40 localedef-Fehler: ung蟣tiger code_cscheme-Name %d\n
41 localedef-Fehler: ung蟣tige cswidth-Zeichenfolgenl蘮ge %d\n
42 localedef-Fehler: ung蟣tiges cswidth-Zeichenfolgenformat %d\n
43 localedef-Fehler: ung蟣tige langinfo-Zeichenfolgenl蘮ge %d\n
44 localedef-Fehler: ung蟣tige monetary-Zeichenfolgenl蘮ge %d\n
45 localedef: ung蟣tige L蘮ge der Ziffernfolge %d\n
46 localedef-Fehler: ung蟣tige L蘮ge der Modifier-Zeichenfolge %d\n
47 localedef-Fehler: malloc() fehlgeschlagen \n
48 localedef-Fehler: 踒erlauf der Priorit蘴swarteschlange \n
49 localedef-Fehler: yes- und no-Zeichenfolgen k蝞nen nicht zugleich mit %d beginnen\n
50 localedef-Fehler: ung蟣tige L蘮ge der Zeitraum-Zeichenfolge %d\n
51 localedef-Fehler: ung蟣tiges Format der Zeitraum-Zeichenfolge %d\n
52 localedef-Fehler: zu viele Zeitraum-Zeichenfolgen angegeben %d\n
53 localedef-Fehler: angegebenes Symbol nicht gefunden %d\n
58 localedef-Fehler: Umsetzungsdatei nicht gefunden \n
60 localedef-Fehler: Symbol dupliziert %d\n
63 localedef-Fehler: Mehr als COLL_WEIGHTS_MAX angegeben in Zeile %d\n
68 localedef-Warnung: angegebenes Symbol nicht gefunden %d\n
72 localedef-Warnung: Schl蟬selwort nicht unterst蟭zt %d\n
73 localedef-Warnung: Falsche ctype-Initialisierung - Korrektur vorgenommen \n
74 Angaben in 'langname' und 'langid' sind nicht vereinbar
75 Warnung: Vom Benutzer definierte Sprache erfordert langid von 901 bis 999\n
76 Vom Benutzer definierte Sprache erfordert langid von 901 bis 999
77 Angaben in 'langname' und 'langid' sind nicht vereinbar
78 Lesefehler auf Datei: 
79 Fehler bei 'lseek' auf Datei: 
80 Tempor蘲e Datei %s kann nicht ge蝔fnet werden\n
81 Fehler beim Interpretieren der Umsetzungsdatei\n
82 Fehler im Lokalisierungsbereich: ung蟣tige Zeile in LC_COLLATE-Kategorie: %d\n
