$set 1
1 Syntax: %s Ziel ...\n
2 Ïbernehme
3 Ziel "%s" nicht verfÏgbar
4 Ziel "%s" verschwunden!
5 Ziel "%s" Ïbernahm bereits AuftrÌge
6 Ziel "%s" Ïbernimmt nun AuftrÌge\n
7 Spooler-Verzeichnis existiert nicht
$set 2
1 Syntax: cancel Id ... Drucker ...\n
2 Klasse kann nicht wieder gestartet werden
3 "%s" ist keine Auftragskennung und kein Drucker
4 Drucker "%s" nicht verfÏgbar!
5 Drucker "%s" war nicht aktiv
6 Auftrag "%s-%d" abgebrochen\n
7 Ihre Druckeranfrage %1$s-%2$d wurde abgebrochen von %3$s.
8 Auftrag "%s-%d" abgebrochen\n
9 Auftrag "%s-%d" abgebrochen\n
10 Ihre Druckeranfrage %1$s-%2$d wurde abgebrochen von %3$s.
11 Spooler-Verzeichnis existiert nicht
12 Auftrag "%s-%d" nicht abgebrochen: nicht EigentÏmer\n
13 Remote-Abbruchbefehl %s kann nicht ausgefÏhrt werden.\n
14 Fehler %d aufgetreten.\n
15 "%s" ist kein Drucker oder eine Klasse
16 Sie mÏssen Root-Berechtigung haben, um diese Option verwenden zu kÎnnen\n
22 Syntax: cancel Id ... Drucker ... -a -e -uBenutzer\n
23 AuftrÌge kÎnnen mit folgenden Optionen abgebrochen werden:\n
24 Kennung    - Auftrag mit der angegebenen Kennung\n
25 Drucker    - Auftrag auf dem angegebenen Drucker\n
26 -a	      - alle AuftrÌge des Benutzers auf dem angegebenen Drucker\n
27 -e	      - alle AuftrÌge in der Druckerwarteschlange\n
28 -uBenutzer - die AuftrÌge der angegebenen Benutzer auf dem angegebenen\n		Drucker\n
29 Maximale Anzahl an FernauftrÌgen Ïberschritten. Auftrag "%s-%d" nicht abgebrochen.\n
30 Maximale Anzahl an FernauftrÌgen Ïberschritten. Auftrag "%s" nicht abgebrochen.\n
31 \t-i	     - Abbruch nur lokaler AuftrÌge\n
$set 3
1 %b %2d %H:%M
$set 4
1 Syntax: %s [-c] [-r[ursache]] drucker ...\n
2 unbekannte Option "%s"
3 Drucker "%s" existiert nicht
4 Keine Drucker angegeben
5 Drucker "%s" nicht verfÏgbar!
6 Drucker "%s" war bereits deaktiviert
7 Auftrag "%s-%d" abgebrochen\n
8 Ursache unbekannt
9 Drucker "%s" jetzt deaktiviert\n
10 Ihr Druckauftrag %1$s-%2$d wurde abgebrochen durch %3$s.
11 Spooler-Verzeichnis existiert nicht
12 Auftrag "%s-%d" nicht abgebrochen: nicht EigentÏmer\n
$set 5
1 Syntax: %s drucker ...\n
2 eingeschaltet
3 Drucker "%s" existiert nicht
4 Drucker "%s" nicht verfÏgbar!
5 Drucker "%s" war bereits eingeschaltet
6 Drucker "%s" jetzt eingeschaltet\n
7 Spooler-Verzeichnis existiert nicht
$set 6
1 Spooler-Verzeichnis existiert nicht
2 Ûbernahmestatus von Ziel "%s" unbekannt
3 AuftrÌge fÏr Ziel "%1$s" -\n\t%2$s kÎnnen nicht Ïbernommen werden
4 Falsche PrioritÌt %d
5 Kein/e solche/r Drucker oder Klasse "%s"
6 Datei %s im CLASS-Verzeichnis kann nicht geÎffnet werden
7 Auftragsdatei %s kann nicht erstellt werden
8 TemporÌre Datei %s kann nicht erstellt werden
9 %s Ziel "%s" nicht erlaubt
10 Standard-Zieldatei kann nicht erstellt werden
11 Kein Systemstandardziel
12 Standardziel "%s" existiert nicht
13 Aktuelles Verzeichnis kann nicht gelesen werden
14 Datei %s kann nicht geÎffnet werden
15 Neue Sequenznummerndatei %s kann nicht geÎffnet werden
16 Zu viele Optionen fÏr das Schnittstellenprogramm
17 Warnung: cluster-Servername nicht gefunden
18 Ziel "%s" existiert nicht
19 Falsche StandardprioritÌt in %s/%s fÏr Drucker: %s
20 Kein Zugriff auf Datei "%s"
21 "%s" ist ein Verzeichnis
22 Datei "%s" ist leer
24 Auftrag nicht Ïbernommen
25 %d Dateien
26 %d Datei
27  und
28 Standardausgabe
29 Auftragskennung ist %1$s (%2$s%3$s%4$s)\n
30 Auftragskennung %s nicht in Warteschlange eingetragen\n
31 Standardeingabe ist leer
34 Zu viele Dateien - Job aufgliedern\n
$set 7
1 Drucker "%1$s" ist kein Mitglied der Klasse "%2$s"
2 Mitgliederdatei kann nicht geÎffnet werden
3 Klassendatei kann nicht geÎffnet werden
4 BeschÌdigte Mitgliederdatei
5 Drucker "%1$s" bereits in Klasse "%2$s"
6 Neue Mitgliederdatei kann nicht erstellt werden
7 Neue Klassendatei kann nicht erstellt werden
8 Neue Druckerstatusdatei kann nicht erstellt werden
9 Neue Ûbernahmestatusdatei kann nicht erstellt werden
10 Neues Schnittstellenprogramm kann nicht erstellt werden
11 Neues Auftragsverzeichnis kann nicht erstellt werden
12 Druckerstatuseintrag fÏr "%s" nicht verfÏgbar
13 Ziel "%s" existiert nicht
14 Drucker "%s" existiert nicht
15 Drucker kann nicht erstellt werden "%s" -- dies ist ein existierender Klassenname
16 Klasse kann nicht erstellt werden "%s" -- dies ist ein existierender Druckername
17 "%s" ist ein ungÏltiger Zielname
18 Neue Drucker erfordern -v und entweder -e, -i oder -m
19 Steuerzeichen "-%c" und "-%c" stehen im Widerspruch zueinander
20 Steuerzeichen -e, -i und -m kÎnnen nur getrennt verwendet werden
21 Klasse "%s" existiert nicht
22 Model "%s" existiert nicht
23 Kein Zugriff auf Datei "%.50s"
24 Auftragsverzeichnis kann nicht entfernt werden
25 Drucker kann nicht entfernt werden
26 AuftrÌge fÏr "%s" weiter in Warteschlange eingetragen  -- lpmove verwenden
27 Klassendatei kann nicht entfernt werden
28 -"%c" und -"%c" Steuerzeichen haben denselben Wert
29 Kann nicht ausgefÏhrt werden - Scheduler ist aktiv
30 Aktuelles Verzeichnis kann nicht gelesen werden
31 Aktuelles Verzeichnis kann nicht gelesen werden
32 Systemstandardzieldatei kann nicht geÎffnet werden
33 Neuer Drucker\r 
34 Neues Ziel\r 
35 UngÏltiges Steuerzeichen "%c"\r 
36 Unbekanntes Steuerzeichen "-%c"
37 Steuerzeichen "%c" verlangt einen Wert
38 LP Verwalter nicht in Kennwortdatei\n
39 Benutzerkennung kann nicht auf die LP-Verwalterbenutzerkennung gesetzt werden
40 Spooler-Verzeichnis existiert nicht
41 Syntax: lpadmin -p Drucker [-v GerÌt] [-c Klasse] [-r LKlasse]\n
42		   [-e Drucker|-i Schnittstelle|-m Modell] [-h|-l]\n
43	   lpadmin -d[Ziel]\n
44	   lpadmin -x Ziel\n
45 Statusmodell "%s" existiert nicht
46 Abbruchmodell "%s" existiert nicht
47 Kein Argument fÏr ob3
48 Argument fÏr orc muŞ 'y' oder 'n' sein, nicht %s
49 Neues Abbruchschnittstellenprogramm kann nicht erstellt werden
50 Neues Statusschnittstellenprogramm kann nicht erstellt werden
51 UngÏltige Taste "%s"
52	  \t	   [-oci Schnittstelle|-ocm Modell] [-ob3]\n
53	  \t	   [-osi Schnittstelle|-osm Modell] [-orc]\n
54	  \t	   [-orm Rechner|-orp Drucker]\n
55 Falsche PrioritÌt %d
56 cnode "%s" existiert nicht
57 Schnittstelle "%s"  kann nicht als CDF erstellt werden
58 Schnittstelle kann nicht auf angegebenen Cluster gestellt werden
59 a
60	  \t	   [-a cluster_client]\n
$set 8
1 Syntax:\t%s Ziel1 Ziel2\n\t\t-oder-\n\t%s Auftrag ... Ziel\n
2 LP-System beschÌdigt
3 Scheduler ist weiter aktiv - keine Verarbeitung
4 Ziel "%s" existiert nicht
5 Zielangaben stimmen Ïberein
6 Insgesamt %1$d AuftrÌge von %2$s nach %3$s Ïbertragen\n
7 "%s" ist keine Auftragskennung
8 Insgesamt %1$d AuftrÌge nach %2$s Ïbertragen\n
9 Auftragsverzeichnis %s kann nicht geÎffnet werden
10 Auftrag %s kann nicht Ïbertragen werden
11 Auftrag "%s-%d" existiert nicht
12 Auftragsdatei %s kann nicht geÎffnet werden
13 Auftrag %s-%d kann nicht Ïbertragen werden
14 Auftrag %s-%d kann nicht Ïbertragen werden
15 alle AuftrÌge Ïbertragen nach
16 Ziel %s Ïbernimmt kein AuftrÌge\n
17 Ûbertragung wird bearbeitet ...\n
18 Spooler-Verzeichnis existiert nicht
$set 9
1 Versuch des Úffnens einer Datei, die nicht mehr existiert. seqno ist %d\n
2 Úffnen und Sperren von "%s" nicht mÎglich\n
3 CLASS-Verzeichnis kann nicht geÎffnet werden
4 Datei %s in CLASS-Verzeichnis kann nicht geÎffnet werden
5 Nichtexistierender Drucker %s in Klasse %s
6 Auftragsverzeichnis %s kann nicht geÎffnet werden
7 TemporÌre Ausgabewarteschlange kann nicht geÎffnet werden
8 Links der alten Ausgabewarteschlange kÎnnen nicht rÏckgÌngig gemacht werden
10 ***** %s GESTOPPT *****\n
11 Deaktiviert durch den Scheduler:
12 Druckerschnittstellenprogramm kann nicht ausgefÏhrt werden (errno=%d)\n
13 \tSOHN: %s  %s %d %.4x\n
14 Schreiben nach %s nicht mÎglich
15 %s kann nicht geÎffnet werden
16 stderr kann nicht wieder geÎffnet werden
17 Kein Zugriff auf FIFO
18 FIFO kann nicht geÎffnet werden
19 MEMBER-Verzeichnis kann nicht geÎffnet werden
20 %s Datei in MEMBER-Verzeichnis kann nicht geÎffnet werden
21 Fehlercode %d in Auftrag %s-%d auf Drucker %s
22 Druckauftrag %s-%d wurde auf Drucker %s ausgegeben
23 Fehler in Druckauftrag %s-%d
24 Deaktiviert durch Scheduler: Anmeldebildschirm
25 Nichtexistierender Drucker %s in PSTATUS
26 \tFIFO: %s  %s\n
27 lpsched: Protokoll kann nicht erstellt werden
28 ***** LP-PROTOKOLL: %s *****\n
29 FIFO: '%s' ?
30 Auftragsdatei "%s" kann nicht geÎffnet werden
31 TemporÌre Auftragsdatei "%s" kann nicht erstellt werden
32 Auftragsdatei "%s" kann nicht erstellt werden
33 Datendatei "%s" kann nicht Ïbertragen werden
35 TemporÌre Auftragsdatei "%s" kann nicht geÎffnet werden
36 Eintrag fÏr StrukturprioritÌt "%d" kann nicht ermittelt werden
37 Eintrag entfernt aus Druckerstatusdatei
38 Spooler-Verzeichnis existiert nicht
39 LP-Verwalter nicht in Kennwortdatei
40 LP-Verwalter nicht in geschÏtzter Kennwortdatei
41 PrÏfmarkierung des LP-Verwalters kann nicht gesetzt werden
42 Benutzerkennung kann nicht auf die Benutzerkennung des LP-Verwalters gesetzt werden
43 Neuer ProzeŞ kann nicht erstellt werden
44 kill: ungÏltige pid %d bei %s\n
45 Unerwartete RÏckkehr aus Wartestatus\n
46 \tFIFO: Ziele --\n
47 \tFIFO: %s: %s %s %s %s\n
48 p
49 c
50 aktiviert
51 nicht aktiviert
52 aktiv
53 nicht aktiv
54 kein Drucken
55 Drucken auf %s
56 \tFIFO: \t%d: %d %s %s zeit:%d %s host %s\n
57 seqno(3)
58 seqno(4)
59 \tFIFO:\t%d: %d %s %s zeit:%d\n
60 \tFIFO: Drucker --\n
61 pid und id unbekannt
62 pid=%d, id=%s-%d
63 \tFIFO: \t%s %s\n
64 \tFIFO: \t\t%s\n
65 \tFIFO: Klassen --\n
66 \tFIFO: \t%s\n
68 Syntax: %s [-v] [-a]\n
69 Unbekannte Option "%s"
70 Pipe kann nicht verbunden werden
71 Schreib-Pipe kann nicht geschlossen werden
72 Scheduler konnte nicht gestartet werden
73 Scheduler war bereits aktiv
74 Scheduler ist eingeschaltet
75 Kein Zugriff auf SCHEDLOCK
$set 10
1 Spooler-Verzeichnis existiert nicht
2 Scheduler gestoppt\n
3 Scheduler nicht eingeschaltet
$set 11
1 Unbekannte Option "%s"
3 Systemstandardziel: %s\n
4 Kein Systemstandardziel\n
6 Remote-Statusbefehl %s kann nicht ausgefÏhrt werden.\n
7 Fehler %d ist aufgetreten.\n
8 Es kann kein weiterer Speicher belegt werden, um mehr AuftrÌge verarbeiten zu kÎnnen.\n
9 "%s" ist keine Auftragskennung und kein Ziel
13  auf %s
14 
16  von %s
17 %-*s %-*s PrioritÌt %d  %s%s%s\n
18 (Standardeingabe)
19	      
20 %-4d Kopien
21 \t%-*s	   %s
22  %*ld Byte\n
23  ??? Byte\n
24 Ziel "%s" existiert nicht
25 %1$s Ïbernommene AuftrÌge seit %2$s\n
26 %1$s nicht Ïbernommene AuftrÌge seit %2$s -\n\t%3$s\n
27 Drucker "%s" existiert nicht
28 (Anmelde-Terminal)
29 %s-%d wird gerade an %s gesendet. Eingeschaltet seit %s
30 %1$s-%2$d wird gerade gedruckt. Eingeschaltet seit %3$s
32 Keine Verarbeitung. Eingeschaltet seit %1$s
33 Ausgeschaltet seit %1$s -\n\t%2$s
34 Drucker %1$s %2$s%3$s\n
35 \tGrenzprioritÌt : %d\n
36 MEMBER-Verzeichnis nicht verfÏgbar!
38 GerÌt fÏr %1$s: %2$s
39 Drucker "%s" nicht verfÏgbar!
40 CLASS-Verzeichnis nicht verfÏgbar!
41 Klasse "%s" existiert nicht
42 Mitglieder der Klasse %s:\n
43 Klasse "%s" nicht verfÏgbar!
44 Scheduler ist eingeschaltet\n
45 Scheduler ist nicht eingeschaltet\n
46 Spooler-Verzeichnis existiert nicht
47 Nicht genug Platz fÏr alle Benutzernamen\n
48 Nicht hinzugefÏgter Benutzername ist %s\n
53 %s Datei im MEMBER-Verzeichnis kann nicht geÎffnet werden
54 Kein GerÌt im MEMBER-Verzeichnis angegeben
55 Status des GerÌtes %s kann nicht ermittelt werden
56 Aktuelle Zeit kann nicht ermittelt werden
57 execlp fehlgeschlagen
60     entfernt an: %1$s auf %2$s \n
$set 12
2 Ausgabewarteschlangendatei kann nicht geÎffnet werden
$set 13
2 Druckerstatusdatei kann nicht geÎffnet werden
$set 14
2 Ûbernahmestatusdatei kann nicht geÎffnet werden
$set 15
1 Syntax: %s [-r[ursache]] zeil ...\n
2 Unbekannte Option "%s"
3 Ziel "%s" existiert nicht
4 Keine Ziele angegeben
5 Ziel "%s" nicht verfÏgbar
6 Ursache unbekannt
7 Ziel "%s" wird nicht weitere AuftrÌge Ïbernehmen\n
8 Ziel "%s" hat keine AuftrÌge mehr Ïbernommen\n
9 Spooler-Verzeichnis existiert nicht
$set 16
1 \nlp: %s\n
$set 17
2 Druckerstatusdatei kann nicht geÎffnet werden
$set 18
1 Spooler-Verzeichnis existiert nicht
2 Ihr Name ist zu lang
3 Der Anmeldename "-all" ist reserviert
4 Zu viele Benutzer
6 Zu viele AuftrÌge
7 rcancel: Es wurde kein Drucker angegeben
8 Syntax: rcancel [-a] [Drucker] [-uBenutzer] [Ids]\n
$set 19
1 Spooler-Verzeichnis existiert nicht
2 Zu viele Benutzer
3 Zu viele AuftrÌge
4 rlpstat: Es wurde kein Drucker angegeben
5 Syntax: rlpstat [-d Drucker] [-u Benutzer] [Kennungen]\n
$set 20
3 Spooler-Verzeichnis existiert nicht
4 Kein AusfÏhrung - Scheduler ist eingeschaltet
5 Kein solcher Drucker "%s"
6 Grenzwert muŞ zwischen 0 und 7 liegen
7 Syntax : %s Drucker grenzwert\n
$set 21
1 Spooler-Verzeichnis existiert nicht
2 Annahmestatus des Ziels "%s" unbekannt
3 Anforderungen fÏr Ziel "%s" kÎnnen nicht angenommen werden -\n\t%s
4 Scheduler lÌuft nicht. Ønderung fehlgeschlagen.
5 Neue Anforderungskennung %s-%d: Eintrag in Warteschlange fehlgeschlagen\n
6 Neue Anforderungskennung ist %s-%d\n
7 Eintrag in Warteschlange fehlgeschlagen\n
8 Anforderung "%s-%d" existiert nicht
9 Anforderung "%s-%d" unverÌndert: nicht EigentÏmer (owner)
10 Neue Sequenznummerdatei "%s" kann nicht geÎffnet werden
11 UngÏltiger SchlÏsselbuchstabe "%c"
12 Ziel "%s" existiert nicht
13 SchlÏsselbuchstabe erwartet nicht Argument "-%c%s"
14 Zu viele Optionen fÏr Schnittstellenprogramm
15 UngÏltige PrioritÌt "-%c%s"
16 Unbekannter SchlÏsselbuchstabe "-%c"
17 Syntax: lpalt id [-dZiel] [-m] [-nZahl] [-oOption]\n\t[-pPrioritÌt] [-s] [-tTitel] [-w]\n
18 Neues Ziel darf nicht mit altem Ziel identisch sein
$set 22
1 Syntax: %s [-d Ziel] [Dateiname]\n
2 %s: %s kann nicht geÎffnet werden\n
3 %s: Protokolldatei-Formatfehler\n
4 %s: Speicherbelegungsfehler\n
5 Performance-Analyse wurde von %h.%d '%y %H:%M
6  bis %h.%d '%y %H:%M durchgefÏhrt\n
7 ---Drucker	  -Wartezeit--	 -Druckzeit-	---Byte----   -Sum- Anzahl\n
8     /Klassen--     AV	    SD	   AV	  SD	  AV	 SD	 KB AuftrÌge\n
