$set 1
1 Dateiname erforderlich, kein Pfadname.
2 Wert muﬁ zwischen 0 und 65535 liegen.
3 Wert muﬁ zwischen 1 und 65535 liegen.
4 Wert muﬁ zwischen 1 und 65535 liegen.
5 Genau einer davon ist anzugeben.
6 Mindestens einer davon ist anzugeben.
7 Muﬁ 1 oder 2 sein.
8 Muﬁ grŒﬁer als 0 sein.
9 Kann nur verwendet werden, wenn "-l" angegeben wurde.
10 Gespiegeltes leeres logisches Volume nicht erstellbar. "-l" angeben.
11 Muﬁ entweder 0 oder 1 sein.
12 "%s": Platten-Label kann nicht gelesen werden, Plattentyp angeben:\n
13 "%s": Plattenpartition kann nicht ermittelt werden.\n
14 "%s": Partition `%c' ist nicht verfœgbar.\n
15 "%s": kein "character device".\n
16 "%s": kein logisches Volume.\n
17 LVM-Datensatz wird geschrieben
18 Verzeichnis ungœltiger BlŒcke wird bereinigt
19 Zu viele ungœltige BlŒcke.\n
20 Verzeichnis ungœltiger BlŒcke wird erstellt
21 DEFECT01-EintrÃge werden geschrieben
22 ist einzugeben.
23 ist einzugeben.
24 muﬁ eine "block special"-Datei sein.
25 "-p" und "-s" kŒnnen nur bei "-a y" verwendet werden.\n
26 Interne Kennung der Volume-Gruppe "%s" konnte aus "%s" nicht gelesen werden.\n
27 "PhysicalExtentSize" muﬁ eine Zweierpotenz zwischen 1 und 256 sein.
28 Wert muﬁ zwischen 1 und 255 liegen.
29 Volume-Gruppe "%s" existiert nicht in der Datei "%s"\n , ist aber im File-System vorhanden. Fortsetzung nicht mŒglich.\n
30 Volume-Gruppe "%s" existiert bereits in der Datei "%s".\n
31 Volume-Gruppe "%s" konnte nicht erstellt werden:\n
32 Fehler beim Schreiben von "%s" und "%s" in "%s".\n
33 "%s" konnte nicht in den Hauptspeicher eingelesen werden.\n
34 Physisches Volume "%s" konnte durch LVM-GerÃtetreiber nicht gelŒscht werden.\n Inkonsistenz zwischen Informationen in File-System\n und Datei "%s" fœr Volume-Gruppe "%s":\n
35 Status der Volume-Gruppe "%s" konnte nicht ermittelt werden:\n
36 Volume-Gruppe "%s" ist nicht aktiv. Nur aktive Volume-Gruppe\n kann erweitert werden.\n
37 Physisches Volume "%s" konnte nicht gelŒscht werden, da es\n entweder fehlt oder nicht verknœpft ist.\n
38 Physisches Volume "%s" konnte nicht gelŒscht werden, da einige\n seiner physischen Bereiche noch benutzt werden.\n
39 Physisches Volume "%s" konnte nicht aus Datei "%s" gelŒscht werden.\n Inkonsistenz zwischen LVM-GerÃtetreiber und\n Datei "%s".\n
40 "%s" wird erstellt.\n
41 "%s" wird gelŒscht
42 "%s" wird wiederhergestellt
43 "%s" wird in "%s" gespeichert
44 Muﬁ eine Zahl sein.
45 Ungœltiger Wert. Gœltige Werte sind "%s".
46 Programmfehler. UnzulÃssiger Gebrauch der Optionsroutinen.
47 Option mehrmals verwendet.
48 Ungœltige Option.
49 Optionen mit Werten dœrfen nicht mit anderen Optionen gemischt werden.
50 Nach der Option ist ein Wert anzugeben.
51 Weitere Argumente erforderlich.
52 Kein Zeichen nach '-'.
53 Physisches Volume "%s" konnte zu "%s" nicht hinzugefœgt werden und\n wurde daher auch der Volume-Gruppe nicht hinzugefœgt.\n
54 Physisches Volume "%s" ist bereits in der Datei "%s" registriert.\n
55 Physisches Volume "%s" ist keine "block special"-Datei.\n
56 Zu viele physische Volumes in PhysicalVolumePath. Mindestens\nein physisches Volume muﬁ in Volume-Gruppe verbleiben.\n
57 Physisches Volume "%s" konnte nicht installiert werden.\n
58 Physisches Volume "%s" wurde LVM-GerÃtetreiber angegeben,\n konnte aber "%s" nicht hinzugefœgt werden.\n LVM ist inkonsistent.\n
59 Volume-Gruppe "%s" existiert nicht in Datei "%s".\n
60 Steuerdatei "%s" kann nicht geŒffnet werden:\n
61 Ungœltiger Pfad "%s".\n
62 Verzeichnis "%s" konnte nicht geŒffnet werden:
63 Status des physischen Volumes "%s" konnte nicht ermittelt werden:\n
64 Physisches Volume "%s" konnte nicht geŒffnet werden:\n
65 Physisches Volume "%s" konnte nicht abgefragt werden:\n
66 Warnung: Physisches Volume "%s" konnte nicht abgefragt werden:\n
67 Physisches Volume konnte nicht gelŒscht werden:\n
68 Logisches Volume "%s" konnte nicht gelŒscht werden:\n
69 Physisches Volume konnte nicht abgefragt werden:\n
70 Zuordnungsliste des physischen Volumes konnte nicht abgefragt werden:\n
71 Zuordnungsliste des logischen Volumes konnte nicht abgefragt werden:\n
72 Eindeutige Kennung fœr Volume-Gruppe "%s" konnte nicht gesetzt werden:\n
73 Volume-Gruppe "%s" konnte nicht inaktiviert werden:\n
74 Volume-Gruppe "%s" konnte nicht aktiviert werden:\n
75 Volume-Gruppe "%s" konnte nicht abgefragt werden:\n
76 Logisches Volume konnte nicht abgefragt werden:\n
77 Logisches Volume "%s" konnte nicht abgefragt werden:\n
78 Logisches Volume konnte nicht reduziert werden:\n
79 Warnung: Physisches Volume "%s" konnte nicht an Volume-Gruppe \n angekoppelt werden:\n
80 Logisches Volume konnte nicht erweitert werden:\n
81 Inhalt des logischen Bereichs konnte nicht aktualisiert werden:\n
82 Veraltete Partitionen des logischen Volumes nicht synchronisierbar:\n
83 Kein Zugriff auf Liste physischer Volumes fœr Volume-Gruppe "%s".\n
84 Kein Zugriff auf Liste logischer Volumes fœr Volume-Gruppe "%s".\n
85 Liste physischer Volumes konnte nicht abgefragt werden.\n
86 Liste logischer Volumes konnte nicht abgefragt werden.\n
87 Informationen œber physisches Volume "%s" konnten nicht gedruckt werden.\n
88 Informationen œber logisches Volume "%s" konnten nicht gedruckt werden.\n
89 verfœgbar
90 nicht verfœgbar
91 Volume-Gruppe, der physisches Volume "%s" \n angehŒrt, konnte nicht gefunden werden.\n
92 Volume-Gruppe, der logisches Volume "%s" \n angehŒrt, konnte nicht gefunden werden.\n
93 nein
94 ja
95 Aus "%s" konnte kein Volume-Gruppenname gelesen werden.\n
96 Volume-Gruppe "%s" kann nicht angezeigt werden.\n
97 Logisches Volume "%s" kann nicht angezeigt werden.\n
98 Physisches Volume "s%" kann nicht angezeigt werden.\n
99 Aktuelles Arbeitsverzeichnis konnte nicht aufgerufen werden
100 Name der Volume-Gruppe, der logisches Volume "%s"\n angehŒrt, kann nicht ermittelt werden.\n
101 Fœr logisches Volume kann kein Name generiert werden.\n
102 Logisches Volume mit Namen "%s" wird erstellt.\n
103 Volume-Gruppe "%s" wurde erstellt.\n
104 Logisches Volume "%s" wurde mit\n minor number %d erstellt.\n
105 Physisches Volume "%s" wurde erstellt.\n
106 Logische Bereiche des logischen Volumes "%s" werden œbertragen...\n
107 Physisches Volume "%s" wurde verschoben.\n
108 Logisches Volume "%s" existiert bereits.\n
109 Status der Volume-Gruppe "%s" konnte nicht ermittelt werden.\n Die major number, die beim Erstellen logischer Volumes genŒtigt\n wird, konnte daher nicht abgerufen werden.\n
110 Logisches Volume "%s" konnte nicht erstellt werden:\n
111 Logisches Volume "%s" konnte nicht als \n "special file" im File-System angelegt werden:\n
112 Logisches Volume "%s" konnte nicht aus dem \n LVM-GerÃtetreiber gelŒscht werden.\n Daher Inkonsistenz zwischen GerÃtetreiber und File-System:\n
113 read-only (nur Lesezugriff)
114 read/write (Lese- und Schreibzugriff)
115 available/stale (verfœgbar/veraltet)
116 available/syncd (verfœgbar/synchronisiert)
117 unavailable (nicht verfœgbar)
118 on (ein)
119 off (aus)
120 on (ein)
121 off (aus)
122 strict (geregelt)
123 non-strict (offen)
124 sequential (sequentiell)
125 parallel (parallel)
126 available (verfœgbar)
127 unavailable (nicht verfœgbar)
128 stale (veraltet)
129 current (aktuell)
130 missing (fehlt)
131 stale (veraltet)
132 current (aktuell)
133 free (frei)
134 "%s" ist kein logisches Volume.\n
135 Minor number des logischen Volumes "%s" kann nicht ermittelt werden.\n
136 Vom LVM-GerÃtetreiber konnte die aktuelle Einstellung \n des logischen Volumes "%s" nicht ermittelt werden:\n
137 Volume-Gruppe "%s" wurde geÃndert.\n
138 Logisches Volume "%s" wurde geÃndert.\n
139 Logisches Volume "%s" konnte nicht geÃndert werden:\n
140 Logisches Volume "%s" konnte nicht geÃndert werden. \nTreiber hat falsche Anzahl an Spiegelinformationen:\n
141 Physisches Volume "%s" wurde geÃndert.\n
142 Physisches Volume "%s" konnte nicht geÃndert werden:\n
143 Die Volume-Gruppe, der das logische Volume "%s" angehŒrt,\n konnte nicht gefunden werden. Eventuell ist der Pfad des \n logischen Volumes falsch.\n
144 "MirrorCopies\" parameter \"%d\" must be larger than existing number \"%d\".\n
145 "LogicalExtentsNumber" liegt nicht œber aktuellem Wert.\n
146 "LogicalExtentsNumber" liegt œber zulÃssigem Maximalwert.\n
147 Volume-Gruppe "%s" wurde erweitert.\n
148 Logisches Volume "%s" wurde erweitert.\n
149 Volume-Gruppe "%s" wurde reduziert.\n
150 Logisches Volume "%s" wurde reduziert.\n
151 Logisches Volume "%s" ist nicht reduziert.\n
152 Volume-Gruppe "%s" wurde gelŒscht.\n
153 Logisches Volume "%s" wurde gelŒscht.\n
154 Zuordnungsliste des logischen Volumes "%s" \n konnte nicht abgerufen werden.\n
155 Zuordnungsliste des physischen Volumes "%s" \n konnte nicht abgerufen werden.\n
156 Die Liste des physischen Volumes, das der Volume-Gruppe\n "%s" angehŒrt, konnte nicht abgerufen werden.\n
157 Physisches Volume "%s" gehŒrt nicht\n der Volume-Gruppe "%s" an.\n
158 Nicht genœgend freie physische Bereiche verfœgbar.\nLogisches Volume "%s" konnte nicht erweitert werden.\n
159 Fehler eventuell auf strikte Zuordnungsvorschrift zurœckzufœhren\n
160 LVM-GerÃtetreiber konnte logisches Volume "%s".\n nicht erweitern.\n
161 Bei strikter (STRICT) Zuordnungsvorschrift kann eine physisches \n Volume nicht mit zwei neuen Spiegelungen versehen werden.\n
162 \"MirrorCopies\" parameter \"%d\" must be smaller than existing \
number \"%d\".\n
163 "LogicalExtentNumber" liegt nicht unter aktuellem Wert;\n daher werden keine logischen Bereiche entfernt.\n
164 Durch Reduzierung eines logischen Volumes kŒnnen wertvolle Daten \n verlorengehen; soll Befehl wirklich ausgefœhrt werden (j/n) : 
165 Logisches Volume "%s" ist nicht leer;\nsoll das logische Volume wirklich gelŒscht werden (j/n) : 
166 Physisches Volume beinhaltet ein File-System.\nFortfahren? (j/n) : 
167 Physisches Volume gehŒrt bereits einer Volume-Gruppe an\n
168 LVM-GerÃtetreiber konnte das logische Volume "%s" \n nicht reduzieren.\n
169 LVM-GerÃtetreiber konnte Spiegelungen auf \nlogischem Volume "%s" nicht reduzieren.\n
170 Logisches Volume "%s" ist aktiv und kann daher nicht gelŒscht werden.\n
171 Das dem logischen Volume "%s" entsprechende "special file" \n konnte nicht aus dem File-System gelŒscht werden. \n Da das logische Volume dem LVM-GerÃtetreiber nicht mehr bekannt ist, \n sollte es mit den œblichen UNIX-Befehlen \n (chmod(1), rm(1)) \n gelŒscht werden.\n
172 Die Namen der physischen Volumes, die Volume-Gruppe "%s" angehŒren, \n konnten nicht abgerufen werden.\n
173 Die Namen der logischen Volumes, die Volume-Gruppe "%s" angehŒren, \n konnten nicht abgerufen werden.\n
174 Zuordnung ist bei physischem Volume "%s" unzulÃssig.\n
175 Das physische Quell-Volume gehŒrt auch den\nphysischen Ziel-Volumes an.\n
176 Volume-Group "%s" beinhaltet kein logisches Volume.\n
177 Logisches Volume "%s" gehŒrt nicht\nVolume-Gruppe "%s" an.\n
178 Volume-Gruppe "%s" kann nicht geŒffnet werden.\n
179 Kein freier physischer Bereich fœr logischen Bereich %d\n auf logischem Volume "%s".\n
180 Warnung: Physisches Volume "%s" fehlt.\n
181 Volume-Gruppe "%s" konnte nicht gelŒscht werden.\n
182 Volume-Gruppe "%s" ist noch aktiv.\n
183 Volume-Gruppe "%s" enthÃlt noch logisches Volume.\n
184 Volume-Gruppe "%s" enthÃlt noch mehrere physische Volumes.\n
185 Zweig "%s" des File-Systems konnte nicht gelŒscht werden.\n
186 Eintrag "%s" konnte nicht aus "%s" gelŒscht werden.\n
187 Re-synchronisierte Volume-Gruppe "%s".\n
188 Re-synchronisiertes logisches Volume "%s".\n
189 Volume-Gruppe "%s" konnte nicht re-synchronisiert werden.\n
190 Logisches Volume "%s" konnte nicht re-synchronisiert werden.\n
191 Entweder keine physischen Volumes angekoppelt oder keine \n gœltigen VGDAs auf physischen Volumes gefunden.
192 Zu wenig Kernel-Speicher zur Abarbeitung der Anfrage.
193 I/O-Fehler beim Lesen der VGDA.
194 Quorum nicht vorhanden oder physische Volumes fehlen.\n
195 Teil des Pfads des physischen Volumes nicht vorhanden.
196 Pfad des physischen Volumes bezieht sich auf nicht existentes GerÃt \n oder ist nicht im Kernel konfiguriert.
197 Ungœltiges ioctl fœr GerÃt - Befehl wurde auf logisches Volume-GerÃt \nstatt auf SteuergerÃt angewandt.
198 Die angegebene minor number bezieht sich auf ein nicht existierendes \n logisches Volume.
199 Volume-Gruppe nicht aktiviert.
200 Vor der Reduzierungsanforderung fehlt gœltige ZuordnungslŒschung.
201 Die angegebene minor number bezieht sich auf ein bereits existierendes \n logisches Volume.
202 Pfad gibt kein gœltiges physisches Volume an.
203 Physisches Volume kann nicht gelesen werden.
204 Fœr physisches Volume ist kein Treiber konfiguriert.
205 Zu wenig Platz im Volume fœr VGRA.
206 Berechtigung bei PfadŒffnung fœr physisches Volume verweigert.
207 Pfad des physischen Volumes bezeichnet kein "block device".
208 Die angegebene minor number bezieht sich auf ein nicht existierendes \n logisches Volume.
209 Das angegebene logische Volume ist offen.
210 Das angegebene logische Volume existiert nicht.
211 Ein vom Extent Array beschriebener physischer Bereich wird bereits benutzt.
212 Fœr physisches Volume ist kein Treiber konfiguriert.
213 Schreibzugriff auf GerÃt verweigert.
214 Pfad bezeichnet eine Datei, die kein "block device" ist.
215 Ein Teil des Pfads ist nicht zugÃnglich.
216 Volume-Gruppe nicht aktiviert.\n
217 An Volume-Gruppe "%s" konnten nicht\nalle dazugehŒrigen physischen Volumes angekoppelt werden.\n
218 Warning: Couldn't deattach the physical volume \"%s\"\nfrom the volume group.\n
219 Datei "%s" konnte nicht gelŒscht werden:
220 Verzeichnis "%s" konnte nicht gelŒscht werden:
221 VG Name
222 VG Status
223 Max LV
224 Akt LV
225 ⁄ffn LV
226 Max PV
227 Akt PV
228 Tats PV
229 PE GrŒﬁe
230 Max PE pro PV
231 Summe PE
232 Zuord PE
233 Freie PE
234 VGDA
235 LV Name
236 VG Name
237 LV Berechtig
238 LV Status
239 Schreibprœf
240 Spiegelungen
241 Ablaufplan
242 Aktuelle LE
243 Zugeordn PE
244 Ungœlt Block
245 Zuordnung
246 Benutzt PV
247 PV Name
248 VG Name
249 PV Status
250 Zuzuordnen
251 VGDA
252 Akt LV
253 PE GrŒﬁe
254 Summe PE
255 Freie PE
256 Zugeord PE
257 Veralt PE
258 LE
259 PV1
260 PE1
261 Status 1
262 PV2
263 PE2
264 Status 2
265 PV3
266 PE3
267 Status 3
268 PE
269 Status
270 LV
271 LE
272 PV Name
273 LE in PV
274 PE in PV
275 LV Name
276 LE von LV
277 PE fœr LV
278 Volume-Gruppen
279 Logische Volumes
280 Physische Volumes
281 Logische Bereiche
282 Physische Bereiche
283 Verteilung logisches Volume
284 Verteilung physisches Volume
285 Der angegebene Pfad entspricht nicht dem an diese \n Volume-Gruppe angekoppelten physischen Volume
286 Volume-Gruppe ist nicht aktiviert
287 Ungœltiger Eingabeparameter\n
288 Anzahl der Spiegelungen kann nicht erhŒht werden, da das logische \nVolume keine logischen Bereiche zugeordnet hat.\n
289 Warnung: Physisches Volume "%s" ist nicht \nfœr Zuordnung verfœgbar.\n
290 Neu zugeordneten Spiegelungen werden jetzt synchronisiert. Dieser \n Vorgang dauert etwas lÃnger. Bitte warten ....\n
$set 2
1 HP-IB- und Nicht-HP-IB-GerÃte kŒnnen nicht gemischt werden.\n
2 Spiegelung auf HP-IB-GerÃten nicht durchfœhrbar.\n
3 Defekte BlŒcke kŒnnen auf HP-IB-GerÃten nicht verschoben werden.\n
4 Summe PVG
5 Physische Volume-Gruppen
6 VG Name
7 PVG Name
8 PV Name
9 PVG-strikt
10 Volume-Gruppe "%s" wurde Datei "%s" nicht hinzugefœgt.\n
11 Physische Volume-Gruppe "%s" ist bereits in Volume-Gruppe "%s" definiert.\n
12 Physische Volume-Gruppe "%s" wurde Volume-Gruppe "%s" nicht hinzugefœgt.\n
13 Physische Volume-Gruppe "%s" wurde erstellt.\n
14 Fehler aufgetreten; physische Volume-Gruppe "%s" nicht erstellt.\n
15 Ziel-PVG "%s" enthÃlt keine PVs.\n
16 PVG-striktes LV nicht erstellt, weil VG "%s" in "%s" nicht definiert.\n
17 Striktere Zuordnungsvorschrift nicht anwendbar, da \n LV "s%" Spiegelkopien enthÃlt.\n
18 PVG "%s" ist in VG "%s" nicht definiert.\n
19 Fehler eventuell durch PVG-strikte Zuordnungsvorschrift verursacht.\n
20 VG "%s" ist in Datei "%s" nicht definiert.\n
21 PVG "%s" konnte nicht hinzugefœgt werden.\n
22 PVG "%s" konnte nicht erweitert werden.\n
23 Physische Volume-Gruppe "%s" wurde erweitert.\n
24 Fehler aufgetreten; physische Volume-Gruppe "%s" nicht erweitert.\n
25 Physisches Volume "%s" konnte nicht aus Datei "%s" gelŒscht werden.\n
26 Physisches Volume "%s" wurde aus physischer \n Volume-Gruppe "%s" gelŒscht.\n
27 Volume-Gruppe "%s" konnte nicht aus Datei "%s" gelŒscht werden.\n
28 Volume-Gruppe "%s" wurde aus Datei "%s" gelŒscht.\n
29 Datei "%s" fehlt.\n
30 Beim Erstellen der Datei "%s" wurde ein Fehler entdeckt.\n
31 Beim Lesen aus der Datei "%s" wurde ein Fehler entdeckt.\n
32 Beim Schreiben in die Datei "%s" wurde ein Fehler entdeckt.\n
33 Fehlerhafte Datei "%s": VG-Schlœsselwort fehlt.\n
34 Fehlerhafte Datei "%s": VG "%s" hat kein PVG.\n
35 Fehlerhafte Datei "%s": PVG-Schlœsselwort fehlt.\n
36 Fehlerhafte Datei "%s": PVG "%s" hat kein PV.\n
37 Informationen in "%s" anders als in "%s".\n
38 Fehlerhafte Datei "%s": Ungœltiger Pfad "%s".\n
39 Fehlerhafte Datei "%s": PVG hat keinen Namen in VG "%s".\n
40 Logisches Volume konnte nicht wieder zugeordnet werden:\n
41 Fehlerhafte Datei "%s": PVG "%s" ist in VG "%s" doppelt definiert.\n
42 Fehlerhafte Datei "%s": PV "%s" in "%s" ist in VG "%s" doppelt definiert.\n
43 Inkonsistenz zwischen Datei "%s" und Datei "%s".\n
44 Die logischen Volumes befinden sich nicht in derselben Volume-Gruppe.\n
45 Dem logischen Ziel-Volume sind bereits Bereiche zugeordnet: %s\n
46 Logisches Quell-Volume verfœgt œber keine Bereiche: %s\n
47 Nicht genœgend Spiegelungen fœr Teilungskopie: %s\n
48 Logisches Volume "%s" wurde geteilt.\n
49 Logische Volumes "%s" und "%s"\nsind unterschiedlich groﬁ.\n
50 Logisches Volume "%s" darf keine weitere Spiegelkopie haben.\n
51 Logisches Volume "%s" wurde verschmolzen mit \nlogischem Volume "%s".\n
52 Achtung: Spiegelungen sind im LV "%s" aufgrund \n unsachgemÃﬁem Shutdown eventuell inkonsistent.\n
53 Alle Bereiche in LV "%s", LX "%d" sind STALE (veraltet).\n
54 Bereiche in LV "%s" konnten nicht auf STALE (veraltet) gesetzt werden.\n
55 Spiegelkonsistenz fœr LV "%s" konnte nicht wiederhergestellt werden.\n
56 Daemon "%s" wurde zur Synchronisation der Spiegelungen fœr \n "%s" aktivert.\n
57 MirrorWriteCache konnte bei offenem oder momentan synchronisiertem LV\n nicht geÃndert werden.\n
58 "-c" kann nur zusammen mit "-M n" verwendet werden.\n
59 "-c" kann nur verwendet werden, wenn MWC ausgeschaltet wird oder ist.\n
60 Wiederherstellung der Konsistenz
61 MWC
62 NOMWC
63 NONE
64 verfœgbar
65 Ungœltige Kombination von Optionen
66 IO-Fehler bei Konfigurationsdatei\n
67 IO-Fehler bei physischem Volume-GerÃt\n
68 Kein Speicher fœr malloc\n
69 Ungœltiger LVMREC bei physischem Volume %s\n
70 Kein Zugriff auf physisches Volume %s: Zuvor gesicherte \n Information wird beibehalten\n
71 Physisches Volume %s\nin Konfigurationsdatei %s nicht gefunden. Konfigurationsdatei nicht aktualisiert.\n
72 Physisches Volume "%s" konnte nicht geŒffnet werden.\n
73 Fœr Sicherungskopie der Konfiguration der Volume-Gruppe mœssen \n alle PVs vorhanden sein.\n
74 Konfiguration der Volume-Gruppe fœr %s gesichert in %s\n
75 Konfiguration der Volume-Gruppe wiederhergestellt in %s\n
76 Konfigurationsangaben fœr physisches Volume "%s" \n in "%s" nicht gefunden :\n"Character-special"-Datei fœr PV fehlt in Befehlszeile, ODER\nPV gehŒrte nicht zu Volume-Gruppe %s bei Erstellung der Konfigurationsdatei.\n
77 Fehler beim ⁄ffnen der LVM-Konfigurationsdatei : %s\n
78 Konfigurationsdatei offenbar defekt\n
79 Volume-Gruppe : %s nicht gefunden in Konfigurationsdatei %s\n
80 Informationen zur Konfiguration der Volume-Gruppe in "%s"\n
81 (Bootable)
82 (Non-bootable)
83 OldPVPath und PVPath : "character special"-Dateien\n
84 Konfigurationsdatei "%s" nicht gefunden oder defekt\n
85 VGRA offenbar defekt\n
86 Physisches Volume "%s" enthÃlt keine LVM-Informationen\n
87 Physisches Volume "%s" ist keine Boot-Platte\n
88 Physisches Volume "%s" ist nicht Teil einer Volume-Gruppe\n
89 Vorschrift fœr zusammenhÃngende Zuordnung kann nicht geÃndert werden, \n da LV "%s" momentan œber nicht zusammenhÃngende physische Bereiche verfœgt.\n
90 none_strict/contiguous  (nicht strikt/zusammenhÃngend)
91 strict/contiguous  (strikt/zusammenhÃngend)
92 PVG-strikt/zusammenhÃngend
93 Fehler eventuell aufgrund zusammenhÃngender Zuordnungsvorschrift.\n
94 Option [PhysicalVolumePath ... | PhysicalVolumeGroupName...] prœfen, \n um sicherzustellen, daﬁ die vorhandenen physischen Volumes aller \n Spiegelungen abgedeckt sind.\n
95 Volume-Gruppe "%s" konnte nicht exportiert werden.\n
96 MAPFILE "%s" konnte nicht geŒffnet werden.\n
97 Volume-Gruppe "%s" ist auf diesem System aktiv. \n "%s" kann bei aktiven Volume-Gruppen nicht auﬁer Kraft gesetzt werden.\n
98 MAPFILE "%s" konnte nicht analysiert (parsed) werden.\n
99 Logisches Volume "%s" in "%s" ist in physischem Volume nicht definiert.\n
100 Physische Volumes im System kŒnnen nicht abgesucht werden\n
101 "Complete Import" oder "Create MapFile" bei VG%02d nicht durchfœhrbar.\n
102 Physische Volumes vollstÃndig abgesucht.\n
103 "exec" kann nicht ausgefœhrt werden.\n
104 Kennung der Volume-Gruppe auf importierten Platten entspricht \nvorhandener Volume-Gruppe "%s".\n
105 Warnung: Volume-Gruppe "%s" ist in Datei "%s" definiert, fehlt aber in der "Group Special"-Datei.\nAnzahl der Volume-Gruppen kann nicht bestimmt werden. Fortsetzung.\n
106 Im System existiert bereits die maximale Anzahl von Volume-Gruppen.\n
107 Warnung: Anzahl der physischen Volumes in Befehlszeile "%d" \nungleich Anzahl der physischen Volumes "%d" laut Volume-\nGruppendaten in den importierten physischen Volumes. Fortsetzung.\n
108 Export der Volume-Gruppe "%s" beginnt.\n
109 Import der Volume-Gruppe "%s" beginnt.\n
110 Warnung: Logische Volume-Nummer "%d" in physischem Volume nicht in "%s".\n
111 Warnung: Logisches Volume "%s" existiert bereits, entspricht\naber nicht Volume-Gruppenkennung fœr "%s". Wird gelŒscht.\n
112 "%s" kann nicht gesperrt werden, wird weiterhin versucht ...
113 Wert muﬁ zwischen 0 und 7039 liegen.
114 Zu viele Argumente
115 Logisches Volume "%s" muﬁ zusammenhÃngend sein.\n
116 /dev/console konnte nicht geŒffnet werden\n
117 Physisches Volume "%s", auf dem sich logisches \nVolume "%s" befindet, ist kein "Boot Physical"-Volume.\n
118 Ein "Root Logical"-Volume muﬁ zugeordnet werden, bevor\nein Dump oder Swap Logical Volume zugeordnet werden kann.\n
119 Ein logisches Volume wurde dem\ntRoot oder Swap Logical Volume bereits zugewiesen.\n
120 Keine "LIF Boot"-Informationen in "%s".\n
121 Warnung: LABEL-Datei nicht gefunden oder defekt in "%s". Wird erstellt.\n
122 LIF-Information defekt oder fehlt in "%s".\n
123 LABEL-Datei ist voll. Keine weiteren Eingaben zulÃssig.\n
124 Unable to write LABEL from \"%s\" to \"%s\": %s.\n
125 Es befinden sich keine gœltigen "Boot Data Reserved Areas" auf den \nphysischen Volumes in Volume-Gruppe "%s".\nMit dem Befehl pvcreate -B muﬁ eine "Boot Area" auf einem physischen \n angelegt werden.\n
126 Logisches Volume "%s" wurde im physischen Volume "%s" gefunden.\n
127 Root Logical Volume muﬁ das erste logische Volume \nim physischen Volume sein.\n
128 Dump Logical Volume kann nicht gelŒscht werden\n
129 Swap Logical Volume kann nicht gelŒscht werden\n
130 Root Logical Volume kann nicht gelŒscht werden\n
131 Logisches Volume "%s" ist bereits als Root Logical Volume konfiguriert.\n
132 Logisches Volume "%s" ist nicht als\nRoot, Swap oder Dump Logical Volume konfiguriert.\n
133 Boot Data Area ist leer.\n
134 Warnung: Gœltige Boot Data Area gefunden. \nFalls physisches Volume "%s" mit /etc/mkboot ein Boot Device werden soll, \n wird diese neu erstellte LABEL-Datei œberschrieben.\n
135 Zu viele physische Volumes in PhysicalVolumePath.\nMaximal "%d"\n
136 Maximalzahl der Dump Logical Volumes ist œberschritten.\n Kein weiteres Dump Logical Volume kann hinzugefœgt werden.\n
137 Boot-Definitionen fœr Volume-Gruppe %s:\n
138 Physische Volumes gehŒren zu Root Volume-Gruppe:\n
139 %s: %s\ton: 
140 %s: %s\ton: %s\n
141 Root
142 Swap
143 Dump
144 Label-Eintrag: %d, %s Volume-Start: %d LÃnge %d\n
145 Kein logisches Volume %s konfiguriert\n
146 Logisches Volume hat keine Bereiche.\n
147 Boot-Platten: 
148 Zu wenig physische Bereiche pro physischem Volume.\n Erforderlich: %d, vorhanden: %d.\n
149 Anzahl der physischen Bereiche pro physischem Volume auf %d erhŒht.\n
150 Physical extents on remaining physical volumes are stale.\n
151 The Physical Volumes specified on the command line\n\
do not belong to the same Volume Group.\n
152 Only one VolumeGroupName can be specified in \n\
combination with the \-r\, \-s\, or \-d\ options.
153 Entry for %s Logical Volume already exists\n\
at a different starting location.  Can not add %s Logical Volume\n
154 Warning: rounding up logical volume size to \
extent boundary at size \%d\ MB.\n
155 Can be used only if \-l\ or \-L\ has been \
specified.
156 Can be used only if \-m\ has been specified.
157 Can't create a mirrored empty logical \
volume. Specify \-l\ or \-L\.)
158 The Logical Volume has a mounted file system \
on it.
159 Warning: The Logical Volume has a file system larger \
than the reduced size.\n.Reducing the \
Logical Volume will cause filesystem corruption.\n
160 The Logical Volume is used as a swap device.
161 LV Size (Mbytes)
162 Root Logical Volume can not have Bad Block Relocation.\n
163 Following Physical Volumes belong to one Volume Group\
.nUnable to match these Physical Volumes to a Volume Group.\n\
Use the vgimport command to complete the process.\n
164 The Volume Group %s was not matched with any Physical Volumes.\n
165 Logical volume %s has been successfully created with\n\
character device %s.\n
166 Run the \lvextend\ command to create space on the Logical Volume.\n.
167 Run the \lvextend\ command add mirror copies on the Logical Volume.\n.
168 Warning:  Can not determine all Physical Volumes on which \
mirrored copies of\nthe Logical Volume are located.   %s is missing Physical \
Volumes.\n
169 Warning:  Volume Group belongs to different CPU ID.\n\
Can not determine if Volume Group is in use on another system. Continuing.\n
170 Couldn't split the logical volume.\n\
Synchronize the stale extents in the logical volume by running lvsync before\n\
lvsplit.\n

$set 3
1 j
2 n
