$set 1
1 mail: %s kann fœr Schreibvorgang nicht geŒffnet werden\n
2 Syntax: mail [+] [-epqr] [-f Datei]\n
3	  mail [-dt] Personen\n
4 mail: hmbox kann nicht zugeordnet werden
5 mail: Postdatei kann nicht zugeordnet werden
6 mail: Berechtigung verweigert!\n
7 mail: %s kann nicht geŒffnet werden\n
8 Keine Post.\n
9 Modus und Gruppenkennung der Postdatei prœfen.\n
10 Ihre Post wird weitergeleitet an
11 %s
12 Ihre Mailbox enthÃlt weitere Nachrichten\n
13 mail: %s kann nicht geŒffnet werden\n
14 Syntax\n
15 q\t\tquit, Verlassen\n
16 x\t\texit, Verlassen ohne ÿnderungen an Post\n
17 p\t\tprint, Drucken\n
18 s [Datei]\tsave (Standard-Mailbox)\n
19 w [Datei]\tgleich, ohne Kopf\n
20 -\t\tvorheriges drucken\n
21 d\t\tdelete, LŒschen\n
22 +\t\tnext, nÃchstes (nicht lŒschen)\n
23 m user\t\tan Benutzer senden\n
24 ! cmd\t\tBefehl ausfœhren\n
25 Ungœltiger Befehl\n
26 mail: Anfœgung an %s nicht durchfœhrbar\n
27 mail: Post kann nicht gespeichert werden\n
28 Ungœltiger Befehl\n
29 %s hat keinen Wert oder wird nicht exportiert.\n
30 !\n
31 mail: %s kann nicht neu geschrieben werden\n
33 mail: %s kann nicht neu gelesen werden\n
34 copyback:zu viele Buchstaben\n
35 mail: %s kann nicht aktualisiert werden\n
36 mail: %s kann nicht aktualisiert werden\n
37 mail: %s kann nicht aktualisiert werden\n
38 mail: Post kann nicht zurœckkopiert werden\n
39 Neue Post ist eingetroffen\n
40 \007Warnung: zu viele Buchstaben, œberschœssige Buchstaben verkettet\n\n
42 mail: %s kann fœr Lesevorgang nicht erneut geŒffnet werden\n
43 mail: malloc nicht durchfœhrbar\n
44 mail: %s kann nicht erstellt werden\n
45 Post gespeichert in %s\n
46 Post gespeichert in %s\n
47 mail: Speichern in "dead.letter" nicht durchfœhrbar\n
48 Kopfzeile zu lang\n
49 Null-Name\n
50 Null-Name\n
51 mail: Pipe an Post-Befehl nicht realisierbar\n
52 Weiterleitung ohne Rœcklauf (bounce)\n
53 mail: Senden an %s nicht durchfœhrbar\n
54 mail: Anfœgen an %s nicht durchfœhrbar\n
55 mail: Anfœgen an %s nicht durchfœhrbar\n
56 mail: Anfœgen an %s nicht durchfœhrbar\n
57 mail: Fehlersignal %d\n
58 mail: Sperren von %s nach %d Versuchen nicht durchfœhrbar\n
59 mail: %s kann nach %d Versuchen nicht erstellt werden\n
