$set 1
1 Panik:
3 Es lÌuft zu viel "sourcing" ab.\n
4 "Source" Stapel-"over-pop".\n
5 Unzutreffendes "if"\n
$set 2
1 Keine weitere Post.\n
2 Auf letztem Bildschirm mit Anzeige von Meldungen\n
3 Auf erstem Bildschirm mit Anzeige von Meldungen\n
4 Nichterkannter Befehl "%s" zum Bildschirmrollen\n
5 Befehle sind:\n
6 Meldung %2d:\n
7 Meldung %2d:\n
8 Keine Wert fÏr "folder" gesetzt\n
$set 3
1 Keine Meldungen anwendbar\n
2 EOF erreicht\n
3 Keine Meldungen zu sichern.\n
4 Keine Meldungen zu kopieren.\n
5 [Piped]
6 [AngehÌngt]
7 [Neue Datei]
8 \nExit-Status = %d.\n
9 Keine Meldungen zu schreiben.\n
10 [Piped]
11 [AngehÌngt]
12 [Neue Datei]
13 \nExit-Status = %d.\n
14 Syntaxfehler: %c fehlt.\n
15 Keine Datei angegeben.\n
16 EOF erreicht\n
17 Keine weiteren Meldungen\n
18 Es werden momentan keine Felder ignoriert.\n
$set 4
1 BefehlspufferÏberlauf\n
2 Augenblicklich keine Hilfe.\n
3 Sorry, es ist nicht mÎglich, auf mehrere Meldungen gleichzeitig zu antworten\n
4 Leeres "reply-to"-Feld -- Antwort an den Author\n
5 Sichern im Edit-Modus nicht mÎglich\n
6 Variablename nicht-NULL erforderlich\n
7 Gruppenname muŞ angegeben werden.\n
8 "%s": Keine Gruppe\n
9 Keine zuvor verarbeitete Datei\n
10 Nicht korrekt verschachteltes "if"\n
11 Nicht erkanntes if-SchlÏsselwort: "%s"\n
12 "Else" ohne entsprechendes "if"\n
13 UngÏltige Bedingung gefunden\n
14 "Endif" ohne entsprechendes "if"\n
$set 5
1 Pipe-Befehlsfehler\n
2 "cmd" nicht gesetzt, ignoriert.\n
3 Keine Meldungen weiterzuleiten (Pipe).\n
4 Pipe nach: "%s"\n
5 \nExit-Status = %d.\n
6 Pipe nach "%s" fehlgeschlagen\n
$set 6
1 Verwende "." um Brief zu beenden\n
2 tilde escape unbekannt.\n
3 (Fortsetzung)\n
4 ~h: no can do!?\n
5 (Fortsetzung)\n
6 Welche Datei soll eingeschoben werden?\n
7 %s: Verzeichnis\n
8 In welche Datei soll geschrieben werden?\n
9 Keine Meldungen abzusenden!?!\n
10 (Fortsetzung)\n
11 Augenblicklich keine Hilfe.\n
12 -------\nMeldung enthÌlt:\n
13 (Fortsetzung)\n
14 (Fortsetzung)\n
15 (Fortsetzung)\n
16 Datei existiert\n
17  [angehÌngt] %d/%ld\n
18 %s: Datei existiert\n
19 Fataler Fehler in "%s"\n
20 TemporÌre Editordatei gesichert als %s\n
21 "%s" fehlgeschlagen!?\n
22 Keine Bytes von "%s" !?\n
23 Keine entsprechenden Meldungen\n
24 EinfÏgen:
25 (Fortsetzung)\n
26 \n(Unterbrechung -- ein weiterer, um Brief zu vernichten)\n
$set 7
1 %s: Datei existiert\n
$set 8
1 Ihr Post wird weitergeleitet anzu %s\n
2 und Ihre Mailbox enthÌlt weiteren Inhalt\n
3 TemporÌrdateisuche
4 Kein ausreichender Speicher fÏr %d Meldungen\n
5 Lesefehler Meldungs-"ghost"-Datei\n
6 entfernt\n
7 vollstÌndig\n
8 "Echo" fehlgeschlagen\n
9 "%s": Keine Ûbereinstimmung\n
10 PufferÏberlauf beim Erweitern von "%s"\n
11 "%s": Nicht eindeutig\n
12 mailx: 1 NULL-Zeichen in Postdatei gelÎscht\n
13 mailx: %d NULL-Zeichen in Postdatei gelÎscht\n
$set 9
1 Es kann kein leerer Einschub fÏr dynamischen Host-Eintrag gefunden werden\n
2 %s kann nicht geÎffnet werden\n
3 Kein sysname in %s\n
$set 10
1 Keine Post.\n
2 Keine Post fÏr %s\n
3 %s: Leere Datei\n
4 Keine Post.\n
5 Keine Post fÏr %s\n
6 Ihre Post wird weitergeleitet nach %s
7 "quit" verwenden zum Beenden.\n
8 Kein "!" wÌhrend "sourcing" mÎglich\n
9 Unbekannter Befehl in Quelle: "%s"\n
10 Unbekannter Befehl: "%s"\n
11 "%s" kann wÌhrend des Sendens nicht ausgefÏhrt werden\n
12 "%s" kann wÌhrend des "sourcing" nicht ausgefÏhrt werden\n
13 "%s" kann nicht ausgefÏhrt werden -- Meldungsdatei kann nur gelesen werden\n
14 Rekursiver Aufruf von "%s" ist nicht mÎglich\n
15 Falsche Anwendung der Meldungsliste\n
16 Keine verarbeitbaren Meldungen\n
17 Falsche Anwendung der Meldungsliste\n
18 %s verlangt mindestens %d Argumente\n
19 %s verwendet nicht mehr als %d Argumente\n
20 Unbekannter Argumenttyp
21 Unterbrechung\n
22 mailx %s  Geben Sie ? ein, um Hilfe zu erhalten.\n
23 1 Meldung
24 %d Meldungen
25  %d neu
26  %d ungelesen
27  %d gelÎscht
28  %d gesichert
29  [nur Lesen]
$set 11
1 Keine Zahlen gemischt mit *\n
2 nicht-numerisches zweites Argument\n
3 Unbekannter "colon"-Bezeichner "%s"\n
4 "*" kann mit nichts anderem gemischt werden\n
5 Keine verarbeitbaren Meldungen.\n
6 Keine verarbeitbaren Meldungen von {%s
7 }\n
8 Keine Meldungen genÏgen
9 %d: UngÏltige Meldungsnummer\n
10 %d: Keine entsprechende Meldung\n
11 Warnung:  Nur die ersten %d Argumente des %s-Befehls verarbeitet.\n
12 %c fehlt\n
13 Zu viele regrets
14 Falsche Meldungsnummer soll markiert werden
15 FÏr eine falsche Meldungsnummer soll Markierung rÏckgÌngig gemacht werden
16 Keine verarbeitbaren Meldungen\n
17 Zugriffsversuch nach letzter Meldung\n
18 Zugriffsversuch vor erster Meldung\n
19 Keine verarbeitbaren Meldungen\n
20 %d: Keine entsprechende Meldung\n
21 Unbekanntes Metazeichen (%c)\n
$set 12
1 -h erfordert Zahl ungleich Null\n
2 Syntax: mailx [-FU] [-s Betreff] [-r Adresse] [-h Zahl] Adresse ...\n
3         mailx -e\n
4         mailx [-UHiNn] [-u Benutzer]\n
5         mailx -f [-UHiNn] [Dateiname]\n
6 Bei -I wird -f Flag benÎtigt\n
7 Nicht vorgesehen: -f und EmpfÌnger.\n
8 Angegebene Flags nur fÏr Verschicken von Post vorgesehen.\n
9 Keine Post fÏr %s\n
10 \nUnterbrechung\n
$set 13
1 Irgendetwas nicht korrekt -- keine @ oder % in arpafix\n
2 Es stehen keine weiteren PlÌtze fÏr Maschinenidentifikationen zur VerfÏgung\n
3 Keine weiteren Maschinenidentifikationen\n
4 Es wurden nichtdefinierte Maschinenidentifikationen verwendet\n
5 Es wurden nichtdefinierte Maschinenidentifikationen verwendet\n
6 Kein Host mit dem Namen "%s"\n
7 Syntax des Netznamens\n
8 Falscher Netzname vervollstÌndigt\n
9 Maschinencode %c (0%o)\n
10 Sorry.\n
11 Ungeeignetes Argument fÏr optiboth\n
12 FEHLER:  Unbekannte interne Maschinenidentifikation\n
$set 14
1 Sie haben neue Post.\n
2 Es ist neue Post angekommen.\n
3 Hielt 1 Meldung in %s\n
4 Hielt %2d Meldungen in %s\n
5 1 Meldung gesichert in %s\n
6 %d Meldungen gesichert in %s\n
7 Sie haben neue Post.\n
8 1 Meldung gehalten in %s\n
9 %d Meldungen gehalten in %s\n
$set 15
1 Anpassung des Statusgeldes fehlgeschlagen\n
2 Keine EmpfÌnger angegeben\n
3 Keine Meldung !?!\n
4 EOT\n
5 Keine EmpfÌnger angegeben\n
6 Keine EmpfÌnger angegeben\n
7 Keine Meldung, Kein subject; hoffentlich ist das in Ordnung\n
8 Hauptteil einer NULL-Meldung; hoffentlich ist das in Ordnung\n
9 . . . Meldung verloren, sorry.\n
$set 16
1 Zeichenkette zu groŞ
2 Keine Platz fÏr Space %d\n
3 Interner Fehler
$set 17
1 "%s" ist kein Benutzer diese Systems\n
2 ubluit
3 Wer sind Sie!?\n
$set 18
1 Zu lang zum editieren\n
3 Zu lang zum editieren\n
$set 19
1 "%s": Nichtdefinierte Variable\n
2 Kein ausreichender Speicher
3 "%s": Keine Gruppe\n
$set 20
1 rmmail: Bindungen fÏr %s kÎnnen nicht rÏckgÌngig gemacht werden\n
2 rmmail: UngÏltige Argumente\n
3 rmmail: Status von %s kann nicht ermittelt werden\n
4 rmmail: %s nicht leer\n
5 rmmail: %s kann nicht entfernt werden - Berechtigung verweigert\n
6 rmmail: Falscher Status\n
$set 21
1 %a %h %d %H:%M
