$set 1
1 Syntax: man [ Kapitel ] Name(n)\n
2 oder: man -k Schlœsselwort(e)\n
3 oder: man -f Datei(en)\n
4 Aber was mŒchten Sie von Kapitel %s?\n
6 Kein Handbucheintrag fœr %s.\n
7 Kein Eintrag fœr %1$s in Kapitel %2$s des Handbuchs.\n
9 Neuformatierung des Eintrags.  Warten Sie...
10  abgebrochen (sorry)\n
11  fertig\n
12 man: -k was?\n
13 %s: nichts Zutreffendes\n
14 man: -f was?\n
15 %s: nicht gefunden\n
$set 2
1 whereis [ -sbmu ] [ -SBM Verzeichnis(se) -f ] Name(n)\n
