$set 1
1 Zu wenig Speicherplatz
2 GerÌt muŞ 'online' oder 'offline' sein
3 Syntax: %s -c [-f] PrimÌrgerÌt pZustand SekundÌrgerÌt sZustand\n
4        %s -u SpiegelgerÌt ...\n
5        %s -o -p|-s SpiegelgerÌt ...\n
6        %s -r [-t] SpiegelgerÌt\n
7        %s -l [GerÌt ...]\n
8 Kann Spiegeltreiber nicht ansprechen
9 Plattenspiegelung nicht im Kernel konfiguriert
10 %s falsch
11 %s kann nicht gespiegelt werden
12 %s kann nicht gespiegelt werden
13 %s und %s kÎnnen nicht gespiegelt werden
14 %s bereits in Spiegelung
15 %s bereits in Spiegelung
16 Ein Teil muŞ ONLINE bleiben
17 %s offen, muŞ daher ONLINE sein
18 %s offen, %s muŞ daher OFFLINE sein
19 %s darf nicht offen sein
20 Spiegelung offen; %s muŞ ONLINE sein
21 %s wird neu abgebildet
22 Offline-Zugriffsdatei %s ist offen
23 Tabelle fÏr Neuabbildung nicht vorhanden
24 root oder swap mit uxgen konfigurieren
25 %s ist keine Spiegelung
26 Markierung oder Zustand ist ungÏltig
27 UngÏltige Zustandskombination
28 Spiegelung bereits teilweise OFFLINE
29 mirrorlog daemon kann nicht gefunden werden
30 Neuabbildung (reimage) fehlgeschlagen
31 Ein Teil muŞ ONLINE gesetzt werden
32 Zu viele GerÌtenamen
33 Zu viele GerÌtenamen
34 %s ist keine Spiegelung
35 Kein Inhalt fÏr Neuabbildung
36 Tabelle fÏr Neuabbildung nicht vorhanden
37 %s kann nicht gespiegelt werden\n
38 Diese Option ist "root" vorbehalten
39 plock bei diesem ProzeŞ nicht durchfÏhrbar
