$set 1
1 Syntax:
2  [-dfln] [+Zeilennum | +/Muster] Name1 Name2 ...\n
3 \n*** %s: Verzeichnis ***\n\n
4 \n******** %s: Keine Textdatei ********\n\n
6 [Verwenden Sie q oder Q zum Beenden]
7 --More--
8 (NÌchste Datei: %s)
9 (%d%%)
10 [Weiter mit Leerzeichen, Abbrechen mit q]
11 ...%d Zeilen werden Ïbersprungen\n
12 ...%d Zeile wird Ïbersprungen\n
13 \n***ZurÏck***\n\n
14 Hilfedatei kann nicht geÎffnet werden
15 "%s" Zeile %d
16 [Keine Datei] Zeile %d
17 RegulÌrer Ausdruck fehlerhaft korrigiert
18 ...Ïberspringen\n
19 \nMuster nicht gefunden\n
20 Muster nicht gefunden
21 AusfÏhrung fehlgeschlagen\n
22 \n...Ûberspringen
23 ...Ûberspringen
24 bis Datei
25 zurÏck bis Datei
26 stderr kann nicht gelesen werden.\n
27 Zeile zu lang
28 Kein vorheriger Befehl zum Ersetzen
99 \n*** %s: FIFO-Datei ***\n\n
