$set 1
1 Syntax: mv [-f] [-i] f1 f2\n	     mv [-f] [-i] f1 ... fn d1\n       mv [-f] [-i] d1 d2\n
2 %s: Bindung kann nicht rÏckgÌngig gemacht werden
3 Kein Zugriff mÎglich
4 %s und %s stimmen Ïberein
5 %s entfernen?
6 Schutzeinrichtung %o%c fÏr %s Ïbergehen?
8 %s: Unbekannter Dateityp %o
9 %s: mv fÏr Socketschnittstellen Ïber Dateisysteme hinweg ist nicht mÎglich
10 %s: mv fÏr NetzwerkgerÌtedateien Ïber Dateisysteme hinweg ist nicht mÎglich
11 mv fÏr mehrfach benutzte Bibliotheken im Zustand "text busy" nicht mÎglich
12 mv fÏr Nichtverzeichnis %s in vorhandenes Verzeichnis %s nicht mÎglich
13 mv fÏr Verzeichnis %s in vorhandenes Nichtverzeichnis %s nicht mÎglich
14 Zeit der DateiÌnderung kann nicht gesetzt werden
15 Besitzer (owner) oder Gruppe (group) einer Datei kann nicht gesetzt werden
16 Dateimodi kÎnnen nicht gesetzt werden
17 Schreibvorgang nicht durchfÏhrbar
18 Erstellung nicht durchfÏhrbar
19 Úffnen nicht durchfÏhrbar
20 mv: %s/%s: Name zu lang.
21 SchlieŞen nicht durchfÏhrbar
