$set 1
1 Konvertiertes Token %.25s... zu lang
2 Kein ausreichender Platz in lookup
3 Datei %s kann nicht geŒffnet werden
4 pushback-€berlauf
5 Zeichenkette %.20s... zu lang
6 Fehlendes " in %.20s
7 Token %.20s... zu lang
8 Unerwartetes Eingabeende an %.20s
9 Nicht abgeschlossene Definition an %.20s
10 Kein ausreichender Platz in strsave auf %s
11 Include nicht implementiert
12 Bizarre Trennsymbole an %.20s
13 Beendet aufgrund eines "eqn"-Fehlers\n
14 Eingabezeile zu lang: %.20s\n
15 Keine "eqn"-Zeichenketten zurœckgelassen
16 Datei %s kann nicht geŒffnet werden
17 eqn Abbruchfehler:
18 \nDatei %1$s, zwischen Zeile %2$d und %d\n
19 eqn: 
20 Abbruchfehler: 
21 \nDatei %1$s, zwischen Zeile %2$d und %d\n
23 funny Typ %d in funny
24 \\e
