$set 1
1 "%s" Keine "rechts-nach-links"-Sprache\n
2 Nicht-Latein-Modusdatei mit Linksausrichtung\n
3 Latein-Modusdatei mit Rechtsausrichtung\n
4 Kein ausreichender Speicher\n
5 EingabepufferÏberlauf\n
6 AusgabepufferÏberlauf\n
7 Druckbreite von "%s" Ïberschreitet EingabepufferlÌnge\n
8 "%s" fehlerhafte Druckbreite\n
9 Ûberlaufrand von "%s" Ïberschreitet EingabepufferlÌnge\n
10 "%s" fehlerhafter Ûberlaufrand\n
11 Ûberlaufrand auf "%s" geÌndert (Ûberschreiten der Druckbreite nicht mÎglich)\n
12 Tabulatorstop von "%s" Ïberschreitet EingabepufferlÌnge\n
13 "%s" fehlerhafter Tabulatorstop\n
14 Eingabedatei "%s" kann nicht geÎffnet werden\n
15 "%s" fehlerhafte Ausrichtung (l oder r)\n
16 "%s" fehlerhafter Modus (l oder n)\n
17 "%s" fehlerhafte Ordnung (k oder s)\n
18 Syntax: nljust [-aclnt] [-e Seq] [-j Just] [-m Modus] [-o Ordnung] [-r Rand] [-w Breite] [-x ck] [Dateien ...]\n
