$set 1
1 Fehler beim Lesen des Datenbereichs\n
2 Verdichtete TemporÌrdatei kann nicht gefunden werden\n
3 Aktiv.\n
4 VerfÏgbar.\n
5 Unbekannte Option:
6 Floating Ausnahme.\n
7  
8  
9 TemporÌre Datei kann nicht erstellt werden.\n
10 Schriftsetzer aktiv.\n
11 Keine existierende Makro-Datei (
12 )
13 Datei kann nicht geÎffnet werden: 
14 Datei kann nicht geÎffnet werden: 
15 Zu viele Seitennummern\n
16 Schreibfehler auf TemporÌrdatei\n
17 Datendatei kann nicht erstellt werden\n
18 TemporÌrdatei kann nicht erstellt werden\n
19 Verdichtung abgeschlossen\n
20 Zu viele Makropakete.\n
21 suftab kann nicht geÎffnet werden.\n
22 Befehlsumgebung kann nicht aufgebaut werden\n
23 AusfÏhrung nicht mÎglich: 
24 Nichtexistierender Bildschirmtyp\n
25 Bildschirmtabelle zu groŞ
26 Warten auf den Schriftsetzer.\n
27 Troff abgeschlossen.\n
28 Pipe nicht erstellt.\n
29 AusfÏhrung nicht mÎglich: 
30 Zu viele Namen fÏr rn
31 Zu viele Zeichenketten-/Makronamen.\n
32 Kein ausreichender Speicher zur Speicherung
33 Kein ausreichender temporÌrer Dateibereich.\n
34 Lesen des Makros fehlgeschlagen\n
35 Falsche Speicherbelegung\n
36 Zu viele Makroaufrufe
37 Kein ausreichender Speicher fÏr Makroaufruf
38 Kernlimit erreicht.\n
39 Kein ausreichender Speicher fÏr Makroaufruf
40 Makroargument zu lang.\n
41 Umlenkung nicht mÎglich.\n
42 Zu viele Zahlregister.\n
43 Division durch Null.\n
44 Einrichtung des Trap nicht mÎglich.\n
45 Benutzerabbruch.
46 ev_ nicht mÎglich\n
47 "if-else"-Ûberlauf.\n
48 :
49 ZeilenÏberlauf.\n
50 Trap botch.\n
51 Wort-Ûberlauf.\n
52 Ausnahmewortliste voll.\n
53 Nullfeldbreite.\n
54 Zu viele overstriking Zeichen.\n
