$set 1
1 %s: Fehler beim Lesen der Datei %s\n
2 %s: Veraltete und neue Formulare nicht kombinierbar\n
3 %s: Ungœltiges Argument fœr Option -A\n
4 %s: Ungœltiger Wert fœr Option -j\n
5 %s: Ungœltiger Wert fœr Option -N\n
6 Syntax: %s [-v] [-A Basis] [-j €berspring] [-N ZÃhlwert] [-t Typenangabe]... [Datei...]\n
7 %s: Dateiende fœr Eingabe erreicht: %s\n
8 %s: Ungœltiges Argument fœr Option -t\n
9 %s: Ungœltiger numerischer Modifizierer\n
10 %s: Verwendeter Modifiziertyp ist ungœltig\n
11 %s: %s kann nicht geŒffnet werden\n
