$set 1
1 Syntax: passwd [ Name ]\n
2 ÿndere Kennwort fœr %s\n
3 Berechtigung verweigert.\n
4 Altes Kennwort:
5 Sorry.\n
6 Sorry: < %ld Wochen seit letzter ÿnderung\n
7 Sie dœrfen dieses Kennwort nicht Ãndern.\n
8 Zu viele Fehler - versuchen Sie es spÃter.\n
9 Neues Kennwort:
10 Kennwort ist zu kurz - muﬁ aus mindestens 6 Zeichen bestehen\n
11 Kennwort kann keine kreisfŒrmige Verschiebung der Anmeldeidentifikaton sein\n
12 Kennwort muﬁ mindestens zwei Buchstaben und mindestens\n
13 ein numerisches Zeichen oder Sonderzeichen enthalten.\n
14 Kennworte mœssen sich in mindestens 3 Positionen unterscheiden\n
15 Geben Sie neues Kennwort erneut ein:
16 Zu viele Versuche; versuchen Sie es spÃter erneut.\n
17 Sie stimmen nicht œberein; erneuter Versuch.\n
18 TemporÃrdatei aktiv; versuchen Sie es spÃter erneut.\n
19 TemporÃrdatei kann nicht erstellt werden\n
20 Berechtigung verweigert.\n
21 Bindungen von %s kŒnnen nicht rœckgÃngig gemacht werden\n
22 Binden von %s zu %s nicht mŒglich\n
23 Bindungen von %s kŒnnen nicht rœckgÃngig gemacht werden\n
24 Binden von %s zu %s nicht mŒglich\n
25 %s kann nicht wiederhergestellt werden\n
26 Bindungen von %s kŒnnen nicht rœckgÃngig gemacht werden\n
27 putpwent() fehlgeschlagen\n
28 chown %s nicht durchfœhrbar\n
29 chmod %s nicht durchfœhrbar\n
30 Ungœltiger Anmeldename.\n
31 Kennwort-Eintrag ist zu lang\n
