$set 1
1 Fehler 0
2 Nicht EigentÏmer
3 Keine solche Datei oder Verzeichnis
4 Kein solcher ProzeŞ
5 Unterbrochener Systemprozedurauf
6 E/A-Fehler
7 Kein/e solche/s GerÌt oder Adresse
8 Argumentliste ist zu lang
9 Exec Formatfehler
10 Falsche Dateinummer
11 Keine Kindprozesse
12 Keine weiteren Prozesse
13 Kein ausreichender Platz
14 Berechtigung verweigert
15 Falsche Adresse
16 BlockgerÌt erforderlich
17 GerÌt aktiv
18 Datei existiert
19 Cross-GerÌt Bindung
20 Kein solches GerÌt
21 Kein Verzeichnis
22 Ist Verzeichnis
23 UngÏltiges Argument
24 DateitabellenÏberlauf
25 Zu viele offene Dateien
26 Keine Schreibmaschine
27 Textdatei aktiv
28 Datei zu groŞ
29 Keine Platz Ïbrig auf GerÌt
30 Unerlaubte Suchvorgang
31 Nur-Lese-Dateisystem
32 Zu viele Bindungen
33 Unterbrochene Pipe
34 Argument auŞerhalb des Bereichs
35 Ergebnis zu groŞ
36 Keine Meldung des gewÏnschten Typs
37 Bezeichner entfernt
38 Unbekannter Fehler
39 Unbekannter Fehler
40 Unbekannter Fehler
41 Unbekannter Fehler
42 Unbekannter Fehler
43 Unbekannter Fehler
44 Unbekannter Fehler
45 Unbekannter Fehler
46 Sperrdatei-Deadlock ermittelt
47 Keine Sperren verfÏgbar
48 Unbekannter Fehler
49 Unbekannter Fehler
50 Unbekannter Fehler
51 Kein Datenstrom
52 Keine Daten
53 Datenstrom-ioctl-Timeout
54 Keine Datenstromressourcen
55 Nicht am Netzwerk
56 Paket nicht installiert
57 Unbekannter Fehler
58 Verbindung unterbrochen
59 Advertise-Fehler
60 Srmount-Fehler
61 Fehler beim Senden
62 Protokollfehler
63 Unbekannter Fehler
64 Unbekannter Fehler
65 Multihop-Versuch
66 Unbekannter Fehler
67 Querverbindungspunkt
68 Falsche Meldung
70 Plattenzuteilung Ïberschritten
71 Veraltete NFS-Dateibezeichnung
72 Zu viele Remote-Ebenen im Pfad
73 Unbekannter Fehler
74 Unbekannter Fehler
75 Unbekannter Fehler
76 Unbekannter Fehler
77 Unbekannter Fehler
78 Unbekannter Fehler
79 Unbekannter Fehler
80 Unbekannter Fehler
81 Unbekannter Fehler
82 Unbekannter Fehler
83 Unbekannter Fehler
84 Unbekannter Fehler
85 Unbekannter Fehler
86 Unbekannter Fehler
87 Unbekannter Fehler
88 Unbekannter Fehler
89 Unbekannter Fehler
90 Unbekannter Fehler
91 Unbekannter Fehler
92 Unbekannter Fehler
93 Unbekannter Fehler
94 Unbekannter Fehler
95 Unbekannter Fehler
96 Unbekannter Fehler
97 Unbekannter Fehler
98 Unbekannter Fehler
99 Unbekannter Fehler
100 Unerwarteter Fehler
101 Unbekannter Fehler
102 Unbekannter Fehler
103 Unbekannter Fehler
104 Unbekannter Fehler
105 Unbekannter Fehler
106 Unbekannter Fehler
107 Unbekannter Fehler
108 Unbekannter Fehler
109 Unbekannter Fehler
110 Unbekannter Fehler
111 Unbekannter Fehler
112 Unbekannter Fehler
113 Unbekannter Fehler
114 Unbekannter Fehler
115 Unbekannter Fehler
116 Unbekannter Fehler
117 Unbekannter Fehler
118 Unbekannter Fehler
119 Unbekannter Fehler
120 Unbekannter Fehler
121 Unbekannter Fehler
122 Unbekannter Fehler
123 Unbekannter Fehler
127 Unbekannter Fehler
128 Unbekannter Fehler
129 Unbekannter Fehler
130 Unbekannter Fehler
131 Unbekannter Fehler
132 Unbekannter Fehler
133 Unbekannter Fehler
134 Externer Pfadname
135 Vorgang am Server abgeschlossen
136 Unbekannter Fehler
137 Unbekannter Fehler
138 Unbekannter Fehler
139 Unbekannter Fehler
140 Unbekannter Fehler
141 Unbekannter Fehler
142 Unbekannter Fehler
143 Unbekannter Fehler
144 Unbekannter Fehler
145 Unbekannter Fehler
146 Unbekannter Fehler
147 Unbekannter Fehler
148 Unbekannter Fehler
149 Unbekannter Fehler
150 Unbekannter Fehler
151 Unbekannter Fehler
152 Unbekannter Fehler
153 Unbekannter Fehler
154 Unbekannter Fehler
155 Unbekannter Fehler
156 Unbekannter Fehler
157 Unbekannter Fehler
158 Unbekannter Fehler
159 Unbekannter Fehler
160 Unbekannter Fehler
161 Unbekannter Fehler
162 Unbekannter Fehler
163 Unbekannter Fehler
164 Unbekannter Fehler
165 Unbekannter Fehler
166 Unbekannter Fehler
167 Unbekannter Fehler
168 Unbekannter Fehler
169 Unbekannter Fehler
170 Unbekannter Fehler
171 Unbekannter Fehler
172 Unbekannter Fehler
173 Unbekannter Fehler
174 Unbekannter Fehler
175 Unbekannter Fehler
176 Unbekannter Fehler
177 Unbekannter Fehler
178 Unbekannter Fehler
179 Unbekannter Fehler
180 Unbekannter Fehler
181 Unbekannter Fehler
182 Unbekannter Fehler
183 Unbekannter Fehler
184 Unbekannter Fehler
185 Unbekannter Fehler
186 Unbekannter Fehler
187 Unbekannter Fehler
188 Unbekannter Fehler
189 Unbekannter Fehler
190 Unbekannter Fehler
191 Unbekannter Fehler
192 Unbekannter Fehler
193 Unbekannter Fehler
194 Unbekannter Fehler
195 Unbekannter Fehler
196 Unbekannter Fehler
197 Unbekannter Fehler
198 Unbekannter Fehler
199 Unbekannter Fehler
200 Unbekannter Fehler
201 Unbekannter Fehler
202 Unbekannter Fehler
203 Unbekannter Fehler
204 Unbekannter Fehler
205 Unbekannter Fehler
206 Unbekannter Fehler
207 Unbekannter Fehler
208 Unbekannter Fehler
209 Unbekannter Fehler
210 Unbekannter Fehler
211 Unbekannter Fehler
212 Unbekannter Fehler
213 Unbekannter Fehler
214 Unbekannter Fehler
215 Unbekannter Fehler
216 Externe Routine nicht gefunden
217 Socketschnittstellenoperation auf Nicht-Socketschnittstelle
218 Zieladresse erforderlich
219 Meldung zu lang
220 Falscher Protokolltyp fÏr Socketschnittstelle
221 Protokoll nicht verfÏgbar
222 Protokoll nicht unterstÏtzt
223 Socketschnittstellentyp nicht unterstÏtzt
224 Operation nicht unterstÏtzt
225 Protokollfamilie nicht unterstÏtzt
226 AdreŞfamilie nicht unterstÏtzt durch Protokollfamilie
227 Adresse bereit im Zugriff
228 Angeforderte Adresse kann nicht zugewiesen werden
229 Netzwerk ist down
230 Netzwerk ist nicht erreichbar
231 Netzwerkverbindung aufgrund eines Reset getrennt
232 Software bewirkte Verbindungsabbruch
233 Verbindung zurÏckgesetzt durch gleichberechtigten Knoten
234 Kein Pufferplatz verfÏgbar
235 Socketschnittstelle bereit verbunden
236 Socketschnittstelle ist nicht verbunden
237 Keine Ûbertragungen nach Socketschnittstellen-Shutdown mÎglich
238 Zu viele Bezugnahmen: Verzweigung nicht mÎglich
239 Verbindung stellte ZeitÏberlauf fest
240 Verbindung verweigert
241 Gleichberechtigter Remote-Knoten gab Verbindung frei
242 Host ist down
243 Kein Netzwerkleitweg nach host
244 Unbekannter Fehler
245 Operation wird bereits verarbeitet
246 Operation wird nun verarbeitet
247 Operation wÏrde blockieren
248 Verzeichnis nicht leer
249 Dateiname zu lang
250 Zu viele Ebenen symbolischer Verbindungen
251 Keine Meldung des gewÏnschten Typs
252 Funktion ist nicht verfÏgbar
253 Unbekannter Fehler
