$set 1
1 Syntax: pg [-Zahl] [-p Zeichenkette] [-cefns] [+Zeile] [+/Muster/] Dateien\n
4 pg: Muster zu lang\n
5 pg: Eingabeaufforderung zu lang\n
6 ...springe rÏckwÌrts\n
7 ...springe vorwÌrts\n
8 (EOF)
9 Save-Datei kann nicht geÎffnet werden
10 Datei wird gesichert: 
11 gesichert
12 Neuer ProzeŞ kann nicht erstellt werden, versuchen Sie es spÌter
13 AusfÏhrung fehlgeschlagen\n
14    h                 Hilfe\n
15    q oder Q          Ende\n
16    <Leerz> oder \\n  nÌchste Seite\n
17    l                 nÌchste Zeile\n
18    d oder ^D         zeigt halbe Seite mehr an\n
19    . oder ^L         aktuelle Seite wird erneut angezeigt\n
20    f                 springe nÌchste Seite vorwÌrts\n
21    n                 nÌchste Datei\n
22    p                 vorherige Datei\n
23    $                 letzte Seite\n
24    w oder z          setzt FenstergrÎŞe und zeigt nÌchste Seite an\n
25    s savefile        sichert aktuelle Datei in Save-Datei\n
26    /pattern/         VorwÌrtssuche nach Muster\n
27    ?pattern? oder\n
28    ^pattern^         RÏckwÌrtssuche nach Muster\n
29    !command          BefehlsausfÏhrung\n
30 Den meisten Befehlen kann eine Zahl vorangestellt werden, wie in:\n
31 +1\\n (nÌchste Seite); -1\\n (vorige Seite); 1\\n (Seite 1).\n
32 FÏr genauere Informationen beachten Sie bitte Handbuchseiten.\n
33 Keine vorige Datei
34 Keine nÌchste Datei
35 pg: %s ist ein Verzeichnis\n
36 pg: GerÌtedateien werden nur als Standardeingabe behandelt\n
37 pg: TemporÌrdatei kann nicht erstellt werden\n
38 pg: TemporÌrdatei kann nicht zum Schreiben herangezogen werden\n
39 pg: TemporÌrdatei kann nicht zum Lesen herangezogen werden\n
40 Muster nicht gefunden
41 Bereichsende zu groŞ
42 Falsche Zahl
43 `\\Ziffer' auŞerhalb des erlaubten Bereichs
44 UngÏltiges oder fehlendes Trennzeichen
45 Kein bekannte Suchzeichenkette
46 \\( \\) Ungleichgewicht
47 Zu viele \\(
48 Mehr als zwei in \\{ \\} angegeben
49 } erwartet nach \\
50 Erste Zahl Ïbersteigt zweite in \\{ \\}
51 [] Ungleichgewicht
52 Ûberlauf regulÌren Ausdrucks
53 Falscher regulÌrer Ausdruck
54 Pipe-Eingabe nur teilweise gesichert
55 pg: Kein weiterer Speicher verfÏgbar - Zeile %d\n
56 pg: stdout kann nicht wieder geÎffnet werden\n
57 pg: Terminaltyp kann nicht gefunden werden\n
58 (NÌchste Datei: 
