$set 1
1 \n%s: Gemeinsam benutzte Bibliotheken werden geprÏft\n
2 
3 NICHT OK\n\n
4 Eine oder mehrere kritische gemeinsam benutzte Bibliotheken nicht gefunden.\nWiederherstellung von gemeinsam benutzten Bibliotheken erfordert ein Update-\nMedium und ein GerÌt, welches dieses Medium lesen kann. Wenn Sie diese\ngemeinsam benutzten Bibliotheken wiederherstellen wollen, wird dieses\nProgramm Sie dabei unterstÏtzen.\n\nFortsetzung (ja/nein)? 
5 Sie wurden nach /bin/sh versetzt. Wenn Sie die Umgebung verlassen,\nwird das System mit dem Ladevorgang fortfahren.\n\nUm zu diesem Programm zurÏckzukehren, geben Sie /etc/recoversl ein.\n
6 Welche Art von Update-Medium haben Sie:\n1. Kassette (Nine-Track) oder DAT-Band\n2. CD-ROM\n\nBitte wÌhlen Sie 1 oder 2: 
7 Wenn Sie mehr als ein Update-Band haben, benutzen Sie das erste Band.\nBitte legen Sie das Band ein, und drÏcken Sie die RÏcklauftaste, wenn es bereit ist.\n
8 Wiederherstellung war nicht erfolgreich. PrÏfen Sie folgendes:\n - Richtiges Band\n - Bandstation eingeschaltet und bereit\n - Band eingelegt und on-line\n - GerÌtedatei korrekt\n
9 \nWiederherstellung erfolgreich. Das System wird nun neu starten\n
10 Wenn Sie mehr als eine Update-Platte haben, benutzen Sie die erste Platte.\nFÏhren Sie die Platte ein, und drÏcken Sie die RÏcklauftaste, wenn sie bereit ist.\n
11 Eingliedern des CD-ROM-Dateisystems fehlgeschlagen. PrÏfen Sie folgendes:\n - PlattengerÌt eingeschaltet und bereit\n - Platte eingefÏhrt\n - GerÌtedatei korrekt\n
12 %d Fehler wÌhrend der Wiederherstellung aufgetreten. PrÏfen Sie folgendes:\n - Richtige CD-ROM\n
13 \nWiederherstellung erfolgreich. Es wird erwartet, daŞ Sie das System\nnun neu laden.\n
14 \nEine GerÌtedatei ist fÏr %s erforderlich.\nWenn keine existieren sollte, so wird sie fÏr Sie generiert.\n\nExistiert ein solche GerÌtedatei auf diesem System (ja/nein/beenden)? 
15 Geben Sie den vollen Pfadnamen der GerÌtedatei an: 
16 Bitte geben Sie grÎŞte und kleinste Zahlen\nfÏr die Block-GerÌtedatei an: 
17 GerÌtedatei: %s
18 : keine Block-GerÌtedatei\n
19 : keine Zeichen-GerÌtedatei\n
20 \nIst das richtig (ja/nein/beenden)? 
21 Neuladen des Systems...\n
22 \t"fixed permissions" eingeschaltet %s\n
23 j
24 n
25 b
26 Sie mÏssen Superuser sein, um dieses Programm zu benutzen.\n
27 Band
28 CD-ROM
29 Bitte geben Sie grÎŞte und kleinste Zahlen\nfÏr die Zeichen-GerÌtedatei an: 
30 tar kann weder in /bin noch in /usr/bin gefunden werden!\n
