$set 1
1 Unbekannter Fehler
2 UngÏltiger regulÌrer Ausdruck
3 
4 
5 
6 
7 
8 
9 
10 
11 UngÏltige Zahl in Konstrukt \\{ \\}
12 
13 
14 
15 
16 Zahl in Konstrukt \\{ \\} zu groŞ
17 
18 
19 
20 regexec() erbringt keine Ûbereinstimmung
21 Bezug auf ungÏltiges Vergleichselement
22 \\ am Ende des Musters
23 UngÏltiger Endpunkt in Bereichsausdruck
24 Bezug auf ungÏltige Zeichenklasse
25 Zahl in \\ziffer ungÏltig oder falsch
26 Vor ?, *, oder + kein gÏltiger regulÌrer Ausdruck
27 Kein Ausdruck in ( ) oder auf einer Seite von |
28 
29 
30 
31 
32 
33 
34 
35 
36 \\n vor Musterende gefunden, aber REG_NEWLINE-Marke nicht gesetzt
37 
38 
39 
40 
41 Keine Suchzeichenfolge registriert
42 \\( \\) oder ( ) nicht paarweise
43 Mehr als neun Paare \\( \\) oder Schachtelung zu tief
44 Mehr als 2 Zahlen in Konstrukt \\{ \\} 
45 \\{ \\} nicht paarweise
46 Erste Zahl grÎŞer als zweite in Konstrukt \\{ \\} 
47 
48 
49 [ ] nicht paarweise
50 Kein freier Speicherplatz
51 Kein freier Speicherplatz bei Ausdrucksabgleich
