$set 1
1 Syntax: rm [-Rfir] Datei ...\n
2 %s: Kann nicht entfernt werden .\n
3 rm: %s existiert nicht\n
4 Verzeichnis %s: ? 
5 rm : Lesen nicht mÎglich: 
6 rm: %s Verzeichnis\n
7 %s: %o Modus ? 
8 rm: %s nicht entfernt.  
10 rm: %s: Name zu lang\n
11 rm: %s/%s: Name zu lang\n
12 rm: Verzeichnis %s nicht entfernt.  
13 Montierbares Verzeichnis kann nicht entfernt werden.\n
14 Verzeichnis nicht leer\n
15 Aktuelles Verzeichnis kann nicht entfernt werden.\n
16 Verzeichnisname zu lang\n
17 Syntax: rmdir [-fip] Verzeichnisname ...\n
18 rmdir: %s:
19 rmdir: %s: %s nicht entfernt; 
20 rmdir: %s: Gesamter Pfad entfernt.\n
21 rm: Status kann nicht ermittelt werden: 
22 rmdir: %s: %s nicht entfernt\n
