$set 1
1 Verzeichnis `%1$s' angegeben als `%2$c' Schlœsselbuchstabe
2 d hat kein Argument
3 Wert nach %c Markierung
5 Falsches Listformat
6 Element in Liste auﬁerhalb des erlaubten Bereichs
7 Unbekannte Markierung
8 Markierung doppelt
9 f hat kein Argument
10 Wert nach %c Markierung
11 Kein Anwendung mit Anwendungsmarkierung.
12 Es existiert keine .FRED-Datei fœr diese Anwendung.
13 Angabe fœr unteren Wert nicht numerisch
14 Unterer Wert auﬁerhalb des erlaubten Bereichs
15 Angabe fœr oberen Wert nicht numerisch
16 Oberer Wert auﬁerhalb des erlaubten Bereichs
17 Keine vorgegebene sid
18 Markierung %c ohne Wert
19 Falsches Listformat
20 Element in Liste auﬁerhalb des erlaubten Bereichs
21 Unbekannte Markierung
22 Markierung doppelt
23 r auﬁerhalb des erlaubten Bereichs
24 Falsches a Argument
25 Zu viele 'a' Schlœsselbuchstaben
26 Falsches e Argument
27 Zu viele 'e' Schlœsselbuchstaben
28 Unbekannter Schlœsselbuchstabe
29 Schlœsselbuchstabe doppelt
30 Fehlendes Dateiargument
31 Falsche Verwendung des 'y'- oder 'm'-Schlœsselbuchstabens
32 Mehr als eine Datei
33 USER ID ist nicht in Kennwortdatei
34 Verzeichnis mit `i'-Schlœsselbuchstabe benannt
35 Zwei €berprœfungsroutinen sind nicht mŒglich.
36 MRs nicht erlaubt
37 MRs erforderlich
38 r nur zusammen mit i erlaubt
39 t hat kein Argument
40 d nicht zusammen mit n erlaubt
41 Datei %s existiert
42 Datei %s existiert nicht
43 Es kann kein neuer Prozeﬁ erstellt werden, versuchen Sie es erneut
44 '%s' kann nicht ausgefœhrt werden
45 BeschÃdigte Datei
46 Sperrdatei kann nicht erstellt werden
47 Dateiname zu lang
48 Falsche CMR Nummer(n).
49 Ungœltige MRs
50 -fz kann nicht zusammen mit -fv verwendet werden.
51 Keine id-Schlœsselworte
52 €ngœltige id-Schlœsselwort
53 Keine id-Schlœsselworte
54 %1$s falsche Daten in Zeile %2$d
55 Datum und Uhrzeit erstellt
56 durch
212 Keine SCCS-Datei
$set 2
1 Unbekannter Schlœsselbuchstabe
2 Wert nach %c Argument
3 Schlœsselbuchstabe doppelt
4 Fehlendes Dateiargument
5 -p und -c nicht beides mŒglich
6 p-Datei existiert
7 sid existiert nicht
8 Nichts zu tun
9 TemporÃre s.Datei kann nicht erstellt werden:
10 TemporÃrdatei kann nicht erstellt werden
11 TemporÃre s.Datei: %s existiert nicht??
$set 3
1 Unbekannter Schlœsselbuchstabe
2 Wert nach %c Argument
3 Schlœsselbuchstabe doppelt
4 Fehlendes Dateiargument
5 Sperrdatei kann nicht erstellt werden
6 Ungœltige sid in p-Datei
7 Keine id-Schlœsselworte
8 Ungœltige id-Schlœsselworte
9 Keine id-Schlœsselworte
12 '%s' kann nicht ausgefœhrt werden
13 '%1$s' fehlgeschlagen, erneuter Versuch, Segmentierung = %2$d
14 diff fehlgeschlagen
15 %u eingefœgt
16 %u gelŒscht
17 %u unverÃndert
18 MRs nicht erlaubt
19 Ungœltige MRs
20 MRs notwendig
21 CMR-Eingabe ignoriert
22 Delta abgelehnt aufgrund von CMR-Unterschieden
23 AUTO NULL DELTA
24 Zu groﬁer Wert fœr `r'-Schlœsselbuchstabe
25 Fehlendes -r-Argument
26 Angegebener Anmeldename oder SID nicht in p-Datei
29 Es kann kein neuer Prozeﬁ erstellt werden, versuchen Sie es erneut
33 Interner Fehler in delta/enter()
34 Interner Fehler in delta/enter()
35 Interner Fehler in delta/enter()
351 fputs kann nicht auf Datei schreiben
$set 4
1 CMR-Liste ist zu lang.
2 r auﬁerhalb des erlaubten Bereichs
3 Datum/Zeit falsch date/time
4 Unbekannter Schlœsselbuchstabe
5 Wert nach %c Argument
6 Schlœsselbuchstabe doppelt
7 Fehlendes Dateiargument
8 e nicht zusammen mit m erlaubt
9 User ID nicht in Kennwortdatei
10 Sperrdatei kann nicht erstellt werden
11 Seriennummer zu lang
12 SchreibfÃhiges `%s' existiert
13 %u Zeilen
14 Keine id-Schlœsselworte
15 Ungœltige id-Schlœsselworte
16 Keine id-Schlœsselworte
17 Falsche SID in newsid() berechnet
18 %s bereits eingefœgt
19 %s bereits ausgetragen
20 Interner Fehler in get/enter()
21 getcwd fehlgeschlagen
22 Verzeichnis kann nicht geÃndert werden
26 wird editiert: `%s'
27 Neues Delta
28 sid existiert nicht
29 Hintergrund-CASSI ohne CMRs erhalten
30 Hintergrund-CASSI mit ungœltigem CMR erhalten
31 Eingabe von durch Komma getrennter Liste von CMRs:
32 ?zu viele CMRs.
33 Sie mœssen midestens einen gœltigen CMR eingeben.
34 Geben Sie ungœltige CMRs erneut ein, oder drœcken Sie die Rœcklauftaste.
101 %y/%m/%d
102 %m/%d/%y
103 %H:%M:%S
104 %y/%m/%d
105 %m/%d/%y
106 %H:%M:%S
351 fputs konnte nicht auf Datei schreiben
$set 5
1 help: Konnte nicht ausgefœhrt werden: %1$s.  Errno=%2$d
$set 6
1 Ungœltige sid
2 Ungœltige cutoff-Datum
3 Wert nach %c Argument
4 Unbekannter Schlœsselbuchstabe
5 Schlœsselbuchstabe doppelt
6 Fehlendes Dateiargument
7 cutoff-Datum und SID kann nicht angegeben werden
8 Sie mœssen -e oder -l zusammen mit -c angeben
9 ja
10 nein
11 kein
27 getcwd fehlgeschlagen
28 Verzeichnis kann nicht geÃndert werden
29 getcwd fehlgeschlagen
30 Verzeichnis kann nicht geÃndert werden
31 SID existiert nicht
32 Vorzeitiges eof
33 Neuer Prozeﬁ kann nicht erstellt werden, versuchen Sie es erneut
34 '%s' kann nicht ausgefœhrt werden
35 (kein)
36 Verzweigung
37 Oberwert\t%s
38 Vorgegeben SID\t%s
39 Unterwert\t%s
40 id keywd err/warn\t%s
41 joint-Editierung
42 Gesperrte Releases\t%s
43 Module\t%s
44 Null-Delta
45 csect-Name\t%s
46 Type\t%s
47 œberprœfte MRs\t
$set 7
1 r hat keine sid
2 Unbekannter Schlœsselbuchstabe
3 Schlœsselbuchstabe doppelt
4 Cassi nicht kompatibel mit cmrs auf Befehlszeile
5 Fehlendes Dateiargument
6 Falscher Aufruf
7 Benutzeridentifikation nicht in Kennwortdatei
8 Fehlendes r
9 Datei %s existiert nicht
10 Sperrdatei kann nicht erstellt werden
11 sid existiert nicht
12 Sie sind weder Eigentœmer noch '%s'
13 Kein 'leaf'-Delta
14 MRs nicht erlaubt
15 Ungœltige MRs
16 Nicht erlaubte Verwendung von 'z'-Markierung \n CASSI InkompatibilitÃt
17 cmr nicht editierbare fœr CASSI-kontrollierte Datei- ÿnderung nicht erlaubt
18 Falscher cdc-Ersatz von cmr's (CASSI)
19 Delta angegeben hat MR freigegeben
20 *** GEÿNDERT ***
21 Nur ein cmr œbrig fœr diese Delta, keine ÿnderung mŒglich
22 MŒchten Sie %s lŒschen
24 %s  ist zur Zeit editierbar
25 Keine fred-Datei gefunden- siehe sccs-Verwaltung
26  %s ist nicht editierbar
27 CASSI-Meldung kann nicht geschrieben werden
28 %1$s chpost %2$s q %3$s sw MID=%4$s MFS=%5$s MPA=%6$s q q
29 Cassi-BD/Quelle kann nicht geschrieben werden
30 Editiert -- sid ist in p-Datei
31 *** LISTE GEL⁄SCHTER MRS ***
$set 8
1 Unbekannter Schlœsselbuchstabe
2 Wert nach %c-Argument
3 Schlœsselbuchstabe doppelt
4 Fehlendes Dateiargument
5 Sperrdatei kann nicht erstellt werden
6 Neuer Prozeﬁ kann nicht erstellt werden, versuchen Sie es erneut
7 SID muﬁ angegeben werden
8 Anmeldename nicht in p-Datei
9 Angegebene SID nicht in p-Datei
10 Keine offenen Deltas fœr: %s
$set 9
1     %1$s: %2$cM%3$c, -m nicht zutreffend
2     %1$s: %2$cY%3$c, -y nicht zutreffend
3     %s: SID existiert nicht
4     %s: SID ungœltig oder zu groﬁ
5     %s: Datei kann nicht geŒffnet werden oder Datei nicht SCCS
6     %s: beschÃdigte SCCS-Datei\n
7     %s: unbekanntes or doppeltes Schlœsselbuchstabenargument
8     %s: fehlendes Dateiargument
11 erwartet
12 oder
13 Delta-Erstellungsdatum nicht in Reihenfolge oder in der Zukunft
14 Falsche Kontrollzeile
15 Unerwartetes Dateiende
16 Checksum-Fehler
$set 10
1 Unbekannter Befehl in Zeile %d
2 `%s' niemals verwendet
3 `%s' niemals deklariert
4 `%s' niemals ein Wert zugewiesen
5 `if' ohne entsprechendes `end'
6 Syntax in Zeile %d
7 `%1$s' doppelt deklariert in Zeile %2$d
8 Fehler:%s
9 Falsche Anweisung in Zeile %d
10 `end' ohne entsprechendes `if' in Zeile %d
11 Meldung(%1$d):%2$s
13 Syntax in Zeile %d
14 Klammerfehler in Zeile %d
15 Ungœltiger Operator in Zeile %d
16 Nicht-numerischer Wert in Zeile %d
17 Kein ausreichender Platz [line %d]
18 Nichtzutreffendes `%1$c' in Zeile %2$d
19 Ungœltiger Schlœsselwortname in Zeile %d
20 Kein ausreichender Platz
21 Schlœsselwortname zu lang in Zeile %d
22 Syntax in Zeile %d
23 Nicht zutreffendes `%1$c%2$c' in Zeile %3$d
$set 11
1 %s kann nicht geŒffnet werden
$set 12
11 Pfile existiert an deltack 
12 Keine Anwendung mit -fz-Markierung gefunden
13 Keine FRED-Datei oder Systemname im admin-Verzeichnis 
15 ***CASSI REPORTS FEHLER: Kein CMRS in pfile: %s
16 CMRs nicht in P.Datei -schwere Inkonsistenz
17 ***CASSI REPORTS FEHLER: kein CMRS an sd
18 Keine CMR's œbrig, Delta nicht erlaubt
19 Die CMRs fœr dieses Delta sind nun:
20 OK ??
24 Sie mœssen mindestens eine gœltige cmr-Nummer eingeben
25 Neue CMR-Nummer oder Rœcklauftaste 
26  \n doppelte CMR-Nummer ignoriert
27  \n ungœltige CMR ignoriert 
28  \n zu viele CMRs hinzugefœgt, keine weiteren erlaubt 
29  \n zu lŒschende CMR-Nummer (oder Rœcklauftaste) ? 
30 \n nur ein CMR œbrig, weitere kŒnnen nicht gelŒscht werden
31 \n nicht auf der Liste, Anfrage ignoriert
32 ***CASSI REPORTS FEHLER: schreiben nach FRED nicht mŒglich : %s
33  Cassi Schnittstellenmeldung kann nicht geschrieben werden
34 %1$s chpost %2$s q %3$s %4$s MID=%5$s MFS=%6$s MPA=%7$s q q
35 ***CASSI REPORTS FEHLER: Schreiben nach BD/Quelle nicht mŒglich : %s
36 Cassi BD/Quelle kann nicht geschrieben werden
37 ging an falsche FRED-Datei %s
101 ungœltige sid
111 Uhr falsch eingestellt!!!
112 Uhr kann falsch eingestellt sein!
121 MRs?
122 Kommentare?
123 Standardeingabe angegeben w/o -y und/oder -m Schlœsselbuchstabe
124 Zeile zu lang
125 Antwort zu lang
126 Neuer Prozeﬁ kann nicht erstellt werden; versuchen Sie es erneut
127 Zu viele MRs
128 MR Nummer zu lang
129 MR Nummer zu lang
130 Kein ausreichender Platz
141 Eingeschlossen:
142 Ausgeschlossen:
151 Falscher Bereich
152 Deltalistensyntax
161 Formatfehler in Zeile %u
171 Frœhzeitiges Dateiende
172 BeschÃdigte Datei
181 Nicht berechtigt, Deltas zu produzieren
182 Release %1$u < %2$u (Unterwert)
183 Release %1$u > %2$u (Oberwert)
184 SCCS-Datei gegen Editierung gesperrt
185 Release `%d' gegen Editierung gesperrt
191 Falsches p-Dateiformat
204 Frœhzeitiges Dateiende
211 zu lang
212 Keine SCCS-Datei
213 Mehr als eine Bindung
221 Datei lÃnger als 99999 Zeilen
321 Kein ausreichender Platz
324 ffree: Pointer zeigt nicht auf belegten Bereich
331 Verzeichnis `%s' existiert nicht
341 Keine Datei
342 `%s' existiert nicht
343 Verzeichnis `%s' nicht schreibfÃhig
344 Kein Platz!
345 Schreibfehler
346 errno = %1$d, Funktion = `%2$s'
$set 13
2 Es existiert kein Platz, um fœr Hilfe œber %s zu suchen\n
3 Es ist keinerlei Hilfe verfœgbar œber %s\n
4 Wie lautet die Meldungsnummer oder der SCCS-Befehlsname? 
