$set 1
1 un/used/avail
101 newline oder ;
201 Erhielt Signal #%d\n
203 Speicherfehler in Shell: Bereinigung.
204 trap 11 nicht mÎglich
205 trap 18 nicht mÎglich
301 Bindungen werden rÏckgÌngig gemacht
401 hits\tcost\tcommand\n
402  ist in Shell intergriert\n
403  ist eine Funktion\n
404  nicht gefunden\n
405  ist hashed (
406  ist in Shell integriert\n
407  ist
601 falsche Option(s)
602 Sie haben Post\n
603 kein Platz
604 kein Stapelplatz
605 Syntaxfehler
606 unbekanntes Signal
607 Falsche Zahl
608 Parameter null oder nicht belegt
609 Parameter nicht belegt
610 Falsche Substitution
611 Erstellung nicht mÎglich
612 Erstellung eines neuen Prozesses fehlgeschlagen - zu viele Processe
613 Erstellung eines neuen Prozesses nicht mÎglich: Kein ausreichender Swap-Bereich
614 beschrÌnkt
615 Pipe kann nicht erstellt werden
616 Úffnen nicht mÎglich
617  - Kern ausgegeben (dumped)
618 Argumentliste zu lang
619 Text aktiv
620 zu groŞ
621 AusfÏhrung nicht mÎglich
622 nicht gefunden
623 Falsche Dateinummer
624 Shift nicht mÎglich
625 Falsches Verzeichnis
626 Falscher Trap
627 kann nur gelesen werden
628 ist keine Kennung
629 falsches ulimit
630 RÏcksprung nur aus einer Funktion mÎglich
631 Funktionen kÎnnen nicht exportiert werden
632 Belegung kann nicht rÏckgÌngig gemacht werden
633 Kein Heimverzeichnis
634 Berechtigung "AusfÏhren" verweigert
635 sh-Fehler: Kennwort zu lang
636 unbekannter Operator
637 Dateiende
638  unerwartetes
639  in Zeile
640 HÌngezustand
641 Ende
642 Unerlaubter Befehl
643 Trace/BPT Trap
644 Abbruch
646 EMT Trap
647 Gleitkomma-Ausnahme
648 Abgebrochen (killed)
649 Busfehler
650 Speicherfehler
651 Falscher Systemprozeduraufruf
652 Alarmruf
653 Beendet
654 Signal 16
655 Signal 17
656 Ende des Sohnprozesses
657 Stromausfall
658 export
659 Nur-Lesen
660 AusfÏhrbare Datei ist nicht mit der Hardware kompatibel
661 sigemptyset() fehlgeschlagen
662 sigprocmask() fehlgeschlagen
663 sigdelset() fehlgeschlagen
701 pwd: Status kann nicht ermittelt werden ..
702 pwd: Úffnen nicht mÎglich ..
703 pwd: Lesefehler in ..
801 execa fehlgeschlagen, t=%s\n
802 ptrace:
803 sh interner 2K-PufferÏberlauf
804 to_tcharn PufferÏberlauf
901 ] fehlt
902 Argument erwartet
903 ) erwartet
1001 Syntax: netunam  netzwerk_gerÌte_datei  anmelde_zeichenkette
1002 UngÏltige Fern-Anmeldung.	errnet =
1003 Fern-Knoten antwortet nicht.  errnet =
1004 UngÏltige NetzwerkgerÌtedatei.  errno =
1005 Unbekanntes integriertes Element\n
1006 Neuer ProzeŞ kann nicht erstellt werden: errno =
1007 Nicht unterstÏtzter Netzwerkaufruf
1101 sh: interner 2K-PufferÏberlauf
1102 sh: interner 2K-PufferÏberlauf
