$set 1
1 Ungœltige Verwendung der Befehlszeilenoptionen
3 Pfadname zu lang:
4 Zu viele Schlœssel
5 Es kann nur eine Datei geprœft werden
6 Belegungsfehler vor dem Sortieren
7 Temp kann nicht gefunden werden
8 Belegungsfehler vor dem Mischen
9 Warnung: Fehlendes NEWLINE am Dateiende hinzugefœgt
10 Warnung: Fehlendes NEWLINE am Ende der Eingabedatei hinzugefœgt
11 Fatal: Satz zu lang
12 Es wird sortiert
13 Es wird gemischt
14 Warnung: Fehlendes NEWLINE am Dateiende hinzugefœgt
15 Fatal: Zeile zu lang
18 Erstellen nicht mŒglich
19 Erstellen nicht mŒglich
20 ⁄ffnen nicht mŒglich
21 Warnung: Option -d fœr Multibyte-Sprachen ignoriert
22 Warnung: Option -f fœr Multibyte-Sprachen ignoriert
23 Warnung: -l nicht erforderlich, ignoriert
24 Warnung: Option -i fœr Multibyte-Sprachen ignoriert
25 Lesefehler auf
26 Schreibfehler wÃhrend
