$set 1
1 tar: TemporÌrdatei (%s) kann nicht erstellt werden\n
2 UngÏltige BlockgrÎŞe. (Max %d)\n
3 tar: %c: unbekannte Option\n
4 tar: BlockgrÎŞe %d zu groŞ, kein Speicher vorhanden\n
5 Es kÎnnen nur Standardausgabe-Archivdateien erstellt werden\n
6 tar: %s kann nicht geÎffnet werden\n
7 tar: Syntax  tar [-]{txruc}[ONvVwAfblHhm{op}][0-7[lmh]] [Banddatei] [BlockgrÎŞe]                 Datei1 Datei2...\n
8 tar: Syntax  tar [-]{txruc}[ONvVwfblHhm{op}][0-7[lmh]] [Banddatei] [BlockgrÎŞe]\n                 Datei1 Datei2...\n
9 tar: Syntax  tar [-]{txruc}[ONvVwAfblhm{op}][0-7[lmh]] [Banddatei] [BlockgrÎŞe]\n                 Datei1 Datei2...\n
10 tar: Syntax  tar [-]{txruc}[ONvVwfblhm{op}][0-7[lmh]] [Banddatei] [BlockgrÎŞe]\n                 Datei1 Datei2...\n
11 tar: Syntax  tar [-]{txruc}[ONvVwAfblm{op}][0-7[lmh]] [Banddatei] [BlockgrÎŞe]\n                 Datei1 Datei2...\n
12 tar: Syntax  tar [-]{txruc}[ONvVwfblm{op}][0-7[lmh]] [Banddatei] [BlockgrÎŞe]\n                 Datei1 Datei2...\n
13 Es wird versucht, eine Archivdatei aus leerer Dateimenge zu erstellen.\nNichts ausgegeben (dumped).\n
14 Fehlender Link zu %s\n
15 Verzeichnis-PrÏfsummenfehler\n
16 tar: Status von %s kann nicht ermittelt werden. Nichts ausgegeben (dumped).\n
17 Wahlfreie acl-EintrÌge fÏr <%s> nicht ausgegeben\n
18 tar: %s: Verzeichnis-Lesefehler\n
19 tar: %s: symbolischer Link zu lang\n
20 tar: Symbolischer Link kann nicht gelesen werden
21 a %1$s symbolischer Link zu %2$s\n
22 a %s 0 BlÎcke\n
23 tar: %s: Datei kann nicht geÎffnet werden\n
24 a %1$s Link zu %2$s\n
25 Kein ausreichender Speicher. Link-Information verloren\n
26 a %1$s %2$ld BlÎcke\n
27 %s: DateigrÎŞe hat sich geÌndert\n
28 tar: %s ist keine Datei. Nicht ausgegeben (dumped).\n
29 tar: %s: Symbolischer Link fehlgeschlagen: 
30 x %1$s symbolischer Link auf %2$s\n
31 %s: Binden nicht mÎglich\n
32 Link von %1$s auf %2$s\n
33 tar: %s Zeichen-GerÌt kann nicht erstellt werden\n
34 x %s, 0 Byte, 0 BlÎcke, Zeichen-GerÌt\n
35 tar: %s Block-GerÌt kann nicht erstellt werden\n
36 x %s, 0 Byte, 0 BlÎcke, Zeichen-GerÌt\n
37 tar: %s FIFO kann nicht erstellt werden\n
38 x %s, 0 Byte, 0 BlÎcke, FIFO\n
39 tar: %s wird als regulÌre Datei erstellt.\n
40 tar: %s - kann nicht erstellt werden\n
41 x %1$s, %2$ld Byte, %3$ld BandblÎcke\n
42 tar: %s: HILFE - Schreibfehler wÌhrend des extract-Vorgangs\n
43 tar: chmod fehlgeschlagen
44 tar: chown fehlgeschlagen
45  hat Link zu %s
46  hat symbolischen Link zu %s
47 %b %2d %H:%M %Y
48 tar: Benutzername kann fÏr uid %d nicht ermittelt werden\n
49 tar: Gruppenname kann fÏr gid %d nicht ermittelt werden\n
51 tar: pwd-GerÌt
52 tar: Limit fÏr pwd-Tiefe Ïberschritten!\n
53 tar: Bandlesefehler\n
54 tar: BandblockgrÎŞe fehlerhaft\n
55 tar: BlockgrÎŞe = 0; Pipe unterbrochen?\n
56 tar: BlockgrÎŞe = %d\n
57 tar: Fehler! BlockgrÎŞe geÌndert\n
58 tar: Fehler beim Schreiben auf das Band\n
59 tar: %s: Pfadname zu lang\n
60 tar: %s: PrÌfix zu lang\n
61 tar: %s: Dateiname zu lang\n
62 %s: Dateiname zu lang\n
63 tar: Bandfehler (%d)\n
64 tar: Fehler auf neuem DatentrÌger\n
65 /dev/tty kann nicht geÎffnet werden, um weitere DatentrÌger anzufordern.\n
66 tar: Bandende\n
67 tar: Geben Sie den GerÌte-/Dateinamen ein, wenn Sie bereit sind,\n     oder eine leere Zeichenkette, um die Verarbeitung zu beenden.\n
68 Leeren Namen als nÌchste GerÌtedatei angegeben.\n
69 tar: %s konnte nicht geÎffnet werden\n
70 Benutzer Îffnete Datei %s zur Fortsetzung.\n
71 tar: %s konnte Verzeichnis nicht erstellen \n
72 tar: %s: Link zum Namen zu lang\n
73 tar: %s: Kein Zugriff auf Datei\n
74 tar: Nicht genÏgend Speicher. Keine "symbolic link loops" gefunden\n
75 tar: Schleife in symbolischem Link gefunden, tar abgebrochen\n
76 tar: Verzeichnis kann nicht nach '%s' geÌndert werden\n
77 tar: Pfad '%s' Ïbersprungen\n
78 tar: Option nicht unterstÏtzt fÏr QIC-GerÌte %s\n
