$set 1
1 Datei kann nicht geÎffnet werden
2 Globale Option falsch dargestellt
3 Falsche Option
4 Falsche Tabellenspezifikationszeichen
5 Zu viele Zeilen in Spezifikation
6 Keine Spezifikation
7 Letztes Zeichen in Formatzeile ist kein Punkt
8 versuchte Erweiterung der Tabelle in T&, nicht erlaubt
9 Erste Spalte kann kein S-Typ sein
10 Warnung: a-Typ-Spalten kÎnnen nicht erstellt werden, geÌndert zu l\n
11 Warnung: n-Typ-Spalten kÎnnen nicht erstellt werden, geÌndert zu c\n
12 Erste Zeile kann keine senkrechte Ausdehnung enthalten
13 Zu viele Spalten in Tabelle
14 Nicht abgeschlossener Zeichensatzname
15 PunktgrÎŞe zu groŞ
16 PunktgrÎŞe nicht sinnvoll
17 Senkrechter Vorlaufwert zu groŞ
18 Spaltenbreite zu groŞ
19 Dateiende beim Lesen der Tabellenspezifikation erreicht
20 Spezifikationszeile zu lang
21 Kein Speicher zur VerfÏgung
22 Senkrechter Vorlauf in erster Zeile nicht erlaubt
23 Tabelle in Zeile %1$d Datei %2$s ist zu breit - \\n(TW Einheiten\n
24 %1$s: Zeile %2$d: Daten ignoriert in Tabellenzeile %3$d\n
25 Kein Daten in Tabelle.
26 Keine echten Zeilen in Tabelle.
27 Zu viele Zeichen in Tabelle
28 Kein Platz fÏr Zeichen
29 Kein Platz fÏr Vektoren
30 Es kÎnnen keine Zeichen gefunden werden, welche als Trennzeichen verwendet erden kÎnnen
31 \n%1$s: Zeile %2$d: %3$s\n
32 tbl beendet\n
33 Abbruch aufgrund einer Fehlerbedingung, erkannt durch den TabellenprÌprozessor\n
34 Zu viel Backup
35 Unerwartetes Dateiende
36 Zu viele Textblockaufteilungen
37 Zu viele Spalten fÏr Register
