$set 1
3 Verarbeitung der Datei beendet: %s\n
5 gtwvec: dir %s\n
6	  return - %d\n
7 einfœgen(%s)
8 fœge %s ein
9 an %d\n
10 Interner Caller-Typ %s\n
11 mlock %s fehlgeschlagen\n
12 mlock %s erfolgreich abgeschlossen\n
13 Timeout bei generischem ⁄ffnen\n
16 Generisches ⁄ffnen (%d) fehlgeschlagen, errno = %d\n
19 %s nicht in Dialers-Datei gefunden\n
22 gdial(%s) aufgerufen\n
23 dkcall(%s)\n
27 tcpdial Host %s,
28 Anschluﬁ %d\n
29 Keine Socketschnittstelle: %s\n
31 Keine Socketschnittstelle, errno %d\n
34 Timeout in tcpopen\n
37 Familie: %d\n
38 Anschluﬁ: %d\n
39 Adresse : %08x\n
40 Verbindungsaufbau fehlgeschlagen: %s\n
42 Verbindungsaufbau fehlgeschlagen, errno %d\n
45 unetdial Host %s,
46 Anschluﬁ %d\n
47 tcpopen fehlgeschlagen: errno %d\n
48 OPEN fehlgeschlagen %s\n
50 COM1-Rœckgabewert = %d\n
52 Timeout bei sytek-⁄ffnen\n
53 OPEN 2 fehlgeschlagen %s\n
54 mlock %s fehlgeschlagen\n
55 Verwende Anschluﬁ %s,
56 acu - %s,
57 Telefonnummer  %s\n
58 Versuche Modem - %s,
59 acu - %s,
60 Ruf: %s:
61 ERFOGREICHE AUSF€HRUNG\n
62 fehlgeschlagen\n
63 %s kann nicht geŒffnet werden\n
64 %s ist geŒffnet\n
65 Timeout beim ⁄ffnen des Modems\n
66 Anwahl fehlgeschlagen. Kindprozeﬁ abgebrochen.\n
68 ACU-Schreibfehler %d\n
69 Anwahl unter Verwendung von Programm %s\n
72 dcf ist %d\n
73 Fork-Status %o\n
74 DN schreibt %s\n
75 Timeout
76 %s kann nicht geŒffnet werden\n
77 %s ist geŒffnet\n
78 %s kann nicht geŒffnet werden\n
79 dcf ist %d\n
80 ACU Schreibfehler %d\n
81 ACU-Schreibvorgang ist ok%s\n
82 Verbindung offen %s\n
83 fehlgeschlagen
84 chdir(%s)\n
85 [-xNUM] [-r[0|1]] -sSYSTEM
88 %s nicht in Systemsdatei\n
89 \tSyntax: %s %s\n
90 Kein -s angegeben\n
91 System angegeben: -smeinname: %s,
92 cico.c: meinname - %s\n
93 cico.c: Login-Benutzer - %s\n
95 sys-%s\n
98 Rœckgabewert von callcheck: %s
109 Momentan Kommunikation mit %s\n
112 %s - fehlgeschlagen\n
113 %s - fehlgeschlagen\n
114 Login erfolgreich: System=%s\n
115 msg-%s\n
117 HANDSHAKE fehlgeschlagen: %s\n
118  Rmtname %s,
119 Role %s,
120 MASTER
121 SLAVE
122 Ifn - %d,
123 Login-Benutzer - %s\n
126 %s - Timeout\n
127 Startup
130 %s\n
133 Cntrl - %d\n
138 Rœckgabe von restline - %d\n
139 Exit Code %d\n
140 GesprÃch abgeschlossen: Status %s\n\n
141 FEHLGESCHLAGEN
142 ERFOLGREICHE AUSF€HRUNG
143 TM_cnt: %d\n
145 Syntax: uuname [-l]\n
146 "%s"-Datei kann nicht geŒffnet werden
293 *** TOP ***	 -  role=%d,
295 Wdatei - %s,
296 Jobid = %s\n
301 Anfrage: %s\n
305 Fehlgeschlagen: Zugriff verweigert\n
311 Fehlgeschlagen: %s kann nicht gelesen werden\n
314 Anfrage: %s\n
318 Fehlgeschlagen: Access verweigert--Datei: %s\n
322 Fehlgeschlagen: Kein Platz!\n
323 wrktype - %c\n
324  PROZESS: Meldung - %s\n
326 RQSTCMPT:
329 HUP:
331 SLAVE-switchRole (%s)\n
332 TRUE
333 FALSE
335 SNDDATEI:
344 Meldung - %s\n
345 Remote angefordert: %s\n
346 SLAVE - Dateiname: %s\n
349 Fehlgeschlagen: Zugriff verweigert\n
351 chkpth ok Rmtname - %s\n
355 Fehlgeschlagen: TemporÃrdatei kann nicht erstellt werden\n
361 ->PUBDIR %d\n
363 RCVDATEI:
375 Remote angefordert: %s\n
376 Meldung - %s\n
377 W_DATEI1 - %s\n
382 Fehlgeschlagen: Zugriff verweigert\n
383 requestOK fœr Login-Benutzer - %s\n
386 Fehlgeschlagen: Zugriff verweigert\n
387 chkpth ok Login-Benutzer - %s\n
391 Fehlgeschlagen: %s kann nicht geŒffnet werden\n
393 rmesg - '%c'
394 %s erhalten\n
395 FAIL
398 %s erhalten\n
401 %s erhalten\n
402 wmesg '%c'
403 %s\n
404 mailopt %d,
405 statfopt %d\n
413 STMES %s\n
417 Proto gestartet %c\n
418 Proto Start-Fehler %c\n
419 conn(%s)\n
420 getto Rœckgabe %d\n
421 Schlieﬁe Caller (%d)\n
422 delock(%s)\n
423 Aufruf fehlgeschlagen: %s\n
424 GerÃtetyp %s gewœnscht\n
425 Angeforderter GerÃtetyp nicht gefunden\n
427 Falscher Zeitpunkt zum Aufruf: %s\n
428 ProtoStr = %s\n
430 erwarte: (
431 erhalten\n
432 Verbindung verloren errno - %d\n
435 bereits ausreichend\n
436 erhalten\n
437 Timeout eingetreten\n
438 BREAK\n
439 EOT\n
440 sendthem (
441 VERZ⁄GERUNG\n
442 <kein CR>
443 <kein CR - MITTE IGNORIERT>\n
444 PAUSE\n
445 ECHO PR€FUNG EIN\n
446 ECHO PR€FUNG AUS\n
447 BREAK\n
448 ^M
449 )\n
458 %s voll\n
459 dturnon: Rœckgabe=%d,
460 Ofn=%d,
461 errno=%d\n
462 ewrmsg-Schreiben fehlgeschlagen\n
463 erdmsg-Lesen fehlgeschlagen\n
464 ewrdata fehlgeschlagen\n
465 ewrmsg-Schreiben %d\n
466 ewrmsg-Rœckgabe %d\n
468 erdblk-MeldungslÃnge %d\n
469 erdblk-Rœckgabe %d\n
470 erdblk fehlgeschlagen\n
471 erdblk zuviel gelesen\n
472 <- %ld / %ld.%.3d sek
473 erdblk-Timeout\n
474 frage %d
475 Lesen fehlgeschlagen\n
476 %d erhalten\n
477 mkdir - %s\n
478 Status des œbergeordneten Verzeichnisses %s kann nicht ermittelt werden
479 errno %d\n
480 Zugriff auf œbergeordnetes Verzeichnis %s kann nicht verÃndert werden
481 errno %d\n
483 Zugriff auf Parent %s kann nicht verÃndert werden\n
487 Falscher Dateiname (%s).\n
489 Eingabe von frdmsg:
490 Prœfsumme: %04x\n
491 ack - '%c'\n
494 ERNEUTER VERSUCH:\n
495 fwrdata-Rœckgabe: %d\n
498 sende ack: 'R'\n
499 ERNEUTER VERSUCH:\n
500 sende ack: 'Q'\n
501 sende ack: 'G'\n
502 frddata-Rœckgabe: %d\n
503 \nPrœfsumme: %04x\n
504 falsche Prœfsumme\n
505 Daten zerstŒrt\n
506 gename(%c,
507 %s,
508 %c)\n
509 Null-sys -> %s\n
510 Datei - %s\n
512 %s seq
513 nun %x\n
514 : Falsche Option --
515 : Option erfordert ein Argument --
516 : Option erfordert ein Argument --
517 Status von %s wird ermittelt\n
519 %s kann nicht gesperrt werden\n
520 %s œbergeben
521 nach %s\n
522 imsg %s>
524 fixline(%d,
525 %d)\n
527 fixline - direkt\n
529 setline - %c\n
530 sytfixline - Geschwindigkeit= %d\n
534 fixline(%d,
535 %d)\n
536 Syntax: %s -f skript [-d] [-v]\n
537 %s unbekannt
538 Syntaxfehler
539 Verwendung: erwarte Zahlenkette
540 Verwendung: erwarte Zahlenkette
546 Fehlendes Label
547 Fehler oder goto nicht mŒglich
548 Label %s nicht gefunden
550 %s nicht gefunden
551 erwartete Zahl
552 erwartete Zeichenkette
554 zu viel Argumente
555 erwartete Markierung
556 Markierung "%s" nicht erkannt
557 logFind aufgerufen (Name: %s,
558 rmtname: %s)\n
559 machine/login Abstimmung fehlgeschlagen
560 _Request (%s),
561 TRUE
562 FALSE
563 _Switch (%s),
564 TRUE
565 FALSE
566 _CallBack (%s),
567 TRUE
568 FALSE
569 _MyName (%s),
570 mchFind aufgerufen (%s)\n
584 _Commands %s\n
585 malloc() Fehler\n
586 Liste (%s)
587 num = %d\n
588 %s kann nicht geŒffnet werden\n
589 Name (%s) nicht gefunden; Rœckgabefehler\n
590 %s kann nicht geŒffnet werden\n
591 validateFind (%s) Fehler\n
593 Falsche Option (%s) in PERMISSIONS\n
594 \n*****************************\n
595 **falsche OPTION in PERMISSIONS-Datei: %s\n
596 *****************************\n
597 cmdOK(%s, )\n
598 bname=%s\n
600 not cntl\n
601 alloc ÿnderung nicht implementiert\n
602 pkcntl: RR/RJ: Connodata=%d\n
603 srj nicht implementiert\n
604 r short %d wœnscht %d\n
605 rzÃhler = %d\n
606 xzÃhler = %d\n
607 Versuche = %d\n
608 pkgetpack: Connodata=%d\n
609 rec h->cntl %o\n
610 falsche €berschrift %o,
611 h->ccntl %o\n
612 Zustand -
613 falsche €berschrift %o\n
614 bp NULL %s\n
615 sende %o\n
618 Alarm %d\n
619 KILL %s\n
620 Bindungen von %s kŒnnen nicht rœckgÃngig gemacht (unlinked) werden\n
621 %s kann nicht gesperrt werden\n
622 %s kann nicht fœr Lesezugriff geŒffnet werden\n
623 Job %s ist gelŒscht\n
624 Job %s nicht gefunden\n
625 fp: %o\n
626 job %s bereits abgeschlossen\n
627 Berechtigung verweigert\n
629 shio - %s\n
630 Status %d\n
634 WIEDERHOLUNGSZEIT (%ld) NICHT ERREICHT\n
636  Eingabe ub_sst, Status ist : %d\n
637 Rmtname: %s\n
638 ulockf von %s fehlgeschlagen\n
639 fopen von %s fehlgeschlagen\n
640 in ub_sst Name=Rmtname: %s\n
641 ulockf fehlgeschlagen in onelock()\n
642 ulockf-Datei %s\n
643 Lockdatei--Lesen nicht mŒglich (errno %d) --entferne!\n
644 Lockdatei--falsches Format--entferne!\n
645 Lockdatei--Prozeﬁ weiter aktiv--nicht enfernt\n
646 kill pid (%d),
647 %d zurœckgegeben
648 --bereit Lockdatei (%s) zu entfernen\n
649 ulockf fehlgeschlagen in unlink()\n
650 ulockf Datei %s\n
651 Lockdatei--Lesen nicht mŒglich (errno %d) --entferne!\n
652 --bereit Lockdatei (%s) zu entfernen\n
653 ulockf fehlgeschlagen in unlink()\n
657 link(%s,
658 %s)\n
660 [-v] [-xNUM]
661 \tSyntax: %s %s\n
662 \tSyntax: %s %s\n
663 *** uucheck:  Prœfe notwendige Dateien und Verzeichnisse\n
664 *** uucheck:  Verzeichnisprœfung abgeschlossen\n\n
665 *** uucheck:  Prœfe %s Datei\n
666 *** uucheck:  %s Prœfung abgeschlossen\n\n
667 ** %s \n\n
668 MASCHINENPHASE (wenn wir ihre uux-Anfragen aufrufen oder ausfœhren)
669 LOGNAMENPHASE  (wenn wir angerufen werden)
670 %s kann nicht geŒffnet werden\n
671 Wenn ein System sich anmeldet als:
672 \tWir werden sie zurœckrufen.\n\n
673 Wenn wir System(e) anrufen:
674 \tWir erlauben ihnen %s Dateien anzufordern.\n
675  
676 nicht
677 \tWe %s fœr sie auf diesen Aufruf hin Dateien aus Warteschlange senden.\n
678 werden
679 werden nicht
680 \tSie kŒnnen Dateien versenden nach\n
681 \t	  %s (STANDARD)\n
682 \t	  %s\n
683 \tAusnahme\n
684 \t	  %s\n
685 \tSie kŒnnen Dateien anfordern von\n
686 \t	  %s (STANDARD)\n
687 \t	  %s\n
688 \tAusnahme\n
689 \t	  %s\n
690 \tEigener Name fœr die Konversation wird %s sein.\n
691 \tPUBDIR fœr die Konversation wird %s sein.\n
692 Maschine(n):
693 \nFolgende Befehle kŒnnen ausgefœhrt werden:\n
694 Softwarefehler in Berechtigung.c\n
695 Befehl (%s), Vollname (%s)\n
696 Unbekannte Markierung %s\n
697 %s Verzeichnis nicht lesbar\n
698 DEBUG# %s\n
699 START
700 Verzeichnis kann nicht in %s geÃndert werden\n
701 Status fœr %s kann nicht ermittelt werden\n
702 Bindungen fœr Datei %s rœckgÃngig machen (unlink)\n
703 PrÃfix: %s\n
704 chkpre fehlgeschlagen - Datei : %s\n
709 STM %d\n
710 [-oTage] [-mZeichenkette] [-Ctage] [-Dtage] [-Wtage] [-Xtage] [-xEbene] [-sSystem]
711 \tSyntax: %s %s\n
712  Optionen: CDWXo erfordert Wert > 0\n
713 \tSyntax: %s %s\n
714 Progname (%s): GESTARTET\n
715 Myname (%s),
716 _ShortLocal (%s)\n
717 Tage C.(%d),
718 D.(%d),
719 W.(%d),
720 X.(%d),
721 andere (%d)\n
722 VERZEICHNIS (%s) KANN NICHT GEÿNDERT WERDEN: errno (%d)\n
723 ⁄FFNEN NICHT M⁄GLICH (%s): errno (%d)\n
724 Verzeichnis: %s\n
725 Datei: %s\n
726 xprozess(%s),
727 unlink(%s)\n
729 \n\t%s!%s -> %s!%s	 (Datum %2.2d/%2.2d)\n\nAusfœhrung nicht mŒglich.
730 \n\t%s!%s  (Datum %2.2d/%2.2d)\n
731 \n\t%s!%s -> %s!%s	 (Datum %2.2d/%2.2d)\n
732 cprozess(%s)\n
733 ⁄ffnen der Datei nicht mŒglich (%s),
734 errno=%d -- œberspringe!\n
735 dummy C. -- unlink(%s)\n
740 text (%s)\n
741 wprocess(%s)\n
742 ⁄ffnen der Datei nicht mŒglich (%s),
743 errno=%d -- œberspringe!\n
744 dummy C. -- œberspringe(%s)\n
745 short line (%s):
746 falsch D. -- œberspringe(%s)\n
748 %s kann nicht gelesen werden\n
749 retaddr (%s)\n
751 text (%s)\n
752 oprocess(%s),
753 unlink(%s)\n
755 dDprocess(%s),
756 unlink(%s)\n
758 dXprocess(%s),
759   unlink(%s)\n
761 dMprocess(%s)\n
762   Lokale Datei %s:
763   Remote-Datei %s:
764 toBenutzer %s,
765 toSystem %s
766 Post gesendet, unlink(%s)\n
768 dNprocess(%s)\n
769   Lokale Datei %s,
770 unlink(%s)\n
772   Remote-Datei %s,
773 Ausfœrung von rnews(%s),
774 unlink(%s)\n
776 Datei kann nicht geŒffnet werden (%s),
777 errno=%d -- œberspringe!\n
778 buf: %s\n
782 Verschicke (mail) %s nach
785 sendMail: %s\n
789 Rnews %s\n
791 toWho(%s)\n
792 buf: %s\n
794 unbekannte Markierung %s\n
796 START
797 Kein Arbeitsverzeichnis - %s - nutze Hilfe\n
798 UID %d,
799 Benutzer %s\n
800 Syntax: uucp von ... nach\n
801 Falsches System: %s\n
802 sys2: %s,
803 fwd2: %s,
804 file2: %s\n
805 Falsches System: %s\n
806 Falsche Syntax %s\n
807 sys1 - %s,
808 file1 - %s,
809 Rmtname - %s\n
812 uucp komplett fehlgeschlagen: Code %d\n
813 uucp teilweise fehlgeschlagen: %d Fehler
814  \n
815  \n
816 alle Arbeit hier %d\n
817 Kann nicht Dateistatus %s erhalten\n kopieren fehlgeschlagen\n
818 %s %s - dieselbe Datei; kopieren nicht mŒglich\n
819 Berechtigung verweigert\n
820 Verzeichnisname ungœltig - %s\n
821 uucp kann nicht lesen (%s) Modus (%o)\n
822 Verwende CP-Befehl\n
823 Datei(%s) kann nicht geschrieben werden, Modus (%o)\n
824 Lokale Kopie:  uidxcp(%s,
825 %s\n
826 Kann Datei (%s) nicht kopieren, errno %d\n
827 Empfangsdatei - %d\n
831 Sendedatei - %d\n
832 Status fœr Datei %s kann nicht ermittelt werden\n
833 Verzeichnisname ungœltig - %s\n
837 cmd: %s\n
838 getty: Timeout-Argument ungœltig. "%s"\n
839 Prœfe Modus-Verwendung: getty -c gettydefs-like-datei\n
840 %s kann nicht geŒffnet werden\n
841 getty: keine Terminal-Verbindung angegeben.\n
842 getty: %s kann in "%s" nicht gefunden werden.\n
843 getty: "%s" kann nicht geŒffnet werden. errno: %d\n
844 %.9s\r\n
845 getty: Zeiger auf nÃchste Geschwindigkeit in Eintrag %s ist falsch.\n
846 getty: Es ist nicht mŒglich, %s erneut zu finden.\n
847 \r\n
848 getty: "%s" kann nicht geŒffnet werden.\n
849 Eintrag zu lang.\n
850 \n**** NÃchster Eintrag ****\n%s\n
851 id: %s\n
852 Anfangsmarkierungen:\niflag- %o oflag- %o cflag- %o lflag- %o\n
853 Endmarkierungen:\niflag- %o oflag- %o cflag- %o lflag- %o\n
854 Meldung: %s\n
855 nÃchste id: %s\n
856 Parsing-Fehler im "%s"-Feld\n%s<--Fehler hier festgestellt\n
857 Nicht definiert: %s\n
861 Syntax:  %s	  [-m] [Verzeichnisse...]\n
862	    %s -s [-m] [Verzeichnisse...]\n
863	    %s -k [-m] [Verzeichnisse...]\n
864 Status des Verzeichnis kann nicht ermittelt werden
865 Verzeichnis kann nicht geŒffnet werden (opendir)
866 Verzeichnis zu groﬁ
867 Verzeichnis kann nicht geÃndert werden (chdir) nach
869 total
870 Waisen:
871 Andere:
872 \n
873 Transaktionen:
874 \n%*s
875 %*s%-*s %s
876 \n
877 %*s\n
880 %s: Falsche Option -- %c\n
881 %s: Option erfordert ein Argument -- %c\n
882 [-xNUM] [-uNUM]
883 \tSyntax: %s %s\n
884 \tSyntax: %s %s\n
885 Progname (%s): GESTARTET\n
886 Keine Limitdatei - %s\n
887 Uusched Limit %d --
888 %d gefunden -- bereinige\n
889 Fortsetzung\n
890 Maschine: %s,
891 ccount: %d\n
892 Ausfœhrung num=%d \n
893 num=%d,
894 snumber=%d,
895 Rmtname=%s\n
896 Aufruf von exuucico(%s)\n
897 System %s gesperrt oder Status nicht korrekt--œberspringe\n
898 Maschine(%s) angerufen\n
900 ret=%d,
901 errno=%d\n
902 %-*.*s
903 %3.d Cmd%s
904    ---
905 %3.d Data
906    ---
907 %3.d Xqt%s
908    ---
909 GESPERRT
910 SPRECHBETRIEB
911 Wiederholungszeit erreicht
912 Wiederholungszeit %ld sek%s
913 Wiederholungszeit %ld min%s
914 ZÃhler: %d\n
915 Fremddatei (%s) in %s\n
916    \t(pid ??)
917    \t(pid ??)
918    \t(pid %d)
919 [-a] [-q] or [-m] or [-kJOB] or [-rJOB] or [-p]
920 [-sSystem] [-uBenutzer]
921 \tSyntax: %s %s\n
922 or\n\tSyntax: %s %s\n
923 \tSyntax: %s %s\n
924 or\n\tSyntax: %s %s\n
925 Progname (%s): GESTARTET\n
926 Benutzer=%s,
927 Login-Benutzer=%s,
928 Jobid=%s,
929 Rmtname=%s\n
930 \tSyntax: %s %s\n
931 or\n\tSyntax: %s %s\n
932 Job %s kann nicht gefunden werden; nicht %s\n
933 abgebrochen
934 verjœngt
935 uprocessC(%s,
936 %s);\n
937 Status der Datei (%s) kann nicht ermittelt werden,
938  errno (%d) -- œberspringe!\n
939 Datei (%s) kann nicht geŒffnet werden,
940 errno=%d -- œberspringe!\n
941 %-12s  %2.2d/%2.2d-%2.2d:%2.2d:%2.2d  (POLL)\n
942 short line (%s)\n
943 Typ (%s),
944 Datei1 (%s)
945 Datei2 (%s)
946 Datei3 (%s)
947 Benutzer (%s)
948 %-12s  %2.2d/%2.2d-%2.2d:%2.2d
949 %-12s  %2.2d/%2.2d-%2.2d:%2.2d
950 %s kann nicht gelesen werden,
951 errno=%d -- œberspringe!\n
952 ????\n
953 kprocessC(%s,
954 %s);\n
955 Status kann nicht ermittelt werden:%s, errno (%d)-- %s nicht mŒglich!\n
956 abbrechen
957 verjœngen
958 Lesen nicht mŒglich:%s, errno (%d)-- %s nicht mŒglich!\n
959 abbrechen
960 verjœngen
961 Falsches Format:%s, errno (%d)-- %s nicht mŒglich!\n
962 abbrechen
963 verjœngen
964 Typ (%s),
965 Datei1 (%s)
966 Datei2 (%s)
967 Datei3 (%s)
968 Benutzer (%s)
969 Nicht owner oder root - %s von job %s nicht mŒglich\n
970 abbrechen
971 verjœngen
972 Entferne %s\n
973 Fehler: %s nicht mŒglich, Datei ( %s), errno (%d)\n
974 abbrechen
975 verjœngen
976 Entferne %s\n
977 Fehler: %s nicht mŒglich, Datei ( %s), errno (%d)\n
978 abbrechen
979 verjœngen
980 Job: %s erfolgreich %s\n
981 abgebrochen
982 verjœngt
983 Maschine(%s),
984 m-M=%d\n
987 WARNUNG: Tabellenœberlauf--Ausgabe nicht vollstÃndig\n
988 %3dC
989 %4dX
990 %2.2d/%2.2d-%2.2d:%2.2d
991 Gesperrt
992 Wiederholung: %d:%2.2d
993  ZÃhler: %d
994 lckpid() - entered\n
995 lockdir (%s)\n
996 f (%s)\n
997 ????\n
1000 uusub: ⁄ffnen nicht mŒglich
1001 Syntax:uusub -a* -d* -c* -u* -r -l-f\n
1002 Flush Datei %s\n
1003 LŒsche System %s aus dem Subnetzwerk\n
1004 Fœge System %s dem Subnetzwerk hinzu\n
1005 System %s hinzugefœgt\n
1007 sysname\tsfile\tsbyte\trfile\trbyte\n
1008 %s\t%d\t%ld\t%d\t%ld\n
1009 sysname\t#call\t#ok\tlatest-oktime\t#noacu\t#login
1010 \t#nack\t#other\n
1011 %s\t%d\t%d
1012 \t(%d/%d-%d:%2.2d)\t
1013 %d\t%d\t%d\t%d\n
1014 Enter edit, Markierung: %d\n
1016 %s beibehalten\n
1018 Uusub ist auf diesem System nicht implementiert\n
1019  Flush Datei %s\n
1020  l.sys: %s\n
1022  Rmt: %s
1023  s_r: %s
1024  bytes: %ld
1025  oldtick: %ld\n
1026  %s innerhalb der Zeit\n
1027 %s ist geschrieben\n
1033 [-aName] [-b] [-c] [-C] [-j] [-gGrad] [-n] [-p] [-r] [-sDatei] [-xZahl] [-z] Befehls-Zeichenkette
1034 \tSyntax: %s %s\n
1036 START
1037 arg - %s:
1038 arg - %s\n
1039 Kein Spool-Verzeichnis - %s - Nutze Hilfe\n
1040 xsys %s\n
1041 Falscher Systemname: %s\n
1042 Benutzer %s\n
1043 cfile = %s\n
1044 rxfile = %s\n
1050 prm - %s\n
1051 syspart -> %s,
1052 rest -> %s,
1053 ret -> %d\n
1054 syspart -> %s\n
1055 Falscher Systemname: %s\n
1056 rest %s\n
1057 Dateistatus %s kann nicht ermittelt werden\n
1058 Berechtigung verweigert %s\n
1059 %s kann nicht kopiert werden %s\n
1061 uux fehlgeschlagen. Code %d\n
1062 exit Code %d\n
1064 [-xDEGUG] [-sSystem]
1066 \tSyntax: %s %s\n
1067 \tSyntax: %s %s\n
1068 \n\n** START **\n
1070 Keine Limitdatei - %s\n
1071 Uuxqt Limit %d --
1072 %d gefunden --
1073 verlasse\n
1074 Fortsetzung\n
1075 Benutzer - %s\n
1076 Prozeﬁ %s\n
1080 stashing %s\n
1081 xsort:  erstes war %s\n
1082 xsort:  erstes ist %s\n
1083 xget: %s zurœckgeliefert\n
1084 gt_Xfile %s erhalten\n
1085 rm_Xfiles: %s kann nicht gelesen werden\n
1086 mv_Xfiles: %s kann nicht gelesen werden\n
1088 unmv_Xfiles: %s kann nicht gelesen werden\n
1090 prm='%s'\n
1091 Vollname: %s\n
1093 retosndr %s,
1095 \n\t===== stderr war =====\n
1096 \n\t===== gut, ich versuchte es =====\n
1097 _Xfile - %s\n
1098 badfile - ein: %s\n
1099 badfile - aus: %s\n
1100 fin - %s,
1101 fout - %s,
1102 sysout - %s,
1103 user - %s\n
1104 incmd - %s\n
1110 falscher Befehl %s\n
1112 Befehl %s\n
1113 VollstÃndiger Befehl: %s\n
