$set 1
1 Syntax: %s -nstux [-|Datei] ...\n
2 %s: Status von stdout kann nicht ermittelt werden\n
3 %s: %s kann nicht geÎffnet werden\n
4 %s: Status von %s kann nicht ermittelt werden\n
5 %s: Eingabe %s ist Ausgabe\n
6 %s: SchlieŞfehler\n
7 %s: SchlieŞfehler\n
8 %s: Ausgabefehler\n
9 %s: Status 1 falsche Daten "%d"\n
10 %s: Status 2 falsche Daten "%d"\n
11 %s: Status 2 falsche Daten "%d"\n
12 %s: Status 2 falsche Daten "%d"\n
13 %s: Status 2 falsche Daten "%d"\n
14 %s: Status 3 falsche Daten "%d"\n
15 %s: Status 3 falsche Daten "%d"\n
16 %s: Status 3 falsche Daten "%d"\n
17 %s: Status 3 falsche Daten "%d"\n
18 %s: Keine normale Beendigung / Status %d\n
