$set 1
1 Syntax: write Benutzer [Terminal]\n
2 Syntax: write Benutzer [Terminal]\n
3 Terminalname kann nicht ermittelt werden. Keine Antwort mÎglich.\n
4 %1$s ist an mehr als einem Platz angemeldet.\nSie sind verbunden mit "%2$s".\nAndere Adressen sind:\n
5 %1$s ist an mehr als einem Platz angemeldet.\nSie sind verbunden mit "%2$s".\nAndere Adressen sind:\n
6 Berechtigung verweigert.\n
7 %1$s ist nicht an "%2$s".\n
8 Berechtigung verweigert.\n
9 %s ist nicht angemeldet.\n
10 Es kann nicht ermittelt werden, wer Sie sind.\n
11 Warnung: Sie haben Ihr Terminal auf "mesg -n" gesetzt. Keine Antworten mÎglich.\n
12 \n\007\007\007\tMeldung von %1$s (%2$s) [ %3$s ] ...\n
13 Schreiben nach %s nicht lÌnger mÎglich\n
14 Es kann kein neuer ProzeŞ gestartet werden. Versuchen Sie es spÌter erneut.\n
15 Timeout bei Versuch des Úffnens von %1$s's Verbindung(%2$s).\n
16 <EOT>\n
17 %a %h %d %H:%M:%S
