#	$Header: makefile,v 1.11.109.1 91/11/21 12:02:33 kcs Exp $
#
#	Makefile for installing sample ARPA/Berkeley services configuration files
#

CONFIGFILES =	netbsdsrc

all sall:

prod:

install: ${CONFIGFILES}
	test "${INS}" && ${INS} ${?}

${CONFIGFILES}:

trace:

debug:

clean:

clobber:

