default:
	: 

install:
	mkdir -p ../../../Filesets.sl/UX-CORE/etc/newconfig
	! cp checklist.wsio ../../../Filesets.sl/UX-CORE/etc/newconfig/checklist
	! chmog 444 bin bin ../../../Filesets.sl/UX-CORE/etc/newconfig/checklist
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE/etc/newconfig
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE/etc
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE
	! chmog 555 bin bin ../../../Filesets.sl
