default:
	:
install:
	mkdir -p ../../../Filesets.sl/UX-CORE/etc/newconfig
	! cp rc ../../../Filesets.sl/UX-CORE/etc/newconfig/rc
	! chmog 544 bin bin ../../../Filesets.sl/UX-CORE/etc/newconfig/rc
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE/etc/newconfig
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE/etc
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE
	! chmog 555 bin bin ../../../Filesets.sl
