default:
	: 
install:
	mkdir -p ../../../Filesets.sl/EDITORS/etc/newconfig
	! cp d.exrc ../../../Filesets.sl/EDITORS/etc/newconfig/d.exrc
	! chmog 444 bin bin ../../../Filesets.sl/EDITORS/etc/newconfig/d.exrc
	! chmog 555 bin bin ../../../Filesets.sl/EDITORS/etc/newconfig
	! chmog 555 bin bin ../../../Filesets.sl/EDITORS/etc
	! chmog 555 bin bin ../../../Filesets.sl/EDITORS/
	! chmog 555 bin bin ../../../Filesets.sl/
