#
#	Makefile configuration for gated
#
#	See Makefile.gated for the various options, but only modify this
#	file. 
#

#
#	Directory where gated and support programs will reside.  Usually
#	/etc (/usr/etc on SunOS 4.0).
#
DESTDIR=/etc

#
#	Include directories for NYSERnet's SNMP.
#
#SNMP_INCLUDE=/usr/include/arpa/snmp
SNMP_INCLUDE=

#
#	Include file which defines all the signals, usually
#	/usr/include/signal.h 
#
SIGNAL_H=/usr/include/signal.h

#
#	Make definitions.  Gated needs it's shell script front-end
#
MAKE=./make

#
#	Where to look for awk.
#
AWK=/usr/bin/awk

#
#	Compile time definitions.  These are defined in Makefile.gated
#
DFLAGS=

#
#	Where to find gated includes.
#
IFLAGS=	-I. -I.. -I../../../include 

#
#	Compiler flags, normally -O, -g for debugging
#
CFLAGS= -O

#
#	Compiler option to generate dependency files.  Usually -M (-eM
#	Under Ultrix and -MM with gcc)
#
CCD=	-M

#
#	Compiler to use, normally /bin/cc.  On an RT where HiC is not the
#	default, /bin/hic.  If you have GCC you may want to use that.
#
CC=	cc
# CC=	gcc -W -Wunused -Wreturn-type -Wcast-qual -Wpointer-arith -Wwrite-strings -Wcomment -Wswitch -Wshadow -pipe

#
#	Loader flags.  -lresolv may be handy if you want to use the
#	nameserver and don't have the resolver routines in libc.  For AIX
#	3.1 you will need '-lm -lbsd'
#
LDFLAGS= -lBSD

#
#	Flags for lint
#
LINTFLAGS=	-hxz

#
#	Lexical analyzer generator and flags.  Lex is ok, flex 2.1 is prefered.
#
LEX = lex
LFLAGS = -v
# LEX = flex
# LFLAGS = -p -s -c

#
#	Parser generator to use.  Just yacc for now, gated has not been
#	tested with bison.
#
YACC = yacc
YFLAGS = -d
# YACC = bison
# YFLAGS = -d -y

#
#	Command to use to see the first few lines of all c and h files
#	to look for $Header: when buliding version.awk.  If you don't
#	have head, cat will do, but will be much slower.
#
HEAD=	head -25

#
#	Command to update the symbol table in a library.  Should be
#	'ranlib' on BSD.  AIX/PS2 requires ':'.
#
#RANLIB=	ranlib

#
#	C compilation definitions.  On Vaxen the assembler output of the
#	compiler is processed by a sed script which translates a few
#	system calls directly into machine instructions.
#
ASMSED=	asm.sed

.c.o:
	@echo "Compiling:	"$*.c
#	Use the following line for non-VAX machines
	@${CC} -c ${CFLAGS} ${DFLAGS} ${IFLAGS} $*.c 
#	Use the following line for VAX machines
#	@${CC} -S ${CFLAGS} ${DFLAGS} ${IFLAGS} $*.c; sed -f ${ASMSED} $*.s | as -o $*.o; rm -f $*.s
