$set 1
1 -F 또는 -f 중 하나만 허용됩니다.\n
2 -F 또는 -f 중 하나만 허용됩니다.\n
3 -P 또는 -p 중 하나만 허용됩니다.\n
4 -P 또는 -p 중 하나만 허용됩니다.\n
5 mark_ev(%d)가 실패했습니다.\n
6 '%c': 사건 인수 누락\n
7 알 수 없는 사건: %s\n
8 mark_ev(%d)가 실패했습니다.\n
9 mark_sc(%d)가 실패했습니다.\n
10 '%c': syscall 인수가 빠졌습니다.\n
11 알 수 없는 syscall: %s\n
12 mark_sc(%d)가 실패했습니다.\n
13 '%c': 알 수 없는 선택 항목입니다.\n
21 슈퍼유저(Super user)가 아닙니다.\n
22 audswitch(AUD_SUSPEND)가 실패했습니다: %s\n
23 mark_ev(%d)가 실패했습니다.\n
24 알 수 없는 인수입니다.: %s\n
25 show_audit()가 실패했습니다.\n
26 set_audit()가 실패했습니다.\n
31 mark_sc(%d)가 실패했습니다.\n
41 audwrite(%s)가 실패했습니다: %s\n
42 getevent()가 실패했습니다: %s\n
43 set_event(%s)가 실패했습니다.\n
44 set_syscall(%d)가 실패했습니다.\n
45 audwrite(%s)가 실패했습니다: %s\n
46 setevent()가 실패했습니다: %s\n
51 audwrite(%s)가 실패했습니다: %s\n
52 getevent()가 실패했습니다: %s\n
53 show_event(%s)가 실패했습니다.\n
61 사용법: %s
