$set 1
2 chmod: %s이(가) 없습니다.\n
3 chmod: 변경할 수 없습니다.
4 chmod: 모드가 잘못되었습니다.\n
5 chmod: -A 선택 항목은 원격 파일:%s에 허용되지 않습니다.\n
6 chmod: %s을(를) 찾을 수 없습니다.\n
7 chmod: %s은(는) 디렉토리가 아닙니다.\n
101 사용법: chmod [-A] [-R] [ugoa]+-=[rwxXstHugo][,...] file ...\n
102 사용법: chmod [-R] [ugoa]+-=[rwxXstHugo][,...] file ...\n
103 사용법: chmod [-A] [-R] [ugoa]+-=[rwxXstugo][,...] file ...\n
104 사용법: chmod [-R] [ugoa]+-=[rwxXstugo][,...] file ...\n
