$set 1
1 사용법:\tcp [-f|-i] [-p] source_file target_file\n\tcp [-f|-i] [-p] source_file ... target_directory\n\tcp [-f|-i] [-p] -R|-r source_directory ... target_directory\n
2 cp: %s을(를) unlink할 수 없습니다: 
3 cp: %s을(를) 사용할 수 없습니다:
4 cp: <%s>은(는) 디렉토리입니다. "-R" 선택 항목이 필요합니다.\n
5 cp: %s/%s: 이름이 너무 깁니다.\n
6 cp: %s와 %s이(가) 동일합니다.\n
7 cp: %s: 디렉토리가 아닙니다.\n
9 cp: %s을(를) 만들 수 없습니다:
10 cp: 열 수 없습니다:
11 cp: %s을(를) 만들 수 없습니다:
12 cp: %s에 대한 복사가 잘못되었습니다:
13 cp: %s을(를) 닫을 수 없습니다:
14 cp: %s에 허용 비트를 설정할 수 없습니다:
15 cp: %s/%s: 이름이 너무 깁니다.\n
16 cp: mkrnod할 수 없습니다.
17 cp: symlink할 수 없습니다.
18 cp: readlink할 수 없습니다.
19 cp: %s에 대한 utime 실패
20 cp: %s에 대한 chown 실패
21 경고: 소켓을 건너 뛰었습니다: %s\n
22 cp: 경고: %s에 cpacl할 수 없습니다.\n
23 cp: 경고: %s에 cpacl할 수 없습니다.\n
24 링크되지 않았습니다.
25 %s을(를) 지우고 다시 쓸까요? 
26 cp: %s: 디렉토리가 아닙니다.\n
27 cp: %s에서 사용 제어 목록(ACL)을 사용할 수 없습니다:
28 cp: %s에 대한 %d 항목의 ACL을 할당할 수 없습니다:
29 cp: %s에서 ACL을 읽을 수 없습니다:
