$set 1
1 crontab 디렉토리에 crontab 파일을 만들 수 없습니다.
2 crontab 파일을 열 수 없습니다.
3 로그인 쉘이  /bin/sh가 아니므로 cron을 사용할 수 없습니다.
4 경고: /bin/sh를 사용하여 명령이 실행될 것입니다.\n
5 사용법: \n\tcrontab [file]\n\tcrontab [-r]\n\tcrontab [-l]
6 정당한 사용자가 아닙니다(/etc/passwd에 항목이 없습니다).
7 cron을 사용하도록 허가되지 않았습니다.
8 예상하지 않은 행의 끝입니다.
9 행에 예상하지 않은 문자가 있습니다.
10 숫자가 범위를 벗어났습니다.
11 %scrontab: 이전 행의 오류; %s\n
12 cron이 수행되고 있는지 시스템 관리자에게 확인하십시오.\n
13 crontab: 메세지 대기행렬을 열 수 없습니다.\n
14 crontab: 메세지를 보낼 수 없습니다.\n
$set 2
1 %d 바이트의 공간을 할당할 수 없습니다.\n
