$set 1
1 grep  [-E|-F] [-cbilnqsvx] [-e expression [-e expression] ... | -f file]\n [expression] [file ...]\n egrep [-cbilnqsvx] [-e expression [-e expression] ... | -f file]\n [expression] [file ...]\n fgrep [-cbilnqsvx] [-e expression [-e expression] ... | -f file]\n [expression] [file ...]
2 %s: %s을(를) 열 수 없습니다.\n
3 사용법:\n %s\n
4 %s: %s을(를) 열 수 없습니다.\n
5 %s: RE 오류 %d:
101 알 수 없는 regexp 오류 코드입니다!!
102 잘못된 대조 요소(collation element)가 참조되었습니다.
103 패턴이 \\으로 끝납니다.
104 패턴에 \\n이 있습니다.
105 \\( \\)가 너무 많거나, ( )가 너무 깊게 내포되어 있습니다.
106 \\digit의 숫자가 잘못되었거나 범위를 벗어났습니다.
107 [ ]의 불균형
108 \\( \\) 또는 ( )의 불균형
109 \\{ \\}의 불균형
110 [ - ] 표현식에서 범위(collation) 끝점이 잘못되었습니다.
111 정규 표현식의 오버플로우입니다.
112 \\{ \\} 구성에서 숫자가 너무 큽니다.
113 \\{ \\} 구성에 잘못된 숫자가 있습니다.
114 \\{ \\} 구성에 2개 이상의 숫자가 있습니다.
115 \\{ \\}에서 첫번째 숫자가 두번째 숫자를 초과합니다.
116 문자 분류가 잘못 명명되었습니다.
117 기억된 검색 문자열이 없습니다.
118 이중 연산자의 위치가 잘못되었습니다.
119 표현식이 비어 있습니다.
