$set 1
1 LC_COLLATE을 설정할 수 없습니다.\n
2 LC_CTYPE을 설정할 수 없습니다.\n
3 stdin을 다시 열 수 없습니다.\n
4 사용법:\tlocaledef [-c] [-f charmap_file] [-i input_file] locale_name\n
5 또는\tlocaledef -d [-o format] locale_name\n
6 또는\tlocaledef -n input_file\n
7 'debug' 파일을 열 수 없습니다.\n
9 입력 파일 %s을(를) 열 수 없습니다.\n
10 'langname'이 지정되지 않았습니다.\n
11 'langid'이 지정되지 않았습니다.\n
12 'langname' 과 'langid'의 지정에 상충되는 것이 있습니다.\n
13 'isfirst' 과 'byte_chars'의 지정에 상충되는 것이 있습니다.\n
14 경고: 순서 지정이 무시됩니다.\n
15 LC_ALL 값이 최대 허용 값을 초과합니다.\n
16 LC_MESSAGES 값이 최대 허용 값을 초과합니다.\n
17 LC_COLLATE 값이 최대 허용 값을 초과합니다.\n
18 LC_CTYPE 값이 최대 허용 값을 초과합니다.\n
19 LC_MONETARY 값이 최대 허용 값을 초과합니다.\n
20 LC_NUMERIC 값이 최대 허용 값을 초과합니다.\n
21 LC_TIME 값이 최대 허용 값을 초과합니다.\n
22 'locale.inf' 파일을 만들 수 없습니다.\n
23 localedef 오류: %d 행에서 키워드가 잘못되었습니다.\n
25 localedef 오류: %d 행에서 문자가 잘못되었습니다.\n
26 localedef 오류: %d 행에서 명령이 잘못되었습니다.\n
27 localedef 오류: %d 행에서 산술식이 잘못되었습니다.\n
28 localedef 오류: %d 행에서 범위가 잘못되었습니다.\n
29 localedef 오류: %d 행에서 langname 길이가 잘못되었습니다.\n
30 localedef 오류: %d 행에 langid이 잘못되었습니다.\n
31 localedef 오류: %d 행의 langname에 언어 이름이 잘못되었습니다.\n
32 localedef 오류: langname %d에서 지역 이름이 잘못되었습니다.\n
33 localedef 오류: %d 행의 langname에 코드세트 이름 길이가 잘못되었습니다.\n
34 localedef 오류: %d 행에서 revision 문자열 길이가 잘못되었습니다.\n
36 localedef 오류: %d 행에서 문자 코드가 잘못되었습니다.\n
37 localedef 오류: %d 행에서 isfirst 문자 코드가 잘못되었습니다.\n
38 localedef 오류: %d 행에서 issecond 문자 코드가 잘못되었습니다.\n
39 localedef 오류: code_scheme 이름 길이가 잘못되었습니다: %d\n
40 localedef 오류: code_cscheme 이름이 잘못되었습니다: %d\n
41 localedef 오류: cswidth 문자열 길이가 잘못되었습니다: %d\n
42 localedef 오류: cswidth 문자열 형식이 잘못되었습니다: %d\n
43 localedef 오류: langinfo 문자열 길이가 잘못되었습니다: %d\n
44 localedef 오류: monetary 문자열 길이가 잘못되었습니다: %d\n
45 localedef 오류: numeric 문자열 길이가 잘못되었습니다: %d\n
46 localedef 오류: modifier 문자열 길이가 잘못되었습니다: %d\n
47 localedef 오류: malloc()되지 않았습니다.\n
48 localedef 오류: 우선순위 대기 행렬이 넘쳤습니다.\n
49 localedef 오류: yes 와 no 문자열의 첫 문자는 같지 않아야 합니다: %d\n
50 localedef 오류: era 문자열 길이가 잘못되었습니다: %d\n
51 localedef 오류: era 문자열 형식이 잘못되었습니다: %d\n
52 localedef 오류: era 문자열이 너무 많이 지정되었습니다: %d\n
53 localedef 오류: 지정된 기호가 없습니다: %d\n
58 localedef 오류: charmap 파일이 없습니다. \n
60 localedef 오류: 기호가 중복되었습니다: %d\n
63 localedef 오류: 행 %d에서 COLL_WEIGHTS_MAX보다 많이 지정되었습니다.\n
68 localedef 경고: 지정된 기호가 없습니다: %d\n
72 localedef 경고: 키워드가 지원되지 않습니다: %d\n
73 localedef 경고: ctype 초기화가 잘못되었습니다 - 수정 조치가 취해집니다. \n
74 'langname' 와 'langid' 사이의 지정 모순
75 WARNING: 사용자가 정의한 언어는 901에서 999 사이의 langid를 가져야 합니다.\n
76 사용자가 정의한 언어는 901에서 999 사이의 langid를 가져야 합니다.\n
77 'langname' 와 'langid' 사이의 지정 모순
78 파일 읽기 오류 : 
79 파일 lseek 오류 : 
80 임시 파일 %s을(를) 열 수 없습니다.\n
81 charmap 파일을 해석 중 오류\n
82 locale 오류: LC_COLLATE에 잘못된 행 : %d\n
