$set 1
1 Usage: passwd [ name ]\n
2 Changing password for %s\n
3 Permission denied.\n
4 Old password:
5 Sorry.\n
6 Sorry: < %ld weeks since the last change\n
7 You may not change this password.\n
8 Too many failures - try later.\n
9 New password:
10 Password is too short - must be at least 6 characters\n
11 Password cannot be circular shift of logonid\n
12 Password must contain at least two alphabetic characters and\n
13 at least one numeric or special character.\n
14 Passwords must differ by at least 3 positions\n
15 Re-enter new password:
16 Too many tries; try again later.\n
17 They don't match; try again.\n
18 Temporary file busy; try again later.\n
19 Cannot create temporary file\n
20 Permission denied.\n
21 cannot unlink %s\n
22 cannot link %s to %s\n
23 cannot unlink %s\n
24 cannot link %s to %s\n
25 cannot recover %s\n
26 cannot unlink %s\n
27 putpwent() failed\n
28 cannot chown %s\n
29 cannot chmod %s\n
30 Invalid login name.\n
31 Password entry is too long\n
