$set 1
1 Tar: 임시 파일 (%s)을(를) 만들 수 없습니다.\n
2 블럭 크기가 잘못되었습니다(최대값 %d).\n
3 tar: %c: 알 수 없는 선택 항목입니다.\n
4 tar: 블럭 크기 %d 가 너무 커서, 공간을 얻을 수 없습니다.\n
5 표준 출력의 보관의 작성만이 가능합니다.\n
6 tar: %s을(를) 열 수 없습니다.\n
7 tar: 사용법  tar [-]{txruc}[ONvVwAfblHhm{op}][0-7[lmh]] [tapefile] [blocksize] file1 file2...\n
8 tar: 사용법  tar [-]{txruc}[ONvVwfblHhm{op}][0-7[lmh]] [tapefile] [blocksize] file1 file2...\n
9 tar: 사용법  tar [-]{txruc}[ONvVwAfblhm{op}][0-7[lmh]] [tapefile] [blocksize] file1 file2...\n
10 tar: 사용법\ttar [-]{txruc}[ONvVwfblhm{op}][0-7[lmh]] [tapefile] [blocksize] file1 file2...\n
11 tar: 사용법\ttar [-]{txruc}[ONvVwAfblm{op}][0-7[lmh]] [tapefile] [blocksize] file1 file2...\n
12 tar: 사용법\ttar [-]{txruc}[ONvVwfblm{op}][0-7[lmh]] [tapefile] [blocksize] file1 file2...\n
13 파일이 없는 아카이브를 만들려 하였습니다.\t아무것도 덤프되지 않았습니다.\n
14 %s와의 연결이 누락되었습니다.\n
15 디렉토리 검사 합계 오류입니다.\n
16 tar: %s을(를) 찾을 수 없습니다.  덤프되지 않았습니다.\n
17 <%s> 의 acl 입력 항목이 덤프되지 않았습니다.\n
18 tar: %s: 디렉토리 읽기 오류입니다.\n
19 tar: %s: 기호연결(symbolic link)이 너무 깁니다.\n
20 tar: 기호연결(symbolic link)을 읽을 수 없습니다.
21 %1$s 는 %2$s에 기호로 연결 됩니다.\n
22 a %s 는 블럭이 없습니다.\n
23 tar: %s: 파일을 열 수 없습니다.\n
24 a %1$s 는  %2$s에 연결됩니다.\n
25 메모리가 부족합니다.  연결에 대한 정보를 상실하였습니다.\n
26 a %1$s %2$ld 블럭\n
27 %s: 파일 크기 변경\n
28 tar: %s은(는) 파일이 아닙니다. 덤프되지 않습니다.\n
29 tar: %s: 기호연결(symbolic link)이 실패하였습니다:
30 x %1$s은(는) %2$s에 기호로 연결합니다.\n
31 %s: 연결할 수 없습니다.\n
32 %1$s이(가) %2$s에 연결되었습니다.\n
33 tar: %s은(는) 문자 장치를 만들 수 없었습니다.\n
34 x %s, 0 바이트, 0 블럭, 문자 장치\n
35 tar: %s은(는) 블럭 장치를 만들 수 없었습니다.\n
36 x %s, 0 바이트, 0 블럭, 문자 장치\n
37 tar: %s은(는) fifo를 만들 수 없습니다.\n
38 x %s, 0 바이트, 0 블럭, fifo\n
39 tar: %s은(는) 정규 파일로 만듭니다.\n
40 tar: %s - 만들 수 없습니다.\n
41 x %1$s, %2$ld 바이트, %3$ld 테이프 블럭\n
42 tar: %s: HELP - 쓰기 오류의 추출\n
43 tar: chmod가 실패하였습니다.
44 tar: chown이 실패하였습니다.
45  %s에 연결되었습니다.
46  %s의 기호 연결.
47 %b %2d일 %H:%M %Y
48 tar: uid %d에 대한 uname을 얻지 못했습니다.\n
49 tar: gid %d에 대한 gname을 얻지 못했습니다.\n
51 tar: pwd가 실패하였습니다.
52 tar: pwd의 깊이 한계를 초과하였습니다!\n
53 Tar: 테이프 읽기의 오류입니다.\n
54 Tar: 테이프 블럭 크기의 오류입니다.\n
55 Tar: 블럭 크기 = 0; 파이프가 고장입니까?\n
56 Tar: 블럭 크기 = %d\n
57 Tar: 오류! 블럭 크기가 변경 되었습니다.\n
58 Tar: 테이프 읽기의 오류입니다.\n
59 tar: %s: 경로가 너무 깁니다.\n
60 tar: %s: 접두어가 너무 깁니다.\n
61 tar: %s: 파일 이름이 너무 깁니다.\n
62 %s: 파일 이름이 너무 깁니다.\n
63 Tar: 테이프 오류입니다(%d).\n
64 Tar: 신규 볼륨상의 오류입니다.\n
65 추가 매체의 요구를 위하여 필요한 /dev/tty를 열 수 없습니다.\n
66 Tar: 테이프의 끝\n
67 Tar: 계속하려면, 준비가 되었을 때 장치/파일 이름을 입력하거나, 끝내려면 공값 문자열을 입력하십시오.\n
68 다음 장치 파일 이름에 공값을 입력하였습니다.\n
69 Tar: %s을(를) 열 수 없었습니다.\n
70 계속하기 위하여 파일 %s을(를) 열었습니다.\n
71 tar: %s이(가) 디렉토리를 만들 수 없었습니다.\n
72 tar: %s: 이름에 대한 연결(link)이 너무 깁니다.\n
73 tar: %s:파일을 사용할 수 없습니다.\n
74 tar: 메모리가 부족합니다. 기호 연결 루프를 찾을 수 없습니다.\n
75 tar: 기호 연결 루프를 찾았습니다. tar가 종료됩니다.\n
76 tar: 디렉토리를 '%s'로 변경할 수 없습니다.\n
77 tar: 경로 '%s'를 건너 뛰었습니다.\n
78 tar: QIC 장치 %s에 대한 선택 항목이 지원되지 않습니다.\n
79 tar: %s을(를) 닫을 수 없습니다.\n
80 tar: NFS를 통해서 읽거나 쓸 수 없습니다.\n
