$set 1
3 파일 : %s 처리가 끝났습니다.\n
5 gtwvec: dir %s\n
6         돌려주는 값 - %d\n
7 삽입(%s)  
8 %s 삽입  
9 %d 에\n
10 내부 호출자 유형 %s\n
11 %s 의 mlock이 실패하였습니다.\n
12 %s 의 mlock이 실행되었습니다.\n
13 장치 열기는 시간 종료되었습니다.\n
16 장치 (%d)를 열지 못했습니다, 오류 번호 = %d\n
19 %s이(가) 다이얼 호출자 파일에 없습니다.\n
22 gdial(%s)이 호출되었습니다.\n
23 dkcall(%s)\n
27 tcpdial host %s, 
28 port %d\n
29 소켓이 없습니다 : %s\n
31 소켓이 없습니다, 오류 번호 %d\n
34 tcpopen은 시간 종료되었습니다.\n
37 family: %d\n
38 port: %d\n
39 addr: %08x\n
40 연결이 실패하였습니다. : %s\n
42 연결이 실패하였습니다., 오류 번호 %d\n
45 unetdial host %s, 
46 port %d\n
47 tcpopen이 실패하였습니다., 오류 번호 %d\n
48 %s을(를) 열지 못하였습니다.\n
50 COM1 return = %d\n
52 sytek 열기는 시간 종료되었습니다.\n
53 OPEN 2 FAILED %s\n
54 %s의 mlock이 실패하였습니다.\n
55 Port %s 사용, 
56 acu - %s, 
57 전화번호 %s\n
58 모뎀 시도 - %s, 
59 acu - %s, 
60 %s 호출:
61 실행되었습니다.\n
62 실패하였습니다.\n
63 %s을(를) 열 수 없습니다.\n
64 %s은(는) 열려 있습니다.\n
65 모뎀 열기는 시간 종료되었습니다.\n
66 다이얼 호출이 실패하였습니다. 나머지 처리는 정지됩니다.\n
68 ACU 기록 오류%d\n
69 %s 프로그램을 사용한 다이얼 호출\n
72 dcf 는 %d 입니다.\n
73 %o 상태 분기\n
74 DN 은 %s을(를) 기록합니다.\n
75 시간 종료
76 %s을(를) 열 수 없습니다.\n
77 %s은(는) 열려 있습니다.\n
78 %s을(를) 열 수 없습니다.\n
79 dcf 는 %d 입니다.\n
80 ACU 기록 오류 %d\n
81 ACU 기록 ok%s\n
82 %s 행을 엽니다.\n
83 실패하였습니다.
84 chdir(%s)\n
85 [-xNUM] [-r[0|1]] -sSYSTEM
88 %s은(는) 시스템 파일에 없습니다.\n
89 \t사용법: %s %s\n
90 -s가 지정되지 않았습니다.\n
91 지정된 이 시스템의 이름: -sMyname: %s, 
92 cico.c: Myname - %s\n
93 cico.c: Loginuser - %s\n
95 sys-%s\n
98 호출 검사(callcheck)에서 복귀:%s
109 지금 %s와(과) 통화하고 있습니다.\n
112 %s - 실패하였습니다.\n
113 %s - 실패하였습니다.\n
114 로그인(login) 성공 : System=%s\n
115 msg-%s\n
117 핸드쉐이크(handshake) 실패 : %s\n
118  Rmtname %s, 
119 Role %s,  
120 MASTER
121 SLAVE
122 Ifn - %d, 
123 loginuser - %s\n
126 %s - 시간 종료\n
127 전송 시작(startup)
130 %s\n
133 cntrl - %d\n
138 ret restline - %d\n
139 마침 코드 %d\n
140 대화가 끝났습니다: %s 상태\n\n
141 실패하였습니다.
142 실행되었습니다.
143 TM_cnt: %d\n
145 사용법: uuname [-l]\n
146 %s을(를) 열 수 없습니다.\n
293 *** TOP ***  -  role=%d, 
295 Wfile - %s,
296 Jobid = %s\n
301 요청: %s\n
305 실패하였습니다. : 파일 사용이 허용되지 않습니다.\n
311 실패하였습니다. : %s을(를) 읽을수 없습니다.\n
314 요청: %s\n
318 실패하였습니다. : 파일 사용이 허용되지 않습니다. -- 파일 : %s\n
322 실패하였습니다. : 사용 공간이 없습니다!\n
323 wrktype - %c\n 
324  PROCESS: msg - %s\n
326 RQSTCMPT:
329 HUP:
331 SLAVE-switchRole (%s)\n
332 참
333 거짓
335 SNDFILE:
344 msg - %s\n
345 요청된 원격지: %s\n
346 SLAVE - filename: %s\n
349 실패하였습니다. : 사용이 거부되었습니다.\n
351 chkpth 정상, Rmtname - %s\n
355 실패하였습니다. : 임시 파일을 만들수 없습니다.\n
361 ->PUBDIR %d\n
363 RCVFILE:
375 요청된 원격지: %s\n
376 msg - %s\n
377 W_FILE1 - %s\n
382 실패하였습니다. : 파일 사용이 허용되지 않습니다.\n
383 loginuser-%s을(를) 위한 승인 요청\n
386 실패하였습니다. : 파일 사용이 허용되지 않습니다.\n
387 chkpth ok Loginuser - %s\n
391 실패하였습니다. : %s을(를) 읽을수 없습니다.\n
393 rmesg - '%c' 
394 %s을(를) 얻습니다.\n
395 실패
398 %s을(를) 얻습니다.\n
401 %s을(를) 얻습니다.\n
402 wmesg '%c'
403 %s\n
404 mailopt %d, 
405 statfopt %d\n
413 STMES %s\n
417 Proto가 %c(으)로 시작되었습니다.\n
418 Proto가 %c(으)로 시작 되지 않았습니다.\n
419 conn(%s)\n
420 getto ret %d\n
421 호출자(%d)을(를) 닫습니다.\n
422 delock(%s)\n
423 호출이 실패하였습니다: %s\n
424 장치 유형 %s을(를) 필요로 합니다.\n
425 요청된 장치 유형을 찾을수 없습니다.\n
427 지금은 호출할 수 없습니다 : %s\n
428 Proto 문자열= %s\n
430 expect: (
431 그것을 얻으십시오.\n
432 회선 이상, 오류 번호 - %d\n
435 이미 충분합니다.\n
436 그것을 얻으십시오.\n
437 시간 종료\n
438 BREAK\n
439 EOT\n
440 sendthem (
441 DELAY\n
442 <NO CR>
443 <NO CR - MIDDLE IGNORED>\n
444 PAUSE\n
445 반향 점검 설정\n
446 반향 점검 취소\n
447 BREAK\n
448 ^M
449 )\n
458 %s이(가) 가득 참\n
459 dturnon: ret=%d, 
460 Ofn=%d, 
461 오류 번호=%d\n
462 ewrmsg에 기록이 되지 않습니다.\n
463 erdmsg을(를) 읽지 못합니다.\n
464 ewrdata가 실행되지 않았습니다.\n
465 ewrmsg가 %d을(를) 기록합니다.\n
466 ewrmsg가 %d을(를) 돌려줍니다\n
468 erdblk 메세지 길이는 %d입니다.\n
469 erdblk이 %d을(를) 돌려줍니다.\n
470 erdblk이 실행되지 않았습니다.\n
471 erdblk이 너무 많이 읽었습니다.\n
472 <- %ld / %ld.%.3d 초
473 erdblk 시간 종료\n
474 %d 요청
475 읽지 못했습니다.\n
476 got %d\n
477 mkdir - %s\n
478 모 디렉토리 %s에서 STAT할수 없습니다.\n
479 오류 번호 %d\n
480 모 디렉토리 %s에서 chmod할수 없습니다.\n
481 오류 번호=%d\n
483 모 디렉토리 %s에서 chmod할수 없습니다.\n
487 파일 이름(%s)이(가) 잘못되어 있습니다.\n
489 frdmsg 입력:
490 checksum: %04x\n
491 ack - '%c'\n
494 RETRY:\n
495 fwrdata ret: %d\n
498 send ack: 'R'\n
499 RETRY:\n
500 send ack: 'Q'\n
501 send ack: 'G'\n
502 frddata ret: %d\n
503 \nchecksum: %04x\n
504 Checksum이 잘못되었습니다.\n
505 데이타가 파손되었습니다.\n
506 gename(%c, 
507 %s, 
508 %c)\n
509 null sys -> %s\n
510 file - %s\n
512 %s seq 
513 now %x\n
514 : 잘못된 선택 항목 -- 
515 : 선택 항목에 인수가 필요로 합니다 --
516 : 선택 항목에 인수가 필요로 합니다 --
517 stat %s\n
519 %s을(를) 잠글수 없습니다.\n
520 %s을(를) commit합니다.
521 %s에게\n
522 imsg %s>
524 fixline(%d, 
525 %d)\n
527 fixline - direct\n
529 setline - %c\n
530 sytfixline - speed= %d\n
534 fixline(%d, 
535 %d)\n
536 사용법 : %s -f script [-d] [-v]\n
537 알수 없는 %s
538 구문 오류
539 구문 : 숫자열이 요구됩니다.
540 구문 : 숫자열이 요구됩니다.
546 레이블이 빠졌습니다.
547 오류 또는 불가능한 goto
548 레이블 %s을(를) 찾을수 없습니다.
550 %s을(를) 찾을수 없습니다.
551 숫자가 요구됩니다.
552 문자열이 요구됩니다.
554 인수가 너무 많습니다.
555 플래그가 요구됩니다.
556 플래그 "%s"은(는) 인식되지 않습니다.
557 logFind 가 호출되었습니다 (name: %s, 
558 rmtname: %s)\n
559 기계/로그인이 일치되지 않습니다.
560 _Request (%s), 
561 참
562 거짓
563 _Switch (%s), 
564 참
565 거짓
566 _CallBack (%s), 
567 참
568 거짓
569 _MyName (%s), 
570 mchFind가 (%s)에서 호출됩니다.\n
584 _Commands %s\n
585 malloc() 오류\n
586 목록 (%s) 
587 num = %d\n
588 %s을(를) 열 수 없습니다.\n
589 이름 (%s)이(가) 없습니다; 거짓(fail)으로 돌려줍니다.\n
590 %s을(를) 열 수 없습니다.\n
591 validateFind (%s) 가 실행되지 않았습니다.\n
593 PERMISSIONS에 선택 항목(%s)이 잘못되었습니다.\n
594 \n*****************************\n
595 **PERMISSIONS 파일에 잘못된 선택 항목: %s\n
596 *****************************\n
597 cmdOK(%s, )\n
598 bname=%s\n
600 cntl이 아닙니다.\n
601 alloc의 변경 사항을 구현하지 않습니다.\n
602 pkcntl: RR/RJ: Connodata=%d\n
603 srj가 이행되지 않습니다.\n
604 r short %d가 %d을(를) 원합니다.\n
605 rcount = %d\n
606 xcount = %d\n
607 tries = %d\n
608 pkgetpack: Connodata=%d\n
609 rec h->cntl %o\n
610 헤더 %o 불량,
611 h->ccntl %o\n
612 state -
613 헤더 %o 불량,
614 bp NULL %s\n
615 send %o\n
618 alarm %d\n
619 KILL %s\n
620 %s을(를) unlink할 수 없습니다.\n
621 %s을(를) 잠글 수 없습니다.\n
622 %s을(를) 읽기 전용으로 열 수 없습니다.\n
623 작업 %s이(가) 삭제됩니다.\n
624 작업 %s을(를) 찾을 수 없습니다.\n
625 fp: %o\n
626 작업 %s이(가) 이미 끝났습니다.\n
627 허용되지 않습니다.\n
629 shio - %s\n
630 status %d\n
634 retry 할 수 있는 시간(%ld)에 도달하지 않았습니다.\n
636 ub_sst를 입력하십시오, 상태는 %d 입니다.\n
637 Rmtname: %s\n
638 %s ulockf가 실패하였습니다.\n
639 %s fopen이 실패하였습니다.\n
640 ub_sst에 있는 이름=Rmtname: %s\n
641 onelock()에서 ulockf가 실패하였습니다.\n
642 ulockf 파일 %s\n
643 Lock File--읽을 수 없습니다(오류 번호 %d) --지우십시오!\n
644 Lock File--형식(format)이 틀립니다.--지우십시오!\n
645 Lock File--프로세스가 활동 중입니다.--지워지지 않았습니다.\n
646 pid (%d)을(를) kill하고,, 
647 %d(으)로 돌려줍니다.
648 --잠금(lock)파일(%s)이(가) 성공적으로 지워졌습니다.\n
649 unlink()에서 ulockf가 실패하였습니다.\n\n
650 ulockf 파일 %s\n
651 Lock File--읽을 수 없습니다.(오류 번호 %d) -- 지우십시오!\n
652 --잠금(lock)파일(%s)이(가) 성공적으로 지워졌습니다.\n
653 unlink()에서 ulockf가 실패하였습니다.\n\n
657 link(%s, 
658 %s)\n
660 [-v] [-xNUM]
661 \t사용법: %s %s\n
662 \t사용법: %s %s\n
663 *** uucheck:  요청받은 파일과 디렉토리들을 점검합니다.\n
664 *** uucheck:  디렉토리 점검이 끝났습니다.\n
665 *** uucheck:  %s 파일 점검\n
666 *** uucheck:  %s 점검이 끝났습니다.\n\n
667 ** %s \n\n
668 MACHINE PHASE (호출하거나 uux요청을 수행할 때)
669 LOGNAME PHASE (호출받을 때)
670 %s 파일을 열 수 없습니다.\n
671 시스템이 다음과 같은 시스템으로  로그하면: 
672 \t그 시스템 호출을 취소할 수 있습니다.\n\n
673 시스템을 호출하면 :
674 \t%s은(는) 시스템의 파일을 요청을 허용합니다.\n
675 합니다
676 하지 못합니다.
677 \t%s은(는) 이번 호출에서 대기된 파일을 보낼 수 있습니다.\n
678 WILL
679 WILL NOT
680 \t다음으로 파일을 보낼 수 있습니다:\n
681 \t    %s (기본)\n
682 \t    %s\n
683 \t예외\n
684 \t    %s\n
685 \t파일을 다음에서 요청할 수 있습니다:\n
686 \t    %s (기본)\n
687 \t    %s\n
688 \t예외\n
689 \t    %s\n
690 대화용 Myname은 %s에 있습니다.\n
691 대화용 PUBDIR은 %s에 있습니다.\n
692 Mashine(s) :
693 \n다음의 명령을 수행할 수 있습니다.\n
694 permission.c에 소프트웨어 오류가 있습니다.\n
695 명령 (%s), 전체 이름 (%s)\n
696 알수없는 플래그 %s\n
697 %s 디렉토리를 읽지 못합니다.\n
698 DEBUG# %s\n
699 START
700 %s 디렉토리를 chdir할 수 없습니다.\n
701 %s에서 stat가 실패하였습니다.\n
702 파일 %s을(를) unlink하십시오.\n
703 Prefix: %s\n
704 chkpre가 실패하였습니다. - 파일 : %s\n
709 STM %d\n
710 [-oDAYS] [-mSTRING] [-Cdays] [-Ddays] [-Wdays] [-Xdays] [-xLEVEL] [-sSYSTEM]
711 \t사용법: %s %s\n
712  선택 항목: CDWXo 는 0보다 커야 합니다.\n
713 \t사용법: %s %s\n
714 프로그램 (%s): 시작되었습니다.\n
715 Myname (%s), 
716 _ShortLocal (%s)\n
717 Days C.(%d), 
718 D.(%d), 
719 W.(%d), 
720 X.(%d), 
721 기타 (%d)\n
722 (%s) CHDIR할 수 없습니다: 오류 번호 (%d)\n
723 (%s) OPEN할 수 없습니다: 오류 번호 (%d)\n
724 디렉토리: %s\n
725 파일: %s\n
726 xprocess(%s), 
727 unlink(%s)\n
729 \n\t%s!%s -> %s!%s   (Date %2.2d/%2.2d)\n\n수행될 수 없습니다.
730 \n\t%s!%s  (Date %2.2d/%2.2d)\n
731 \n\t%s!%s -> %s!%s   (Date %2.2d/%2.2d)\n
732 cprocess(%s)\n
733 파일 (%s)을(를) 열 수 없습니다.\n
734 오류 번호=%d -- 건너 뛰십시오!\n
735 dummy C. -- unlink(%s)\n
740 text (%s)\n
741 wprocess(%s)\n
742 파일 (%s)을(를) 열 수 없습니다.\n
743 오류 번호=%d -- 건너 뛰십시오!\n
744 dummy C. -- skip(%s)\n
745 짧은 행 (%s): 
746 D.불량 -- skip(%s)\n
748 %s을(를) 읽을 수 없습니다.\n
749 retaddr (%s)\n
751 text (%s)\n
752 oprocess(%s), 
753 unlink(%s)\n
755 dDprocess(%s), 
756 unlink(%s)\n
758 dXprocess(%s), 
759   unlink(%s)\n
761 dMprocess(%s)\n
762   로칼 파일 %s: 
763   원격 파일 %s: 
764 toUser %s, 
765 toSystem %s  
766 Mail 송신, unlink(%s)\n
768 dNprocess(%s)\n
769   로칼 파일 %s: 
770 unlink(%s)\n
772   원격 파일 %s: 
773 exec rnews(%s), 
774 unlink(%s)\n
776 파일 (%s)을(를) 열 수 없습니다.\n
777 오류 번호=%d -- 건너 뛰십시오!\n
778 buf: %s\n
782 Mail %s to 
785 sendMail: %s\n
789 Rnews %s\n
791 toWho(%s)\n
792 buf: %s\n
794 알 수 없는 플래그 %s\n
796 시작
797 작업 디렉토리가 아닙니다 -%s -도움을 받으십시오.\n
798 UID %d, 
799 User %s\n
800 사용법 uucp from ... to\n
801 잘못된 시스템: %s\n
802 sys2: %s, 
803 fwd2: %s, 
804 file2: %s\n
805 잘못된 시스템: %s\n
806 잘못 사용된 구문 %s\n
807 sys1 - %s, 
808 file1 - %s, 
809 Rmtname - %s\n
812 uucp가 완전히 실패하였습니다 : 코드 %d\n
813 uucp가 부분적으로 실패하였습니다 : %d 오류
814  \n
815 s \n
816 %d에서 모든 작업이 수행됩니다.\n
817 %s 상태 파일을 얻을 수 없습니다.\n복사되지 않았습니다.\n
818 %s %s - 같은 파일; 복사할 수 없습니다.\n
819 허용되지 않습니다.\n
820 디렉토리 이름 -%s가 잘못되었습니다.\n
821 uucp는 (%s)을(를) 모드(%o)로 읽을 수 없습니다.\n
822 cp 명령어를 사용하십시오.\n
823 (%s) 파일을 모드(%o)로 기록(write)할 수 없습니다.\n
824 로칼 복사:  uidxcp(%s, 
825 %s\n
826 (%s)파일을 복사할 수 없습니다. 오류 번호 %d\n
827 받는 파일 - %d\n
831 보내는 파일 - %d\n
832 파일 %s의 상태(status)를 얻을 수 없습니다.\n
833 디렉토리 이름이 틀립니다 - %s\n
837 cmd: %s\n
838 getty: 시간 종료 인수가 잘못되었습니다. "%s"\n
839 점검 모드 사용법: getty -c gettydefs-like-file\n
840 %s을(를) 열 수 없습니다.\n
841 getty: 지정된 단말기 행이 없습니다.\n
842 getty: %s을(를) "%s"에서 찾을 수 없습니다.\n
843 getty: %s을(를) 열 수 없습니다. 오류 번호 %d\n
844 %.9s\r\n
845 getty: %s 입력에서 다음 속도 지정이 잘못되었습니다.\n
846 getty: 다시 %s을(를)찾을 수 없습니다.\n
847 \r\n
848 getty: "%s"을(를) 열 수 없습니다.\n
849 입력이 너무 깁니다.\n
850 \n**** 다음 입력 ****\n%s\n
851 id: %s\n
852 초기 플래그:\niflag- %o oflag- %o cflag- %o lflag- %o\n
853 최종 플래그:\niflag- %o oflag- %o cflag- %o lflag- %o\n
854 메세지: %s\n
855 다음 id: %s\n
856 "%s"항목에서 파싱 실패\n%s<--여기에 오류가 있습니다.\n
857 정의 안됨: %s\n
861 사용법: %s    [-m] [directories...]\n
862         %s -s [-m] [directories...]\n
863         %s -k [-m] [directories...]\n
864 디렉토리를 stat할 수 없습니다.
865 디렉토리를 opendir 할 수 없습니다.
866 디렉토리가 너무 큽니다.
867 chdir 할 수 없습니다.
869 total
870 Orphans:
871 Others:
872 \n
873 Transactions:
874 \n%*s
875 %*s%-*s %s
876 \n
877 %*s\n
880 %s: 잘못된 선택 항목 -- %c\n
881 %s: 선택 항목에 인수가 필요합니다 -- %c\n
882 [-xNUM] [-uNUM]
883 \t사용법: %s %s\n
884 \t사용법: %s %s\n
885 Progname (%s): 시작됨\n
886 limitfile이 없습니다 - %s\n
887 Uusched는 %d을(를) 제한합니다. -- 
888 %d을(를) 찾았습니다 -- 종결 처리합니다.\n
889 계속합니다\n
890 machine: %s, 
891 ccount: %d\n
892 Execute num=%d \n
893 num=%d, 
894 snumber=%d, 
895 Rmtname=%s\n
896 exuucico(%s)을(를) 호출합니다.\n
897 시스템 %s이(가) 잠겨져 있거나 적당하지 못한 상태입니다--건너 뛰십시오.\n
898 machine(%s) 가 호출되었습니다.\n
900 ret=%d, 
901 errno=%d\n
902 %-*.*s 
903 %3.d Cmd%s 
904    ---   
905 %3.d Data 
906    ---   
907 %3.d Xqt%s 
908    ---   
909 LOCKED   
910 TALKING
911 retry할 수 있습니다.
912 retry 시간 %ld %s 초 
913 retry 시간 %ld %s 분 
914 Count: %d\n
915 이상한 파일(%s)이 %s에 있읍니다.\n
916    \t(pid ??)
917    \t(pid ??)
918    \t(pid %d)
919 [-a] [-q] or [-m] or [-kJOB] or [-rJOB] or [-p]
920 [-sSYSTEM] [-uUSER]
921 \t사용법: %s %s\n
922 or\n\t사용법: %s %s\n
923 \t사용법: %s %s\n
924 or\n\t사용법: %s %s\n
925 Progname (%s): 시작됨\n
926 User=%s, 
927 Loginuser=%s, 
928 Jobid=%s, 
929 Rmtname=%s\n
930 \t사용법: %s %s\n
931 또는 \n\t사용법: %s %s\n
932 작업 %s을(를) 찾을 수 없습니다; %s가 아닙니다.\n
933 정지되었습니다(killed).
934 회복되었습니다(rejuvenated).
935 uprocessC(%s, 
936 %s);\n
937 파일(%s)을(를) stat할 수 없습니다,
938  오류 번호  (%d) -- 건너 뛰십시오!\n
939 파일 (%s)을(를) 열 수 없습니다,
940  오류 번호  (%d) -- 건너 뛰십시오!\n
941 %-12s  %2.2d/%2.2d-%2.2d:%2.2d:%2.2d  (POLL)\n
942 짧은 행 (%s)\n
943 type (%s), 
944 file1 (%s)
945 file2 (%s)
946 file3 (%s)
947 user (%s)
948 %-12s  %2.2d/%2.2d-%2.2d:%2.2d  
949 %-12s  %2.2d/%2.2d-%2.2d:%2.2d  
950 %s을(를) 읽을 수 없습니다.
951  오류 번호  (%d) -- 건너 뛰십시오!\n
952 ????\n
953 kprocessC(%s, 
954 %s);\n
955 stat:%s 할 수 없습니다, 오류 번호(%d)-- 그것을 %s할 수 없습니다!\n
956 정지합니다.
957 회복합니다.
958 read:%s 할 수 없습니다, 오류 번호(%d)-- 그것을 %s할 수 없습니다!\n
959 정지합니다.
960 회복합니다.
961 잘못된 형식:%s, 오류 번호 (%d)--그것을 %s할 수 없습니다!\n
962 정지합니다.
963 회복합니다.
964 type (%s), 
965 file1 (%s)
966 file2 (%s)
967 file3 (%s)
968 user (%s)
969 소유자나 root가 아닙니다 - %s을(를) 작업 %s에서 할 수 없습니다.\n
970 정지합니다.
971 회복합니다.
972 %s을(를) 지우십시오.\n
973 오류: %s 할 수 없습니다, 파일(%s), 오류 번호(%d)\n
974 정지합니다.
975 회복합니다.
976 %s을(를) 지우십시오.\n
977 오류: %s 할 수 없습니다, 파일(%s), 오류 번호(%d)\n
978 정지합니다.
979 회복합니다.
980 작업: %s은(는) 성공적으로 %s 되었습니다.\n
981 정지되었습니다.
982 회복되었습니다.
983 machine(%s), 
984 m-M=%d\n
987 경고: 표 오버플로우 -- 출력이 끝나지 않았습니다.\n
988 %3dC
989 %4dX
990 %2.2d/%2.2d-%2.2d:%2.2d 
991 잠겨 있습니다. 
992 Retry: %d:%2.2d
993  Count: %d
994 lckpid() - entered\n
995 lockdir (%s)\n
996 f (%s)\n
997 ????\n
1000 uusub: 열 수 없습니다.
1001 사용법:uusub -a* -d* -c* -u* -r -l-f\n
1002 Flush 파일 %s\n
1003 부 네트워크(subnetwork)에서 %s 시스템을 제거합니다.\n
1004 부 네트워크(subnetwork)에 %s 시스템을 추가합니다.\n
1005 시스템 %s이(가) 추가되었습니다.\n
1007 sysname\tsfile\tsbyte\trfile\trbyte\n
1008 %s\t%d\t%ld\t%d\t%ld\n
1009 sysname\t#call\t#ok\tlatest-oktime\t#noacu\t#login
1010 \t#nack\t#other\n
1011 %s\t%d\t%d
1012 \t(%d/%d-%d:%2.2d)\t
1013 %d\t%d\t%d\t%d\n
1014 편집(edit) 하십시오, 플래그: %d\n
1016 %s은(는) 유지되어 있습니다.\n
1018 Uusub는 이 시스템에는 구현되지 않았습니다.\n
1019  파일 %s을(를) 나누십시오.\n
1020  l.sys: %s\n
1022  Rmt: %s 
1023  s_r: %s
1024  bytes: %ld 
1025  oldtick: %ld\n
1026  %s은(는) 시간 안에 있습니다.\n
1027 %s 이(가) 기록되었습니다.\n
1033 [-aNAME] [-b] [-c] [-C] [-j] [-gGRADE] [-n] [-p] [-r] [-sFILE] [-xNUM] [-z] command-string
1034 \t사용법: %s %s\n
1036 시작
1037 arg - %s:
1038 arg - %s\n
1039 스풀 디렉토리가 없습니다 -%s - 도움을 받으십시오.\n
1040 xsys %s\n
1041 잘못된 시스템 이름: %s\n
1042 User %s\n
1043 cfile = %s\n
1044 rxfile = %s\n
1050 prm - %s\n
1051 syspart -> %s, 
1052 rest -> %s, 
1053 ret -> %d\n
1054 syspart -> %s\n
1055 잘못된 시스템 이름: %s\n
1056 rest %s\n
1057 상태 파일 %s을(를) 얻을 수 없습니다.\n
1058 %s은(는) 허용되지 않습니다.\n
1059 %s을(를) 복사할 수 없습니다.\n
1061 uux 실패. 코드 %d\n
1062 마침 코드 %d\n
1064 [-xDEGUG] [-sSYSTEM]
1066 \t사용법: %s %s\n
1067 \t사용법: %s %s\n
1068 \n\n** 시작 **\n
1070 limitfile이 없습니다 - %s\n
1071 Uuxqt는 %d을(를) 제한합니다--
1072 %d을(를) 찾았습니다 --
1073 마침\n
1074 계속\n
1075 User - %s\n
1076 process %s\n
1080 %s 감춤\n
1081 xsort:  처음은 %s 였습니다.\n
1082 xsort:  처음은 %s입니다.\n
1083 xget: %s로 돌려줍니다.\n
1084 gt_Xfile 은 %s을(를) 얻습니다.\n
1085 rm_Xfiles: %s 파일을 읽을 수 없습니다.\n
1086 mv_Xfiles: %s 파일을 읽을 수 없습니다.\n
1088 unmv_Xfiles: %s 파일을 읽을 수 없습니다.\n
1090 prm='%s'\n
1091 fullname: %s\n
1093 retosndr %s, 
1095 \n\t===== 오류는 =====\n
1096 \n\t===== 시도되었습니다. =====\n
1097 _Xfile - %s\n
1098 badfile - in: %s\n
1099 badfile - out: %s\n
1100 fin - %s, 
1101 fout - %s, 
1102 sysout - %s, 
1103 user - %s\n
1104 incmd - %s\n
1110 잘못된 명령 %s\n
1112 cmd %s\n
1113 full cmd: %s\n
