default:
	cp install.sh install
	mkdir -p ../../../Filesets.sl/SYS-ADMIN/etc
	! cp install ../../../Filesets.sl/SYS-ADMIN/etc/install
	! chmog 555 bin bin ../../../Filesets.sl/SYS-ADMIN/etc/install
	! chmog 555 bin bin ../../../Filesets.sl/SYS-ADMIN/etc
	! chmog 555 bin bin ../../../Filesets.sl/SYS-ADMIN
	! chmog 555 bin bin ../../../Filesets.sl

install:
	:
