default:
	cp mkdev.sh mkdev

install:
	mkdir -p ../../../Filesets.sl/SYS-ADMIN/etc/newconfig
	! cp mkdev ../../../Filesets.sl/SYS-ADMIN/etc/newconfig/mkdev
	! chmog 555 bin bin ../../../Filesets.sl/SYS-ADMIN/etc/newconfig/mkdev
	! chmog 555 bin bin ../../../Filesets.sl/SYS-ADMIN/etc/newconfig
	! chmog 555 bin bin ../../../Filesets.sl/SYS-ADMIN/etc
	! chmog 555 bin bin ../../../Filesets.sl/SYS-ADMIN
	! chmog 555 bin bin ../../../Filesets.sl
