default:
	:

install:
	mkdir -p ../../../Filesets.sl/ACCOUNTNG/system/ACCOUNTNG
	! cp ACCOUNTNG.cst ../../../Filesets.sl/ACCOUNTNG/system/ACCOUNTNG/customize
	! chmog 544 bin bin ../../../Filesets.sl/ACCOUNTNG/system/ACCOUNTNG/customize
	! chmog 555 bin bin ../../../Filesets.sl/ACCOUNTNG/system/ACCOUNTNG
	! chmog 555 bin bin ../../../Filesets.sl/ACCOUNTNG/system
	! chmog 555 bin bin ../../../Filesets.sl/ACCOUNTNG
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/AMERICAN/system/AMERICAN
	! cp AMERICAN.cst ../../../Filesets.sl/AMERICAN/system/AMERICAN/customize
	! chmog 544 bin bin ../../../Filesets.sl/AMERICAN/system/AMERICAN/customize
	! chmog 555 bin bin ../../../Filesets.sl/AMERICAN/system/AMERICAN
	! chmog 555 bin bin ../../../Filesets.sl/AMERICAN/system
	! chmog 555 bin bin ../../../Filesets.sl/AMERICAN
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/ARABIC/system/ARABIC
	! cp ARABIC.cst ../../../Filesets.sl/ARABIC/system/ARABIC/customize
	! chmog 544 bin bin ../../../Filesets.sl/ARABIC/system/ARABIC/customize
	! chmog 555 bin bin ../../../Filesets.sl/ARABIC/system/ARABIC
	! chmog 555 bin bin ../../../Filesets.sl/ARABIC/system
	! chmog 555 bin bin ../../../Filesets.sl/ARABIC
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/ARABICW/system/ARABICW
	! cp ARABICW.cst ../../../Filesets.sl/ARABICW/system/ARABICW/customize
	! chmog 544 bin bin ../../../Filesets.sl/ARABICW/system/ARABICW/customize
	! chmog 555 bin bin ../../../Filesets.sl/ARABICW/system/ARABICW
	! chmog 555 bin bin ../../../Filesets.sl/ARABICW/system
	! chmog 555 bin bin ../../../Filesets.sl/ARABICW
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/AUDIT/system/AUDIT
	! cp AUDIT.cst ../../../Filesets.sl/AUDIT/system/AUDIT/customize
	! chmog 544 bin bin ../../../Filesets.sl/AUDIT/system/AUDIT/customize
	! chmog 555 bin bin ../../../Filesets.sl/AUDIT/system/AUDIT
	! chmog 555 bin bin ../../../Filesets.sl/AUDIT/system
	! chmog 555 bin bin ../../../Filesets.sl/AUDIT
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/BIF-CMDS/system/BIF-CMDS
	! cp BIF-CMDS.cst ../../../Filesets.sl/BIF-CMDS/system/BIF-CMDS/customize
	! chmog 544 bin bin ../../../Filesets.sl/BIF-CMDS/system/BIF-CMDS/customize
	! chmog 555 bin bin ../../../Filesets.sl/BIF-CMDS/system/BIF-CMDS
	! chmog 555 bin bin ../../../Filesets.sl/BIF-CMDS/system
	! chmog 555 bin bin ../../../Filesets.sl/BIF-CMDS
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/BULGARIAN/system/BULGARIAN
	! cp BULGARIAN.cst ../../../Filesets.sl/BULGARIAN/system/BULGARIAN/customize
	! chmog 544 bin bin ../../../Filesets.sl/BULGARIAN/system/BULGARIAN/customize
	! chmog 555 bin bin ../../../Filesets.sl/BULGARIAN/system/BULGARIAN
	! chmog 555 bin bin ../../../Filesets.sl/BULGARIAN/system
	! chmog 555 bin bin ../../../Filesets.sl/BULGARIAN
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/C/system/C
	! cp C.cst ../../../Filesets.sl/C/system/C/customize
	! chmog 544 bin bin ../../../Filesets.sl/C/system/C/customize
	! chmog 555 bin bin ../../../Filesets.sl/C/system/C
	! chmog 555 bin bin ../../../Filesets.sl/C/system
	! chmog 555 bin bin ../../../Filesets.sl/C
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/C-AUX/system/C-AUX
	! cp C-AUX.cst ../../../Filesets.sl/C-AUX/system/C-AUX/customize
	! chmog 544 bin bin ../../../Filesets.sl/C-AUX/system/C-AUX/customize
	! chmog 555 bin bin ../../../Filesets.sl/C-AUX/system/C-AUX
	! chmog 555 bin bin ../../../Filesets.sl/C-AUX/system
	! chmog 555 bin bin ../../../Filesets.sl/C-AUX
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/C-INC/system/C-INC
	! cp C-INC.cst ../../../Filesets.sl/C-INC/system/C-INC/customize
	! chmog 544 bin bin ../../../Filesets.sl/C-INC/system/C-INC/customize
	! chmog 555 bin bin ../../../Filesets.sl/C-INC/system/C-INC
	! chmog 555 bin bin ../../../Filesets.sl/C-INC/system
	! chmog 555 bin bin ../../../Filesets.sl/C-INC
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/C-MIN/system/C-MIN
	! cp C-MIN.cst ../../../Filesets.sl/C-MIN/system/C-MIN/customize
	! chmog 544 bin bin ../../../Filesets.sl/C-MIN/system/C-MIN/customize
	! chmog 555 bin bin ../../../Filesets.sl/C-MIN/system/C-MIN
	! chmog 555 bin bin ../../../Filesets.sl/C-MIN/system
	! chmog 555 bin bin ../../../Filesets.sl/C-MIN
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/C-TOOLS/system/C-TOOLS
	! cp C-TOOLS.cst ../../../Filesets.sl/C-TOOLS/system/C-TOOLS/customize
	! chmog 544 bin bin ../../../Filesets.sl/C-TOOLS/system/C-TOOLS/customize
	! chmog 555 bin bin ../../../Filesets.sl/C-TOOLS/system/C-TOOLS
	! chmog 555 bin bin ../../../Filesets.sl/C-TOOLS/system
	! chmog 555 bin bin ../../../Filesets.sl/C-TOOLS
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/CFRENCH/system/CFRENCH
	! cp CFRENCH.cst ../../../Filesets.sl/CFRENCH/system/CFRENCH/customize
	! chmog 544 bin bin ../../../Filesets.sl/CFRENCH/system/CFRENCH/customize
	! chmog 555 bin bin ../../../Filesets.sl/CFRENCH/system/CFRENCH
	! chmog 555 bin bin ../../../Filesets.sl/CFRENCH/system
	! chmog 555 bin bin ../../../Filesets.sl/CFRENCH
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/CFRENCH-CAT/system/CFRENCH-CAT
	! cp CFRENCH-CAT.cst ../../../Filesets.sl/CFRENCH-CAT/system/CFRENCH-CAT/customize
	! chmog 544 bin bin ../../../Filesets.sl/CFRENCH-CAT/system/CFRENCH-CAT/customize
	! chmog 555 bin bin ../../../Filesets.sl/CFRENCH-CAT/system/CFRENCH-CAT
	! chmog 555 bin bin ../../../Filesets.sl/CFRENCH-CAT/system
	! chmog 555 bin bin ../../../Filesets.sl/CFRENCH-CAT
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/CHINESES/system/CHINESES
	! cp CHINESES.cst ../../../Filesets.sl/CHINESES/system/CHINESES/customize
	! chmog 544 bin bin ../../../Filesets.sl/CHINESES/system/CHINESES/customize
	! chmog 555 bin bin ../../../Filesets.sl/CHINESES/system/CHINESES
	! chmog 555 bin bin ../../../Filesets.sl/CHINESES/system
	! chmog 555 bin bin ../../../Filesets.sl/CHINESES
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/CHINESES-CAT/system/CHINESES-CAT
	! cp CHINESES-CAT.cst ../../../Filesets.sl/CHINESES-CAT/system/CHINESES-CAT/customize
	! chmog 544 bin bin ../../../Filesets.sl/CHINESES-CAT/system/CHINESES-CAT/customize
	! chmog 555 bin bin ../../../Filesets.sl/CHINESES-CAT/system/CHINESES-CAT
	! chmog 555 bin bin ../../../Filesets.sl/CHINESES-CAT/system
	! chmog 555 bin bin ../../../Filesets.sl/CHINESES-CAT
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/CHINESET/system/CHINESET
	! cp CHINESET.cst ../../../Filesets.sl/CHINESET/system/CHINESET/customize
	! chmog 544 bin bin ../../../Filesets.sl/CHINESET/system/CHINESET/customize
	! chmog 555 bin bin ../../../Filesets.sl/CHINESET/system/CHINESET
	! chmog 555 bin bin ../../../Filesets.sl/CHINESET/system
	! chmog 555 bin bin ../../../Filesets.sl/CHINESET
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/CHINESET-CAT/system/CHINESET-CAT
	! cp CHINESET-CAT.cst ../../../Filesets.sl/CHINESET-CAT/system/CHINESET-CAT/customize
	! chmog 544 bin bin ../../../Filesets.sl/CHINESET-CAT/system/CHINESET-CAT/customize
	! chmog 555 bin bin ../../../Filesets.sl/CHINESET-CAT/system/CHINESET-CAT
	! chmog 555 bin bin ../../../Filesets.sl/CHINESET-CAT/system
	! chmog 555 bin bin ../../../Filesets.sl/CHINESET-CAT
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/CMDS-AUX/system/CMDS-AUX
	! cp CMDS-AUX.cst ../../../Filesets.sl/CMDS-AUX/system/CMDS-AUX/customize
	! chmog 544 bin bin ../../../Filesets.sl/CMDS-AUX/system/CMDS-AUX/customize
	! chmog 555 bin bin ../../../Filesets.sl/CMDS-AUX/system/CMDS-AUX
	! chmog 555 bin bin ../../../Filesets.sl/CMDS-AUX/system
	! chmog 555 bin bin ../../../Filesets.sl/CMDS-AUX
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/CMDS-MIN/system/CMDS-MIN
	! cp CMDS-MIN.cst ../../../Filesets.sl/CMDS-MIN/system/CMDS-MIN/customize
	! cp cron_config ../../../Filesets.sl/CMDS-MIN/system/CMDS-MIN/cron_config
	! chmog 544 bin bin ../../../Filesets.sl/CMDS-MIN/system/CMDS-MIN/customize
	! chmog 544 bin bin ../../../Filesets.sl/CMDS-MIN/system/CMDS-MIN/cron_config
	! chmog 555 bin bin ../../../Filesets.sl/CMDS-MIN/system/CMDS-MIN
	! chmog 555 bin bin ../../../Filesets.sl/CMDS-MIN/system
	! chmog 555 bin bin ../../../Filesets.sl/CMDS-MIN
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/CORE-SHLIBS/system/CORE-SHLIBS
	! cp CORE-SHLIBS.cst ../../../Filesets.sl/CORE-SHLIBS/system/CORE-SHLIBS/customize
	! chmog 544 bin bin ../../../Filesets.sl/CORE-SHLIBS/system/CORE-SHLIBS/customize
	! chmog 555 bin bin ../../../Filesets.sl/CORE-SHLIBS/system/CORE-SHLIBS
	! chmog 555 bin bin ../../../Filesets.sl/CORE-SHLIBS/system
	! chmog 555 bin bin ../../../Filesets.sl/CORE-SHLIBS
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/CZECH/system/CZECH
	! cp CZECH.cst ../../../Filesets.sl/CZECH/system/CZECH/customize
	! chmog 544 bin bin ../../../Filesets.sl/CZECH/system/CZECH/customize
	! chmog 555 bin bin ../../../Filesets.sl/CZECH/system/CZECH
	! chmog 555 bin bin ../../../Filesets.sl/CZECH/system
	! chmog 555 bin bin ../../../Filesets.sl/CZECH
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/DANISH/system/DANISH
	! cp DANISH.cst ../../../Filesets.sl/DANISH/system/DANISH/customize
	! chmog 544 bin bin ../../../Filesets.sl/DANISH/system/DANISH/customize
	! chmog 555 bin bin ../../../Filesets.sl/DANISH/system/DANISH
	! chmog 555 bin bin ../../../Filesets.sl/DANISH/system
	! chmog 555 bin bin ../../../Filesets.sl/DANISH
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/DISKLESS/system/DISKLESS
	! cp DISKLESS.cst ../../../Filesets.sl/DISKLESS/system/DISKLESS/customize
	! chmog 544 bin bin ../../../Filesets.sl/DISKLESS/system/DISKLESS/customize
	! chmog 555 bin bin ../../../Filesets.sl/DISKLESS/system/DISKLESS
	! chmog 555 bin bin ../../../Filesets.sl/DISKLESS/system
	! chmog 555 bin bin ../../../Filesets.sl/DISKLESS
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/DOS-UTILS/system/DOS-UTILS
	! cp DOS-UTILS.cst ../../../Filesets.sl/DOS-UTILS/system/DOS-UTILS/customize
	! chmog 544 bin bin ../../../Filesets.sl/DOS-UTILS/system/DOS-UTILS/customize
	! chmog 555 bin bin ../../../Filesets.sl/DOS-UTILS/system/DOS-UTILS
	! chmog 555 bin bin ../../../Filesets.sl/DOS-UTILS/system
	! chmog 555 bin bin ../../../Filesets.sl/DOS-UTILS
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/DQUOTA/system/DQUOTA
	! cp DQUOTA.cst ../../../Filesets.sl/DQUOTA/system/DQUOTA/customize
	! chmog 544 bin bin ../../../Filesets.sl/DQUOTA/system/DQUOTA/customize
	! chmog 555 bin bin ../../../Filesets.sl/DQUOTA/system/DQUOTA
	! chmog 555 bin bin ../../../Filesets.sl/DQUOTA/system
	! chmog 555 bin bin ../../../Filesets.sl/DQUOTA
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/DUTCH/system/DUTCH
	! cp DUTCH.cst ../../../Filesets.sl/DUTCH/system/DUTCH/customize
	! chmog 544 bin bin ../../../Filesets.sl/DUTCH/system/DUTCH/customize
	! chmog 555 bin bin ../../../Filesets.sl/DUTCH/system/DUTCH
	! chmog 555 bin bin ../../../Filesets.sl/DUTCH/system
	! chmog 555 bin bin ../../../Filesets.sl/DUTCH
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/ECC-TOOLS/system/ECC-TOOLS
	! cp ECC-TOOLS.cst ../../../Filesets.sl/ECC-TOOLS/system/ECC-TOOLS/customize
	! chmog 544 bin bin ../../../Filesets.sl/ECC-TOOLS/system/ECC-TOOLS/customize
	! chmog 555 bin bin ../../../Filesets.sl/ECC-TOOLS/system/ECC-TOOLS
	! chmog 555 bin bin ../../../Filesets.sl/ECC-TOOLS/system
	! chmog 555 bin bin ../../../Filesets.sl/ECC-TOOLS
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/EDITORS/system/EDITORS
	! cp EDITORS.cst ../../../Filesets.sl/EDITORS/system/EDITORS/customize
	! chmog 544 bin bin ../../../Filesets.sl/EDITORS/system/EDITORS/customize
	! chmog 555 bin bin ../../../Filesets.sl/EDITORS/system/EDITORS
	! chmog 555 bin bin ../../../Filesets.sl/EDITORS/system
	! chmog 555 bin bin ../../../Filesets.sl/EDITORS
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/ENGLISH/system/ENGLISH
	! cp ENGLISH.cst ../../../Filesets.sl/ENGLISH/system/ENGLISH/customize
	! chmog 544 bin bin ../../../Filesets.sl/ENGLISH/system/ENGLISH/customize
	! chmog 555 bin bin ../../../Filesets.sl/ENGLISH/system/ENGLISH
	! chmog 555 bin bin ../../../Filesets.sl/ENGLISH/system
	! chmog 555 bin bin ../../../Filesets.sl/ENGLISH
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/FINNISH/system/FINNISH
	! cp FINNISH.cst ../../../Filesets.sl/FINNISH/system/FINNISH/customize
	! chmog 544 bin bin ../../../Filesets.sl/FINNISH/system/FINNISH/customize
	! chmog 555 bin bin ../../../Filesets.sl/FINNISH/system/FINNISH
	! chmog 555 bin bin ../../../Filesets.sl/FINNISH/system
	! chmog 555 bin bin ../../../Filesets.sl/FINNISH
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/FPA/system/FPA
	! cp FPA.cst ../../../Filesets.sl/FPA/system/FPA/customize
	! chmog 544 bin bin ../../../Filesets.sl/FPA/system/FPA/customize
	! chmog 555 bin bin ../../../Filesets.sl/FPA/system/FPA
	! chmog 555 bin bin ../../../Filesets.sl/FPA/system
	! chmog 555 bin bin ../../../Filesets.sl/FPA
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/FRENCH/system/FRENCH
	! cp FRENCH.cst ../../../Filesets.sl/FRENCH/system/FRENCH/customize
	! chmog 544 bin bin ../../../Filesets.sl/FRENCH/system/FRENCH/customize
	! chmog 555 bin bin ../../../Filesets.sl/FRENCH/system/FRENCH
	! chmog 555 bin bin ../../../Filesets.sl/FRENCH/system
	! chmog 555 bin bin ../../../Filesets.sl/FRENCH
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/FRENCH-CAT/system/FRENCH-CAT
	! cp FRENCH-CAT.cst ../../../Filesets.sl/FRENCH-CAT/system/FRENCH-CAT/customize
	! chmog 544 bin bin ../../../Filesets.sl/FRENCH-CAT/system/FRENCH-CAT/customize
	! chmog 555 bin bin ../../../Filesets.sl/FRENCH-CAT/system/FRENCH-CAT
	! chmog 555 bin bin ../../../Filesets.sl/FRENCH-CAT/system
	! chmog 555 bin bin ../../../Filesets.sl/FRENCH-CAT
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/GERMAN/system/GERMAN
	! cp GERMAN.cst ../../../Filesets.sl/GERMAN/system/GERMAN/customize
	! chmog 544 bin bin ../../../Filesets.sl/GERMAN/system/GERMAN/customize
	! chmog 555 bin bin ../../../Filesets.sl/GERMAN/system/GERMAN
	! chmog 555 bin bin ../../../Filesets.sl/GERMAN/system
	! chmog 555 bin bin ../../../Filesets.sl/GERMAN
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/GERMAN-CAT/system/GERMAN-CAT
	! cp GERMAN-CAT.cst ../../../Filesets.sl/GERMAN-CAT/system/GERMAN-CAT/customize
	! chmog 544 bin bin ../../../Filesets.sl/GERMAN-CAT/system/GERMAN-CAT/customize
	! chmog 555 bin bin ../../../Filesets.sl/GERMAN-CAT/system/GERMAN-CAT
	! chmog 555 bin bin ../../../Filesets.sl/GERMAN-CAT/system
	! chmog 555 bin bin ../../../Filesets.sl/GERMAN-CAT
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/GREEK/system/GREEK
	! cp GREEK.cst ../../../Filesets.sl/GREEK/system/GREEK/customize
	! chmog 544 bin bin ../../../Filesets.sl/GREEK/system/GREEK/customize
	! chmog 555 bin bin ../../../Filesets.sl/GREEK/system/GREEK
	! chmog 555 bin bin ../../../Filesets.sl/GREEK/system
	! chmog 555 bin bin ../../../Filesets.sl/GREEK
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/HEBREW/system/HEBREW
	! cp HEBREW.cst ../../../Filesets.sl/HEBREW/system/HEBREW/customize
	! chmog 544 bin bin ../../../Filesets.sl/HEBREW/system/HEBREW/customize
	! chmog 555 bin bin ../../../Filesets.sl/HEBREW/system/HEBREW
	! chmog 555 bin bin ../../../Filesets.sl/HEBREW/system
	! chmog 555 bin bin ../../../Filesets.sl/HEBREW
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/HUNGARIAN/system/HUNGARIAN
	! cp HUNGARIAN.cst ../../../Filesets.sl/HUNGARIAN/system/HUNGARIAN/customize
	! chmog 544 bin bin ../../../Filesets.sl/HUNGARIAN/system/HUNGARIAN/customize
	! chmog 555 bin bin ../../../Filesets.sl/HUNGARIAN/system/HUNGARIAN
	! chmog 555 bin bin ../../../Filesets.sl/HUNGARIAN/system
	! chmog 555 bin bin ../../../Filesets.sl/HUNGARIAN
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/ICELANDIC/system/ICELANDIC
	! cp ICELANDIC.cst ../../../Filesets.sl/ICELANDIC/system/ICELANDIC/customize
	! chmog 544 bin bin ../../../Filesets.sl/ICELANDIC/system/ICELANDIC/customize
	! chmog 555 bin bin ../../../Filesets.sl/ICELANDIC/system/ICELANDIC
	! chmog 555 bin bin ../../../Filesets.sl/ICELANDIC/system
	! chmog 555 bin bin ../../../Filesets.sl/ICELANDIC
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/ITALIAN/system/ITALIAN
	! cp ITALIAN.cst ../../../Filesets.sl/ITALIAN/system/ITALIAN/customize
	! chmog 544 bin bin ../../../Filesets.sl/ITALIAN/system/ITALIAN/customize
	! chmog 555 bin bin ../../../Filesets.sl/ITALIAN/system/ITALIAN
	! chmog 555 bin bin ../../../Filesets.sl/ITALIAN/system
	! chmog 555 bin bin ../../../Filesets.sl/ITALIAN
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/JAPANESE/system/JAPANESE
	! cp JAPANESE.cst ../../../Filesets.sl/JAPANESE/system/JAPANESE/customize
	! chmog 544 bin bin ../../../Filesets.sl/JAPANESE/system/JAPANESE/customize
	! chmog 555 bin bin ../../../Filesets.sl/JAPANESE/system/JAPANESE
	! chmog 555 bin bin ../../../Filesets.sl/JAPANESE/system
	! chmog 555 bin bin ../../../Filesets.sl/JAPANESE
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/JAPANESE-CAT/system/JAPANESE-CAT
	! cp JAPANESE-CAT.cst ../../../Filesets.sl/JAPANESE-CAT/system/JAPANESE-CAT/customize
	! chmog 544 bin bin ../../../Filesets.sl/JAPANESE-CAT/system/JAPANESE-CAT/customize
	! chmog 555 bin bin ../../../Filesets.sl/JAPANESE-CAT/system/JAPANESE-CAT
	! chmog 555 bin bin ../../../Filesets.sl/JAPANESE-CAT/system
	! chmog 555 bin bin ../../../Filesets.sl/JAPANESE-CAT
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/KATAKANA/system/KATAKANA
	! cp KATAKANA.cst ../../../Filesets.sl/KATAKANA/system/KATAKANA/customize
	! chmog 544 bin bin ../../../Filesets.sl/KATAKANA/system/KATAKANA/customize
	! chmog 555 bin bin ../../../Filesets.sl/KATAKANA/system/KATAKANA
	! chmog 555 bin bin ../../../Filesets.sl/KATAKANA/system
	! chmog 555 bin bin ../../../Filesets.sl/KATAKANA
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/KEYSHELL-RUN/system/KEYSHELL-RUN
	! cp KEYSHELL.cst ../../../Filesets.sl/KEYSHELL-RUN/system/KEYSHELL-RUN/customize
	! chmog 544 bin bin ../../../Filesets.sl/KEYSHELL-RUN/system/KEYSHELL-RUN/customize
	! chmog 555 bin bin ../../../Filesets.sl/KEYSHELL-RUN/system/KEYSHELL-RUN
	! chmog 555 bin bin ../../../Filesets.sl/KEYSHELL-RUN/system
	! chmog 555 bin bin ../../../Filesets.sl/KEYSHELL-RUN
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/KOREAN/system/KOREAN
	! cp KOREAN.cst ../../../Filesets.sl/KOREAN/system/KOREAN/customize
	! chmog 544 bin bin ../../../Filesets.sl/KOREAN/system/KOREAN/customize
	! chmog 555 bin bin ../../../Filesets.sl/KOREAN/system/KOREAN
	! chmog 555 bin bin ../../../Filesets.sl/KOREAN/system
	! chmog 555 bin bin ../../../Filesets.sl/KOREAN
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/KOREAN-CAT/system/KOREAN-CAT
	! cp KOREAN-CAT.cst ../../../Filesets.sl/KOREAN-CAT/system/KOREAN-CAT/customize
	! chmog 544 bin bin ../../../Filesets.sl/KOREAN-CAT/system/KOREAN-CAT/customize
	! chmog 555 bin bin ../../../Filesets.sl/KOREAN-CAT/system/KOREAN-CAT
	! chmog 555 bin bin ../../../Filesets.sl/KOREAN-CAT/system
	! chmog 555 bin bin ../../../Filesets.sl/KOREAN-CAT
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/LP-SPOOL/system/LP-SPOOL
	! cp LP-SPOOL.cst ../../../Filesets.sl/LP-SPOOL/system/LP-SPOOL/customize
	! chmog 544 bin bin ../../../Filesets.sl/LP-SPOOL/system/LP-SPOOL/customize
	! chmog 555 bin bin ../../../Filesets.sl/LP-SPOOL/system/LP-SPOOL
	! chmog 555 bin bin ../../../Filesets.sl/LP-SPOOL/system
	! chmog 555 bin bin ../../../Filesets.sl/LP-SPOOL
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/MAILERS/system/MAILERS
	! cp MAILERS.cst ../../../Filesets.sl/MAILERS/system/MAILERS/customize
	! chmog 544 bin bin ../../../Filesets.sl/MAILERS/system/MAILERS/customize
	! chmog 555 bin bin ../../../Filesets.sl/MAILERS/system/MAILERS
	! chmog 555 bin bin ../../../Filesets.sl/MAILERS/system
	! chmog 555 bin bin ../../../Filesets.sl/MAILERS
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/NLS-CORE/system/NLS-CORE
	! cp NLS-CORE.cst ../../../Filesets.sl/NLS-CORE/system/NLS-CORE/customize
	! chmog 544 bin bin ../../../Filesets.sl/NLS-CORE/system/NLS-CORE/customize
	! chmog 555 bin bin ../../../Filesets.sl/NLS-CORE/system/NLS-CORE
	! chmog 555 bin bin ../../../Filesets.sl/NLS-CORE/system
	! chmog 555 bin bin ../../../Filesets.sl/NLS-CORE
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/NONHPTERM/system/NONHPTERM
	! cp NONHPTERM.cst ../../../Filesets.sl/NONHPTERM/system/NONHPTERM/customize
	! chmog 544 bin bin ../../../Filesets.sl/NONHPTERM/system/NONHPTERM/customize
	! chmog 555 bin bin ../../../Filesets.sl/NONHPTERM/system/NONHPTERM
	! chmog 555 bin bin ../../../Filesets.sl/NONHPTERM/system
	! chmog 555 bin bin ../../../Filesets.sl/NONHPTERM
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/NORWEGIAN/system/NORWEGIAN
	! cp NORWEGIAN.cst ../../../Filesets.sl/NORWEGIAN/system/NORWEGIAN/customize
	! chmog 544 bin bin ../../../Filesets.sl/NORWEGIAN/system/NORWEGIAN/customize
	! chmog 555 bin bin ../../../Filesets.sl/NORWEGIAN/system/NORWEGIAN
	! chmog 555 bin bin ../../../Filesets.sl/NORWEGIAN/system
	! chmog 555 bin bin ../../../Filesets.sl/NORWEGIAN
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/POLISH/system/POLISH
	! cp POLISH.cst ../../../Filesets.sl/POLISH/system/POLISH/customize
	! chmog 544 bin bin ../../../Filesets.sl/POLISH/system/POLISH/customize
	! chmog 555 bin bin ../../../Filesets.sl/POLISH/system/POLISH
	! chmog 555 bin bin ../../../Filesets.sl/POLISH/system
	! chmog 555 bin bin ../../../Filesets.sl/POLISH
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/PORTUGUES/system/PORTUGUES
	! cp PORTUGUES.cst ../../../Filesets.sl/PORTUGUES/system/PORTUGUES/customize
	! chmog 544 bin bin ../../../Filesets.sl/PORTUGUES/system/PORTUGUES/customize
	! chmog 555 bin bin ../../../Filesets.sl/PORTUGUES/system/PORTUGUES
	! chmog 555 bin bin ../../../Filesets.sl/PORTUGUES/system
	! chmog 555 bin bin ../../../Filesets.sl/PORTUGUES
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/PROG-AUX/system/PROG-AUX
	! cp PROG-AUX.cst ../../../Filesets.sl/PROG-AUX/system/PROG-AUX/customize
	! chmog 544 bin bin ../../../Filesets.sl/PROG-AUX/system/PROG-AUX/customize
	! chmog 555 bin bin ../../../Filesets.sl/PROG-AUX/system/PROG-AUX
	! chmog 555 bin bin ../../../Filesets.sl/PROG-AUX/system
	! chmog 555 bin bin ../../../Filesets.sl/PROG-AUX
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/PROG-MIN/system/PROG-MIN
	! cp PROG-MIN.cst ../../../Filesets.sl/PROG-MIN/system/PROG-MIN/customize
	! chmog 544 bin bin ../../../Filesets.sl/PROG-MIN/system/PROG-MIN/customize
	! chmog 555 bin bin ../../../Filesets.sl/PROG-MIN/system/PROG-MIN
	! chmog 555 bin bin ../../../Filesets.sl/PROG-MIN/system
	! chmog 555 bin bin ../../../Filesets.sl/PROG-MIN
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/RBOOTD/system/RBOOTD
	! cp RBOOTD.cst ../../../Filesets.sl/RBOOTD/system/RBOOTD/customize
	! chmog 544 bin bin ../../../Filesets.sl/RBOOTD/system/RBOOTD/customize
	! chmog 555 bin bin ../../../Filesets.sl/RBOOTD/system/RBOOTD
	! chmog 555 bin bin ../../../Filesets.sl/RBOOTD/system
	! chmog 555 bin bin ../../../Filesets.sl/RBOOTD
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/RUMANIAN/system/RUMANIAN
	! cp RUMANIAN.cst ../../../Filesets.sl/RUMANIAN/system/RUMANIAN/customize
	! chmog 544 bin bin ../../../Filesets.sl/RUMANIAN/system/RUMANIAN/customize
	! chmog 555 bin bin ../../../Filesets.sl/RUMANIAN/system/RUMANIAN
	! chmog 555 bin bin ../../../Filesets.sl/RUMANIAN/system
	! chmog 555 bin bin ../../../Filesets.sl/RUMANIAN
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/RUSSIAN/system/RUSSIAN
	! cp RUSSIAN.cst ../../../Filesets.sl/RUSSIAN/system/RUSSIAN/customize
	! chmog 544 bin bin ../../../Filesets.sl/RUSSIAN/system/RUSSIAN/customize
	! chmog 555 bin bin ../../../Filesets.sl/RUSSIAN/system/RUSSIAN
	! chmog 555 bin bin ../../../Filesets.sl/RUSSIAN/system
	! chmog 555 bin bin ../../../Filesets.sl/RUSSIAN
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/SDF-CMDS/system/SDF-CMDS
	! cp SDF-CMDS.cst ../../../Filesets.sl/SDF-CMDS/system/SDF-CMDS/customize
	! chmog 544 bin bin ../../../Filesets.sl/SDF-CMDS/system/SDF-CMDS/customize
	! chmog 555 bin bin ../../../Filesets.sl/SDF-CMDS/system/SDF-CMDS
	! chmog 555 bin bin ../../../Filesets.sl/SDF-CMDS/system
	! chmog 555 bin bin ../../../Filesets.sl/SDF-CMDS
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/SERBOCROATIAN/system/SERBOCROATIAN
	! cp SERBOCROATIAN.cst ../../../Filesets.sl/SERBOCROATIAN/system/SERBOCROATIAN/customize
	! chmog 544 bin bin ../../../Filesets.sl/SERBOCROATIAN/system/SERBOCROATIAN/customize
	! chmog 555 bin bin ../../../Filesets.sl/SERBOCROATIAN/system/SERBOCROATIAN
	! chmog 555 bin bin ../../../Filesets.sl/SERBOCROATIAN/system
	! chmog 555 bin bin ../../../Filesets.sl/SERBOCROATIAN
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/SLOVENE/system/SLOVENE
	! cp SLOVENE.cst ../../../Filesets.sl/SLOVENE/system/SLOVENE/customize
	! chmog 544 bin bin ../../../Filesets.sl/SLOVENE/system/SLOVENE/customize
	! chmog 555 bin bin ../../../Filesets.sl/SLOVENE/system/SLOVENE
	! chmog 555 bin bin ../../../Filesets.sl/SLOVENE/system
	! chmog 555 bin bin ../../../Filesets.sl/SLOVENE
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/SPANISH/system/SPANISH
	! cp SPANISH.cst ../../../Filesets.sl/SPANISH/system/SPANISH/customize
	! chmog 544 bin bin ../../../Filesets.sl/SPANISH/system/SPANISH/customize
	! chmog 555 bin bin ../../../Filesets.sl/SPANISH/system/SPANISH
	! chmog 555 bin bin ../../../Filesets.sl/SPANISH/system
	! chmog 555 bin bin ../../../Filesets.sl/SPANISH
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/SPELL/system/SPELL
	! cp SPELL.cst ../../../Filesets.sl/SPELL/system/SPELL/customize
	! chmog 544 bin bin ../../../Filesets.sl/SPELL/system/SPELL/customize
	! chmog 555 bin bin ../../../Filesets.sl/SPELL/system/SPELL
	! chmog 555 bin bin ../../../Filesets.sl/SPELL/system
	! chmog 555 bin bin ../../../Filesets.sl/SPELL
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/SRC-CNTL/system/SRC-CNTL
	! cp SRC-CNTL.cst ../../../Filesets.sl/SRC-CNTL/system/SRC-CNTL/customize
	! chmog 544 bin bin ../../../Filesets.sl/SRC-CNTL/system/SRC-CNTL/customize
	! chmog 555 bin bin ../../../Filesets.sl/SRC-CNTL/system/SRC-CNTL
	! chmog 555 bin bin ../../../Filesets.sl/SRC-CNTL/system
	! chmog 555 bin bin ../../../Filesets.sl/SRC-CNTL
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/SWEDISH/system/SWEDISH
	! cp SWEDISH.cst ../../../Filesets.sl/SWEDISH/system/SWEDISH/customize
	! chmog 544 bin bin ../../../Filesets.sl/SWEDISH/system/SWEDISH/customize
	! chmog 555 bin bin ../../../Filesets.sl/SWEDISH/system/SWEDISH
	! chmog 555 bin bin ../../../Filesets.sl/SWEDISH/system
	! chmog 555 bin bin ../../../Filesets.sl/SWEDISH
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/SYS-ADMIN/system/SYS-ADMIN
	! cp SYS-ADMIN.cst ../../../Filesets.sl/SYS-ADMIN/system/SYS-ADMIN/customize
	! chmog 544 bin bin ../../../Filesets.sl/SYS-ADMIN/system/SYS-ADMIN/customize
	! chmog 555 bin bin ../../../Filesets.sl/SYS-ADMIN/system/SYS-ADMIN
	! chmog 555 bin bin ../../../Filesets.sl/SYS-ADMIN/system
	! chmog 555 bin bin ../../../Filesets.sl/SYS-ADMIN
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/SYSCOM/system/SYSCOM
	! cp SYSCOM.cst ../../../Filesets.sl/SYSCOM/system/SYSCOM/customize
	! chmog 544 bin bin ../../../Filesets.sl/SYSCOM/system/SYSCOM/customize
	! chmog 555 bin bin ../../../Filesets.sl/SYSCOM/system/SYSCOM
	! chmog 555 bin bin ../../../Filesets.sl/SYSCOM/system
	! chmog 555 bin bin ../../../Filesets.sl/SYSCOM
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/TERM-MNGR-MIN/system/TERM-MNGR-MIN
	! cp TERM-MNGR-MIN.cst ../../../Filesets.sl/TERM-MNGR-MIN/system/TERM-MNGR-MIN/customize
	! chmog 544 bin bin ../../../Filesets.sl/TERM-MNGR-MIN/system/TERM-MNGR-MIN/customize
	! chmog 555 bin bin ../../../Filesets.sl/TERM-MNGR-MIN/system/TERM-MNGR-MIN
	! chmog 555 bin bin ../../../Filesets.sl/TERM-MNGR-MIN/system
	! chmog 555 bin bin ../../../Filesets.sl/TERM-MNGR-MIN
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/TERM-MNGR-NHP/system/TERM-MNGR-NHP
	! cp TERM-MNGR-NHP.cst ../../../Filesets.sl/TERM-MNGR-NHP/system/TERM-MNGR-NHP/customize
	! chmog 544 bin bin ../../../Filesets.sl/TERM-MNGR-NHP/system/TERM-MNGR-NHP/customize
	! chmog 555 bin bin ../../../Filesets.sl/TERM-MNGR-NHP/system/TERM-MNGR-NHP
	! chmog 555 bin bin ../../../Filesets.sl/TERM-MNGR-NHP/system
	! chmog 555 bin bin ../../../Filesets.sl/TERM-MNGR-NHP
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/TEXT-FMT/system/TEXT-FMT
	! cp TEXT-FMT.cst ../../../Filesets.sl/TEXT-FMT/system/TEXT-FMT/customize
	! chmog 544 bin bin ../../../Filesets.sl/TEXT-FMT/system/TEXT-FMT/customize
	! chmog 555 bin bin ../../../Filesets.sl/TEXT-FMT/system/TEXT-FMT
	! chmog 555 bin bin ../../../Filesets.sl/TEXT-FMT/system
	! chmog 555 bin bin ../../../Filesets.sl/TEXT-FMT
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/THAI/system/THAI
	! cp THAI.cst ../../../Filesets.sl/THAI/system/THAI/customize
	! chmog 544 bin bin ../../../Filesets.sl/THAI/system/THAI/customize
	! chmog 555 bin bin ../../../Filesets.sl/THAI/system/THAI
	! chmog 555 bin bin ../../../Filesets.sl/THAI/system
	! chmog 555 bin bin ../../../Filesets.sl/THAI
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/TURKISH/system/TURKISH
	! cp TURKISH.cst ../../../Filesets.sl/TURKISH/system/TURKISH/customize
	! chmog 544 bin bin ../../../Filesets.sl/TURKISH/system/TURKISH/customize
	! chmog 555 bin bin ../../../Filesets.sl/TURKISH/system/TURKISH
	! chmog 555 bin bin ../../../Filesets.sl/TURKISH/system
	! chmog 555 bin bin ../../../Filesets.sl/TURKISH
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/UNSUPP/system/UNSUPP
	! cp UNSUPP.cst ../../../Filesets.sl/UNSUPP/system/UNSUPP/customize
	! chmog 544 bin bin ../../../Filesets.sl/UNSUPP/system/UNSUPP/customize
	! chmog 555 bin bin ../../../Filesets.sl/UNSUPP/system/UNSUPP
	! chmog 555 bin bin ../../../Filesets.sl/UNSUPP/system
	! chmog 555 bin bin ../../../Filesets.sl/UNSUPP
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/USRCONTRB/system/USRCONTRB
	! cp USRCONTRB.cst ../../../Filesets.sl/USRCONTRB/system/USRCONTRB/customize
	! chmog 544 bin bin ../../../Filesets.sl/USRCONTRB/system/USRCONTRB/customize
	! chmog 555 bin bin ../../../Filesets.sl/USRCONTRB/system/USRCONTRB
	! chmog 555 bin bin ../../../Filesets.sl/USRCONTRB/system
	! chmog 555 bin bin ../../../Filesets.sl/USRCONTRB
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/UUCP/system/UUCP
	! cp UUCP.cst ../../../Filesets.sl/UUCP/system/UUCP/customize
	! chmog 544 bin bin ../../../Filesets.sl/UUCP/system/UUCP/customize
	! chmog 555 bin bin ../../../Filesets.sl/UUCP/system/UUCP
	! chmog 555 bin bin ../../../Filesets.sl/UUCP/system
	! chmog 555 bin bin ../../../Filesets.sl/UUCP
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/UX-CORE/system/UX-CORE
	! cp UX-CORE.cst ../../../Filesets.sl/UX-CORE/system/UX-CORE/customize
	! cp custom_utils ../../../Filesets.sl/UX-CORE/system/UX-CORE/custom_utils
	! chmog 544 bin bin ../../../Filesets.sl/UX-CORE/system/UX-CORE/customize
	! chmog 544 bin bin ../../../Filesets.sl/UX-CORE/system/UX-CORE/custom_utils
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE/system/UX-CORE
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE/system
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE
	! chmog 555 bin bin ../../../Filesets.sl

