default:
	: 
install:
	mkdir -p ../../../Filesets.sl/UX-CORE/etc/newconfig
	! cp group ../../../Filesets.sl/UX-CORE/etc/newconfig/group
	! chmog 444 bin bin ../../../Filesets.sl/UX-CORE/etc/newconfig/group
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE/etc/newconfig
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE/etc
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE
	! chmog 555 bin bin ../../../Filesets.sl
