$set 1
10 Internal caller type %s\n
11 mlock %s failed\n
12 mlock %s succeeded\n
13 generic open timeout\n
16 ゼネリック・オープンができません (%d)。エラー番号 = %d\n
19 %s not found in Dialers file\n
22 gdial(%s) called\n
23 dkcall(%s)\n
27 tcpdial host %s, 
28 port %d\n
29 no socket: %s\n
31 no socket, errno %d\n
34 timeout tcpopen\n
37 family: %d\n
38 port: %d\n
39 addr: %08x\n
40 connect failed: %s\n
42 connect failed, errno %d\n
45 unetdial host %s, 
46 port %d\n
47 tcpopen failed: errno %d\n
48 OPEN FAILED %s\n
50 COM1 return = %d\n
52 timeout sytek open\n
53 OPEN 2 FAILED %s\n
54 mlock %s failed\n
55 Use Port %s, 
56 acu - %s, 
57 Phone Number  %s\n
58 Trying modem - %s, 
59 acu - %s, 
60 calling  %s:  
61 SUCCEEDED\n
62 FAILED\n
63 can't open %s\n
64 %s is open\n
65 timeout modem open\n
66 Dialing failed. Child died.\n
68 ACU write error %d\n
69 Dialing using program %s\n
72 dcf is %d\n
73 Fork Stat %o\n
74 DN write %s\n
75 timeout
76 can't open %s\n
77 %s is open\n
78 can't open %s\n
79 dcf is %d\n
80 ACU write error %d\n
81 ACU write ok%s\n
82 Line open %s\n
83 failed
419 conn(%s)\n
420 getto ret %d\n
421 close caller (%d)\n
422 delock(%s)\n
423 Call Failed: %s\n
424 Device Type %s wanted\n
425 Requested Device Type Not Found\n
427 Wrong Time To Call: %s\n
428 ProtoStr = %s\n
430 expect: (
431 got it\n
432 lost line errno - %d\n
435 enough already\n
436 got it\n
437 timed out\n
438 BREAK\n
439 EOT\n
440 sendthem (
441 DELAY\n
442 <NO CR>
443 <NO CR - MIDDLE IGNORED>\n
444 PAUSE\n
445 ECHO CHECK ON\n
446 ECHO CHECK OFF\n
447 BREAK\n
448 ^M
449 )\n
524 fixline(%d, 
525 %d)\n
527 fixline - direct\n
529 setline - %c\n
530 sytfixline - speed= %d\n
534 fixline(%d, 
535 %d)\n
641 ulockf failed in onelock()\n
642 ulockf file %s\n
643 Lock File--can't read (errno %d) --remove it!\n
644 Lock File--bad format--remove it!\n
645 Lock File--process still active--not removed\n
646 kill pid (%d), 
647 returned %d
648 --ok to remove lock file (%s)\n
649 ulockf failed in unlink()\n
650 ulockf file %s\n
651 Lock File--can't read (errno %d) --remove it!\n
652 --ok to remove lock file (%s)\n
653 ulockf failed in unlink()\n
657 link(%s, 
658 %s)\n
1120 [-h] [-v] [-w n] [-x n] [-s speed] telno ...
1121 ct: can't open %s\n
1122 \t使用法: %s %s\n
1123 (-w %s) Wait time must be > 0\n
1124 \t使用法: %s %s\n
1125 \t使用法: %s %s\n
1126 No phone numbers specified!\n
1127 ct: phone number too long -- %s\n
1128 ct: bad phone number -- %s\n
1129 Allocated dialer at %s baud\n
1130 No %s dialers on this system\n
1131 %s busy
1132 Dialer is
1133 Dialers are
1134  (%d minute(s))\n
1135 The (%d) %s dialer%s busy\n
1136  is
1137 s are
1138 Waiting for %d minute%s\n
1139 s
1140 Do you want to wait for dialer? (y for yes): 
1141 Time, in minutes? 
1142 Waiting for dialer\n
1143 *** TIMEOUT ***\n
1144 Confirm hang-up? (y to hang-up): 
1145 Connected\n
1146 Hit carriage return 
1147 there is a uugetty; exit\n
1148 start getty -h -t60 %s 
1149 ct: can't fork for getty\n
1150 ct: can't exec getty\n
1151 \nReconnect? 
1152 Disconnect(%d)\n
1153 Disconnected\n
1154 cleanup(%d)\n
1155 chmod/chown %s\n
1156 Can't chown/chmod on %s 
1157 to %d\n
1158 ut_line %s, 
1159 ut_user %s, 
1160 ut_id %.4s, 
1161 ut_pid %d\n
1162 process still active\n
