$set 1
1 使用方法: %s -f fromcode -t tocode [files ...]\n
2 変換テーブルのサイズを探すことができません。\n
3 変換テーブルの空間がありません。\n
4 変換を初期化できません。\n
5 入力文字が誤っています。\n
6 変換を終了できません。\n
7 %s から %s への変換は下記の文字をマップします:\n
8 ROMAN8: \\x%x %-25sISO8859/1: \\x%x %-25s\n
9 ISO8859/1: \\x%x %-25sROMAN8: \\x%x %-25s\n
10 NA (Do not use)
11 No break space
12 Accent grave
13 Left single quote
14 Circumflex accent
15 Caret
16 Tilde accent
17 Tilde
18 Italian lira symbol
19 Pound sign
20 Overline
21 Macron
22 Dutch guilder
23 Lowercase f
24 Uppercase S caron
25 Uppercase S
26 Lowercase s caron
27 Lowercase s
28 Uppercase Y umlaut
29 Uppercase Y
30 Horizonal bar
31 Hyphen
32 Solid box
33 Asterisk
34 NA (Do not use)
35 No break space
40 No break space
41 NA (Do not use)
42 Broken bar
43 Vertical line
44 Copyright sign
45 Lowercase c
46 Not sign
47 Tilde
48 Soft hyphen
49 Hyphen
50 Registered Trade Mark
51 Uppercase R
52 Macron
53 Top bar
54 Superscript two
55 Digit two
56 Superscript three
57 Digit three
58 Cedilla
59 Comma
60 Superscript one
61 Digit one
62 Multiplication sign
63 Lowercase x
64 Division sign
65 Solidus
