$set 1
4 空スロットです。\n
5 名前       TTY名        開始時刻        休眠時間  PID   コメント\n
6 名前       TTY名        開始時刻\n
7   id=%4.4s
8  ターミナル=%-3d 終了状態=%-3d
9 \nユーザ数=%d\n
10 \n使用法:\twho [-rbtpludAasHTqcRm] [am i] [utmp_like_file]\n
11 \n使用法:\twho [-rbtpludAasHTqRm] [am i] [utmp_like_file]\n
12 \nr\tラン・レベル\nb\tブート時刻\nt\t時刻の変更\n
13 p\tgetty あるいはユーザが生成した以外のプロセス\n
14 l\tログイン・プロセス\nu\t役に立つ情報\n
15 d\tデッド・プロセス\nA\tアカウント情報\n
16 a\t全情報 (rbtpludA オプションと同じ)\n
17 s\twho の短い書式 (前回からの経過時間と pid を表示しない)\n
18 H\tヘッダを出力\n
19 T\ttty の状態 (＋書き込み可能, －書き込み不能, ｘ排他オープン, ？ハング)\n
20 q\tクイック who\n
21 c\tクラスタ全体の who\n
22 %2m月 %2d日 %H:%M
23  old    
24    .    
25 %2u:%2.2u   
26 R\tホスト名を表示\n
