default:
	: 

install:
	mkdir -p ../../../Filesets.sl/PROG-AUX/etc/newconfig
	! cp termcap ../../../Filesets.sl/PROG-AUX/etc/newconfig/termcap
	! chmog 444 bin bin ../../../Filesets.sl/PROG-AUX/etc/newconfig/termcap
	! chmog 555 bin bin ../../../Filesets.sl/PROG-AUX/etc/newconfig
	! chmog 555 bin bin ../../../Filesets.sl/PROG-AUX/etc
	! chmog 555 bin bin ../../../Filesets.sl/PROG-AUX
	! chmog 555 bin bin ../../../Filesets.sl

