$set 1
1 -F または -f のいずれかを使います。\n
2 -F または -f のいずれかを使います。\n
3 -P または -p のいずれかを使います。\n
4 -P または -p のいずれかを使います。\n
5 mark_ev(%d) ができません。\n
6 '%c': イベント引き数がありません。\n
7 イベントがありません: %s\n
8 mark_ev(%d) ができません。\n
9 mark_sc(%d) ができません。\n
10 '%c': syscall 引き数がありません。\n
11 syscall がありません: %s\n
12 mark_sc(%d) ができません。\n
13 '%c': オプションが定義されていません。\n
21 スーパ・ユーザではありません。\n
22 audswitch(AUD_SUSPEND) ができません: %s\n
23 mark_ev(%d) ができません。\n
24 引き数が確定できません: %s\n
25 show_audit() ができません。\n
26 set_audit() ができません。\n
31 mark_sc(%d) ができません。\n
41 audwrite(%s) ができません: %s\n
42 getevent() ができません: %s\n
43 set_event(%s) ができません。\n
44 set_syscall(%d) ができません。\n
45 audwrite(%s) ができません: %s\n
46 setevent() ができません: %s\n
51 audwrite(%s) ができません: %s\n
52 getevent() ができません: %s\n
53 show_event(%s) ができません。\n
61 使用法: %s
