$set 1
2 chmod: %s をアクセスすることができません。\n
3 chmod: 変更ができません: 
4 chmod: モードが不適当です。\n
5 chmod: -A オプションはリモート・ファイルでは使えません: %s\n
6 chmod: %s へ移動することができません。\n
7 chmod: %s はディレクトリではありません。\n
101 使用法: chmod [-A] [-R] [ugoa]+-=[rwxXstHugo][,...] file ...\n
102 使用法: chmod [-R] [ugoa]+-=[rwxXstHugo][,...] file ...\n
103 使用法: chmod [-A] [-R] [ugoa]+-=[rwxXstugo][,...] file ...\n
104 使用法: chmod [-R] [ugoa]+-=[rwxXstugo][,...] file ...\n
