$set 1
1 使用法:\tcp [-f|-i] [-p] source_file target_file\n\tcp [-f|-i] [-p] source_file ... target_directory\n\tcp [-f|-i] [-p] -R|-r source_directory ... target_directory\n
2 cp: %s のリンクを解除できません: 
3 cp: %s をアクセスできません: 
4 cp: <%s> はディレクトリです。"-R" オプションを指定してください。\n
5 cp: %s/%s: 名前が長すぎます。\n
6 cp: %s と %s は同じです。\n
7 cp: %s: ディレクトリではありません。\n
9 cp: %s を作ることができません: 
10 cp: オープンできません: 
11 cp: %s を作ることができません: 
12 cp: %s にコピーすることはできません: 
13 cp: %s をクローズすることができません: 
14 cp: %s のパーミッション・ビットを設定できません: 
15 cp: %s/%s: 名前が長すぎます。\n
16 cp: mkrnod を実行できません。
17 cp: symlink を実行できません。
18 cp: readlink を実行できません。
19 cp: %s で utime できません: 
20 cp: %s で chown できません:
21 警告: ソケットがスキップされました: %s\n
22 cp: 警告: %s に cpacl できません。\n
23 cp: 警告: %s に cpacl できません。\n
24 link できません。
25 %s を書き換えますか? 
26 cp: %s: ディレクトリではありません。\n
27 cp: %s の ACL にアクセスできません: 
28 cp: %s に %d エントリの ACL をアロケートすることができません: 
29 cp: %s の ACL を読み取ることができません: 
