$set 1
1 使用法 : dumpmsg catfile\n
2 カタログ・ファイル %s をオープンします。\n
3 カタログ・ファイル %s をクローズします。\n
4 カタログ・ファイル中にメッセージがありません。\n
5 dumpmsg: %s はカタログ・ファイルではありません。\n
6 カタログ・ファイル中には %ld 行のメッセージがあります。\n
7 dumpmsg: %s はカタログ・ファイルとして適当ではありません。\n
8 setnum : %d\n
9 msgnum : %d\n
10 length : %d\n
11 addr   : %d\n\n
12 dumpmsg: %s はカタログ・ファイルとして適当ではありません。\n
13 setnum  : %d\n
14 msgnum  : %d\n
15 length  : %d\n
16 addr    : %d\n
17 message : %s\n\n
