$set 1
1 LC_COLLATEがセットできません。\n
2 LC_CTYPEがセットできません。\n
3 標準入力が再オープンできません。\n
4 使用法:\tlocaledef [-c] [-f charmap_file] [-i input_file] locale_name\n
5 または\tlocaledef -d [-o format] locale_name\n
6 または\tlocaledef -n input_file\n
7 'デバッグ' ファイルをオープンできません。\n
9 入力ファイル %s をオープンできません。\n
10 'langname' の指定がありません。\n
11 'langid' の指定がありません。\n
12 'langname' と 'langid' の指定が矛盾しています。\n
13 'isfirst' と 'byte_chars' の指定が矛盾しています。\n
14 警告: シーケンスの指定は無視されます。\n
15 LC_ALL カテゴリが最大許容サイズを超えました。\n
16 LC_MESSAGES カテゴリが最大許容サイズを超えました。\n
17 LC_COLLATE カテゴリが最大許容サイズを超えました。\n
18 LC_CTYPE カテゴリが最大許容サイズを超えました。\n
19 LC_MONETARY カテゴリが最大許容サイズを超えました。\n
20 LC_NUMERIC カテゴリが最大許容サイズを超えました。\n
21 LC_TIME カテゴリが最大許容サイズを超えました。\n
22 'locale.inf' ファイルを作成できません。\n
23 localedef エラー: 行 %d に不正なキーワードがあります。\n
25 localedef エラー: 行 %d に不正な文字があります。\n
26 localedef エラー: 行 %d に不正な文があります。\n
27 localedef エラー: 行 %d に不正な表現があります。\n
28 localedef エラー: 行 %d の範囲指定が不正です。\n
29 localedef エラー: 行 %d の langname 長が不正です。\n
30 localedef エラー: 行 %d の langid 番号が不正です。\n
31 localedef エラー: %d の langname の langage 名の長さが不正です。\n
32 localedef エラー: langname %d のテリトリ名の長さが不正です。\n
33 localedef エラー: 行 %d の langname の codeset 名の長さが不正です。\n
34 localedef エラー: 行 %d のリビジョン文字列長が不正です。\n
36 localedef エラー: 行 %d に不正な文字コードがあります。\n
37 localedef エラー: 行 %d に不正な isfirst 文字コードがあります。\n
38 localedef エラー: 行 %d に不正な issecond 文字コードがあります。\n
39 localedef エラー: code_scheme 名の長さ %d が不正です。\n
40 localedef エラー: code_cscheme 名の長さ %d が不正です。\n
41 localedef エラー: cswidth 文字列の長さ %d が不正です。\n
42 localedef エラー: cswidth 文字列のフォーマット %d が不正です。\n
43 localedef エラー: langinfo 文字列の長さ %d が不正です。\n
44 localedef エラー: monetary 文字列の長さ %d が不正です。\n
45 localedef: 数値文字列の長さ %d が不正です。\n
46 localedef エラー: 修飾文字列の長さ %d が不正です。\n
47 localedef エラー: malloc() が失敗しました。\n
48 localedef エラー: 優先順位キューがオーバフローしました。\n
49 localedef エラー: yes/no 文字列の最初の文字 %d が同じになりません。\n
50 localedef エラー: era 文字列の長さ %d が不正です。\n
51 localedef エラー: era 文字列のフォーマット %d が不正です。\n
52 localedef エラー: era 文字列の指定 %d が多過ぎます。\n
53 localedef エラー: 指定されたシンボルが見つかりません。%d\n
58 localedef エラー: charmap ファイルが見つかりません。\n
60 localedef エラー: シンボルが重複しています。%d\n
63 localedef エラー: 行 %d で COLL_WEIGHTS_MAX より大きい値が指定されています。\n
68 localedef 警告: 指定されたシンボルが見つかりません。%d\n
72 localedef 警告: 使えないキーワードです。%d\n
73 localedef 警告: ctype が正しく初期化されていません。 - 訂正します。\n
74 'langname' と 'langid' の指定が矛盾しています。
75 警告: ユーザ定義言語は901から999の範囲の langid でなければなりません。\n
76 ユーザ定義言語は901から999の範囲のlangidでなければなりません。
77 'langname' と 'langid' の指定が矛盾しています。
78 ファイルの読み取りでエラーが発生しました: 
79 ファイルを lseek できません: 
80 テンポラリ・ファイル %s がオープンできません。\n
81 キャラクタマップ・ファイルの解釈でエラーが発生しました。\n
82 locale エラー: LC_CALLATE カテゴリの中に不適切な行があります: %d\n
