$set 1
3 Finished Processing file: %s\n
5 gtwvec: dir %s\n
6         return - %d\n
7 insert(%s)  
8 insert %s 
9 at %d\n
10 Internal caller type %s\n
11 mlock %s failed\n
12 mlock %s succeeded\n
13 generic open timeout\n
16 ゼネリック・オープン (%d) ができません。エラー番号 = %d\n
19 %s not found in Dialers file\n
22 gdial(%s) called\n
23 dkcall(%s)\n
27 tcpdial host %s, 
28 port %d\n
29 no socket: %s\n
31 no socket, errno %d\n
34 timeout tcpopen\n
37 family: %d\n
38 port: %d\n
39 addr: %08x\n
40 connect failed: %s\n
42 connect failed, errno %d\n
45 unetdial host %s, 
46 port %d\n
47 tcpopen failed: errno %d\n
48 OPEN FAILED %s\n
50 COM1 return = %d\n
52 timeout sytek open\n
53 OPEN 2 FAILED %s\n
54 mlock %s failed\n
55 Use Port %s, 
56 acu - %s, 
57 Phone Number  %s\n
58 Trying modem - %s, 
59 acu - %s, 
60 calling  %s:  
61 SUCCEEDED\n
62 FAILED\n
63 can't open %s\n
64 %s is open\n
65 timeout modem open\n
66 Dialing failed. Child died.\n
68 ACU write error %d\n
69 Dialing using program %s\n
72 dcf is %d\n
73 Fork Stat %o\n
74 DN write %s\n
75 timeout
76 can't open %s\n
77 %s is open\n
78 can't open %s\n
79 dcf is %d\n
80 ACU write error %d\n
81 ACU write ok%s\n
82 Line open %s\n
83 failed
84 chdir(%s)\n
85 [-xNUM] [-r[0|1]] -sSYSTEM
88 %s not in Systems file\n
89 \t使用法: %s %s\n
90 No -s specified\n
91 This system specified: -sMyname: %s, 
92 cico.c: Myname - %s\n
93 cico.c: Loginuser - %s\n
95 sys-%s\n
98 return from callcheck: %s
109 Currently Talking With %s\n
112 %s - failed\n
113 %s - failed\n
114 Login Successful: System=%s\n
115 msg-%s\n
117 HANDSHAKE FAILED: %s\n
118  Rmtname %s, 
119 Role %s,  
120 MASTER
121 SLAVE
122 Ifn - %d, 
123 Loginuser - %s\n
126 %s - timeout\n
127 startup
130 %s\n
133 cntrl - %d\n
138 ret restline - %d\n
139 exit code %d\n
140 Conversation Complete: Status %s\n\n
141 FAILED
142 SUCCEEDED
143 TM_cnt: %d\n
145 使用法: uuname [-l]\n
146 Cannot open file "%s"
293 *** TOP ***  -  role=%d, 
295 Wfile - %s,
296 Jobid = %s\n
301 Request: %s\n
305 Failed: Access Denied\n
311 Failed: Can't Read %s\n
314 Request: %s\n
318 Failed: Access Denied--File: %s\n
322 Failed: No Space!\n
323 wrktype - %c\n 
324  PROCESS: msg - %s\n
326 RQSTCMPT:
329 HUP:
331 SLAVE-switchRole (%s)\n
332 TRUE
333 FALSE
335 SNDFILE:
344 msg - %s\n
345 Remote Requested: %s\n
346 SLAVE - filename: %s\n
349 Failed: Access Denied\n
351 chkpth ok Rmtname - %s\n
355 Failed: Can't Create Temp File\n
361 ->PUBDIR %d\n
363 RCVFILE:
375 Remote Requested: %s\n
376 msg - %s\n
377 W_FILE1 - %s\n
382 Failed: Access Denied\n
383 requestOK for Loginuser - %s\n
386 Failed: Access Denied\n
387 chkpth ok Loginuser - %s\n
391 Failed: Can't Open %s\n
393 rmesg - '%c' 
394 got %s\n
395 FAIL
398 got %s\n
401 got %s\n
402 wmesg '%c'
403 %s\n
404 mailopt %d, 
405 statfopt %d\n
413 STMES %s\n
417 Proto started %c\n
418 Proto start-fail %c\n
419 conn(%s)\n
420 getto ret %d\n
421 close caller (%d)\n
422 delock(%s)\n
423 Call Failed: %s\n
424 Device Type %s wanted\n
425 Requested Device Type Not Found\n
427 Wrong Time To Call: %s\n
428 ProtoStr = %s\n
430 expect: (
431 got it\n
432 lost line errno - %d\n
435 enough already\n
436 got it\n
437 timed out\n
438 BREAK\n
439 EOT\n
440 sendthem (
441 DELAY\n
442 <NO CR>
443 <NO CR - MIDDLE IGNORED>\n
444 PAUSE\n
445 ECHO CHECK ON\n
446 ECHO CHECK OFF\n
447 BREAK\n
448 ^M
449 )\n
458 full %s\n
459 dturnon: ret=%d, 
460 Ofn=%d, 
461 errno=%d\n
462 ewrmsg write failed\n
463 erdmsg read failed\n
464 ewrdata failed\n
465 ewrmsg write %d\n
466 ewrmsg ret %d\n
468 erdblk msglen %d\n
469 erdblk ret %d\n
470 erdblk failed\n
471 erdblk read too much\n
472 <- %ld / %ld.%.3d secs
473 erdblk timeout\n
474 ask %d 
475 read failed\n
476 got %d\n
477 mkdir - %s\n
478 CAN'T STAT PARENT DIRECTORY %s 
479 errno %d\n
480 CAN'T CHMOD PARENT DIRECTORY %s 
481 errno %d\n
483 CAN'T CHMOD PARENT %s\n
487 Illegal filename (%s).\n
489 enter frdmsg:
490 checksum: %04x\n
491 ack - '%c'\n
494 RETRY:\n
495 fwrdata ret: %d\n
498 send ack: 'R'\n
499 RETRY:\n
500 send ack: 'Q'\n
501 send ack: 'G'\n
502 frddata ret: %d\n
503 \nchecksum: %04x\n
504 Bad checksum\n
505 Data corrupted\n
506 gename(%c, 
507 %s, 
508 %c)\n
509 null sys -> %s\n
510 file - %s\n
512 %s seq 
513 now %x\n
514 : illegal option -- 
515 : option requires an argument -- 
516 : option requires an argument -- 
517 stat %s\n
519 can't lock %s\n
520 commit %s 
521 to %s\n
522 imsg %s>
524 fixline(%d, 
525 %d)\n
527 fixline - direct\n
529 setline - %c\n
530 sytfixline - speed= %d\n
534 fixline(%d, 
535 %d)\n
536 使用法: %s -f script [-d] [-v]\n
537 %s unknown
538 syntax error
539 syntax: expect number string
540 syntax: expect number string
546 missing label
547 error or goto impossible
548 label %s not found
550 %s not found
551 expected number
552 expected string
554 too many args
555 expected flag
556 flag "%s" unrecognized
557 logFind called (name: %s, 
558 rmtname: %s)\n
559 machine/login match failed
560 _Request (%s), 
561 TRUE
562 FALSE
563 _Switch (%s), 
564 TRUE
565 FALSE
566 _CallBack (%s), 
567 TRUE
568 FALSE
569 _MyName (%s), 
570 mchFind called (%s)\n
584 _Commands %s\n
585 malloc() error\n
586 list (%s) 
587 num = %d\n
588 can't open %s\n
589 name (%s) not found; return FAIL\n
590 can't open %s\n
591 validateFind (%s) FAIL\n
593 bad option (%s) in PERMISSIONS\n
594 \n*****************************\n
595 **BAD OPTION in PERMISSIONS file: %s\n
596 *****************************\n
597 cmdOK(%s, )\n
598 bname=%s\n
600 not cntl\n
601 alloc change not implemented\n
602 pkcntl: RR/RJ: Connodata=%d\n
603 srj not implemented\n
604 r short %d want %d\n
605 rcount = %d\n
606 xcount = %d\n
607 tries = %d\n
608 pkgetpack: Connodata=%d\n
609 rec h->cntl %o\n
610 bad header %o,
611 h->ccntl %o\n
612 state -
613 bad header %o\n
614 bp NULL %s\n
615 send %o\n
618 alarm %d\n
619 KILL %s\n
620 Can't unlink %s\n
621 cannot lock %s\n
622 cannot open for reading:%s\n
623 Job %s is deleted\n
624 Job %s not found\n
625 fp: %o\n
626 job %s already complete\n
627 Permission Denied\n
629 shio - %s\n
630 status %d\n
634 RETRY TIME (%ld) NOT REACHED\n
636  enter ub_sst, status is : %d\n
637 Rmtname: %s\n
638 ulockf of %s failed\n
639 fopen of %s failed\n
640 in ub_sst name=Rmtname: %s\n
641 ulockf failed in onelock()\n
642 ulockf file %s\n
643 Lock File--can't read (errno %d) --remove it!\n
644 Lock File--bad format--remove it!\n
645 Lock File--process still active--not removed\n
646 kill pid (%d), 
647 returned %d
648 --ok to remove lock file (%s)\n
649 ulockf failed in unlink()\n
650 ulockf file %s\n
651 Lock File--can't read (errno %d) --remove it!\n
652 --ok to remove lock file (%s)\n
653 ulockf failed in unlink()\n
657 link(%s, 
658 %s)\n
660 [-v] [-xNUM]
661 \t使用法: %s %s\n
662 \t使用法: %s %s\n
663 *** uucheck:  Check Required Files and Directories\n
664 *** uucheck:  Directories Check Complete\n\n
665 *** uucheck:  Check %s file\n
666 *** uucheck:  %s Check Complete\n\n
667 ** %s \n\n
668 MACHINE PHASE (when we call or execute their uux requests)
669 LOGNAME PHASE (when they call us)
670 can't open %s\n
671 When a system logs in as: 
672 \tWe will call them back.\n\n
673 When we call system(s): 
674 \tWe %s allow them to request files.\n
675 DO
676 DO NOT
677 \tWe %s send files queued for them on this call.\n
678 WILL
679 WILL NOT
680 \tThey can send files to\n
681 \t    %s (DEFAULT)\n
682 \t    %s\n
683 \tExcept\n
684 \t    %s\n
685 \tThey can request files from\n
686 \t    %s (DEFAULT)\n
687 \t    %s\n
688 \tExcept\n
689 \t    %s\n
690 \tMyname for the conversation will be %s.\n
691 \tPUBDIR for the conversation will be %s.\n
692 Machine(s): 
693 \nCAN execute the following commands:\n
694 Software Error in permission.c\n
695 command (%s), fullname (%s)\n
696 unknown flag %s\n
697 %s directory unreadable\n
698 DEBUG# %s\n
699 START
700 cannot chdir to %s directory \n
701 stat on %s failed\n
702 unlink file %s\n
703 Prefix: %s\n
704 chkpre failed - file : %s\n
709 STM %d\n
710 [-oDAYS] [-mSTRING] [-Cdays] [-Ddays] [-Wdays] [-Xdays] [-xLEVEL] [-sSYSTEM]
711 \t使用法: %s %s\n
712  Options: CDWXo require value > 0\n
713 \t使用法: %s %s\n
714 Progname (%s): STARTED\n
715 Myname (%s), 
716 _ShortLocal (%s)\n
717 Days C.(%d), 
718 D.(%d), 
719 W.(%d), 
720 X.(%d), 
721 other (%d)\n
722 CAN'T CHDIR (%s): errno (%d)\n
723 CAN'T OPEN (%s): errno (%d)\n
724 Directory: %s\n
725 file: %s\n
726 xprocess(%s), 
727 unlink(%s)\n
729 \n\t%s!%s -> %s!%s   (Date %2.2d/%2.2d)\n\nCan't be executed.
730 \n\t%s!%s  (Date %2.2d/%2.2d)\n
731 \n\t%s!%s -> %s!%s   (Date %2.2d/%2.2d)\n
732 cprocess(%s)\n
733 Can't open file (%s), 
734 errno=%d -- skip it!\n
735 dummy C. -- unlink(%s)\n
740 text (%s)\n
741 wprocess(%s)\n
742 Can't open file (%s), 
743 errno=%d -- skip it!\n
744 dummy C. -- skip(%s)\n
745 short line (%s): 
746 bad D. -- skip(%s)\n
748 Can't read %s\n
749 retaddr (%s)\n
751 text (%s)\n
752 oprocess(%s), 
753 unlink(%s)\n
755 dDprocess(%s), 
756 unlink(%s)\n
758 dXprocess(%s), 
759   unlink(%s)\n
761 dMprocess(%s)\n
762   Local file %s: 
763   Remote file %s: 
764 toUser %s, 
765 toSystem %s  
766 Mail sent, unlink(%s)\n
768 dNprocess(%s)\n
769   Local file %s, 
770 unlink(%s)\n
772   Remote file %s, 
773 exec rnews(%s), 
774 unlink(%s)\n
776 Can't open file (%s), 
777 errno=%d -- skip it!\n
778 buf: %s\n
782 Mail %s to 
785 sendMail: %s\n
789 Rnews %s\n
791 toWho(%s)\n
792 buf: %s\n
794 unknown flag %s\n
796 START
797 No work directory - %s - get help\n
798 UID %d, 
799 User %s\n
800 usage uucp from ... to\n
801 bad system: %s\n
802 sys2: %s, 
803 fwd2: %s, 
804 file2: %s\n
805 bad system: %s\n
806 illegal  syntax %s\n
807 sys1 - %s, 
808 file1 - %s, 
809 Rmtname - %s\n
812 uucp failed completely: code %d\n
813 uucp failed partially: %d error
814  \n
815 s \n
816 all work here %d\n
817 can't get file status %s\n copy failed\n
818 %s %s - same file; can't copy\n
819 permission denied\n
820 directory name illegal - %s\n
821 uucp can't read (%s) mode (%o)\n
822 use cp command\n
823 can't write file (%s) mode (%o)\n
824 local copy:  uidxcp(%s, 
825 %s\n
826 can't copy file (%s) errno %d\n
827 receive file - %d\n
831 send file - %d\n
832 can't get status for file %s\n
833 directory name illegal - %s\n
837 cmd: %s\n
838 getty: timeout argument invalid. "%s"\n
839 Check Mode Usage: getty -c gettydefs-like-file\n
840 Cannot open %s\n
841 getty: no terminal line specified.\n
842 getty: unable to find %s in "%s".\n
843 getty: cannot open "%s". errno: %d\n
844 %.9s\r\n
845 getty: pointer to next speed in entry %s is bad.\n
846 getty: unable to find %s again.\n
847 \r\n
848 getty: can't open "%s".\n
849 Entry too long.\n
850 \n**** Next Entry ****\n%s\n
851 id: %s\n
852 initial flags:\niflag- %o oflag- %o cflag- %o lflag- %o\n
853 final flags:\niflag- %o oflag- %o cflag- %o lflag- %o\n
854 message: %s\n
855 next id: %s\n
856 Parsing failure in the "%s" field\n%s<--error detected here\n
857 Undefined: %s\n
861 使用法:  %s    [-m] [directories...]\n
862         %s -s [-m] [directories...]\n
863         %s -k [-m] [directories...]\n
864 can't stat directory
865 can't opendir directory
866 directory too large
867 can't chdir to
869 total
870 Orphans:
871 Others:
872 \n
873 Transactions:
874 \n%*s
875 %*s%-*s %s
876 \n
877 %*s\n
880 %s: illegal option -- %c\n
881 %s: option requires an argument -- %c\n
882 [-xNUM] [-uNUM]
883 \t使用法: %s %s\n
884 \t使用法: %s %s\n
885 Progname (%s): STARTED\n
886 No limitfile - %s\n
887 Uusched limit %d -- 
888 found %d -- cleanuping\n 
889 continuing\n
890 machine: %s, 
891 ccount: %d\n
892 Execute num=%d \n
893 num=%d, 
894 snumber=%d, 
895 Rmtname=%s\n
896 call exuucico(%s)\n
897 system %s locked or inappropriate status--skip it\n
898 machine(%s) called\n
900 ret=%d, 
901 errno=%d\n
902 %-*.*s 
903 %3.d Cmd%s 
904    ---   
905 %3.d Data 
906    ---   
907 %3.d Xqt%s 
908    ---   
909 LOCKED   
910 TALKING
911 Retry time reached  
912 Retry time %ld sec%s  
913 Retry time %ld min%s  
914 Count: %d\n
915 strange file (%s) in %s\n
916    \t(pid ??)
917    \t(pid ??)
918    \t(pid %d)
919 [-a] [-q] or [-m] or [-kJOB] or [-rJOB] or [-p]
920 [-sSYSTEM] [-uUSER]
921 \t使用法: %s %s\n
922 または\n\t使用法: %s %s\n
923 \t使用法: %s %s\n
924 または\n\t使用法: %s %s\n
925 Progname (%s): STARTED\n
926 User=%s, 
927 Loginuser=%s, 
928 Jobid=%s, 
929 Rmtname=%s\n
930 \t使用法: %s %s\n
931 または\n\t使用法: %s %s\n
932 Can't find Job %s; Not %s\n
933 killed
934 rejuvenated
935 uprocessC(%s, 
936 %s);\n
937 Can't stat file (%s),
938  errno (%d) -- skip it!\n
939 Can't open file (%s), 
940 errno=%d -- skip it!\n
941 %-12s  %2.2d/%2.2d-%2.2d:%2.2d:%2.2d  (POLL)\n
942 short line (%s)\n
943 type (%s), 
944 file1 (%s)
945 file2 (%s)
946 file3 (%s)
947 user (%s)
948 %-12s  %2.2d/%2.2d-%2.2d:%2.2d  
949 %-12s  %2.2d/%2.2d-%2.2d:%2.2d  
950 Can't read %s, 
951 errno=%d -- skip it!\n
952 ????\n
953 kprocessC(%s, 
954 %s);\n
955 Can't stat:%s, errno (%d)--can't %s it!\n
956 kill
957 rejuvenate
958 Can't read:%s, errno (%d)--can't %s it!\n
959 kill
960 rejuvenate
961 Bad format:%s, errno (%d)--can't %s it!\n
962 kill
963 rejuvenate
964 type (%s), 
965 file1 (%s)
966 file2 (%s)
967 file3 (%s)
968 user (%s)
969 Not owner or root - can't %s job %s\n
970 kill
971 rejuvenate
972 Remove %s\n
973 Error: Can't %s, File ( %s), errno (%d)\n
974 kill
975 rejuvenate
976 Remove %s\n
977 Error: Can't %s, File ( %s), errno (%d)\n
978 kill
979 rejuvenate
980 Job: %s successfully %s\n
981 killed
982 rejuvenated
983 machine(%s), 
984 m-M=%d\n
987 WARNING: Table Overflow--output not complete\n
988 %3dC
989 %4dX
990 %2.2d/%2.2d-%2.2d:%2.2d 
991 Locked 
992 Retry: %d:%2.2d
993  Count: %d
994 lckpid() - entered\n
995 lockdir (%s)\n
996 f (%s)\n
997 ????\n
1000 uusub: cannot open 
1001 使用法:uusub -a* -d* -c* -u* -r -l-f\n
1002 Flush file %s\n
1003 Delete system %s from subnetwork\n
1004 Add system %s to subnetwork\n
1005 system %s is added\n
1007 sysname\tsfile\tsbyte\trfile\trbyte\n
1008 %s\t%d\t%ld\t%d\t%ld\n
1009 sysname\t#call\t#ok\tlatest-oktime\t#noacu\t#login
1010 \t#nack\t#other\n
1011 %s\t%d\t%d
1012 \t(%d/%d-%d:%2.2d)\t
1013 %d\t%d\t%d\t%d\n
1014 enter edit, flag: %d\n
1016 %s is retained\n
1018 Uusub is not implemented on this system\n
1019  Flush file %s\n
1020  l.sys: %s\n
1022  Rmt: %s 
1023  s_r: %s
1024  bytes: %ld 
1025  oldtick: %ld\n
1026  %s inside the time\n
1027 %s is written\n
1033 [-aNAME] [-b] [-c] [-C] [-j] [-gGRADE] [-n] [-p] [-r] [-sFILE] [-xNUM] [-z] command-string
1034 \t使用法: %s %s\n
1036 START
1037 arg - %s:
1038 arg - %s\n
1039 No spool directory - %s - get help\n
1040 xsys %s\n
1041 bad system name: %s\n
1042 User %s\n
1043 cfile = %s\n
1044 rxfile = %s\n
1050 prm - %s\n
1051 syspart -> %s, 
1052 rest -> %s, 
1053 ret -> %d\n
1054 syspart -> %s\n
1055 bad system name: %s\n
1056 rest %s\n
1057 can't get file status %s\n
1058 permission denied %s\n
1059 can't copy %s\n
1061 uux failed. code %d\n
1062 exit code %d\n
1064 [-xDEGUG] [-sSYSTEM]
1066 \t使用法: %s %s\n
1067 \t使用法: %s %s\n
1068 \n\n** START **\n
1070 No limitfile - %s\n
1071 Uuxqt limit %d -- 
1072 found %d -- 
1073 exiting\n
1074 continuing\n
1075 User - %s\n
1076 process %s\n
1080 stashing %s\n
1081 xsort:  first was %s\n
1082 xsort:  first is %s\n
1083 xget: returning %s\n
1084 gt_Xfile got %s\n
1085 rm_Xfiles: can't read %s\n
1086 mv_Xfiles: can't read %s\n
1088 unmv_Xfiles: can't read %s\n
1090 prm='%s'\n
1091 fullname: %s\n
1093 retosndr %s, 
1095 \n\t===== stderr was =====\n
1096 \n\t===== well, i tried =====\n
1097 _Xfile - %s\n
1098 badfile - in: %s\n
1099 badfile - out: %s\n
1100 fin - %s, 
1101 fout - %s, 
1102 sysout - %s, 
1103 user - %s\n
1104 incmd - %s\n
1110 bad command %s\n
1112 cmd %s\n
1113 full cmd: %s\n
