default:
	: 
install:
	mkdir -p ../../../Filesets.sl/INSTALL/etc
	! cp disktab.wsio ../../../Filesets.sl/INSTALL/etc/disktab
	! chmog 444 bin bin ../../../Filesets.sl/INSTALL/etc/disktab
	! chmog 555 bin bin ../../../Filesets.sl/INSTALL/etc
	! chmog 555 bin bin ../../../Filesets.sl/INSTALL
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/UX-CORE/etc/newconfig
	! cp disktab.wsio ../../../Filesets.sl/UX-CORE/etc/newconfig/disktab
	! chmog 444 bin bin ../../../Filesets.sl/UX-CORE/etc/newconfig/disktab
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE/etc/newconfig
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE/etc
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE
	! chmog 555 bin bin ../../../Filesets.sl
