#	$Header: makefile,v 1.10.109.1 91/11/21 12:02:03 kcs Exp $
#
#	Makefile for installing sample network link product configuration files
#

CONFIGFILES =	networks protocols services hosts inetd.conf inetd.sec

all sall:

prod:

install: ${CONFIGFILES}
	test "${INS}" && ${INS} ${?}

${CONFIGFILES}:

trace:

debug:

clean:

clobber:
