$set 1
1 只允许选 -F 与 -f 选项之一\n
2 只允许选 -F 与 -f 选项之一\n
3 只允许选 -P 与 -p 选项之一\n
4 只允许选 -P 与 -p 选项之一\n
5 mark_ev(%d) 失败\n
6 '%c': 缺少 event 参数\n
7 未知event: %s \n
8 mark_ev(%d) 失败\n
9 mark_sc(%d) 失败\n
10 '%c': 系统调用缺少参数\n
11 未知系统调用: %s\n
12 mark_sc(%d) 失败 \n
13 '%c': 未知的选择项\n
21 非超级用户。\n
22 audswitch(AUD_SUSPEND) 失败: %s\n
23 mark_ev(%d) 失败\n
24 未知参数: %s\n
25 show_audit() 失败\n
26 set_audit() 失败\n
31 mark_sc(%d) 失败\n
41 audwrite(%s) 失败: %s\n
42 getevent() 失败: %s\n
43 set_event(%s) 失败 \n
44 set_syscall(%d) 失败\n
45 audwrite(%s) 失败: %s\n
46 setevent() 失败: %s\n 
51 audwrite(%s) 失败: %s\n 
52 getevent() 失败: %s\n 
53 show_event(%s) 失败\n 
61 用法: %s
