$set 1
1 用法: audomon [-p fss] [-t sp_freq] [-w warning] [-v] [-o output]\n
2 audomon: fss 是个整数 > 0 和 < 100\n
3 audomon: sp_frep(minutes)是个正实数\n
4 audomon: 警告 正整数 <= 100\n
5 审计文件的文件系统有 %d%% 的剩余空间! \n
6 转换至备份文件的尝试失败。\n
7 此时必须指定一个备份文件 !\n
8 当前的审计文件大小是 %ld 千字节!!!\n
9 转换至备份文件的尝试失败。\n
10 审计文件接近 FreeSpaceSwitch 点。\n
11 文件系统的剩余空间 = %d%%。\n
12 审计文件接近 FreeSpaceSwitch 点。\n
13 当前的审计文件大小 = %ld 千字节。\n
14 审计文件损坏: 不能打开/读\n
15 审计控制文件 - %s !\n
16 审计系统损坏: 找不到当前文件\n
17 审计文件, %s, 在控制文件中, %s。\n
18 不能得到当前/下一个审计文件 -\n
20 audomon: 您不能访问审计系统。\n
24 audomon: 不能 stat 当前审计文件。\n
26 audomon: 不能写进输出文件。\n
27 audomon: 不能 stat 当前审计文件系统。\n
