$set 1
1 用法:\tcp [-f|-i] [-p] 源文件 目标文件\n\tcp [-f|-i] [-p] 源文件 ... 目标目录\n\tcp [-f|-i] [-p] -R|-r 源目录 ... 目标目录\n
2 cp: 不能断开联接 %s: 
3 cp: 不能存取 %s:
4 cp: <%s> 目录, 需要 "-R" 选项。\n
5 cp: %s/%s: 名字太长\n
6 cp: %s 和 %s 相同\n
7 cp: %s: 不是目录\n
9 cp: 不能创建 %s: 
10 cp: 打不开
11 cp: 不能创建%s: 
12 cp: 错误地拷贝至 %s: 
13 cp: 不能关闭 %s: 
14 cp: 不能对 %s 设置权限位: 
15 cp: %s/%s: 名字太长。\n
16 cp: 不能 mkrnod 
17 cp: 不能 symlink 
18 cp: 不能 readlink 
19 cp: utime 失败 %s:
20 cp: chown 失败 %s:
21 警告: 跳过的插座: %s\n
22 cp: 警告: 不能对 %s 做 cpacl\n
23 cp: 警告: 不能对 %s 做 cpacl\n
24 联接失败
25 覆盖 %s?
26 cp: %s 不是一个目录\n
27 cp: 不能在 %s 中存取 ACL: 
28 cp: 不能分配 %d 个记录 ACL(为 %s):
29 cp: 不能在 %s 中读 ACL: 
