$set 1
1 用法: find path-list [predicate-list]\n
2 find: 不能获得 'pwd'\n
3 find: 语法分析错误\n
4 find: 丢失联接\n
5 find: 操作数跟着操作数\n
6 find: 找不到 - 用户 %s\n
7 find: 找不到 - 组 %s\n
8 find: 不能创建 %s\n
9 find: 不能存取 %s\n
10 find: 非法选项%s\n
11 find: 不完整语句\n
14 find: 不能 stat %s\n
15 find: 不能 %s %s\n
16 打不开 /dev/tty 提示其它媒介\n
17 find: 不能写入 %s: %s\n 
19 如您想继续, 准备好后键入设备/文件名\n
20 用户对下一个设备文件键入了一个空名字\n
21 find: 打不开 %s: %s\n
22 用户打开文件 %s 继续\n
23 find: 非法 -type %s \n
24 find: 非法 -inum 值 %s\n
25 find: %s 需要一个变量\n
26 find: %s 不能用 ';' 结尾\n
27 find: %s 必须指定运行一个命令\n
28 find: 非法模式 %s\n
40 入口超过16个: 
41 在短格式中, 入口不能以 "(" 开始: 
42 在短格式中, 入口不能以 ")" 结束: 
43 在入口用户名不以点结束: 
44 在入口组名结束不正确: 
45 在入口用户名空: 
46 在入口组名空: 
47 在入口非法用户名: 
48 在入口非法组名: 
49 在入口非法方式: 
51 未知错误, 出自 strtoaclpatt( ): 
55 find: 
56 find: 非法文件系统类型 %s\n
57 打开
58 搜索
59 find: 没有找到 - 设备 %s\n
60 find: 不能 chdir 返回到 %s\n
61 find: 对同一文件不能同时使用 -ncpio 和 -cpio\n
62 find: cpio 输入输出错误 --
63 find: %s 创建一个循环\n
64 没有错误\n
65 内存溢出\n
66 文件类型未知\n
67 内部缓冲区错误\n
68 文件改变了大小\n
69 未知错误 (CPIO_%d)\n
