$set 1
1 grep  [-E|-F] [-cbilnqsvx] [-e expression [-e expression] ... | -f file]\n [expression] [file ...]\n egrep [-cbilnqsvx] [-e expression [-e expression] ... | -f file]\n [expression] [file ...]\n fgrep [-cbilnqsvx] [-e expression [-e expression] ... | -f file]\n [expression] [file ...]
2 %s: 不能打开 %s\n
3 用法:\n %s\n
4 %s: 不能打开 %s\n
5 %s: RE 错误 %d:
101 未知regexp错误码!!
102 引用非法冲突元
103 模式中尾随\\
104 模式中发现\\n
105 \\( \\) 对或 ( ) 嵌套过深
106 在 \\digit 中数非法或出界
107 [ ] 不平衡
108 \\ ( \\) 或 ( ) 不平衡。
109 \\{ \\} 不平衡
110 在 [ - ] 表达式中有非法的冲突端点.
111 正则表达式溢出
112 在 \\{ \\} 结构中数太大
113 在 \\{ \\} 结构中数非法
114 在 \\{ \\} 结构中多于两个的数
115 在 \\{ \\} 中第一个数大于第二个
116 命名字符类非法
117 未记住搜索串
118 在非法位置有重复操作符
119 指定空表达式
