$set 1
1 不能设置 LC_COLLATE\n
2 不能设置 LC_CTYPE\n
3 不能重新打开 stdin\n
4 用法:\tlocaledef [-c] [-f charmap_file] [-i input_file] locale_name\n
5 或\tlocaledef -d [-o format] locale_name\n
6 或\tlocaledef -n input_file\n
7 打不开 'debug' 文件\n
9 打不开输入文件 %s\n
10 未指定 'langname'\n
11 未指定 'langid'\n
12 指定的 'langname' 和 'langid' 冲突\n
13 指定的 'isfirst' 和 'byte_chars' 冲突\n
14 警告: 指定的顺序被忽略\n
15 LC_ALL 超过最大允许值\n
16 LC_MESSAGES 超过最大允许值\n
17 LC_COLLATE 超过最大允许值\n
18 LC_CTYPE 超过最大允许值\n
19 LC_MONETARY 超过最大允许值\n
20 LC_NUMERIC 超过最大允许值\n
21 LC_TIME 超过最大允许值\n
22 不能生成 'locale.inf' 文件\n
23 localedef 错误: 在第 %d 行有非法的关键字\n
25 localedef 错误: 在第 %d 行有非法的字符\n
26 localedef 错误: 在第 %d 行有非法的语句\n
27 localedef 错误: 在第 %d 行有非法的表达式\n
28 localedef 错误: 在第 %d 行有非法的范围\n
29 localedef 错误: 在第 %d 行有非法的语言名称长度\n
30 localedef 错误: 在第 %d 行有非法的语言标识号\n
31 localedef 错误: 在第 %d 行的语言名称中有非法的语言名称长度\n
32 localedef 错误: 在第 %d 行的语言名称中有非法的域名长度\n
33 localedef 错误: 在第 %d 行的语言名称中有非法的代码集名长度\n
34 localedef 错误: 在第 %d 行有非法的版本字串长度\n
36 localedef 错误: 在第 %d 行有非法的字符代码\n
37 localedef 错误: 在第 %d 行有非法的 isfirst 字符代码\n
38 localedef 错误: 在第 %d 行有非法的 issecond 字符代码\n
39 localedef 错误: 非法的 code_scheme 名长度 %d\n
40 localedef 错误: 非法的 code_scheme 名 %d\n
41 localedef 错误: 非法的 cswidth 字串长度 %d\n
42 localedef 错误: 非法的 cswidth 字串格式 %d\n
43 localedef 错误: 非法的 langinfo 字串长度 %d\n
44 localedef 错误: 非法的货币字串长度 %d\n
45 localedef 错误: 非法的数字串长度 %d\n
46 localedef 错误: 非法的修饰字串长度 %d\n
47 localedef 错误: malloc() 失败\n
48 localedef 错误: 优先级排队溢出 \n
49 localedef 错误: 是/否的第一个字符相同 %d\n
50 localedef 错误: 非法的 era 字串长度 %d\n
51 localedef 错误: 非法的 era 字串格式 %d\n
52 localedef 错误: 指定了太多的 era 字串 %d\n
53 localedef 错误: 未找到指定符号 %d\n
58 localedef 错误: charmap 文件找不到\n
60 localedef 错误: 符号重复 %d\n
63 localedef 错误: 在第 %d 行指定义的值超过了 COLL_WEIGHTS_MAX 的限额\n
68 localedef 警告: 未找到指定的符号 %d\n
72 localedef 警告: 不支持的关键字 %d\n
73 localedef 警告: 不正确的 ctype 初始化 - 已做修正\n
74 指定的 'langname' 和 'langid' 冲突
75 警告: 用户定义的语言的 langid 范围应在 901 至 999 之间\n
76 用户定义的语言的 langid 范围应在 901 至 999 之间
77 指定的 'langname' 和 'langid' 冲突
78 读出错误文件: 
79 不能 lseek 文件: 
80 不能打开临时文件 %s\n
81 错误中断 charmap 文件\n
82 locale 错误: 在 LC_COLLATE 种类中非法行: %d\n
