$set 1
1 mail: 不能写入 %s\n
2 用法: mail [+] [-epqr] [-f 文件]\n
3       mail [-dt] 人名\n
4 mial: 不能分配 hmbox
5 mail: 不能分配 hmbox
6 mail: 权限不够!\n
7 mail: 打不开 %s\n
8 无邮件。\n
9 检查邮件文件的属性和组标志。\n
10 您的邮作正被转发至
11 %s
12 而且您的邮箱中还含有杂物\n
13 mail: 打不开 %s\n
14 用法\n
15 q\t\t退出\n
16 x\t\t退出, 不改动邮件\n
17 p\t\t打印\n
18 s [文件]\t存储 (缺省邮箱)\n
19 w [文件]\t同样无头栏\n
20 -\t\t打印前一个\n
21 d\t\t删除\n
22 +\t\t下一个 (不删除)\n
23 m 用户\t发送至用户\n
24 ! 命令\t\t执行命令\n
25 无效命令\n
26 mail: 不能附加至 %s\n
27 mail: 不能存储邮件\n
28 无效命令\n
29 %s 无值或没用 export 命令。\n
30 !\n
31 mail: 不能重复写 %s\n
33 mail: 不能重复读 %s\n
34 copyback:邮件太多\n
35 mail: 不能更新 %s\n
36 mail: 不能更新 %s\n
37 mail: 不能更新 %s\n
38 mail: 不能复制回邮件\n
39 已收到新邮件\n
40 \007警告: 邮件太多, 邮件连接溢出\n\n
42 mail: 不能重读 %s\n
43 mail: 不能分配内存\n
44 mail: 不能生成 %s\n
45 邮件存入 %s\n
46 邮件存入 %s\n
47 mail: 不能存入死信\n
48 头栏行太长\n
49 空名\n
50 空名\n
51 mail: 不能对 mail 命令用管道功能\n
52 无限制的转发\n
53 mail: 不能送至 %s\n
54 mail: 不能附加至 %s\n
55 mail: 不能附加至 %s\n
56 mail: 不能附加至 %s\n
57 mail: 错误符号 %d\n
58 mail: %s 不能加锁 (试了 %d 次)\n
59 mail: 不能生成 %s (试了 %d 次)\n
