$set 1
1 tar: 不能产生临时文件 (%s)\n
2 非法块长度 (最大 %d)\n
3 tar: %c: 不认识的选项\n
4 tar: 块长度 %d 太大不能得到内存\n
5 只能产生标准输出文档\n
6 tar: 不能打开 %s\n
7 tar: 用法 tar [-]{txruc}[ONvVwAfblHhm{op}][0-7[lmh]] [磁带文件] [块长度] 文件1  文件2...\n
8 tar: 用法 tar [-]{txruc}[ONvVwfblHhm{op}][0-7[lmh]] [磁带文件] [块长度] 文件1  文件2...\n
9 tar: 用法 tar [-]{txruc}[ONvVwAfblhm{op}][0-7[lmh]] [磁带文件] [块长度] 文件1  文件2...\n
10 tar: 用法 tar [-]{txruc}[ONvVwfblhm{op}][0-7[lmh]] [磁带文件] [块长度] 文件1 文件2...\n
11 tar: 用法 tar [-]{txruc}[ONvVwAfblm{op}][0-7[lmh]] [磁带文件] [块长度] 文件1 文件2...\n
12 tar: 用法 tar [-]{txruc}[ONvVwfblm{op}][0-7[lmh] [磁带文件] [块长度] 文件1 文件2...\n
13 企图产生没有文件的档案, 未转储\n
14 失去指向 %s 的连接\n
15 目录校验和错误\n
16 tar: 不能 stat %s, 没有转储\n
17 <%s>可选择的acl表项没有转储\n
18 tar: %s 目录读出错误\n
19 tar: %s 符号连接表太长\n
20 tar: 不能读符号连接表
21 %1$s 的符号连接指向 %2$s\n
22 %s 0 块\n
23 tar: %s 不能打开文件\n
24 %1$s 连接指向 %2$s\n
25 内存溢出, 连接信息丢失\n
26 %1$s %2$ld 块\n
27 %s: 文件改变了大小\n
28 tar: %s 不是一个文件, 没有转储\n
29 tar: %s: 符号连接失败:
30 x %1$s 符号连接到 %2$s\n
31 %s: 不能连接\n
32 %1$s 连接到 %2$s\n
33 tar: %s 不能产生字符设备\n
34 x %s, 0 字节, 0 块, 字符设备\n
35 tar: %s 不能产生块设备\n
36 x%s, 0 字节, 0 块, 字符设备\n
37 tar: %s 不能产生先进先出\n
38 x %s, 0 字节, 0 块, 先进先出\n
39 tar: %s 当成正规文件产生\n
40 tar: %s - 不能产生\n
41 x %1$s, %2$ld 字节, %3$ld 磁带块\n
42 tar: %s: HELP-抽取写错误\n
43 tar: chmod 失败\n
44 tar: chown 失败\n
45 连接到 %s
46 符号连接到 %s
47 %b %2d %H:%M %Y
48 tar: 不能从 uid %d 得到用户名\n
49 tar: 不能从 gid %d 得到组名\n
51 tar: pwd 失败\n
52 tar: pwd 超出了深度限制!\n
53 tar: 磁带块长度错误\n
54 tar: 磁带读错误\n
55 tar: 块长度 = 0; 打断管道吗?\n
56 tar: 块大小 = %d\n
57 tar: 错误! 块长度已经改变\n
58 tar: 写带错误\n
59 tar: %s 路径名太长\n
60 tar: %s 前缀太长\n
61 tar: %s 文件名太长\n
62 %s: 文件名太长\n
63 tar: 磁带错误 (%d)\n
64 tar: 新卷出错\n
65 不能打开 /dev/tty 来要求更多媒介\n
66 tar: 磁带结束\n
67 tar: 继续, 当准备好时键入 device/file; 输入空串则退出\n
68 用户为下一个设备文件输入了一个空串名字\n
69 tar: 不能打开 %s\n
70 用户打开了文件 %s 继续\n
71 tar: %s 不能产生目录\n
72 tar: 指向名字的%s连接太长\n
73 tar: %s: 不能存取文件\n
74 tar: 超出内存。不能发现符号连接循环\n
75 tar: 发现符号连接循环, tar 中断\n
76 tar: 目录不能改变为 '%s'\n
77 tar: 跳过路径 '%s'\n
78 tar: 选项不支持 QIC 设备 %s\n
79 tar: 不能关闭 %s\n
80 tar: 不能通过 NFS 读/写\n
