$set 1
3 处理完成的文件: %s\n
5 gtwvec: dir %s\n
6         return - %d\n
7 insert(%s) 
8 插入 %s
9 在 %d\n
10 内部呼叫者类型 %s\n
11 mlock %s 失败\n
12 mlock %s 成功\n
13 一般性的打开超时\n
16 一般性的打开 (%d) 失败, 错误号 = %d\n
19 在文件 Dialers 中没有找到 %s\n
22 调用 gdial(%s)\n
23 dkcall(%s)\n
27 tcpdial 主机 %s, 
28 端口 %d\n
29 没有插座 (socket): %s\n
31 没有插座 (socket), 错误号 %d\n
34 超时 tcpopen\n
37 系列: %d\n
38 端口: %d\n
39 地址: %08x\n
40 连接失败: %s\n
42 连接失败, 错误号 %d\n
45 unetdial 主机 %s
46 端口 %d\n
47 tcpopen 失败: 错误号 %d\n
48 打开失败 %s\n
50 COM1 返回码 =%d\n
52 打开 sytek 超时\n
53 打开 2 失败 %s\n
54 mlock %s 失败\n
55 使用端口 %s
56 acu - %s, 
57 电话号码 %s\n
58 试 modem - %s, 
59 acu - %s, 
60 呼叫 %s:
61 成功\n
62 失败\n
63 打不开 %s\n 
64 %s 已打开\n
65 打开 modem 超时\n
66 拨号失败.子进程终止. \n
68 ACU 写错误 %d\n
69 使用程序拨号 %s\n
72 dcf 是 %d\n
73 Fork Stat %o\n
74 DN 写 %s\n 
75 超时
76 打不开 %s\n 
77 %s 已打开\n
78 打不开 %s\n 
79 dcf 是 %d\n
80 ACU 写错误 %d\n
81 ACU 写成功 %s\n
82 打开行 %s\n
83 失败
84 chdir(%s)\n
85 [-xNUM] [-r[0|1]] -sSYSTEM
88 %s 不在文件 Systems 中\n
89 \t用法: %s %s\n
90 没有指定 -s\n
91 这系统规定: -sMyname: %s,
92 cico.c: Myname - %s\n
93 cico.c: 登录用户 - %s\n
95 sys-%s\n
98 从 callcheck 返回: %s
109 现正与 %s 对话\n
112 %s - 失败\n 
113 %s - 失败\n 
114 登录成功: Systerm=%s\n
115 msg-%s\n
117 信息交换失败: %s\n
118  Rmtname %s,
119 作用 %s,
120 主设备
121 从设备
122 Ifn - %d
123 登录用户名 - %s\n
126 %s - 超时\n
127 启动
130 %s\n
133 cntrl - %d\n
138 ret 剩余行 - %d\n
139 退出代码 %d\n
140 对话结束: 状态 %s\n\n
141 失败
142 成功
143 TM_cnt: %d\n
145 用法: uuname [-l]\n
146 打不开文件 "%s"
293 *** TOP ***  -  role=%d
295 Wfile - %s,
296 Jobid = %s\n
301 请求: %s\n
305 失败: 不能存取\n
311 失败: 不能读%s\n  
314 请求: %s\n
318 失败: 不能存取--文件: %s\n
322 失败: 空间不够!\n
323 wrktype - %c\n
324 进程: msg - %s\n
326  请求:
329 HUP:
331 从设备 -- 切换原则 (%s)\n
332 TRUE
333 FALSE
335 SNDFILE:
344 msg - %s\n
345 远程请求: %s\n
346 从设备 -- 文件: %s\n
349 失败: 不能存取\n
351 chkpth ok Rmtname - %s\n
355 失败: 不能建立临时文件\n
361 ->PUBDIR %d\n
363 RCVFILE:
375 远程请求:%s\n
376 msg - %s\n
377 W_FILE1 - %s\n
382 失败: 不能存取\n
383 对登录用户名, 需要 OK -- %s\n
386 失败: 不能存取\n
387 chkpth  ok 登录用户名 - %s\n
391 失败: 打不开 %s\n
393 rmesg - '%c'
394 获取 %s\n
395 失败
398 获取 %s\n
401 获取 %s\n
402 wmesg '%c'
403 %s\n
404 mailopt %d
405 statfopt %d\n
413 STMES %s\n
417 Proto 启动 %c\n
418 Proto 启动 - 失败 %c\n
419 conn(%s)\n
420 getto ret %d\n
421 关闭电话呼叫者 (%d)\n
422 delock(%s)\n
423 调用失败: %s\n
424 需要 %s 型设备\n
425 所需设备没有找到\n
427 调用时间错误: %s\n
428 ProtoStr = %s\n
430 希望: (
431 获得\n
432 丢行错误号 - %d\n
435 已足够\n 
436 获得\n
437 超时\n
438 中断\n
439 EOT\n
440 sendthem (
441 延时\n
442 <NO CR>
443 <NO CR - MIDDLE IGNORED>\n
444 暂停\n
445 回送校验打开\n
446 回送校验关闭\n
447 中断\n
448 ^M
449 )\n
458 装满 %s\n
459 dturnon: ret=%d, 
460 Ofn=%d, 
461 错误号 =%d\n
462 ewrmsg 写错误\n
463 erdmsg 读错误\n
464 ewrdata 失败\n
465 ewrmsg 写 %d\n
466 ewrmsg ret %d\n
468 redblk msglen %d\n
469 erdblk ret %d\n
470 erdblk 失败\n
471 erdblk 读太多\n
472 <- %ld / %ld.%.3d secs
473 erdblk 超时\n
474 要求 %d
475 读失败\n
476 获得 %d\n
477 mkdir - %s\n
478 无法检查上层目录 %s
479 错误号 %d\n
480 无法改变上层目录 %s 属性
481 错误号 %d\n
483 无法改变上层 %s 属性\n
487 文件名非法 (%s).\n
489 输入 frdmsg:
490 总数检查: %04x\n
491 ack - '%c'\n
494 再试:\n
495 fqedata ret: %d\n
498 发送 ack: 'R'\n
499 再试:\n
500 发送 ack: 'Q'\n
501 发送 ack: 'G'\n
502 frddata ret: %d\n
503 \n 检验和: %04x\n
504 检验和错\n
505 数据损坏\n
506 gename(%c,
507 %s,
508 %c)\n
509 空 sys -> %s\n
510 文件 - %s\n
512 %s seq
513 现在 %x\n
514 : 非法的选择项 -- 
515 : 选择项需要一个参数 -- 
516 : 选择项需要一个参数 -- 
517 打开 %s\n
519 不能锁定 %s\n
520 承诺 %s
521 到 %s\n
522 imsg %s>
524 fixline(%d, 
525 %d)\n
527 fixline - direct\n
529 setline - %c\n
530 sytfixline - speed= %d\n
534 fixline(%d,
535 %d)\n
536 用法: %s -f script [-d] [-v]\n
537 %s 不认识
538 句法错误
539 句法: 希望数字串 
540 句法: 希望数字串 
546 缺少标号
547 错误或不可能
548 标号 %s 没有找到
550 %s 没有找到
551 希望数字
552 希望字符串
554 变元太多
555 希望标识
556 标识 "%s" 不认识
557 调用 logFind (名字: %s, 
558 rmtname: %s)\n
559 机器/登录不匹配
560 _Request (%s), 
561 TRUE
562 FALSE
563 _Switch (%s)
564 TRUE
565 FALSE
566 _CallBack (%s), 
567 TRUE
568 FALSE
569 _Myname (%s)
570 调用 mchFind (%s)\n
584 _Command %s\n
585 malloc() 错误\n
586 列表 (%s)
587 num=%d\n
588 打不开 %s\n
589 没有找到名字 (%s); 返回失败\n
590 打不开 %s\n
591 validateFind (%s) 失败\n
593 对于许可权, 选项(%s)非法\n
594 \n**************************************\n
595 ** 有关文件: %s 的许可权,选项非法\n
596 ***************************************\n   
597 cmdOK(%s, )\n
598 bname=%s\n
600 不是 cntl\n
601 alloc 的修改没有生效\n
602 pkcntl: RR/RJ: Connodata =%d\n
603 srj 没有完成\n
604 r 缺少 %d 需要 %d\n 
605 rcount = %d\n
606 xcount = %d\n
607 tries = %d\n
608 pkgetpack: Connodata=%d\n
609 rec h->cntl %o\n
610 标题错误 %o, 
611 h ->ccntl %o\n
612 状态 -
613 标题错误 %o\n
614 bp 空 %s\n
615 发送 %o\n
618 警告: %d\n
619 中止 %s\n
620 不能 unlink %s\n
621 不能锁 %s\n
622 打不开 %s 读\n
623 作业 %s 已删\n
624 作业 %s 没有找到\n
625 fp: %o\n
626 作业 %s 已完成\n
627 没有权限\n
629 shio - %s\n
630 状态  %d\n
634 重试时间 (%ld) 没有到\n 
636 进入 ub_set, 状态是: %d\n
637 Rmtname: %s\n
638 %s 的 ulockf 失败\n
639 %s 的 fopen 失败\n
640 在 ub_set name=Rmtname: %s\n
641 在 onelock() ulockf 失败\n
642 ulockf 文件 %s\n
643 文件已锁--不能读 (错误号 %d) -- 删除它!\n   
644 文件已锁--格式错误  -- 删除它!\n   
645 文件已锁--进程仍在执行 -- 不能删除它\n   
646 中止进程 (%d), 
647 返回 %d
648 -- 删去上锁的文件 (%s)\n
649 unlink() 中 ulockf 失败\n
650 ulockf 文件 %s\n
651 文件已锁--不能读 (错误号 %d) -- 删除它!\n   
652 -- 删去上锁的文件 (%s)\n
653 unlink() 中 ulockf 失败\n
657 连接(%s, 
658 %s)\n
660 [-v] [-xNUM]
661 \t 用法: %s %s\n
662 \t 用法: %s %s\n
663 *** uucheck: 检查所需的文件和目录\n
664 *** uucheck: 完成目录检查\n\n
665 *** uucheck: 检查 %s 文件\n
666 *** uucheck: 完成 %s 检查\n\n
667 ** %s \n\n 
668 MACHINE 阶段 (当我们主叫或执行其 uux 请求时)
669 LOGNAME 阶段 (当他们叫我们时) 
670 打不开 %s\n
671 系统登录的名义是:
672 \t我们将回叫他们。\n\n
673 当我们呼叫系统时:
674 \t我们%s他们请求文件。\n
675 允许
676 不允许
677 \t我们%s文件放入这次接通的发送队。\n 
678 将
679 不将
680 \t 他们可把文件发送至\n
681 \t     %s (缺省)\n
682 \t     %s\n
683 \t 除外\n
684 \t     %s\n
685 \t 他们可请求文件从\n
686 \t     %s (缺省)\n
687 \t     %s\n
688 \t 除外\n
689 \t     %s\n
690 \t 我用于对话的名字是 %s。\n
691 \t 用于对话的 PUBDIR 是 %s。\n
692 Machine(s):
693 \n可以执行下面命令:\n
694 permission.c 中软件错误\n
695 命令 (%s), 全名 (%s)\n
696 不认识标识符 %s\n
697 目录 %s 不可读\n
698 DEBUG# %s\n  
699 启动
700 不能把目录改到 %s\n
701 打开 %s 失败\n  
702 unlink 文件 %s\n
703 前缀: %s\n
704 chkpre 失败 -- 文件: %s\n
709 STM %d\n
710 [-oDAYS] [-mSTRING] [-Cdays] [-Wdays] [-Xdays] [-xLEVEL] [-sSYSTEM]
711 \t 用法: %s %s\n
712 任选项: CDWXo 需要的值 > O\n
713 \t 用法: %s %s\n
714 progname (%s): STARTED\n
715 Myname (%s), 
716 _Shortlocal (%s)\n
717 Days C.(%d), 
718 D.(%d), 
719 W.(%d), 
720 X.(%d), 
721 其它 (%d)\n
722 不能改目录 (%s): 错误号 (%d)\n
723 打不开 (%s): 错误号 (%d)\n
724 目录: %s\n
725 文件: %s\n
726 xprocess(%s), 
727 unlink(%s)\n
729 \n\t%s!%s -> %s!%s   (日期 %2.2d/%2.2d)\n\n 不能执行。
730 \n\t%s!%s  (日期 %2.2d/%2.2d)\n
731 \n\t%s!%s -> %s!%s   (日期 %2.2d/%2.2d)\n
732 cprocess(%s)\n
733 打不开文件 (%s), 
734 错误号 =%d -- 跳过它!\n  
735 dummly C. -- unlink(%s)\n
740 文本 (%s)\n
741 wprocess(%s)\n
742 打不开文件 (%s),
743 错误号=%d -- 跳过它!\n  
744 dummly C. -- 跳过(%s)\n
745 短行 (%s): 
746 非法的 D. -- 跳过(%s)\n
748 不能读 %s\n
749 retaddr (%s)\n
751 text (%s)\n
752 oprocess(%s), 
753 unlink(%s)\n
755 dDprocess(%s), 
756 unlink(%s)\n
758 dXprocess(%s), 
759   unlink(%s)\n
761 dMprocess(%s)\n
762   本地文件 %s: 
763   远程文件 %s: 
764 对用户 %s, 
765 对系统 %s
766 邮件传递, unlink(%s)\n 
768 dNprocess(%s)\n
769   本地文件 %s, 
770 unlink(%s)\n
772   远程文件 %s,  
773 执行 rnew(%s), 
774 unlink(%s)\n
776 打不开文件 (%s), 
777 错误号 =%d -- 跳过它!\n  
778 buf: %s\n
782 邮递 %s 至
785 发送邮件: %s\n
789 Rnews %s\n
791 送至 (%s)\n
792 buf: %s\n
794 不认识标识符 %s\n
796 启动
797 没有该目录 - %s - 寻求提示\n
798 UID %d, 
799 用户 %s\n
800 用法: uucp from ... to\n
801 系统错误: %s\n
802 sys2: %s, 
803 fwd2: %s, 
804 文件2: %s\n
805 系统错误: %s\n
806 句法错误: %s\n
807 sys1 - %s, 
808 文件1 - %s, 
809 Rmtname - %s\n
812 uucp 完全错误: 代码 %d\n
813 uucp 部分错误: %d 错误  
814  \n
815 s \n
816 都在 %d\n
817 不能获得文件状态 %s\n 拷贝失败\n
818 %s %s - 同一文件; 不能拷贝\n
819 没有权限\n
820 目录名非法 - %s\n
821 uucp 不能读 (%s) 方式 (%o)\n
822 使用 cp 命令\n
823 不能写文件 (%s) 方式 (%o)\n
824 本地拷贝:  uidxcp(%s, 
825 %s\n
826 不能拷贝文件 (%s) 错误号 %d\n
827 收到文件 - %d\n
831 发送文件 - %d\n
832 不能获得文件状态 %s\n
833 目录名非法 - %s\n
837 命令: %s\n
838 getty: 超时变元非法. "%s"\n
839 检查方式的用法: getty  -c gettydefs -like-file\n
840 打不开 %s\n
841 getty: 没有指定终止行。\n
842 getty: 找不到 %s (在 %s 中)。\n
843 getty: 打不开"%s", 错误号: %d\n
844 %.9s\r\n
845 getty: 在记录 %s 中指向下一个波特率的指针出错。\n
846 getty: 仍没找到 %s。\n
847 \r\n
848 getty: 打不开 "%s"。\n
849 项目太长。\n
850 \n**** 下一项 ****\n%s\n
851 id: %s\n
852 初始化标识位: \niflag- %o oflag- %o cflag- %o lflag- %o\n
853 最终标识位: \niflag- %o oflag- %o cflag- %o lflag- %o\n
854 信息: %s\n
855 下一个 id: %s\n
856 分析"%s"域的错误\n%s<--错误在这.\n
857 未定义: %s\n
861 用法: %s     [-m] [directories...]\n
862       %s -s  [-m] [directories...]\n
863       %s -k  [-m] [directories...]\n
864 打不开工作目录
865 打不开目录
866 目录太大
867 不能把目录改至
869 全部
870 孤立点: 
871 其它: 
872 \n
873 事务处理: 
874 \n%*s
875 %*s%-*s %s
876 \n
877 %*s\n
880 %s: 选择项非法 -- %c\n
881 %s: 选择项需要一个参数 -- %c\n
882 [-xNUM] [-uNUM]
883 \t用法: %s %s\n 
884 \t用法: %s %s\n 
885 progname (%s): 启动\n
886 无界限文件 - %s\n
887 Uusched 限制 %d -- 
888 发现%d -- 清除\n
889 继续\n
890 机器: %s, 
891 ccout: %d\n
892 执行 num=%d \n
893 num=%d,
894 snumber=%d,
895 Rmtname=%s\n
896 调用 exuucico(%s)\n
897 系统 %s 已锁, 或状态错误--跳过它\n
898 被叫的主机(%s)\n
900 ret=%d
901 错误号=%d\n
902 %-*.*s
903 %3.d Cmd%s
904    ---
905 %3.d Data
906    ---
907 %3.d Xqt%s
908    ---
909 锁住
910 对话
911 重试时间到
912 重试时间 %ld 秒%s
913 重试时间 %ld 分%s
914 计算: %d\n
915 陌生文件 (%s) 在 %s 中\n
916    \t(pid ??)
917    \t(pid ??)
918    \t(pid %d)
919 [-a] [-q] 或 [-m] 或 [-kJOB] 或 [-rJOB] 或 [-p]
920 [-sSYSTEM] [-uUSER]
921 \t用法: %s %s\n
922 或\n\t用法: %s %s\n
923 \t用法: %s %s\n
924 或\n\t用法: %s %s\n
925 progname (%s): 启动\n
926 用户 (User)=%s, 
927 登录用户名 (loginuser)=%s, 
928 Jobid=%s, 
929 Rmtname=%s\n
930 \t用法: %s %s\n
931 或\n\t用法: %s %s\n
932 没有找到 %s 作业; 不是 %s\n
933 终止
934 更新
935 uprocessC(%s, 
936 %s);\n
937 打不开文件 (%s), 
938 错误号 (%d) -- 跳过它!\n 
939 打不开文件 (%s), 
940 错误号 =%d -- 跳过它!\n 
941 %-12s %2.2d/%2.2d-%2.2d:%2.2d:%2.2d  (POLL)\n
942 短行 (%s)\n
943 类型 (%s), 
944 文件1(%s)
945 文件2(%s)
946 文件3(%s)
947 用户 (%s)
948 %-12s  %2.2d/%2.2d-%2.2d:%2.2d
949 %-12s  %2.2d/%2.2d-%2.2d:%2.2d
950 不能读 %s, 
951 错误号 =%d -- 跳过它!\n 
952 ????\n
953 kprocessC(%s, 
954 %s);\n
955 打不开: %s, 错误号 (%d)--不能 %s 它!\n
956 终止
957 更新
958 不能read: %s, 错误号 (%d)--不能 %s 它!\n
959 终止
960 更新
961 格式错误: %s, 错误号 (%d)--不能 %s 它!\n
962 终止
963 更新
964 类型 (%s), 
965 文件1 (%s)
966 文件2 (%s)
967 文件3 (%s)
968 用户 (%s)
969 非属主或 root - 不能 %s 作业 %s\n
970 终止
971 更新
972 删除 %s\n
973 错误: 不能 %s, 文件 ( %s), 错误号 (%d)\n 
974 终止
975 更新
976 删除 %s\n
977 错误: 不能 %s, 文件 ( %s), 错误号 (%d)\n 
978 终止
979 更新
980 作业: %s 成功 %s\n
981 已终止
982 已更新
983 machine(%s), 
984 m-M=%d\n
987 警告: 表溢出--输出未完\n
988 %3dC
989 %4dX
990 %2.2d/%2.2d-%2.2d:%2.2d
991 已锁
992 重试: %d:%2.2d
993 计算: %d
994 lckpid() - 进入\n
995 lockdir (%s)\n
996 f (%s)\n
997 ????\n
1000 uusub: 打不开
1001 用法: uusub -a* -d* -c* -u* -r -l-f\n
1002 删除文件 %s\n
1003 从子网络删除系统%s\n 
1004 向子网络增添系统%s\n 
1005 已加入系统 %s \n
1007 sysname\tsfile\tsbyte\trfile\trbyte\n
1008 %s\t%d\t%ld\t%d\t%ld\n
1009 sysname\t#call\t#ok\tlatest-oktime\t#noacu\t#login
1010 \t#nack\t#其它\n
1011 %s\t%d\t%d
1012 \t(%d/%d-%d:%2.2d)\t
1013 %d\t%d\t%d\t%d\n
1014 进入编缉, 标识位: %d\n
1016 %s 已保留\n
1018 Uusub 没有在本系统运行\n
1019 删除文件 %s\n
1020 l.sys: %s\n
1022 Rmt: %s
1023 s_r: %s
1024 字节: %ld
1025 oldtick: %ld\n
1026 %s 在时间内\n  
1027 %s 已写\n
1033 [-aNAME] [-b] [-c] [-C] [-j] [-gGRADE] [-n] [-p] [-r] [-sFILE] [-xNUM] [-z] 命令串
1034 \t用法: %s %s\n
1036 启动
1037 参数 - %s: 
1038 参数 - %s\n
1039 没有 spool 目录 - %s - 寻求帮助\n
1040 xsys %s\n
1041 系统名非法: %s\n
1042 用户 %s\n
1043 cfile=%s\n
1044 rxfile=%s\n
1050 prm - %s\n
1051 syspart -> %s, 
1052 rest -> %s, 
1053 ret -> %d\n
1054 syspart -> %s\n
1055 系统名非法: %s\n
1056 rest %s\n, 
1057 不能获得文件状态  %s\n
1058 权限不够 %s\n
1059 不能拷贝 %s\n
1061 uux 失败, 代码 %d\n 
1062 退出代码 %d\n
1064 [-xDEGUG] [-sSYSTEM]
1066 \t用法: %s %s\n
1067 \t用法: %s %s\n
1068 \n\n** 启动 **\n
1070 无界限文件 - %s\n
1071 Uuxqt 限制 %d --
1072 发现 %d --
1073 正在退出\n
1074 继续\n
1075 用户 - %s\n
1076 进程 %s\n
1080 终止 %s\n
1081 xsort: 第一个曾是 %s\n
1082 xsort: 第一个是 %s\n
1083 xget: 返回 %s\n
1084 gt_Xfile 得到 %s\n
1085 rm_Xfiles: 不能读 %s\n
1086 mv_Xfiles: 不能读 %s\n
1088 unmv_Xfiles: 不能读 %s\n
1090 prm='%s'\n
1091 全名: %s\n
1093 retosndr %s, 
1095 \n\t===== stderr 是 =====\n
1096 \n\t===== 好, 我试了 =====\n
1097 _Xfile - %s\n
1098 输入文件错误 - in: %s\n
1099 输出文件错误 - out: %s\n
1100 fin - %s, 
1101 fout - %s, 
1102 sysout - %s, 
1103 用户 - %s\n
1104 incmd - %s\n
1110 非法命令 %s\n
1112 命令 %s\n
1113 完整的命令是: %s\n 
