$set 1
1 用法: %s -nstux [-|file] ...\n 
2 %s: 不能stat 标准输出\n
3 %s: 不能打开 %s\n
4 %s: 不能 stat %s\n
5 %s: 输入 %s是输出\n
6 %s: 关闭错误\n
7 %s: 关闭错误\n
8 %s: 输出错误\n
9 %s: state 1 非法数据 "%d"\n
10 %s: state 2 非法数据 "%d"\n
11 %s: state 2 非法数据 "%d"\n
12 %s: state 2 非法数据 "%d"\n
13 %s: state 2 非法数据 "%d"\n
14 %s: state 3 非法数据 "%d"\n
15 %s: state 3 非法数据 "%d"\n
16 %s: state 3 非法数据 "%d"\n
17 %s: state 3 非法数据 "%d"\n
18 %s: 从 state %d 非正常终止\n
