default:
	:

install:
	mkdir -p ../../../Filesets.sl/UX-CORE/etc/newconfig
	! cp tztab ../../../Filesets.sl/UX-CORE/etc/newconfig/tztab
	! chmog 444 bin bin ../../../Filesets.sl/UX-CORE/etc/newconfig/tztab
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE/etc/newconfig
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE/etc
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE
	! chmog 555 bin bin ../../../Filesets.sl
