default:
	: 

install:
	mkdir -p ../../../Filesets.sl/CMDS-MIN/etc/newconfig
	! cp csh.login ../../../Filesets.sl/CMDS-MIN/etc/newconfig/csh.login
	! chmog 444 bin bin ../../../Filesets.sl/CMDS-MIN/etc/newconfig/csh.login
	! chmog 555 bin bin ../../../Filesets.sl/CMDS-MIN/etc/newconfig
	! chmog 555 bin bin ../../../Filesets.sl/CMDS-MIN/etc
	! chmog 555 bin bin ../../../Filesets.sl/CMDS-MIN/
	! chmog 555 bin bin ../../../Filesets.sl/
