$set 1
1 %4h %2d %H:%M 19%a
2 ar: option `%c' erron≈e\n
3 ar: l'un des [%s] doit ¡tre sp≈cifi≈\n
4 ar: seul l'un des [%s] est admis\n
5 ar: impossible d'ouvrir %s\n
6 ar: impossible de cr≈er %s\n
7 ar: impossible de cr≈er le troisi…me fichier temporaire\n
8 ar: abi non admis avec q\n
9 ar: impossible d'ouvrir %s\n
10 ar: impossible de cr≈er fichier temporaire\n
11 ar: %s n'est pas en format archive\n
12 ar: impossible d'acc≈der » %s\n
13 ar: cr≈ation de %s\n
14 ar: impossible de cr≈er %s\n
15 ar: %s n'est pas en format archive\n
16 syntaxe: ar [%s][%s] [pos] archive fichiers ...\n
17 ar: %s n'existe pas\n
18 ar: %s introuvable\n
19 ar: impossible d'ouvrir %s\n
20 ar: cr≈ation de %s\n
21 ar: impossible de cr≈er %s\n
22 entr≈es acl optionnelles de %s non archiv≈es\n
23 ar: erreur interne lors de la cr≈ation de l'en-t¡te %s\n
24 ar: archivage erron≈ (%ld)\n
25 ar: en-t¡te erron≈ %s pour %s\n
26 ar: impossible de cr≈er le deuxi…me fichier temporaire\n
27 ar: erreur phase sur %s\n
28 erreur d'≈criture ar
