$set 1
1 votre shell d'ouverture n'est pas /bin/sh, impossible d'utiliser at
2 attention: les commandes sont ex≈cut≈es » partir de /bin/sh\n
3 impossible de passer au r≈pertoire at
4 impossible de vous d≈finir comme le propri≈taire de votre travail
5 impossible de cr≈er un travail pour vous
6 vous n'¡tes pas un utilisateur valide (aucune entr≈e dans /etc/passwd)
7 syntaxe correcte :\n\tat -ln\n\tn ≈tant un nombre
8 impossible de lire le r≈pertoire at
9 D≈sol≈, mais vous n'¡tes pas autoris≈ » utiliser at.
10 sp≈cification absente
11 cette heure est pass≈e
12 %s n'existe pas\n
13 vous n'¡tes pas propri≈taire de %s\n
14 nom de travail %s non valide\n
15 %s n'existe pas\n
16 vous n'¡tes pas propri≈taire de %s\n
17 ≈chec » l'ouverture de '%s', num≈ro de l'erreur=%d\n
18 trop tard
19 ce travail ne sera peut-¡tre pas ex≈cut≈ » l'heure fix≈e.\n
20 file d'attente pleine
21 aucun prototype
22 cron ne s'ex≈cute peut-¡tre pas - contactez l'administrateur de syst…me\n
23 erreur dans la file d'attente ouverte\n
24 erreur dans l'envoi du message\n
25 impossible d'utiliser la file d'attente c 
26 Syntaxe:\nat [-m][-f fichier][-qfile_d'att] heure [date][[next| +incr≈m] heures] travail\nat -r travail ...\nat -l [travail ...]\n
28 impossible d'ouvrir \'%s\'\n
29 Impossible d'≈tablir un conduit avec mail\n
30 At: travail %s » %.44s\n
32 utilisateur = %s\t%s\t%s\n
$set 2
1 impossible d'allouer %d octets d'espace\n
$set 3
1 midi
2 minuit
3 maintenant
4 aujourd'hui
5 demain
6 minute
7 minutes
8 heure
9 heures
10 jour
11 jours
12 semaine
13 semaines
14 mois
15 mois
16 ann≈e
17 ann≈es
18 suivant
21 sp≈cification de date erron≈e
22 sp≈cification d'heure erron≈e
23 zone heures non valide
24 date erron≈e
25 heure erron≈e
26 environnement NLS incorrect
27 l'argument date est ambigu
28 fichier de catalogue incorrect
