$set 1
1 les options -F et -f ne peuvent pas ¡tre utilis≈es simultan≈ment\n
2 les options -F et -f ne peuvent pas ¡tre utilis≈es simultan≈ment\n
3 les options -P et -p ne peuvent pas ¡tre utilis≈es simultan≈ment\n
4 les options -P et -p ne peuvent pas ¡tre utilis≈es simultan≈ment\n
5 ≈v≈nement marqu≈ (%d) a ≈chou≈\n
6 '%c': argument manquant d'≈v≈nement\n
7 ≈v≈nement inconnu: %s\n
8 ≈v≈nement marqu≈ (%d) a ≈chou≈\n
9 appel syst…me marqu≈ (%d) a ≈chou≈\n
10 '%c': argument de l'appel syst…me manquant\n
11 appel syst…me inconnu: %s\n
12 appel syst…me marqu≈ (%d) a ≈chou≈\n
13 '%c': option inconnue\n
21 N'est pas superutilisateur.\n
22 audswitch(AUD_SUSPEND) a ≈chou≈: %s\n
23 ≈v≈nement marqu≈ (%d) a ≈chou≈\n
24 argument inconnu: %s\n
25 show_audit() a ≈chou≈\n
26 set_audit() a ≈chou≈\n
31 appel syst…me marqu≈ (%d) a ≈chou≈\n
41 audwrite(%s) a ≈chou≈: %s\n
42 getevent() a ≈chou≈: %s\n
43 set_event(%s) a ≈chou≈\n
44 set_syscall(%d) a ≈chou≈\n
45 audwrite(%s) a ≈chou≈: %s\n
46 setevent() a ≈chou≈: %s\n
51 audwrite(%s) a ≈chou≈: %s\n
52 getevent() a ≈chou≈: %s\n
53 show_event(%s) a ≈chou≈\n
61 syntaxe: %s
