$set 1
1 audisp: vous n'avez pas les autorisations requises.\n
2 audisp: impossible de lire le fichier de v≈rification %s.\n
3 audisp: impossible d'utiliser simultan≈ment les options -p et -f.\n
4 audisp [ -u code util] [ -e nom ≈v≈n] [ -c app syst ]\n
5        [ -p ] [ -f ] [ -l idtty ] [ -t mmjjhhmm[aa] ]\n
6        [ -s mmjjhhmm[aa] ] nomfichier_audit ...\n
7 audisp: heure de d≈but incorrecte dans l'option -t.\n
8 audisp: heure d'arr¡t incorrecte dans l'option -s.\n
9 audisp: l'heure de d≈but est post≈rieure » l'heure d'arr¡t.\n
10 audisp: aucun code util sp≈cifi≈ n'est valide.\n
11 audisp: tous les noms tty sp≈cifi≈s sont non valides.\n
12 audisp: tous les noms d'≈v≈nements sp≈cifi≈s sont non valides.\n
13 audisp: impossible de passer au r≈pertoire /dev.\n
14 audisp: impossible d'ouvrir le r≈pertoire /dev.\n
15 \naudisp: enregistrement de v≈rification (audit) erron≈.\n
16 \naudisp: corps de l'enregistrement de v≈rification (audit) erron≈.\n
17 \naudisp: l'allocation de m≈moire (malloc) a ≈chou≈.\n
18 \naudisp: structure de l'indicateur de v≈rification erron≈e.\n
19 Remarque: # fichiers ouverts avec succ…s = %d.\n
20 audisp: impossible de se r≈f≈rer aux informations d'identification de pid.\n
21 audisp: la tentative d'auto-v≈rification a ≈chou≈.\n
22 HEURE       PID E  EVEN   PPID    AID   RUID   RGID   EUID   EGID TTY\n\n
23 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n
24      
25  
26 utilisateurs et id de v≈rification:\n
27 Tous les utilisateurs sont s≈lectionn≈s.\n
28 S≈lection des ≈v≈nements suivants:\n
29 Tous les ≈v≈nements sont s≈lectionn≈s.\n
30 ttys et ttydevs:\n
31 Tous les ttys sont s≈lectionn≈s.\n
32 S≈lection des ≈v≈nements r≈ussis seulement.\n
33 S≈lection des ≈v≈nements non r≈ussis seulement.\n
34 S≈lection des ≈v≈nements r≈ussis et non r≈ussis.\n
35 heure de d≈but :\n
36 heure d'arr¡t :\n
37 F 
38 S 
39 TEST AUTO-VERIFICATION: 
40 VALEUR_RETOURN‹E 1 = %d; 
41 VALEUR_RETOURN‹E 2 = %d
42 PARAM #%1d (int) = %ld\n
43 PARAM #%1d (unsigned long) = %lu\n
44 PARAM #%1d (long) = %ld\n
45 PARAM #%1d (char string) = 
46 PARAM #%1d (int) = %lu\n
47 PARAM #%1d (int array) = 
49 %d (addr family); %s\n
50 PARAM #%1d (chemin fichier) = %lu (noeudg);
51                        0x%08.8x (p≈riph);
52                        %lu (inoeud);
53          (chemin) = 
54 PARAM #%1d (fichier descript) = %lu (ip≈riph);\n
55                        %lu (inum)\n
56 PARAM #%1d (time struct) = %lu (secondes); %lu (micro-sec)\n
57 PARAM #%1d (fuseau horaire) = %d (min west); %d (heure d'≈t≈)\n
58 PARAM #%1d (adresse de char) = %lu\n
59 PARAM #%1d (cast long ptr) = %lu\n
60 PARAM #%1d (acl) = 
61 aucun acl enregistr≈\n
62 uid=%lu, 
63 gid=%lu, 
64 mode=%#o
65 PARAM #%1d (fichier descript) =\n
66 fd#%1d:   %lu (ip≈riph); %lu (inum)\n
67 En-t¡te du flot {\n
68    pid = %d\n
69    ppid = %d\n
70    aid = %ld\n
71    uid = %d\n
72    gid = %d\n
73    euid = %d\n
74    egid = %d\n
75    tty = %ld\n
76 Corps du flot =\n
77 /dev
78 /dev
79 syscon
80 systty
81 /dev
82 /dev
83 syscon
84 systty
85 ?????
86 %02d%02d%02d %02d:%02d:%02d
87 audisp:trop fichiers de v≈rif » g≈rer.(Certains sont peut-¡tre FTC).\n
88 [ 
89 ‹v≈nement=%s; 
90 Utilisateur=%s; 
91 Groupe r≈el=%s; 
92 Groupe effectif=%s; 
93 Origine=%s; 
94  ]
95 /dev/pty
96 /dev/pty
97 /dev/pty
98 /dev/pty
