$set 1
1 syntaxe: audomon [-p fss] [-t sp_freq] [-w avertissement] [-v] [-o sortie]\n
2 audomon: point saturation syst fich (fss) est un nombre entier > 0 et < 100\n
3 audomon: point de saturation sp_freq (minutes) est un nombre rÅel positif\n
4 audomon: l'avertissement est un nombre entier positif <= 100\n
5 espace disponible dans le systÉme de fichiers de vÅrification: %d%%\n
6 la tentative de passage au fichier de sauvegarde a ÅchouÅ.\n
7 PrÅcisez un fichier de sauvegarde È cette Åtape!\n
8 taille du fichier de vÅrification en cours : %ld kilo-octets!!!\n
9 la tentative de passage au fichier de sauvegarde a ÅchouÅ.\n
10 syst de vÅrif prÉs du point de saturation du systÉme de fichiers (FSS)\n
11 espace disponible dans le systÉme de fichiers = %d%%.\n
12 syst de vÅrif prÉs du point de saturation du fichier de vÅrification (AFS)\n
13 taille du fichier de vÅrification en cours = %ld kilo-octets!!!\n
14 systÉme de vÅrification altÅrÅ: impossible de l'ouvrir ou de le lire\n
15 fichier de contrÂle de vÅrification - %s !\n
16 systÉme de vÅrification altÅrÅ: impossible de trouver celui en cours\n
17 fichier de vÅrification, %s, dans le fichier de contrÂle, %s.\n
18 impossible d'obtenir les fichiers de vÅrification en cours/suivants -/n
20 audomon:vous n'avez pas accÉs au systÉme de vÅrification.\n
24 audomon:impossible de vÅrifier l'Åtat du fichier de vÅrification en cours.\n
26 audomon: impossible d'Åcrire dans le fichier de sortie.\n
27 audomon:impossible de vÅrifier l'Åtat du sys de fichiers de vÅrif en cours.\n
