$set 1
1 les options -a et -D ne peuvent pas ¡tre sp≈cifi≈es simultan≈ment\n
2 les options -A et -D ne peuvent pas ¡tre sp≈cifi≈es simultan≈ment\n
3 les options -A et -d ne peuvent pas ¡tre sp≈cifi≈es simultan≈ment\n
4 syntaxe: audusr [[-a utilisateur]...] [[- d utilisateur]...] [-AD]\n
5 fichier de mots de passe verrouill≈, mise » jour impossible\n
6 impossible de cr≈er le fichier de mots de passe temp,aucune mise » jour\n
7 impossible d'ouvrir le fichier de mots de passe /etc/passwd\n
8 impossible d'ouvrir le fichier de mots de passe temp /etc/ptmp\n
9 impossible d'≈crire dans le fichier de mots de passe temp /etc/ptmp\n
10 impossible de v≈rifier l'≈tat du fichier de mots de passe\n
11 un ou plusieurs utilisateurs entr≈s n'existent pas,aucune mise » jour\n
12 nombre d'utilisateurs entr≈s sup≈rieur au maximum admis\n
13 syst…me de v≈rification inchang≈, aucun utilisateur mis » jour\n
14 impossible d'interrompre la v≈rification de ce processus, sortie\n
15 vous n'avez pas acc…s au syst…me de v≈rification\n
16 syntaxe: audsys [-nf] [-c fichier -s Ko] [-x fichier -z Ko]\n
17 donn≈es en entr≈e non valides
18 attention: /.secure/etc/audnames n'existe pas\n
19 impossible d'ouvrir et de verrouiller /.secure/etc/audnames;\nv≈rifiez que le syst…me de v≈rif est install≈ correct,\n et que le r≈pert /.secure/etc existe, avant d'ex≈cuter cette commande\n
20 attention:impossible de lire /.secure/etc/audnames (erreur de formatage)\n
21 /.secure/etc/audnames cr≈≈ ou r≈par≈\n
22 impossible de cr≈er le fichier de v≈rification: %s\n
23 le fichier de v≈rification %s n'est pas vide\n
24 le fichier de v≈rification %s n'est pas un fichier ordinaire (ou FTC)\n
25 erreur interne\n
26 les options -n et -f ne peuvent pas ¡tre sp≈cifi≈es simultan≈ment\n
27 l'option -n doit ¡tre sp≈cifi≈e pour mettre la v≈rification en fonction\n
28 syst…me de v≈rification d≈j» en fonction, arguments entr≈s ignor≈s\n
29 les options -c et -s doivent toutes deux ¡tre sp≈cifi≈es\n
30 syst…me de v≈rification inchang≈\n
31 en cours
32 suivant
33 %s fichier de v≈rification %s\nexc…de l'AFS, s≈lectionnez-en un autre\n
34 %s fichier de v≈rif %s\nespace insuffisant dans syst de fichiers de v≈rif,\n pr≈cisez un autre fichier de v≈rification ou choisissez un AFS plus petit\n
35 %s fichier de v≈rif %s\nsyst…me de fichiers exc…de espace disponible minimal,\n pr≈cisez un fichier de v≈rification d'un autre syst…me de fichiers\n
36 fichier de v≈rification en cours inconnu:
37 fichier de v≈rification suivant inconnu:
38 l'option -c doit ¡tre sp≈cifi≈e pour la s≈lection d'un fichier en cours\n
39 l'option -x doit ¡tre sp≈cifi≈e pour s≈lectionner un fichier suivant\n
40 un fichier de v≈rification inconnu ≈tait utilis≈:
41 les options -x et -z doivent ¡tre sp≈cifi≈es simultan≈ment\n
42 le r≈pertoire %s du fichier de v≈rification n'existe pas\n
43 avertissement: fichier de v≈rification %s n'existe pas\n
44 fichiers de v≈rification:\n
45 fichier en cours:
46 fichier suivant:
47 ** inconnu **
48 fichier suivant: aucun\n
49 fichier suivant:        ** aucune donn≈e disponible **\n
50 fichier en cours:       ** aucune donn≈e disponible **\n
51 statistiques-   afs Ko  Ko utilis≈s dispon %%  sf Ko  Ko utilis≈s dispon%%\n
52 fichiers de v≈rification en cours et suivant d≈finis » la m¡me cible\n
53 syst…me de v≈rification lanc≈\n
54 syst…me de v≈rification arr¡t≈\n
55 fichier de v≈rification cr≈≈:
56 autres arguments entr≈s ne sont pas pris en compte\n
57 aucun fichier de v≈rification suivant disponible\n
58 le syst…me de v≈rification est pr≈sentement hors service\n
59 le syst…me de v≈rification est pr≈sentement en service\n
60 fich suivant d≈fini » <null> \naucun fich de v≈rif disponible dans syst…me\n
101 Tous les utilisateurs 
102 seront v≈rifi≈s\n
103 ne seront pas v≈rifi≈s\n
104 audsys: impossible d'arr¡ter la v≈rification - impossible de poursuivre
105 audsys: le fichier de v≈rification en cours devient
106 audsys: le fichier de v≈rification suivant devient
107 audsys: ce fichier de v≈rification n'est pas un fichier ordinaire vide\n
108 audsys: impossible de cr≈er le fichier de v≈rification
109 audsys: syst…me de v≈rification arr¡t≈\n
110 audsys: syst…me de v≈rification lanc≈\n
111 audsys: fichier de v≈rification en cours inconnu: 
112 audsys: fichier de v≈rification suivant inconnu: 
113 audsys: d≈finition du fichier suivant » NULL\n
114 audsys: fich en cours et fich suivant d≈fini au m¡me fichier (aucun suivant)\n
115 audsys: impossible d'ouvrir ou de verrouiller /.secure/etc/audnames\n
116 audsys: erreur interne inconnue\n
117 audsys: erreur interne: l'arr¡t a ≈chou≈\n
118 audsys: erreur interne: mise » jour de  /.secure/etc/audnames a ≈chou≈\n
119 audsys: erreur interne: impossible de mettre le noyau » jour\n
120 audsys: fichier /.secure/etc/audnames introuvable\n
121 audsys: fichier /.secure/etc/audnames rep≈r≈ est erron≈\n
122 audsys: fichier /.secure/etc/audnames corrig≈\n
123 audsys: impossible de r≈parer /.secure/etc/audnames\n
124 audsys: syst…me de v≈rification inchang≈\n
125 audsys: le fichier en cours est 
126 audsys: le fichier suivant est 
127 audsys: fichier de v≈rification attendu introuvable (supprim≈?)
