$set 1
1 rien ne va plus
2 r≈acheminement non valide
3 instruction non valide
4 cha—ne trop longue
5 caract…re de changement de ligne dans l'expression standard
6 caract…re de changement de ligne dans la classe de caract…res
7 caract…re de changement de ligne dans la cha—ne
8 awk: %s pr…s de la ligne %d\n
9 expression standard non valide
10 %s n'est pas un tableau
11 Syntaxe: awk [-f source | 'cmds'] [fichiers]
12 format de la cha—ne erron≈ dans l'expression printf(%s)
13 constitution d'un gros enregistrement `%.20s...'
14 impossible d'ouvrir %s
15 impossible d'ouvrir le fichier %s
16 impossible de d≈finir $0
17 division par z≈ro
18 format de l'≈l≈ment %.20s... trop long
19 variable inad≈quate %o: %s %s %g %o
20 op≈rateur arithm≈tique %d non valide
21 op≈rateur d'affectation %d non valide
22 type de fonction %d non valide
23 type de saut %d non valide
24 r≈f≈rence au tableau %s non valide
25 intruction %o non valide
26 arguments insuffisants dans l'expression printf(%s)
27 m≈moire insuffisante, %d octets requis
28 espace insuffisant pour la commande makesymtab
29 espace insuffisant pour la commande nodealloc
30 espace insuffisant pour la commande tostring dans %s
31 m≈moire temporaire insuffisante pour gettemp
32 l'instruction print a ≈chou≈
33 l'enregistrement  `%.20s...' contient trop de zones
34 l'enregistrement `%.20s...' est trop long
35 expression standard trop longue\n
36 cha—ne %.20s ... trop longue pour l'instruction print
37 d≈bordement de la table des r≈f≈rences symboliques » %s
38 trop de fichiers de sortie %d
39 tentative d'acc≈der » la zone %d
40 instruction break, continue ou next inattendue
41 op≈rateur bool≈en %d inconnu
42 op≈rateur relationnel %d inconnu
43 type %d inconnu dans cfoll
44 type %d inconnu dans first\n
45 type %d inconnu dans freetr
46 type %d inconnu dans penter\n
47 non restaur≈
48 non sauvegard≈
49 fichier restaur≈ vide
50 num≈ro d'enregistrement: %g\n
30001 erreur de syntaxe - impossible de sauvegarder
30002 d≈bordement de la pile yacc
30003 erreur de syntaxe
30004 impossible d'allouer de l'espace aux piles yacc
