$set 1
1  » la ligne source %d
2  le contexte est\n\t
3  dans la fonction %s
4  num≈ro de l'enregistrement en entr≈e:%g
5  ligne source num≈ro %d\n
6 %s argument hors domaine
7 %s est une fonction et non un tableau
8 %s est un tableau et non une fonction
9 %s n'est pas un tableau
10 %s ouvre trop de fichiers
11 %s hors plage
12 , fichier %s
13 Syntaxe: %s [-f source | 'cmds'] [fichiers]
14 \t%d: trop de %c\n
15 \t%d: absence de %c\n
16 \trop de %c\n
17 \absence de %c\n
18 `%s' est un nom de tableau et un nom de fonction
19 l'argument #%d de la fonction %s n'a pas ≈t≈ fourni
20 format de cha—ne erron≈ dans printf(%s)
21 rien ne va plus
22 constitution d'un gros enregistrement `%.20s...'
23 appel d'une fonction non d≈finie %s
24 impossible de %s %s; c'est une fonction.
25 impossible de %s %s; c'est un nom de tableau.
26 impossible d'ouvrir %s
27 impossible d'ouvrir le fichier %s
28 impossible d'utiliser la fonction %s comme argument
29 trop de zones cr≈≈es
30 division par z≈ro dans %=
31 division par z≈ro dans /=
32 division par z≈ro dans mod
33 division par z≈ro
34 expression standard vide
35 fichier de restauration vide\n
36 ) en trop
37 ] en trop
38 } en trop
39 exception de virgule flottante
40 format de l'≈l≈ment %.20s... trop long
41 espace insuffisant pour les structures type de la pile dans %s
42 variable inad≈quate %o: n=%s s="%s" f=%g t=%o
43 r≈sultat de la fonction gsub() %.20s trop gros
44 op≈rateur arithm≈tique %d non valide
45 op≈rateur d'affectation %d non valide
46 zone $(%s) non valide
47 type de fonction %d non valide
48 type de saut %d non valide
49 fonction imbriqu≈e non valide
50 ≈l≈ment principal non valide dans l'expression standard %s » %s
51 r≈acheminement non valide
52 r≈f≈rence au tableau %s non valide
53 instruction non valide
54 type de fonction split() non valide
55 la fonction index() n'admet pas les expressions standards
56 enregistrement en entr≈e `%.20s...' trop long
57 caract…re de changement de ligne dans la classe de caract…res %s...
58 caract…re de changement de ligne dans l'expression standard %.10s...
59 caract…re de changement de ligne dans la cha—ne %.10s...
60 l'expression next n'est pas valide dans une fonction
61 espace insuffisant pour la m≈moire temporaire
62 caract…re de fin manquant dans la classe de caract…res %s
63 arguments insuffisants dans printf(%s)
64 arguments insuffisants dans printf(%s)
65 non restaur≈\n
66 non sauvegard≈\n
67 nom de fichier nul dans l'expression print ou getline
68 espace insuffisant pour la commande makesymtab
69 espace insuffisant pour la commande nodealloc
70 espace insuffisant pour la commande rehash
71 espace insuffisant pour la commande tostring dans %s
72 l'enregistrement `%.20s...' contient trop de zones
73 expression standard trop grande: %s
74 l'instruction return n'a pas ≈t≈ entr≈e
75 cha—ne %.10s... trop longue
76 cha—ne trop longue
77 cha—ne ou expression standard %.10s... trop longue
78 r≈sultat de la fonction gsub() %.20s trop gros
79 d≈bordement de la table des r≈f≈rences symboliques » %s
80 erreur de syntaxe dans l'expression standard %s » %s
81 tentative d'acc≈der » la zone %d
82 instruction break ou next inattendue
83 instruction break, continue ou next inattendue
84 op≈rateur bool≈en %d inconnu
85 op≈rateur relationnel %d inconnu
86 type %d inconnu dans cfoll
87 type %d inconnu dans first\n
88 type %d inconnu dans freetr
89 type %d inconnu dans penter\n
90 vous ne pouvez pas d≈finir la fonction %s plus d'une fois
91 num≈ro de l'enregistrement en entr≈e:%g
92 , fichier %s
93  ligne source num≈ro %d\n
94  le contexte est\n\t
95  » la ligne source %d
96  dans la fonction %s
97 \absence de %c\n
98 \t%d: absence de %c\n
99 \trop de %c\n
100 \t%d: trop de %c\n
101 ordre de classement de l'≈l≈ment de r≈f≈rence non valide\n
102 \\ en-queue dans l'expression\n
103 \\n trouv≈s avant la fin de l'expression\n
104 niveau d'imbrication trop complexe\n
105 nombre dans \\digits non valide ou erron≈\n
106 [ ] manquant\n
107 \\( \\) ou ( ) manquant\n
108 \\{ \\} manquant\n
109 caract…re de fin non valide dans l'instruction de plage\n
110 m≈moire insuffisante pour l'expression compil≈e\n
111 nombre trop ≈lev≈ dans la d≈finition \\{ \\}\n
112 nombre non valide dans la d≈finition \\{ \\}\n
113 plus de deux nombres dans la d≈finition \\{ \\}\n
114 le premier nombre exc…de le deuxi…me dans la d≈finition \\{ \\}\n
115 type de classe de caract…res nomm≈ non valide\n
116 aucune cha—ne de recherche n'a ≈t≈ utilis≈e; impossible de rappeler\n
117 position de l'op≈rateur de duplication non valide\n
118 aucune expression dans ( ) ou sur l'un des c¬t≈s de la notation |\n
119 vous pouvez supprimer seulement tableau[≈l≈ment]\n
120 aucun programme donn≈\n
121 espace insuffisant pour l'appel des structures de pile %s\n
122 fonction %s appel≈e avec %d arguments, utilise seulement %d\n
123 fonction %s comprend %d arguments, la limite ≈tant %d\n
124 la liste les cellulles de m≈moire temporaire est bloqu≈e\n
125 cha—ne printf  %.40s... trop longue\n
126 espace insuffisant pour concat≈ner %.15s et %.15s\n
127 fonction atan2 n≈cessite deux arguments; valeur 1.0 retourn≈e\n
128 attention: la fonction comprend trop d'arguments\n
129 erreur e-s survenue dans %s\n
130 erreur e-s survenue en fermant %s\n
131 trop de fichiers programmes ouverts: Pass≈s outre: %s\n
