$set 1
2 chmod: impossible d'acc≈der » %s\n
3 chmod: impossible de changer 
4 chmod: mode non valide\n
5 chmod: option -A non admise dans le fichier ≈loign≈: %s\n
6 chmod: parcours %s impossible\n
7 chmod: %s n'est pas un r≈pertoire\n
101 Syntaxe: chmod [-A] [-R] [ugoa]+-=[rwxXstHugo][,...] fichier ...\n
102 Syntaxe: chmod [-R] [ugoa]+-=[rwxXstHugo][,...] fichier ...\n
103 Syntaxe: chmod [-A] [-R] [ugoa]+-=[rwxXstugo][,...] fichier ...\n
104 Syntaxe: chmod [-R] [ugoa]+-=[rwxXstugo][,...] fichier ...\n
