$set 1
1 cnodes: erreur d'allocation de m≈moire (malloc)\n
2 cnodes: erreur d'allocation de m≈moire (malloc)\n
3 Syntaxe: %s -aAnlmxC1sr [noms]\n
4 cnodes: impossible de lire /etc/clusterconf\n
5 cnodes: id_noeudg %d: cet ordinateur n'existe pas\n
6 cnodes: %s: cet ordinateur ne fait pas partie d'une grappe\n
7 cnodes: %s: cet ordinateur n'existe pas\n
8 cnodes: l'allocation de m≈moire (malloc) a ≈chou≈\n
9 <introuvable>
10 NOEUDG      ID PERMUTATION  SITE\n========== === =================
11 ID NOEUDG      PERMUTATION SITE\n== =========== ================
