$set 1
1 Syntaxe: cp [-f|-i] [-p] fichier_source fichier_cible\n\t cp [-f|-i] [-p]  fichier_source ... r≈pertoire_cible\n\t cp [-f|-i] [-p] -R|-r r≈pertoire_source ... r≈pertoire_cible\n
2 cp: impossible de supprimer le lien %s: 
3 cp: impossible d'acc≈der » %s: 
4 cp: <%s> est un r≈pertoire. Option "-R" requise.\n
5 cp: %s/%s: Nom trop long\n
6 cp: %s et %s sont identiques\n
7 cp: %s: n'est pas un r≈pertoire.\n
9 cp: impossible de cr≈er %s: 
10 cp: impossible d'ouvrir 
11 cp: impossible de cr≈er %s: 
12 cp: copie erron≈e dans %s: 
13 cp: impossible de fermer %s: 
14 cp: impossible de d≈finir les bits de droits d'acc…s sur %s: 
15 cp: %s/%s: Nom trop long.\n
16 cp: mkrnod impossible 
17 cp: symlink impossible 
18 cp: readlink impossible 
19 cp: utime a ≈chou≈ %s: 
20 cp: chown a ≈chou≈ %s: 
21 attention: saut de la prise: %s\n
22 cp: attention: impossible de copier l'acl (cpacl) dans %s\n
23 cp: attention: impossible de copier l'acl (cpacl) dans %s\n
24 link a ≈chou≈
25 remplacer %s? 
26 cp: %s: n'est pas un r≈pertoire\n
27 cp: impossible d'acc≈der » l'ACL sur %s: 
28 cp: impossible d'attribuer l'ACL de l'entr≈e %d pour %s: 
29 cp: impossible de lire l'ACL sur %s: 
