$set 1
2 impossible d'≈crire dans <%s>\n
3 impossible de renommer (/dev/tty manquant)\n
4 les options doivent comprendre o|i|p\n
5 L'option `R' n'est pas pertinente avec l'option '-%c'\n
7 L'option `B' n'est pas pertinente avec l'option '-p'\n
10 Impossible de lire %s\n
11 Impossible de lire %s\n
12 avertissement: contenu de %s alt≈r≈ dans les archives\n
13 Impossible d'≈crire dans %s\n
14 Impossible modifier mode fichier (chmod) <%s>\n(num≈ro de l'erreur:%d)\n
15 Utilisez l'option `-d' pour copier <%s>\n
16 Impossible de lier <%s> et <%s>\n(num≈ro de l'erreur:%d)\n
17 Impossible de lier <%s> et <%s>\n(num≈ro de l'erreur:%d)\n
18 Impossible de cr≈er un r≈pertoire pour <%s>\n(num≈ro de l'erreur:%d)\n
19 Impossible de lier <%s> et <%s>\n(num≈ro de l'erreur:%d)\n
20 Impossible modifier mode fichier (chmod) <%s>\n(num≈ro de l'erreur:%d)\n
21 Impossible de lire %s\n
22 Impossible d'≈crire dans %s\n
23 Impossible modifier mode fichier (chmod) <%s>\n(num≈ro de l'erreur:%d)\n
24 cpio: impossible de restaurer au moins %d fichier.\n
25 cpio: impossible de restaurer au moins %d fichiers.\n
26 %ld blocs\n
27 Syntaxe: cpio -o[aAcBvxCh] <liste_de_noms >cible\n
28          cpio -i[BcdmPrtuvfsSbx6RU] [expression ...] <cible\n
29          cpio -p[adlmruvxU] r≈pertoire <liste_de_noms\n\n
30 cpio: Resynchronis≈ apr…s un saut de %d octet.\n
31 cpio: Resynchronis≈ apr…s un saut de %d octets.\n
32 cpio: Probl…me de synchronisation; resynchronisation.\n
33 cpio: Resynchronis≈ apr…s un saut de %d octets.\n
34 cpio: Probl…me de synchronisation; resynchronisation.\n
35 Probl…me de synchronisation; demandez de l'aide\n
36 Vous pouvez utiliser l'option "R"\n
37 Il vaudrait peut-¡tre mieux ne pas utiliser l'option "-c"\n
38 Il vaudrait peut-¡tre mieux utiliser l'option "-c"\n
39 Probl…me de synchronisation; demandez de l'aide (RT)\n
40 Il vaudrait peut-¡tre mieux utiliser l'option "-c"\n
41 Renommer <%s>\n
42 Saut\n
43 Impossible de cr≈er le r≈pertoire pour <%s>\n(num≈ro de l'erreur:%d)\n
44 Impossible de cr≈er le r≈pertoire <%s>\n(num≈ro de l'erreur:%d)\n
45 Impossible modifier mode fichier (chmod) <%s>\n(num≈ro de l'erreur:%d)\n
46 Impossible de modifier propri≈taire (chown) <%s>\n(num≈ro de l'erreur:%d)\n
47 Impossible de supprimer le lien en cours <%s>\n(num≈ro de l'erreur:%d)\n
48 <%s> en cours plus r≈cent\n
49 Essai pour passer d'un fichier » lui-m¡me!\n
50 Impossible de cr≈er le fichier sp≈cial (mknod)<%s>\n(num≈ro de l'erreur:%d)\n
51 Impossible de cr≈er le r≈pertoire pour <%s>\n(num≈ro de l'erreur:%d)\n
52 Impossible de cr≈er le fichier sp≈cial (mknod) <%s>\n(num≈ro de l'erreur:%d)\n
53 Impossible modifier mode fichier (chmod) <%s>\n(num≈ro de l'erreur:%d)\n
54 Impossible de modifier propri≈taire (chown) <%s> (num≈ro de l'erreur:%d)\n
55 Impossible d'ouvrir <%s> (num≈ro de l'erreur:%d)\n
56 Impossible de cr≈er le r≈pertoire pour <%s>\n(num≈ro de l'erreur:%d)\n
57 Impossible de cr≈er <%s> (num≈ro de l'erreur:%d)\n
58 Impossible de cr≈er fichier adjacent <%s> de taille ad≈quate\n
59     <%s> sera cr≈≈ comme fichier ordinaire\n
60 <%s> non supprim≈\n
61 Impossible de cr≈er un lien pour <%s>\n(num≈ro de l'erreur:%d)\n
62 Impossible de cr≈er un lien <%s>\n(num≈ro de l'erreur:%d)\n
64 Impossible de modifier le propri≈taire (chown) <%s>\n(num≈ro de l'erreur:%d)\n
65 Impossible de cr≈er le r≈pertoire pour <%s>\n(num≈ro de l'erreur:%d)\n
66 Impossible de cr≈er <%s>\n(num≈ro de l'erreur:%d)\n
67 Impossible de relier ce fichier: %s\n
68 %s et %s repr≈sentent le m¡me fichier!\n
69 %s li≈ » %s\n
70 Impossible de cr≈er le r≈pertoire pour <%s>\n(num≈ro de l'erreur:%d)\n
71 Impossible de relier <%s> et <%s>\n(num≈ro de l'erreur:%d)\n
73 M≈moire insuffisante pour les liens\n
76 Impossible de modifier le propri≈taire (chown) <%s>\n(num≈ro de l'erreur:%d)\n
77 Impossible d'ouvrir /dev/tty pour demander d'entrer d'autres supports.\n
79 Fin de volume\n
81 num≈ro de l'erreur: %d, 
82 Impossible d'≈crire les r≈sultats\n
83 Impossible de lire les donn≈es en entr≈e\n
84 Pour continuer, entrez le nom de l'unit≈ ou du fichier\n
85 Le nom du fichier de p≈riph≈riques suivant entr≈ par l'utilisateur est nul.\n
86 L'op≈ration a ≈chou≈.\n
87 L'utilisateur a ouvert le fichier %s pour continuer.\n
88 option 'd' manquante\n
89 Impossible passer » un autre r≈pertoire (chdir) (option `d' manquante)\n
90 Impossible passer » autre r≈pert (chdir) - autorisation d'≈criture absente\n
91 Impossible de passer » un autre r≈pertoire (chdir)\n
92 cpio: impossible d'obtenir le r≈pertoire de travail en cours: 
93 cpio: Trop d'expressions sur la ligne de commande (maximum=%d).\n
94 L'option `C' n'est pas pertinente avec l'option '-%c'\n
95 Impossible de cr≈er un fichier temp pour la liste de noms de fichiers.\n
96 %s\n
97 Impossible d'ouvrir <%s>.\n
98 %s\n
99 ≈tat inattendu » l'≈criture: V‹RIFICATION (CHECKPT)\n
100 ‹tat inattendu » l'≈criture (%d).\n
101 Impossible d'acc≈der » <%s>.\n
102 ≈tat inattendu » l'≈criture: V‹RIFICATION (CHECKPT)\n
103 ‹tat inattendu » l'≈criture (%d).\n
104 Partie (%d) inconnue.\n
105 Impossible d'ouvrir /dev/tty.\n
106 %3h %2d %H:%M:%S 19%y
107 Le fichier "EN-QUEUE!!!" n'a pas ≈t≈ sauvegard≈.\n
108 Les entr≈es acl optionnelles pour <%s> ne sont pas sauvegard≈es.\n
109 Fichier de p≈riph≈riques r≈seau p≈rim≈ <%s> non sauvegard≈\n
110 Montez une nouvelle bande pour r≈crire la bobine #%d.\n
111 (Utilisation unit≈ bande avec mode direct en fonction (bobine #%d)).\n
112 Prise <%s> non sauvegard≈e\n
113 Saut du fichier de p≈riph≈riques r≈seau p≈rim≈ <%s>\n
