$set 1
1 expression trop longue
2 %s: appel de macro non termin≈
3 Indicateur de fin de fichier inattendu dans le commentaire
4 Probl…me d'≈criture dans le fichier de sortie (manque d'espace temporaire?)
5 instruction(s) #endif manquante(s)
6 (NLS) deuxi…me octet non valide dans le caract…re » 16 bits
7 (NLS) deuxi…me octet non valide dans le caract…re » 16 bits
8 %s: trop de retours en arri…re
9 pas d'espace
10 expression trop longue
11 syntaxe include erron≈e
12 imbrication d'instructions include non valide
13 pas d'espace
14 fichier include %s introuvable
15 trop de d≈finitions
16 nom de macro non valide
17 %s: ) manquante
18 param…tre formel erron≈: %s
19 trop de param…tres formels: %s
20 %s red≈fini
21 Une pseudo-instruction endif ne correspond » aucune pseudo-instruction if
22 Une pseudo-instruction else ne correspond » aucune pseudo-instruction if
23 Une pseudo-instruction IF n'est pas en place, vrai est implicite
24 num≈ro erron≈ associ≈ » #line
25 num≈ro erron≈ associ≈ » #line
26 num≈ro erron≈ associ≈ » #line
27 pseudo-instruction de pr≈processeur non d≈finie
28  (if dans le pr≈processeur)
29 trop de pseudo-instructions define
30 %s: r≈currence de la macro
31 %s: les instructions effectives sont trop longues
33 %s: argument non concordant
36 Impossible d'ouvrir %s\n
37 trop d'options -D, %s non pris en compte
38 trop d'options -U, %s non pris en compte
39 trop d'options -I, le fichier (%s) n'est pas pris en compte
40 taille de la table manquante apr…s l'option -H, option -H non ex≈cut≈e
41 Taille de la table de d≈finitions sp≈cifi≈e non valide
42 indicateur %s inconnu
43 Aucun fichier source %s
44 Impossible de cr≈er %s
45 nom ≈tranger %s
46 ligne de commande
47 Probl…me avec le fichier de sortie (manque d'espace temporaire?)
48 Impossible d'attribuer la table des d≈finitions
49 Impossible d'attribuer la table des symboles 
50 Impossible d'attribuer le fichier objet
51 Autorisation d'acc…s refus≈e pour %s
52 Chemin du fichier %s trop long
53 La table de fichiers syst…me est pleine. Impossible d'ouvrir %s
54 Chemin de %s non valide
55 Impossible d'ouvrir %s
56 trop d'options -y, le fichier (%s) n'est pas pris en compte 
57 trop d'options -p, le fichier (%s) n'est pas pris en compte 
30003 erreur de syntaxe
$set 2
1 Caract…re %c non valide dans la pseudo-instruction if du pr≈processeur
2 "define" modifiant  non-identificateur "%s" dans pr≈processeur associ≈ » if
3 Nombre %s non valide
54 division par z≈ro
30001 erreur de syntaxe - impossible de sauvegarder
30002 d≈bordement de la pile yacc
30003 erreur de syntaxe
30004 impossible d'allouer de l'espace pour les piles yacc
