$set 1
1 impossible de passer au r≈pertoire crontab.
2 impossible de lire le r≈pertoire crontab.
3 impossible de lire votre travail at.
4 votre shell d'ouverture n'≈tant pas /bin/sh, vous ne pouvez utiliser cron.
5 impossible d'acc≈der » votre fichier crontab.  Ressayez.
6 impossible de passer » votre r≈pertoire initial.\nVos commandes ne seront pas ex≈cut≈es.
7 impossible d'ex≈cuter le shell pour l'une de vos commandes.
8 fin de ligne inattendue
9 impossible de lire votre fichier crontab.  Ressayez.
10 impossible de cr≈er un fichier d'entr≈e standard pour l'une de vos\ncommandes crontab. Cette commande n'a pas ≈t≈ ex≈cut≈e.
11 nombre trop ≈lev≈ ou trop petit pour la zone
12 \n\n****************************************************\nCron: Le message pr≈c≈dent est la sortie standard\n    et l'erreur standard de l'une de vos commandes cron.\n\n
13 \n\n****************************************************\nCron: Le message pr≈c≈dent est la sortie standard\n    et l'erreur standard de l'une de vos commandes crontab:\n\n
14 \n\n****************************************************\nCron: Le message pr≈c≈dent est la sortie standard\n    et l'erreur standard de l'une de vos commandes at.\n\n
15 cron a ≈t≈ incapable de vous envoyer les r≈sultats d'une de vos commandes\n(donn≈es ou erreurs). N'oubliez pas de r≈acheminer la sortie et\nl'erreur standard pour chaque commande.
16 symbole inattendu rep≈r≈
17 *** cron est lanc≈ ***   pid = %d
18 impossible d'acc≈der au fichier QUEDEFS
19 impossible d'acc≈der » la file d'attente fifo
20 impossible de cr≈er la file d'attente fifo
21 cron s'ex≈cute d≈j»
22 impossible d'ouvrir %s\n
23 impossible de passer au r≈pertoire at
24 impossible de lire le r≈pertoire at
25 Il y a une erreur dans votre fichier crontab.\n
26 Le syst…me n'a pas tenu compte de cette entr≈e.\n
27 %c le nombre maximal de processus en file d'attente est atteint
28 nombre maximal d'ex≈cutions de processus MAXRUN (%d) atteint
29 limite de at ATLIMIT (%d) atteinte pour l'uid %d
30 limite de cron CRONLIMIT (%d) atteinte pour l'uid %d
31 impossible de dupliquer le processus (fork)
32 pid retourn≈ inattendu %d (non pris en compte)
33 impossible d'acc≈der » la file d'attente fifo
34 message reµu - format erron≈
35 cron interrompu: 
36 ******* CRON INTERROMPU ********
37 replanification d'un travail cron
38 replanification d'un travail at
39 impossible d'ouvrir fichier des d≈finitions de la file d'attente (quedefs)
40 utilisation des d≈finitions de la file d'attente par d≈faut
69 Votre travail ne contenait aucun ID de v≈rification valide.\nVoir l'administrateur du syst…me\n
$set 2
1 impossible d'allouer %d octets d'espace\n
