$set 1
1 impossible de cr≈er votre fichier crontab dans le r≈pertoire crontab.
2 impossible d'ouvrir votre fichier crontab.
3 votre shell d'ouverture n'≈tant pas /bin/sh, vous ne pouvez utiliser cron.
4 avertissement: les commandes seront ex≈cut≈es » partir de /bin/sh\n
5 syntaxe correcte: \n\tcrontab [fichier]\n\tcrontab [-r]\n\tcrontab [-l]
6 vous n'¡tes pas un utilisateur valide (aucune entr≈e dans /etc/passwd).
7 vous n'¡tes pas autoris≈ » utiliser cron.  D≈sol≈.
8 fin de ligne inattendue.
9 la ligne comprend un caract…re incorrect.
10 num≈ro hors limite.
11 %scrontab: erreur sur la ligne pr≈c≈dente; %s\n
12 cron ne s'ex≈cute peut-¡tre pas - contactez l'administrateur de syst…me\n
13 crontab: erreur dans la file d'attente de messages ouverte\n
14 crontab: erreur envoi message\n
$set 2
1 impossible d'allouer %d octets d'espace\n
