$set 1
1 assertion incorrecte: %s\n
2 l'attribution initiale a ≈chou≈, erreur = %d\n
3 l'attribution de temp a ≈chou≈:%d WORD:%d erreur = %d\n
$set 2
1 getwd: impossible d'ouvrir ..\n
2 getwd: erreur de lecture dans ..\n
3 getwd: erreur de lecture dans ..\n
4 getwd: impossible de rechanger\n
5 getwd: nom du r≈pertoire en cours trop long\n
$set 3
1 fermeture de session automatique\n
2 Attention:pas d'acc…s » tty; donc pas de gestion des travaux dans ce shell...\n
3 fermeture de session\n
4 Interrompu
5 Vous avez reµu du courrier.\n
6 Vous avez du courrier.\n
7 Nouveau courrier dans %s.\n
8 Courrier dans %s.\n
9 %s: N'est pas un fichier ordinaire
10 Trop peu d'arguments
11 Trop d'arguments
$set 4
1 Syntaxe: dirs [ -l ]
2 Aucun r≈pertoire initial
3 Impossible de passer au r≈pertoire initial
4 Aucun autre r≈pertoire
5 La pile de r≈pertoire n'est pas aussi grande
6 R≈pertoire erron≈
7 Pile de r≈pertoire vide
8 Le r≈pertoire %s n'existe pas, supprim≈ de la pile
$set 5
1 Ambigu
2 Seul %c
3 Mot trop long
4 $< ligne trop longue
5 Aucun fichier pour $0
6 Syntaxe variable
7 Indice inf≈rieur hors plage
8 Erron≈ : mode dans $
9 << caract…re de fin introuvable
10 D≈bordement de ligne
11 D≈bordement de ligne
$set 6
1 Aucune concordance
2 Commande introuvable
3 %d trouv≈s, %d saut≈s, %2d%%\n
4 %s: Fichier ex≈cutable incompatible avec le mat≈riel
$set 7
1 Division par 0
2 Mod par 0
3 Syntaxe de l'expression
4 } manquante
5 Nom de fichier manquant
6 Syntaxe de l'expression
$set 8
1 Trop peu d'arguments
2 Trop d'arguments
3 Impossible » partir du terminal
4 Impossible » partir du terminal
5 Il est trop risqu≈ d'utiliser alias avec
6 Mot de passe:
7 nom et mot de passe trop longs
8 ouverture de session » distance non valide; num≈ro de l'erreur r≈seau = %d\n
9 erreur r≈seau
10 le noeud ≈loign≈ ne r≈pond pas; num≈ro de l'erreur r≈seau = %d\n
11 erreur r≈seau
12 num≈ro de l'erreur r≈seau = %d\n
13 erreur r≈seau
14 fichier de p≈riph≈riques r≈seau non valide; num≈ro de l'erreur = %d\n
15 N'est pas le shell d'ouverture
16 Pseudo-expression if vide
17 pseudo-instruction then incorrecte
18 Erreur de syntaxe
19 N'appara—t pas dans while/foreach
20 Syntaxe de l'expression
21 Variable non valide
22 Des mots ne sont pas entre ()
23 Aucune concordance
24 Syntaxe de l'expression
25 N'appara—t pas dans while/foreach
26 N'appara—t pas dans while/foreach
27 pseudo-instructions then/endif introuvables
28 pseudo-instruction endif introuvable
29 pseudo-instruction endsw introuvable
30 pseudo-instruction end introuvable
31 label introuvable
32 Aucune concordance
33 Masque inad≈quat
34 Impossible d'utiliser `suspend` » partir d'un shell d'ouverture
35 Aucune concordance
36 r≈seau non pris en charge\n
$set 9
2 ] manquant
3 } manquante
4 ] manquant
5 ] manquant
7 Arguments trop longs
8 Nom d'acc…s trop long
9  Aucune concordance
10 Ambigu
11 ` seul
12 Mot trop long
13 Trop de mots » partir de ``
14 Expression non valide
$set 10
1 Non concordant 
2 Mot trop long
3 Syntaxe variable
4 D≈bordement du tampon d'extension
5 Forme ! erron≈e
6 Aucun caract…re de remplacement pr≈c≈dent
7 Caract…re de remplacement erron≈
8 Aucun lhs pr≈c≈dent
9 Rhs trop long
10 Modificateur ! erron≈: 
11 Le modificateur a ≈chou≈
12 D≈bordement du tampon des caract…res de remplacement
13 S≈lecteur d'argument ! erron≈
14 Aucune recherche pr≈c≈dente
15 : ≈v≈nement non trouv≈
16 Remise » l'≈tat initial du pgrp du tty de %d » %d\n
17 \nUtilisez "logout" pour fermer la session.\n
18 \nUtilisez "exit" pour sortir de csh.\n
19 Remise » l'≈tat initial du pgrp du tty jusqu'» %d\n
$set 11
1 M≈moire insuffisante
2 Variable non d≈finie
3 manque d'espace pour to_short
4 A d≈pass≈ l'espace to_chart\n
$set 12
1 Boucle d'alias
2 Trop de )
3 Trop de )
4 Trop de (
5 ( mal plac≈e
6 Nom manquant pour le r≈acheminement
7 R≈acheminement des r≈sultats ambigu
8  << impossible » l'int≈rieur de ()
9 R≈acheminement de l'entr≈e ambigu
10 () mal plac≈es
11 Commande nulle non valide
$set 13
1 Arr¡t
2 Interruption
3 Sortie
4 Instruction non valide
5 Analyse /interruption BPT
6 interruption IOT
7 interruption EMT
8 Exception de virgule flottante
9 Arr¡t≈ pr≈matur≈ment
10 Erreur bus
11 Incident de segmentation
12 Appel syst…me erron≈
13 Conduit interrompu
14 Horloge
15 Caract…re de fin
16 Signal 16
17 Signal 17
18 Sortie du processus enfant
19 Relance apr…s panne de courant
20 Virtual Timer Alarm
21 Profiling Timer Alarm
22 Signal E/S asynchrone
23 Window Signal
24 Arr¡t≈
25 Arr¡t≈
26 Poursuivi
27 Arr¡t≈ (entr≈e tty)
28 Arr¡t≈ (sortie tty)
29 Signal 29
30 Signal 30
31 Signal 31
32 Signal 32
41 BOGUE: en attente de travail d'arri…re-plan!\n
42 BOGUE: processus vid≈ deux fois
43 Ex≈cution 
44 Sortie %-16d
45 Ex≈cut≈
46 BOGUE: ≈tat=%-9o
47  (noyau vid≈)
48  (wd: 
49 (wd now: 
50 Syntaxe: travaux [ -l ]
51 Num≈ro de signal erron≈
52 Signal inconnu; la commande kill -l donne la liste des signaux
53 %s: D≈j» arr¡t≈\n
54 Les arguments devraient correspondre » des travaux ou des id de processus
55 \nDes travaux sont arr¡t≈s
56 Aucun travail en cours
57 Aucun travail pr≈c≈dent
58 Aucun travail de ce type
60 Aucun travail ne correspond » l'expression
61 Aucun travail de ce type
$set 14
4 Impossible de cr≈er le conduit
5 %s: fichier existant
$set 15
1 Erreur de syntaxe
2 ) manquante
3 Erreur dans l'indice
4 Indice hors plage
5 Erreur de syntaxe
6 Syntaxe de l'expression
7 Num≈ro mal form≈
8 Aucune concordance
9 Plus de mots
10 Avertissement:  PATH beaucoup trop long; tronqu≈\n
11 le chemin du r≈pertoire initial "home" doit ¡tre un chemin absolu
$set 16
1 \nAAAH!! Trop de noms dans le fichier de mots de passe (passwd)!!\n
2 \nAAAH!! Trop de fichiers!!\n
3 m≈moire insuffisante\n
$set 17
1 .\n
