$set 1
10 Type demandeur interne %s\n
11 l'appel mlock %s a ≈chou≈\n
12 l'appel mlock %s a r≈ussi\n
13 d≈lai d'ouverture g≈n≈rique\n
16 l'ouverture g≈n≈rique (%d) a ≈chou≈, num≈ro de l'erreur = %d\n
19 %s introuvable dans le fichier Dialers\n
22 gdial(%s) called\n
23 dkcall(%s)\n
27 tcpdial h¬te %s, 
28 port %d\n
29 aucune prise: %s\n
31 aucune prise, num≈ro de l'erreur %d\n
34 d≈lai tcpopen\n
37 famille: %d\n
38 port: %d\n
39 adresse: %08x\n
40 la liaison a ≈chou≈: %s\n
42 la liaison a ≈chou≈, num≈ro de l'erreur %d\n
45 unetdial h¬te %s, 
46 port %d\n
47 tcpopen a ≈chou≈: num≈ro de l'erreur %d\n
48 OUVERTURE A ‹CHOU‹ %s\n
50 valeur COM1 retourn≈e = %d\n
52 d≈lai » l'ouverture de sytek\n
53 OUVERTURE 2 A ECHOU‹ %s\n
54 mlock %s a ≈chou≈\n
55 Port d'utilisation %s, 
56 acu - %s, 
57 Num≈ro de t≈l≈phone  %s\n
58 Essai de modem - %s, 
59 acu - %s, 
60 appel  %s: 
61 R‹USSI\n
62 A ‹CHOU‹\n
63 impossible d'ouvrir %s\n
64 %s est ouvert\n
65 d≈lai » l'ouverture du modem\n
66 La composition du num≈ro a ≈chou≈. Le processus fils est interrompu.\n
68 Erreur d'≈criture ACU %d\n
69 Composition du num≈ro » l'aide du programme %s\n
72 dcf est %d\n
73 Fork Stat %o\n
74 ≈criture DN %s\n
75 d≈lai d'attente
76 impossible d'ouvrir %s\n
77 %s est ouvert\n
78 impossible d'ouvrir %s\n
79 dcf est %d\n
80 erreur d'≈criture ACU %d\n
81 ≈criture ACU ok%s\n
82 Ligne ouverte %s\n
83 a ≈chou≈
419 conn(%s)\n
420 getto ret %d\n
421 close caller (%d)\n
422 delock(%s)\n
423 Call failed: %s\n
424 Device Type %s wanted\n
425 Requested Device Type Not Found\n
427 Wrong Time To Call: %s\n
428 ProtoStr = %s\n
430 expect: (
431 got it\n
432 lost line errno - %d\n
435 enough already\n
436 got it\n
437 time out\n
438 BREAK\n
439 EOF\n
440 sendthem (
441 DELAY\n
442 <NO CR>
443 <NO CR - MIDDLE IGNORED>\n
444 PAUSE\n
445 ECHO CHECK ON\n
446 ECHO CHECK OFF\n
447 BREAK\n
448 ^M
449 )\n
524 fixline (%d, 
525 %d)\n
527 fixline - direct\n
529 setline - %c\n
530 sytfixline - speed= %d\n
534 fixline(%d, 
535 %d)\n
641 ulockf failed in onelock()\n
642 ulockf file %s\n
643 Lock File--can't read (errno %d) --remove it!\n
644 Lock File--bad format--remove it!\n
645 Lock File--process still active--not removed\n
646 kill pid (%d), 
647 returned %d
648 --ok to remove lock file (%s)\n
649 ulockf failed in unlink()\n
650 ulockf file %s\n
651 Lock File--can't read (errno %d) --remove it!\n
652 --ok to remove lock file (%s)\n
653 ulockf failed in unlink()\n
657 link(%s, 
658 %s)\n
1120 [-h] [-v] [-w n] [-x n] [-s vitesse] num≈ro_de_t≈l≈phone ...
1121 ct: impossible d'ouvrir %s\n
1122 syntaxe: %s %s\n
1123 (-w %s) Le temps d'attente doit ¡tre > 0\n
1124 syntaxe: %s %s\n
1125 syntaxe: %s %s\n
1126 Aucun num≈ro de t≈l≈phone sp≈cifi≈!\n
1127 ct: num≈ro de t≈l≈phone trop long -- %s\n
1128 ct: num≈ro de t≈l≈phone erron≈ -- %s\n
1129 composeur (dialer) attribu≈ est » %s bauds\n
1130 Aucun composeur (dialer) %s sur ce syst…me\n
1131 %s occup≈
1132 Le composeur (dialer) est
1133 Les composeurs (dialer) sont
1134  (%d minute(s))\n
1135 Le (%d) composeur %s (dialer) %s occup≈\n
1136  est
1137 s sont
1138 Attente de %d minute%s\n
1139 s
1140 D≈sirez-vous attendre pour le composeur (dialer)? (y pour oui): 
1141 Dur≈e, en minutes? 
1142 En attente du composeur (dialer)\n
1143 *** D‹LAI ***\n
1144 D≈sirez-vous vraiment raccrocher? (y pour raccrocher): 
1145 Connexion ≈tablie\n
1146 Appuyez sur Entr≈e 
1147 il y a un uugetty; sortie\n
1148 lancer le getty -h -t60 %s 
1149 ct: impossible de dupliquer (fork) pour le getty\n
1150 ct: impossible d'ex≈cuter le getty\n
1151 \nR≈tablir la connexion? 
1152 D≈connexion(%d)\n
1153 D≈connect≈\n
1154 ≈limination des erreurs(%d)\n
1155 changement de propri≈taire/d'autorisation (chmod/chown) %s\n
1156 impossible de changer propri≈taire/autorisation (chmod/chown) sur %s\n 
1157 » %d\n
1158 ligne ut %s, 
1159 utilisateur ut %s, 
1160 id ut %.4s, 
1161 pid ut %d\n
1162 processus encore actif\n
