$set 1
1 syntaxe: %s [-s baud] [-l ligne] [-h] [-n] [-t] [-d niveau] [-m] [-o|-e] no_tel | 'dir' | nom_syst_≈loign≈\n
2 interruption
3 le composeur (dialer) a raccroch≈
4 pas de r≈ponse
5 d≈bit non valide
6 probl…me acu (unit≈ d'appel automatique)
7 probl…me de ligne
8 impossible d'ouvrir le fichier de p≈riph≈riques L
9 impossible d'ouvrir le fichier Devices
10 L'unit≈ demand≈e n'est pas disponible\r\n
11 Le nom de l'unit≈ ou du syst…me demand≈ est inconnu\r\n
12 Aucune unit≈ disponible » %d bauds\r\n
13 Aucune unit≈ connue » %d bauds\r\n
14 La connexion a ≈chou≈: %s\r\n
15 Impossible d'ouvrir: %s\r\n
16 Ligne perdue\r\n
17 Impossible d'ex≈cuter le shell\r\n
18 Impossible de d≈router %s\r\n
19 Utilisez `~~' pour commencer la ligne par `~'\r\n
20 caract…re oubli≈\r\n
21 apr…s %ld octets\r\n
22 %d lignes/%ld caract…res\r\n
23 Transmission de fichier interrompue\r\n
24 Impossible de dupliquer le processus (fork) -- attendez et ressayez\r\n
25 \r\nImpossible de transmettre le caract…re sp≈cial `%#o'\r\n
26 \nLigne trop longue\r\n
27 r\nerreur E-S\r\n
28 Utilisez la commande `~$' \r\n
29 Impossible d'obtenir l'≈tat du terminal\r\n
30 D≈sol≈, vous ne pouvez pas utiliser cu » partir de la console 3B\r\n
31 la vitesse demand≈e ne concorde pas\r\n
32 le nom du syst…me demand≈ est inconnu\r\n
33 Cu n'est pas compil≈ avec un indicateur de mise au point\r\n
34 Veuillez entrer le num≈ro: 
35 Appel automatique - veuillez patienter\r\n
36 Impossible d'obtenir l'≈tat de l'unit≈
37 Changement de propri≈taire impossible (chown) dans %s\n
38 Modification des autorisations impossible (chmod) dans %s\n
39 Impossible de d≈finir l'uid %d\n
40 Connect≈\007\r\n
41 L'ex≈cution de '%s' a ≈chou≈\r\n
42 transmission commenc≈e\n\r
43 interruption dans la transmission\n\r
44 interruption du terminal (tintr)\n\r
46 appel tilde(%s)\r\n
47 appel shell(%s)\r\n
48 appel dopercen ("%s")\r\n
50 syntaxe: ~%%take de [»]\r\n
55 syntaxe: ~%%put de [»]\r\n
58 Impossible d'ouvrir le fichier %s\r\n
59 Le d≈routement de l'entr≈e commence.\r\n
60 Le d≈routement de l'entr≈e est termin≈.\r\n
61 Invite = \\%03o \\%03o\r\n
62 D≈lai = %d s.\r\n
63 Suffixe ligne = \\%03o \\%03o\r\n
64 Le d≈routement de la sortie est termin≈.\r\n
65 Aucun d≈routement d'entr≈e actif.\r\n
66 Le d≈routement de la sortie est termin≈.\r\n
67 Impossible d'ouvrir le fichier %s.\r\n
68 Le d≈routement de la sortie commence.\r\n
69 Impossible de passer » %s\r\n
70 Impossible de passer » %s\r\n
71 ~%%%s inconnu de cu\r\n
72 l'≈criture a ≈chou≈\r\n
73 r≈ception a commenc≈\r\n
74 \r\nOnde porteuse perdue\r\n
75 appel mode(%d)\r\n
76 Impossible de d≈finir l'uid\r\n
77 Impossible de d≈finir le gid\r\n
79 erreur de lecture obtenue, pas EINTR\n\r
80 lu de fd=%d valeur retourn≈e %d
81 erreur de lecture obtenue, pas EINTR\n\r
82 \ncu: r≈sultats group≈s\r\n
83 \ncu: r≈sultats group≈s\r\n
84 appel rcvdead(%d)\r\n
85 appel (sortie) quit(%d)\r\n
86 appel (sortie) bye(%d)\r\n
87 \r\nD≈connect≈\007\r\n
88 appel raccrochage(%d)\r\n
89 Impossible changer propri≈taire ou autorisation (chown/chmod) dans %s\n
90 \r≈tat de l'unit≈ pour fd=%d\r\n
91 Local
92 impossible d'ouvrir le fichier Systems\n
93 impossible d'ouvrir le fichier L.sys\n
