$set 1
1 dd: argument %s erron≈\n
2 dd: impossible d'ouvrir %s\n
3 dd: impossible de copier un fichier sur lui-m¡me\n
4 dd: impossible de cr≈er %s\n
5 dd: valeurs nulles non valides\n
6 dd: m≈moire insuffisante\n
7 dd: erreur de lecture
8 erreur E/S \n
9 %u+%u enregistrements en entr≈e\n
10 %u+%u enregistrements en sortie\n
11 %u enregistrements tronqu≈s\n
12 \nERREUR !! La taille de la section %s exc…de 4 gigaoctets !! \n
13 L'appel ioctl pour trouver la taille du disque a ≈chou≈ !!\n 
14 L'appel ioctl pour trouver la taille des blocs a ≈chou≈ !!\n 
