$set 1
1 diff: fichier d'entr≈e 
2 diff: -h n'accepte pas -e, -f, -n, -c, ni -I\n
3 diff: m≈moire insuffisante\n
4 diff: fichiers trop gros, essayez -h\n
5 Seulement dans %.*s: %s\n
6 Fichiers communs identiques dans %.*s et %.*s\n
7 Fichiers binaires diff≈rents dans %.*s et %.*s\n
8 Sous-r≈pertoires communs de %.*s et %.*s\n
9 diff: r≈pertoire 
10 Sous-r≈pertoires communs: %s et %s\n
11 Les fichiers %s et %s sont identiques\n
12 Les fichiers binaires %s et %s sont diff≈rents\n
13 diff: exec 
14 diff: d≈but de l'ex≈cution de pr: 
15 Aucune diff≈rence relev≈e\n
16 diff: fichier d'entr≈e temporaire 
18 diff: impossible de sp≈cifier - avec autre r≈pertoire d'arguments \n
19 Attention:nouvelle ligne manquante » la fin du fichier %s\n
21 diff: attention: n'utilisez pas -s ou -l avec -e\n
22 diff: d≈but de l'ex≈cution de diff: 
23 diff: impossible de sp≈cifier - -\n
24 Le fichier %s est un %s alors que le fichier %s est un %s\n
25 fichier sp≈cial en mode caract…re
26 fichier sp≈cial en mode bloc
27 fichier FIFO sp≈cial
28 standard
29 r≈pertoire
30 inconnu
