$set 1
1 syntaxe : dumpmsg fichier-catalogue\n
2 Ouverture du fichier-catalogue : %s\n
3 Fermeture du fichier-catalogue : %s\n
4 Aucun message dans le fichier-catalogue\n
5 dumpmsg: %s: n'est pas un fichier-catalogue\n
6 %ld messages dans le fichier-catalogue\n
7 dumpmsg: %s: fichier-catalogue erron≈\n
8 setnum  (d≈finition du num≈ro): %d\n
9 msgnum (num≈ro du message) : %d\n
10 length (longueur) : %d\n
11 addr (adresse)   : %d\n\n
12 dumpmsg: %s: fichier-catalogue erron≈\n
13 setnum  (d≈finition du num≈ro): %d\n
14 msgnum (num≈ro du message) : %d\n
15 length (longueur)  : %d\n
16 addr (adresse)   : %d\n
17 message : %s\n\n
