$set 1
1 l'≈criture sur le conduit ou l'ouverture a ≈chou≈
2 attention: `w' attendu
3 la marque n'est pas en minuscule
4 impossible d'ouvrir le fichier d'entr≈e
5 probl…me de sp≈cification PWB
6 rien » annuler
7 shell » acc…s restreint
8 impossible de cr≈er le fichier de sortie
9 manque d'espace pour le syst…me de fichiers!
10 impossible d'ouvrir le fichier
11 impossible d'≈tablir un lien
12 Plage des points de terminaison trop vaste
13 commande inconnue
14 cha—ne de recherche introuvable
15 -
16 ligne hors plage
17 num≈ro erron≈
18 plage erron≈e
19 Valeur d'adresse non valide
20 Expression incompl…te associ≈e au changement global
21 suffixe non valide
22 nom de fichier non valide ou manquant
23 aucun espace apr…s la commande
24 la duplication (fork) a ≈chou≈ - ressayez
25 maximum de 64 caract…res dans les noms de fichiers
26 `\\digit' hors plage
27 interruption
28 ligne trop longue
29 caract…re non valide dans le fichier d'entr≈e
30 erreur d'≈criture
31 m≈moire insuffisante pour annexer (append)
32 fichier temporaire (temp) trop gros
33 erreur d'E/S dans le fichier temporaire (temp)
34 changements globaux multiples (global) non admis
35 l'expression globale (global) est trop longue
36 aucune concordance
37 s≈parateur non valide ou manquant
38 -
39 cha—ne de remplacement trop longue
40 cible du d≈placement (move) non valide
41 -
42 aucune cha—ne de recherche pr≈c≈demment utilis≈e
43 '\\( \\)' manquante
44 Trop de `\\('
45 plus de 2 num≈ros donn≈s
46 '\\}' attendu
47 le premier num≈ro est sup≈rieur au deuxi…me
48 remplacement incomplet
49 caract…re de changement de ligne inattendu
50 '[ ]' manquant
51 d≈bordement de l'expression standard
52 erreur dans l'expression standard (RE)
53 commande attendue
54 a, i, ou c non admis dans G
55 fin de ligne attendue
56 aucune cha—ne de remplacement pr≈c≈demment utilis≈e
57 aucune commande pr≈c≈demment utilis≈e
58 r≈acheminement non valide
59 mise » jour concurrente possible
60 cette commande n'≈tait pas attendue par yed
61 la commande x est devenue X (majuscule)
62 Attention: 'w' peut d≈truire fichier entr≈e (`caract…re non valide' rep≈r≈)
63 Attention: 'q' peut perdre donn≈es dans tampon:'w' peut d≈truire fich entr≈e
65 l'option -x n'est pas disponible
66 nom de fichier trop long
67 cette option n'est pas disponible
68  les caract…res nuls ont ≈t≈ remplac≈s par '\\0'
69 \007la lecture est peut-¡tre incompl…te - attention!\007
70 ligne trop longue: (num≈ro de ligne) lno = 
71 ligne trop longue: (num≈ro de ligne) lno = 
72 trop long
73 nombre de tabulations\n
75 Op≈ration non prise en charge dans la prise
