$set 1
1 (alias "%s" inconnu)\n\r
2 Impossible de r≈soudre l'alias '%s'!\n\r
3 Entrez "elmalias -c" pour localiser des adresses valides!\n\r
4 '%s' est une adresse inconnue. Remplacez-la par: 
5 Impossible de cr≈er l'adresse de retour -\nlimite du nombre de transits atteinte!
$set 2
1 Entrez nom alias: 
2 un groupe de ce nom existe d≈j»:%s
3 d≈j» associ≈ » un alias: %s
4 Nom complet pour %s: 
5 Entrez l'adresse de %s: 
6 Aucune adresse sp≈cifi≈e!
7 Aucun message associ≈ » alias!
8 Adresse du message en cours associ≈e » l'alias: 
11 Nom complet de %s: 
12 impossible d'ouvrir %s pour ajouter le nouvel alias!
13 Impossible d'ajouter le nouvel alias au fichier %s
14 Commandes alias
15 A)lias msg courant, M)ake alias, D)elete alias, P)erson (v≈rifier personne).
16 E)xpand (r≈soudre et v≈rifier alias), U)ser ou S)ystem (liste des alias).
17 initialisation des tables internes...
18 Alias: 
21 V≈rifier personne: 
22 Alias du groupe:\n\r%s
23 Adresse associ≈e » l'alias:\n\r%s
24 introuvable
25 Afficher la liste des alias du syst…me:\r\n
26 \n\n(Si l'affichage est alt≈r≈, utilisez ^L pour le r≈tablir)\n
27 \n\nAppuyez sur une touche pour revenir au menu principal Alias: 
28 Impossible de lire le fichier syst…me %s
29 Afficher la liste des alias des utilisateurs:\r\n
32 Impossible de lire le fichier %s de l'utilisateur %s
38 Donn≈es en entr≈e non valides!
39 Suppression d'alias...
40 Ajout de nouveaux alias...
41 Relecture de la base de donn≈es dans...
42 Cr≈ation r≈ussie des nouveaux alias
43 Suppression r≈ussie des nouveaux alias
44 'elmalias' a ≈chou≈. V≈rifiez 'aliases.text' ou 'elmalias'.
45 Touche pour laquelle vous d≈sirez de l'aide : 
46 Touche pour laquelle vous d≈sirez de l'aide, '?' pour liste ou '.' pour sortir
47 Touche :  
48 a = Ajouter adresse de retour du message » la base de donn≈es d'alias.
49 m = Cr≈er nouvel alias d'utilisateur, l'ajouter » la base de donn≈es d'alias.
50 Revenir au menu principal.
51 p = V≈rifier l'alias d'un utilisateur dans la base de donn≈es d'alias.
52 s = Afficher la base de donn≈es des alias du syst…me.
53 Cette touche n'est pas utilis≈e dans cette section.
56 Fichier des cl≈s %s ouvert, mais impossible d'ouvrir fichier de donn≈es!\n
57 d = Supprimer l'alias de l'usager, puis le retirer de la base de donn≈es d'alias
58 u = Afficher la base de donn≈es des alias des usagers.
59 e = Affichage d'alias enti…rement r≈solu.
60 ^L = R≈g≈n≈rer l'≈cran.
61 Alias enti…rement r≈solu: 
62 Adresse associ≈e » l'alias:\n\r%s
63 Appuyez sur une touche pour continuer: 
$set 3
1 initialisation des tables internes...
$set 4
1 %s est une adresse non valide!
2 \n** Votre fichier d'alias syst…me semble constitu≈ pour une autre version\n
3 ** du syst…me Elm. L'administrateur doit le reconstituer comme fichier racine\n
4 ** » l'aide de la commande ``elmalias'' (aucune modification au fichier n'est\n
5 ** n≈cessaire --> appelez `elmalias -q' en tant qu'utilisateur root).\n\n
6 \n** Votre fichier d'alias semble constitu≈ pour une autre version du syst…me\n
7 ** Elm. Vous devez le reconstituer » l'aide de la commande ``elmalias'' ou\n
8 ** le syst…me peut le faire automatiquement. Reconstitution automatique (y/n)? 
9 \n\n** Faites-le vous-m¡me en entrant la commande ``elmalias'' » l'invite\n
10 ** suivante. (Aucune modification au fichier texte des alias n'est\n
11 ** n≈cessaire).\n\n
12 Oui\n\n** reconstitution de la base de donn≈es d'alias...\n\n
13 \n** probl…me de reconstitution des alias (%d ; faites-le manuellement).\n\n
14 \n** alias reconstitu≈s, rappelez le programme Elm.\n\n
$set 5
1 Syntaxe: %s [-akKmz] [-f fichier] \n
2          %s [-s objet] <noms>\n
3          %s -h\n\n
4 Attention:syst…me cr≈≈ sans activation de la mise au point - demande ignor≈e\n
5 \n\rImpossible de sp≈cifier d'objet sans entrer de destinataire!\n\n\r
6 \n\rDestinataire du courrier non valide!\n\n\r
7 \nArguments de lancement valides pour le programme ELM :\n\n
8 \targ\t\tSignification\n
9 \t -a \tArrow - utiliser le pointeur en forme de fl…che\n
10 \t -fx\tFile - lire le fichier 'x' au lieu de la bo—te » lettres\n
11 \t -h \tHelp - afficher la pr≈sente liste d'options\n
12 \t -k \tSoftkeys off - d≈sactiver touches progr. au terminal HP 2622\n
13 \t -K \tKeypad&softkeys off - d≈sactiver touches progr. et clavier num.\n
14 \t -m \tMenu - retirer l'affich. du menu, plus de lignes ≈cran\n
15 \t -sx\tSubject 'x' - sp≈cificier l'objet 'x' pour les envois par lots\n
16 \t -z \tZero - ne pas entrer dans Elm s'il n'y a pas de courrier\n
$set 6
1 encore %d ligne(s): appuyez sur <espace> pour la suite, sur 'q' pour sortir 
2 encore %d ligne(s): appuyez sur <espace> pour la suite, 'q' pour sortir 
3 encore %d ligne(s) 
4 ...recherche de l'expression "%s"...
5 Expression introuvable : Appuyez sur une touche pour continuer
$set 8
1 Attention: Impossible d'identifier les connexions syst…me...
$set 9
1 Supprimer alias: 
2 aucun alias pour ce nom: %s
3 Impossible de supprimer l'alias syst…me: %s
4 Impossible d'ouvrir le fichier texte d'alias: %s
5 Impossible de modifier le fichier texte d'alias!
6 le lien a ≈chou≈! %s - %s
7 Impossible de supprimer plusieurs alias » la fois
$set 10
1 Attention:le domaine %s utilise une zone p≈rim≈e!!
2 Impossible de trouver un chemin vers %s!
3 Impossible de trouver un chemin vers %s!
$set 11
1 appel de l'≈diteur...
2 Attention: acc…s au fichier impossible, permissions peuvent ¡tre alt≈r≈es
3 Probl…mes lors de l'appel de l'≈diteur %s!
4 Attention: nouveau courrier arriv≈...
5 Impossible d'ouvrir de nouveau le fichier temporaire.  Modifications PERDUES!
6 Impossible d'ouvrir %s pour la lecture!  Modifications PERDUES!
7 Impossible de rechercher dans toute la bo—te » lettres. Modifications PERDUES!
8 Impossible de copier le fichier temporaire dans la bo—te » lettres!
9 \n\rImpossible d'≈tablir une liaison entre %s et\nle fichier de courrier %s...\n\r
10 \n\rImpossible d'≈tablir une liaison interne entre %s et\nle fichier de courrier %s...\n\r
11 \n\rV≈rifiez %s pour votre courrier...\n\r
12 modifications apport≈es au nouveau courrier...
13 Relecture de la nouvelle version de la bo—te » lettres...
$set 12
1 appel de l'≈diteur...
2 \r\nappel de l'≈diteur...\r\n
3 Impossible d'appeler l'≈diteur - trop d'options
4 Impossible d'appeler l'≈diteur - trop d'options\r\n
5 Impossible d'appeler l'≈diteur '%s' pour composition.
6 Impossible d'appeler l'≈diteur '%s' pour composition.\r\n
7 Impossible d'ouvrir %s pour l'ajout
8 \n\nContinuez le message, '.' pour fin, %cp pour liste, %c? pour aide;\n\n
9 \n\nEntrez le message, '.' pour fin ou %c? <retour> pour aide;\n\n
10 (continuer) \n\r
11 (continuer l'entr≈e du message, '.' pour terminer)\r\n
12 \r\n(Impossible de trouver '%s' sur ce syst…me! continuer)\r\n
13 \r\nEntrez le nom de l'≈diteur : 
16 (vous devez utiliser une commande pr≈cise. Continuer...)\r\n
18 \r\n(%c%c est inconnu. Entrez %c? pour obtenir de l'aide)\r\n
19 (Attention:impossible d'annexer au tampon de modification - %s\n...Continuer.)
20 \r\n<fin-du-message>\n\r\n\r
21 \r\nOptions disponibles:\n\n
22 \t%c?\tImprimer ce menu d'aide\n
23 \t~~\tAjouter la ligne en la faisant pr≈c≈der d'un seul caract…re '~'\n
24 \t%cb\tChanger les adresses dans la liste des copies secr…tes\n
25 \t%cc\tChanger les adresses dans la liste des copies\n
26 \t%ce\tAppeler l'≈diteur $EDITOR avec le message, si possible\n
27 \t%cf\tajouter la liste de messages sp≈cifi≈e, ou celle en cours\n
28 \t%ch\tmodifier tous les en-t¡tes disponibles\n\t\t(destinataire,cc%s,objet)\n
29 \t%cm\tidentique » '%cf', mais avec le 'pr≈fixe' en cours\n
30 \t%co\tAppeler l'≈diteur sp≈cifi≈ par l'usager dans le message\n
31 \t%cp\timprimer le message tel quel\n
32 \t%cr\tLire le fichier sp≈cifi≈\n
33 \t%cs\tModifier l'objet du message\n
34 \t%ct\tModifier les adresses dans la liste de destinataires (To)\n
35 \t%cv\tAppeler l'≈diteur $VISUAL avec le message\n\n
36 \t%c!\tex≈cuter une commande unix (ou entrer un shell si aucune commande)\n
37 \t%c<\tex≈cuter une commande unix et ajouter ses r≈sultats au message\n\n
38 \t.  \tseul sur une ligne (ou CTRL-D) met fin au message\n\n
39 \r\n(pas de nom de fichier sp≈cifi≈ pour la lecture! Continuer...)\r\n
40 \r\n(Impossible de lire le fichier '%s'!  Continuer..)\r\n
41 \r\n(Impossible d'ajouter totalement: %s)
42 \r\n(%d ligne(s) ajout≈e(s) depuis le fichier %s.  Veuillez continuer...)\r\n
43 \r\n(%d ligne(s) ajout≈e(s) au message.  Veuillez continuer...)\r\n
44 \r\nErreur grave: Impossible d'ouvrir le fichier pour la lecture! \r\n
45 \r\nErreur grave: Impossible d'ouvrir le fichier de nouveau pour l'ajout!\r\n
46 \r\n(poursuivez l'entr≈e du message)\r\n
47 (vous devez pr≈ciser le(s) message(s) » inclure)\r\n
48 (impossible d'obtenir la commande 'readmail'. D≈sol≈...)\r\n
49 (Impossible d'ajouter le message demand≈. Continuer)\r\n
50 (Impossible d'ajouter tout le message demand≈. Continuer)\r\n
51 (%d ligne(s) ajout≈e(s) dans le message.  Veuillez continuer)\r\n
52 (Interruption. Encore une et la lettre sera annul≈e...)\n\r
$set 13
1 Nouveau courrier arriv≈!
2 %d nouveau(x) message(s) reµu(s)
3 Commande: 
4 Commande: 
5 expression introuvable!
6 Balayage du message pour les entr≈es dans l'agenda...
7 D≈sol≈ - fonction d'agenda d≈sactiv≈e
8 Faire suivre message
9 Aucun courrier » faire suivre!
10 Changement de bo—te » lettres
11 Aucun courrier » supprimer!
12 Modification de la bo—te » lettres
13 La bo—te » lettres est vide!
15 Faire suivre
16 Aucun courrier » faire suivre!
17 R≈ponse de groupe
18 Impossible d'exp≈dier une r≈ponse de groupe pour un formulaire!!
19 constitution des adresses...
20 Aucun courrier auquel r≈pondre!
21 Message avec en-t¡tes...
22 Lire Message
23 Limiter les messages affich≈s par...
24 Courrier
26 Message suivant
27 Options
28 Imprimer courrier
29 Aucun courrier » imprimer!
30 Sortie
31 Nouveau courrier!  Sortie annul≈e...
32 R≈ponse au message
33 Sortie annul≈e...
34 Aucun courrier » sauvegarder!
35 Sauvegarder Message
36 (? pour afficher la liste des dossiers)
37 Aucun courrier » marquer!
38 Aucun courrier » identifier comme restaur≈!
39 Aucun courrier » restaurer!
40 Sortie
41 Aucun courrier » v≈rifier
42 Nouveau message en cours
43 Commande inconnue: Entrez '?' pour obtenir de l'aide sur les commandes
44 d≈j» au premier message!
45 Aucun message » lire!
46 seulement %d message(s) s≈lectionn≈(s)!
47 seulement %d message(s)!
48 Num≈ro du message en cours = %d\t\t%d message(s) au total\n
49 En-t¡te de page = %d           \t\t%d page(s) possible(s)\n
50 \nFichier de courrier en cours : %s.\n\n
51 Appuyez sur une touche pour revenir : 
52 Aucun courrier pour ≈tablir un conduit!
53 La bo—te » lettres a ≈t≈ modifi≈e! --- relecture
54 [%d message(s) %s %s, et %d supprim≈s]
55 [message(s) stock≈s dans votre bo—te » lettres]
56 [tous les messages ont ≈t≈ supprim≈s]
$set 14
1 ERREUR-INCONNUE (%d)
2 Erreur inconnue - %d - Aucune description
$set 15
1 Enregistrer le(s) message(s) dans : 
3 Impossible d'annexer » '%s': %s
4 Impossible d'annexer int≈gralement » '%s': %s
5 Message(s) sauvegard≈(s)
6 Message %d annex≈ au fichier '%s'
7 Message %d sauvegard≈ dans le fichier '%s'
8 MAILDIR non d≈fini.  Extension de '%c' impossible
9 La valeur de $%s est inconnue!
10 Nom de fichier non valide. Le message n'est pas sauvegard≈.
11 Erreur popen.  Le message n'est pas sauvegard≈.
$set 16
1 \n\rErreur lors de l'ex≈cution de fstat avec le fichier %s!\n\r
3 impossible d'ouvrir le fichier %s
4 Le fichier %s existe d≈j»!  Remplacement...\n
5 Aucun courrier » lire.\n
$set 17
1 ‹chec de lecture de %d octets dans le fichier par ELM [acc…s]
$set 18
1 Erreur %s lors de l'ouverture de %s pour v≈rifier les zones!
2 Impossible de lire le message pour valider le formulaire!
3 Impossible d'ouvrir fichier nouveau formulaire pour sortie de formulaire!
4 ‹chec de cr≈ation du fichier de formulaires temporaire %s : %s
5 ‹chec de cr≈ation du fichier de formulaires temporaire %s : %s
7 Erreur %s lors de la suppression de la liaison du fichier %s
8 Erreur %s lors de la liaison de %s et %s
10 ‹chec de lecture de %d octets dans le fichier (%s) par ELM [acc…s]
11 Aucun formulaire dans ce message!?
13 Conception du formulaire erron≈e. Impossible de r≈pondre!
15 Impossible d'ouvrir "%s" comme fichier de sortie! (%s)
16 (Impossible d'ajouter au tampon d'≈dition : %s)\r\n
17 (Entrez toutes les lignes voulues, en terminant par un '.'\nsur une ligne distincte)\n
18 (Impossible d'ajouter au tampon d'≈dition : %s)\r\n
19 Impossible d'ajouter au tampon d'≈dition : %s
$set 19
1 Choix: 
2  (v≈rification) 
5 En-t¡te inconnu sp≈cifi≈!
6 ‹cran de modification des en-t¡tes de message
7 Choisissez 1…re lettre d'un en-t¡te existant, U)en-t¡te utilisateur ou <retour>
9 Dans combien de jours ce message doit-il expirer? 
10 Impossible!
11 La date d'expiration ne doit pas d≈passer huit semaines
12 Impossible d'entrer un blanc en d≈but d'en-t¡te!
13 Vous ne pouvez entrer de deux-points comme premier caract…re!
14 Le nom de la zone doit se terminer par un deux-points!
15 Impossible d'int≈grer des blancs dans un nom d'en-t¡te!
16 Trop d'utilisateurs. Copies non prises en compte!
17 S Objet: 
18 B Copies secr…tes: 
19 C Copies: 
20 E Expir: %s
21 A Intervention: 
22 P Priorit≈: 
23 I En r≈ponse »: %s
24 T °: %s
25 C Copie: %s
26 B Copies secr…tes: %s
27 R R≈ponse »: %s
28 S Objet: %s
29 A Intervention: %s
30 E Expir: %s
31 P Priorit≈: %s
32 D≈finir message en cours »: 
$set 20
1 \r\n‹diteur d'en-t¡tes Elm. Faites un choix dans la liste suivante:\n\r\n
2 Choix? q%c
3 \r\nEn-t¡te » modifier ('?' pour conna—tre les choix) : q%c
4 Visualiser les en-t¡tes:\r\n\n
5 Sortie de l'≈diteur d'en-t¡tes\r\n
6 Aide\r\n\n
7 %c\r\nChoix non valide!\r\n
8 Dans combien de jours ce message doit-il expirer? 
9 Vous ne pouvez pas exp≈dier de messages expir≈s!\r\n
10 La date d'expiration ne doit pas d≈passer huit semaines\r\n
11 \rTrop d'utilisateurs. Copies non prises en compte!\r\n
12 \rTrop d'utilisateurs. Copies secr…tes non prises en compte!\r\n
$set 21
1 Syst…me d'aide d'ELM
2 Touche pour laquelle vous d≈sirez de l'aide, '?' pour liste ou '.' pour sortir
3 Touche : 
5 Commande inconnue. Entrez '?' pour afficher la liste des commandes...
6 $ = Relecture de la bo—te » lettres pour ≈liminer les messages supprim≈s
7 ! = Passer au shell Unix de votre choix, ou entrer des commandes
9 | = Conduit entre le msg courant ou les msg marqu≈s et la commande sp≈cifi≈e
12 * = Passer au dernier message dans la bo—te » lettres en cours
13 - = Passer » la page de messages pr≈c≈dente de la bo—te » lettres en cours
14 '=' = Passer au premier messages de la bo—te » lettre en cours
15 + = Passer » la page de messages suivante de la bo—te » lettre en cours
16 / = Rechercher l'expression sp≈cifi≈e dans la bo—te » lettres en cours
17 < = Rechercher les entr≈es d'Agenda (si en service) dans le message en cours
20 a = Passer au sous-menu d'alias. Cr≈er et afficher des alias
21 b = Faire suivre un message comme si vous ne l'aviez pas visualis≈
22 c = Changer de bo—te » lettres, sortir de celle en cours
23 d = Marquer un message en cours pour suppression ult≈rieure
24 ^D = Marquer pour suppression tous les messages avec l'expression sp≈cifi≈e
26 f = Faire suivre le message en cours en indiquant votre adresse comme\n    adresse de retour
27 g = R≈ponse de groupe » l'exp≈diteur et » tous les destinataires
28 h = Afficher le message avec tous les en-t¡tes (ignorer la liste d'≈l≈ments\n    » supprimer)
29 j = Passer au message suivant. ‹quivalent » la touche fl≈ch≈e vers le bas
30 k = Passer au message pr≈c≈dent. ‹quivalent » la touche fl≈ch≈e vers le haut
31 l = Limiter l'affichage des messages selon les crit…res sp≈cifi≈s
32 m = Cr≈er et exp≈dier du courrier aux personnes sp≈cifi≈es
33 n = Lire le message suivant, puis d≈placer celui en cours au message suivant
34 o = Passez au sous-menu des options
35 p = Imprimer le message en cours ou les messages marqu≈s
36 q = Sortir du syst…me de messagerie, demande de suppression, sauvegarde, etc.
37 r = R≈pondre au message. R≈ponse transmise seulement » l'exp≈diteur du message
38 s = Sauvegarder le message en cours ou les messages marqu≈s dans le\n    fichier sp≈cifi≈
39 t = Marquer un msg pour des op≈rations ult≈rieures (ou annuler cette marque)
40 ^T = Marquer tous les messages avec l'expression sp≈cifi≈e
41 u = Restaurer - supprimer la marque de suppression du message
42 x = Sortir rapidement du syst…me de messagerie
43 <retour> = Lire le message en cours
44 ^L = R≈g≈n≈rer l'≈cran
45 Sortir rapidement du syst…me de messagerie
46 <num≈ro> = Faire du message ayant le num≈ro indiqu≈ le message en cours
47 impossible d'ouvrir le fichier d'aide %s
48 Appuyez sur une touche pour continuer : 
49 Appuyez sur une touche pour revenir : 
50 ^U = Restaurer-supprimer la marque 'D' sur tous les messages avec l'expression\n     sp≈cifi≈e
$set 22
1 Impossible d'ouvrir le fichier %s pour la mise au point\ndes donn≈es en sortie!\n
2 Vous devez sp≈cifier le type de terminal sur lequel vous travaillez\npour ex≈cuter\n
3 le programme "elm"...(vous devez r≈gler la variable environnementale "TERM")\n
4 Vous avez besoin d'un terminal adressable par curseur pour ex≈cuter "elm" \n
5 et entr≈e termcap introuvable pour "%s" -\nv≈rifiez la d≈finition de "TERM"...\n
6 L'initialisation du terminal a ≈chou≈: code de retour %d inconnu\n
7 Impossible de lire le mot de passe entr≈!
8 Impossible d'ouvrir la bo—te » lettres '%s':%s\n
9 \n\r\n\rImpossible d'allouer les en-t¡tes initiaux!\n\r\n
10 \n\r\n\rImpossible d'afficher l'index des en-t¡tes!\n\r
11 \n\r‹largir la colonne de la fen¡tre!\n\r
$set 23
1 Supprimer le(s) message(s)? (y/n) 
2 Aucune suppression
3 Supprimer tous les message(s)? (y/n) 
4 Aucune suppression
5 Conserver courrier dans le bac arriv≈e? (y/n) 
6 Bo—te » lettres non modifi≈e
7 Nouveau courrier arriv≈ - relecture...
8 [sauvegarde de %d message(s), et suppression en cours de %d]
9 [sauvegarde de tous les messages]
15 [suppression de tous les messages]
16 [aucun message » %s, et aucun » supprimer]
17 conserver
18 sauvegarder
19 Impossible d'annexer » %s: %s\n
20 Bo—te » lettres %s non modifi≈e: %s\n
21 Erreur %s (%s) sur stat(%s)
23 impossible de modifier le fichier de courrier!
24 erreur grave!!!
25 courrier sauvegard≈ dans %s
26 la liaison a ≈chou≈! %s - %s
27 ..sauvegarde du fichier de courrier '%s' vide..
29 \n\rErreur d≈cel≈e lors de l'essai de cr≈ation du\nfichier de verrouillage %s;\n\r
30 Impossible de cr≈er le fichier de verrouillage sans autorisation\nd'≈criture dans "%s"\n\r
31 R≈ception de courrier en cours...\t\ten attente...1 
32   Essai #%d: R≈ception de courrier en cours...en attente 
33 \nD≈lai d≈pass≈ - retrait du fichier de verrouillage en cours...
34 ‹limination du fichier de verrouillage en cours!
35 \n\rSuppression impossible du fichier de verrouillage en cours %s\n\r
36 \n\r\n\rAbandon apr…s %d it≈rations...\n\r
37 \n\rR≈essayez de lire votre courrier dans quelques minutes.\n\r\n\r
38 D≈lai d≈pass≈ pour les lectures du fichier de verrouillage.\nSortie du programme.
$set 24
1 Des crit…res de s≈lection existent d≈j» - voulez-vous en ajouter? (y/n) n%c
2 Ajout de crit…res...
4 Entrez les crit…res: 
5 "%s" n'est pas un crit…re de s≈lection!
6 aucun ≈l≈ment s≈lectionn≈
7 %d ≈l≈ment(s) s≈lectionn≈(s)
$set 25
1 courrier non exp≈di≈
2 \r\n\r\nCourrier annul≈!\n\r
3 \n\rAucun objet - Continuer avec le message? (y/n) n%c
4 Aucun objet - Continuer avec le message? (y/n) n%c
5 \n\r\n\rCourrier non exp≈di≈!\n\r
6 Trop de noms. Copies non prises en compte
7 Trop de noms. Copies secr…tes non prises en compte
8 Copier le message? (y/n) 
9 Envoyer le message » : 
10 Dest : 
11 Objet du message : 
12 Objet : 
13 Objet : <aucun>
14 Copies » : 
15 Copies secr…tes » : 
16 Dest : (%s)
17 Dest : %s
18           Dest : %s
$set 26
1 Impossible de cr≈er le fichier %s (%s)\r\n
2 Impossible de cr≈er le fichier %s (%s)
3 D≈sol≈, la transmission a ≈chou≈ : %s\n
4 fichier de formulaires introuvable!
5 Attention - impossible d'annexer le fichier de signatures: %s\r\n
6 Attention - impossible d'annexer le fichier de signatures: %s
7 Attention - impossible d'annexer tout le fichier de signatures: %s\r\n
8 Attention - impossible d'annexer tout le fichier de signatures: %s
13 courrier non exp≈di≈ sans en-t¡te DEST:! 
14 Impossible d'ouvrir le fichier de r≈ponse (%s)\r\n
15 Impossible d'ouvrir le fichier de r≈ponse (%s)
16 Impossible d'ouvrir le fichier de r≈ponse (%s)\n
17 Impossible de copier le message de d≈part dans %s : %s\r\n
18 Impossible de copier le message de d≈part dans %s : %s
19 Message exp≈di≈ via un autre syst…me de messagerie - %s\r\n
20 Message exp≈di≈ via un autre syst…me de messagerie  - %s
21 envoi de courrier...
23 \rcourrier envoy≈!      \n\r
24 Courrier envoy≈!
25 Rappeler le dernier message conserv≈? (y/n) y%c
26 Rappeler le dernier message conserv≈? (y/n) y%c
27 \n\rVos choix d'options sont les suivants:\n\r
28 S)end (envoyer message), E)dit (modifier message), H)eaders (modifier ou\najouter en-t¡tes) ou F)orget (annuler)\n\r
29 \n\rQuel est votre choix? s%c
30 Message non sauvegard≈, d≈sol≈.\n\r\n\r
32 Message sauvegard≈ dans le fichier "$HOME/%s"\n\r\n\r
33 \n\rR≈ponse incompr≈hensible, r≈pondez de nouveau...\n\r
34 Choisissez l'une des options suivantes en entrant la lettre correspondante
35 E)dit message,  H)eaders (modifier en-t¡tes), S)end ou F)orget (annuler): s%c
36 Choisissez: H)eaders (modifier en-t¡tes), S)end ou F)orget (annuler): s%c
37 Choisissez: E)dit msg, H)eaders (modifier en-t¡tes), S)end ou F)orget: s%c
38 Choisissez: E)dit msg, H)eaders (modifier), M)ake formul., S)end ou F)orget: s%c
39 Choisissez: E)dit msg, H)eaders (modifier), S)end ou F)orget (annuler): s%c
40 Message conserv≈ - Restauration possible au prochain F)orward, M)ail ou R)eply 
41 Aucune zone dans le formulaire!
42 Erreur %s d≈cel≈e lors d'un essai d'≈criture dans %s\r\n
43 Erreur %s d≈cel≈e lors d'un essai d'≈criture dans %s
44 Voulez-vous qu'une copie soit "r≈exp≈di≈e" depuis l'ordinateur ≈loign≈? (y/n) 
45 Oui - R≈exp≈dition comprise\n\r
46 "R≈exp≈dier" une copie » l'ordinateur ≈loign≈? (y/n) n%c
$set 27
1 Attention:ligne vierge dans %s non prise en compte!\r\n
2 Attention:ligne vierge dans %s non prise en compte!
3 Attention:≈chec d'ex≈cution de la commande entre \`\` dans l'en-t¡te\r\n
4 Attention:≈chec d'ex≈cution de la commande entre \`\` dans l'en-t¡te
5 la commande entre \`\` "%s" dans .elmheaders a ≈chou≈\r\n
6 la commande entre \`\` "%s" dans .elmheaders a ≈chou≈
$set 28
1  Un autre syst…me de messagerie est d≈j» en train de lire ce courrier!\n\r
2 \n\r [s'il y a une erreur, vous devrez supprimer '%s/%s%s']\n\r
3 Impossible d'ouvrir la bo—te » lettres '%s' (%s)
4 (? pour afficher la liste des dossiers)
5 Nom de la nouvelle bo—te » lettres: 
6 \n\rNom de la nouvelle bo—te » lettres: 
8 la lecture de cette bo—te » lettres est d≈j» en cours!
9 Impossible d'ouvrir le fichier '%s': %s
10 Relecture du fichier
11 Bo—te » lettres: %s
12 Impossible de supprimer la liaison du fichier de\ncourrier temporaire [%s]\n\r
13 Lecture dans %s, message: %d
14 Lecture dans %s, message: 0
15 Lecture du message: 0
17 La bo—te » lettres temporaire existe d≈j» !!
18 Sortie imm≈diate...
19 \nImpossible d'ouvrir le fichier %s pour l'utiliser\ncomme bo—te » lettres temporaire;\n
20 \nImpossible de rouvrir le fichier %s pour l'utiliser\ncomme bo—te » lettres temporaire;\n
21 \nImpossible de rechercher jusqu'» %ld (fin de la bo—te » lettres)\ndans %s!\n
22 Courrier en cours de diffusion » %s
23 \n\rLe fichier de courrier est alt≈r≈!!  Impossible de le lire!!\n\r\n\r
24 Impossible de copier le fichier %s dans la bo—te » lettres temporaire: %s
25 D≈sol≈, sortie sans aucun changement dans la bo—te » lettres...
26 \n\r\n\rM≈moire insuffisante!  ‹chec du message #%d\n\r\n\r
27 \nImpossible de rouvrir %s comme fichier de courrier temporaire;\n
28 Le fichier de courrier est alt≈r≈!! Impossible de le lire!!
29 Nom de fichier non valide. La bo—te » lettres ne peut ¡tre modifi≈e.
30 Erreur popen. La bo—te » lettres ne peut ¡tre modifi≈e.
$set 29
1 S≈lectionnez 1…re lettre de la ligne Option, '>' pour Sauvegarder, ou R)etour
2 Commande: 
3 Sauvegarder les options dans .elm/elmrc...
4 Commande inconnue!
5 -- ‹diteur d'options Elm --
6 (<Barreesp> pour basculer ou autre pour sortir)
7 <Barreesp> pour changer
8 <Barreesp> suivant, R)everse
9 reclassement de la bo—te » lettres...
10 Ordre du tri: de l'envoi le plus r≈cent au moins r≈cent
11 Ordre du tri: de la r≈ception la plus r≈cente » la moins r≈cente
12 Ordre du tri: de l'ajout le plus r≈cent au moins r≈cent dans la bo—te » lettres
13 Ordre du tri: par nom d'exp≈diteur, en ordre alphab≈tique d≈croissant
14 Ordre du tri: du plus long message au plus court
15 Ordre du tri: par objet, en ordre alphab≈tique d≈croissant
16 Ordre du tri: par ≈tat d≈croissant - allant des msg supprim≈s aux msg marqu≈s...
17 Ordre du tri: de l'envoi le moins r≈cent au plus r≈cent
18 Ordre du tri: de la r≈ception la moins r≈cente » la plus r≈cente
19 Ordre du tri: de l'ajout le moins r≈cent au plus r≈cent dans la bo—te » lettres
20 Ordre du tri: par nom d'exp≈diteur
21 Ordre du tri: du plus court message au plus long
22 Ordre du tri: par objet
23 Ordre du tri: par ≈tat - allant des messages marqu≈s aux messages supprim≈s...
24 Fichier oÀ les entr≈es d'agenda provenant de messages sont sauvegard≈es.
25 Programme appel≈ pour afficher les messages un » un (essayez 'builtin')
26 ‹diteur utilis≈ pour l'envoi des messages, etc.
27 R≈pert. des dossiers utilis≈ quand '=' (etc) fait partie des noms de fichiers
28 Cette option d≈termine l'affichage du mini-menu
29 Affichage des noms et adresses du courrier, ou des noms seulement
30 Emplacement de sauvegarde automatique des copies de messages en partance.
31 Faµon dont les imprim≈s sont g≈n≈r≈s. "%s" sera remplac≈ par le nom de fichier.
32 Utilis≈ pour sp≈cifier les crit…res de tri des bo—tes » lettres
33 Lors de l'envoi de courrier, votre nom complet sera enregistr≈ ainsi.
34 Permet de d≈finir si le curseur ELM est une fl…che ou une barre en ≈vidence.
35 Votre niveau de connaissance du syst…me de messagerie Elm.
36 Touche pour laquelle vous d≈sirez de l'aide, '?' pour liste ou '.' pour sortir
37 Touche : 
38 %c n'est pas utilis≈ dans cette section
39 %s = Retour au menu principal avec les valeurs d'option.
40 L'entr≈e est nulle, la valeur par d≈faut sera utilis≈e!
41 R≈pertoire de dossiers introuvable -- %s
42 Voulez-vous cr≈er le r≈pertoire (y/n)? y%c
43 Impossible de cr≈er le r≈pertoire, la valeur par d≈faut sera utilis≈e!
44 La valeur par d≈faut sera utilis≈e!
45 Utiliser la valeur pr≈c≈dente
46 Lors de l'envoi de courrier, remplacer les tabulations par des espaces ou non.
47 C fichier d'agenda   : %s
48 D afficher avec      : %s
49 D afficher avec      : %s
50 E ≈diteur            : 
51 E ≈diteur            : %s
52 F r≈pertoire dossiers: 
53 F r≈pertoire dossiers: %s
54 S crit…res de tri    : %s
55 O courrier sauvegard≈: 
56 O courrier sauvegard≈: %s
57 P impr. courrier avec: 
58 P impr. courrier avec: %s
59 Y votre nom complet  : 
60 Y votre nom complet  : %s
61 A curseur fl…che     : %s
62 M affichage de menu  : %s
63 U niveau utilisateur : %s
64 N noms seulement     : %s
65 T Tabul. par espaces : %s
$set 30
1 Commande: 
2 %s messages correspondant » l'expression...
3 Certains messages sont d≈j» marqu≈s
4 Un message est d≈j» marqu≈
5 - Supprimer le(s) rep…re(s)? y%c
6 Entrez l'expression: 
7 %s %d messsage(s)
8 avec marque
9 marqu≈ pour suppression
10 non supprim≈
11 aucune correspondance - aucun message %s
12 / = recherche dans tous les messages
13 recherche: 
14 recherche: (dans toute la bo—te » lettres):
15 la seule occurrence est dans le message en cours
16 recherche de l'expression dans la bo—te » lettres...
17 ELM [recherche] n'a pas trouv≈ %ld octets dans le fichier (%s)
$set 31
1 \n\r\n\rImpossible d'allouer (malloc) %d octets d'espace m≈moire!!\n\r\n\r
$set 32
1 \n\rAttention:\n\r
2 Tous les fichiers Elm commanµant par un 'point' devraient ¡tre dans leur \n\r
3 r≈pertoire -- $HOME/.elm --. D≈sirez-vous que le syst…me les d≈place\n\r
4 [si vous r≈pondez non, les fichiers ne seront pas pris en compte] (y/n)? y%c
5 \n\rLes fichiers n'ont pas ≈t≈ d≈plac≈s.\n\r
6 Ligne %d du fichier ".elm/elmrc" mal constitu≈e:\n> %s\n
7 Erreur de lecture du fichier '.elm/elmrc';\n
8 Ligne %d: impossible d'identifier la cl≈ de tri '%s'!\n
9 fichier "signature" pr≈cis≈ de faµon d≈su…te dans le fichier .elm/elmrc -\nNon pris en compte!\n\r
10 \t("signature" doit inclure un nom de fichier et non on/off)\n\r\n
11 Attention: Nombre de r≈exp≈dition plus grand que %d (max transits) -\nNon pris en compte.\n
12 Attention: le d≈lai imparti est d≈fini » moins de 10 secondes -\nNon pris en compte.\n
13 Ligne %d incompr≈hensible dans le fichier ".elm/elmrc":\n> %s\n
14 Trop d'en-t¡tes cach≈s!  Sortie...\n
15 Trop d'en-t¡tes cach≈s - m≈moire insuffisante! Sortie...\n
16 \n\rM≈moire insuffisante pour la liste des en-t¡tes cach≈s. Sortie.\n\r
17 \n\rImpossible de r≈soudre la variable environnementale '%s'\n\r
18 \n\rImpossible de r≈soudre la variable environnementale '%s' -\nnom de fichier trop long
19 Elm a besoin du r≈pertoire -- $HOME/.elm pour stocker vos\nfichiers elmrc et d'alias.\n\r
20 D≈sirez-vous cr≈er le r≈pertoire maintenant (y/n)? y%c
21 \n\rOk.\tL'op≈ration sera ex≈cut≈e.\n\r
22 \n\rImpossible de cr≈er le r≈pertoire.   * %s *\n\r
23 \n\rOk.\tMais vous risquez d'avoir des probl…mes par la suite.\n\r
24 Impossible de trouver le r≈pertoire de dossiers -- %s\n\r
$set 33
1 D≈sol≈ - impossible d'ouvrir le fichier %s pour ≈crire (%s)
2 D≈sol≈ - impossible d'annexer au fichier %s: %s
3 D≈sirez-vous vraiment r≈exp≈dier ce message (y/n) ? y%c
4 Faire suivre message annul≈
5 renvoi du courrier...
6 Courrier renvoy≈
7 trop d'adresses pour faire suivre - courrier non exp≈di≈ !
$set 34
1 <aucune modification autoris≈e>
2 Modifiez le message en partance (y/n) ? 
3 ‹chec de lecture de %d octets dans le fichier (%s) par ELM [acc…s]
4 Impossible de cr≈er l'adresse de retour - limite de transits atteinte!
$set 35
1 impossible de rechercher %d octets dans le fichier (%s)
2 impossible de rechercher %d octets dans le fichier (%s)
$set 36
1 Attention: sauvegarde sans les commentaires - impossible d'obtenir %s
2 Impossible de sauvegarder la Configuration:\nerreur d'≈criture dans %s [%s]
3 Options sauvegard≈es dans le fichier %s
4 ‹chec de la sauvegarde de "%s" ..... continuer
5 Impossible de sauvegarder enti…rement la liste des en-t¡tes cach≈s
6 Impossible de sauvegarder enti…rement "alternatives"
7 Impossible de sauvegarder la configuration: chemin trop long
$set 37
1 variable 'SAVEFILE' non d≈finie!\r\n
2 variable 'SAVEFILE' non d≈finie!
3 impossible d'annexer » %s : %s\r\n
4 impossible d'annexer » %s : %s
5 impossible de lire le fichier %s: %s\r\n
6 impossible de lire le fichier %s: %s
$set 38
1 La bo—te » lettres est '%s' [Elm %s]
3 La bo—te » lettres est '%s' avec %d affich≈s sur %d [Elm %s]
4 La bo—te » lettres est '%s' avec %d message(s) [Elm %s]
5 Utilisez les commandes suivantes en appuyant sur le premier caract…re
6 D)elete ou U)ndelete courrier,  M)ail un message,  R)eply ou F)orward,  Q)uit
7 Pour lire un message, <retour>. j = vers le bas, k = vers le haut, ? = aide
8 |=conduit, !=shell, ?=aide, <n>=d≈finir » n, /=expression de recherche
9 A)lias, C)hanger bo—te), D)elete, F)orward, G)roupe r≈ponse, M)ail, N)ext,
10 O)ptions, P)rint, R)≈pondre, S)auvegarder), T)ag, Q)uit, U)ndelete, ou eX)it
$set 39
1 Seulement %d messages!
2 vous ne pouvez pas lire CE message!
3 ELM n'a pas retrouv≈ %d octets dans le fichier (%s)
4 Impossible d'≈tablir un conduit vers %s [%s]
5 %s(message adress≈ » %.60s)\n
6 %s(message adress≈ » %s)\n
7 \n(** Ce message est marqu≈ Priv≈
8 \n(** Ce message est marqu≈ Confidentiel
9 \n(** Ce message est marqu≈ Urgent
10 , Urgent
11  et Urgent
12 \n(** Ce message a expir≈
13 , et a expir≈
14 Erreur de relecture:impossible de rouvrir la bo—te » lettres!!
15  Appuyez sur <retour> pour revenir au menu principal : 
$set 40
1 Commande: ≈tablir un conduit (pipe)
2 Commande: appel syst…me
3 balayage des entr≈es d'agenda impossible!
4 Commande: faire suivre message
5 message marqu≈ pour la suppression
6 Message marqu≈ pour la suppression. Commande ? 
7 Commande: diffuser message
8 Commande: r≈ponse de groupe
9 Commande: exp≈dier le message
11 En file d'attente d'impression. Commande ? 
12 Commande: r≈pondre au message
13 Commande: sauvegarder le message
14 message marqu≈
15 message marqu≈.  Commande? 
16 suppression du message annul≈e
17 Suppression du message annul≈e .  Commande? 
18 Demande (revenir » la page d'I)ndex) ? 
$set 41
1   Lire  Message 
2 Exp≈dierMessage 
3 R≈pondreMessage 
4 SauvgardMessage 
5  Suppr  Message 
6 AnnulSupMessage 
7 Modifier Bo—te 
9  Suppr/ Annuler 
10 ImprimerMessage 
11  Sortir   Elm  
12  Alias  En cours
13 V≈rifierPersonne
14 AfficherSyst…me 
15  Suppr   Alias  
16  Cr≈er   Alias  
17  Menu   Initial 
18   Oui
19   Non
20   Page  Suivante
21 Message Suivant 
22 Message   Pr≈c  
25 Exp≈dierMessage 
27  R≈pert Courrier
28  R≈pert Initial 
29  Bo—te  Arriv≈e 
30 Annuler
32 Annuler
33 ModifierEn-t¡tes
34 Exp≈dier
35 Modifier Formul
38 ModifierMessage
41 Exp≈dier
42 ModifierMessage
43 ModifierEn-t¡tes
44 Exp≈dier
45 R≈soudreAdresse
46 Afficher Usager
47  Objet
48 Exp≈dit
49   Dest
50   Sans   limite
$set 42
1 tri des messages par %s
$set 43
1 niveau d'imbrication d'appels get_token sup≈rieur » %d!
2 boucle d'alias possible. Un alias n'a pas ≈t≈ r≈solu apr…s %d niveaux!
$set 44
1 (nom de shell pour appeler un shell)
2 Commande du shell: 
3 \n\n(Si l'affichage est alt≈r≈, utilisez ^L pour le r≈tablir)\n
4 \n\nAppuyez sur une touche pour revenir » ELM: 
5 Le code de retour ≈tait %d
6 ‹tablissez un conduit entre les messages marqu≈s et: 
7 ‹tablissez un conduit entre le message marqu≈ et: 
8 ‹tablissez un conduit entre le message en cours et: 
9 \n\nAppuyez sur une touche pour revenir » ELM: 
11 Impression impossible - option "printmail" non d≈finie!
12 mise en file d'attente...
13 Message(s) mis en file d'attente pour l'impression
14 L'impression a ≈chou≈, code de retour %d
15 \n\rContenu du r≈pertoire de dossiers:\n\r\n\r
16 Trop de messages » imprimer - seulement %d message(s) mis en file d'attente
17 Trop de messages » imprimer ou longue commande d'impression
18 Trop de messages ou commande avec conduit trop longue
$set 45
1 \nSortie d'urgence!  Tous les fichiers temporaires sont intacts!\n\n
2 Erreur: pile d'≈tats alt≈r≈e
$set 46
1 \n\nArr¡t. Entrez "fg" pour revenir » Elm\n\n
2 De retour dans Elm. (Vous devrez peut-¡tre r≈g≈n≈rer l'≈cran)
3 \n\nSignal d'instruction interdite!\n\n
4 \n\nSignal d'exception de calcul en virgule flottantel!\n\n
5 \n\nSignal d'erreur de bus!\n\n
6 \n\nSignal de violation de segment!\n\n

