$set 1
1 %s: Langue %s inconnue. Utilisation de la langue par d≈faut.\n
2 %s: permission refus≈e\n
3 arr¡t pr≈matur≈, impossible d'ouvrir le fichier fifo %s\n
4 relancez et consultez le fichier de configuration
5 arr¡t pr≈matur≈, impossible d'ouvrir le fichier fifo %s\n
6 arr¡t pr≈matur≈, impossible de lire » partir du fichier fifo %s\n
7 arr¡t pr≈matur≈, fichier de configuration %s ouvert pour erreur de lecture\n
8 arr¡t pr≈matur≈, fichier d'action %s ouvert pour erreur d'≈criture\n
9 arr¡t pr≈matur≈, aucune ligne ≈v≈nement sp≈cifi≈e dans %s\npour la ligne %d "%s"\n
10 arr¡t pr≈matur≈, aucune configuration sp≈cifi≈e dans %s\n
11 arr¡t pr≈matur≈, ≈v≈nement %s reproduit, sp≈cifi≈ dans fichier %s\n
12 arr¡t pr≈matur≈, erreur de syntaxe » la ligne "%s"\ndu fichier de configuration %s\n
13 Temp≈rature ramen≈e » la normale.
14 ***** ATTENTION - SURCHAUFFE IMMINENTE (Seuil OVERTEMP_CRIT atteint) *****
15 Temp≈rature sup≈rieure » la normale. R≈tablissez-la.
16 ***** ATTENTION - SURCHAUFFE (Seuil OVERTEMP_EMERG atteint) *****
17 La temp≈rature a d≈pass≈ le seuil OVERTEMP_CRIT.  R≈tablissez-la imm≈diatement.
18 Erreur interne:valeur %d non valide transmise » %s.
19 Interruption par signal %d\n
20 syntaxe:%s [-f fichier_de_configuration]\n
