$set 1
1 L'option -x n'est pas disponible.\n
2 Option %s inconnue\n
3 [Appuyez sur Retour pour continuer]
101 syntaxe: ed1000 [-r] [fichier]\n
$set 2
1 Adresse1 > adresse2|La premi…re adresse est sup≈rieure » la deuxi…me
2 Valeur erron≈e|Valeur autre que z≈ro requis
3 Adresse non admise|Aucune adresse admise dans cette commande
4 Erreur de syntaxe dans l'adresse
5 Aucune correspondance|Recherche a atteint FIN sans trouver de correspondance
6 Aucune correspondance|Recherche a atteint D‹BUT sans trouver de correspondance
7 ‹chec|Expression introuvable
8 Les marques sont ' et a-z
9 Marque non d≈finie|R≈f≈rence » une marque non d≈finie
10 Adresse n≈gative|Adresse n≈gative - la premi…re ligne du tampon est 1
11 D≈passe le nombre de lignes|Le tampon ne contient pas tant de lignes
$set 3
1 D≈calage hors limite|D≈calage apr…s la commande trop long
2 R≈pertoire initial inconnu
3 Que d≈sirez-vous marquer?|%s n≈cessite une lettre » sa suite
4 Marque erron≈e|La marque doit pr≈ciser une lettre
5 La sauvegarde a ≈chou≈!
6 Fichier sauvegard≈.
7 Aucune modification|Aucune modif depuis la derni…re (:rewind! remplace)
8 Version HP %s
9 Registre erron≈
10 ° la fin de fichier|° la fin de fichier
11 Quoi?|Caract…re de commande '%c' inconnu
12 Aucune gestion des travaux|Ce shell ne g…re pas les travaux
101  Ed1000 : 
102  Entrez ? pour obtenir de l'aide\n
$set 4
1 Caract…re en trop|Caract…res en trop » la fin de la commande
2  [Attention - %s est incomplet]\n                                   \nVos modifications seront perdues si vous n'entrez pas de commande\nd'≈criture avant de sortir. S'il s'agissait du fichier original,\nce qu'il contenait a ≈t≈ d≈truit.\nContactez l'administrateur de syst…me avant de sortir, si vous avez\nbesoin d'aide.\n
3 %d fichiers|%d fichiers » modifier
4 Plus de fichiers|Plus de fichiers » modifier
5 Caract…re en trop|Caract…res en trop » la fin de la commande "%s"
6 %d de fichiers restants|%d fichiers restants » modifier
7 Aucune modification|Aucune modif depuis la derni…re (:%s! remplace)
8 Quoi?|%s: cette commande n'existe pas avec le mode open ni mode visual
9 Quoi?|%s: cette commande n'est pas accept≈e par l'≈diteur
10 [Appuyez sur Entr≈e pour continuer] 
$set 5
1 M≈moire insuffisante|M≈moire insuffisante- trop de lignes dans le fichier
2 D≈bordement de lignes|La jonction des lignes cr≈erait un r≈sultat trop long
3 %s oÀ?|%s n≈cessite une adresse en queue
4 Ce d≈placement n'aurait aucun effet!
5 D≈placement vers une ligne d≈plac≈e
6 Impossible d'int≈grer » un changement global ou » une macro (global/macro)
7 Ligne trop longue|La ligne r≈sultant du d≈calage serait trop longue
8 Descripteur erron≈|Entrez un descripteur par ligne
9 Aucun descripteur ant≈rieur
10 %s: entr≈e de fichier tags erron≈
11 Aucune ≈criture|Aucune ≈criture depuis le dernier changement (:tag! remplace)
12 Aucun fichier tags
13 %s: pas de descripteur de ce type|%s: pas de descripteur de ce type dans tags
14 Extraction impossible dans changement global ou macro (global/macro)
15 \n° la fin du fichier
16 ° la fin de fichier
17 Entrez FIN
18 Entrez D‹BUT
19 Impossible d'annuler dans global|Impossible d'annuler dans commandes global
20 Rien » annuler
21 Rien de modifier|La derni…re commande d'annulation n'a rien modifi≈
22 lhs manquant
23 rhs manquant
24 rhs manquant
25 Aucune r≈currence en queue
26 Correspondance trop risqu≈e » ≈tablir
27 Aucune r≈currence en queue
28 lhs manquant
29 Correspondance non ≈tablie|Correspondance avec macro non ≈tablie
30 Trop de macros
31 Trop de macros de format texte
$set 6
1 Ligne d'entr≈e trop longue
$set 7
1 Aucun fichier|Pas de nom de fichier en cours
2  [Lecture seulement]
3  [Pas modifi≈]
4  [Modifi≈]
5 Aucun fichier
6  ligne %d de %d --%ld%%--
7 Expression trop longue
8 D≈bordement du tampon des arguments
9 Aucun nom de fichier de remplacement|Pas de nom de fichier pour remplacer
10 Aucun nom de fichier en cours|Pas de nom de fichier pour remplacer %%
11 Impossible d'≈tablir le conduit avec une requ¡te globale (glob)
12 Impossible de dupliquer (fork) pour ex≈cuter la requ¡te globale (glob)
13 La liste d'arguments est trop longue
14 La liste d'arguments est trop longue
15 Aucune correspondance
16 Nom de fichier manquant
17 Ambigu|Trop de noms de fichiers
18 Nom de fichier trop long
19  [Nouveau fichier]
20  Fichier sp≈cial en mode bloc
21  T≈l≈type
22  Fichier sp≈cial en mode caract…re
23  R≈pertoire
24  Ex≈cutable
25  Fichier translatable
26  Archive
27  [Lecture seulement]
28 La syntaxe d'≈criture est 'w' et 'w>>'
29 Aucun fichier|Aucun nom de fichier en cours
30  Le fichier existe| Fichier existant - utilisez "w! %s" pour le remplacer
31  Ce fichier est accessible en lecture seulement
32  Ce fichier est accessible en lecture seulement
33  Utilisez "w!" pour sauvegarder dans le tampon partiel
34  [Nouveau fichier]
35  [Fichier existant]
36  [Derni…re ligne incompl…te]
37  Ligne trop longue
38 Trop de fichiers source embo—t≈s
39  %d lignes, %D caract…res
40  (%D nul)
101 Le fichier existe|\nFichier existant - utilisez "wr ou er %s" pour le remplacer
102  Utilisez "wr" pour sauvegarder dans le tampon partiel
$set 8
1 Requ¡te glob dans requ¡te glob|Requ¡te globale dans requ¡te glob non admise
2 Requ¡te n≈cessitant RE|Expression standard (RE) manquante dans requ¡te glob
3 Commande de requ¡te globale (global) trop longue
4 boucle de remplacement
5 ‹chec|La concordance de l'expression de remplacement a ≈chou≈.
6 Remplacement n≈cessite RE|Express stand (RE) n≈cessaire pour remplacer
7 Aucune RE ant≈rieure|Aucune expression standard (RE)ant≈rieure
8 Aucune RE de remplac|Aucune expression standard de remplacement » reproduire
9 Express de rempl trop longue|Express de rempl trop longue - limite 256 caract
10 D≈bordement de ligne|D≈bordement de ligne dans le remplacement
11 %d remplacements|%d remplacements
12 sur %d lignes
13 Expressions standards (RE) ne peuvent ¡tre s≈par≈es par lettres ou chiffres
14 Aucune (RE) rep≈r≈e|Aucun balayage ant≈rieur de l'express stand
15 Aucune (RE) remplac≈e|Aucune express stand ant≈rieure remplac≈e
16 Express stand RE erron≈e|Expression standard \\ doit ¡tre suivie de / ou ?
17 Aucune express stand (RE) ant≈rieure|Aucune expression standard ant≈rieure
19 Express stand (RE) trop complexe|Expression standard trop complexe
20 \\ manquant(ou \\ en trop)|Nombre in≈gal de \\(et \\) dans l'express stand
21 D≈bordement dans \\(!|Trop de \\(sous-express dans expression standard RE
22 Ordre ≈l≈ment erron≈|‹l≈ment non ordonn≈ sp≈cifi≈ l» oÀ un est requis
25 Fin plage erron≈e|Premier caract fin > deuxi…me ou classe caract utilis≈e
26 Classe caract…res erron≈e |Type classe caract…res non valide '[: :]' nomm≈e
27 Liste non concordante|Liste associ≈e vide ou incompl…te: '[]' ou '[^]'
29 Pas nouvel lignes dans express stand|Impossible sauter nouvelles lignes
30 \\ en queue|\\ en queue impossible dans une expression standard
32 Erreur de syntaxe dans express|Syntaxe de l'express stand non valide
$set 9
1 %s: option inexistante|%s:option inexistante - 'set all' = toutes les valeurs
2 Option %s ne permet pas d'alterner
3 = manquant |= manquant dans l'instruction de l'option %s
4 Chiffres requis|Chiffres requis apr…s =
5 Cha—ne trop longue|Cha—ne trop longue dans l'instruction de l'option
6 Impossible de changer le type du terminal » partir du mode open/visual
$set 10
1 %d lignes
2 Adresse autre que z≈ro requise|Commande n≈cessitant une adresse autre que z≈ro
3 Aucune ligne|Aucune ligne dans le tampon
4 %d lignes en plus|%d lignes en plus dans le fichier apr…s %s
5 %d lignes en moins|%d lignes en moins dans le fichier apr…s %s
6 M≈moire insuffisante|M≈m insuff pour sauveg ligne r≈cup≈ration- utilisez ed
44 Erreur syst…me %d
45 emt trap, _ovno est %d |emt trap, _ovno est %d   - r≈essayez
46 \r\nVotre fichier a ≈t≈ sauvegard≈\r\n
47 \nInterruption
$set 11
1 Fichier tmp trop gros
2 Fichier tmp trop gros
3 Espace d'enregistrement insuffisant (ugh)
4 Rien dans le registre %c
5 Impossible d'ins≈rer une ligne partielle dans une macro
6 Rien dans l'enregistrement %c
7 Enregistrement trop long|Enregistrement trop long pour la m≈moire
$set 12
1 %s: type de terminal inconnu
$set 13
1 Comm de passage au shell incompl|Commande de passage au shell incompl…te;\n-utilisez  'shell' pour appeler un shell
2 Commande trop longue
3 Aucune commande ant≈rieure|Aucune commande ant≈rieure pour remplacer !
4 Aucun nom de fich de rempl|Aucun nom de fichier pour remplacer
5 Aucun nom de fichier|Aucun nom de fichier pour remplacer %%
6 [Aucune modification]|[Aucune modification depuis la derni…re]
7 Aucune commande ant≈rieure|Aucune commande ant≈rieure » reproduire
8 Impossible de cr≈er un conduit pour le filtre
9 Plus de processus
10 Aucun %s!\n
11 Impossible de cr≈er un conduit
12 Plus de processus
13  Impossible de cr≈er un conduit pour le syst…me de reprise
14  Impossible de dupliquer (fork) pour ex≈cuter la reprise
15  Aucun sous-programme de reprise
16 %d: termin≈ avec le signal %d
17  -- noyau vid≈
$set 14
1 ‹chec|Expression introuvable sur la ligne demand≈e
2 Mode open/visual r≈current non admis
3 Type de terminal inconnu - le type connu est '%s'.
4 [Utilisation du mode open]
5 Le mode visuel n≈cessite curseur d≈plaµable ou capacit≈ de revenir en arri…re
6 Impossible d'utiliser le mode visuel sur un terminal qui surimprime
7 Le mode visuel n≈cessite des fonctions de r≈g≈n≈ration d'≈cran
8 Le mode visuel n≈cessite les fonctions de d≈filement
9 ‹cran trop grand pour le tampon interne
10 Connaissance insuffisante de votre terminal pour utiliser %s
11 Terminal trop large
12 ‹cran trop grand
$set 15
1 Erreur interne: vscroll
2 Aucune ligne dans le tampon
3 Erreur interne: vredraw
$set 16
1 Erreur de lecture en entr≈e
2 %d ligne(s) en plus
3 %d ligne(s) en moins
4 %d ligne
5 Macro trop longue|Macro trop longue  - peut-¡tre r≈currente?
$set 17
1 Boucle de macros sans fin
$set 18
1 Boucle de macros sans fin
2 Ligne trop longue
3 Ligne trop longue
$set 19
1 Erreur interne: vclreol
2 Erreur interne: vgoto
3 Ligne trop longue pour le mode open
4 Ligne trop longue
$set 20
1 (pointeur null)
