$set 1
2 Erreur de lecture du tampon
3 Impossible de trouver un nom \n
4 Copie d'un tampon de l'≈diteur a ≈t≈ sauvegard≈e » l'arr¡t du syst…me.\n
5 Copie d'un tampon de l'≈diteur sauvegard≈e » l'arr¡t pr≈matur≈ de l'≈diteur.\n
6 Aucun nom associ≈ » ce tampon; il a donc ≈t≈ nomm≈ "PERDU".\n
7 Copie d'un tampon de l'≈diteur du fichier "%s"\na ≈t≈ sauvegard≈e » l'arr¡t du syst…me.\n
8 Copie du tampon du fichier "%s"\nde l'≈diteur sauvegard≈e » l'arr¡t pr≈matur≈ de l'≈diteur.\n
9 Tampon r≈cup≈rable » l'aide de la commande "recover" de l'≈diteur.\n
10 Pour ce faire, entrez la commande "ex -r %s".\n
11 Ceci est ≈galement valable pour "edit" et "vi".\n
