$set 1
1 fbackup(1001): m≈moire virtuelle insuffisante\n
2 fbackup(1002): sauvegarde non termin≈e:\nsortie du programme de lecture ou d'≈criture
3 fbackup(1003): m≈moire virtuelle insuffisante\n
4 fbackup(1004): la session commence sur %s\n
5 fbackup(1005): temps d'ex≈cution: %d secondes\n
6 fbackup(1006): trop de lecteurs sp≈cifi≈s\n
7 fbackup(1007): trop d'enregistrements m≈moire sp≈cifi≈s\n
8 fbackup(1008): impossible d'obtenir le r≈pertoire de travail en cours\n
9 fbackup(1009): impossible d'obtenir le segment de m≈moire partag≈e sp≈cifi≈\n
10 fbackup(1010): semget a ≈chou≈ pour le s≈maphore\n
11 fbackup(1011): shmat a ≈chou≈ pour le segment de m≈moire partag≈e\n
12 fbackup(1012): session relanc≈e avec succ…s\n
13 fbackup(1013): impossible de relancer la session\n
14 fbackup(1014): la duplication (fork) a ≈chou≈ pour le lecteur %d\n
15 fbackup(1015): acc≈d≈ apr…s l'ex≈cution du programme de lecture (execl)\n
16 fbackup(1016): semctl a ≈chou≈\n
17 fbackup(1017): la duplication (fork) a ≈chou≈ pour le programme d'≈criture\n
18 fbackup(1018): acc≈d≈ apr…s l'ex≈cution du programme d'≈criture (execl)\n
19 fbackup(1019): attention:\naucun des fichiers sp≈cifi≈s ne n≈cessite une sauvegarde\n
20 fbackup(1020): sortie inattendue\n
21 fbackup(1021): la liste des fichiers a ≈t≈ r≈cup≈r≈e\n
22 fbackup(1022): impossible de r≈cup≈rer la liste des fichiers\n
23 fbackup(1023): relancerez-vous cette session plus tard?\n
24 fbackup(1024): l'≈tat de cette session a ≈t≈ sauvegard≈\n
25 fbackup(1025): l'≈tat de cette session n'a pas ≈t≈ sauvegard≈\n
26 fbackup(1026): sortie sans sauvegarde de l'≈tat de la session\n
27 fbackup(1027): sauvegarde non termin≈e:\nsortie du programme de lecture ou d'≈criture
28 fbackup(1028): SIGTERM (fin de processus) reµu; nettoyage et sortie\n
29 fbackup(1029): sortie inattendue\n
101 fbackup(1101): fin inattendue des fichiers » sauvegarder\n
102 fbackup(1102): impossible d'acc≈der au fichier %s\n
103 fbackup(1103): impossible d'ouvrir le fichier %s\n
104 fbackup(1104): m≈moire virtuelle insuffisante\n
105 fbackup(1105): impossible d'ouvrir le r≈pertoire %s\n
106 fbackup(1106): m≈moire virtuelle insuffisante\n
107 fbackup(1107): unable to get file control information for file %s\n
108 fbackup(1108): file %s has been locked,\n and will not be backed up\n
201 fbackup(1201): impossible de red≈finir temps d'acc…s et modification\npour le fichier %s\n
202 fbackup(1202): utilisateur ou groupe inconnu sp≈cifi≈\ndans l'ACL pour le fichier: %s;\nles entr≈es optionnelles ne sont pas sauvegard≈es.\n
301 fbackup(1301): reprise de l'ex≈cution » partir du fichier %d\n
401 fbackup(1401): argument en trop: %s non pris en compte\n
402 fbackup(1402): ne pr≈cisez pas plus d'un niveau pour fbackup\n
403 fbackup(1403): vous devez pr≈ciser au moins un fichier de sortie\n
404 fbackup(1404): aucun fichier sp≈cifi≈; (utilisez l'option -i ou -g)\n
405 fbackup(1405): aucune option [0-9ieg] ne peut ¡tre utilis≈e avec -R\n
406 syntaxe: /etc/fbackup -f p≈riph [-f p≈riph] ... [-0-9] [-nsuvyH]\n
407 \t [-i chemin] ... [-e chemin] ... [-g graph] ... [-d chemin] [-I chemin]\n\t [-V chemin] [-c config]\n
408 \nsyntaxe: /etc/fbackup -f p≈riph [-f p≈riph] ... -R relance [-nsuvyH]\n
409 \t [-d chemin] [-I chemin] [-V chemin] [-c config]\n\n
410 fbackup(1410):\npour l'ex≈cution de la mise » jour (-u), un fichier graph (-g)\n
411 \t doit ¡tre sp≈cifi≈ et aucun fichier include ou exclude (-i, -e)\n
412 fbackup(1412): impossible d'ouvrir le fichier graphique %s\n
413 fbackup(1413): impossible d'ouvrir le fichier de configuration %s\n
414 fbackup(1414):\n≈tiquette du fichier configuration non valide (%s) non prise en compte\n
415 fbackup(1415): erreur dans le fichier de configuration » la ligne %d\n
416 ligne erron≈e:\n%s\n
417 fbackup(1417): impossible d'ouvrir le fichier dates %s en lecture\n
418 fbackup(1418): le dernier niveau %d de session pour graph %s ≈tait\n
419 \ta ≈t≈ lanc≈ : %s\n
420 \test termin≈ : %s\n
421 fbackup(1421): aucun historique disponible pour le fichier graphique %s 
422 (sous le niveau %d)\n
423 fbackup(1423): impossible d'acc≈der en ≈criture au fichier dates %s\n
424 fbackup(1424): impossible d'ouvrir le fichier de dates temporaire %s\n
425     LANC‹: %s
426     TERMIN‹: %s\n
427 fbackup(1427): entr≈e non valide dans le fichier graphique %s\n
428 fbackup(1428): erreur dans l'expression du fichier de sortie\n
429 fbackup(1429): le nombre de fichiers de sortie ne peut exc≈der %d\n
501 fbackup(1501): impossible d'acc≈der » %s dans la recherche de fonction\n
502 fbackup(1502): impossible passer au r≈pertoire %s (chdir)\ndans recherche de fonction\n
503 fbackup(1503): impossible passer au r≈pertoire de d≈part %s (chdir)\n
504 fbackup(1504): impossible d'ouvrir le r≈pertoire `.' (%s)\n
505 fbackup(1505): m≈moire virtuelle insuffisante\n
506 fbackup(1506): impossible d'acc≈der au fichier %s\n
507 fbackup(1507): impossible de passer au r≈pertoire (chdir) %s\n
508 fbackup(1508): impossible de r≈gler "cp2" dans expanddir().\n
509 fbackup(1509): erreur d'initialisation pour findpath.\n
510 fbackup(1510): impossible d'acc≈der » %s\n
512 fbackup(1512): m≈moire virtuelle insuffisante\n
513 fbackup(1513): statcall a ≈chou≈ dans dotdotnotparent\n
514 fbackup(1514): impossible d'acc≈der » %s\n
515 fbackup(1515): impossible d'acc≈der » %s\n
516 fbackup(1516): %s non sauvegard≈ - option 'n' (NFS) non sp≈cifi≈e \n
517 fbackup(1517): %s non sauvegard≈ - option 'n' (NFS) non sp≈cifi≈e \n
601 fbackup(1601): impossible d'acc≈der (-i/-e) au fichier %s\n
602 fbackup(1602): m≈moire virtuelle insuffisante\n
603 fbackup(1603): m≈moire virtuelle insuffisante\n
604 fbackup(1604): m≈moire virtuelle insuffisante\n
605 fbackup(1605): m≈moire virtuelle insuffisante\n
701  <LINK> 
702 fbackup(1702): m≈moire virtuelle insuffisante\n
704 fbackup(1704): m≈moire virtuelle insuffisante\n
705 fbackup(1705): impossible de cr≈er le fichier index en ligne %s\n
706 fbackup(1706): entrez nom de fichier de relance (entr≈e pour quitter)\n
707 fbackup(1707): impossible de cr≈er fichier de relance %s pour enregistr\n
708 fbackup(1708): impossible d'ouvrir fichier de relance %s en lecture\n
709 fbackup(1709): m≈moire virtuelle insuffisante\n
710 fbackup(1710): m≈moire virtuelle insuffisante\n
712 fbackup(1712): la session de relance a commenc≈ sur %s\n
713 fbackup(1713): du fichier graphique %s au niveau %d\n
714 fbackup(1714): reprise au num≈ro de fichier %d sur le volume num≈ro %d\n
715 fbackup(1715): impossible de cr≈er le fichier d'en-t¡te de volume %s\n
801 fbackup(1801): m≈moire virtuelle insuffisante\n
802 fbackup(1802): m≈moire virtuelle insuffisante\n
$set 2
1 fbackup(2001): lecteur %d: shmat a ≈chou≈ pour le segment de m≈moire\n
2 fbackup(2002): lecteur %d: impossible d'ouvrir le fichier %s\n
3 fbackup(2003): lecteur %d: \nimpossible d≈placer pointeur (lseek) au fichier %s\n
4 fbackup(2004): lecteur %d: premi…re erreur de lecture, 
5 fbackup(2005): lecteur %d: deuxi…me erreur de lecture, 
6 fbackup(2006): lecteur %d: signal reµu mais aucun travail » ex≈cuter\n
7 fbackup(2007): lecteur %d: annulation\n
8 fbackup(2008): reader %d: unable to read file %s,\n  file has been locked\n
$set 3
1 fbackup(3001): shmat a ≈chou≈, segment m≈moire programme ≈criture;\nerreur %d\n
2 fbackup(3002): m≈moire virtuelle insuffisante\n
3 fbackup(3003): signal normal de fin de bande\n
4 fbackup(3004): enregistrement annul≈\n
5 fbackup(3005): ATTENTION: le fichier num≈ro %d N'A PAS ≈t≈ sauvegard≈\n
6 fbackup(3006): perte synchronisation en ≈criture, nof=%d, num≈ro fichier=%d\n
7 fbackup(3007): ATTENTION: le fichier num≈ro %d (%s)\n
8 \t≈tait actif pendant la tentative num≈ro %d\n
9 fbackup(3009): ATTENTION: le fichier num≈ro %d (%s)\n
10 \tn'a pas ≈t≈ sauvegard≈ correctement\n
11 fbackup(3011):\nERREUR D'‹CRITURE de l'indicateur fin de fichier au point de contr¬le
12 fbackup(3012):ERREUR D'‹CRITURE de l'enregistr du point de contr¬le\n
13 fbackup(3013):ERREUR D'‹CRITURE de l'enregistrement de donn≈es\n
14 fbackup(3014):ERREUR D'‹CRITURE:impossible d'≈crire dans fichier de sortie\n
15 fbackup(3015): p≈riph≈riques de sortie en mode bloc non pris en charge\n
16 fbackup(3016): lorsque le volume %d est pr¡t sur %s, appuyez sur retour?\n
17 fbackup(3017): la bande n'est pas au d≈but, rebobinage en cours\n
18 fbackup(3018): le type du fichier de sortie %s n'est pas valide\n
19 fbackup(3019): voulez-vous pr≈ciser un nouveau fichier de sortie?\n
20 fbackup(3020): entrez le nom du nouveau fichier:\n
21 fbackup(3021): m≈moire virtuelle insuffisante\n
22 fbackup(3022): voulez-vous poursuivre cette session?\n
23 fbackup(3023): assurez-vous que le volume %d est pr¡t sur %s\n
24 fbackup(3024): ≈criture du volume %d dans le fichier de sortie %s\n
25 fbackup(3025): erreur d'≈criture au d≈but du volume\n
26 fbackup(3026): erreur ioctl, impossible d'interroger le fichier de sortie\n
27 fbackup(3027): erreur ioctl, impossible d'interroger le fichier de sortie\n
28 fbackup(3028): ERREUR D'‹CRITURE de l'enregistrer du point de contr¬le
29 fbackup(3029):\nERREUR D'‹CRITURE de l'indicateur fin de fichier au point de contr¬le
30 fbackup(3030): ERREUR D'‹CRITURE de l'enregistrement de donn≈es
32 fbackup(3032): impossible d'ouvrir le fichier de sortie %s\n
33 fbackup(3033): Le type du fichier de sortie %s n'est pas valide;\npr≈cisez un 
34 p≈riph≈rique en mode UCB \n\tsans rebobinage, ou un p≈riph≈rique en mode 
35 AT&T avec rebobinage\n
36 fbackup(3036): impossible de positionner le support %s au d≈but\n
37 fbackup(3037): impossible d'ouvrir le fichier de sortie %s\n
43 fbackup(3043): ERREUR D'‹CRITURE de l'enregistrement de donn≈es
44 fbackup(3044): erreur ioctl, impossible d'interroger le fichier de sortie\n
45 fbackup(3045): ERREUR D'‹CRITURE de l'enregistrement de donn≈es 
46 fbackup(3046): lorsque le volume %d est pr¡t sur %s, appuyez sur retour?\n
47 fbackup(3047): impossible d'ouvrir le fichier de sortie %s\n
48 fbackup(3048): impossible de positionner le support %s au d≈but\n
49 fbackup(3049): lorsque le volume %d est pr¡t sur %s, appuyez sur retour?\n
50 fbackup(3050): impossible d'ouvrir le fichier de sortie %s\n
51 fbackup(3051): lorsque le volume %d est pr¡t sur %s, appuyez sur retour?\n
52 fbackup(3052): impossible d'ouvrir le fichier de sortie %s\n
54 fbackup(3054): impossible d'ouvrir le fichier de sortie %s\n
101  » l'enregistrement %d de support\n
102 fbackup(3102): tentative pour rendre ce volume r≈cup≈rable\n
103 fbackup(3103): r≈≈crire ce volume depuis le d≈but?\n
104 fbackup(3104): ≈criture de 2 indicateurs de fin de fichier et rebobinage\n
105 fbackup(3105): ≈criture de 2 indicateurs de fin de fichier et rebobinage\n
106 fbackup(3106): veuillez monter une bande ad≈quate\n
107 fbackup(3107): erreur d'≈criture d'un indicateur de fin de fichier\ndans %s\n
108 fbackup(3108): erreur d'≈criture d'un enregistrement dans %s\n
109 fbackup(3109): erreur d'≈criture d'un indicateur de fin de fichier\ndans %s\n
110 fbackup(3110): erreur d'≈criture d'un enregistrement dans %s\n
111 fbackup(3111): erreur d'≈criture d'un enregistrement dans %s\n
112 fbackup(3112): erreur d'≈criture d'un indicateur de fin de fichier\ndans %s\n
113 fbackup(3113): erreur d'≈criture d'un enregistrement dans %s\n
114 fbackup(3114): erreur d'≈criture d'un indicateur de fin de fichier\ndans %s\n
115 fbackup(3115): erreur d'≈criture d'un enregistrement dans %s\n
116 fbackup(3116): erreur d'≈criture d'un enregistrement dans %s\n
117 fbackup(3117): erreur d'≈criture d'un enregistrement dans %s\n
118 fbackup(3118): erreur d'≈criture d'un enregistrement dans %s\n
119 fbackup(3119): erreur d'≈criture d'un enregistrement dans %s\n
120 fbackup(3120): erreur d'≈criture d'un enregistrement dans %s\n
121 fbackup(3121): erreur d'≈criture d'un enregistrement dans %s\n
122 fbackup(3122): erreur d'≈criture d'un enregistrement dans %s\n
123 fbackup(3123): impossible de lire l'enregistrement de contr¬le pr≈c≈dent\n
124 fbackup(3124): erreur d'≈criture d'un enregistrement dans %s\n
125 fbackup(3125): erreur d'≈criture d'un FSM dans %s\n
126 fbackup(3126): erreur d'≈criture d'un enregistrement dans %s\n
127 fbackup(3127): erreur d'≈criture d'un enregistrement dans %s\n
128 fbackup(3128): erreur d'≈criture d'un indicateur de fin de fichier\ndans %s\n
129 fbackup(3129): erreur d'≈criture d'un enregistrement dans %s\n
130 fbackup(3130): erreur d'≈criture d'un enregistrement dans %s\n
202 fbackup(3202): volume %d DE CETTE SESSION!\n\trejet de ce volume\n
203 fbackup(3203): le volume %d a ≈t≈ utilis≈ %d fois \n
204 fbackup(3204): le volume a ≈t≈ utilis≈ plus de fois que le maximum permis,\n d≈sirez-vous quand m¡me l'utiliser?\n
205 fbackup(3205): impossible de lire un en-t¡te de volume\n
301 fbackup(3301): impossible d'ouvrir le fichier de sortie %s\n
303 fbackup(3303): erreur dans processus ioctl, requ¡te fichier de sortie imposs\n
304 fbackup(3304): erreur d'op≈ration de la bande magn≈tique\n
305 fbackup(3305): impossible d'ouvrir le fichier de sortie %s\n
306 fbackup(3306): volume %d DE CETTE SESSION!\n\trejet de ce volume\n
307 fbackup(3307): le volume %d a ≈t≈ utilis≈ %d fois (maximum: %d)\n
308 fbackup(3308): d≈sirez-vous quand m¡me utiliser ce volume?\n
309 fbackup(3309): impossible de lire un en-t¡te de volume\n
310 fbackup(3310): enter '%s' when volume %d is ready on %s,\n or '%s' to discontinue:\n
$set 4
1 fbackup(4001): '%s' automatique\n
2 fbackup(4002): veuillez r≈pondre par: '%s' ou '%s'\n
3 fbackup(4003): s≈maphore op a ≈chou≈: op=%d\n
4 fbackup(4004): la fonction mymalloc n'a pu attribuer de l'espace\n
