$set 1
1 Syntaxe: find liste_de_chemins [liste_de_pr≈dicats]\n
2 find: impossible d'obtenir 'pwd'\n
3 find: erreur lors de l'analyse\n
4 find: op≈rateur manquant\n
5 find: un op≈rande suit l'op≈rande\n
6 find: -user %s introuvable\n
7 find: -group %s introuvable\n
8 find: impossible de cr≈er %s\n
9 find: impossible d'acc≈der » %s\n
10 find: option %s erron≈e\n
11 find: instruction incompl…te\n
14 find: impossible d'acc≈der » %s\n
15 find: impossible %s %s\n
16 Impossible d'ouvrir /dev/tty pour demander d'entrer d'autres supports.\n
17 find: impossible d'≈crire %s: %s\n
19 Pour continuer, entrez le nom du fichier de p≈riph≈riques\n
20 L'utilisateur a entr≈ un nom nul comme fichier de p≈riph≈riques suivant.\n
21 find: impossible d'ouvrir %s: %s\n
22 L'utilisateur a ouvert le fichier %s pour continuer.\n
23 find: -type %s erron≈\n
24 find: valeur -inum %s erron≈e\n
25 find: %s n≈cessite un argument\n
26 find: %s ne se termine pas par ';'\n
27 find: %s doit pr≈ciser une commande » ex≈cuter\n
28 find: mode %s non valide\n
40 plus de 16 entr≈es » l'entr≈e: 
41 l'entr≈e ne commence pas par "(" dans la forme abr≈g≈e: 
42 l'entr≈e ne se termine pas par ")" dans la forme abr≈g≈e: 
43 le nom de l'utilisateur ne se termine pas par un point dans l'entr≈e: 
44 le nom de groupe ne se termine pas correctement dans l'entr≈e: 
45 le nom de l'utilisateur est nul dans l'entr≈e: 
46 le nom de groupe est nul dans l'entr≈e: 
47 le nom de l'utilisateur dans l'entr≈e n'est pas valide: 
48 le nom de groupe dans l'entr≈e n'est pas valide: 
49 mode dans l'entr≈e non valide: 
51 erreur inconnue en provenance de strtoaclpatt(): 
55 find: 
56 find: type de syst…me de fichiers %s non valide\n
57 ouverture (open)
58 recherche (search)
59 find: -devcid %s introuvable\n
60 find: impossible de revenir au r≈pertoire %s (chdir)\n
61 find: impossible utiliser -ncpio et -cpio simultan≈ment pour le m¡me fichier
62 find: cpio; E/S a ≈chou≈ -- 
63 find: %s cr≈e un cycle\n
64 Aucune erreur\n
65 m≈moire insuffisante\n
66 type de fichier inconnu\n
67 erreur interne de mise en m≈moire tampon\n
68 la taille du fichier a chang≈\n
69 erreur inconnue (CPIO_%d)\n
