$set 1
1 (1001): en queue de fichier ne concorde pas avec l'en-t¡te de fichier pour
2 (1002): fichier %s
3 (1003): identificateur de sauvegarde ne concorde pas avec valeur attendue
4 (1004): heure de la sauvegarde ne concorde pas avec la valeur attendue
6 (1006): valeur non valide pour ordinateur ≈loign≈; zone bit doit ¡tre 
7 (1007): z≈ro ou un
8 (1008): type inconnu dans l'en-t¡te ou l'en queue
9 (1009): tente de continuer
10 (1010): identificateur inconnu dans l'en-t¡te ou l'en queue
11 (1011): tente de continuer
12 (1012): acc…s non autoris≈ au fichier %s
13 (1013): impossible de passer (chdir) au r≈pertoire %s
14 (1014): valeur non valide pour ordinateur ≈loign≈; zone bit doit ¡tre 
15 (1015): impossible de passer (chdir) au r≈pertoire %s
16 (1016): z≈ro ou un
17 (1017): impossible de passer (chdir) au r≈pertoire %s
18 (1018): impossible d'acc≈der au fichier %s
20 (1020): non-concordance du total de contr¬le (checksum) de blocs
21 (1021): non-concordance du total de contr¬le (checksum) de blocs
22 (1022): impossible d'acc≈der au fichier %s
23 (1023): le fichier %s existe mais n'est pas un r≈pertoire
24 (1024): impossible de cr≈er le r≈pertoire %s
25 (1025): impossible de supprimer le lien du fichier %s
26 (1026): impossible de cr≈er un conduit (mknod) pour le fichier %s
27 (1027): impossible de cr≈er un conduit (mknod) pour le fichier %s
28 (1028): ancien fichier r≈seau sp≈cial non pris en compte
29 (1029): impossible de convertir fichier existant %s en fichier\ntributaire du contexte\n
30 (1030): erreur (%s) d'attribution du nouveau nom %s au r≈pertoire\n
32 (1032): %s - impossible d'ouvrir
33 (1033): impossible de cr≈er le fichier %s
35 (1035): impossible de cr≈er un nom de fichier temporaire
36 (1036): saut du fichier 
37 (1037): impossible de cr≈er un lien entre %s et %s: %s
38 (1038): le syst…me ne prend pas en charge les liens symboliques
39 (1039): la version sauvegard≈e de %s est plus r≈cente
40 (1040): r≈cup≈rez d'abord le lien %s
41 (1041): impossible de cr≈er un lien entre %s et %s
42 (1042): impossible d'acc≈der au fichier li≈ %s
43 (1043): erreur dans l'en-t¡te au moment de la reprise
44 (1044): erreur dans la reprise du fichier
45 (1045): erreur dans la r≈cup≈ration de l'en queue
46 (1046): erreur d'≈criture dans le fichier r≈siduel
47 (1047): erreur d'E/S dans la sauvegarde du fichier %s
48 (1048): erreur d'E/S dans l'≈criture du fichier %s
50 (1050): impossible de se positionner au fichier de relance
51 (1051): volume mont≈ inad≈quat
52 (1052): impossible de supprimer le lien %s
53 (1053): impossible de modifier les autorisations (chmod) du fichier %s
54 (1054): trop de composantes dans le nom de fichier %s
55 (1055): propri≈taire/groupe non valide pour fichier %s;propri≈taire inchang≈
56 (1056): entr≈es non valides pour le fichier %s; ACL non r≈cup≈r≈es.
57 (1057): erreur du d≈rouleur lors du positionnement de rep…res avec fastsearch
58 (1058): impossible d'≈crire dans %s
59 (1059): fichier %s rep≈r≈, mais en cours d'utilisation/irr≈cup≈rable pour\ncet essai
60 (1060): %s n'est pas sur le support;\n\tpoursuite avec %s et fichiers\nsuivants
61 (1061): essai pour continuer la reprise avec un nouvel identificateur de\nsauvegarde
62 (1062): essai pour continuer la reprise avec une nouvelle heure de sauvegarde
63 (1063): Impossible de cr≈er l'ACL:code d'utilisateur inconnu %s
64 (1064): Impossible de cr≈er l'ACL:code de groupe inconnu %s
65 (1065): erreur de lecture de l'en-t¡te de fichier
$set 2
102 (2102): nombre maximum (%d) de resynchronisation d≈pass≈
103 (2103): IOERROR dans un fichier sur disque. Sortie de frecover
104 (2104): longueur z≈ro lu dans un fichier sur disque. Sortie de frecover
105 (2105): rep…re de fichier attendu introuvable
107 (2107): IOERROR sur une unit≈ de disque. Sortie de frecover
108 (2108): aucune lecture sur unit≈ de disque. Sortie de frecover
109 (2109): lecture du rep…re de fichier
110 (2110): lecture d'un enregistrement de point de contr¬le
111 (2111): lecture d'un rep…re DDS
112 (2112): lecture d'un rep…re DDS inattendu. ‹tat:
113 (2113): impossible de resynchroniser le support de sauvegarde
114 (2114): erreur de lecture du p≈riph≈rique d'entr≈e (%s)
$set 3
203 (3203): impossible d'ouvrir le fichier r≈siduel %s
204 (3204): ex≈cution sans le fichier r≈siduel
205 (3205): les options sp≈cifi≈es s'excluent mutuellement
206 (3206): l'option '%c' exige un argument
207 (3207): argument additionnel: %s sp≈cifi≈
208 (3208): doit sp≈cifier au moins l'une des options suivantes: V, I, x, r ou R
209 (3209): touches X et F sp≈cifi≈es; F est utilis≈e
210 (3210): option non valide (-i/-e) sp≈cifi≈e avec l'option r
211 (3211): option N sp≈cifi≈e. %s ignor≈e
237 (3238): les options sp≈cifi≈es s'excluent mutuellement
241 (3241): impossible d'ouvrir le fichier de configuration %s
242 (3242): label du fichier de configuration non valide (%s) non pris en compte
243 (3243): erreur dans le fichier de configuration » la ligne %d
244 (3244): ligne erron≈e:\n%s
245 (3245): l'option '%c' n'est pas reconnue
246 (3246): options additionnelles inad≈quates sp≈cifi≈es pour l'extraction d'index
247 (3247): options additionnelles inad≈quates sp≈cifi≈es pour l'extraction\nd'en-t¡tes de volume 248 (3248):\ni ou e manquant dans le fichier graphique %s
249 (3249): impossible d'ouvrir le fichier graphique %s
250 (3250): impossible d'ouvrir le fichier d'en-t¡tes de volume %s
251 (3251): le nombre de fichiers de sortie ne peut d≈passer MAXOUTFILES \n
252 (3252): erreur dans l'expression du fichier de sortie\n
253 frecover -r [-hosvymFNOX] [-c fich_config] [-f p≈riph] [-S fich_saut]\n
254 frecover -R chemin [-f p≈riph]\n
255 frecover -x [-hosvymFNOX] [-c fich_config] [-e chemin] [-f p≈riph]\n\
            [-g fich_graph] [-i chemin] [-S fich_saut]\n
256 frecover [-I | -V] chemin [-vy] [-f p≈riph] [-c fich_config]\n
257  -{r,x} - reprise compl…te ou partielle\n
258  -{I,V} - ≈criture de l'index ou de l'en-t¡te de volume dans chemin\n
259  -{F,X} - reprise sans structure de r≈pertoires ou dans r≈pertoire en cours\n
260  -{i,e} - chemin » inclure ou » exclure\n
261  -{g,c} - fichier de graphiques ou fichier de configuration\n
262  -{N,h} - aucune reprise - v≈rif. seulement/extraction r≈pertoire r≈el\n
263  -R     - poursuivre une session de reprise interrompue\n
264  -f     - p≈riph. de sauvegarde » utiliser au lieu du p≈riph par d≈faut\n
265  -o     - ≈crasement des fichiers existants\n
266  -v     - mode prolixe\n
267  -y     - r≈ponse affirmative » toutes les questions\n
268  -S     - fichier pour blocs contourn≈s\n
269  -s     - aucune cr≈ation de fichiers avec blocs vides\n
270  -O     - fichiers deviennent propri≈t≈ de l'utilisateur faisant la reprise\n
271  -m     - affichage d'un message » chaque rep…re (total contr¬le, eof, rep…re)
$set 4
301 (4301): %s non r≈cup≈r≈ depuis le support de sauvegarde
302 (4302): frecover interrompu, continue
303 (4303): d≈sirez-vous sauvegarder l'≈tat pour relancer
304 (4304): '%s' automatique\n
305 (4305): m≈moire insuffisante pour attribution
306 (4306): impossible de cr≈er le fichier de relance, ressayez
307 (4307): impossible de sauvegarder le fichier de relance
308 (4308): impossible d'ouvrir le fichier de relance
309 (4309): impossible de lire le fichier de relance
310 frecover(4310): Entrez nom chemin absolu d'un fichier pour sauvegarde ≈tat: 
311 (4311): impossible de le lire le noeud OBSCURE
312 (4312): impossible de sauvegarder le noeud OBSCURE
$set 5
401 (5401): Volume %d termin≈.
402 (5402): la fermeture sur le p≈riph≈rique %s a ≈chou≈
403 (5403): Impossible d'ouvrir ou d'identifier le p≈riph≈rique » %s\n
404 frecover(5404): Appuyez sur retour quand le volume suivant\nest pr¡t sur %s:\n
405 (5405): impossible d'ouvrir %s
406 (5406): D≈sirez-vous continuer?
407 (5407): abandon s≈lectionn≈
408 (5408): n'est pas un volume fbackup; impossible de lire le label de volume
409 (5409): impossible de lire l'en-t¡te de volume
410 frecover(5410):Appuyez sur retour quand le volume pr≈c≈dent\nest pr¡t sur %s:\n
411 (5411): Voulez-vous essayer un autre volume
412 (5412): Voulez-vous essayer de r≈cup≈rer ce volume
413 (5413): essai de lecture des donn≈es de sauvegarde suivant\nl'en-t¡te de volume erron≈
414 (5414): abandon s≈lectionn≈
418 (5418): n'est pas un volume fbackup;impossible de lire l'en-t¡te du volume
419 (5419): total de contr¬le incorrect sur l'en-t¡te de volume.
420 (5420): n'est pas un volume fbackup; valeur du nombre (magic) incorrecte
421 (5421): l'identification du volume ne correspond pas » la session en cours
422 (5422): la sauvegarde s≈lectionn≈e » la relance est inad≈quate
423 (5423): volume mont≈ incorrect;
424 (5424): volume attendu %d, volume obtenu %d
425 (5425): impossible d'ouvrir le fichier index
426 (5426): erreur lors d'un essai de lecture de l'index. Non pris en compte.
427 (5427): impossible d'ouvrir le terminal de contr¬le
429 (5429): volume de sauvegarde cr≈≈ avec variable environn LC_COLLATE ou\nLANG d≈finies comme %s; doit ¡tre r≈cup≈r≈e avec m¡me valeur:\nr≈initialisation » %s.
430 (5430): impossible d'ouvrir /tmp/sampipe
431 (5431): volume de sauvegarde cr≈≈ avec variable environn LC_COLLATE ou\nLANG non d≈finies. Supprimez la d≈finition des variables LANG et LC_COLLATE\net continuez.
432 (5432): le rebobinage a ≈chou≈
433 (5433): D≈sirez-vous continuer » utiliser ce volume?
434 (5434): tentative de resynchroniser apr…s l'en-t¡te de volume
435 (5435): erreur malloc lors d'un essai de lecture de l'index
436 (5436): erreur malloc: m≈moire virtuelle insuffisante pour utiliser fastsearch.\nPoursuite sans la fonction fastsearch.
437 (5437): impossible de localiser le fichier de p≈riph≈riques %s\n
