$set 1
1 syntaxe: gencat [ -l ] fichier-catalogue fichiers ...\n
2 gencat: %s: n'est pas un fichier-catalogue\n
3 gencat: %s: fichier-catalogue erron≈\n
4 gencat: %s: fichier-catalogue erron≈\n
5 "%s", ligne %ld: Num≈ro de set erron≈\n
6 "%s", ligne %ld: S≈quence de num≈ros set erron≈\n
7 "%s", ligne %ld: Num≈ro de delset erron≈\n
9 "%s", ligne %ld: Aucun num≈ro de message\n
10 "%s", ligne %ld: Message trop long\n
12 "%s", ligne %ld: Num≈ro de message erron≈\n
13 "%s", ligne %ld: S≈quence de num≈ros de messages erron≈e\n
14 "%s", ligne %ld: S≈parateur erron≈\n
15 "%s", ligne %ld: Message erron≈\n
16 "%s", ligne %ld: Num≈ro de message » supprimer erron≈\n
18 "%s", ligne %ld: Caract…re quote manquant\n
