$set 1
1 syntaxe: %s [-u utilisateur] [-g groupe[,groupe]...] [-n] fichier ...
2          %s -r [-n] fichier ...
3 -u d≈termine l'acc…s pour un util donn≈ au lieu de l'ID effectif du demandeur
4 -g d≈termine l'acc…s pour groupes donn≈s au lieu de groupes du demandeur
5 -r v≈rif droits d'acc…s en utilisant ID r≈el du demandeur au lieu de l'effect
6 -n affiche valeur num≈rique des droits d'acc…s (0..7) au lieu d'une cha—ne
7    utilisateur ou groupe peut ¡tre "@" pour chaque gid de fichier tour » tour
15 impossible d'associer -u ou -g avec -r
17 plus de %d groupes non admis
18 ID (num≈ro d'identification) utilisateur nul non admis
19 ID (num≈ro d'identification) de groupe nul non admis
20 ID (num≈ro d'identification) utilisateur "%s" non valide
21 ID de groupe "%s" non valide
22 fichier "%s"
23 fichier "%s"
30  (num≈ro de l'erreur = %d)
