$set 1
1 grep  [-E|-F] [-cbilnqsvx] [-e expression [-e expression] ... | -f fichier]\n [expression] [fichier ...]\n egrep [-cbilnqsvx] [-e expression [-e expression] ... | -f fichier]\n [expression] [fichier ...]\n fgrep [-cbilnqsvx] [-e expression [-e expression] ... |  -f fichier\n [expression] [fichier...]
2 %s: impossible d'ouvrir %s\n
3 syntaxe:\n %s\n
4 %s: impossible d'ouvrir %s\n
5 %s: erreur %d dans l'expression standard (RE): 
101 Code d'erreur regexp inconnu!!
102 Ordre des ≈l≈ments r≈f≈renc≈s non valide.
103 \\ en queue dans l'expression.
104 \\n trouv≈ dans l'expression.
105 Trop de paires de \\( \\) ou imbrication de ( ) trop complexe.
106 Nombre dans \\digit non valide ou hors plage.
107 [ ] manquant.
108 Non concordance \\( \\) ou ( ).
109 Non concordance \\{ \\}.
110 Point de terminaison de l'intreclassement non valide dans l'expression [ - ]
111 D≈bordement de l'expression standard.
112 Num≈ro trop ≈lev≈ dans la structure \\{ \\}.
113 Num≈ro non valide dans la structure \\{ \\}.
114 Plus de 2 num≈ros dans la structure \\{ \\}.
115 Le premier num≈ro est sup≈rieur au deuxi…me dans \\{ \\}.
116 Classe de caract…res nomm≈e non valide.
117 Aucune cha—ne de recherche pr≈c≈demment utilis≈e.
118 Op≈rateur de duplication dans une position non valide.
119 L'expression sp≈cifi≈e est vide.
