$set 1
1 syntaxe: %s -f du_code -t au_code [fichiers ...]\n
2 impossible de trouver la taille de la table de conversion\n
3 espace insuffisant pour la table de conversion\n
4 impossible d'initialiser la conversion\n
5 caract…re d'entr≈e erron≈\n
6 impossible de mettre fin » la conversion\n
7 la conversion de %s » %s ≈tablit la correspondance\ndes caract…res suivants:\n
8 ROMAN8: \\x%x %-25sISO8859/1: \\x%x %-25s\n
9 ISO8859/1: \\x%x %-25sROMAN8: \\x%x %-25s\n
10 NA (Do not use)
11 No break space
12 Accent grave
13 Guillemet anglais simple de gauche
14 Accent circonflexe
15 Caret
16 Tilde (accent)
17 Tilde
18 Symbole de la lire italienne
19 Symbole de la livre anglaise
20 Ligne de s≈paration sup≈rieure
21 Accent d'intensit≈ (macron)
22 Symbole du florin
23 f minuscule
24 Uppercase S caron
25 S majuscule
26 Lowercase s caron
27 s minuscule
28 Uppercase Y umlaut
29 Y majuscule
30 Barre horizontale
31 Trait d'union
32 Carr≈ plein
33 Ast≈risque
34 NA (Do not use)
35 No break space
40 No break space
41 NA (Do not use)
42 Barre bris≈e
43 Ligne verticale
44 Symbole du copyright
45 c minuscule
46 Not sign
47 Tilde
48 Trait d'union » angle droit
49 Trait d'union
50 Symbole de marque d≈pos≈e
51 R majuscule
52 Accent d'intensit≈ (macron)
53 Barre du dessus
54 Exposant deux
55 Chiffre deux
56 Exposant trois
57 Chiffre trois
58 C≈dille
59 Virgule
60 Exposant un
61 Chiffre un
62 Signe de la multiplication
63 x minuscule
64 Signe de la division
65 Barre oblique
