$set 1
1 /usr/keysh/C/softkeys
2 /usr/keysh/C/keyshrc
3 /usr/keysh/C/help
4 /usr/keysh/builtins
5 /.softkeys
6 /.keyshrc
7 
8 
9 
10 %s: [10] l'initialisation de Terminfo a ≈chou≈ ; v≈rifiez $TERM.\n
11 %s: [11] Ex≈cution de /bin/ksh...\n
12 %s: [12] L'ex≈cution se poursuit sans terminfo...\n
13 [13] Impossible de trouver la touche %q dans le fichier %q.\n
14 [14] Impossible de trouver la touche %q.\n
15 [15] %q remplac≈; changements pr≈c≈dents sont peut-¡tre perdus.\n
16 [16] Impossible de sauvegarder %q;modifications non sauvegard≈es.\n
17 [17] Impossible de supprimer %q; aucune modification apport≈e.\n
18 [18] Erreur de syntaxe dans fichier de configuration--non pris en compte.\n
19 [19] Impossible d'ouvrir le fichier de touches %q.\n
20 [20] Utilisateur %q inconnu.\n
21 [21] Erreur dans le fichier de touches %q, ligne %d, caract…re %d.\n
22 [22] (Nouveau noeud de touches attendu; %q trouv≈.)\n
23 [23] (Attribut de touches attendu; %q trouv≈.)\n
24 [24] (";" attendu; %q trouv≈.)\n
25 [25] ("}" attendu; fin de fichier trouv≈.)\n
26 [26] (Valeur de code autre que z≈ro attendue; %q trouv≈e.)\n
27 [27] Trop d'erreurs; saut des touches restantes.\n
28 [28] erreur de syntaxe %s dans la touche %q pr…s du caract…re %d.\n
29 [29] Fichier de touches modifi≈; impossible de lire l'aide.\n
30 [30] Impossible de lire la configuration » partir de %q ou %q.\n
31 
32 
33 
34 
35 
36 
37 
38 
39 
40 --Aide--
41 AIDE
42 --Encore--
43 ° SUIVRE
44  de 
45 Vous avez reµu du courrier
46 Vous avez du courrier
47 Pas de courrier
48 
49 
50 S≈lectionnez une touche ou appuyez sur <Retour> pour l'aide contextuelle.
51 D≈sol≈.  Aucune aide n'est offerte pour cette touche.
52 D≈sol≈.  Aucun conseil n'est offert pour cette touche.
53 D≈sol≈.  Aucune aide n'est offerte.
54 Cette touche n'est pas en fonction.
55 help
56 S≈lectionnez le sujet pour lequel vous d≈sirez obtenir de l'aide...
57 (sujets)
58 SORTIE
59 
60 Keysh_config
61 kc
62 Puis, entrez un espace.
63 tsm-
64 Incomplet...
65 
66 S≈lectionnez une option; puis
67 S≈lectionnez une option ou
68 Non admis » cette ≈tape.
69 
