$set 1
1 Syntaxe: ln [-f] [-i] [-s] fichier1 fichier2\n\t ln [-f] [-i] [-s] fichier1 ... fichiern r≈pertoire1\n
2 Syntaxe: ln [-f] [-i] fichier1 fichier2\n\t ln [-f] [-i] fichier1 ... fichiern r≈pertoire1\n
3 ln: impossible d'acc≈der » %s\n
4 ln: <%s> est un r≈pertoire\n
5 ln: %s/%s: Nom trop long\n
6 ln: %s et %s sont identiques\n
7 ln: %s: %o%c mode (%s/%s) 
8 ln: impossible de supprimer le lien %s\n
9 ln: syst…me de fichiers diff≈rent\n
10 ln: aucune autorisation pour %s\n
11 ln: trop de liens » %s\n
12 ln: %s existe\n
