$set 1
1 impossible de d≈finir LC_COLLATE\n
2 impossible de d≈finir LC_CTYPE\n
3 impossible de r≈ouvrir stdin\n
4 Syntaxe: localedef [-c] [-f fich_corr_carac] [-i fich_entr≈e] nom_langnat\n
5 ou\t localedef -d [-o format] nom_langnat\n
6 ou\t localedef -n fich_entr≈e\n
7 impossible d'ouvrir le fichier 'debug'\n
9 impossible d'ouvrir le fichier d'entr≈e %s\n
10 aucune sp≈cification pour 'langname'\n
11 aucune sp≈cification pour 'langid'\n
12 conflit de sp≈cification dans 'langname' et 'langid'\n
13 conflit de sp≈cification dans 'isfirst' et 'byte_chars'\n
14 ATTENTION: la sp≈cification de s≈quence sera ignor≈e\n
15 La cat≈gorie LC_ALL exc…de la taille maximale permise\n
16 La cat≈gorie LC_MESSAGES exc…de la taille maximale permise\n
17 La cat≈gorie LC_COLLATE exc…de la taille maximale permise\n
18 La cat≈gorie LC_CTYPE exc…de la taille maximale permise\n
19 La cat≈gorie LC_MONETARY exc…de la taille maximale permise\n
20 La cat≈gorie LC_NUMERIC exc…de la taille maximale permise\n
21 La cat≈gorie LC_TIME exc…de la taille maximale permise\n
22 impossible de cr≈er le fichier 'locale.inf'\n
23 Erreur localedef: mot cl≈ non valide » la ligne %d\n
25 Erreur localedef: caract…re non valide » la ligne %d\n
26 Erreur localedef: instruction non valide » la ligne %d\n
27 Erreur localedef: expression non valide » la ligne %d\n
28 Erreur localedef: plage de valeurs non valide » la ligne %d\n
29 Erreur localedef: longueur de langname non valide » la ligne  %d\n
30 Erreur localedef: num≈ro de langid non valide » la ligne %d\n
31 Erreur localedef: longueur du nom de langue non valide dans langname » %d\n
32 Erreur localedef: longueur du nom de territoire non valide dans langname\n» la ligne %d\n
33 Erreur localedef: longueur du nom de jeu de caract…res non valide dans\nlangname » la ligne %d\n
34 Erreur localedef: longueur de la cha—ne revision non valide » la ligne %d\n
36 Erreur localedef: code de caract…re non valide » la ligne  %d\n
37 Erreur localedef: code de caract…re isfirst non valide » la ligne %d\n
38 Erreur localedef: code de caract…re issecond non valide » la ligne %d\n
39 Erreur localedef: longueur du nom de code_scheme non valide %d\n
40 Erreur localedef: nom de code_cscheme non valide %d\n
41 Erreur localedef: longueur de la cha—ne cswidth non valide %d\n
42 Erreur localedef: format de la cha—ne cswidth non valide %d\n
43 Erreur localedef: longueur de la cha—ne langinfo non valide %d\n
44 Erreur localedef: longueur de la cha—ne monetary non valide  %d\n
45 Erreur localedef: longueur de la cha—ne numeric non valide %d\n
46 Erreur localedef: longueur de la cha—ne modifier non valide %d\n
47 Erreur localedef: l'allocation de m≈moire (malloc) a ≈chou≈\n
48 Erreur localedef: d≈bordement de la file d'attente de priorit≈s \n
49 Erreur localedef: la cha—ne du oui et la cha—ne du non doivent commencer\npar un caract…re distinct%d\n
50 Erreur localedef: longueur de la cha—ne era non valide %d\n
51 Erreur localedef: format de la cha—ne era non valide %d\n
52 Erreur localedef: trop de cha—nes era sont sp≈cifi≈es %d\n
53 Erreur localedef: symbole sp≈cifi≈ introuvable %d\n
58 Erreur localedef: fichier de correspondance des caract…res introuvable \n
60 Erreur localedef: symbole en double %d\n
63 Erreur localedef: plus que COLL_WEIGHTS_MAX sp≈cifi≈s » la ligne %d\n
68 Attention localedef: symbole sp≈cifi≈ introuvable %d\n
72 Attention localedef: mot cl≈ non accept≈ %d\n
73 Attention localedef: Initialisation de ctype incorrecte - correctif apport≈\n
74 conflit de sp≈cification dans 'langname' et 'langid'
75 ATTENTION:\nla langue de l'utilisateur (langid) doit ¡tre comprise entre 901 et 999\n
76 la langue de l'utilisateur (langid) doit ¡tre comprise entre 901 et 999
77 conflit de sp≈cification dans 'langname' et 'langid'
78 erreur de lecture sur le fichier : 
79 impossible d'ex≈cuter lseek sur le fichier : 
80 impossible d'ouvrir le fichier temporaire %s\n
81 Erreur lors de l'interpr≈tation du fichier de correspondance de caract…res\n
82 Erreur locale: ligne non valide dans la cat≈gorie LC_COLLATE : %d\n
