$set 1
1 syntaxe: %s dest ...\n
2 prise en charge
3 destination "%s" inexistante
4 la destination "%s" n'existe plus!
5 la destination "%s" acceptait d≈j» les demandes!
6 la destination "%s" accepte les demandes\n
7 r≈pertoire de spooling inexistant
$set 2
1 syntaxe: cancel id ... imprimante ...\n
2 impossible de relancer la classe
3 "%s" n'est ni un id de demande ni une imprimante
4 l'imprimante "%s" n'existe plus!
5 l'imprimante "%s" n'≈tait pas occup≈e
6 la demande "%s-%d" a ≈t≈ annul≈e\n
7 votre demande d'impression %1$s-%2$d a ≈t≈ annul≈e par %3$s.
8 la demande "%s-%d" a ≈t≈ annul≈e\n
9 la demande "%s-%d" a ≈t≈ annul≈e\n
10 votre demande d'impression %1$s-%2$d a ≈t≈ annul≈e par %3$s.
11 r≈pertoire de spooling inexistant
12 la demande "%s-%d" n'a pas ≈t≈ annul≈e: n'est pas le propri≈taire\n
13 Impossible d'ex≈cuter la commande %s d'annulation » distance.\n
14 L'erreur %d s'est produite.\n
15 "%s" n'est ni une imprimante ni une classe
16 Sans les privil…ges root, vous ne pouvez pas utiliser cette option\n
22 syntaxe: cancel id ... imprimante ... -a -e -uutilisateur\n
23 les demandes peuvent ¡tre annul≈es » l'aide des options suivantes\n
24 \tid      - l'identificateur de la demande\n
25 \timprnte - l'imprimante vis≈e par l'annulation de la demande\n
26 \t-a      - toutes demandes de l'utilisateur dans l'imprimante sp≈cifi≈e\n
27 \t-e      - toutes les demandes dans la file d'attente d'impression\n
28 \t-uutil  - l'utilisateur sp≈cifi≈ dans l'imprimante pr≈cis≈e\n
29 Nombre max de demandes » distance d≈pass≈. Demande "%s-%d" non annul≈e.\n
30 Nombre max de demandes » distance d≈pass≈. Demande "%s" non annul≈e.\n
31 \t-i      - annule seulement les demandes locales\n
$set 3
1 %b %2d %H:%M
$set 4
1 syntaxe: %s [-c] [-r[raison]] imprimante ...\n
2 option "%s" inconnue
3 imprimante "%s" n'existe pas
4 aucune imprimante sp≈cifi≈e
5 l'imprimante "%s" n'existe plus!
6 l'imprimante "%s" n'acceptait d≈j» pas les demandes (disable)
7 la demande "%s-%d" a ≈t≈ annul≈e\n
8 raison inconnue
9 l'imprimante "%s" n'accepte plus les demandes (disable)\n
10 votre demande d'impression "%1$s-%2$d" a ≈t≈ annul≈e par %3$s.
11 r≈pertoire de spooling inexistant
12 la demande "%s-%d" n'a pas ≈t≈ annul≈e: n'est pas le propri≈taire\n
$set 5
1 syntaxe: %s imprimante ...\n
2 prise en charge des demandes (enable)
3 l'imprimante "%s" n'existe pas!
4 l'imprimante "%s" n'existe pas!
5 l'imprimante "%s" acceptait d≈j» les demandes (enable)
6 l'imprimante "%s" accepte les demandes (enable) \n
7 r≈pertoire de spooling inexistant
$set 6
1 r≈pertoire de spooling inexistant
2 ≈tat d'acceptation de la destination "%s" inconnue
3 impossible de prendre en charge demandes pour destination "%1$s" -\n\t%2$s
4 niveau de priorit≈ %d erron≈
5 imprimante ou classe "%s" inexistante
6 impossible d'ouvrir le fichier %s dans le r≈pertoire CLASS
7 impossible de cr≈er le fichier %s dans le r≈pertoire REQUEST
8 impossible de cr≈er le fichier temp %s
9 %s destination "%s" non valide
10 impossible d'ouvrir le fichier destination par d≈faut
11 aucune destination syst…me par d≈faut
12 destination par d≈faut "%s" inexistante
13 impossible de lire le r≈pertoire en cours
14 impossible d'ouvrir le fichier %s
15 impossible d'ouvrir le nouveau fichier de num≈ros de s≈quence %s
16 trop d'options pour le programme d'interface
17 Attention: nom du serveur de grappe introuvable
18 destination "%s" inexistante
19 niveau de priorit≈ par d≈faut erron≈ dans %s/%s pour l'imprimante %s
20 impossible d'acc≈der au fichier "%s"
21 "%s" est un r≈pertoire
22 le fichier "%s" est vide
24 demande non prise en charge
25 %d fichiers
26 %d fichier
27  et 
28 entr≈e standard
29 l'identificateur de la demande est %1$s (%2$s%3$s%4$s)\n
30 l'identificateur %s de la demande n'a pas ≈t≈ mis en file d'attente\n
31 l'entr≈e standard est vide
34 trop de fichiers - r≈partissez le travail\n
$set 7
1 l'imprimante "%1$s" n'appartient pas » la classe "%2$s"
2 impossible d'ouvrir l'un des fichiers d'impression (member)
3 impossible d'ouvrir l'un des fichiers du r≈pertoire CLASS
4 fichier du r≈pertoire MEMBER d'impression alt≈r≈
5 l'imprimante "%1$s" est d≈j» dans la classe "%2$s"
6 impossible de cr≈er un nouveau fichier d'impression (member)
7 impossible de cr≈er un nouveau fichier de classe
8 impossible de cr≈er un nouveau fichier d'≈tat d'impression
9 impossible de cr≈er un nouveau fichier d'≈tat d'acceptation
10 impossible de cr≈er un nouveau programme d'interface
11 impossible de cr≈er un nouveau r≈pertoire REQUEST
12 l'entr≈e d'≈tat d'impression "%s" n'existe plus
13 destination "%s" inexistante
14 l'imprimante "%s" n'existe pas!
15 impossible de cr≈er l'imprimante "%s", ce nom de classe existe d≈j»
16 impossible de cr≈er la classe "%s", ce nom d'imprimante existe d≈j»
17 "%s" est un nom de destination non valide
18 les nouvelles imprimantes n≈cessitent -v ainsi que -e, -i ou -m
19 les lettres cl≈s "-%c" et "-%c" sont contradictoires
20 les lettres cl≈s -e, -i et -m s'excluent mutuellement
21 la classe "%s" n'existe pas
22 le mod…le "%s" n'existe pas
23 impossible d'acc≈der au fichier "%.50s"
24 impossible de supprimer le r≈pertoire REQUEST
25 impossible de supprimer l'imprimante
26 les demandes sont encore dans la file d'attente pour "%s";\nutilisez lpmove
27 impossible de supprimer le fichier de la classe
28 les lettres cl≈s -"%c" et -"%c" ont la m¡me valeur
29 ex≈cution impossible - le programmateur s'ex≈cute
30 impossible de lire le r≈pertoire en cours
31 impossible de lire le r≈pertoire en cours
32 impossible d'ouvrir le fichier destination syst…me par d≈faut
33 nouvelle imprimante
34 nouvelle destination
35 lettre cl≈ "%c" non valide
36 lettre cl≈ "-%c" inconnue
37 une valeur doit ¡tre associ≈e » la lettre cl≈ "%c"
38 l'administrateur LP n'est pas dans le fichier de mots de passe\n
39 impossible de d≈finir l'uid » celui de l'administrateur LP
40 r≈pertoire de spooling inexistant
41 syntaxes: lpadmin -pimprimante [-vp≈riph≈rique] [-cclasse] [-rclasse]\n
42 \t  [-eimprimante|-iinterface|-mmod…le] [-h|-l]\n
43 \t  lpadmin -d[destination]\n
44 \t  lpadmin -xdestination\n
45 mod…le d'≈tat "%s" inexistant
46 mod…le cancel "%s" inexistant
47 aucun argument pour ob3
48 L'argument de orc doit ¡tre 'y' ou 'n', et non %s
49 impossible de cr≈er le nouveau programme d'interface cancel
50 impossible de cr≈er le nouveau programme d'interface d'≈tat
51 touche "%s" non valide
52 \t  [-ociinterface|-ocmmod…le] [-ob3]\n
53 \t  [-osiinterface|-osmmod…le] [-orc]\n
54 \t  [-ormordinateur|-orpimprimante]\n
55 niveau de priorit≈ %d erron≈
56 noeudg "%s" inexistant
57 impossible de cr≈er l'interface "%s" comme fichier tributaire du contexte
58 impossible de d≈placer l'interface » la grappe sp≈cifi≈e
59 a
60 \t  [-agrappe_client]\n
$set 8
1 syntaxe: %s dest1 dest2\n\t -ou-\n\t %s demande ... destination\n
2 syst…me LP alt≈r≈
3 le programmateur s'ex≈cute encore - impossible d'ex≈cuter
4 destination "%s" inexistante
5 les destinations sont identiques
6 un total de %1$d demandes d≈plac≈es de %2$s vers %3$s\n
7 "%s" n'est pas un num≈ro d'identification de demande
8 un total de %1$d demandes d≈plac≈es vers %2$s\n
9 impossible d'ouvrir le r≈pertoire REQUEST %s
10 impossible de d≈placer la demande %s
11 la demande "%s-%d" n'existe pas
12 impossible d'ouvrir le fichier %s du r≈pertoire REQUEST
13 impossible de d≈placer la demande %s-%d
14 impossible de d≈placer la demande %s-%d
15 toutes les demandes ont ≈t≈ d≈plac≈es vers 
16 la destination %s ne prend pas en charge les demandes\n
17 d≈placement en cours d'ex≈cution ...\n
18 r≈pertoire de spooling inexistant
$set 9
1 tentative d'ouvrir un fichier supprim≈. Num≈ro de s≈quence (seqno): %d\n
2 Impossible d'ouvrir et de verrouiller "%s"\n
3 impossible d'ouvrir le r≈pertoire CLASS
4 impossible d'ouvrir le fichier %s dans le r≈pertoire CLASS
5 imprimante  %s inexistante dans la classe %s
6 impossible d'ouvrir le r≈pertoire REQUEST %s
7 impossible d'ouvrir la file d'attente de sortie temporaire
8 impossible de supprimer le lien avec l'ancienne file d'attente de sortie
10 ***** ARR§T‹  %s *****\n
11 suspension de l'impression par le programmateur: 
12 impossible d'ex≈cuter le programme d'interface d'impression (errno=%d)\n
13 \t CHILD: %s  %s %d %.4x\n
14 impossible d'≈crire dans %s
15 impossible d'ouvrir %s
16 impossible de r≈ouvrir le fichier d'erreur standard (stderr)
17 impossible d'acc≈der » FIFO
18 impossible d'ouvrir FIFO
19 impossible d'ouvrir le r≈pertoire MEMBER
20 impossible d'ouvrir le fichier %s dans le r≈pertoire MEMBER
21 code d'erreur %d dans la demande %s-%d pour l'imprimante %s
22 la demande d'impression %s-%d a ≈t≈ imprim≈e sur l'imprimante %s
23 erreur dans la demande d'impression %s-%d
24 suspension de l'impression (disabled) par programmateur: terminal d'ouverture
25 imprimante %s inexistante dans PSTATUS
26 \t FIFO: %s  %s\n
27 lpsched: impossible de cr≈er le journal de consignation
28 ***** JOURNAL LP: %s *****\n
29 FIFO: '%s' ?
30 impossible d'ouvrir le fichier REQUEST "%s"
31 impossible de cr≈er le fichier REQUEST temporaire "%s"
32 impossible de cr≈er le fichier REQUEST "%s"
33 impossible de d≈placer le fichier de donn≈es "%s"
35 impossible d'ouvrir le fichier REQUEST temporaire "%s"
36 impossible d'obtenir l'entr≈e du niveau de priorit≈ d≈termin≈ "%d"
37 l'entr≈e n'est plus dans le fichier d'≈tat d'impression
38 r≈pertoire de spooling inexistant
39 l'administrateur LP n'est pas dans le fichier de mots de passe
40 l'administrateur LP n'est pas dans un fichier de mots de passe prot≈g≈
41 impossible de d≈finir l'indicateur de v≈rification de l'administrateur LP
42 impossible de d≈finir l'uid » celui de l'administrateur LP
43 impossible de dupliquer (fork)
44 kill: pid %d non valide en utilisant %s\n
45 retour du d≈lai (wait) inattendu\n
46 \t FIFO: Destinations --\n
47 \t FIFO: %s: %s %s %s %s\n
48 p
49 c
50 prise en charge des demandes (enable)
51 aucune prise en charge des demandes
52 occup≈
53 inoccup≈
54 n'imprime pas
55 impression sur %s
56 \t FIFO: \t%d: %d %s %s heure:%d %s h¬te %s\n
57 seqno(3)
58 seqno(4)
59 \t FIFO:\t%d: %d %s %s heure:%d\n
60 \t FIFO: Imprimantes --\n
61 pid et id inconnus
62 pid=%d, id=%s-%d
63 \t FIFO: \t%s %s\n
64 \t FIFO: \t\t%s\n
65 \t FIFO: Classes --\n
66 \t FIFO: \t%s\n
68 syntaxe: %s [-v] [-a]\n
69 option "%s" inconnue
70 le conduit n'est pas reli≈
71 fermeture du conduit en ≈criture a ≈chou≈
72 le programmateur n'a pu ¡tre lanc≈
73 le programmateur ≈tait d≈j» actif
74 le programmateur s'ex≈cute
75 impossible d'acc≈der » SCHEDLOCK
$set 10
1 r≈pertoire de spooling inexistant
2 le programmateur s'est arr¡t≈\n
3 le programmateur ne s'ex≈cute pas
$set 11
1 option "%s" inconnue
3 destination syst…me par d≈faut: %s\n
4 aucune destination syst…me par d≈faut\n
6 Impossible d'ex≈cuter la commande d'≈tat %s » distance.\n
7 L'erreur %d s'est produite.\n
8 impossible d'allouer (malloc) de la m≈moire pour d'autres demandes.\n
9 "%s" n'est pas un id de demande ni une destination.
13  sur %s
14 
16  de %s
17 %-*s %-*s niveau de priorit≈ %d  %s%s%s\n
18 (entr≈e standard)
19 
20 %-4d exemplaires
21 \t%-*s          %s
22  %*ld octets\n
23  ??? octets\n
24 destination "%s" inexistante
25 %1$s accepte les demandes depuis %2$s\n
26 %1$s n'accepte plus les demandes depuis %2$s -\n\t%3$s\n
27 l'imprimante "%s" n'existe pas!
28 (terminal d'ouverture de session) 
29 envoi de %s-%d »  %s.\nprise en charge des demandes (enable) depuis %s
30 impression de %1$s-%2$d.\nprise en charge des demandes (enable) depuis %3$s
32 est inoccup≈.\nprise en charge des demandes (enable) depuis %1$s
33 suspension de l'impression (disable) depuis %1$s -\n\t%2$s
34 imprimante %1$s %2$s%3$s\n
35 \tpriorit≈ de base : %d\n
36 le r≈pertoire MEMBER n'existe plus!
38 p≈riph≈rique pour %1$s: %2$s
39 l'imprimante "%s" n'existe plus!
40 le r≈pertoire CLASS n'existe plus!
41 la classe "%s" n'existe pas
42 imprimantes de classe %s:\n
43 la classe "%s" n'existe plus!
44 le programmateur s'ex≈cute\n
45 le programmateur ne s'ex≈cute pas\n
46 r≈pertoire de spooling inexistant
47 espace insuffisant pour tous les noms d'utilisateurs\n
48 Le non l'utilisateur qui n'a pas ≈t≈ ajout≈ est %s\n
53 impossible d'ouvrir le fichier %s dans le r≈pertoire MEMBER
54 aucun p≈riph≈rique sp≈cifi≈ dans le r≈pertoire MEMBER
55 Impossible d'acc≈der au p≈riph≈rique  %s
56 Impossible d'obtenir l'heure courante
57 la commande execlp a ≈chou≈
60     syst…me ≈loign≈: %1$s sur %2$s \n
$set 12
2 impossible d'ouvrir le fichier de la file d'attente de sortie
$set 13
2 impossible d'ouvrir le fichier d'≈tat de l'imprimante
$set 14
2 impossible d'ouvrir le fichier d'≈tat d'acceptation
$set 15
1 syntaxe: %s [-r[raison]] dest ...\n
2 option "%s" inconnue
3 destination "%s" inexistante
4 aucune destination sp≈cifi≈e
5 la destination "%s" n'existe plus
6 raison inconnue
7 la destination "%s" n'accepte plus les demandes\n
8 la destination "%s" n'acceptait d≈j» plus les demandes\n
9 r≈pertoire de spooling inexistant
$set 16
1 \nlp: %s\n
$set 17
2 impossible d'ouvrir le fichier d'≈tat d'impression
$set 18
1 r≈pertoire de spooling inexistant
2 votre nom est trop long
3 Le nom d'ouverture de session  "-all" est r≈serv≈
4 Trop d'utilisateurs
6 Trop de demandes
7 rcancel: aucune imprimante n'≈tait sp≈cifi≈e
8 syntaxe: rcancel [-a] [imprimante] [-uutilisateur] [ids]\n
$set 19
1 r≈pertoire de spooling inexistant
2 Trop d'utilisateurs
3 Trop de demandes
4 rlpstat: aucune imprimante n'≈tait sp≈cifi≈e
5 syntaxe: rlpstat [-dimprimante] [-uutilisateur] [ids]\n
$set 20
3 r≈pertoire de spooling inexistant
4 impossible d'ex≈cuter - le programmateur s'ex≈cute
5 aucune imprimante "%s"
6 la valeur de la priorit≈ de base doit ¡tre comprise entre 0 et 7
7 syntaxe : %s imprimante priorit≈_de_base\n
$set 21
1 r≈pertoire de spooling inexistant
2 ≈tat d'acceptation de la destination "%s" inconnu
3 impossible d'accepter des demandes pour destination "%s" -\n\t%s
4 le programmateur ne s'ex≈cute pas. La modification a ≈chou≈.
5 l'identificateur %s-d% de la nouvelle demande n'a pas ≈t≈ mis\nen file d'attente\n
6 l'identificateur de la nouvelle demande est %s-%d\n
7 n'a pu ¡tre mis en file d'attente\n
8 demande "%s-%d" inexistante
9 demande "%s-%d" non modifi≈e: n'est pas le propri≈taire
10 impossible d'ouvrir le nouveau fichier de num≈ros de s≈quences "%s"
11 lettre cl≈ "%c" non valide
12 destination "%s" inexistante
13 la lettre cl≈ n'a pas besoin de l'argument "-%c%s"
14 trop d'options pour le programme d'interface
15 priorit≈ "-%c%s" erron≈e
16 lettre cl≈ "-%c" inconnue
17 syntaxe: lpalt id [-ddest] [-m] [-ncopies] [-ooption]\n\t [-ppriorit≈] [-s] [-ttitre] [-w]\n
18 la nouvelle destination doit diff≈rer de l'ancienne
$set 22
1 syntaxe: %s [-ddestination] [nom_fichier]\n
2 %s: impossible d'ouvrir %s\n
3 %s: erreur de format du fichier de consignation\n
4 %s: erreur dans l'attribution de la m≈moire\n
5 l'analyse des performances est effectu≈e » partir de %h.%d '%y %H:%M
6  jusqu'» %h.%d '%y %H:%M\n
7 ---imprimantes  --attente---   -impression-   --octets---   total nombre_de\n
8     /classes--  Moyenn ‹cart  Moyenn ‹cart    Moyenn ‹cart   Ko   demandes\n
