$set 1
1 Doit ¡tre un nom de fichier et non un chemin.
2 Doit ¡tre une valeur comprise entre 0 et 65 535.
3 Doit ¡tre une valeur comprise entre 1 et 65 535.
4 Doit ¡tre une valeur comprise entre 1 et 65 535.
5 L'un d'eux doit ¡tre sp≈cifi≈.
6 Au moins l'un d'eux doit ¡tre sp≈cifi≈.
7 Doit ¡tre 1 ou 2.
8 Doit ¡tre sup≈rieur » 0.
9 Peut-¡tre utilis≈ seulement si l'option "-l" a ≈t≈ sp≈cifi≈e.
10 Impossible de cr≈er un volume doubl≈ logique vide. Sp≈cifiez "-l".
11 Doit ¡tre 0 ou 1.
12 "%s": impossible de lire le label du disque; sp≈cifiez le type de disque:\n
13 "%s": impossible d'identifier la partition du disque.\n
14 "%s": partition `%c' n'est pas disponible.\n
15 "%s": n'est pas un fichier de p≈riph≈riques en mode caract…re.\n
16 "%s": n'est pas un volume logique.\n
17 ≈criture d'un enregistrement LVM
18 effacement du r≈pertoire de blocs erron≈s
19 trop de blocs erron≈s.\n
20 ≈criture du r≈pertoire de blocs erron≈s
21 ≈criture des entr≈es DEFECT01
22 doit ¡tre pr≈cis≈.
23 doit ¡tre pr≈cis≈.
24 doit ¡tre un fichier de p≈riph≈riques en mode bloc.
25 "-p" et "-s" peuvent ¡tre utilis≈es seulement avec "-a y".\n
26 Impossible de lire l'identificateur interne du\ngroupe de volumes "%s" de "%s".\n
27 "PhysicalExtentSize" doit ¡tre un nombre » la puissance 2 compris entre 1 et 256.
28 Doit ¡tre une valeur comprise entre 1 et 255.
29 Le groupe de volumes "%s" n'existe pas dans le fichier "%s",\nmais il existe dans le syst…me de fichiers. Traitement impossible.\n
30 Le groupe de volumes "%s" existe d≈j» dans le fichier "%s".\n
31 Le groupe de volumes "%s" n'a pas pu ¡tre cr≈≈:\n
32 Erreur lors de l'≈criture de "%s" et "%s" sur "%s".\n
33 "%s" ne peut ¡tre lu en m≈moire.\n
34 Le volume physique "%s" n'a pas pu ¡tre supprim≈ par le\ngestionnaire de p≈riph≈riques LVM. Incoh≈rence entre les\ninformations du syst…me de fichiers et le fichier "%s"\npour le groupe de volumes "%s":\n
35 Impossible de demander l'≈tat du groupe de volumes "%s":\n
36 Le groupe de volumes "%s" n'est pas actif.\nSeul un groupe de volumes actif peut ¡tre ≈tendu.\n
37 Le volume physique "%s" n'a pas pu ¡tre supprim≈ car il est\nmanquant ou non reli≈.\n
38 Le volume physique "%s" n'a pas pu ¡tre supprim≈ car certains\nde ses fragments physiques sont en cours d'utilisation.\n
39 Le volume physique "%s" n'a pas pu ¡tre supprim≈\ndu fichier "%s".\nIncoh≈rence entre le gestionnaire\nde p≈riph≈riques LVM et le fichier "%s".\n
40 Cr≈ation de "%s".\n
41 Suppression de "%s"
42 Restauration de "%s"
43 Sauvegarde de "%s" sur "%s"
44 Doit ¡tre un nombre.
45 Valeur erron≈e entr≈e. Les valeurs valides sont "%s".
46 Erreur de programme. Usage erron≈ des options prenant en charge les programmes.
47 Option utilis≈e plus d'une fois.
48 Option non valide.
49 Les options comportant des valeurs ne doivent pas ¡tre combin≈es\n» d'autres options.
50 Vous devez entrer une valeur apr…s l'option.
51 Il faut entrer plus d'arguments.
52 Aucun caract…re apr…s '-'.
53 Le volume physique "%s" n'a pu ¡tre ajout≈ » "%s" et\npar cons≈quent il n'a pas ≈t≈ ajout≈ au groupe de volumes.\n
54 Le volume physique "%s" est d≈j» enregistr≈ dans le fichier "%s".\n
55 Le volume physique "%s" n'est pas un fichier de\np≈riph≈riques en mode bloc.\n
56 Trop de volumes physiques dans Chemin_Volume_Physique. Au moins\nun volume physique doit demeurer dans le groupe.\n
57 Impossible d'installer le volume physique "%s".\n
58 Le volume physique "%s" a ≈t≈ reconnu par le gestionnaire\nde p≈riph≈riques LVM, mais il n'a pu ¡tre ajout≈ » "%s".\nL'≈tat de LVM n'est pas coh≈rent.\n
59 Le groupe de volumes "%s" n'existe pas dans le fichier "%s".\n
60 Impossible d'ouvrir le fichier de commandes "%s":\n
61 Chemin "%s" non valide.\n
62 Impossible d'ouvrir le r≈pertoire "%s":
63 Impossible d'acc≈der au volume physique "%s":\n
64 Impossible d'ouvrir le volume physique "%s":\n
65 Impossible d'interroger le volume physique "%s":\n
66 Attention : impossible d'interroger le volume physique "%s":\n
67 Impossible de supprimer le volume physique:\n
68 Impossible de supprimer le volume logique "%s":\n
69 Impossible d'interroger le volume physique:\n
70 Impossible d'interroger la table de correspondance d'affectation du\nvolume physique:\n
71 Impossible d'interroger la table de correspondance d'affectation du\nvolume logique:\n
72 Impossible de d≈finir l'identificateur unique pour le groupe de\nvolumes "%s":\n
73 Impossible de d≈sactiver le groupe de volumes "%s":\n
74 Impossible d'activer le groupe de volumes "%s":\n
75 Impossible d'interroger le groupe de volumes "%s":\n
76 Impossible d'interroger le volume logique:\n
77 Impossible d'interroger le volume logique "%s":\n
78 Impossible de r≈duire le volume logique:\n
79 Attention: Impossible de relier le volume physique "%s" au groupe :\n
80 Impossible d'≈tendre le volume logique:\n
81 Impossible de mettre » jour le contenu du fragment logique:\n
82 Impossible de resynchroniser les partitions non » jour du volume logique:\n
83 Impossible d'acc≈der » la liste des volumes physiques\npour le groupe "%s".\n
84 Impossible d'acc≈der » la liste des volumes logiques\npour le groupe "%s".\n
85 Impossible d'interroger la liste des volumes physiques.\n
86 Impossible d'interroger la liste des volumes logiques.\n
87 Impossible d'imprimer les informations sur le volume physique "%s".\n
88 Impossible d'imprimer les informations sur le volume logique "%s".\n
89 disponible
90 non disponible
91 Impossible de trouver le groupe de volumes\nauquel le volume physique "%s" appartient.\n
92 Impossible de trouver le groupe de volumes\nauquel le volume logique "%s" appartient.\n
93 non
94 oui
95 Aucun nom de groupe de volumes n'a pu ¡tre lu » partir de "%s".\n
96 Impossible d'afficher le groupe de volumes "%s".\n
97 Impossible d'afficher le volume logique "%s".\n
98 Impossible d'afficher le volume physique "%s".\n
99 Impossible d'obtenir le r≈pertoire de travail en cours
100 Impossible d'identifier le nom du groupe de volumes auquel appartient\nle volume logique "%s".\n
101 Impossible de g≈n≈rer un nom pour le volume logique.\n
102 Un volume logique du nom de "%s" sera cr≈≈.\n
103 Le groupe de volumes "%s" a ≈t≈ cr≈≈ avec succ…s.\n
104 Le volume logique "%s" a ≈t≈ cr≈≈ avec succ…s\navec le mineur %d.\n
105 Le volume physique "%s" a ≈t≈ cr≈≈ avec succ…s.\n
106 Transfert des fragments logiques du volume "%s"...\n
107 Le volume physique "%s" a ≈t≈ d≈plac≈ avec succ…s.\n
108 Le volume logique "%s" existe d≈j».\n
109 L'≈tat du groupe de volumes "%s" n'a pas pu ¡tre lu.\nLe majeur requis lors de la cr≈ation du volume logique n'a pu ¡tre r≈cup≈r≈.\n
110 Le volume logique "%s" n'a pu ¡tre cr≈≈:\n
111 Le volume logique "%s" n'a pu ¡tre cr≈≈\ncomme fichier sp≈cial\ndans le syst…me de fichiers:\n
112 Le volume logique "%s" n'a pu ¡tre supprim≈ du gestionnaire\nde p≈riph≈riques LVM. Incoh≈rence entre le gestionnaire de p≈riph≈riques\net le syst…me de fichiers :\n
113 lecture seulement
114 lecture/≈criture
115 disponible/non » jour
116 disponible/synchronisation
117 non diponible
118 en fonction
119 hors fonction
120 en fonction
121 hors fonction
122 stricte
123 non stricte
124 s≈quentielle
125 parall…le
126 disponible
127 non » jour
128 non » jour
129 en cours
130 manquant
131 non » jour
132 en cours
133 libre
134 "%s" n'est pas un volume logique.\n
135 Impossible d'obtenir le mineur du volume logique "%s".\n
136 Impossible de demander au gestionnaire de p≈riph≈riques LVM\nla d≈finition du volume logique "%s" en cours:\n
137 Le groupe de volumes "%s" a ≈t≈ modifi≈ avec succ…s.\n
138 Le volume logique "%s" a ≈t≈ modifi≈ avec succ…s.\n
139 Le volume logique "%s" n'a pu ¡tre modifi≈:\n
140 Le volume logique "%s" n'a pu ¡tre modifi≈.\nLe nombre d'informations doubl≈es est erron≈:\n
141 Le volume physique "%s" a ≈t≈ modifi≈ avec succ…s.\n
142 Le volume physique "%s" n'a pu ¡tre modifi≈:\n
143 Le groupe de volumes auquel appartient le volume logique "%s"\nest introuvable. Le chemin du volume logique est probablement erron≈.\n
144 "MirrorCopies\" parameter \"%d\" must be larger than existing number \"%d\".\n
145 "LogicalExtentsNumber" n'est pas plus ≈lev≈ que la valeur en cours.\n
146 "LogicalExtentsNumber" est plus ≈lev≈ que la valeur maximale autoris≈e.\n
147 Le groupe de volumes "%s" a ≈t≈ ≈tendu avec succ…s.\n
148 Le volume logique "%s" a ≈t≈ ≈tendu avec succ…s.\n
149 Le groupe de volumes "%s" a ≈t≈ r≈duit avec succ…s.\n
150 Le volume logique "%s" a ≈t≈ r≈duit avec succ…s.\n
151 Le volume logique "%s" n'est pas r≈duit.\n
152 Le groupe de volumes "%s" a ≈t≈ supprim≈ avec succ…s.\n
153 Le volume logique "%s" a ≈t≈ supprim≈ avec succ…s.\n
154 Impossible de r≈cup≈rer la table de correspondance d'affectation du\nvolume logique "%s".\n
155 Impossible de r≈cup≈rer la table de correspondance d'affectation du\nvolume physique "%s".\n
156 Impossible de r≈cup≈rer la liste des volumes physiques appartenant au\ngroupe de volumes "%s".\n
157 Le volume physique "%s" n'appartient pas\nau groupe de volumes "%s".\n
158 Nombre insuffisant de fragments physiques disponibles.\nLe volume logique "%s" n'a pu ¡tre ≈tendu.\n
159 Incident peut-¡tre caus≈ par le principe d'affectation stricte\n
160 Le gestionnaire de p≈riph≈riques LVM n'a pu ≈tendre le\nvolume logique "%s".\n
161 Impossible d'ajouter deux nouveaux miroirs » un volume\nphysique quand le principe d'affectation est STRICT.\n
162 \"MirrorCopies\" parameter \"%d\" must be smaller than existing \
number \"%d\".\n
163 "LogicalExtentsNumber" n'est pas inf≈rieur » la valeur en cours;\npar cons≈quent aucun fragment logique n'est supprim≈.\n
164 Lorsqu'un volume logique est r≈duit, des donn≈es utiles peuvent ¡tre\nperdues; voulez-vous vraiment ex≈cuter la commande (o/n) : 
165 Le volume logique "%s" n'est pas vide;\nvoulez-vous vraiment supprimer le volume logique (o/n) : 
166 Le volume physique comporte d≈j» un syst…me de fichiers.\nVoulez-vous proc≈der (o/n) : 
167 Le volume physique appartient d≈j» » un groupe de volumes\n
168 Le gestionnaire de p≈riph≈riques LVM n'a pas r≈ussi » r≈duire\nle volume logique "%s".\n
169 Le gestionnaire de p≈riph≈riques LVM n'a pas r≈ussi » r≈duire\nles miroirs sur le volume logique "%s".\n
170 Le volume logique "%s" ne peut ¡tre supprim≈ puisqu'il est actif.\n
171 Impossible de supprimer le fichier sp≈cial correspondant au\nvolume logique "%s" dans le syst…me de fichiers.\n‹tant donn≈ que le volume logique n'est pas reconnu du gestionnaire\nde p≈riph≈riques LVM, il doit ¡tre supprim≈ » l'aide des commandes\nUnix habituelles (chmod(1), rm(1)).\n
172 Impossible de r≈cup≈rer les noms des volumes physiques\nappartenant au groupe de volumes "%s".\n
173 Impossible de r≈cup≈rer les noms des volumes logiques\nappartenant au groupe de volumes "%s".\n
174 L'affectation n'est pas autoris≈e sur le volume physique "%s".\n
175 Le volume physique source appartient ≈galement » l'ensemble des volumes\nphysiques cibles.\n
176 Le groupe de volumes "%s" ne contient pas de volume logique.\n
177 Le volume logique "%s" n'appartient pas au\ngroupe de volumes "%s".\n
178 Impossible d'ouvrir le groupe de volumes "%s".\n
179 Impossible de rep≈rer un fragment physique libre pour le fragment logique\n%d du volume logique "%s".\n
180 Attention: le volume physique "%s" est manquant.\n
181 Impossible de supprimer le groupe de volumes "%s".\n
182 Le groupe de volumes "%s" est encore actif.\n
183 Le groupe de volumes "%s" contient encore des volumes logiques.\n
184 Le groupe de volumes "%s" contient encore plus d'un volume physique.\n
185 Impossible de supprimer le sous-syst…me de fichiers "%s".\n
186 Impossible de supprimer l'entr≈e "%s" de "%s".\n
187 Groupe de volumes resynchronis≈ "%s".\n
188 Volume logique resynchronis≈ "%s".\n
189 Impossible de resynchroniser le groupe de volumes "%s".\n
190 Impossible de resynchroniser le volume logique "%s".\n
191 Aucun volume physique reli≈ ou aucune VGDA valide rep≈r≈e\nsur les volumes physiques.
192 M≈moire insuffisante dans le noyau pour terminer la demande.
193 Erreur E/S lors de la lecture de la VGDA.
194 Espace minimal requis non disponible, ou il manque certains volumes physiques.\n
195 Un ≈l≈ment du chemin du volume physique n'existe pas.
196 Le chemin du volume physique d≈signe un p≈riph≈rique qui n'existe\npas ou qui n'est pas configur≈ dans le noyau.
197 appel ioctl erron≈ pour le p≈riph≈rique - la commande a ≈t≈ envoy≈e pour un\np≈riph≈rique de volumes logiques plut¬t que pour un p≈riph≈rique de commandes.
198 Le mineur entr≈ d≈signe un volume logique inexistant.
199 Le groupe de volumes n'est pas actif.
200 La demande de r≈duction n'a pas ≈t≈ pr≈c≈d≈e d'une d≈saffectation ad≈quate.
201 Le mineur entr≈ d≈signe un volume logique d≈j» existant.
202 Le chemin ne pr≈cise pas un volume physique valide.
203 Impossible de lire le volume physique.
204 Aucun gestionnaire n'est configur≈ pour le volume physique.
205 Espace insuffisant sur le volume pour la VGRA.
206 Autorisation refus≈e pour l'ouverture du chemin du volume physique.
207 Le chemin du volume physique ne d≈signe pas un p≈riph≈rique en mode bloc.
208 Le mineur entr≈ d≈signe un volume logique inexistant.
209 Le volume logique sp≈cifi≈ est ouvert.
210 Le volume logique sp≈cifi≈ n'existe pas.
211 Un fragment physique du tableau des fragments est d≈j» utilis≈.
212 Aucun gestionnaire n'est configur≈ pour le volume physique.
213 Autorisation d'≈criture refus≈e sur le p≈riph≈rique.
214 Le chemin d≈signe un fichier qui n'est pas un fichier de p≈riph en mode bloc.
215 Un ≈l≈ment du chemin n'est pas accessible.
216 Le groupe de volumes n'est pas actif.\n
217 Impossible de relier au groupe de volumes "%s" tous\nles volumes physiques lui appartenant.\n
218 Warning: Couldn't deattach the physical volume \"%s\"\nfrom the volume group.\n
219 Impossible de supprimer le fichier "%s":
220 Impossible de supprimer le r≈pertoire "%s":
221 Nom VG
222 ‹tat VG
223 LV maximal
224 LV en cours
225 LV ouvert
226 PV maximal
227 PV en cours
228 PV actif
229 Taille PE
230 PE maximal par PV
231 PE total
232 Affectation des PE
233 PE disponible
234 VGDA
235 Nom LV
236 Nom VG
237 Autorisation LV
238 ‹tat LV
239 V≈rifier ≈criture
240 Copies miroirs
241 Planification
242 LE en cours
243 PE affect≈
244 Bloc erron≈
245 Affectation
246 PV utilis≈
247 Nom PV
248 Nom VG
249 ‹tat PV
250 Attribuable
251 VGDA
252 LV en cours
253 Taille PE
254 PE total
255 PE disponible
256 PE affect≈
257 PE non » jour
258 LE
259 PV1
260 PE1
261 ‹tat 1
262 PV2
263 PE2
264 ‹tat 2
265 PV3
266 PE3
267 ‹tat 3
268 PE
269 ‹tat
270 LV
271 LE
272 Nom PV
273 LE sur PV
274 PE sur PV
275 Nom LV
276 LE de LV
277 PE pour LV
278 Groupes de volumes
279 Volumes logiques
280 Volumes physiques
281 Fragments logiques
282 Fragments physiques
283 Distribution du volume logique
284 Distribution du volume physique
285 Le chemin sp≈cifi≈ ne correspond pas au volume physique reli≈ »\nce groupe de volumes
286 Le groupe de volumes n'est pas actif
287 Param…tre d'entr≈e erron≈\n
288 Le nombre de miroirs ne peut ¡tre ≈tendu puisque aucun fragment logique\nn'est affect≈ au volume logique.\n
289 Attention: Le volume physique "%s" n'est pas\ndisponible pour l'affectation.\n
290 Les nouveaux disques miroirs sont en cours de synchronisation.\nL'op≈ration demande du temps. Veuillez patienter...\n
$set 2
1 Impossible de combiner des p≈riph≈riques HP-IB et non HP-IB.\n
2 Impossible de doubler sur les p≈riph≈riques HP-IB.\n
3 Impossible de r≈affecter les blocs erron≈s sur les p≈riph≈riques HP-IB.\n
4 PVG total
5 Groupes de volumes physiques
6 Nom VG
7 Nom PVG
8 Nom PV
9 Affect PVG stricte
10 L'ajout du groupe de volumes "%s" au fichier "%s" a ≈chou≈.\n
11 Le groupe de volumes physiques "%s" est d≈j» d≈fini dans le groupe "%s".\n
12 L'ajout du groupe de volumes physiques "%s" au groupe "%s" a ≈chou≈.\n
13 Le groupe de volumes physiques "%s" a ≈t≈ cr≈≈ avec succ…s.\n
14 ‹chec; groupe de volumes physiques "%s" non cr≈≈.\n
15 Le PVG cible "%s" ne contient aucun PV.\n
16 Impossible de cr≈er le LV d'affectation PVG stricte car le VG "%s" n'est/npas d≈fini dans "%s".\n
17 Impossible de passer » un principe d'affectation plus stricte\ncar le LV "%s" a des copies miroirs.\n
18 Le PVG "%s" n'est pas d≈fini dans le VG "%s".\n
19 ‹chec peut-¡tre caus≈ par le principe d'affectation PVG stricte.\n
20 Le VG "%s" n'est pas d≈fini dans le fichier "%s".\n
21 L'ajout du PVG "%s" a ≈chou≈.\n
22 L'extension du PVG "%s" a ≈chou≈.\n
23 Le groupe de volumes physiques "%s" a ≈t≈ ≈tendu avec succ…s.\n
24 ‹chec; groupe de volumes physiques "%s" non ≈tendu.\n
25 Le volume physique "%s" n'a pas pu ¡tre supprim≈ du fichier "%s".\n
26 Le volume physique "%s" a ≈t≈ supprim≈ avec succ…s du groupe "%s".\n
27 Impossible de supprimer le groupe de volumes "%s" du fichier "%s".\n
28 Le groupe de volumes "%s" a ≈t≈ supprim≈ avec succ…s du fichier "%s".\n
29 Fichier "%s" manquant.\n
30 Erreur rep≈r≈e lors de la cr≈ation du fichier "%s".\n
31 Erreur rep≈r≈e lors de la lecture du fichier "%s".\n
32 Erreur rep≈r≈e lors de l'≈criture dans le fichier "%s".\n
33 Fichier "%s" erron≈: Mot-cl≈ VG manquant.\n
34 Fichier "%s" erron≈: le VG "%s" n'a aucun PVG.\n
35 Fichier "%s" erron≈: Mot-cl≈ PVG manquant.\n
36 Fichier "%s" erron≈: le PVG "%s" n'a aucun PV.\n
37 Les informations dans "%s" diff…rent de celles de "%s".\n
38 Fichier "%s" erron≈: Chemin "%s" non valide.\n
39 Fichier "%s" erron≈:\nle PVG n'a pas de nom dans le VG "%s".\n
40 Impossible de r≈affecter le volume logique:\n
41 Fichier "%s" erron≈: le PVG "%s" est d≈fini\ndeux fois dans le VG "%s".\n
42 Fichier "%s" erron≈: le PV "%s" dans "%s" est d≈fini\ndeux fois dans le VG "%s".\n
43 Incoh≈rence entre les fichiers "%s" et "%s".\n
44 Les volumes logiques ne font pas partie du m¡me groupe.\n
45 Des fragments sont d≈j» affect≈s au volume logique cible: %s\n
46 Aucun fragment n'est affect≈ au volume logique source: %s\n
47 Le nombre de miroirs est insuffisant pour faire une copie scind≈e: %s\n
48 Le volume logique "%s" a ≈t≈ scind≈ avec succ…s.\n
49 Les volumes logiques "%s" et "%s"\nsont de taille diff≈rente.\n
50 Le volume logique "%s" ne peut avoir une autre copie miroir.\n
51 Le volume logique "%s" a ≈t≈ fusionn≈ avec succ…s\navec le volume logique "%s".\n
52 Attention: Il peut y avoir incoh≈rence entre les miroirs sur le\nvolume logique "%s" en raison d'un arr¡t incorrect.\n
53 Aucun fragment n'est ° JOUR sur le LV "%s", LX "%d".\n
54 Impossible de mettre les fragments ° JOUR pour le LV "%s".\n
55 Impossible de r≈tablir la coh≈rence entre les miroirs pour le LV "%s".\n
56 Le d≈mon "%s" a ≈t≈ relanc≈ pour r≈tablir la coh≈rence entre\nles miroirs pour "%s".\n
57 Impossible de changer MirrorWriteCache lorsqu'un LV est ouvert\nou en cours de synchronisation.\n
58 On peut utiliser "-c" seulement avec "-M n".\n
59 On peut utiliser "-c" seulement lorsque MWC est hors fonction ou en voie\nde le devenir.\n
60 R≈tablissement de la coh≈rence
61 MWC
62 NOMWC
63 AUCUNE
64 disponible
65 Combinaison d'options non valide
66 Erreur d'E/S au fichier de configuration\n
67 Erreur d'E/S au p≈riph≈rique du volume physique\n
68 Aucun espace m≈moire » affecter (malloc)\n
69 LVMREC non valide sur le volume physique %s\n
70 Impossible d'acc≈der au volume physique %s:\nConservation des donn≈es d≈j» sauvegard≈es\n
71 Impossible de trouver le volume physique %s\ndans le fichier de configuration %s.\nFichier de configuration non mis » jour.\n
72 Impossible d'ouvrir le volume physique "%s".\n
73 Tous les PV doivent ¡tre pr≈sents pour la sauvegarde de la configuration\ndu groupe de volumes.\n
74 Configuration du groupe de volumes pour %s sauvegard≈e dans %s\n
75 Configuration du groupe de volumes restaur≈e dans %s\n
76 Informations de configuration pour volume physique "%s"\nintrouvables dans "%s" :\nFichier de p≈riph≈riques en mode caract…re pour le PV non indiqu≈ sur\nla ligne de commande, OU le PV n'appartenait pas au groupe de\nvolumes %s lors de la cr≈ation du fichier de configuration.\n
77 Erreur d'ouverture du fichier de configuration LVM : %s\n
78 Le fichier de configuration semble ¡tre alt≈r≈\n
79 Groupe de volumes : %s non trouv≈ dans fichier de configuration %s\n
80 Informations de configuration du groupe de volumes dans "%s"\n
81 (Amorµable)
82 (Non amorµable)
83 OldPVPath et PVPath : fichiers de p≈riph≈riques en mode caract…re\n
84 Fichier de configuration "%s" introuvable ou alt≈r≈\n
85 La VGRA semble ¡tre alt≈r≈e\n
86 Le volume physique "%s" ne contient aucune information LVM\n
87 Le volume physique "%s" n'est pas un disque d'initialisation\n
88 Le volume physique "%s" ne fait pas partie d'un groupe de volumes\n
89 Impossible de passer » l'≈criture miroir en contigu car le LV "%s"\nposs…de d≈j» des fragments physiques non contigus.\n
90 non strict/contigu
91 strict/contigu
92 PVG strict/contigu
93 ‹chec peut-¡tre caus≈ par l'≈criture miroir en contigu.\n
94 V≈rifiez l'option [CheminVolumePhysique... | NomGroupeVolumePhysique...]\npour vous assurer qu'elle prend en compte les volumes physiques\nexistants pour tous les miroirs.\n
95 Impossible d'exporter le groupe de volumes "%s".\n
96 Impossible d'ouvrir le fichier de table de correspondances "%s".\n
97 Le groupe de volumes "%s" est actif dans ce syst…me.\nImpossible de remplacer "%s" lorsque des groupes\nde volumes sont actifs.\n
98 Impossible d'analyser le fichier de table de correspondances "%s".\n
99 Le volume logique "%s" trouv≈ dans "%s"\nn'est pas d≈fini sur le volume physique.\n
100 Impossible de balayer les volumes physiques dans le syst…me\n
101 Impossible de terminer l'importation ou de cr≈er le fichier de table de\ncorrespondances pour VG%02d.\n
102 Balayage des volumes physiques termin≈.\n
103 Impossible de lancer l'ex≈cution (exec).\n
104 Identificateur de groupe de volumes sur disques import≈s correspond au\ngroupe de volumes existant "%s".\n
105 Attention: Groupe de volumes "%s" d≈fini dans le\nfichier "%s", mais manquant dans le fichier\nsp≈cial de groupe. Impossible de d≈terminer le num≈ro de groupe de volumes.\nLe traitement se poursuit.\n
106 Nombre maximal de groupes de volumes d≈j» atteint dans le syst…me.\n
107 Attention: le nombre de volumes physiques sur la ligne de commande "%d"\nne correspond pas au nombre de volumes physiques "%d" dans les\ninformations de groupe de volumes sur les volumes physiques import≈s.\nLe traitement se poursuit.\n
108 D≈but de l'exportation du groupe de volumes "%s".\n
109 D≈but de l'importation du groupe de volumes "%s".\n
110 Attention: le num≈ro de volume logique "%d" trouv≈ sur le volume physique\nest introuvable dans "%s".\n
111 Attention: le volume logique "%s" existe d≈j»,\nmais ne correspond pas » l'identificateur de groupe de volumes\npour "%s".  Suppression en cours.\n
112 Impossible de verrouiller "%s", nouvel essai en cours ...
113 Cette valeur doit ¡tre comprise entre 0 et 7039.
114 Trop d'arguments
115 Le volume logique "%s" doit ¡tre contigu.\n
116 Impossible d'ouvrir /dev/console\n
117 Le volume physique "%s" sur lequel se trouve\nle volume logique "%s" n'est pas un volume\nphysique d'initialisation.\n
118 Il faut d'abord affecter un volume logique racine avant d'affecter\nun volume logique de vidage ou de permutation.\n
119 Un volume logique a d≈j» ≈t≈ affect≈ au volume racine ou de permutation.\n
120 Aucune information d'initialisation LIF rep≈r≈e sur "%s".\n
121 Attention : fichier de labels introuvable ou\nalt≈r≈ sur "%s". Cr≈ation.\n
122 Informations LIF alt≈r≈es ou absentes sur "%s".\n
123 Le fichier de labels est plein. Aucune autre entr≈e autoris≈e.\n
124 Unable to write LABEL from \"%s\" to \"%s\": %s.\n
125 Aucune zone r≈serv≈e de donn≈es d'initialisation valide sur les\nvolumes physiques dans le groupe de volumes "%s".\nEntrez la commande pvcreate -B pour cr≈er une zone d'initialisation\nsur un volume physique.\n
126 Volume logique "%s" rep≈r≈ sur le volume physique "%s".\n
127 Le volume racine doit ¡tre le premier volume logique sur le volume physique.\n
128 Impossible de supprimer le volume logique de vidage \n
129 Impossible de supprimer le volume logique de permutation\n
130 Impossible de supprimer le volume logique racine \n
131 Le volume logique "%s" est d≈j» configur≈ comme volume logique racine.\n
132 Le volume logique "%s" n'est pas configur≈ comme volume\nracine, de permutation ou de vidage.\n
133 La zone de donn≈es d'initialisation est vide.\n
134 Attention : Une zone valide de donn≈es d'initialisation a ≈t≈ rep≈r≈e.\nSi le volume physique "%s" doit devenir un p≈riph≈rique\nd'initialisation » l'aide de /etc/mkboot, ce nouveau fichier de labels\nsera remplac≈.\n
135 Trop de volumes physiques dans Chemin_Volume_Physique.\nMaximum autoris≈ : "%d"\n
136 Le nombre maximum de volumes logiques de vidage a ≈t≈ d≈pass≈.\nImpossible d'ajouter un autre volume logique de vidage.\n
137 D≈finitions d'initialisation pour le groupe de volumes %s:\n
138 Volumes physiques appartenant au groupe de volumes racine:\n
139 %s: %s\tsur: 
140 %s: %s\tsur: %s\n
141 Racine
142 Permutation
143 Vidage
144 Label: %d, %s D≈but du volume: %d longueur %d\n
145 Aucun volume logique %s configur≈\n
146 Le volume logique n'a aucun fragment.\n
147 Disques d'initialisation: 
148 Nombre de fragments physiques par volume physique insuffisant.\nRequis: %d, Existants: %d.\n
149 Le nombre de fragments physiques par volume physique a ≈t≈ augment≈ » %d.\n
150 Physical extents on remaining physical volumes are stale.\n
151 The Physical Volumes specified on the command line\n\
do not belong to the same Volume Group.\n
152 Only one VolumeGroupName can be specified in \n\
combination with the \-r\, \-s\, or \-d\ options.
153 Entry for %s Logical Volume already exists\n\
at a different starting location.  Can not add %s Logical Volume\n
154 Warning: rounding up logical volume size to \
extent boundary at size \%d\ MB.\n
155 Can be used only if \-l\ or \-L\ has been \
specified.
156 Can be used only if \-m\ has been specified.
157 Can't create a mirrored empty logical \
volume. Specify \-l\ or \-L\.)
158 The Logical Volume has a mounted file system \
on it.
159 Warning: The Logical Volume has a file system larger \
than the reduced size.\n.Reducing the \
Logical Volume will cause filesystem corruption.\n
160 The Logical Volume is used as a swap device.
161 LV Size (Mbytes)
162 Root Logical Volume can not have Bad Block Relocation.\n
163 Following Physical Volumes belong to one Volume Group\
.nUnable to match these Physical Volumes to a Volume Group.\n\
Use the vgimport command to complete the process.\n
164 The Volume Group %s was not matched with any Physical Volumes.\n
165 Logical volume %s has been successfully created with\n\
character device %s.\n
166 Run the \lvextend\ command to create space on the Logical Volume.\n.
167 Run the \lvextend\ command add mirror copies on the Logical Volume.\n.
168 Warning:  Can not determine all Physical Volumes on which \
mirrored copies of\nthe Logical Volume are located.   %s is missing Physical \
Volumes.\n
169 Warning:  Volume Group belongs to different CPU ID.\n\
Can not determine if Volume Group is in use on another system. Continuing.\n
170 Couldn't split the logical volume.\n\
Synchronize the stale extents in the logical volume by running lvsync before\n\
lvsplit.\n

$set 3
1 o
2 n
