$set 1
1 mail: impossible d'ouvrir %s en ≈criture\n
2 syntaxe: mail [+] [-epqr] [-f fichier]\n
3          mail [-dt] utilisateurs\n
4 mail: impossible d'attribuer hmbox
5 mail: impossible d'attribuer mailfile
6 mail: autorisation refus≈e!\n
7 mail: impossible d'ouvrir %s\n
8 Pas de courrier.\n
9 V≈rifiez le mode et l'ID de groupe de mailfile.\n
10 Votre courrier est exp≈di≈ » 
11 %s
12 et votre bo—te aux lettres contient des donn≈es suppl≈mentaires\n
13 mail: impossible d'ouvrir %s\n
14 syntaxe\n
15 q\t\tsortir\n
16 x\t\tsortir sans modifier le courrier\n
17 p\t\timprimer\n
18 s [fich]\tsauvegarder (par d≈faut dans mbox)\n
19 w [fich]\tsauvegarder sans l'en-t¡te\n
20 -\t\timprimer le message pr≈c≈dent\n
21 d\t\tsupprimer\n
22 +\t\tpasser » la ligne suivante (sans supprimer)\n
23 m util\t\texp≈dier le message » l'utilisateur\n
24 ! cmde\t\tex≈cuter la commande\n
25 commande non valide\n
26 mail: impossible d'annexer » %s\n
27 mail: impossible de sauvegarder le courrier\n
28 commande non valide\n
29 %s n'a pas de valeur ou n'a pas ≈t≈ export≈.\n
30 !\n
31 mail: impossible d'≈crire %s de nouveau\n
33 mail: impossible de lire %s de nouveau\n
34 Remise dans la bo—te aux lettres: Trop de lettres\n
35 mail: mise » jour de %s impossible\n
36 mail: mise » jour de %s impossible\n
37 mail: mise » jour de %s impossible\n
38 mail: impossible de remettre le courrier dans la bo—te aux lettres\n
39 du nouveau courrier est arriv≈\n
40 \007Attention: Trop de lettres, lettres exc≈dentaires concat≈n≈es\n\n
42 mail: impossible d'ouvrir de nouveau %s en lecture\n
43 mail: impossible d'ex≈cuter l'allocation de m≈moire (malloc)\n
44 mail: impossible de cr≈er %s\n
45 Courrier sauvegard≈ dans %s\n
46 Courrier sauvegard≈ dans %s\n
47 mail: impossible de sauvegarder dans dead.letter\n
48 ligne d'en-t¡te trop longue\n
49 nom nul\n
50 nom nul\n
51 mail: impossible d'≈tablir un conduit avec la commande mail\n
52 envoi non born≈\n
53 mail: impossible d'envoyer » %s\n
54 mail: impossible d'annexer » %s\n
55 mail: impossible d'annexer » %s\n
56 mail: impossible d'annexer » %s\n
57 mail: signal d'erreur %d\n
58 mail: impossible de verrouiller sur %s apr…s %d essais infructueux\n
59 mail: impossible de cr≈er %s apr…s %d essais infructueux\n
