$set 1
1 r≈action: 
3 Too much "sourcing" going on.\n
4 "Source" stack over-pop.\n
5 "if" sans correspondance\n
$set 2
1 Plus de courrier.\n
2 Sur la derni…re page-≈cran de messages\n
3 Sur la premi…re page-≈cran de messages\n
4 Commande de d≈filement "%s" inconnue\n
5 Les commandes sont:\n
6 Message %2d:\n
7 Message %2d:\n
8 Aucune valeur d≈finie pour la variable "folder"\n
$set 3
1 Aucun message ne s'applique\n
2 ° la fin du fichier\n
3 Aucun message » sauvegarder.\n
4 Aucun message » copier.\n
5 [Conduit ≈tabli]
6 [Annex≈]
7 [Nouveau fichier]
8 \n‹tat de sortie = %d.\n
9 Aucun message » enregistrer.\n
10 [Conduit ≈tabli]
11 [Annex≈]
12 [Nouveau fichier]
13 \n‹tat de sortie = %d.\n
14 Erreur de syntaxe: %c manquant.\n
15 Aucun fichier sp≈cifi≈.\n
16 ° la fin du fichier\n
17 Plus de messages\n
18 Toutes les zones sont prises en compte.\n
$set 4
1 D≈bordement du tampon de commandes\n
2 Aucune aide n'est offerte pr≈sentement.\n
3 D≈sol≈, impossible de r≈pondre » plusieurs messages » la fois\n
4 Zone "r≈pondre »" (R) vide -- r≈ponse envoy≈ » l'auteur\n
5 Impossible "de conserver" (pre) en mode ≈dition\n
6 Nom de variable non nul requis\n
7 Un nom de groupe doit ¡tre sp≈cifi≈\n
8 "%s": n'est pas un groupe\n
9 Aucun fichier pr≈c≈dent\n
10 Imbrication de "if" non valide\n
11 Mot cl≈ if non reconnu: "%s"\n
12 "Else" sans "if" correspondant\n
13 condition non valide rencontr≈e\n
14 "Endif" sans "if" correspondant\n
$set 5
1 erreur de commande de conduit\n
2 commande "cmd" non d≈finie, non prise en compte.\n
3 Pas de messages pour ≈tablir un conduit.\n
4 Conduit avec: "%s"\n
5 \n‹tat de sortie = %d.\n
6 Le conduit avec "%s" a ≈chou≈\n
$set 6
1 Utilisez un "." pour terminer la lettre\n
2 Caract…re tilde d'≈chappement inconnu.\n
3 (se poursuit)\n
4 ~h: rien » faire!?\n
5 (se poursuit)\n
6 Quel fichier d≈sirez-vous interpoler?\n
7 %s: r≈pertoire\n
8 Dans quel fichier d≈sirez-vous ≈crire?\n
9 Aucun message » envoyer » partir de!?!\n
10 (se poursuit)\n
11 Aucune aide n'est pas offerte pr≈sentement.\n
12 -------\nMessage comprenant:\n
13 (se poursuit)\n
14 (se poursuit)\n
15 (se poursuit)\n
16 Ce fichier existe\n
17  [annex≈] %d/%ld\n
18 %s: ce fichier existe\n
19 Erreur grave dans "%s"\n
20 Fichier tmp de l'≈diteur sauvegard≈ sous %s\n
21 "%s" a ≈chou≈!?\n
22 Aucun octet depuis "%s" !?\n
23 Aucun message appropri≈\n
24 Interpolation:
25 (se poursuit)\n
26 \n(Interruption -- appuyez encore une fois et il n'y aura plus de lettres)\n
$set 7
1 %s: ce fichier existe\n
$set 8
1 Votre courrier est exp≈di≈ » %s\n
2 et votre bo—te aux lettres contient des donn≈es en plus\n
3 recherche du fichier temporaire
4 M≈moire insuffisante pour %d messages\n
5 Erreur de lecture du fichier de message fant¬me\n
6 supprim≈\n
7 termin≈\n
8 La commande echo a ≈chou≈\n
9 "%s": aucune concordance\n
10 D≈bordement du tampon, expansion de "%s"\n
11 "%s": Ambigu\n
12 mailx: suppression d'un caract…re NUL dans le fichier de courrier\n
13 mailx: suppression de %d caract…res NUL dans le fichier de courrier\n
$set 9
1 Impossible de trouver un emplacement vide pour entr≈e h¬te dynamique\n
2 Impossible d'ouvrir %s\n
3 aucun nom de syst…me dans %s\n
$set 10
1 Pas de courrier.\n
2 Pas de courrier pour %s\n
3 %s: ce fichier est vide\n
4 Pas de courrier.\n
5 Pas de courrier pour %s\n
6 Votre courrier est exp≈di≈ » %s
7 Utilisez "q" pour sortir.\n
8 Impossible de "!" » cette ≈tape\n
9 Commande inconnue dans le fichier source: "%s"\n
10 Commande inconnue: "%s"\n
11 "%s" ne s'ex≈cutera peut-¡tre pas pendant l'envoi\n
12 "%s" ne s'ex≈cutera peut-¡tre pas pendant l'appel de fichiers sources\n
13 "%s" ne s'ex≈cutera peut-¡tre pas--\n     fichier message accessible en lecture seulement\n
14 Appel r≈current de "%s" impossible\n
15 Utilisation non valide de la liste de messages\n
16 Aucun message ne s'applique\n
17 Utilisation non valide de la liste de messages\n
18 %s n≈cessite au moins %d argument(s)\n
19 %s n'accepte pas plus de %d argument(s)\n
20 Type d'argument inconnu
21 Interruption\n
22 mailx %s  Entrez ? pour obtenir de l'aide.\n
23 1 message
24 %d messages
25  %d nouveau (x)
26  %d non lu (s)
27  %d supprim≈ (s)
28  %d sauvegard≈ (s)
29  [Lecture seulement]
$set 11
1 Aucun num≈ro n'est associ≈ » *\n
2 Le deuxi…me argument n'est pas num≈rique\n
3 Modificateur deux-points inconnu "%s"\n
4 Impossible  d'associer * avec quoi que ce soit\n
5 Aucun message ne s'applique.\n
6 Aucun message ne s'applique en provenance de {%s
7 }\n
8 Aucun message ne satisfait aux conditions
9 %d: Num≈ro de message non valide\n
10 %d: Message non appropri≈\n
11 Attention: seuls premiers %d arguments de la commande %s sont ex≈cut≈s.\n
12 %c manquant\n
13 Trop de probl…mes
14 Num≈ro de message » marquer erron≈
15 Num≈ro de message dont il faut supprimer la marque erron≈
16 Aucun message ne s'applique\n
17 R≈f≈rence apr…s le dernier message\n
18 R≈f≈rence avant le premier message\n
19 Aucun message ne s'applique\n
20 %d: message non appropri≈\n
21 M≈tacaract…re (%c) inconnu\n
$set 12
1 -h n≈cessite un nombre autre que z≈ro\n
2 syntaxe: mailx [-FU] [-s objet] [-r adresse] [-h nombre] adresse...\n
3          mailx -e\n
4          mailx [-UHiNn] [-u utilisateur]\n
5          mailx -f [-UHiNn] [nom_fichier]\n
6 Vous devez pr≈ciser -f avec l'indicateur -I\n
7 Impossible de pr≈ciser -f et des destinataires.\n
8 Les indicateurs donn≈s sont utilis≈s seulement pour l'envoi de courrier.\n
9 Pas de courrier pour %s\n
10 \nInterruption\n
$set 13
1 Il manque quelque chose -- aucun @ ou % dans arpafix\n
2 Impossibilit≈ de cr≈er d'autres num≈ros d'identification d'ordinateurs\n
3 Impossibilit≈ de cr≈er d'autres num≈ros d'identification d'ordinateurs\n
4 Num≈ro d'identification d'ordinateur non d≈fini\n
5 Num≈ro d'identification d'ordinateur non d≈fini\n
6 Aucun h¬te nomm≈ "%s"\n
7 syntaxe du nom de r≈seau\n
8 Cr≈ation d'un nom de r≈seau erron≈\n
9 Code machine %c (0%o)\n
10 D≈sol≈.\n
11 Argument erron≈ dans l'option (optiboth)\n
12 ERREUR:  num≈ro d'identification de machine interne iconnu\n
$set 14
1 Vous avez reµu du courrier.\n
2 Du courrier est arriv≈.\n
3 %s contient encore 1 message\n
4 %s contient encore %2d messages\n
5 1 message sauvegard≈ dans %s\n
6 %d messages sauvegard≈s dans %s\n
7 Vous avez reµu du courrier.\n
8 %s contient encore 1 message\n
9 %s contient encore %d messages\n
$set 15
1 la tentative pour r≈parer la zone d'≈tat a ≈chou≈\n
2 Aucun destinataire sp≈cifi≈\n
3 Aucun message !?!\n
4 Indicateur de fin de fichier EOT\n
5 Aucun destinataire sp≈cifi≈\n
6 Aucun destinataire sp≈cifi≈\n
7 Pas de message, pas d'objet; esp≈rons que c'est voulu!\n
8 Corps du message nul; esp≈rons que c'est voulu!\n
9 . . . message perdu, d≈sol≈.\n
$set 16
1 Cha—ne trop longue
2 Plus de place pour l'espace %d\n
3 Erreur interne
$set 17
1 "%s" n'est pas un utilisateur de ce syst…me\n
2 ubluit
3 Identifiez-vous!\n
$set 18
1 trop long pour modifier\n
3 trop long pour modifier\n
$set 19
1 "%s": variable non d≈finie\n
2 M≈moire insuffisante
3 "%s": n'est pas un groupe\n
$set 20
1 rmmail: impossible de supprimer le lien (unlink) %s\n
2 rmmail: arguments non valides\n
3 rmmail: impossible d'acc≈der » %s\n
4 rmmail: %s n'est pas vide\n
5 rmmail: impossible de supprimer %s - autorisation refus≈e\n
6 rmmail: ≈tat erron≈\n
$set 21
1 %a %h %d %H:%M
