$set 1
1 Syntaxe: man [ section ] nom ...\n
2 ou: man -k mot cl≈ ...\n
3 ou: man -f fichier ...\n
4 Que recherchez-vous dans la section %s?\n
6 Aucune entr≈e man pour %s.\n
7 Aucun entr≈e associ≈e » %1$s dans la section %2$s du manuel.\n
9 Reformatage de l'entr≈e.  Veuillez patienter...
10  annul≈ (d≈sol≈)\n
11  termin≈\n
12 man: -k quoi?\n
13 %s: rien d'appropri≈\n
14 man: -f quoi?\n
15 %s: introuvable\n
$set 2
1 whereis [ -sbmu ] [ -SBM r≈pertoire... -f ] nom...\n
