$set 1
1 M≈moire insuffisante
2 L'≈tat du p≈riph≈rique doit ¡tre 'online' ou 'offline'
3 syntaxe: %s -c [-f] p≈riph_primaire ≈tat_prim p≈riph_secondaire ≈tat_second\n
4          %s -u p≈riph_mirroir ...\n
5          %s -o -p|-s p≈riph_mirroir ...\n
6          %s -r [-t] p≈riph_mirroir\n
7          %s -l [p≈riph ...]\n
8 Impossible de communiquer avec le gestionnaire
9 ‹criture mirroir non configur≈e dans le noyau
10 %s non valide
11 %s ne peut pas ¡tre doubl≈
12 %s ne peut pas ¡tre doubl≈
13 %s et %s ne peuvent pas ¡tre doubl≈s
14 %s fait d≈j» partie d'un disque mirroir
15 %s fait d≈j» partie d'un disque mirroir
16 Une section doit demeurer » l'≈tat ONLINE
17 %s est ouvert, son ≈tat doit donc ¡tre ONLINE
18 %s est ouvert, l'≈tat de %s doit donc ¡tre OFFLINE
19 %s ne doit pas ¡tre ouvert
20 Disque mirroir ouvert; l'≈tat de %s doit ¡tre ONLINE
21 R≈tablissement du disque mirroir en cours sur %s
22 Le fichier » l'≈tat Offline %s est ouvert
23 La table pour le r≈tablissement du disque mirroir est inexistante
24 Utilisez uxgen pour configurer root ou swap
25 %s n'est pas un disque mirroir
26 Indicateur ou ≈tat erron≈
27 Combinaison d'≈tats erron≈e
28 Un disque mirroir est d≈j» » l'≈tat OFFLINE
29 Impossible de trouver le d≈mon mirrorlog
30 Le r≈tablissement du disque mirroir a ≈chou≈
31 Une section doit ¡tre d≈finie » l'≈tat ONLINE
32 Trop de noms de p≈riph≈riques
33 Trop de noms de p≈riph≈riques
34 %s n'est pas un disque mirroir
35 Aucun disque mirroir » r≈tablir
36 La table pour le r≈tablissement du disque mirroir est inexistante
37 %s ne peut pas ¡tre doubl≈ \n
38 Seul le superutilisateur peut utiliser cette option
39 Impossible d'utiliser plock avec ce processus
