$set 1
1 Syntaxe: 
2  [-dfln] [+numligne | +/expression] nom1 nom2 ...\n
3 \n*** %s: r≈pertoire ***\n\n
4 \n******** %s n'est pas un fichier texte ********\n\n
6 [Entrez q or Q pour sortir]
7 --Encore--
8 (Fichier suivant: %s)
9 (%d%%)
10 [Barre d'espacement pour continuer, q pour quitter]
11 ...saut de %d lignes\n
12 ...saut de la ligne %d\n
13 \n***Vers l'arri…re***\n\n
14 Impossible d'ouvrir le fichier d'aide
15 "%s" ligne %d
16 [N'est pas un fichier] ligne %d
17 Expression standard incorrecte
18 ...saut\n
19 \nExpression introuvable\n
20 Expression introuvable
21 l'ex≈cution a ≈chou≈ (exec)\n
22 \n...Saut 
23 ...Saut 
24 au fichier 
25 retour au fichier 
26 Impossible de lire le fichier d'erreur standard (stderr).\n
27 Ligne trop longue
28 Aucune commande pr≈c≈dente » remplacer
99 \n*** %s: fichier fifo ***\n\n
