$set 1
1 Syntaxe: mv [-f] [-i] f1 f2\n\t mv [-f] [-i] f1 ... fn r1\n\t mv [-f] [-i] r1 r2\n
2 $s: Impossible de supprimer le lien
3 Acc…s impossible
4 %s et %s sont identiques
5 supprimer %s? 
6 annuler la protection %o%c pour %s? 
8 %s: type de fichier %o inconnu
9 %s: impossible de d≈placer une prise d'un syst…me de fichiers » un autre
10 %s: imposs d≈placer fich p≈riph r≈seau d'un syst de fichiers » un autre
11 Impossible de d≈placer une biblioth…que partag≈e "occup≈e"
12 impossible de d≈placer le fichier %s dans le r≈pertoire existant %s
13 impossible de d≈placer le r≈pertoire %s dans le fichier existant %s
14 impossible de d≈finir les heures de modification du fichier
15 impossible de d≈finir le propri≈taire ou le groupe du fichier
16 impossible de d≈finir les modes d'autorisation du fichier
17 impossible d'≈crire
18 impossible de cr≈er
19 impossible d'ouvrir
20 mv: %s/%s: Nom trop long.
21 impossible de fermer

