$set 1
1 l'expression convertie %.25s... est trop longue
2 espace insuffisant dans la table de consultation (lookup)
3 impossible d'ouvrir le fichier %s
4 trop de retours en arri…re (pushback)
5 la cha—ne entre guillemets %.20s est trop longue
6 " manquant dans %.20s
7 l'expression %.20s... est trop longue
8 Fin inattendue de l'entr≈e » %.20s
9 D≈finition non termin≈e » %.20s
10 espace insuffisant dans strsave sur %s
11 La pseudo-instruction include n'est pas encore en application
12 S≈parateurs erron≈s » %.20s
13 ex≈cution interrompue; erreur dans le pr≈-processeur eqn\n
14 ligne d'entr≈e trop longue: %.20s\n
15 plus de cha—ne dans le pr≈-processeur eqn
16 impossible d'ouvrir le fichier %s
17 erreur grave dans le pr≈-processeur eqn: 
18 \nfichier %1$s, entre les lignes %2$d et %d\n
19 eqn: 
20 erreur grave: 
21 \nfichier %1$s, entre les lignes %2$d et %d\n
23 type erron≈ %d dans expression erron≈e
24 \\e
