$set 1
1 "%s" n'est pas un langage de droite » gauche\n
2 fichier en mode droite » gauche avec justification » gauche\n
3 fichier en mode gauche » droite avec justification » droite\n
4 m≈moire insuffisante\n
5 d≈bordement du tampon d'entr≈e\n
6 d≈bordement du tampon de sortie\n
7 largeur ligne d'impression de "%s" exc…de la longueur du tampon d'entr≈e\n
8 "%s" largeur de la ligne d'impression non valide\n
9 la marge de bouclage de "%s" exc…de la longueur du tampon d'entr≈e\n
10 "%s" marge de bouclage non valide\n
11 marge de bouclage chang≈e » "%s" (ne peut exc≈der largeur ligne d'impress)\n
12 le taquet de tabulation de "%s" exc…de la longueur du tampon d'entr≈e\n
13 "%s" taquet de tabulation non valide\n
14 impossible d'ouvrir le fichier d'entr≈e "%s"\n
15 "%s" justification non valide (l ou r)\n
16 "%s" mode non valide (l ou n)\n
17 "%s" ordre non valide (k ou s)\n
18 syntaxe: nljust [-aclnt] [-e s≈q] [-j just] [-m mode] [-o ordre] [-r marge] [-w largeur] [-x ck] [fichiers ...]\n
