$set 1
1 erreur de lecture de la zone de donn≈es\n
2 fichier temporaire (tmp) comprim≈ introuvable\n
3 Occup≈.\n
4 Disponible.\n
5 Option inconnue: 
6 Exception de virgule flottante.\n
7  
8  
9 Impossible de cr≈er le fichier temporaire (temp).\n
10 Photocomposeuse occup≈e.\n
11 Fichier macro n'existe pas (
12 )
13 impossible d'ouvrir le fichier 
14 impossible d'ouvrir le fichier 
15 Trop de num≈ros de page\n
16 erreur d'≈criture dans le fichier temporaire (tmp)\n
17 impossible de cr≈er fichier de donn≈es\n
18 impossible de cr≈er fichier temporaire (tmp)\n
19 Tassement termin≈\n
20 Trop de macros.\n
21 Impossible d'ouvrir la table de c≈sures des suffixes (suftab).\n
22 Impossible de d≈finir environnement pour ex≈cution commande (env)\n
23 Impossible d'ex≈cuter 
24 Type de terminal inexistant\n
25 erreur dans la sp≈cification du terminal
26 Attente de la photocomposeuse.\n
27 Le programme troff a ≈t≈ ex≈cut≈.\n
28 Conduit non cr≈≈.\n
29 Ex≈cution (exec) impossible: 
30 trop de noms associ≈ » rn
31 Trop de noms de cha—nes/macros.\n
32 m≈moire insuffisante pour stockage
33 Espace insuffisant pour les fichiers temporaires.\n
34 La lecture de la macro a ≈chou≈\n
35 Affectation erron≈e de la m≈moire\n
36 trop d'appels de macros
37 m≈moire insuffisante pour l'appel de macro
38 Limite du noyau atteinte.\n
39 m≈moire insuffisante pour l'appel de macro
40 Argument de macro trop long.\n
41 d≈routement impossible.\n
42 Trop de registres num≈riques.\n
43 Division par z≈ro.\n
44 Impossible d'installer un pi…ge.\n
45 Abandon de l'utilisateur.
46 Impossible d'ex≈cuter l'≈v≈nement (ev_)\n
47 d≈bordement de l'instruction if-else.\n
48 :
49 D≈bordement de ligne.\n
50 Pi…ge erron≈.\n
51 D≈bordement du mot.\n
52 La liste des exceptions est pleine.\n
53 zone de longueur z≈ro.\n
54 Trop de caract…res superpos≈s.\n
