$set 1
1 %s: Erreur de lecture du fichier %s\n
2 %s: Les formes anciennes et nouvelles ne peuvent ¡tre combin≈es\n
3 %s: Argument non valide pour l'option -A\n
4 %s: Valeur non valide pour l'option -j\n
5 %s: Valeur non valide pour l'option -N\n
6 Syntaxe: %s [-v] [-A base] [-j saut] [-N num] [-t type_cha—ne]... [fichier...]\n 
7 %s: Fin de fichier atteinte pour l'entr≈e: %s\n
8 %s: Argument non valide pour l'option -t\n
9 %s: Modificateur num≈rique non valide\n
10 %s: Modificateur de type non valide \n
11 %s: impossible d'ouvrir %s\n
