$set 1
1 Syntaxe: passwd [ nom_utilisateur ]\n
2 Changement de mot de passe pour %s\n
3 Autorisation refus≈e.\n
4 Ancien mot de passe: 
5 D≈sol≈.\n
6 D≈sol≈: < %ld semaines depuis le dernier changement\n
7 Vous ne pouvez pas changer ce mot de passe.\n
8 Trop d'essais infructueux; essayez plus tard.\n
9 Nouveau mot de passe: 
10 Mot de passe trop court : minimum 6 caract…res\n
11 Mot de passe ne peut ¡tre une r≈p≈tition du nom d'ouverture\n
12 Mot de passe doit comprendre au moins deux lettres et\n
13 au moins un chiffre ou un caract…re sp≈cial.\n
14 Les mots de passe doivent diff≈rer d'au moins 3 caract…res\n
15 Entrez le mot de passe de nouveau:
16 Trop d'essais infructueux; esssayez plus tard.\n
17 Les mots de passe ne correspondent pas; essayez de nouveau.\n
18 Fichier temporaire occup≈; esssayez plus tard.\n
19 Impossible de cr≈er fichier temporaire\n
20 Autorisation refus≈e.\n
21 impossible de supprimer le lien %s\n
22 impossible de cr≈er le lien entre %s et %s\n
23 impossible de supprimer le lien %s\n
24 impossible de cr≈er le lien entre %s et %s\n
25 impossible de r≈cup≈rer %s\n
26 impossible de supprimer le lien %s\n
27 ≈criture de l'entr≈e dans fichier mot de passe a ≈chou≈ (putpwent) ()\n
28 changement de propri≈taire impossible (chown) dans %s\n
29 Changement de mode impossible (chmod) pour %s\n
30 Nom d'ouverture de session non valide.\n
31 Mot de passe trop long\n
