$set 1
1 Erreur 0
2 N'est pas le propri≈taire
3 Fichier ou r≈pertoire inexistant
4 Processus inexistant
5 Appel syst…me interrompu
6 Erreur d'E-S
7 P≈riph≈rique ou adresse inexistante
8 Liste d'arguments trop longue
9 Erreur dans le format de la commande exec
10 Num≈ro de fichier erron≈
11 Aucun processus enfant
12 Plus de processus
13 Espace insuffisant
14 Autorisation refus≈e
15 Adresse erron≈e
16 P≈riph≈rique en mode bloc requis
17 P≈riph≈rique occup≈
18 Fichier existant
19 Lien entre deux p≈riph≈riques
20 P≈riph≈rique inexistant
21 N'est pas un r≈pertoire
22 Est un r≈pertoire
23 Argument non valide
24 D≈bordement de la table de fichier
25 Trop de fichiers ouverts
26 N'est pas une machine » ≈crire
27 Fichier texte occup≈
28 Fichier trop grand
29 Plus d'espace dans le p≈riph≈rique
30 Recherche non valide
31 Syst…me de fichiers accessible en lecture seulement
32 Trop de liens
33 Conduit interrompu
34 Argument hors domaine
35 R≈sultat trop grand
36 Aucun message du type d≈sir≈
37 Identificateur supprim≈
38 Erreur inconnue
39 Erreur inconnue
40 Erreur inconnue
41 Erreur inconnue
42 Erreur inconnue
43 Erreur inconnue
44 Erreur inconnue
45 Erreur inconnue
46 Fichier verrouill≈ d≈tection d'impasse
47 Aucun verrou disponible
48 Erreur inconnue
49 Erreur inconnue
50 Erreur inconnue
51 N'est pas un flot de donn≈es
52 Aucune donn≈e
53 Retard du flot de donn≈es dans la commande ioctl
54 Aucune ressource du flot de donn≈es
55 Pas dans le r≈seau
56 Produit non install≈
57 Erreur inconnue
58 Lien coup≈
59 Erreur de diffusion
60 Erreur Srmount
61 Erreur d'envoi
62 Erreur de protocole
63 Erreur inconnue
64 Erreur inconnue
65 Essai de transmissions multiples vers un noeud
66 Erreur inconnue
67 Point de montage rencontr≈
68 Message erron≈
70 Limites du disque d≈pass≈es
71 Indicateur de fichier NFS p≈rim≈
72 Trop de niveaux ≈loign≈s dans le chemin
73 Erreur inconnue
74 Erreur inconnue
75 Erreur inconnue
76 Erreur inconnue
77 Erreur inconnue
78 Erreur inconnue
79 Erreur inconnue
80 Erreur inconnue
81 Erreur inconnue
82 Erreur inconnue
83 Erreur inconnue
84 Erreur inconnue
85 Erreur inconnue
86 Erreur inconnue
87 Erreur inconnue
88 Erreur inconnue
89 Erreur inconnue
90 Erreur inconnue
91 Erreur inconnue
92 Erreur inconnue
93 Erreur inconnue
94 Erreur inconnue
95 Erreur inconnue
96 Erreur inconnue
97 Erreur inconnue
98 Erreur inconnue
99 Erreur inconnue
100 Erreur inattendue
101 Erreur inconnue
102 Erreur inconnue
103 Erreur inconnue
104 Erreur inconnue
105 Erreur inconnue
106 Erreur inconnue
107 Erreur inconnue
108 Erreur inconnue
109 Erreur inconnue
110 Erreur inconnue
111 Erreur inconnue
112 Erreur inconnue
113 Erreur inconnue
114 Erreur inconnue
115 Erreur inconnue
116 Erreur inconnue
117 Erreur inconnue
118 Erreur inconnue
119 Erreur inconnue
120 Erreur inconnue
121 Erreur inconnue
122 Erreur inconnue
123 Erreur inconnue
127 Erreur inconnue
128 Erreur inconnue
129 Erreur inconnue
130 Erreur inconnue
131 Erreur inconnue
132 Erreur inconnue
133 Erreur inconnue
134 Chemin ≈loign≈
135 Op≈ration termin≈e dans le serveur
136 Erreur inconnue
137 Erreur inconnue
138 Erreur inconnue
139 Erreur inconnue
140 Erreur inconnue
141 Erreur inconnue
142 Erreur inconnue
143 Erreur inconnue
144 Erreur inconnue
145 Erreur inconnue
146 Erreur inconnue
147 Erreur inconnue
148 Erreur inconnue
149 Erreur inconnue
150 Erreur inconnue
151 Erreur inconnue
152 Erreur inconnue
153 Erreur inconnue
154 Erreur inconnue
155 Erreur inconnue
156 Erreur inconnue
157 Erreur inconnue
158 Erreur inconnue
159 Erreur inconnue
160 Erreur inconnue
161 Erreur inconnue
162 Erreur inconnue
163 Erreur inconnue
164 Erreur inconnue
165 Erreur inconnue
166 Erreur inconnue
167 Erreur inconnue
168 Erreur inconnue
169 Erreur inconnue
170 Erreur inconnue
171 Erreur inconnue
172 Erreur inconnue
173 Erreur inconnue
174 Erreur inconnue
175 Erreur inconnue
176 Erreur inconnue
177 Erreur inconnue
178 Erreur inconnue
179 Erreur inconnue
180 Erreur inconnue
181 Erreur inconnue
182 Erreur inconnue
183 Erreur inconnue
184 Erreur inconnue
185 Erreur inconnue
186 Erreur inconnue
187 Erreur inconnue
188 Erreur inconnue
189 Erreur inconnue
190 Erreur inconnue
191 Erreur inconnue
192 Erreur inconnue
193 Erreur inconnue
194 Erreur inconnue
195 Erreur inconnue
196 Erreur inconnue
197 Erreur inconnue
198 Erreur inconnue
199 Erreur inconnue
200 Erreur inconnue
201 Erreur inconnue
202 Erreur inconnue
203 Erreur inconnue
204 Erreur inconnue
205 Erreur inconnue
206 Erreur inconnue
207 Erreur inconnue
208 Erreur inconnue
209 Erreur inconnue
210 Erreur inconnue
211 Erreur inconnue
212 Erreur inconnue
213 Erreur inconnue
214 Erreur inconnue
215 Erreur inconnue
216 Appel non r≈solu
217 Op≈ration de prise ou n'est pas une prise
218 Adresse de destination requise
219 Message trop long
220 Type de protocole erron≈ pour la prise
221 Protocole non disponible
222 Ce protocole n'est pas pris en charge
223 Ce type de prise n'est pas pris en charge
224 Cette op≈ration n'est pas prise en charge
225 Cette famille de protocoles n'est pas prise en charge
226 Famille d'adresses non prise en charge par famille de protocoles
227 Adresse d≈j» utilis≈e
228 Impossible d'attribuer l'adresse demand≈e
229 R≈seau arr¡t≈
230 Impossible d'acc≈der au r≈seau
231 Connexion abandonn≈e par r≈seau » la r≈initialisation
232 Logiciel responsable de l'abandon de la connexion
233 Connexion r≈initialis≈e par un pair
234 Espace tampon non disponible
235 Prise d≈j» connect≈e
236 Prise non connect≈e
237 Impossible d'envoyer apr…s l'arr¡t de la prise
238 Trop de r≈f≈rences : impossible de raccorder
239 D≈passement du d≈lai de connexion
240 Connexion refus≈e
241 Abandon de la connexion par le pair ≈loign≈
242 H¬te arr¡t≈
243 Aucune route vers l'h¬te
244 Erreur inconnue
245 Op≈ration d≈j» en cours
246 Op≈ration maintenant en cours
247 Op≈ration cr≈erait un regroupement
248 Ce r≈pertoire n'est pas vide
249 Nom de fichier trop long
250 Trop de niveaux de liens symboliques
251 Aucun message du type voulu
252 Cette fonction n'est pas disponible
253 Erreur inconnue
