$set 1
1 Syntaxe: pg [-nombre] [-p cha—ne] [-cefns] [+ligne] [+/expression/] fichiers\n
4 pg: expression trop longue\n
5 pg: invite trop longue\n
6 ...saut vers l'arri…re\n
7 ...saut vers l'avant\n
8 (Fin de fichier)
9 impossible d'ouvrir fichier de sauvegarde
10 sauvegarde du fichier
11 sauvegard≈
12 duplication impossible (fork), essayez plus tard
13 l'ex≈cution a ≈chou≈\n
14    h               aide\n
15    q ou Q          sortie\n
16    <vide> ou \\n    page suivante\n
17    l               ligne suivante\n
18    d ou ^D         affiche une autre demi-page\n
19    . ou ^L         r≈affiche la page courante\n
20    f               saute la page suivante\n
21    n               fichier suivant\n
22    p               fichier pr≈c≈dent\n
23    $               derni…re page\n
24    w ou z          d≈finit la taille de fen¡tre et affiche page suivante\n
25    s fichsauv      sauvegarde le fichier en cours dans fichsauv\n
26    /expression/    recherche l'expression vers l'avant\n
27    ?expression? ou\n
28    ^expression^    recherche l'expression vers l'arri…re\n
29    !commande       ex≈cute la commande\n
30 La plupart des commandes peuvent ¡tre pr≈c≈d≈es d'un nombre, comme dans:\n
31 +1\\n (page suivante); -1\\n (page pr≈c≈dente); 1\\n (page 1).\n
32 Pour plus de d≈tails, reportez-vous » la page de manuel.\n
33 Il n'y a pas de fichier pr≈c≈dent
34 Il n'y a pas de fichier suivant
35 pg: %s est un r≈pertoire\n
36 pg: fichiers sp≈ciaux trait≈s comme entr≈e standard seulement\n
37 pg: Impossible de cr≈er fichier temporaire (temp)\n
38 pg: Impossible d'acc≈der au fichier temporaire (temp) en ≈criture\n
39 pg: Impossible d'acc≈der au fichier temporaire (temp) en lecture\n
40 Expression introuvable
41 Point de terminaison de la plage trop grand
42 Nombre erron≈
43 `\\chiffre' hors plage
44 S≈parateur non valide ou manquant
45 Aucune cha—ne de recherche n'a ≈t≈ utilis≈e auparavant
46 \\( \\) manquantes
47 Trop de \\(
48 Plus de deux nombres dans les \\{ \\}
49 } obligatoire apr…s \\
50 Le premier nombre d≈passe le deuxi…me dans \\{ \\}
51 [] manquants
52 D≈bordement de l'expression standard
53 Expression standard erron≈e
54 L'entr≈e du conduit n'a ≈t≈ que partiellement sauvegard≈e
55 pg: m≈moire insuffisante: ligne %d\n
56 pg: impossible de rouvrir la sortie standard (stdout)\n
57 pg: impossible de trouver le type de terminal\n
58 (Fichier suivant:
