$set 1
1 \n%s: V≈rification des biblioth…ques partag≈es\n
2 
3 ERREUR\n\n
4 Une ou plusieurs biblioth…ques partag≈es importantes sont introuvables.\nLa reprise des biblioth…ques partag≈es exige un support de mise » jour et\nun p≈riph≈rique pouvant lire le support. Si vous d≈sirez\nr≈cup≈rer ces biblioth…ques partag≈es, ce programme vous aidera » le faire.\n\nD≈sirez-vous continuer (oui/non)? 
5 Vous ¡tes dans /bin/sh. Lorsque vous sortez,\nle syst…me continuera » s'initialiser.\n\nPour revenir » ce programme, entrez /etc/recoversl\n
6 Type du support de mise » jour:\n1. Cartouche, Bande » neuf pistes ou bande audionum≈rique (DAT)\n2. CD-ROM\n\nVeuillez choisir 1 ou 2: 
7 Si vous poss≈dez plusieurs bandes de mise » jour, utilisez la premi…re.\nChargez-la et appuyez sur <retour>\n
8 La reprise a ≈chou≈. Faites les v≈rifications suivantes:\n - Bande ad≈quate\n - D≈rouleur de bande pr¡t\n - Bande charg≈e, en ligne\n - Fichier de p≈riph≈riques correct\n
9 \nLa reprise a r≈ussi. Le syst…me va maintenant s'initialiser\n
10 Si vous poss≈dez plusieurs disques de mise » jour, utilisez le premier.\n\nIns≈rez-le et appuyez sur <retour>\n
11 ‹chec montage syst…me fichiers CD-ROM. Faites les v≈rifications suivantes:\n - Unit≈ de disque pr¡te\n - Disque ins≈r≈\n - Fichier de p≈riph≈riques correct\n
12 %d erreurs pendant la reprise. Faites les v≈rifications suivantes:\n - CD-ROM correct\n
13 \nReprise r≈ussie. Il est conseill≈ de r≈initialiser le syst…me maintenant\n
14 \nUn fichier de p≈riph≈riques est exig≈ pour le %s.\nSi ce fichier n'existe pas, il sera cr≈≈.\n\nEst-ce qu'un fichier de p≈riph≈riques appropri≈ existe d≈j»\ndans ce syst…me (oui/non/sortie)? 
15 Entrez le chemin complet du fichier de p≈riph≈riques: 
16 Entrez le majeur et le mineur\ndu fichier de p≈riph≈riques en mode bloc: 
17 fichier de p≈riph≈riques: %s
18 : n'est pas un fichier de p≈riph≈riques en mode bloc\n
19 : n'est pas un fichier de p≈riph≈riques en mode caract…re\n
20 \nEst-ce correct (oui/non/sortie)? 
21 r≈initialisation du syst…me...\n
22 \tautorisations fixes sur %s\n
23 o
24 n
25 s
26 Vous devez ¡tre superutilisateur pour utiliser ce programme\n
27 bande
28 CD-ROM
29 Entrez le majeur et le mineur\ndu fichier de p≈riph≈riques en mode caract…re: 
30 tar introuvable dans /bin et /usr/bin!\n
