$set 1
1 Erreur inconnue
2 Expression standard non valide
3 
4 
5 
6 
7 
8 
9 
10 
11 nombre non valide dans la d≈finition \\{ \\}
12 
13 
14 
15 
16 nombre trop ≈lev≈ dans la d≈finition \\{ \\}
17 
18 
19 
20 regexec() a ≈chou≈ dans la v≈rification
21 ordre de classement de l'≈l≈ment de r≈f≈rence non valide
22 \\ en-queue dans l'expression
23 caract…re de fin non valide dans l'instruction de plage
24 type de classe de caract…res de r≈f≈rence non valide
25 nombre dans \\digits non valide ou erron≈
26 ?, * ou + non pr≈c≈d≈ d'une expression standard valide
27 pas d'expression entre les ( ) ou d'un c¬t≈ d'un |
28 
29 
30 
31 
32 
33 
34 
35 
36 \\n trouv≈s avant la fin de l'expression et descripteur REG_NEWLINE non d≈fini
37 
38 
39 
40 
41 aucune cha—ne de recherche retenue
42 \\( \\) ou ( ) manquant
43 plus de neuf paires de \\( \\) ou niveau d'imbrication trop complexe
44 plus de deux nombres dans la d≈finition \\{ \\}
45 \\( \\) manquant
46 le premier nombre exc…de le deuxi…me dans la d≈finition \\{ \\}
47 
48 
49 [ ] manquant
50 m≈moire insuffisante
51 m≈moire insuffisante pendant la v≈rification de l'expression
