$set 1
1 Syntaxe: rm [-Rfir] fichier ...\n
2 %s: impossible de supprimer.\n
3 rm: %s n'existe pas\n
4 r≈pertoire %s: ? 
5 rm: lecture impossible 
6 rm: %s est un r≈pertoire\n
7 %s: mode %o ? 
8 rm: %s n'a pas ≈t≈ supprim≈.   
10 rm: %s: Nom trop long\n
11 rm: %s/%s: Nom trop long\n
12 rm: le r≈pertoire %s n'a pas ≈t≈ supprim≈.
13 Impossible de supprimer un r≈pertoire mont≈\n
14 R≈pertoire qui n'est pas vide\n
15 Impossible de supprimer le r≈pertoire en cours\n
16 Nom de r≈pertoire trop long\n
17 Syntaxe: rmdir [-fip] nomr≈p ...\n
18 rmdir: %s: 
19 rmdir: %s: %s n'a pas ≈t≈ supprim≈;  
20 rmdir: %s: chemin complet supprim≈.\n
21 rm: acc…s impossible 
22 rmdir: %s: %s n'a pas ≈t≈ supprim≈\n
