$set 1
1 r≈pertoire `%1$s' pr≈cis≈ comme valeur de lettre cl≈ `%2$c'
2 d n'a pas d'argument
3 valeur apr…s l'indicateur %c
5 format de liste erron≈
6 ≈l≈ment de la liste hors plage
7 indicateur inconnu
8 un indicateur appara—t deux fois
9 f n'a pas d'argument
10 il y a une valeur apr…s l'indicateur %c
11 Pas d'application avec indicateur d'application.
12 Aucun fichier .FRED n'existe pour cette application.
13 la version inf≈rieure n'est pas num≈rique
14 version inf≈rieure hors plage
15 la version sup≈rieure n'est pas num≈rique
16 version sup≈rieure hors plage
17 pas de sid (ID SCCS) par d≈faut
18 aucune valeur n'est associ≈e » l'indicateur %c
19 format de liste erron≈
20 ≈l≈ment de la liste hors plage
21 indicateur inconnu
22 un indicateur appara—t deux fois
23 r hors plage
24 argument a erron≈
25 trop de lettres cl≈s 'a'
26 argument e erron≈
27 trop de lettres cl≈s 'e'
28 lettre cl≈ inconnue
29 une lettre cl≈ appara—t deux fois
30 argument de fichier manquant
31 utilisation non valide de la lettre cl≈ 'y' ou 'm'
32 plus d'un fichier
33 ID utilisateur ne se trouve pas dans le fichier mot de passe
34 r≈pertoire nomm≈ avec la lettre cl≈ `i'
35 Impossible d'avoir deux sous-programmes de v≈rification.
36 MRs not allowed
37 MRs required
38 r permis avec i seulement
39 t n'a pas d'argument
40 d n'est pas permis avec n
41 fichier %s existe
42 fichier %s n'existe pas
43 impossible de dupliquer (fork), essayez de nouveau
44 impossible d'ex≈cuter '%s'
45 fichier alt≈r≈
46 impossible de cr≈er un fichier verrouill≈
47 nom de fichier trop long
48 Bad CMR number(s).
49 invalid MRs
50 Impossible d'utiliser -fz avec -fv.
51 aucun mot cl≈ d'identification
52 mots cl≈s d'identification non valides
53 Aucun mot cl≈ d'identification
54 %1$s donn≈es non valides sur la ligne %2$d
55 date et heure cr≈≈s
56 par
212 n'est pas un fichier SCCS
$set 2
1 lettre cl≈ inconnue
2 valeur apr…s l'argument %c
3 une lettre cl≈ appara—t deux fois
4 argument de fichier manquant
5 impossible d'avoir -p et -c
6 p-file existe
7 sid (ID SCCS) n'existe pas
8 rien » faire
9 impossible de cr≈er s.file temporaire:
10 impossible de cr≈er fichier temporaire
11 s.file temporaire: %s n'existe pas??
$set 3
1 lettre cl≈ inconnue
2 valeur apr…s l'argument %c
3 une lettre cl≈ appara—t deux fois
4 argument de fichier manquant
5 impossible de cr≈er un fichier verrouill≈
6 sid (ID SCCS) non valide dans p-file
7 aucun mot cl≈ d'identification
8 mots cl≈s d'identification non valides
9 Aucun mot cl≈ d'identification
12 impossible d'ex≈cuter '%s'
13 ≈chec de '%1$s', nouvel essai, segmentation = %2$d
14 ≈chec de diff
15 %u ins≈r≈
16 %u supprim≈
17 %u inchang≈
18 MRs not allowed
19 invalid MRs
20 MRs required
21 input CMR's ignored
22 Delta denied due to CMR difficulties
23 DELTA NUL AUTOMATIQUE
24 valeur de la lettre-cl≈ `r' ambiguÕ
25 argument -r manquant
26 nom d'ouverture de session ou SID pr≈cis≈ ne se trouve pas dans p-file
29 impossible de dupliquer (fork), essayez de nouveau
33 erreur interne dans delta/enter()
34 erreur interne dans delta/enter()
35 erreur interne dans delta/enter()
351 fputs n'a pu ≈crire dans le fichier
$set 4
1 CMR list is too long.
2 r hors plage
3 date/heure erron≈e
4 lettre cl≈ inconnue
5 valeur apr…s l'argument %c
6 une lettre cl≈ appara—t deux fois
7 argument de fichier manquant
8 e non admis avec m
9 ID utilisateur ne se trouve pas dans le fichier mot de passe
10 impossible de cr≈er un fichier verrouill≈
11 num≈ro d'ordre trop grand
12 fichier `%s' existe d≈j» en autorisation d'≈criture
13 %u lignes
14 aucun mot cl≈ d'identification
15 mots cl≈s d'identification non valides
16 Aucun mot cl≈ d'identification
17 SID (ID SCCS) erron≈ calcul≈ dans newsid()
18 %s est d≈j» inclus
19 %s est d≈j» exclus
20 erreur interne dans get/enter()
21 ≈chec de getcwd
22 impossible de changer de r≈pertoire
26 en cours d'≈dition: `%s'
27 nouveau delta
28 sid (ID SCCS) n'existe pas
29 Background CASSI get with no CMRs
30 Background CASSI get with invalid CMR
31 Input Comma Separated List of CMRs:
32 ?Too many CMRs.
33 Must enter at least one valid CMR.
34 Re-enter invalid CMRs, or press return.
101 %y/%m/%d
102 %m/%d/%y
103 %H:%M:%S
104 %y/%m/%d
105 %m/%d/%y
106 %H:%M:%S
351 fputs n'a pu ≈crire dans le fichier
$set 5
1 aide: Impossible d'ex≈cuter: %1$s.  Num≈ro d'erreur=%2$d
$set 6
1 sid (ID SCCS) non valide
2 troncature de date non valide
3 valeur apr…s l'argument %c
4 lettre cl≈ inconnue
5 lettre cl≈ appara—t deux fois
6 argument de fichier manquant
7 impossible de pr≈ciser la troncature de date et le SID (ID SCCS)
8 -e ou -l obligatoire avec -c
9 oui
10 non
11 aucun
27 ≈chec de getcwd
28 impossible de changer de r≈pertoire
29 ≈chec de getcwd
30 impossible de changer de r≈pertoire
31 le SID (ID SCCS) n'existe pas
32 fin de fichier pr≈matur≈e
33 impossible de dupliquer (fork), essayez de nouveau
34 impossible d'ex≈cuter '%s'
35 (aucun)
36 branche
37 version sup≈rieure\t%s
38 SID (ID SCCS) par d≈faut\t%s
39 version inf≈rieure\t%s
40 erreur dans le mot cl≈ d'identification/avertissement\t%s
41 modifications simultan≈es
42 versions verrouill≈es\t%s
43 module\t%s
44 delta nul
45 nom csect\t%s
46 type\t%s
47 validate MRs\t
$set 7
1 r n'a pas de sid (ID SCCS)
2 lettre cl≈ inconnue
3 une lettre cl≈ appara—t deux fois
4 Cassi not compatible with cmrs on command line
5 argument de fichier manquant
6 appel erron≈
7 ID utilisateur ne se trouve pas dans le fichier mot de passe
8 r manquant
9 fichier %s n'existe pas
10 impossible de verrouiller le fichier
11 ce sid (ID SCCS) n'existe pas
12 vous n'¡tes pas propri≈taire ni '%s'
13 n'est pas un delta 'feuille'
14 MRs not allowed
15 invalid MRs
16 invalid use of 'z' flag \n CASSI incompatablity
17 uneditable cmr for CASSI controlled file- Change not allowed
18 bad cdc replace of cmr's (CASSI)
19 delta specified has delivered MR
20 *** CHANGED *** 
21 only one cmr left for this delta no change possible
22 d≈sirez-vous supprimer %s
24 %s  ne peut ¡tre ≈dit≈ maintenant
25 Aucun fichier fred trouv≈; voyez l'administrateur du sccs
26  %s ne peut ¡tre ≈dit≈
27 CASSI msg not writable
28 %1$s chpost %2$s q %3$s sw MID=%4$s MFS=%5$s MPA=%6$s q q
29 Cassi BD/source not writeable
30 en cours d'≈dition -- sid (ID SCCS) dans p-file
31 *** LIST OF DELETED MRS ***
$set 8
1 lettre cl≈ inconnue
2 valeur apr…s l'argument %c
3 une lettre cl≈ appara—t deux fois
4 argument de fichier manquant
5 impossible de cr≈er un fichier verrouill≈
6 impossible de dupliquer (fork), essayez de nouveau
7 SID (ID SCCS) doit ¡tre pr≈cis≈
8 nom d'ouverture de session n'est pas dans p-file
9 le SID (ID SCCS) pr≈cis≈ ne se trouve pas dans p-file
10 Aucun delta particulier pour: %s
$set 9
1     %1$s: %2$cM%3$c, non concordant -m
2     %1$s: %2$cY%3$c, non concordant -y
3     %s: SID (ID SCCS) n'existe pas
4     %s: SID (ID SCCS) non valide ou ambigu
5     %s: impossible d'ouvrir le fichier ou n'est pas un fichier SCCS
6     %s: fichier SCCS alt≈r≈\n
7     %s: argument lettre cl≈ inconnu ou dupliqu≈
8     %s: argument de fichier manquant
11 attendu
12 ou
13 date de cr≈ation du delta hors s≈quence ou » venir
14 ligne de contr¬le non valide
15 fin de fichier inattendue
16 erreur du total de contr¬le (checksum)
$set 10
1 commande inconnue sur la ligne %d
2 `%s' jamais utilis≈
3 `%s' ne fait partie d'aucune d≈claration
4 n'a jamais attribu≈ de valeur `%s'
5 instruction `if' sans instruction `end' correspondante
6 syntaxe sur la ligne %d
7 `%1$s' fait partie de deux d≈clarations sur la ligne %2$d
8 ERREUR:%s
9 erreur dans l'instruction sur la ligne %d
10 instruction `end' sans instruction `if' correspondant sur la ligne %d
11 Message(%1$d):%2$s
13 syntaxe sur la ligne %d
14 erreur de parenth…se sur la ligne %d
15 op≈rateur non valide sur la ligne %d
16 valeur non num≈rique sur la ligne %d
17 espace insuffisant [ligne %d]
18 `%1$c' sans correspondance sur la ligne %2$d
19 nom de mot cl≈ non valide sur la ligne %d
20 espace insuffisant
21 nom du mot cl≈ trop long sur la ligne %d
22 syntaxe sur la ligne %d
23 `%1$c%2$c' sans correspondance sur la ligne %3$d
$set 11
1 impossible d'ouvrir %s
$set 12
11 Pfile n'existe pas dans la v≈rification de delta 
12 aucune application rep≈r≈e avec l'indicateur -fz
13 aucun fichier FRED ou nom syst…me dans le r≈pertoire admin 
15 ***CASSI REPORTS ERROR: no CMRS in pfile: %s
16 CMRs not on P.file -serious inconsistancy
17 ***CASSI REPORTS ERROR: no CMRS at sd
18 no CMR's left, delta forbidden
19 the CMRs for this delta now are:
20 OK ??
24 you must input a least 1 valid cmr number
25 enter new CMR number or 'CR' 
26  \n duplicate CMR number ignored
27  \n invalid CMR ignored 
28  \n to many CMRs added no more allowed 
29  \n CMR number to delete or (CR) ? 
30 \n only one CMR left can't delete more
31 \n pas dans la liste, demande non prise en compte
32 ***CASSI REPORTS ERROR: can't write to FRED : %s
33  Cassi Interface Msg not writable
34 %1$s chpost %2$s q %3$s %4$s MID=%5$s MFS=%6$s MPA=%7$s q q
35 ***CASSI REPORTS ERROR: can't write to BD/source : %s
36 Cassi BD/source not writeable
37 rendu au fichier FRED erron≈ %s
101 sid (ID SCCS) non valide
111 r≈glage de l'horloge erron≈!!!
112 L'horloge est peut-¡tre mal r≈gl≈e!
121 MRs? 
122 commentaires? 
123 entr≈e standard pr≈cis≈e w/o -y et/ou -m lettre cl≈
124 ligne trop longue
125 r≈ponse trop longue
126 impossible de dupliquer (fork), essayez de nouveau
127 too many MRs
128 MR number too long
129 MR number too long
130 espace insuffisant
141 Inclus:
142 Exclus:
151 plage erron≈e
152 syntaxe de la liste de deltas
161 erreur de format » la ligne %u
171 fin de fichier (EOF) pr≈matur≈e
172 fichier alt≈r≈
181 non autoris≈ » cr≈er des deltas
182 version %1$u < %2$u (inf≈rieure)
183 version %1$u > %2$u (sup≈rieure)
184 fichier SCCS verrouill≈; modification impossible
185 version `%d' verrouill≈e; modification impossible
191 format de p-file erron≈
204 fin de fichier (EOF) pr≈matur≈e
211 trop long
212 n'est pas un fichier SCCS
213 plus d'un lien
221 ce fichier comporte plus de 99999 lignes
321 ESPACE INSUFFISANT
324 ffree: le pointeur ne pointe pas » la zone allou≈e
331 r≈pertoire `%s' n'existe pas
341 pas de fichier
342 `%s' n'existe pas
343 impossible d'≈crire dans le r≈pertoire `%s'
344 pas d'espace!
345 erreur d'≈criture
346 num≈ro d'erreur = %1$d, fonction = `%2$s'
$set 13
2 Il n'y a aucune aide disponible sur le sujet %s\n
3 Il n'y a aucune aide disponible sur le sujet %s\n
4 Quel est le num≈ro du message ou le nom de la commande SCCS? 
