$set 1
1 %s: "%s": Param…tre non valide.\n
2 %s: Langue %s inconnue. Utilisation de la langue par d≈faut.\n
3 %s: Autorisation refus≈e. N'est pas superutilisateur.\n
4 %s: Attention: aucune op≈ration ex≈cut≈e.\n
5 %s: Impossible d'ouvrir le p≈riph≈rique %s.\n
6 %s: N'est pas un p≈riph≈rique en mode caract…re %s.\n
7 %s: N'est pas un p≈riph≈rique SCSI %s.\n
8 %s: Argument de p≈riph≈rique non valide %s.\n
9 d≈finir immediate_report
10 obtenir immediate_report
11 %s: P≈riph≈rique magn≈to-optique %s non valide pour effacement.\n
12 %s: P≈riph≈rique de la section-2 %s non valide pour effacement.\n
13 effacement
14 Syntaxe: %s [-akq] [-m mode[=valeur]]... [-c commande]... p≈riph≈rique\n
$
$ L10N note:  The following 2 messages are used together.  The entire error
$             message should look somthing like this:
$
$                    scsictl: Device ioctl ("msg") error
$
$             where "msg" would be a localized message.
$             Do not localize "ioctl" since it is a Unix terminlolgy.
15 : Erreur ioctl (
16 ) sur p≈riph≈rique
