$set 1
1 un/used/avail 
101 nouvelle ligne ou ;
201 reµu signal #%d\n
203 Incident au niveau de la m≈moire dans le shell: ≈limination des erreurs.
204 impossible d'ex≈cuter la commande (trap) pour l'≈v≈nement num≈ro 11
205 impossible d'ex≈cuter la commande (trap) pour l'≈v≈nement num≈ro 18
301 suppression du lien 
401 hits\tcost\tcommand\n
402  est une commande interne du shell \n
403  est une fonction\n
404  introuvable\n
405  est index≈ (
406  est une commande interne du shell \n
407  est 
601 option(s) erron≈e(s)
602 vous avez du courrier\n
603 pas d'espace
604 pas d'espace dans la pile
605 erreur de syntaxe
606 signal inconnu
607 num≈ro erron≈
608 param…tre nul ou non d≈fini
609 param…tre non d≈fini
610 substitution erron≈e
611 cr≈ation impossible
612 ≈chec de la duplication (fork) - trop de processus
613 duplication impossible (fork): manque d'espace de permutation
614 acc…s restreint
615 impossible de cr≈er le conduit
616 impossible d'ouvrir
617  - noyau vid≈
618 liste d'arguments trop longue
619 texte occup≈
620 trop gros
621 impossible d'ex≈cuter
622 introuvable
623 num≈ro de fichier erron≈
624 impossible de d≈caler
625 r≈pertoire erron≈
626 pi…ge (trap) erron≈
627 est accessible en lecture seulement
628 n'est pas un identificateur
629 Limite (ulimit) erron≈e
630 imp arr¡ter ex≈cution (return) si instruction n'est pas dans fonction
631 impossible d'exporter des fonctions (export)
632 impossible de supprimer (unset)
633 pas de r≈pertoire initial
634 autorisation d'ex≈cution refus≈e
635 erreur sh : mot de passe (pwd) trop long
636 op≈rateur inconnu 
637 fin du fichier
638  inattendu
639  » la ligne 
640 Arr¡t
641 Sortie
642 Instruction non valide
643 Analyse/interruption BPT
644 annulation (abort)
646 Interruption EMT
647 Exception virgule flottante
648 Interrompu
649 Erreur de bus
650 Incident au niveau de la m≈moire
651 Appel syst…me erron≈
652 Signal d'alarme
653 Termin≈
654 Signal 16
655 Signal 17
656 Destruction du processus enfant
657 Panne de courant
658 exporter
659 lecture seulement (readonly)
660 Fichier ex≈cutable non compatible avec le mat≈riel
661 ≈chec de sigemptyset()
662 ≈chec de sigprocmask()
663 ≈chec de sigdelset()
701 pwd: acc…s impossible ..
702 pwd: impossible d'ouvrir ..
703 pwd: erreur de lecture dans ..
801 l'ex≈cution a ≈chou≈ (exec) t=%s\n
802 ptrace: 
803 d≈bordement du tampon interne de 2K du shell sh
804 d≈bordement du tampon to_tcharn
901 ] manquant
902 argument attendu
903 ) attendue
1001 Syntaxe: netunam fichier_sp≈cial_r≈seau cha—ne_ouverture
1002 Le nom d'ouverture de session » distance non valide.  Erreur r≈seau = 
1003 Le noeud ≈loign≈ ne r≈pond pas.  Erreur r≈seau = 
1004 Fichier sp≈cial de r≈seau non valide.  Num≈ro d'erreur = 
1005 commande interne inconnue\n
1006 impossible de dupliquer (fork): num≈ro d'erreur = 
1007 appel r≈seau non pris en charge
1101 d≈bordement du tampon interne de 2K du shell sh
1102 d≈bordement du tampon interne de 2K du shell sh
