$set 1
1 utilisation non valide des options de la ligne de commande
3 nom de chemin trop long: 
4 trop de cl≈s de tri
5 v≈rifie un fichier seulement
6 erreur d'affectation avant le tri (sort)
7 fichier temporaire (temp) introuvable
8 erreur d'affectation avant la fusion (merge)
9 attention: caract de changement de ligne (NEWLINE) ajout≈ » fin du fichier
10 attention: caract de chang de ligne (NEWLINE) ajout≈ » fin du fich d'entr≈e 
11 erreur grave: enregistrement trop grand
12 tri
13 fusion
14 attention: caract…re de changement de ligne (NEWLINE) ajout≈ » fin du fichier
15 erreur grave: ligne trop longue
18 impossible de cr≈er 
19 impossible de cr≈er 
20 impossible d'ouvrir 
21 attention: option -d pas prise en compte pour langages » octets multiples
22 attention: option -f pas prise en compte pour langages » octets multiples
23 attention: l'option -l n'est pas exig≈e, non prise en compte
24 attention: option -i pas prise en compte pour langages » octets multiples
25 erreur de lecture dans 
26 erreur d'≈criture pendant 
