$set 1
1 Tar: impossible de cr≈er le fichier temporaire (%s)\n
2 Longueur de bloc non valide (maximum %d).\n
3 tar: %c: option inconnue\n
4 tar: longueur de bloc %d trop grande, m≈moire insuffisante\n
5 Ne peut cr≈er que des archives de sortie standard\n
6 tar: impossible d'ouvrir %s\n
7 tar: syntaxe\ntar [-]{txruc}[ONvVwAfblHhm{op}][0-7[lmh]] [fichbande] [longbloc] f1 f2...\n
8 tar: syntaxe\ntar [-]{txruc}[ONvVwfblHhm{op}][0-7[lmh]] [fichbande] [longbloc] f1 f2...\n
9 tar: syntaxe\ntar [-]{txruc}[ONvVwAfblhm{op}][0-7[lmh]] [fichbande] [longbloc] f1 f2...\n
10 tar: syntaxe\ntar [-]{txruc}[ONvVwfblhm{op}][0-7[lmh]] [fichbande] [longbloc] f1 f2...\n
11 tar: syntaxe\ntar [-]{txruc}[ONvVwAfblm{op}][0-7[lmh]] [fichbande] [longbloc] f1 f2...\n
12 tar: syntaxe\ntar [-]{txruc}[ONvVwfblm{op}][0-7[lmh]] [fichbande] [longbloc] f1 f2...\n
13 Tentative d'archivage d'aucun fichier. Rien n'a ≈t≈ vid≈.\n
14 Liens manquants » %s\n
15 total de contr¬le (checksum) du r≈pertoire erron≈\n
16 tar: impossible d'acc≈der » %s.  N'est pas vid≈.\n
17 Les entr≈es acl facultatives de <%s> ne sont pas vid≈es\n
18 tar: %s: erreur de lecture de r≈pertoire\n
19 tar: %s: lien symbolique trop long\n
20 tar: impossible de lire le lien symbolique 
21 a %1$s lien symbolique » %2$s\n
22 a %s 0 bloc\n
23 tar: %s: impossible d'ouvrir le fichier\n
24 a %1$s lien » %2$s\n
25 M≈moire insuffisante.  L'information sur le lien est perdue\n
26 a %1$s %2$ld blocs\n
27 %s: la taille du fichier a chang≈\n
28 tar: %s n'est pas un fichier.  N'est pas vid≈\n
29 tar: %s: ≈chec du lien symbolique: 
30 x %1$s lien symbolique » %2$s\n
31 %s: impossible de cr≈er le lien\n
32 %1$s li≈ » %2$s\n
33 tar: %s n'a pu cr≈er le fichier de p≈riph≈riques en mode caract…re\n
34 x %s, 0 octet, 0 bloc, fichier de p≈riph≈riques en mode caract…re\n
35 tar: %s n'a pu cr≈er le fichier de p≈riph≈riques en mode bloc\n
36 x %s, 0 octet, 0 bloc, fichier de p≈riph≈riques en mode caract…re\n
37 tar: %s n'a pu cr≈er fifo \n
38 x %s, 0 octet, 0 bloc, fifo\n
39 tar: %s cr≈≈ comme fichier standard.\n
40 tar: %s - impossible de cr≈er\n
41 x %1$s, %2$ld octets, %3$ld blocs sur la bande\n
42 tar: %s: AIDE - erreur d'≈criture au moment de l'extraction\n
43 tar: le changement de mode (chmod) a ≈chou≈
44 tar: le changement de propri≈taire (chown) a ≈chou≈
45  li≈ » %s
46  lien symbolique » %s
47 %b %2d %H:%M %Y
48 tar: impossible d'obtenir le nom du syst…me (uname) de l'uid %d\n
49 tar: impossible d'obtenir le nom du syst…me (gname) du gid %d\n
51 tar: impossible d'acc≈der au r≈pertoire de travail (pwd)
52 tar: (pwd!) limite du niveau de bouclage atteinte \n
53 Tar: erreur de lecture de la bande\n
54 Tar: erreur dans la longueur de bloc sur la bande\n
55 Tar: longueur de bloc = 0; conduit interrompu?\n
56 Tar: longueur de bloc = %d\n
57 Tar: erreur! longueur de bloc modifi≈e\n
58 Tar: erreur de lecture de la bande\n
59 tar: %s: nom de chemin trop long\n
60 tar: %s: pr≈fixe trop long\n
61 tar: %s: nom de fichier trop long\n
62 %s: nom de fichier trop long\n
63 Tar: erreur de bande (%d)\n
64 Tar: erreur dans le nouveau volume\n
65 Impossible d'ouvrir /dev/tty pour inviter » pr≈ciser un autre support.\n
66 Tar: fin de la bande\n
67 Tar: pour continuer, entrez nom fich/p≈riph ou cha—ne vide pour sortir.\n
68 L'utilisateur a entr≈ un nom vide comme fichier de p≈riph≈riques suivant.\n
69 Tar: impossible d'ouvrir %s\n
70 L'utilisteur a ouvert le fichier %s pour continuer.\n
71 tar: %s n'a pu cr≈er le r≈pertoire \n
72 tar: %s: lien au nom trop long\n
73 tar: %s: impossible d'acc≈der au fichier\n
74 tar: M≈moire insuffisante. Impossible de rep≈rer boucles liens symboliques\n
75 tar: Boucle de liens symboliques d≈tect≈e, tar interrompu\n
76 tar: Impossible de passer au r≈pertoire '%s'\n
77 tar: Saut du chemin '%s' \n
78 tar: option non accept≈e pour unit≈s » cartouche 1/4 de pouce (QIC) %s\n
79 tar: Impossible de fermer %s\n
80 tar: Impossible de lire/≈crire par le biais de NFS\n
