$set 1
1 Impossible d'ouvrir le fichier
2 Faute de frappe dans une option globale
3 Option non valide
4 caract…re de sp≈cification de tableau erron≈
5 trop de lignes dans la sp≈cification
6 aucune sp≈cification
7 le dernier caract…re de la ligne de format ne peut ¡tre un point
8 tentative d'≈largir le tableau dans T&, non admis
9 la premi…re colonne ne peut ¡tre de type S
10 attention: chevauchement impossible dans colonne type a, type chang≈ » l\n
11 attention: chevauchement impossible dans colonne type n, type chang≈ » c\n
12 la premi…re ligne ne peut comporter une ≈tendue verticale
13 trop de colonnes dans le tableau
14 Nom de police incomplet
15 corps de caract…re trop grand
16 corps de caract…re non valable
17 valeur de l'interlignage trop ≈lev≈e
18 largeur de colonne trop grande
19 Fin de fichier inattendue dans les sp≈cifications du tableau
20 ligne de sp≈cification trop longue
21 Impossible d'obtenir de la m≈moire
22 Chevauchement vertical interdit dans la premi…re ligne
23 Tableau » la ligne %1$d fichier %2$s est trop grand - \\n(unit≈s TW\n
24 %1$s: ligne %2$d: Donn≈es ignor≈es sur la ligne %3$d du tableau\n
25 ‹trange, aucune donn≈e dans le tableau.
26 ‹trange, pas de vrais lignes dans le tableau.
27 Trop de caract…res dans le tableau
28 pas d'espace pour les caract…res
29 pas d'espace pour le vecteurs
30 caract…res » utiliser comme s≈parateurs introuvables
31 \n%1$s: ligne %2$d: %3$s\n
32 sortie de tbl\n
33 ex≈cution interrompue; erreur d≈tect≈e par le pr≈processeur tbl\n
34 trop de sauvegardes
35 fin de fichier inattendue
36 Trop de transferts de blocs de texte
37 Trop de colonnes pour les registres
