$set 1
100 Vous devez Átre le superutilisateur pour dÅfinir un nom de noeud\n
101 Le nom de noeud doit comporter moins de\n
102  caractÉres\n
103 syntaxe: uname [-amnrsvil] [-S nom_noeud]\n
104 licence pour deux utilisateurs
105 licence pour un nombre illimitÅ d'utilisateurs
106 licence pour 16 utilisateurs
107 licence pour 32 utilisateurs
108 licence pour 64 utilisateurs
109 licence pour 8 utilisateurs
