$set 1
1 syntaxe: %s -nstux [-|fichier] ...\n
2 %s: impossible d'acc≈der (stat) au fichier de sortie standard (stdout)\n
3 %s: impossible d'ouvrir %s\n
4 %s: impossible d'acc≈der (stat) » %s\n
5 %s: le fichier d'entr≈e %s est le m¡me que le fichier de sortie\n
6 %s: erreur de fermeture\n
7 %s: erreur de fermeture\n
8 %s: erreur » la sortie\n
9 %s: ≈tat 1, donn≈es non valides "%d"\n
10 %s: ≈tat 2, donn≈es non valides "%d"\n
11 %s: ≈tat 2, donn≈es non valides "%d"\n
12 %s: ≈tat 2, donn≈es non valides "%d"\n
13 %s: ≈tat 2, donn≈es non valides "%d"\n
14 %s: ≈tat 3, donn≈es non valides "%d"\n
15 %s: ≈tat 3, donn≈es non valides "%d"\n
16 %s: ≈tat 3, donn≈es non valides "%d"\n
17 %s: ≈tat 3, donn≈es non valides "%d"\n
18 %s: fin anormale en provenance de l'≈tat %d\n
