$set 1
4 Fente vide.\n
5 NOM        LIGNE        HEURE         INACTIF  PID  COMMENTAIRES\n
6 NOM        LIGNE        HEURE\n
7   id=%4.4s
8  term = %-3d sortie = %-3d
9 \n# utilisateurs = %d\n
10 \nSyntaxe: who [-rbtpludAasHTqcR] [am i] [fichier_type_utmp]\n
11 \nSyntaxe: who [-rbtpludAasHTqR] [am i] [fichier_type_utmp]\n
12 \nr\t niveau d'ex≈cution\nb\t heure d'initialisation\nt\t dernier changement d'heure\n
13 p\t processus autres que getty ou utilisateurs\n
14 l\t processus d'ouverture de session\nu\t informations utiles\n
15 d\t processus interrompus\nA\t information sur la gestion du syst…me\n
16 a\t toutes les options (options rbtpludA)\n
17 s\t format abr≈g≈ de who (temps ≈coul≈ depuis derni…re sortie ou pid)\n
18 H\t affiche un en-t¡te\n
19 T\t ≈tat du tty (+ ≈criture, - ≈criture non aut., x ouverture exclusive,\n\t ? en interruption)\n
20 q\t who tr…s abr≈g≈\n
21 c\t who au niveau de toute la grappe\n
22 %b %2d %H:%M
23   ancien 
24    . 
25  %2u:%2.2u
26 R\t affiche le nom d'h¬te\n
