$set 1
1 Syntaxe: write utilisateur [terminal]\n
2 Syntaxe: write utilisateur [terminal]\n
3 Je ne peux d≈terminer le nom de votre terminal. Aucune r≈ponse possible.\n
4 %1$s a ouvert une session » plus d'un emplacement.\nVous ¡tes connect≈ » "%2$s".\nAutres emplacements:\n
5 %1$s a ouvert une session » plus d'un emplacement.\nVous ¡tes connect≈ » "%2$s".\nAutres emplacements:\n
6 Autorisation refus≈e.\n
7 %1$s ne se trouve pas » "%2$s".\n
8 Autorisation refus≈e.\n
9 %s n'a pas ouvert de session.\n
10 Impossible de d≈terminer qui vous ¡tes.\n
11 Attention: Votre terminal est d≈fini » "mesg -n". Aucune r≈ponse possible.\n
12 \n\007\007\007\tMessage de %1$s (%2$s) [ %3$s ] ...\n
13 Ne peut plus ≈crire » %s\n
14 Duplication (fork) impossible.  Ressayez plus tard.\n
15 D≈passement de d≈lai : ouverture de la ligne(%2$s) de %1$s.\n
16 <EOT>\n
17 %a %h %d %H:%M:%S
