$set 1
1 ¨¥¤Χαΰ -F ¶τ -f ¤υ΅·΅Ζ΅Ά\n
2 ¨¥¤Χαΰ -F ¶τ -f ¤υ΅·΅Ζ΅Ά\n
3 ¨¥¤Χαΰ -P ¶τ -p ¤υ΅·΅Ζ΅Ά\n
4 ¨¥¤Χαΰ -P ¶τ -p ¤υ΅·΅Ζ΅Ά\n
5 mark_ev (%d) «κίά­©ΊΫ\n
6 '%c' υλ Υυ°¬΅ΪΆ¶§μΊι\n
7 ΅©»Σ΅ΪΆ¶ υλ %s\n
8 mark_ev (%d) «κίά­©ΊΫ\n
9 mark_sc (%d) «κίά­©ΊΫ\n
10 '%c'υλ Υυ°¬ syscall §μΊι\n
11 ΅©»ΣΜί syscall υλ %s\n
12 mark_sc(%d) «κίά­©ΊΫ\n
13 '%c' υλ ΅©»Σθ΄Ήωξθ\n
21 νύρΘΡθΆμΚυΦύ\n
22 audswitch(AUD_SUSPEND) υέ «κίά­©ΊΫυλ %s\n
23 mark_ev(%d) «κίά­©ΊΫ\n
24 ΅©»Σ§μΊιυλ %s\n
25 show_audit () «κίά­©ΊΫ\n
26 set _audit () «κίά­©ΊΫ\n
31 mark_sc (%d) «κίά­©ΊΫ\n
41 audwrite(%s) «κίά­©ΊΫυλ %s\n
42 getevent() «κίά­©ΊΫυλ %s\n
43 set_event(%s) «κίά­©ΊΫ\n
44 set_syscall(%d) «κίά­©ΊΫ\n
45 audwrite(%s) «κίά­©ΊΫυλ %s\n
46 setevent() «κίά­©ΊΫυλ %s\n
51 audwrite(%s) «κίά­©ΊΫυλ %s\n
52 getevent() «κίά­©ΊΫυλ %s\n
53 show_event(%s) «κίά­©ΊΫ\n
61 ΚυΒΊυλ %s
