$set 1
1 ส๕ยบ:\tcp [-f|-i] [-p] source_file target_file\n\tcp [-f|-i] [-p] source_file ... target_directory\n\tcp [-f|-i] [-p] -R|-r source_directory ... target_directory\n
2 cp: ฦเยบ unlink %s:
3 cp: ฦเยบฏขง๕ %s:
4 cp: <%s> อท๊Ý. ํำเ๗ "-R" ่ด๎่.\n
5 cp: %s๕เ%s๕๋ จนะำญฅ๋ใ\n
6 cp: %s จ๎ %s ปแจธกขฃร\n
7 cp: %s๕๋ กฉปแกขฃรอท๊Ý\n
9 cp: ฦเยบณฅัผ %s:
10 cp: ฦเยบ๋๋ฉอ
11 cp: ฦเยบณฅัผ %s:
12 cp: เลเรฅ์ %s ๊้โผ:
13 cp: ฦเยบ์ต๋้ %s:
14 cp: ฦเยบแแฏฦคืแเขาคุปญ %s:
15 cp: %s/%s: จนะำญฅ๋ใ.\n
16 cp: ฦเยบ mkrnod
17 cp: ฦเยบ symlink
18 cp: ฦเยบ readlink
19 cp: utime ญฉบÛ %s:
20 cp: chown ญฉบÛ %s:
21 ใทจา: ดวหทsocket: %s\n
22 cp: ใทจา๕๋ฦเยบspaclูค%s\n๗ก
23 cp: ใทจา: ฦเยบspaclูค%s\n
24 ็ไิตญฉบÛ
25 เลฏ๕ %s?
26 cp: %s: กฉปแอท๊Ý\n
27 cp: ฦเยบฏขง๕ ACL ปญ %s:
28 cp: ฦเยบ้นึฒ %d ๆโค้๎่ ACL ิฝ %s:
29 cp: ฦเยบใมง๕ ACL ปญ %s:
