$set 1
1 ÊõÂºõë%s -f fromcode -t tocode [¿ú½ó...]\n
2 ÆàÂº·Ê¥Ôæò¸şßì½ëÌß­¢°«\n
3 ÆàĞóëğ¢÷æò¸şßì½ë¢ìÊõ\n
4 ÆàÂº°¨æò¸ş£ãäù­âáá¯Æ\n
5 êéâ¼Ìßæâ¤é¯¡¤Ø\n
6 ÆàÂºÔµ¼şæò¸ş\n
7 Êü %s æò¸şÇß %s ³Ù¶ï¡¨¥â¯¡¤Øõë\n
8 ROMAN8õë\\x%x%-25s ISO 8859/1õë\\x%x%-25s\n
9 ISO8859/1: \\x%x %-25sROMAN8: \\x%x %-25s\n
10 NA (Do not use)
11 No break space
12 Accent grave 
13 Left single quote
14 Circumflex accent
15 Caret 
16 Tilde accent 
17 Tilde
18 Italian lira symbol
19 Pound sign 
20 Overline
21 Macron
22 Cutch guilder
23 Lowercase f
24 Uppercase S caron
25 Uppercase S
26 Lowercase s caron
27 Uppercase s
28 Uppercase Y umlaut
29 Uppercase Y
30 Horizonal bar
31 Hyphen
32 Solid box
33 Asterisk
34 NA (Do not use)
35 No break space
40 No break space
41 NA (D0 not use)
42 Broken bar
43 Vertical line
44 Copyright sign 
45 Lowercase c
46 Not sign 
47 Tilde
48 Soft hyphen
49 Hyphen
50 Registered Trade Mark
51 Uppercase R
52 Macron
53 Top bar
54 Superscript two
55 Digit two
56 Superscript three
57 Digit three
58 Cedilla
59 Comma
60 Superscript one
61 Digit one
62 Multiplication sign
63 Lowercase x
64 Division sign
65 Solidus
