$set 1
1 ΖΰΒΊαα―Ζ LC_COLLATE\n
2 ΖΰΒΊαα―Ζ LC_CTYPE\n
3 ΖΰΒΊισ»§λλ©Ν stdin\n
4 ΚυΒΊ:\tlocaledef [-c] [-f charmap_file] [-i input_file] locale_name\n
5 ¶τ\tlocaledef -d [-o format] locale_name\n
6 ¶τ\tlocaledef -n input_file\n
7 ΖΰΒΊλλ©Ν 'debug' Ώϊ½σ\n
9 ΖΰΒΊλλ©Ν %s ζβ¤ιΏϊ\n
10 Ζΰ 'langname' ΅Ζα΅½λ\n
11 Ζΰ 'langid' ΅Ζα΅½λ\n
12 'langname' ¨ξ 'langid' ΅·΅Ζα΅½λ΅ίΝΊ·ΘαΔ\n
13 'isfirst' ¨ξ 'byte_chars' ΅·΅Ζα΅½λ΅ίΝΊ·ΘαΔ\n
14 γ·¨Ò: °£΄ΗΛ·ξκ²Πα΅½λ\n
15 LC_ALL οµ¥ηδόηφ¤Χαΰ΅ΖΌΟ­ΆμΡ¥π\n
16 LC_MESSAGES οµ¥ηδόηφ¤Χαΰ΅ΖΌΟ­ΆμΡ¥π\n
17 LC_COLLATE οµ¥ηδόηφ¤Χαΰ΅ΖΌΟ­ΆμΡ¥π\n
18 LC_CTYPE οµ¥ηδόηφ¤Χαΰ΅ΖΌΟ­ΆμΡ¥π\n
19 LC_MONETARY οµ¥ηδόηφ¤Χαΰ΅ΖΌΟ­ΆμΡ¥π\n
20 LC_NUMERIC οµ¥ηδόηφ¤Χαΰ΅ΖΌΟ­ΆμΡ¥π\n
21 LC_TIME οµ¥ηδόηφ¤Χαΰ΅ΖΌΟ­ΆμΡ¥π\n
22 ΖΰΒΊ³¥ΡΌ 'locale.inf' Ώϊ½σ\n
23 localedef κιβΌ: %d ίά΅Ζμµκς―΅΅©¨µ\n
25 localedef κιβΌ: %d ίά΅Ζ―΅¤Ψ΅©¨µ\n
26 localedef κιβΌ: %d ίά΅ΖΊΥηΔ΅©°¨\n
27 localedef κιβΌ: %d ίά΅ΖητÒª³²΅©°¨\n
28 localedef κιβΌ: %d ίά΅ΖÒΏ«®΅©°¨\n
29 localedef κιβΌ: %d ίά΅ΖβΈαΙ¨ΉΠΣλγ²Ψ΅©°¨\n
30 localedef κιβΌ: %d ίά΅ΖβΈαΙγ²¥ηΞχ΅©¨µ\n
31 localedef κιβΌ: βΈαΙ¨ΉΠΣ %d ΅·΅ΖβΈαΙ¨ΉΠΣλγ²Ψ΅©°¨\n
32 localedef κιβΌ: βΈαΙ¨ΉΠΣ %d ΅·΅Ζ§¬«ε¨ΉΠΣλγ²Ψ΅©°¨\n
33 localedef κιβΌ: βΈαΙ¨ΉΠΣ΅·Ρί %d ίάΜί―΅Ξχν³¨ΉΠΣ΅©°¨\n
34 localedef κιβΌ: %d ίά£µΊΞ΅Ζ―΅΅Ίλγ²Ψ΅©°¨\n
36 localedef κιβΌ: %d ίά΅Ζ―΅¤ΨΞχ΅©°¨\n
37 localedef κιβΌ: %d ίά΅Ζ isfirst ―΅¤ΨΞχ΅©°¨\n
38 localedef κιβΌ: %d ίά΅Ζ issecond ―΅¤ΨΞχ΅©°¨\n
39 localedef κιβΌ: code_scheme ¨ΉΠΣλγ²Ψ %d ΅©°¨\n
40 localedef κιβΌ: code_cscheme ¨ΉΠΣ %d ΅©°¨\n
41 localedef κιβΌ: cswidth ―΅΅Ίλγ²Ψ %d ΅©°¨\n
42 localedef κιβΌ: cswidth ―΅΅Ί½λ³² %d ΅©°¨\n
43 localedef κιβΌ: langinfo ―΅΅Ίλγ²Ψ %d ΅©°¨\n
44 localedef κιβΌ: δ¦²µ―΅΅Ίλγ²Ψ %d ΅©°¨\n
45 localedef: Ίι£Ò―΅΅Ίλγ²Ψ %d ΅©°¨\n
46 localedef κιβΌ: £µΊΞ―΅΅Ίλγ²Ψ %d ΅©°¨\n
47 localedef κιβΌ: malloc() ­©ΊΫ \n
48 localedef κιβΌ: ¤Ξ¤ά²Π΅t¥βΔΤΔ« \n
49 localedef κιβΌ: »α¨ξ¨Ε ―΅΅Ί΅©Ψ¥ΌΤΝΊ¨ΈΜίΡί΅Ά£Γ―΅¤Ψ %d\n
50 localedef κιβΌ: Σα¤Ψ―΅΅Ίλγ²Ψ %d ΅©°¨\n
51 localedef κιβΌ: Σα¤Ψ―΅΅Ί½λ³² %d ΅©°¨\n
52 localedef κιβΌ: Έ«―Ζ­¥¬ωΣα¤Ψ―΅΅Ί %d\n
53 localedef κιβΌ: ·Κ΅©¥μΈ«―Ζ΅ΖΡΪέλ %d\n
58 localedef κιβΌ: ·Κ΅©¥μ charmap Ώϊ½σ \n
60 localedef κιβΌ: ΡΪέλισΰΕ %d\n
63 localedef κιβΌ: %d ίά΅·,δόηφ COLL_WEIGHTS_MAX ·©Έ«―Ζ\n
68 localedef γ·¨Ò: ·Κ΅©¥μΈ«―Ζ΅ΖΡΪέλ %d\n
72 localedef γ·¨Ò: ΌζΊΗΉ«μµκς―΅ %d\n
73 localedef γ·¨Ò: ΅©ΐάΞφΜί ctype δω­βαα―Ζ - Έζ§υΐάΞφίά¦Σ\n
74 'langname' ¨ξ 'langid' ΅·΅Ζα΅½λ΅ίΝΊ·ΘαΔ
75 γ·¨Ò: ΆμΚυΦύΈ«―Ζ΅ΖβΈαΙ¶Ξ«¶βΈαΙγ²¥ηΞχÒΏ«® 901 Ω¤ 999 ΅Ζλπ\n
76 ΆμΚυΦύΈ«―Ζ΅ΖβΈαΙ¶Ξ«¶βΈαΙγ²¥ηΞχÒΏ«® 901 Ω¤ 999
77 'langname' ¨ξ 'langid' ΅·΅Ζα΅½λ΅ίΝΊ·ΘαΔ
78 γΑ§υκιβΌ΅ΖΏϊ½σ:
79 ΖΰΒΊ lseek Ώϊ½σ:
80 ΖΰΒΊλλ©Ν %s Ό«―ΆΏϊ\n
81 κιβΌΤωγ» charmap Ώϊ½σ\n
82 ΆÒΦ²κιβΌ: ΜΪΙΠκιβΌίά»­ LC_COLLATE οµ¥η: %d\n
