$set 1
1 %s: "%s": §ìºé¡©ÑÚ.\n
2 %s: ¡©»ÓÌß %s â¸ºğ.  ¢ìÊõ¤ê¯Æâ¸ºğ.\n
3 %s: Æà¢ìÊõÀ¹. íı super-user.\n
4 %s: ã·¨Ò: ¼æ«êßÜ¢¸¢Øçô¢Ş.\n
5 %s: ÆàÂºëë©Í %sà·Ö².\n
6 %s: íı¯¡¤Øà·Ö² %s.\n
7 %s: íı SCSI à·Ö² %s .\n
8 %s: à·Ö²³·ºé %s ¡©°¨.\n
9 áá¯Æ immediate_report
10 §õ³ø immediate_report
11 %s: ¥åìİ¡Æ magneto-optical %s à·Ö²¡©°¨.\n
12 %s: ¥åìİ¡Æ section-2 %s à·Ö²¡©°¨.\n
13 ¥åìİ
14 ÊõÂº: %s [-akq] [-m mode[=value]]... [-c command]... device\n
$
$ L10N note:  The following 2 messages are used together.  The entire error
$             message should look somthing like this:
$
$                    scsictl: Device ioctl ("msg") error
$
$             where "msg" would be a localized message.
$             Do not localize "ioctl" since it is a Unix terminlolgy.
15 : ioctl à·Ö²(
16 ) êéâ¼
