$set 1
4 ΠσΜίΏΝ\n
5 ¨ΉΠΣ       ¥βΊι        »ηλπ          IDLE       PID     αθαΌ\n
6 ¨ΉΠΣ       ¥βΊι        »ηλπ\n
7 id=%4.4s
8 term=%-3d exit=%-3d
9 \n# ΆμΚυΦύ=%d\n
10 \nΚυΒΊ:\twho [-rbtpludAasHTqcRm] [am i] [utmp_like_file]\n
11 \nΚυΒΊ:\twho [-rbtpludAasHTqRm] [am i] [utmp_like_file]\n
12 \nr\t«κίά°Τΐΐ\nb\t©Ν¦Σ»ηλπ\nt\t»ηλπΊΞγΔ\n
13 p\tgetty ¶τΆμΚυΦύΆ±¬χΜίΠΔ²Π\n
14 l\tΜΩκέΠΔ²Π\nu\tΌΤΚυΜίδΎαΞ\n
15 d\tΐηΠΔ²Π\nA\tΌΠαΝδΎαΞ\n
16 a\t¤λθουΩrbtpludA θ΄ΉωξθυΪ\n
17 s\twho ΜίΞ·³Ω³²υΩΨό³ό΅§΅Άΐΐζβ¥Τ¶τ pid ³τΖΰ»ηλπυΪ\n
18 H\t§Θ¥ΤΏΤο­\n
19 T\ttty Θ»µχυΩ+ ¨«―υΜί, - ΅©¨«―υΜί, x©Δ΅Άλλ©ΝΜί, ? ΈδΫάυΪ\n
20 g\t΄ΏηΰΜί who\n
21 c\tΦΟν³―φΜί who\n
22 %b %2d»Ε %H:%M
23 Ω΄Μί
24 .
25 %2uυλ%2.2u
26 R\tprint ΅ΐΏλ¨ΉΠΣ\n
