# $Source: /source/hpux_source/networking/rcs/arpa90_800/xntp/ntpdate/RCS/Makefile.tmpl,v $
# $Revision: 1.2.109.1 $	$Author: mike $
# $State: Exp $   	$Locker:  $
# $Date: 94/10/27 10:40:38 $

#
# Makefile.tmpl,v 3.1 1993/07/06 01:09:20 jbj Exp
#
PROGRAM=	ntpdate
#
# ntpdate - private mode query program for ntpdate
#
COMPILER= cc
COPTS= -O
BINDIR=	/usr/local
DEFS=
RESLIB=
ADJLIB=
COMPAT=
#
INCL=		-I../include
CFLAGS=		$(COPTS) $(DEFS) $(INCL)
CC=		$(COMPILER)
LIB=		../lib/libntp.a
LINTLIB=	../lib/llib-llibntp.ln
MAKE=		make
#
OBJS=	ntpdate.o
SOURCE=	ntpdate.c

all:	$(PROGRAM)

$(PROGRAM): $(OBJS) version.o $(LIB)
	$(CC) $(COPTS) -o $@ $(OBJS) version.o $(LIB) $(RESLIB) \
		$(ADJLIB) $(COMPAT)

install:	$(PROGRAM)
	install -c -m 0755 $(PROGRAM) $(BINDIR)

tags:
	ctags *.c *.h

depend:
	mkdep $(CFLAGS) $(SOURCE)

clean:
	rm -f $(PROGRAM) *.o *.out tags make.log Makefile.bak lint.errs

distclean:	clean
	rm -f Makefile

lint:	$(LINTLIB)
	lint -x -u $(DEFS) $(INCL) $(LINTLIB) $(SOURCE) >lint.errs

../lib/llib-llibntp.ln:
	cd ../lib ; $(MAKE) $(MFLAGS) lintlib

../libc/libntp.a:
	cd ../libntp ; $(MAKE) $(MFLAGS)

