default:
	: 
install:
	mkdir -p ../../../Filesets.sl/UX-CORE/etc/newconfig
	! cp syslog.conf ../../../Filesets.sl/UX-CORE/etc/newconfig/syslog.conf
	! chmog 444 bin bin ../../../Filesets.sl/UX-CORE/etc/newconfig/syslog.conf
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE/etc/newconfig
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE/etc
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE
	! chmog 555 bin bin ../../../Filesets.sl
