
/* Here are the symbols we will go after */

struct	nlist nl[] = {
	{ "proc" },
	{ "firstfree" },
	{ "maxfree" },
	{ "text" },
	{ "freemem" },
	{ "nproc" },
	{ "ntext" },
	{ "UNUSED"},		/* was bclnlist */
	{ "bswlist" },
	{ "nswbuf" },
	{ "swbuf" },	/* 10 */
	{ "dbc_hdr" },	
	{ "nbuf" },
	{ "bufhash" },
	{ "bfreelist" },
	{ "inode" },
	{ "mount" },
	{ "ninode" },
	{ "ihead" },
	{ "shmem" },
	{ "shminfo" },	/* 20 */
	{ "shm_shmem"},
	{ "pdir" },
	{ "htbl" },
	{ "iopdir" },
	{ "npdir" },
	{ "nhtbl" },
	{ "niopdir" },
	{ "npids" },
	{ "niopids" },
	{ "ifreeh" }, /* 30 */
	{ "ifreet" },
	{ "file" },
	{ "nfile" },
	{ "lotsfree"},
	{ "minfree"},
	{ "desfree"},
	{ "_release_version"},
	{ "camap"},
	{ "ecamap"},
	{ "shm_vfds"}, /* 40 */
	{ "qs"},
	{ "swapdev"},
	{ "end"},
	{ "etext"},
	{ "rpb"},
	/* REGION STUFF */
	{ "phead"},
	{ "pbad"},
	{ "pfdat"},
	{ "phash"},
	{ "phashmask"},		/* 50 */
	{ "pregfree"},
	{ "pactive"},
	{ "region"},
	{ "regactive"},
	{ "regfree"},
	{ "ptfree"},
	{ "swaptab"},
	{ "nextswap"},
	{ "sysmap"},
	{ "tune"},		/* 60 */
	{ "sysinfo"},
	{ "v"},
	{ "physmem"},
	{ "swapwant"},
	{ "psegs"},
	{ "slroot"},
	{ "pregion"},
	/* vnode stuff */
	{ "rootvfs"},
	{ "ufs_vfsops"},
	{ "ufs_vnodeops"},	/* 70 */
	{ "nfs_vfsops"},
	{ "nfs_vnodeops"},
	{ "rtable" },
	{ "rpfreelist" },
	{ "uidhash"},
	/* vnode dnlc stuff */
	{ "ncache"},
	{ "nc_hash"},
	{ "nc_lru"},
	{ "ncstats"},
	/* DUX related stuff */
	{ "UNUSED"},		/* 80 (was devices) */
	{ "UNUSED"},		/* was ndevices */
	{ "nsp"},
	{ "ncsp"},
	{ "max_nsp"},
	{ "mountlock"},
	{ "mount_waiting"},
	{ "selftest_passed"},
	{ "clustab"},
	{ "my_site"},
	{ "root_site"},		/* 90 */
	{ "swap_site"},
	{ "my_site_status"},
	{ "using_array"},
	{ "using_array_size"},
	{ "serving_array"},
	{ "serving_array_size"},
	{ "UNUSED"},		/* used to be dskless_mbufs */
	{ "UNUSED"},		/* used to be dskless_cbufs */
	{ "UNUSED"},
	{ "dbc_hdr"},		/* 100 */
	{ "dux_mbstat"},
	{ "net_bchain"},		/* used to be mbuf_xtra_stats */
	{ "inbound_opcode_stats"},
	{ "outbound_opcode_stats"},
	{ "physmembase"},
	{ "mpproc_info"},
	{ "spl_lock"},
	{ "spl_word"},
	{ "stackaddr"},
	{ "vastable"},		/* 110 */
	{ "global_lock_list" },
	{ "global_sema_list" },
	{ "semaphore_log" },
	{ "TrFreeq" },
	{ "TrUncommittedq" },
	{ "TrCommittedq" },
	{ "Syssegtab"},
	{ "u" },
	{ "cur_proc"},
	{ "swdevt"},		/* 120 */
	{ "swapdev_vp"},
	{ "crash_processor_table" },
	{ "crash_event_table" },
	{ "panic_save_state" },
	{ "panic_second_save_state" },
	{ "boottime" },
	/* MP stuff */
	{ "slpsem" },
	{ "kernel_sema" },
	{ "net_sema" },
	{ "filesys_sema" },      /* 130 */
	{ "vmsys_sema" },
	{ "pm_sema" },
	{ "io_sema" },
	{ "spin_alloc_base" },
	{ "spin_alloc_end" },
	{ "spin_alloc_next" },
	{ "global_lock_list" },
	{ "global_sema_list" },
	{ "semaphore_log" },
	{ "log_index" },              /* 140 */
	{ "last_log_entry" },
	{ "log_total" },
	{ "nsemalogs" },
	{ "semalog_entry_size" },
		/* configurable table variables */
	{ "BUFHSZ" },
	{ "INOHSZ" },
	{ "UIDHMASK" },
	{ "kernvas" },
	{ "tt_region_addr" },
	{ "pgtopde_table" },        /* 150 */
	{ "scaled_npdir" },
	{ "pdirhash_type" },
	{ "kmemstats" },
	{ "shmmni" },
	{ "nclist" },
	{ "bufpages" },
	{ "cfree" },
	{ "three_level_tables" },
	{ "pst_cmds" },
	{ "dqhead" },		   /* 160 */
	{ "dqfreelist" },
	{ "dqresvlist" },
	{ "" }
};
