#
# $Header: makefile,v 1.1.109.1 91/11/21 11:39:10 kcs Exp $
#

all: 
	(cd res; $(MAKE) all)
	(cd named; $(MAKE) all)
	(cd tools; $(MAKE) all)

clean:
	(cd res; $(MAKE) clean)
	(cd named; $(MAKE) clean)
	(cd tools; $(MAKE) clean)

clobber:
	(cd res; $(MAKE) clobber)
	(cd named; $(MAKE) clobber)
	(cd named; $(MAKE) clobber)
