extern int vcbLstFirst;
extern unsigned int memsize;
extern int noprotect;
extern int vimap, vpid;
extern pMODER vmode;
extern int display_headers;
extern int sym_tab_size;
extern int scroll;
extern int vibpMac;
extern BPR vrgBp[];
extern FLAGT FClearBp ();
extern int IbpFBrk ();
extern int BrkIn ();
extern int IbpFBrkOut ();
extern int IbpFAdr ();
extern int IbpFSet ();
extern char *vsbCmd;
extern char vsbCmdBuf[];
extern long vdot;
extern TYR vtyDot[];
extern int viln;
extern int vslop;
extern char * EatCmdList();
extern char * SbFEob ();
extern FLAGT FDoCommand ();
extern int viopMac;
extern int vivarMac;
extern FLAGT FValFTok ();
extern TKE TkFExpr ();
extern long GetExpr ();
extern int ImdFIpd ();
extern int IpdFAdr ();
extern int IpdFName ();
extern int IfdFOpen ();
extern int IfdFAdr ();
extern int IfdFName ();
extern int IfdFIpd ();
extern int vcNest;
extern int IncFTyMode ();
extern char *sccsid;
extern char *sccsid;
extern char *sccsid;
extern char *sccsid;
extern char *vsbErrSinSD;
extern char *vsbErrSinSDD;
extern char *vsbErrSfailSD;
extern char *vsbErrNoChild;
extern char *vsbCmdsIgnored;
extern char * Malloc ();
extern int vibp;
extern int IbpFMachInst();
extern int IbpFRun ();
extern pADR vrgAd;
extern int viadMac;
extern int viadMax;
extern ASE vas;
extern FLAGT vfRunAssert;
extern ADRT AdrFStackFix ();
extern int IbpFSingle ();
extern long vcbSltFirst;
extern long visltMax;
extern long vislt;
extern pSLTR vsltCur;
extern FLAGT FNextSlt ();
extern ADRT AdrFIslt ();
extern long IsltFIsym ();
extern ADRT AdrFIsym ();
extern pFDR vrgFd;
extern int vifdMac;
extern int vifd;
extern pPDR vrgPd;
extern int vipdMac;
extern int vipd;
extern pMDR vrgMd;
extern int vimdMac;
extern long vcbSymFirst;
extern pSYMR vsymCur;
extern long visym;
extern long visymLim;
extern long visymMax;
extern long visymGlobal;
extern long vipxdbheader;
extern long vipdfdmd;
extern char *vsbSymfile;
extern int vfnSym;
extern int vcbSbFirst;
extern int vcbSbCache;
extern FLAGT FSbCmp ();
extern FLAGT FHdrCmp ();
extern FLAGT FNextSym ();
extern int IlnFIsym ();
extern FLAGT FNextVar ();
extern ADRT AdrFIfdLn ();
extern char * NameFCurSym ();
extern FLAGT FNameCmp ();
extern int vcbTok;
extern int vcbPeek;
extern TKE vtk;
extern TKE vtkPeek;
extern char vsbTok  [];
extern char vsbPeek [];
extern  ushort  fWhiteSpace;
extern char ChFEscape ();
extern TKE TkFStr ();
extern TKE TkPeek();
extern TKE TkNext();
extern pTYR vtyZeros;
extern pTYR vtyCnChar;
extern pTYR vtyCnInt;
extern pTYR vtyLong;
extern pTYR vtyCnDouble;
extern SBT SbSafe ();
extern int TqFTy ();
extern int CbFTy ();
extern long IsymFNextTqSym ();
extern int vilvMax;
extern ADRT AdrFReg ();
extern ADRT AdrFField ();
extern ADRT AdrFLocal ();
extern ADRT AdrFGlobal ();
