default:
	:

install:
	mkdir -p ../../../Filesets.sl/ACCOUNTNG/system/ACCOUNTNG
	! cp ACCOUNTNG.dcst ../../../Filesets.sl/ACCOUNTNG/system/ACCOUNTNG/decustomize
	! chmog 544 bin bin ../../../Filesets.sl/ACCOUNTNG/system/ACCOUNTNG/decustomize
	! chmog 555 bin bin ../../../Filesets.sl/ACCOUNTNG/system/ACCOUNTNG
	! chmog 555 bin bin ../../../Filesets.sl/ACCOUNTNG/system
	! chmog 555 bin bin ../../../Filesets.sl/ACCOUNTNG
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/AUDIT/system/AUDIT
	! cp AUDIT.dcst ../../../Filesets.sl/AUDIT/system/AUDIT/decustomize
	! chmog 544 bin bin ../../../Filesets.sl/AUDIT/system/AUDIT/decustomize
	! chmog 555 bin bin ../../../Filesets.sl/AUDIT/system/AUDIT
	! chmog 555 bin bin ../../../Filesets.sl/AUDIT/system
	! chmog 555 bin bin ../../../Filesets.sl/AUDIT
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/C-MIN/system/C-MIN
	! cp C-MIN.dcst ../../../Filesets.sl/C-MIN/system/C-MIN/decustomize
	! chmog 544 bin bin ../../../Filesets.sl/C-MIN/system/C-MIN/decustomize
	! chmog 555 bin bin ../../../Filesets.sl/C-MIN/system/C-MIN
	! chmog 555 bin bin ../../../Filesets.sl/C-MIN/system
	! chmog 555 bin bin ../../../Filesets.sl/C-MIN
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/C-TOOLS/system/C-TOOLS
	! cp C-TOOLS.dcst ../../../Filesets.sl/C-TOOLS/system/C-TOOLS/decustomize
	! chmog 544 bin bin ../../../Filesets.sl/C-TOOLS/system/C-TOOLS/decustomize
	! chmog 555 bin bin ../../../Filesets.sl/C-TOOLS/system/C-TOOLS
	! chmog 555 bin bin ../../../Filesets.sl/C-TOOLS/system
	! chmog 555 bin bin ../../../Filesets.sl/C-TOOLS
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/C/system/C
	! cp C.dcst ../../../Filesets.sl/C/system/C/decustomize
	! chmog 544 bin bin ../../../Filesets.sl/C/system/C/decustomize
	! chmog 555 bin bin ../../../Filesets.sl/C/system/C
	! chmog 555 bin bin ../../../Filesets.sl/C/system
	! chmog 555 bin bin ../../../Filesets.sl/C
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/CMDS-AUX/system/CMDS-AUX
	! cp CMDS-AUX.dcst ../../../Filesets.sl/CMDS-AUX/system/CMDS-AUX/decustomize
	! chmog 544 bin bin ../../../Filesets.sl/CMDS-AUX/system/CMDS-AUX/decustomize
	! chmog 555 bin bin ../../../Filesets.sl/CMDS-AUX/system/CMDS-AUX
	! chmog 555 bin bin ../../../Filesets.sl/CMDS-AUX/system
	! chmog 555 bin bin ../../../Filesets.sl/CMDS-AUX
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/CMDS-MIN/system/CMDS-MIN
	! cp CMDS-MIN.dcst ../../../Filesets.sl/CMDS-MIN/system/CMDS-MIN/decustomize
	! chmog 544 bin bin ../../../Filesets.sl/CMDS-MIN/system/CMDS-MIN/decustomize
	! chmog 555 bin bin ../../../Filesets.sl/CMDS-MIN/system/CMDS-MIN
	! chmog 555 bin bin ../../../Filesets.sl/CMDS-MIN/system
	! chmog 555 bin bin ../../../Filesets.sl/CMDS-MIN
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/CORE-SHLIBS/system/CORE-SHLIBS
	! cp CORE-SHLIBS.dcst ../../../Filesets.sl/CORE-SHLIBS/system/CORE-SHLIBS/decustomize
	! chmog 544 bin bin ../../../Filesets.sl/CORE-SHLIBS/system/CORE-SHLIBS/decustomize
	! chmog 555 bin bin ../../../Filesets.sl/CORE-SHLIBS/system/CORE-SHLIBS
	! chmog 555 bin bin ../../../Filesets.sl/CORE-SHLIBS/system
	! chmog 555 bin bin ../../../Filesets.sl/CORE-SHLIBS
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/DISKLESS/system/DISKLESS
	! cp DISKLESS.dcst ../../../Filesets.sl/DISKLESS/system/DISKLESS/decustomize
	! chmog 544 bin bin ../../../Filesets.sl/DISKLESS/system/DISKLESS/decustomize
	! chmog 555 bin bin ../../../Filesets.sl/DISKLESS/system/DISKLESS
	! chmog 555 bin bin ../../../Filesets.sl/DISKLESS/system
	! chmog 555 bin bin ../../../Filesets.sl/DISKLESS
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/EDITORS/system/EDITORS
	! cp EDITORS.dcst ../../../Filesets.sl/EDITORS/system/EDITORS/decustomize
	! chmog 544 bin bin ../../../Filesets.sl/EDITORS/system/EDITORS/decustomize
	! chmog 555 bin bin ../../../Filesets.sl/EDITORS/system/EDITORS
	! chmog 555 bin bin ../../../Filesets.sl/EDITORS/system
	! chmog 555 bin bin ../../../Filesets.sl/EDITORS
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/LP-SPOOL/system/LP-SPOOL
	! cp LP-SPOOL.dcst ../../../Filesets.sl/LP-SPOOL/system/LP-SPOOL/decustomize
	! chmog 544 bin bin ../../../Filesets.sl/LP-SPOOL/system/LP-SPOOL/decustomize
	! chmog 555 bin bin ../../../Filesets.sl/LP-SPOOL/system/LP-SPOOL
	! chmog 555 bin bin ../../../Filesets.sl/LP-SPOOL/system
	! chmog 555 bin bin ../../../Filesets.sl/LP-SPOOL
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/MAILERS/system/MAILERS
	! cp MAILERS.dcst ../../../Filesets.sl/MAILERS/system/MAILERS/decustomize
	! chmog 544 bin bin ../../../Filesets.sl/MAILERS/system/MAILERS/decustomize
	! chmog 555 bin bin ../../../Filesets.sl/MAILERS/system/MAILERS
	! chmog 555 bin bin ../../../Filesets.sl/MAILERS/system
	! chmog 555 bin bin ../../../Filesets.sl/MAILERS
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/PROG-AUX/system/PROG-AUX
	! cp PROG-AUX.dcst ../../../Filesets.sl/PROG-AUX/system/PROG-AUX/decustomize
	! chmog 544 bin bin ../../../Filesets.sl/PROG-AUX/system/PROG-AUX/decustomize
	! chmog 555 bin bin ../../../Filesets.sl/PROG-AUX/system/PROG-AUX
	! chmog 555 bin bin ../../../Filesets.sl/PROG-AUX/system
	! chmog 555 bin bin ../../../Filesets.sl/PROG-AUX
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/RBOOTD/system/RBOOTD
	! cp RBOOTD.dcst ../../../Filesets.sl/RBOOTD/system/RBOOTD/decustomize
	! chmog 544 bin bin ../../../Filesets.sl/RBOOTD/system/RBOOTD/decustomize
	! chmog 555 bin bin ../../../Filesets.sl/RBOOTD/system/RBOOTD
	! chmog 555 bin bin ../../../Filesets.sl/RBOOTD/system
	! chmog 555 bin bin ../../../Filesets.sl/RBOOTD
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/SPELL/system/SPELL
	! cp SPELL.dcst ../../../Filesets.sl/SPELL/system/SPELL/decustomize
	! chmog 544 bin bin ../../../Filesets.sl/SPELL/system/SPELL/decustomize
	! chmog 555 bin bin ../../../Filesets.sl/SPELL/system/SPELL
	! chmog 555 bin bin ../../../Filesets.sl/SPELL/system
	! chmog 555 bin bin ../../../Filesets.sl/SPELL
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/SYS-ADMIN/system/SYS-ADMIN
	! cp SYS-ADMIN.dcst ../../../Filesets.sl/SYS-ADMIN/system/SYS-ADMIN/decustomize
	! chmog 544 bin bin ../../../Filesets.sl/SYS-ADMIN/system/SYS-ADMIN/decustomize
	! chmog 555 bin bin ../../../Filesets.sl/SYS-ADMIN/system/SYS-ADMIN
	! chmog 555 bin bin ../../../Filesets.sl/SYS-ADMIN/system
	! chmog 555 bin bin ../../../Filesets.sl/SYS-ADMIN
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/UNSUPP/system/UNSUPP
	! cp UNSUPP.dcst ../../../Filesets.sl/UNSUPP/system/UNSUPP/decustomize
	! chmog 544 bin bin ../../../Filesets.sl/UNSUPP/system/UNSUPP/decustomize
	! chmog 555 bin bin ../../../Filesets.sl/UNSUPP/system/UNSUPP
	! chmog 555 bin bin ../../../Filesets.sl/UNSUPP/system
	! chmog 555 bin bin ../../../Filesets.sl/UNSUPP
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/USRCONTRB/system/USRCONTRB
	! cp USRCONTRB.dcst ../../../Filesets.sl/USRCONTRB/system/USRCONTRB/decustomize
	! chmog 544 bin bin ../../../Filesets.sl/USRCONTRB/system/USRCONTRB/decustomize
	! chmog 555 bin bin ../../../Filesets.sl/USRCONTRB/system/USRCONTRB
	! chmog 555 bin bin ../../../Filesets.sl/USRCONTRB/system
	! chmog 555 bin bin ../../../Filesets.sl/USRCONTRB
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/UUCP/system/UUCP
	! cp UUCP.dcst ../../../Filesets.sl/UUCP/system/UUCP/decustomize
	! chmog 544 bin bin ../../../Filesets.sl/UUCP/system/UUCP/decustomize
	! chmog 555 bin bin ../../../Filesets.sl/UUCP/system/UUCP
	! chmog 555 bin bin ../../../Filesets.sl/UUCP/system
	! chmog 555 bin bin ../../../Filesets.sl/UUCP
	! chmog 555 bin bin ../../../Filesets.sl
	mkdir -p ../../../Filesets.sl/UX-CORE/system/UX-CORE
	! cp UX-CORE.dcst ../../../Filesets.sl/UX-CORE/system/UX-CORE/decustomize
	! chmog 544 bin bin ../../../Filesets.sl/UX-CORE/system/UX-CORE/decustomize
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE/system/UX-CORE
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE/system
	! chmog 555 bin bin ../../../Filesets.sl/UX-CORE
	! chmog 555 bin bin ../../../Filesets.sl
