#define         dpp_c_error_bad_parameter               0
#define         dpp_c_no_dpp_file                       1
#define         dpp_c_bad_dpp_file                      2
#define         dpp_c_no_log_file                       3
#define         dpp_c_cannot_create_log_file            4
#define         dpp_c_cannot_access_log_file            5
#define         dpp_c_no_ocd_program                    6
#define         dpp_c_cannot_execute_ocd_program        7
#define         dpp_c_cannot_purge_device_file          8
#define         dpp_c_cannot_execute_default_ocd        9
#define         dpp_c_bad_ip_address                    10
#define         dpp_c_bad_port                          11
#define         dpp_c_bad_board                         12
#define         dpp_c_bad_device_name                   13
#define         dpp_c_bad_config_file_name              14
#define         dpp_c_cannot_create_process             15
#define         dpp_c_port_board_missing                16
#define         dpp_c_device_name_missing               17
#define         dpp_c_too_many_login_entries            30
#define         dpp_c_cannot_access_dpp_login_file      31
