$set 1
1 %4h %2d %H:%M 19%y
2 ar: bad option `%c'\n
3 ar: one of [%s] must be specified\n
4 ar: only one of [%s] allowed\n
5 ar: cannot open %s\n
6 ar: %s cannot create\n
7 ar: cannot create third temp\n
8 ar: abi not allowed with q\n
9 ar: %s cannot open\n
10 ar: cannot create temp file\n
11 ar: %s not in archive format\n
12 ar: %s cannot seek\n
13 ar: creating %s\n
14 ar: cannot create %s\n
15 ar: %s not in archive format\n
16 usage: ar [%s][%s] [posname] archive files ...\n
17 ar: %s does not exist\n
18 ar: %s not found\n
19 ar: %s cannot open\n
20 ar: creating %s\n
21 ar: cannot create %s\n
22 optional acl entries for %s not archived\n
23 ar: %s internal header generation error\n
24 ar: malformed archive (at %ld)\n
25 ar: %s bad header layout for %s\n
26 ar: cannot create second temp\n
27 ar: phase error on %s\n
28 ar write error
