$set 1
1 because your login shell isn't /bin/sh, you can't use at
2 warning: commands will be executed using /bin/sh\n
3 can't change directory to the at directory
4 can't change the owner of your job to you
5 can't create a job for you
6 you are not a valid user (no entry in /etc/passwd)
7 proper syntax is:\n\tat -ln\nwhere n is a number
8 can't read the at directory
9 you are not authorized to use at.  Sorry.
10 nothing specified
11 it's past that time
12 %s does not exist\n
13 you don't own %s\n
14 invalid job name %s\n
15 %s does not exist\n
16 you don't own %s\n
17 open '%s' failed, errno=%d\n
18 too late
19 At: this job may not be executed at the proper time.\n
20 queue full
21 no prototype
22 cron may not be running - call your system administrator\n
23 error in message queue open\n
24 error in message send\n
25 can't use c queue 
26 Usage:\nat [-m][-f file][-qqueue] time [date][[next| +increment] time_designation] job\nat -r job ...\nat -l [job ...]\n
28 unable to open \'%s\'\n
29 Unable to open pipe to mail\n
30 At: job %s at %.44s\n
32 user = %s\t%s\t%s\n
$set 2
1 cannot allocate %d byte of space\n
$set 3
1 noon
2 midnight
3 now
4 today
5 tomorrow
6 minute
7 minutes
8 hour
9 hours
10 day
11 days
12 week
13 weeks
14 month
15 months
16 year
17 years
18 next
21 bad date specification
22 bad time specification
23 hours field is invalid
24 bad date
25 bad time
26 bad NLS environment
27 the date argument is ambiguous
28 bad catalogue file
