$set 1
1 only one of -F or -f allowed\n
2 only one of -F or -f allowed\n
3 only one of -P or -p allowed\n
4 only one of -P or -p allowed\n
5 mark_ev(%d) failed\n
6 '%c': event argument missing\n
7 unknown event: %s\n
8 mark_ev(%d) failed\n
9 mark_sc(%d) failed\n
10 '%c': syscall argument missing\n
11 unknown syscall: %s\n
12 mark_sc(%d) failed\n
13 '%c': unknown option\n
21 Not superuser.\n
22 audswitch(AUD_SUSPEND) failed: %s\n
23 mark_ev(%d) failed\n
24 unknown argument: %s\n
25 show_audit() failed\n
26 set_audit() failed\n
31 mark_sc(%d) failed\n
41 audwrite(%s) failed: %s\n
42 getevent() failed: %s\n
43 set_event(%s) failed\n
44 set_syscall(%d) failed\n
45 audwrite(%s) failed: %s\n
46 setevent() failed: %s\n
51 audwrite(%s) failed: %s\n
52 getevent() failed: %s\n
53 show_event(%s) failed\n
61 usage: %s
