$set 1
1  at source line %d
2  context is\n\t
3  in function %s
4  input record number %g
5  source line number %d\n
6 %s argument out of domain
7 %s is a function, not an array
8 %s is an array, not a function
9 %s is not an array
10 %s makes too many open files
11 %s result out of range
12 , file %s
13 Usage: %s [-f source | 'cmds'] [files]
14 \t%d extra %c's\n
15 \t%d missing %c's\n
16 \textra %c\n
17 \tmissing %c\n
18 `%s' is an array name and a function name
19 argument #%d of function %s was not supplied
20 bad format string in printf(%s)
21 bailing out
22 built giant record `%.20s...'
23 calling undefined function %s
24 can't %s %s; it's a function.
25 can't %s %s; it's an array name.
26 can't open %s
27 can't open file %s
28 can't use function %s as argument
29 creating too many fields
30 division by zero in %=
31 division by zero in /=
32 division by zero in mod
33 division by zero
34 empty regular expression
35 empty restore file\n
36 extra )
37 extra ]
38 extra }
39 floating point exception
40 format item %.20s... too long
41 out of space for stack frames in %s
42 funny variable %o: n=%s s="%s" f=%g t=%o
43 gsub() result %.20s too big
44 illegal arithmetic operator %d
45 illegal assignment operator %d
46 illegal field $(%s)
47 illegal function type %d
48 illegal jump type %d
49 illegal nested function
50 illegal primary in regular expression %s at %s
51 illegal redirection
52 illegal reference to array %s
53 illegal statement
54 illegal type of split()
55 index() doesn't permit regular expressions
56 input record `%.20s...' too long
57 newline in character class %s...
58 newline in regular expression %.10s...
59 newline in string %.10s...
60 next is illegal inside a function
61 no space for temporaries
62 nonterminated character class %s
63 not enough args in printf(%s)
64 not enough arguments in printf(%s)
65 not restored\n
66 not saved\n
67 null file name in print or getline
68 out of space in makesymtab
69 out of space in nodealloc
70 out of space in rehash
71 out of space in tostring on %s
72 record `%.20s...' has too many fields
73 regular expression too big: %s
74 return not in function
75 string %.10s... too long
76 string too long
77 string/reg expr %.10s... too long
78 sub() result %.20s too big
79 symbol table overflow at %s
80 syntax error in regular expression %s at %s
81 trying to access field %d
82 unexpected break or next
83 unexpected break, continue or next
84 unknown boolean operator %d
85 unknown relational operator %d
86 unknown type %d in cfoll
87 unknown type %d in first\n
88 unknown type %d in freetr
89 unknown type %d in penter\n
90 you can't define function %s more than once
91  input record number %g
92 , file %s
93  source line number %d\n
94  context is\n\t
95  at source line %d
96  in function %s
97 \tmissing %c\n
98 \t%d missing %c's\n
99 \textra %c\n
100 \t%d extra %c's\n
101 invalid collation element referenced\n
102 trailing \\ in pattern\n
103 \\n found before end of pattern\n
104 nesting level too deep\n
105 number in \\digit invalid or in error\n
106 [ ] imbalance\n
107 \\( \\) or ( ) imbalance\n
108 \\{ \\} imbalance\n
109 invalid endpoint in range statement\n
110 out of memory for compiled pattern\n
111 number too large in \\{ \\} construct\n
112 invalid number in \\{ \\} construct\n
113 more than two numbers in \\{ \\} construct\n
114 first number exceeds second in \\{ \\} construct\n
115 invalid character class type named\n
116 no remembered search string\n
117 duplication operator in illegal position\n
118 no expression within ( ) or on one side of an |\n
119 you can only delete array[element]\n
120 no program given\n
121 out of space for stack frames calling %s\n
122 function %s called with %d args, uses only %d\n
123 function %s has %d arguments, limit %d\n
124 tempcell list is curdled\n
125 printf string %.40s... too long\n
126 out of space concatenating %.15s and %.15s\n
127 atan2 requires two arguments; returning 1.0\n
128 warning: function has too many arguments\n
129 i/o error occurred on %s\n
130 i/o error occurred closing %s\n
131 too many program files: Ignoring: %s\n
