$set 1
2 chmod: can't access %s\n
3 chmod: can't change 
4 chmod: invalid mode\n
5 chmod: -A option not allowed on remote file: %s\n
6 chmod: can't traverse %s\n
7 chmod: %s not a directory\n
101 Usage: chmod [-A] [-R] [ugoa]+-=[rwxXstHugo][,...] file ...\n
102 Usage: chmod [-R] [ugoa]+-=[rwxXstHugo][,...] file ...\n
103 Usage: chmod [-A] [-R] [ugoa]+-=[rwxXstugo][,...] file ...\n
104 Usage: chmod [-R] [ugoa]+-=[rwxXstugo][,...] file ...\n
