$set 1
1 cnodes: malloc error\n
2 cnodes: malloc error\n
3 Usage: %s -aAnlmxC1sr [names]\n
4 cnodes: can't read /etc/clusterconf\n
5 cnodes: cnode_id %d: Machine does not exist\n
6 cnodes: %s: Machine is not clustered\n
7 cnodes: %s: Machine does not exist\n
8 cnodes: malloc failed\n
9 <not found>
10 CNODE       ID SWAP SITE\n========== === ==========
11  ID CNODE      SWAP SITE\n=== ========== ==========
