$set 1
1 Usage:\tcp [-f|-i] [-p] source_file target_file\n\tcp [-f|-i] [-p] source_file ... target_directory\n\tcp [-f|-i] [-p] -R|-r source_directory ... target_directory\n
2 cp: couldn't unlink %s: 
3 cp: cannot access %s: 
4 cp: <%s> directory.  Need "-R" option.\n
5 cp: %s/%s: Name too long\n
6 cp: %s and %s are identical\n
7 cp: %s: Not a directory.\n
9 cp: cannot create %s: 
10 cp: cannot open 
11 cp: cannot create %s: 
12 cp: bad copy to %s: 
13 cp: cannot close %s: 
14 cp: cannot set the permission bits on %s: 
15 cp: %s/%s: Name too long.\n
16 cp: cannot mkrnod 
17 cp: cannot symlink 
18 cp: cannot readlink 
19 cp: utime failed %s: 
20 cp: chown failed %s: 
21 warning: skipped socket: %s\n
22 cp: Warning: cannot cpacl to %s\n
23 cp: Warning: cannot cpacl to %s\n
24 link failed
25 overwrite %s? 
26 cp: %s: not a directory\n
27 cp: cannot access ACL on %s: 
28 cp: cannot allocate %d entry ACL for %s: 
29 cp: cannot read ACL on %s: 
