$set 1
2 cannot write in <%s>\n
3 Cannot rename (/dev/tty missing)\n
4 Options must include o|i|p\n
5 `R' option is irrelevant with the '-%c' option\n
7 `B' option is irrelevant with the '-p' option\n
10 Cannot read %s\n
11 Cannot read %s\n
12 warning: contents of %s are corrupt on archive\n
13 Cannot write %s\n
14 Cannot chmod <%s> (errno:%d)\n
15 Use `-d' option to copy <%s>\n
16 Cannot link <%s> & <%s> (errno:%d)\n
17 Cannot link <%s> & <%s> (errno:%d)\n
18 Cannot create directory for <%s> (errno:%d)\n
19 Cannot link <%s> & <%s> (errno:%d)\n
20 Cannot chmod <%s> (errno:%d)\n
21 Cannot read %s\n
22 Cannot write %s\n
23 Cannot chmod <%s> (errno:%d)\n
24 cpio: Unable to restore at least %d file.\n
25 cpio: Unable to restore at least %d files.\n
26 %ld blocks\n
27 Usage: cpio -o[aAcBvxCh] <name-list >collection\n
28        cpio -i[BcdmPrtuvfsSbx6RU] [pattern ...] <collection\n
29        cpio -p[adlmruvxU] directory <name-list\n\n
30 cpio: Re-synced after skipping %d byte.\n
31 cpio: Re-synced after skipping %d bytes.\n
32 cpio: Out of phase; resyncing.\n
33 cpio: Re-synced after skipping %d bytes.\n
34 cpio: Out of phase; resyncing.\n
35 Out of phase--get help\n
36 You may want to use "R" option\n
37 Perhaps the "-c" option shouldn't be used\n
38 Perhaps the "-c" option should be used\n
39 Out of phase--get RT help\n
40 Perhaps the "-c" option should be used\n
41 Rename <%s>\n
42 Skipped\n
43 Cannot create directory for <%s> (errno:%d)\n
44 Cannot create directory <%s> (errno:%d)\n
45 Cannot chmod <%s> (errno:%d)\n
46 Cannot chown <%s> (errno:%d)\n
47 cannot unlink current <%s> (errno:%d)\n
48 current <%s> newer\n
49 Attempt to pass file to self!\n
50 Cannot mknod <%s> (errno:%d)\n
51 Cannot create directory for <%s> (errno:%d)\n
52 Cannot mknod <%s> (errno:%d)\n
53 Cannot chmod <%s> (errno:%d)\n
54 Cannot chown <%s> (errno:%d)\n
55 Cannot open <%s> (errno:%d)\n
56 Cannot create directory for <%s> (errno:%d)\n
57 Cannot create <%s> (errno:%d)\n
58 Cannot create contiguous file <%s> proper size\n
59     <%s> will be created as a regular file\n
60 <%s> not removed\n
61 Cannot create link for <%s> (errno:%d)\n
62 Cannot create link <%s> (errno:%d)\n
64 Cannot chown <%s> (errno:%d)\n
65 Cannot create directory for <%s> (errno:%d)\n
66 Cannot create <%s> (errno:%d)\n
67 Cannot link this file: %s\n
68 %s and %s are same file!\n
69 %s linked to %s\n
70 Cannot create directory for <%s> (errno:%d)\n
71 Cannot link <%s> & <%s> (errno:%d)\n
73 No memory for links\n
76 Cannot chown <%s> (errno:%d)\n
77 Can't open /dev/tty to prompt for more media.\n
79 End of volume\n
81 errno: %d, 
82 Can't write output\n
83 Can't read input\n
84 If you want to go on, type device/file name when ready\n
85 User entered a null name for next device file.\n
86 That didn't work.\n
87 User opened file %s to continue.\n
88 missing 'd' option\n
89 Cannot chdir (no `d' option)\n
90 Cannot chdir - no write permission\n
91 Cannot chdir\n
92 cpio: can't get current working directory: 
93 cpio: Too many patterns on command line (max=%d).\n
94 `C' option is irrelevant with the '-%c' option\n
95 Can't create temporary file for file name list.\n
96 %s\n
97 Cannot open <%s>.\n
98 %s\n
99 unexpected write state: CHECKPT\n
100 Unknown write state (%d).\n
101 Cannot stat <%s>.\n
102 unexpected write state: CHECKPT\n
103 Unknown write state (%d).\n
104 Unknown part (%d).\n
105 Can't open /dev/tty.\n
106 %3h %2d %H:%M:%S 19%y
107 The file "TRAILER!!!" was not backed up.\n
108 Optional acl entries for <%s> are not backed up.\n
109 Obsolete network special file <%s> not backed up\n
110 Mount a new tape to rewrite reel #%d.\n
111 (Using tape drive with immediate report mode enabled (reel #%d).)\n
112 Socket <%s> not backed up\n
113 Skipped obsolete network special file <%s>\n
