$set 1
1 token too long
2 %s: unterminated macro call
3 Unexpected EOF in comment
4 Problems with writing output file; probably out of temp space
5 missing #endif statement(s)
6 (NLS) illegal second byte in 16-bit character
7 (NLS) illegal second byte in 16-bit character
8 %s: too much pushback
9 no space
10 token too long
11 bad include syntax
12 Unreasonable include nesting
13 no space
14 Can't find include file %s
15 too much defining
16 illegal macro name
17 %s: missing )
18 bad formal: %s
19 too many formals: %s
20 %s redefined
21 If-less endif
22 If-less else
23  IF not implemented, true assumed
24 bad number for #line
25 bad file for #line
26 bad file for #line
27 undefined preprocessor directive
28  (in preprocessor if)
29 too many defines
30 %s: macro recursion
31 %s: actuals too long
33 %s: argument mismatch
36 Can't open %s\n
37 too many -D options, ignoring %s
38 too many -U options, ignoring %s
39 excessive -I file (%s) ignored
40 missing table size after -H option, -H option ignored
41 Invalid define table size specified
42 unknown flag %s
43 No source file %s
44 Can't create %s
45 extraneous name %s
46 command line
47 Problems with output file; probably out of temp space
48 Can't allocate define table
49 Can't allocate symbol table 
50 Can't allocate object file
51 Access permission denied for %s
52 Pathname too long for file %s
53 System File Table full.  Can't open %s
54 Invalid Pathname for %s
55 Can't open %s
56 excessive -y file (%s) ignored
57 excessive -p file (%s) ignored
30003 syntax error
$set 2
1 Illegal character %c in preprocessor if
2 "defined" modifying non-identifier "%s" in preprocessor if
3 Illegal number %s
54 division by zero
30001 syntax error - cannot backup
30002 yacc stack overflow
30003 syntax error
30004 unable to allocate space for yacc stacks
