$set 1
1 can't change directory to the crontab directory.
2 can't read the crontab directory.
3 unable to read your at job.
4 because your login shell isn't /bin/sh, you can't use cron.
5 can't access your crontab file.  Resubmit it.
6 can't change directory to your home directory.\nYour commands will not be executed.
7 unable to exec the shell for one of your commands.
8 unexpected end of line
9 can't read your crontab file.  Resubmit it.
10 unable to create a standard input file for one of your crontab commands.\nThat command was not executed.
11 number too large or too small for field
12 \n\n*************************************************\nCron: The previous message is the standard output\n      and standard error of one of your cron commands.\n\n
13 \n\n*************************************************\nCron: The previous message is the standard output\n      and standard error of one of your crontab commands:\n\n
14 \n\n*************************************************\nCron: The previous message is the standard output\n      and standard error of one of your at commands.\n\n
15 one of your commands generated output or errors, but cron was unable to mail you this output.\nRemember to redirect standard output and standard error for each of your commands.
16 unexpected symbol found
17 *** cron started ***   pid = %d
18 cannot stat QUEDEFS file
19 cannot access fifo queue
20 cannot create fifo queue
21 cron is already running
22 cannot open %s\n
23 cannot chdir to at directory
24 cannot read at directory
25 Your crontab file has an error in it.\n
26 This entry has been ignored.\n
27 %c queue max run limit reached
28 MAXRUN (%d) procs reached
29 ATLIMIT (%d) reached for uid %d
30 CRONLIMIT (%d) reached for uid %d
31 cannot fork
32 unexpected pid returned %d (ignored)
33 cannot stat fifo queue
34 message received - bad format
35 cron aborted: 
36 ******* CRON ABORTED ********
37 rescheduling a cron job
38 rescheduling at job
39 cannot open quedefs file
40 using default queue definitions
69 Your job did not contain a valid audit ID.\nSee your system administrator.\n
$set 2
1 cannot allocate %d byte of space\n
