$set 1
1 can't create your crontab file in the crontab directory.
2 can't open your crontab file.
3 because your login shell isn't /bin/sh, you can't use cron.
4 warning: commands will be executed using /bin/sh\n
5 proper usage is: \n\tcrontab [file]\n\tcrontab [-r]\n\tcrontab [-l]
6 you are not a valid user (no entry in /etc/passwd).
7 you are not authorized to use cron.  Sorry.
8 unexpected end of line.
9 unexpected character found in line.
10 number out of bounds.
11 %scrontab: error on previous line; %s\n
12 cron may not be running - call your system administrator\n
13 crontab: error in message queue open\n
14 crontab: error in message send\n
$set 2
1 cannot allocate %d byte of space\n
