$set 1
1 assertion botched: %s\n
2 failed initial alloc err=%d\n
3 failed alloc of temp:%d WORD:%derr=%d\n
$set 2
1 getwd: cannot open ..\n
2 getwd: read error in ..\n
3 getwd: read error in ..\n
4 getwd: can't change back\n
5 getwd: current directory name too long\n
$set 3
1 auto-logout\n
2 Warning: no access to tty; thus no job control in this shell...\n
3 logout\n
4 Interrupted
5 You have new mail.\n
6 You have mail.\n
7 New mail in %s.\n
8 Mail in %s.\n
9 %s: Not a regular file
10 Too few arguments
11 Too many arguments
$set 4
1 Usage: dirs [ -l ]
2 No home directory
3 Can't change to home directory
4 No other directory
5 Directory stack not that deep
6 Bad directory
7 Directory stack empty
8 Directory %s doesn't exist, removed from stack
$set 5
1 Ambiguous
2 Unmatched %c
3 Word too long
4 $< line too long
5 No file for $0
6 Variable syntax
7 Subscript out of range
8 Bad : mod in $
9 << terminator not found
10 Line overflow
11 Line overflow
$set 6
1 No match
2 Command not found
3 %d hits, %d misses, %2d%%\n
4 %s: Executable file incompatible with hardware
$set 7
1 Divide by 0
2 Mod by 0
3 Expression syntax
4 Missing }
5 Missing file name
6 Expression syntax
$set 8
1 Too few arguments
2 Too many arguments
3 Can't from terminal
4 Can't from terminal
5 Too dangerous to alias that
6 Password:
7 name and password too long
8 invalid remote login.  errnet = %d\n
9 network error
10 remote node not answering.  errnet = %d\n
11 network error
12 errnet = %d\n
13 network error
14 invalid network special file.  errno = %d\n
15 Not login shell
16 Empty if
17 Improper then
18 Syntax error
19 Not in while/foreach
20 Expression syntax
21 Invalid variable
22 Words not ()'ed
23 No match
24 Expression syntax
25 Not in while/foreach
26 Not in while/foreach
27 then/endif not found
28 endif not found
29 endsw not found
30 end not found
31 label not found
32 No match
33 Improper mask
34 Can't suspend a login shell (yet)
35 No match
36 network not supported\n
$set 9
2 Missing ]
3 Missing }
4 Missing ]
5 Missing ]
7 Arguments too long
8 Pathname too long
9 No match
10 Ambiguous
11 Unmatched `
12 Word too long
13 Too many words from ``
14 Invalid pattern
$set 10
1 Unmatched 
2 Word too long
3 Variable syntax
4 Expansion buf ovflo
5 Bad ! form
6 No prev sub
7 Bad substitute
8 No prev lhs
9 Rhs too long
10 Bad ! modifier: 
11 Modifier failed
12 Subst buf ovflo
13 Bad ! arg selector
14 No prev search
15 : Event not found
16 Reset tty pgrp from %d to %d\n
17 \nUse "logout" to logout.\n
18 \nUse "exit" to leave csh.\n
19 Reset tty pgrp to %d\n
$set 11
1 Out of memory
2 Undefined variable
3 to_short ran out of space
4 Exceeded to_char space\n
$set 12
1 Alias loop
2 Too many )'s
3 Too many )'s
4 Too many ('s
5 Badly placed (
6 Missing name for redirect
7 Ambiguous output redirect
8 Can't << within ()'s
9 Ambiguous input redirect
10 Badly placed ()'s
11 Invalid null command
$set 13
1 Hangup
2 Interrupt
3 Quit
4 Illegal instruction
5 Trace/BPT trap
6 IOT trap
7 EMT trap
8 Floating exception
9 Killed
10 Bus error
11 Segmentation fault
12 Bad system call
13 Broken pipe
14 Alarm clock
15 Terminated
16 Signal 16
17 Signal 17
18 Child exited
19 Power-fail restart
20 Virtual Timer Alarm
21 Profiling Timer Alarm
22 Async I/O Signal
23 Window Signal
24 Stopped
25 Stopped
26 Continued
27 Stopped (tty input)
28 Stopped (tty output)
29 Signal 29
30 Signal 30
31 Signal 31
32 Signal 32
41 BUG: waiting for background job!\n
42 BUG: process flushed twice
43 Running 
44 Exit %-16d
45 Done
46 BUG: status=%-9o
47  (core dumped)
48  (wd: 
49 (wd now: 
50 Usage: jobs [ -l ]
51 Bad signal number
52 Unknown signal; kill -l lists signals
53 %s: Already stopped\n
54 Arguments should be jobs or process id's
55 \nThere are stopped jobs
56 No current job
57 No previous job
58 No such job
60 No job matches pattern
61 No such job
$set 14
4 Can't make pipe
5 %s: File exists
$set 15
1 Syntax error
2 Missing )
3 Subscript error
4 Subscript out of range
5 Syntax error
6 Expression syntax
7 Badly formed number
8 No match
9 No more words
10 Warning: ridiculously long PATH truncated\n
11 "home" must be an absolute path
$set 16
1 \nYikes!! Too many names in passwd file!!\n
2 \nYikes!! Too many files!!\n
3 out of mem\n
$set 17
1 .\n
