$set 1
1 usage: %s [-s baud] [-l line] [-h] [-n] [-t] [-d level] [-m] [-o|-e] telno | 'dir' | remote\n
2 interrupt
3 dialer hung
4 no answer
5 illegal baud-rate
6 acu problem
7 line problem
8 can't open L-devices file
9 can't open Devices file
10 Requested device not available\r\n
11 Requested device/system name not known\r\n
12 No device available at %d baud\r\n
13 No device known at %d baud\r\n
14 Connect failed: %s\r\n
15 Cannot open: %s\r\n
16 Line gone\r\n
17 Can't execute shell\r\n
18 Can't divert %s\r\n
19 Use `~~' to start line with `~'\r\n
20 character missed\r\n
21 after %ld bytes\r\n
22 %d lines/%ld characters\r\n
23 File transmission interrupted\r\n
24 Cannot fork -- try later\r\n
25 \r\nCan't transmit special character `%#o'\r\n
26 \nLine too long\r\n
27 r\nIO error\r\n
28 Use `~$'cmd \r\n
29 Cannot obtain status of the terminal\r\n
30 Sorry you cannot cu from 3B console\r\n
31 requested speed does not match\r\n
32 requested system name not known\r\n
33 Cu not compiled with debugging flag\r\n
34 Please enter the number: 
35 Autodialing - please wait\r\n
36 Cannot get the status of the device
37 Cannot chown on %s\n
38 Cannot chmod on %s\n
39 Cannot set the uid %d\n
40 Connected\007\r\n
41 Exec of '%s' failed\r\n
42 transmit started\n\r
43 got break in transmit\n\r
44 got a tintr\n\r
46 call tilde(%s)\r\n
47 call shell(%s)\r\n
48 call dopercen("%s")\r\n
50 usage: ~%%take from [to]\r\n
55 usage: ~%%put from [to]\r\n
58 Could not open file %s\r\n
59 Input Diversion starting.\r\n
60 Input Diversion ended.\r\n
61 Prompt = \\%03o \\%03o\r\n
62 Timeout = %d s.\r\n
63 Line suffix = \\%03o \\%03o\r\n
64 Output Diversion ended.\r\n
65 No Output Diversion active.\r\n
66 Output Diversion ended.\r\n
67 Could not open file %s.\r\n
68 Starting Output Diversion.\r\n
69 Cannot change to %s\r\n
70 Cannot change to %s\r\n
71 ~%%%s unknown to cu\r\n
72 write failed\r\n
73 receive started\r\n
74 \r\nLost Carrier\r\n
75 call mode(%d)\r\n
76 Cannot set uid\r\n
77 Cannot set gid\r\n
79 got read error, not EINTR\n\r
80 read from fd=%d returned %d
81 got read error, not EINTR\n\r
82 \ncu: Output blocked\r\n
83 \ncu: Output blocked\r\n
84 call rcvdead(%d)\r\n
85 call quit(%d)\r\n
86 call bye(%d)\r\n
87 \r\nDisconnected\007\r\n
88 call hangup(%d)\r\n
89 Cannot chown/chmod on %s\n
90 \rdevice status for fd=%d\r\n
91 Local
92 cannot open Systems file\n
93 cannot open L.sys file\n
