$set 1
1 dd: bad arg %s\n
2 dd: cannot open %s\n
3 dd: can't copy file onto itself\n
4 dd: cannot create %s\n
5 dd: counts cannot be zero\n
6 dd: not enough memory\n
7 dd read error
8 I/O error \n
9 %u+%u records in\n
10 %u+%u records out\n
11 %u truncated records\n
12 \nERROR !! %s Section Size Exceeds 4GB !! \n
13 ioctl call to find disk size failed !!\n 
14 ioctl call to find block size failed !!\n 
