$set 1
1 diff: input file 
2 diff: -h doesn't support -e, -f, -n, -c, or -I\n
3 diff: out of memory\n
4 diff: files too big, try -h\n
5 Only in %.*s: %s\n
6 Common identical files in %.*s and %.*s\n
7 Binary files which differ in %.*s and %.*s\n
8 Common subdirectories of %.*s and %.*s\n
9 diff: directory 
10 Common subdirectories: %s and %s\n
11 Files %s and %s are identical\n
12 Binary files %s and %s differ\n
13 diff: exec 
14 diff: forking for pr: 
15 No differences encountered\n
16 diff: temporary input file 
18 diff: can't specify - with other arg directory\n
19 Warning : missing newline at end of file %s\n
21 diff: warning: shouldn't give -s or -l with -e\n
22 diff: forking for diff: 
23 diff: can't specify - -\n
24 File %s is a %s while file %s is a %s\n
25 character special
26 block special
27 FIFO special
28 regular
29 directory
30 unknown
