$set 1
1 usage : dumpmsg catfile\n
2 Open catalog file : %s\n
3 Close catalog file : %s\n
4 No messages in catalog file\n
5 dumpmsg: %s: Not a catalog file\n
6 %ld messages in catalog file\n
7 dumpmsg: %s: Bad catalog file\n
8 setnum : %d\n
9 msgnum : %d\n
10 length : %d\n
11 addr   : %d\n\n
12 dumpmsg: %s: Bad catalog file\n
13 setnum  : %d\n
14 msgnum  : %d\n
15 length  : %d\n
16 addr    : %d\n
17 message : %s\n\n
