$set 1
1 write or open on pipe failed
2 warning: expecting `w'
3 mark not lower case
4 cannot open input file
5 PWB spec problem
6 nothing to undo
7 restricted shell
8 cannot create output file
9 filesystem out of space!
10 cannot open file
11 cannot link
12 Range endpoint too large
13 unknown command
14 search string not found
15 -
16 line out of range
17 bad number
18 bad range
19 Illegal address count
20 incomplete global expression
21 illegal suffix
22 illegal or missing filename
23 no space after command
24 fork failed - try again
25 maximum of 64 characters in file names
26 `\\digit' out of range
27 interrupt
28 line too long
29 illegal character in input file
30 write error
31 out of memory for append
32 temp file too big
33 I/O error on temp file
34 multiple globals not allowed
35 global too long
36 no match
37 illegal or missing delimiter
38 -
39 replacement string too long
40 illegal move destination
41 -
42 no remembered search string
43 '\\( \\)' imbalance
44 Too many `\\(' s
45 more than 2 numbers given
46 '\\}' expected
47 first number exceeds second
48 incomplete substitute
49 newline unexpected
50 '[ ]' imbalance
51 regular expression overflow
52 regular expression error
53 command expected
54 a, i, or c not allowed in G
55 end of line expected
56 no remembered replacement string
57 no remembered command
58 illegal redirection
59 possible concurrent update
60 that command confuses yed
61 the x command has become X (upper case)
62 Warning: 'w' may destroy input file (due to `illegal char' read earlier)
63 Caution: 'q' may lose data in buffer; 'w' may destroy input file
65 -x option is not available
66 file name too long
67 this option is not available
68  nulls replaced by '\\0'
69 \007read may be incomplete - beware!\007
70 line too long: lno = 
71 line too long: lno = 
72 too long
73 tab count\n
75 Operation not supported on socket
