$set 1
1 %s: Language %s unknown.  Proceeding with default.\n
2 %s: permission denied\n
3 aborted, can't open the fifo file %s\n
4 restart, and read the configuration file
5 aborted, can't open the fifo file %s\n
6 aborted, can't read from fifo file %s\n
7 aborted, configfile %s open for read error\n
8 aborted, action file %s open for write error\n
9 aborted, no event line specified in %s for line %d "%s"\n
10 aborted, no configuration specified in %s\n
11 aborted, event %s is duplicated specified in file %s\n
12 aborted, configfile %s syntax error in line "%s"\n
13 Temperature is back to the normal machine operating range.
14 ***** OVERTEMP_CRIT WARNING *****
15 Temperature exceeded the normal operation threshold.  Correct the over-temperature condition.
16 ***** OVERTEMP_EMERG WARNING *****
17 Temperature exceeded the OVERTEMP_CRIT threshold.  Correct the over-temperature condition immediately.
18 Internal error: Invalid value %d passed to %s.
19 terminated by signal %d\n
20 usage: %s [-f configfile]\n
