$set 1
2 Buffer read error
3 Can't find a name\t
4 A copy of an editor buffer of yours was saved when the system went down.\n
5 A copy of an editor buffer of yours was saved when the editor was killed.\n
6 No name was associated with this buffer so it has been named "LOST".\n
7 A copy of an editor buffer of your file "%s"\nwas saved when the system went down.\n
8 A copy of an editor buffer of your file "%s"\nwas saved when the editor was killed.\n
9 This buffer can be retrieved using the "recover" command of the editor.\n
10 An easy way to do this is to give the command "ex -r %s".\n
11 This works for "edit" and "vi" also.\n
