$set 1
1 Usage: find path-list [predicate-list]\n
2 find: cannot get 'pwd'\n
3 find: parsing error\n
4 find: missing conjunction\n
5 find: operand follows operand\n
6 find: cannot find -user %s\n
7 find: cannot find -group %s\n
8 find: cannot create %s\n
9 find: cannot access %s\n
10 find: bad option %s\n
11 find: incomplete statement\n
14 find: cannot stat %s\n
15 find: cannot %s %s\n
16 Can't open /dev/tty to prompt for more media.\n
17 find: can't write %s: %s\n
19 If you want to go on, type device/file name when ready\n
20 User entered a null name for next device file.\n
21 find: can't open %s: %s\n
22 User opened file %s to continue.\n
23 find: bad -type %s\n
24 find: bad -inum value %s\n
25 find: %s requires an argument\n
26 find: %s not terminated with ';'\n
27 find: %s must specify a command to run\n
28 find: invalid mode %s\n
40 more than 16 entries at entry: 
41 entry doesn't start with "(" in short form: 
42 entry doesn't end with ")" in short form: 
43 user name not terminated with dot in entry: 
44 group name not terminated correctly in entry: 
45 user name is null in entry: 
46 group name is null in entry: 
47 invalid user name in entry: 
48 invalid group name in entry: 
49 invalid mode in entry: 
51 unknown error from strtoaclpatt(): 
55 find: 
56 find: invalid file system type %s\n
57 open
58 search
59 find: cannot find -devcid %s\n
60 find: can't chdir back to %s\n
61 find: can't use both -ncpio and -cpio on the same file\n
62 find: cpio I/O failed -- 
63 find: %s creates a cycle\n
64 No error\n
65 out of memory\n
66 unknown file type\n
67 internal buffering error\n
68 file changed size\n
69 unknown error (CPIO_%d)\n
