$set 1
1 usage: gencat [ -l ] catfile files ...\n
2 gencat: %s: Not a catalog file\n
3 gencat: %s: Bad catalog file\n
4 gencat: %s: Bad catalog file\n
5 "%s", line %ld: Bad set number\n
6 "%s", line %ld: Bad set number sequence\n
7 "%s", line %ld: Bad delset number\n
9 "%s", line %ld: No message number\n
10 "%s", line %ld: Message too long\n
12 "%s", line %ld: Bad message number\n
13 "%s", line %ld: Bad message number sequence\n
14 "%s", line %ld: Bad delimiter\n
15 "%s", line %ld: Bad message\n
16 "%s", line %ld: Bad delete message number\n
18 "%s", line %ld: Missing quote character\n
