$set 1
1 grep  [-E|-F] [-cbilnqsvx] [-e expression [-e expression] ... | -f file]\n [expression] [file ...]\n egrep [-cbilnqsvx] [-e expression [-e expression] ... | -f file]\n [expression] [file ...]\n fgrep [-cbilnqsvx] [-e expression [-e expression] ... | -f file]\n [expression] [file ...]
2 %s: can't open %s\n
3 usage:\n %s\n
4 %s: can't open %s\n
5 %s: RE error %d: 
101 Unknown regexp error code!!
102 Invalid collation element referenced.
103 Trailing \\ in pattern.
104 \\n found in pattern.
105 Too many \\( \\) pairs or ( ) nested too deep.
106 Number in \\digit invalid or out of range.
107 [ ] imbalance.
108 \\( \\) or ( ) imbalance.
109 \\{ \\} imbalance.
110 Invalid collation endpoint in [ - ] expression.
111 Regular expression overflow.
112 Number too large in \\{ \\} construct.
113 Invalid number in \\{ \\} construct.
114 More than 2 numbers in \\{ \\} construct.
115 First number exceeds second in \\{ \\}.
116 Invalid character class named.
117 No remembered search string.
118 Duplication operator in illegal position.
119 Empty expression specified.
