$set 1
1 Usage: ln [-f] [-i] [-s] f1 f2\n       ln [-f] [-i] [-s] f1 ... fn d1\n
2 Usage: ln [-f] [-i] f1 f2\n       ln [-f] [-i] f1 ... fn d1\n
3 ln: cannot access %s\n
4 ln: <%s> directory\n
5 ln: %s/%s: Name too long\n
6 ln: %s and %s are identical\n
7 ln: %s: %o%c mode (%s/%s) 
8 ln: cannot unlink %s\n
9 ln: different file system\n
10 ln: no permission for %s\n
11 ln: too many links to %s\n
12 ln: %s exists\n
