$set 1
1 cannot set LC_COLLATE\n
2 cannot set LC_CTYPE\n
3 cannot reopen stdin\n
4 Usage:\tlocaledef [-c] [-f charmap_file] [-i input_file] locale_name\n
5 or\tlocaledef -d [-o format] locale_name\n
6 or\tlocaledef -n input_file\n
7 can't open 'debug' file\n
9 cant open input file %s\n
10 no 'langname' specification\n
11 no 'langid' specification\n
12 specification conflict in 'langname' and 'langid'\n
13 specification conflict in 'isfirst' and 'byte_chars'\n
14 WARNING: sequence specification will be ignored\n
15 LC_ALL category exceeds the maximum size allowed\n
16 LC_MESSAGES category exceeds the maximum size allowed\n
17 LC_COLLATE category exceeds the maximum size allowed\n
18 LC_CTYPE category exceeds the maximum size allowed\n
19 LC_MONETARY category exceeds the maximum size allowed\n
20 LC_NUMERIC category exceeds the maximum size allowed\n
21 LC_TIME category exceeds the maximum size allowed\n
22 can't create 'locale.inf' file\n
23 localedef Error: invalid keyword on line %d\n
25 localedef Error: invalid character on line %d\n
26 localedef Error: invalid statement on line %d\n
27 localedef Error: invalid expression on line%d\n
28 localedef Error: invalid range on line %d\n
29 localedef Error: invalid langname length on line  %d\n
30 localedef Error: invalid langid number on line %d\n
31 localedef Error: invalid language name length in langname on %d\n
32 localedef Error: invalid territory name length in langname %d\n
33 localedef Error: invalid codeset name length in langname on line %d\n
34 localedef Error: invalid revision string length on line %d\n
36 localedef Error: invalid character code on line  %d\n
37 localedef Error: invalid isfirst character code on line %d\n
38 localedef Error: invalid issecond character code on line %d\n
39 localedef Error: invalid code_scheme name length %d\n
40 localedef Error: invalid code_cscheme name %d\n
41 localedef Error: invalid cswidth string length %d\n
42 localedef Error: invalid cswidth string format %d\n
43 localedef Error: invalid langinfo string length %d\n
44 localedef Error: invalid monetary string length  %d\n
45 localedef: invalid numeric string length %d\n
46 localedef Error: invalid modifier string length %d\n
47 localedef Error: malloc() failed \n
48 localedef Error: priority queue overflow \n
49 localedef Error: yes and no strings can't have the same first char %d\n
50 localedef Error: invalid era string length %d\n
51 localedef Error: invalid era string format %d\n
52 localedef Error: too many era strings are specified %d\n
53 localedef Error: Specified symbol not found %d\n
58 localedef Error: charmap file not found \n
60 localedef Error: symbol duplicated %d\n
63 localedef Error: more than COLL_WEIGHTS_MAX specified on line %d\n
68 localedef warning: Specified symbol not found %d\n
72 localedef warning: keyword not supported %d\n
73 localedef warning: Incorrect ctype initialization - corrective action taken \n
74 specification conflict in 'langname' and 'langid'
75 WARNING: user defined language should have langid in the range of 901 to 999\n
76 user defined language should have langid in the range of 901 to 999
77 specification conflict in 'langname' and 'langid'
78 read error on file: 
79 can't lseek file: 
80 cannot open temporary file %s\n
81 Error interpreting charmap file\n
82 locale Error: invalid line in LC_COLLATE category: %d\n
