$set 1
1 mail: can't open %s for writing\n
2 usage: mail [+] [-epqr] [-f file]\n
3        mail [-dt] persons\n
4 mail: can't allocate hmbox
5 mail: can't allocate mailfile
6 mail: permission denied!\n
7 mail: cannot open %s\n
8 No mail.\n
9 Check mode and group id of mail file.\n
10 Your mail is being forwarded to 
11 %s
12 and your mailbox contains extra stuff\n
13 mail: can't open %s\n
14 usage\n
15 q\t\tquit\n
16 x\t\texit without changing mail\n
17 p\t\tprint\n
18 s [file]\tsave (default mbox)\n
19 w [file]\tsame without header\n
20 -\t\tprint previous\n
21 d\t\tdelete\n
22 +\t\tnext (no delete)\n
23 m user\t\tmail to user\n
24 ! cmd\t\texecute cmd\n
25 invalid command\n
26 mail: cannot append to %s\n
27 mail: cannot save mail\n
28 invalid command\n
29 %s has no value or is not exported.\n
30 !\n
31 mail: can't re-write %s\n
33 mail: can't re-read %s\n
34 copyback:Too many letters\n
35 mail: can't update %s\n
36 mail: can't update %s\n
37 mail: can't update %s\n
38 mail: cannot copy mail back\n
39 new mail arrived\n
40 \007Warning: Too many letters, overflowing letters concatenated\n\n
42 mail: cannot reopen %s for reading\n
43 mail: can't malloc\n
44 mail: cannot create %s\n
45 Mail saved in %s\n
46 Mail saved in %s\n
47 mail: cannot save in dead letter\n
48 header line too long\n
49 null name\n
50 null name\n
51 mail: cannot pipe to mail command\n
52 unbounded forwarding\n
53 mail: can't send to %s\n
54 mail: cannot append to %s\n
55 mail: cannot append to %s\n
56 mail: cannot append to %s\n
57 mail: error signal %d\n
58 mail: can not lock on %s after %d tries\n
59 mail: %s not creatable after %d tries\n
