$set 1
1 panic: 
3 Too much "sourcing" going on.\n
4 "Source" stack over-pop.\n
5 Unmatched "if"\n
$set 2
1 No more mail.\n
2 On last screenful of messages\n
3 On first screenful of messages\n
4 Unrecognized scrolling command "%s"\n
5 Commands are:\n
6 Message %2d:\n
7 Message %2d:\n
8 No value set for "folder"\n
$set 3
1 No messages applicable\n
2 At EOF\n
3 No messages to save.\n
4 No messages to copy.\n
5 [Piped]
6 [Appended]
7 [New file]
8 \nExit status = %d.\n
9 No messages to write.\n
10 [Piped]
11 [Appended]
12 [New file]
13 \nExit status = %d.\n
14 Syntax error: missing %c.\n
15 No file specified.\n
16 At EOF\n
17 No more messages\n
18 No fields currently being ignored.\n
$set 4
1 Command buffer overflow\n
2 No help just now.\n
3 Sorry, can't reply to multiple messages at once\n
4 Empty reply-to field -- replying to author\n
5 Cannot "preserve" in edit mode\n
6 Non-null variable name required\n
7 Must specify a group name.\n
8 "%s": not a group\n
9 No previous file\n
10 Illegal nested "if"\n
11 Unrecognized if-keyword: "%s"\n
12 "Else" without matching "if"\n
13 invalid condition encountered\n
14 "Endif" without matching "if"\n
$set 5
1 pipe command error\n
2 "cmd" not set, ignored.\n
3 No messages to pipe.\n
4 Pipe to: "%s"\n
5 \nExit status = %d.\n
6 Pipe to "%s" failed\n
$set 6
1 Use "." to terminate letter\n
2 Unknown tilde escape.\n
3 (continue)\n
4 ~h: no can do!?\n
5 (continue)\n
6 Interpolate what file?\n
7 %s: directory\n
8 Write what file!?\n
9 No messages to send from!?!\n
10 (continue)\n
11 No help just now.\n
12 -------\nMessage contains:\n
13 (continue)\n
14 (continue)\n
15 (continue)\n
16 File exists\n
17  [appended] %d/%ld\n
18 %s: file exists\n
19 Fatal error in "%s"\n
20 Editor tmp file saved as %s\n
21 "%s" failed!?\n
22 No bytes from "%s" !?\n
23 No appropriate messages\n
24 Interpolating:
25 (continue)\n
26 \n(Interrupt -- one more to kill letter)\n
$set 7
1 %s: file exists\n
$set 8
1 Your mail is being forwarded to %s\n
2 and your mailbox contains extra stuff\n
3 temporary file seek
4 Insufficient memory for %d messages\n
5 Message ghost file read error\n
6 removed\n
7 complete\n
8 "Echo" failed\n
9 "%s": No match\n
10 Buffer overflow expanding "%s"\n
11 "%s": Ambiguous\n
12 mailx: deleted 1 NULL character in mail file\n
13 mailx: deleted %d NULL characters in mail file\n
$set 9
1 Cannot find empty slot for dynamic host entry\n
2 Cannot open %s\n
3 no sysname in %s\n
$set 10
1 No mail.\n
2 No mail for %s\n
3 %s: empty file\n
4 No mail.\n
5 No mail for %s\n
6 Your mail is being forwarded to %s
7 Use "quit" to quit.\n
8 Can't "!" while sourcing\n
9 Unknown command in source: "%s"\n
10 Unknown command: "%s"\n
11 May not execute "%s" while sending\n
12 May not execute "%s" while sourcing\n
13 May not execute "%s" -- message file is read only\n
14 Cannot recursively invoke "%s"\n
15 Illegal use of "message list"\n
16 No applicable messages\n
17 Illegal use of "message list"\n
18 %s requires at least %d arg(s)\n
19 %s takes no more than %d arg(s)\n
20 Unknown argtype
21 Interrupt\n
22 mailx %s  Type ? for help.\n
23 1 message
24 %d messages
25  %d new
26  %d unread
27  %d deleted
28  %d saved
29  [Read only]
$set 11
1 No numbers mixed with *\n
2 Non-numeric second argument\n
3 Unknown colon modifier "%s"\n
4 Can't mix "*" with anything\n
5 No applicable messages.\n
6 No applicable messages from {%s
7 }\n
8 No messages satisfy
9 %d: Invalid message number\n
10 %d: Inappropriate message\n
11 Warning:  only first %d arguments of %s command processed.\n
12 Missing %c\n
13 Too many regrets
14 Bad message number to mark
15 Bad message number to unmark
16 No applicable messages\n
17 Referencing beyond last message\n
18 Referencing before first message\n
19 No applicable messages\n
20 %d: Inappropriate message\n
21 Unknown metachar (%c)\n
$set 12
1 -h needs non-zero number\n
2 usage: mailx [-FU] [-s subject] [-r address] [-h number] address ...\n
3        mailx -e\n
4        mailx [-UHiNn] [-u user]\n
5        mailx -f [-UHiNn] [filename]\n
6 Need -f with -I flag\n
7 Cannot give -f and people to send to.\n
8 The flags you gave are used only when sending mail.\n
9 No mail for %s\n
10 \nInterrupt\n
$set 13
1 Somethings amiss -- no @ or % in arpafix\n
2 Ran out of machine id spots\n
3 Out of machine ids\n
4 Use made of undefined machine id\n
5 Use made of undefined machine id\n
6 No host named "%s"\n
7 net name syntax\n
8 Made up bad net name\n
9 Machine code %c (0%o)\n
10 Sorry.\n
11 Strange arg to optiboth\n
12 ERROR:  unknown internal machine id\n
$set 14
1 You have new mail.\n
2 New mail has arrived.\n
3 Held 1 message in %s\n
4 Held %2d messages in %s\n
5 Saved 1 message in %s\n
6 Saved %d messages in %s\n
7 Thou hast new mail.\n
8 Held 1 message in %s\n
9 Held %d messages in %s\n
$set 15
1 failed to fix up status field\n
2 No recipients specified\n
3 No message !?!\n
4 EOT\n
5 No recipients specified\n
6 No recipients specified\n
7 No message, no subject; hope that's ok\n
8 Null message body; hope that's ok\n
9 . . . message lost, sorry.\n
$set 16
1 String too large
2 No room for space %d\n
3 Internal error
$set 17
1 "%s" is not a user of this system\n
2 ubluit
3 Who are you!?\n
$set 18
1 too long to edit\n
3 too long to edit\n
$set 19
1 "%s": undefined variable\n
2 Out of memory
3 "%s": not a group\n
$set 20
1 rmmail: cannot unlink %s\n
2 rmmail: invalid arguments\n
3 rmmail: cannot stat %s\n
4 rmmail: %s not empty\n
5 rmmail: cannot remove %s - permission denied\n
6 rmmail: bad status\n
$set 21
1 %a %h %d %H:%M
