$set 1
1 Usage: man [ section ] name ...\n
2 or: man -k keyword ...\n
3 or: man -f file ...\n
4 But what do you want from section %s?\n
6 No manual entry for %s.\n
7 No entry for %1$s in section %2$s of the manual.\n
9 Reformatting entry.  Wait...
10  aborted (sorry)\n
11  done\n
12 man: -k what?\n
13 %s: nothing appropriate\n
14 man: -f what?\n
15 %s: not found\n
$set 2
1 whereis [ -sbmu ] [ -SBM dir ... -f ] name...\n
