$set 1
1 Out of memory
2 Device state must be 'online' or 'offline'
3 usage: %s -c [-f] primarydev pstate secondarydev sstate\n
4        %s -u mirrordev ...\n
5        %s -o -p|-s mirrordev ...\n
6        %s -r [-t] mirrordev\n
7        %s -l [device ...]\n
8 Cannot talk to mirror driver
9 Disk mirroring not configured into kernel
10 %s incorrect
11 %s cannot be mirrored
12 %s cannot be mirrored
13 %s and %s cannot be mirrored
14 %s is already in a mirror
15 %s is already in a mirror
16 One section must remain ONLINE
17 %s open, so must be ONLINE
18 %s open, so %s must be OFFLINE
19 %s must not be open
20 Mirror open; %s must be ONLINE
21 %s is being reimaged
22 Offline-access file %s is open
23 Table for reimage does not exist
24 Use uxgen to configure root or swap
25 %s is not a mirror
26 Bad flag or state
27 Bad state combination
28 Some mirror already OFFLINE
29 Cannot find mirrorlog daemon
30 Reimage failed
31 One section must be set ONLINE
32 Too many device names
33 Too many device names
34 %s is not a mirror
35 Nothing to reimage
36 Table for reimage does not exist
37 %s cannot be mirrored\n
38 You must be root to use this option
39 Cannot plock process
