$set 1
1 Usage: 
2  [-dfln] [+linenum | +/pattern] name1 name2 ...\n
3 \n*** %s: directory ***\n\n
4 \n******** %s: Not a text file ********\n\n
6 [Use q or Q to quit]
7 --More--
8 (Next file: %s)
9 (%d%%)
10 [Press space to continue, q to quit]
11 ...skipping %d lines\n
12 ...skipping %d line\n
13 \n***Back***\n\n
14 Cannot open help file
15 "%s" line %d
16 [Not a file] line %d
17 Regular expression botch
18 ...skipping\n
19 \nPattern not found\n
20 Pattern not found
21 exec failed\n
22 \n...Skipping 
23 ...Skipping 
24 to file 
25 back to file 
26 Can't read stderr.\n
27 Line too long
28 No previous command to substitute for
99 \n*** %s: fifo file ***\n\n
