$set 1
1 Usage: mv [-f] [-i] f1 f2\n       mv [-f] [-i] f1 ... fn d1\n       mv [-f] [-i] d1 d2\n
2 %s: Cannot unlink.
3 cannot access
4 %s and %s are identical
5 remove %s? 
6 override protection %o%c for %s? 
8 %s: unknown file type %o
9 %s: can't move sockets across file systems
10 %s: can't move network special files across file systems
11 cannot move "text busy" shared library
12 cannot move non-directory %s to existing directory %s
13 cannot move directory %s to existing non-directory %s
14 cannot set file modification times
15 cannot set file owner or group
16 cannot set file modes
17 cannot write
18 cannot create
19 cannot open
20 mv: %s/%s: Name too long.
21 cannot close
