$set 1
1 converted token %.25s... too long
2 out of space in lookup
3 can't open file %s
4 pushback overflow
5 quoted string %.20s... too long
6 missing " in %.20s
7 token %.20s... too long
8 Unexpected end of input at %.20s
9 Unterminated definition at %.20s
10 out of space in strsave on %s
11 Include not yet implemented
12 Bizarre delimiters at %.20s
13 run terminated due to eqn error\n
14 input line too long: %.20s\n
15 no eqn strings left
16 can't open file %s
17 eqn fatal error: 
18 \nfile %1$s, between lines %2$d and %d\n
19 eqn: 
20 fatal error: 
21 \nfile %1$s, between lines %2$d and %d\n
23 funny type %d in funny
24 \\e
