$set 1
1 "%s" not a right-to-left language\n
2 non-latin mode file with left justification\n
3 latin mode file with right justification\n
4 out of memory\n
5 input buffer overflow\n
6 output buffer overflow\n
7 print width of "%s" exceeds input buffer length\n
8 "%s" invalid print width\n
9 wrap margin of "%s" exceeds input buffer length\n
10 "%s" invalid wrap margin\n
11 wrap margin changed to "%s" (can not exceed print width)\n
12 tab stop of "%s" exceeds input buffer length\n
13 "%s" invalid tab stop\n
14 unable to open input file "%s"\n
15 "%s" invalid justification (l or r)\n
16 "%s" invalid mode (l or n)\n
17 "%s" invalid order (k or s)\n
18 usage: nljust [-aclnt] [-e seq] [-j just] [-m mode] [-o order] [-r margin] [-w width] [-x ck] [files ...]\n
