$set 1
1 error reading data area\n
2 can't find compacted tmp file\n
3 Busy.\n
4 Available.\n
5 Unknown option: 
6 Floating Exception.\n
7  
8  
9 Cannot create temp file.\n
10 Typesetter busy.\n
11 Non-existent macro file (
12 )
13 cannot open file 
14 can't open file 
15 Too many page numbers\n
16 tmp file write error\n
17 can't create data file\n
18 can't create tmp file\n
19 Compaction completed\n
20 Too many macro packages.\n
21 Cannot open suftab.\n
22 can't setup command env\n
23 Can't execute 
24 Non-existent terminal type\n
25 terminal table too big
26 Waiting for Typesetter.\n
27 Troff finished.\n
28 Pipe not created.\n
29 Cannot exec: 
30 too many names for rn
31 Too many string/macro names.\n
32 out of memory for store
33 Out of temp file space.\n
34 Macro read failed\n
35 Bad storage allocation\n
36 too many macro calls
37 out of memory for macro call
38 Core limit reached.\n
39 out of memory for macro call
40 Macro argument too long.\n
41 Cannot divert.\n
42 Too many number registers.\n
43 Divide by zero.\n
44 Cannot plant trap.\n
45 User Abort.
46 Cannot do ev_\n
47 if-else overflow.\n
48 :
49 Line overflow.\n
50 Trap botch.\n
51 Word overflow.\n
52 Exception word list full.\n
53 Zero field width.\n
54 Too many overstriking characters.\n
