$set 1
1 %s: Error reading file %s\n
2 %s: Obsolescent forms and new forms cannot be combined\n
3 %s: Illegal argument for -A option\n
4 %s: Illegal value for -j option\n
5 %s: Illegal value for -N option\n
6 Usage: %s [-v] [-A base] [-j skip] [-N count] [-t type_string]... [file...]\n
7 %s: End of file reached for input: %s\n
8 %s: Invalid argument for -t option\n
9 %s: Invalid numeric modifier\n
10 %s: Invalid type modifier used\n
11 %s: cannot open %s\n
