$set 1
1 Error 0
2 Not owner
3 No such file or directory
4 No such process
5 Interrupted system call
6 I/O error
7 No such device or address
8 Arg list too long
9 Exec format error
10 Bad file number
11 No child processes
12 No more processes
13 Not enough space
14 Permission denied
15 Bad address
16 Block device required
17 Device busy
18 File exists
19 Cross-device link
20 No such device
21 Not a directory
22 Is a directory
23 Invalid argument
24 File table overflow
25 Too many open files
26 Not a typewriter
27 Text file busy
28 File too large
29 No space left on device
30 Illegal seek
31 Read-only file system
32 Too many links
33 Broken pipe
34 Argument out of domain
35 Result too large
36 No message of desired type
37 Identifier removed
38 Unknown error
39 Unknown error
40 Unknown error
41 Unknown error
42 Unknown error
43 Unknown error
44 Unknown error
45 Unknown error
46 Lockf deadlock detection
47 No locks available
48 Unknown error
49 Unknown error
50 Unknown error
51 Not a stream
52 No data
53 Stream ioctl timeout
54 No stream resources
55 Not on the network
56 Package not installed
57 Unknown error
58 Link severed
59 Advertise error
60 Srmount error
61 Error on send
62 Protocol error
63 Unknown error
64 Unknown error
65 Multihop attempted
66 Unknown error
67 Cross mount point
68 Bad message
70 Disk quota exceeded
71 Stale NFS file handle
72 Too many levels of remote in path
73 Unknown error
74 Unknown error
75 Unknown error
76 Unknown error
77 Unknown error
78 Unknown error
79 Unknown error
80 Unknown error
81 Unknown error
82 Unknown error
83 Unknown error
84 Unknown error
85 Unknown error
86 Unknown error
87 Unknown error
88 Unknown error
89 Unknown error
90 Unknown error
91 Unknown error
92 Unknown error
93 Unknown error
94 Unknown error
95 Unknown error
96 Unknown error
97 Unknown error
98 Unknown error
99 Unknown error
100 Unexpected Error
101 Unknown error
102 Unknown error
103 Unknown error
104 Unknown error
105 Unknown error
106 Unknown error
107 Unknown error
108 Unknown error
109 Unknown error
110 Unknown error
111 Unknown error
112 Unknown error
113 Unknown error
114 Unknown error
115 Unknown error
116 Unknown error
117 Unknown error
118 Unknown error
119 Unknown error
120 Unknown error
121 Unknown error
122 Unknown error
123 Unknown error
127 Unknown error
128 Unknown error
129 Unknown error
130 Unknown error
131 Unknown error
132 Unknown error
133 Unknown error
134 Pathname is remote
135 Operation completed at server
136 Unknown error
137 Unknown error
138 Unknown error
139 Unknown error
140 Unknown error
141 Unknown error
142 Unknown error
143 Unknown error
144 Unknown error
145 Unknown error
146 Unknown error
147 Unknown error
148 Unknown error
149 Unknown error
150 Unknown error
151 Unknown error
152 Unknown error
153 Unknown error
154 Unknown error
155 Unknown error
156 Unknown error
157 Unknown error
158 Unknown error
159 Unknown error
160 Unknown error
161 Unknown error
162 Unknown error
163 Unknown error
164 Unknown error
165 Unknown error
166 Unknown error
167 Unknown error
168 Unknown error
169 Unknown error
170 Unknown error
171 Unknown error
172 Unknown error
173 Unknown error
174 Unknown error
175 Unknown error
176 Unknown error
177 Unknown error
178 Unknown error
179 Unknown error
180 Unknown error
181 Unknown error
182 Unknown error
183 Unknown error
184 Unknown error
185 Unknown error
186 Unknown error
187 Unknown error
188 Unknown error
189 Unknown error
190 Unknown error
191 Unknown error
192 Unknown error
193 Unknown error
194 Unknown error
195 Unknown error
196 Unknown error
197 Unknown error
198 Unknown error
199 Unknown error
200 Unknown error
201 Unknown error
202 Unknown error
203 Unknown error
204 Unknown error
205 Unknown error
206 Unknown error
207 Unknown error
208 Unknown error
209 Unknown error
210 Unknown error
211 Unknown error
212 Unknown error
213 Unknown error
214 Unknown error
215 Unknown error
216 Unresolved external
217 Socket operation on non-socket
218 Destination address required
219 Message too long
220 Protocol wrong type for socket
221 Protocol not available
222 Protocol not supported
223 Socket type not supported
224 Operation not supported
225 Protocol family not supported
226 Address family not supported by protocol family
227 Address already in use
228 Can't assign requested address
229 Network is down
230 Network is unreachable
231 Network dropped connection on reset
232 Software caused connection abort
233 Connection reset by peer
234 No buffer space available
235 Socket is already connected
236 Socket is not connected
237 Can't send after socket shutdown
238 Too many references: can't splice
239 Connection timed out
240 Connection refused
241 Remote peer released connection
242 Host is down
243 No route to host
244 Unknown error
245 Operation already in progress
246 Operation now in progress
247 Operation would block
248 Directory not empty
249 File name too long
250 Too many levels of symbolic links
251 No message of desired type
252 Function is not available
253 Unknown error
