$set 1
1 Unknown error
2 Invalid regular expression
3 
4 
5 
6 
7 
8 
9 
10 
11 invalid number in \\{ \\} construct
12 
13 
14 
15 
16 number too large in \\{ \\} construct
17 
18 
19 
20 regexec() failed to match
21 Invalid collating element referenced
22 Trailing \\ in pattern
23 Invalid endpoint in range expression
24 Invalid character class type referenced
25 Number in \\digit invalid or in error
26 ?, *, or + not preceded by valid regular expression
27 no expression within ( ) or on one side of an |
28 
29 
30 
31 
32 
33 
34 
35 
36 \\n found before end of pattern and REG_NEWLINE flag not set
37 
38 
39 
40 
41 no remembered search string
42 \\( \\) or ( ) imbalance
43 more than nine \\( \\) pairs or nesting level too deep
44 more than 2 numbers in \\{ \\} construct
45 \\{ \\} imbalance
46 first number exceeds second in \\{ \\} construct
47 
48 
49 [ ] imbalance
50 out of memory
51 out of memory while matching expression
