$set 1
1 Usage: rm [-Rfir] file ...\n
2 %s: cannot remove .\n
3 rm: %s non-existent\n
4 directory %s: ? 
5 rm : cannot read 
6 rm: %s directory\n
7 %s: %o mode ? 
8 rm: %s not removed.  
10 rm: %s: Name too long\n
11 rm: %s/%s: Name too long\n
12 rm: directory %s not removed.  
13 Cannot remove mountable directory\n
14 Directory not empty\n
15 Cannot remove current directory\n
16 Directory name too long\n
17 Usage: rmdir [-fip] dirname ...\n
18 rmdir: %s: 
19 rmdir: %s: %s not removed; 
20 rmdir: %s: Whole path removed.\n
21 rm: cannot stat 
22 rmdir: %s: %s not removed\n
