$set 1
1 directory `%1$s' specified as `%2$c' keyletter value
2 d has no argument
3 value after %c flag
5 bad list format
6 element in list out of range
7 unknown flag
8 flag twice
9 f has no argument
10 value after %c flag
11 No application with application flag.
12 No .FRED file exists for this application.
13 floor not numeric
14 floor out of range
15 ceiling not numeric
16 ceiling out of range
17 no default sid
18 flag %c has no value
19 bad list format
20 element in list out of range
21 unknown flag
22 flag twice
23 r out of range
24 bad a argument
25 too many 'a' keyletters
26 bad e argument
27 too many 'e' keyletters
28 unknown key letter
29 key letter twice
30 missing file arg
31 illegal use of 'y' or 'm' keyletter
32 more than one file
33 USER ID not in password file
34 directory named with `i' keyletter
35 Can't have two verification routines.
36 MRs not allowed
37 MRs required
38 r only allowed with i
39 t has no argument
40 d not allowed with n
41 file %s exists
42 file %s does not exist
43 cannot fork, try again
44 cannot execute '%s'
45 corrupted file
46 cannot create lock file
47 file name too long
48 Bad CMR number(s).
49 invalid MRs
50 Can't use -fz with -fv.
51 no id keywords
52 invalid id keywords
53 No id keywords
54 %1$s illegal data on line %2$d
55 date and time created
56 by
212 not an SCCS file
$set 2
1 unknown key letter
2 value after %c arg
3 key letter twice
4 missing file arg
5 can't have both -p and -c
6 p-file exists
7 sid doesn't exist
8 nothing to do
9 can't create temporary s.file:
10 can't create temporary file
11 temporary s.file: %s nonexistant??
$set 3
1 unknown key letter
2 value after %c arg
3 key letter twice
4 missing file arg
5 cannot create lock file
6 invalid sid in p-file
7 no id keywords
8 invalid id keywords
9 No id keywords
12 cannot execute '%s'
13 '%1$s' failed, re-trying, segmentation = %2$d
14 diff failed
15 %u inserted
16 %u deleted
17 %u unchanged
18 MRs not allowed
19 invalid MRs
20 MRs required
21 input CMR's ignored
22 Delta denied due to CMR difficulties
23 AUTO NULL DELTA
24 ambiguous `r' keyletter value
25 missing -r argument
26 login name or SID specified not in p-file
29 cannot fork, try again
33 internal error in delta/enter()
34 internal error in delta/enter()
35 internal error in delta/enter()
351 fputs could not write to file
$set 4
1 CMR list is too long.
2 r out of range
3 bad date/time
4 unknown key letter
5 value after %c arg
6 key letter twice
7 missing file arg
8 e not allowed with m
9 User ID not in password file
10 cannot create lock file
11 serial number too large
12 writable `%s' exists
13 %u lines
14 no id keywords
15 invalid id keywords
16 No id keywords
17 bad SID calculated in newsid()
18 %s already included
19 %s already excluded
20 internal error in get/enter()
21 getcwd failed
22 cannot change directory
26 being edited: `%s'
27 new delta
28 nonexistent sid
29 Background CASSI get with no CMRs
30 Background CASSI get with invalid CMR
31 Input Comma Separated List of CMRs:
32 ?Too many CMRs.
33 Must enter at least one valid CMR.
34 Re-enter invalid CMRs, or press return.
101 %y/%m/%d
102 %m/%d/%y
103 %H:%M:%S
104 %y/%m/%d
105 %m/%d/%y
106 %H:%M:%S
351 fputs could not write to file
$set 5
1 help: Could not exec: %1$s.  Errno=%2$d
$set 6
1 invalid sid
2 invalid cutoff date
3 value after %c arg
4 unknown key letter
5 key letter twice
6 missing file arg
7 can't specify cutoff date and SID
8 must specify -e or -l with -c
9 yes
10 no
11 none
27 getcwd failed
28 cannot change directory
29 getcwd failed
30 cannot change directory
31 nonexistent SID
32 premature eof
33 cannot fork, try again
34 cannot execute '%s'
35 (none)
36 branch
37 ceiling\t%s
38 default SID\t%s
39 floor\t%s
40 id keywd err/warn\t%s
41 joint edit
42 locked releases\t%s
43 module\t%s
44 null delta
45 csect name\t%s
46 type\t%s
47 validate MRs\t
$set 7
1 r has no sid
2 unknown key letter
3 key letter twice
4 Cassi not compatable with cmrs on command line
5 missing file arg
6 bad invocation
7 User ID not in password file
8 missing r
9 file %s does not exist
10 cannot create lock file
11 nonexistent sid
12 you are neither owner nor '%s'
13 not a 'leaf' delta
14 MRs not allowed
15 invalid MRs
16 invalid use of 'z' flag \n CASSI incompatablity
17 uneditable cmr for CASSI controlled file- Change not allowed
18 bad cdc replace of cmr's (CASSI)
19 delta specified has delivered MR
20 *** CHANGED *** 
21 only one cmr left for this delta no change possible
22 do you want to delete %s
24 %s  is not editable now
25 No fred file found- see sccs administrator
26  %s is not editable
27 CASSI msg not writable
28 %1$s chpost %2$s q %3$s sw MID=%4$s MFS=%5$s MPA=%6$s q q
29 Cassi BD/source not writeable
30 being edited -- sid is in p-file
31 *** LIST OF DELETED MRS ***
$set 8
1 unknown key letter
2 value after %c arg
3 key letter twice
4 missing file arg
5 cannot create lock file
6 cannot fork, try again
7 SID must be specified
8 login name not in p-file
9 specified SID not in p-file
10 No outstanding deltas for: %s
$set 9
1     %1$s: %2$cM%3$c, -m mismatch
2     %1$s: %2$cY%3$c, -y mismatch
3     %s: SID nonexistent
4     %s: SID invalid or ambiguous
5     %s: can't open file or file not SCCS
6     %s: corrupted SCCS file\n
7     %s: Unknown or duplicate keyletter argument
8     %s: missing file argument
11 expected
12 or
13 delta creation date out of sequence or in the future
14 illegal control line
15 unexpected end of file
16 checksum error
$set 10
1 unknown command on line %d
2 `%s' never used
3 `%s' never declared
4 `%s' never assigned a value
5 `if' with no matching `end'
6 syntax on line %d
7 `%1$s' declared twice on line %2$d
8 ERROR:%s
9 err statement on line %d
10 `end' without matching `if' on line %d
11 Message(%1$d):%2$s
13 syntax on line %d
14 parenthesis error on line %d
15 invalid operator on line %d
16 non-numerical value on line %d
17 out of space [line %d]
18 unmatched `%1$c' on line %2$d
19 invalid keyword name on line %d
20 out of space
21 keyword name too long on line %d
22 syntax on line %d
23 unmatched `%1$c%2$c' on line %3$d
$set 11
1 can't open %s
$set 12
11 Pfile non existant at deltack 
12 no application found with -fz flag
13 no FRED file or system name in admin directory 
15 ***CASSI REPORTS ERROR: no CMRS in pfile: %s
16 CMRs not on P.file -serious inconsistancy
17 ***CASSI REPORTS ERROR: no CMRS at sd
18 no CMR's left, delta forbidden
19 the CMRs for this delta now are:
20 OK ??
24 you must input a least 1 valid cmr number
25 enter new CMR number or 'CR' 
26  \n duplicate CMR number ignored
27  \n invalid CMR ignored 
28  \n to many CMRs added no more allowed 
29  \n CMR number to delete or (CR) ? 
30 \n only one CMR left can't delete more
31 \n not on list request ignored
32 ***CASSI REPORTS ERROR: can't write to FRED : %s
33  Cassi Interface Msg not writable
34 %1$s chpost %2$s q %3$s %4$s MID=%5$s MFS=%6$s MPA=%7$s q q
35 ***CASSI REPORTS ERROR: can't write to BD/source : %s
36 Cassi BD/source not writeable
37 got to bad FRED file %s
101 invalid sid
111 clock set wrong!!!
112 Clock may be set wrong!
121 MRs? 
122 comments? 
123 standard input specified w/o -y and/or -m keyletter
124 line too long
125 response too long
126 cannot fork; try again
127 too many MRs
128 MR number too long
129 MR number too long
130 out of space
141 Included:
142 Excluded:
151 bad range
152 delta list syntax
161 format error at line %u
171 premature eof
172 corrupted file
181 not authorized to make deltas
182 release %1$u < %2$u (floor)
183 release %1$u > %2$u (ceiling)
184 SCCS file locked against editing
185 release `%d' locked against editing
191 bad p-file format
204 premature eof
211 too long
212 not an SCCS file
213 more than one link
221 file longer than 99999 lines
321 OUT OF SPACE
324 ffree: Pointer not pointing to allocated area
331 directory `%s' nonexistent
341 no file
342 `%s' nonexistent
343 directory `%s' unwritable
344 no space!
345 write error
346 errno = %1$d, function = `%2$s'
$set 13
2 There is not a place to look for help on the subject of %s\n
3 There is not any help available on the subject of %s\n
4 What is the message number or SCCS command name? 
