$set 1
1 un/used/avail 
101 newline or ;
201 got signal #%d\n
203 Memory fault in shell: cleaning up.
204 cannot trap 11
205 cannot trap 18
301 unlinking 
401 hits\tcost\tcommand\n
402  is a shell builtin\n
403  is a function\n
404  not found\n
405  is hashed (
406  is a shell builtin\n
407  is 
601 bad option(s)
602 you have mail\n
603 no space
604 no stack space
605 syntax error
606 unknown signal
607 bad number
608 parameter null or not set
609 parameter not set
610 bad substitution
611 cannot create
612 fork failed - too many processes
613 cannot fork: no swap space
614 restricted
615 cannot make pipe
616 cannot open
617  - core dumped
618 arg list too long
619 text busy
620 too big
621 cannot execute
622 not found
623 bad file number
624 cannot shift
625 bad directory
626 bad trap
627 is read only
628 is not an identifier
629 Bad ulimit
630 cannot return when not in function
631 cannot export functions
632 cannot unset
633 no home directory
634 execute permission denied
635 sh error: pwd too long
636 unknown operator 
637 end of file
638  unexpected
639  at line 
640 Hangup
641 Quit
642 Illegal instruction
643 Trace/BPT trap
644 abort
646 EMT trap
647 Floating exception
648 Killed
649 Bus error
650 Memory fault
651 Bad system call
652 Alarm call
653 Terminated
654 Signal 16
655 Signal 17
656 Child death
657 Power Fail
658 export
659 readonly
660 Executable file incompatible with hardware
661 sigemptyset() failed
662 sigprocmask() failed
663 sigdelset() failed
701 pwd: cannot stat ..
702 pwd: cannot open ..
703 pwd: read error in ..
801 execa failed, t=%s\n
802 ptrace: 
803 sh internal 2K buffer overflow
804 to_tcharn buffer overflow
901 ] missing
902 argument expected
903 ) expected
1001 Usage: netunam  network_special_file  login_string
1002 invalid remote login.  errnet = 
1003 remote node not answering.  errnet = 
1004 invalid network special file.  errno = 
1005 unknown builtin\n
1006 cannot fork: errno = 
1007 unsupported network call
1101 sh internal 2K buffer overflow
1102 sh internal 2K buffer overflow
