$set 1
1 invalid use of command line options
3 path name too long: 
4 too many keys
5 can check only 1 file
6 allocation error before sort
7 can't locate temp
8 allocation error before merge
9 warning: missing NEWLINE added at EOF
10 warning: missing NEWLINE added at end of input file 
11 fatal: record too large
12 sorting
13 merging
14 warning: missing NEWLINE added at EOF
15 fatal: line too long
18 can't create 
19 can't create 
20 can't open 
21 warning: -d option ignored for multibyte languages
22 warning: -f option ignored for multibyte languages
23 warning: -l not required, ignored
24 warning: -i option ignored for multibyte languages
25 read error on 
26 write error while 
