$set 1
1 Tar: cannot create temporary file (%s)\n
2 Invalid blocksize. (Max %d)\n
3 tar: %c: unknown option\n
4 tar: blocksize %d too big, can't get memory\n
5 Can only create standard output archives\n
6 tar: cannot open %s\n
7 tar: usage  tar [-]{txruc}[ONvVwAfblHhm{op}][0-7[lmh]] [tapefile] [blocksize] file1 file2...\n
8 tar: usage  tar [-]{txruc}[ONvVwfblHhm{op}][0-7[lmh]] [tapefile] [blocksize] file1 file2...\n
9 tar: usage  tar [-]{txruc}[ONvVwAfblhm{op}][0-7[lmh]] [tapefile] [blocksize] file1 file2...\n
10 tar: usage  tar [-]{txruc}[ONvVwfblhm{op}][0-7[lmh]] [tapefile] [blocksize] file1 file2...\n
11 tar: usage  tar [-]{txruc}[ONvVwAfblm{op}][0-7[lmh]] [tapefile] [blocksize] file1 file2...\n
12 tar: usage  tar [-]{txruc}[ONvVwfblm{op}][0-7[lmh]] [tapefile] [blocksize] file1 file2...\n
13 Attempt to create archive of no files. Nothing dumped.\n
14 Missing links to %s\n
15 directory checksum error\n
16 tar: cannot stat %s.  Not dumped.\n
17 Optional acl entries for <%s> not dumped\n
18 tar: %s: directory read error\n
19 tar: %s: symbolic link too long\n
20 tar: can't read symbolic link 
21 a %1$s symbolic link to %2$s\n
22 a %s 0 blocks\n
23 tar: %s: cannot open file\n
24 a %1$s link to %2$s\n
25 Out of memory. Link information lost\n
26 a %1$s %2$ld blocks\n
27 %s: file changed size\n
28 tar: %s is not a file. Not dumped\n
29 tar: %s: symbolic link failed: 
30 x %1$s symbolic link to %2$s\n
31 %s: cannot link\n
32 %1$s linked to %2$s\n
33 tar: %s couldn't create character device\n
34 x %s, 0 bytes, 0 blocks, character device\n
35 tar: %s couldn't create block device\n
36 x %s, 0 bytes, 0 blocks, character device\n
37 tar: %s couldn't create fifo \n
38 x %s, 0 bytes, 0 blocks, fifo\n
39 tar: %s creating as regular file.\n
40 tar: %s - cannot create\n
41 x %1$s, %2$ld bytes, %3$ld tape blocks\n
42 tar: %s: HELP - extract write error\n
43 tar: chmod failed
44 tar: chown failed
45  linked to %s
46  symbolic link to %s
47 %b %2d %H:%M %Y
48 tar: couldn't get uname for uid %d\n
49 tar: couldn't get gname for gid %d\n
51 tar: pwd failed
52 tar: pwd depth limit exceeded!\n
53 Tar: tape read error\n
54 Tar: tape blocksize error\n
55 Tar: blocksize = 0; broken pipe?\n
56 Tar: blocksize = %d\n
57 Tar: error! blocksize changed\n
58 Tar: tape write error\n
59 tar: %s: pathname too long\n
60 tar: %s: prefix too long\n
61 tar: %s: file name too long\n
62 %s: file name too long\n
63 Tar: tape error (%d)\n
64 Tar: error on new volume\n
65 Can't open /dev/tty to prompt for more media.\n
66 Tar: end of tape\n
67 Tar: to continue, enter device/file name when ready or null string to quit.\n
68 User entered a null name for next device file.\n
69 Tar: couldn't open %s\n
70 User opened file %s to continue.\n
71 tar: %s couldn't create directory \n
72 tar: %s: link to name too long\n
73 tar: %s: cannot access file\n
74 tar: Out of memory. Cannot detect symbolic link loops\n
75 tar: Loop of symbolic links detected, tar terminated\n
76 tar: Cannot change directory to '%s'\n
77 tar: Path '%s' skipped\n
78 tar: option  not supported for QIC devices %s\n
79 tar: Cannot close %s\n
80 tar: Cannot read/write over NFS\n
