$set 1
1 Can't open file
2 Misspelled global option
3 Illegal option
4 bad table specification character
5 too many lines in specification
6 no specification
7 dot not last character on format line
8 tried to widen table in T&, not allowed
9 first column can not be S-type
10 warning: can't span a-type cols, changed to l\n
11 warning: can't span n-type cols, changed to c\n
12 first row can not contain vertical span
13 too many columns in table
14 Nonterminated font name
15 point size too large
16 point size unreasonable
17 vertical spacing value too large
18 column width too long
19 EOF reading table specification
20 too long spec line
21 Couldn't get memory
22 Vertical spanning in first row not allowed
23 Table at line %1$d file %2$s is too wide - \\n(TW units\n
24 %1$s: line %2$d: Data ignored on table line %3$d\n
25 Wierd.  No data in table.
26 Wierd.  No real lines in table.
27 Too many characters in table
28 no space for characters
29 no space for vectors
30 couldn't find characters to use for delimiters
31 \n%1$s: line %2$d: %3$s\n
32 tbl quits\n
33 run terminated due to error condition detected by tbl preprocessor\n
34 too much backup
35 unexpected EOF
36 Too many text block diversions
37 Too many columns for registers
