$set 1
1 usage: %s -nstux [-|file] ...\n
2 %s: cannot stat stdout\n
3 %s: cannot open %s\n
4 %s: cannot stat %s\n
5 %s: input %s is output\n
6 %s: close error\n
7 %s: close error\n
8 %s: output error\n
9 %s: state 1 illegal data "%d"\n
10 %s: state 2 illegal data "%d"\n
11 %s: state 2 illegal data "%d"\n
12 %s: state 2 illegal data "%d"\n
13 %s: state 2 illegal data "%d"\n
14 %s: state 3 illegal data "%d"\n
15 %s: state 3 illegal data "%d"\n
16 %s: state 3 illegal data "%d"\n
17 %s: state 3 illegal data "%d"\n
18 %s: abnormal termination from state %d\n
