$set 1
1 Usage: write user [terminal]\n
2 Usage: write user [terminal]\n
3 I cannot determine your terminal name. No reply possible.\n
4 %1$s is logged on more than one place.\nYou are connected to "%2$s".\nOther locations are:\n
5 %1$s is logged on more than one place.\nYou are connected to "%2$s".\nOther locations are:\n
6 Permission denied.\n
7 %1$s is not at "%2$s".\n
8 Permission denied.\n
9 %s is not logged on.\n
10 Cannot determine who you are.\n
11 Warning: You have your terminal set to "mesg -n". No reply possible.\n
12 \n\007\007\007\tMessage from %1$s (%2$s) [ %3$s ] ...\n
13 Can no longer write to %s\n
14 Unable to fork.  Try again later.\n
15 Timeout trying to open %1$s's line(%2$s).\n
16 <EOT>\n
17 %a %h %d %H:%M:%S
