default:
	: 

install:
	mkdir -p ../../../Filesets.sl/AUDIT/etc/newconfig
	! cp auditrc ../../../Filesets.sl/AUDIT/etc/newconfig/auditrc
	! chmog 544 bin bin ../../../Filesets.sl/AUDIT/etc/newconfig/auditrc
	! chmog 555 bin bin ../../../Filesets.sl/AUDIT/etc/newconfig
	! chmog 555 bin bin ../../../Filesets.sl/AUDIT/etc
	! chmog 555 bin bin ../../../Filesets.sl/AUDIT
	! chmog 555 bin bin ../../../Filesets.sl
